### PR TITLE
feat(sql): add SHOW commands for ACL

### PR DESCRIPTION
**Pull request by marregui**
Complementary to https://github.com/questdb/questdb-enterprise/pull/86

### CODE REVIEW

**Comment by ideoma** [comment]
#### [PR Coverage check]

:disappointed: **fail** : 0 / 4 (00.00%)




#### file detail

|   |path|covered line|new line|coverage|
|----|----|----|----|----|
|:large_blue_circle:|io/questdb/cairo/security/ReadOnlySecurityContext.java|0|2|00.00%|
|:large_blue_circle:|io/questdb/cairo/security/AllowAllSecurityContext.java|0|2|00.00%|

**Comment by ideoma** [comment]
#### [PR Coverage check]

:disappointed: **fail** : 0 / 4 (00.00%)




#### file detail

|   |path|covered line|new line|coverage|
|----|----|----|----|----|
|:large_blue_circle:|io/questdb/cairo/security/ReadOnlySecurityContext.java|0|2|00.00%|
|:large_blue_circle:|io/questdb/cairo/security/AllowAllSecurityContext.java|0|2|00.00%|

**Comment by ideoma** [comment]
#### [PR Coverage check]

:disappointed: **fail** : 0 / 4 (00.00%)




#### file detail

|   |path|covered line|new line|coverage|
|----|----|----|----|----|
|:large_blue_circle:|io/questdb/cairo/security/ReadOnlySecurityContext.java|0|2|00.00%|
|:large_blue_circle:|io/questdb/cairo/security/AllowAllSecurityContext.java|0|2|00.00%|

**Comment by ideoma** [comment]
#### [PR Coverage check]

:heart_eyes: **pass** : 6 / 6 (100.00%)




#### file detail

|   |path|covered line|new line|coverage|
|----|----|----|----|----|
|:large_blue_circle:|io/questdb/cairo/security/DenyAllSecurityContext.java|2|2|100.00%|
|:large_blue_circle:|io/questdb/cairo/security/ReadOnlySecurityContext.java|2|2|100.00%|
|:large_blue_circle:|io/questdb/cairo/security/AllowAllSecurityContext.java|2|2|100.00%|

**Comment by ideoma** [comment]
#### [PR Coverage check]

:heart_eyes: **pass** : 6 / 6 (100.00%)




#### file detail

|   |path|covered line|new line|coverage|
|----|----|----|----|----|
|:large_blue_circle:|io/questdb/cairo/security/DenyAllSecurityContext.java|2|2|100.00%|
|:large_blue_circle:|io/questdb/cairo/security/ReadOnlySecurityContext.java|2|2|100.00%|
|:large_blue_circle:|io/questdb/cairo/security/AllowAllSecurityContext.java|2|2|100.00%|

**Comment by ideoma** [comment]
#### [PR Coverage check]

:heart_eyes: **pass** : 6 / 6 (100.00%)




#### file detail

|   |path|covered line|new line|coverage|
|----|----|----|----|----|
|:large_blue_circle:|io/questdb/cairo/security/DenyAllSecurityContext.java|2|2|100.00%|
|:large_blue_circle:|io/questdb/cairo/security/ReadOnlySecurityContext.java|2|2|100.00%|
|:large_blue_circle:|io/questdb/cairo/security/AllowAllSecurityContext.java|2|2|100.00%|

**Review by glasstiger — APPROVED** [review]

**Comment by glasstiger** [comment]
we could expand `authorizeListUsers()` and `authorizeUserDetails()` to separate methods, such as `authorizeShowUsers()`, `authorizeShowGroups()`, `authorizeShowServiceAccounts()` and so on...
let's do it in a separate PR.

**Review by glasstiger — APPROVED** [review]

**Comment by ideoma** [comment]
#### [PR Coverage check]

:heart_eyes: **pass** : 24 / 24 (100.00%)




#### file detail

|   |path|covered line|new line|coverage|
|----|----|----|----|----|
|:large_blue_circle:|io/questdb/cairo/security/DenyAllSecurityContext.java|8|8|100.00%|
|:large_blue_circle:|io/questdb/cairo/security/ReadOnlySecurityContext.java|8|8|100.00%|
|:large_blue_circle:|io/questdb/cairo/security/AllowAllSecurityContext.java|8|8|100.00%|

**Pull request merged**
