### PR TITLE
docs(core): benchmarks and examples for JavaZone 2022

### PR DESCRIPTION
**Pull request by bluestreak01**
I created simple Ping/Pong server and client to showcase `IODispatcher` API. While doing that I want to keep examples clean and simple and I had to undertake some refactoring.

Specifically I introduced inheritance to deal with code duplication during bootstrap. I removed the burden of generating `affinity` array correctly when affinity wasn't important. This helped to remove code duplication even further.

### CODE REVIEW

**Comment by questdb-butler** [comment]
<table>
  <thead>
    <tr>
      <th width="50"></th>
      <th width="100%" data-danger-table="true">Fails</th>
    </tr>
  </thead>
  <tbody><tr>
      <td>:no_entry_sign:</td>
      <td>

  Please update the PR title to match this format:
`type(subType): description`

Where `type` is one of:
`feat`, `fix`, `chore`, `docs`, `style`, `refactor`, `perf`, `test`, `build`, `ci`, `chore`, `revert`

And: `subType` is one of:
`build`, `sql`, `log`, `mig`, `core`, `ilp`, `pgwire`, `http`, `conf`

For Example:

```
perf(sql): improve pattern matching performance for SELECT sub-queries
```
  </td>
    </tr>
  </tbody>
</table>




<p align="right">
  Generated by :no_entry_sign: <a href="https://danger.systems/js">dangerJS</a> against b3f34510ad48e638200f438c6cbaa953b107187c
</p>

**Comment by ideoma** [comment]
#### [PR Coverage check]

:heart_eyes: **pass** : 56 / 66 (84.85%)




#### file detail

|   |path|covered line|new line|coverage|
|----|----|----|----|----|
|:large_blue_circle:|io/questdb/std/Chars.java|0|2|00.00%|
|:large_blue_circle:|io/questdb/std/str/DirectUnboundedByteSink.java|0|5|00.00%|
|:large_blue_circle:|io/questdb/network/AbstractMutableIOContext.java|8|11|72.73%|
|:large_blue_circle:|io/questdb/cutlass/pgwire/PGWireServer.java|5|5|100.00%|
|:large_blue_circle:|io/questdb/cutlass/http/HttpConnectionContext.java|3|3|100.00%|
|:large_blue_circle:|io/questdb/cutlass/line/tcp/LineTcpReceiver.java|13|13|100.00%|
|:large_blue_circle:|io/questdb/cutlass/http/HttpServer.java|2|2|100.00%|
|:large_blue_circle:|io/questdb/network/MutableIOContextFactory.java|15|15|100.00%|
|:large_blue_circle:|io/questdb/cutlass/pgwire/PGConnectionContext.java|10|10|100.00%|

**Comment by ideoma** [comment]
#### [PR Coverage check]

:heart_eyes: **pass** : 56 / 66 (84.85%)




#### file detail

|   |path|covered line|new line|coverage|
|----|----|----|----|----|
|:large_blue_circle:|io/questdb/std/Chars.java|0|2|00.00%|
|:large_blue_circle:|io/questdb/std/str/DirectUnboundedByteSink.java|0|5|00.00%|
|:large_blue_circle:|io/questdb/network/AbstractMutableIOContext.java|8|11|72.73%|
|:large_blue_circle:|io/questdb/cutlass/pgwire/PGWireServer.java|5|5|100.00%|
|:large_blue_circle:|io/questdb/cutlass/http/HttpConnectionContext.java|3|3|100.00%|
|:large_blue_circle:|io/questdb/cutlass/line/tcp/LineTcpReceiver.java|13|13|100.00%|
|:large_blue_circle:|io/questdb/cutlass/http/HttpServer.java|2|2|100.00%|
|:large_blue_circle:|io/questdb/network/MutableIOContextFactory.java|15|15|100.00%|
|:large_blue_circle:|io/questdb/cutlass/pgwire/PGConnectionContext.java|10|10|100.00%|

**Comment by ideoma** [comment]
#### [PR Coverage check]

:heart_eyes: **pass** : 56 / 66 (84.85%)




#### file detail

|   |path|covered line|new line|coverage|
|----|----|----|----|----|
|:large_blue_circle:|io/questdb/std/Chars.java|0|2|00.00%|
|:large_blue_circle:|io/questdb/std/str/DirectUnboundedByteSink.java|0|5|00.00%|
|:large_blue_circle:|io/questdb/network/AbstractMutableIOContext.java|8|11|72.73%|
|:large_blue_circle:|io/questdb/cutlass/pgwire/PGWireServer.java|5|5|100.00%|
|:large_blue_circle:|io/questdb/cutlass/http/HttpConnectionContext.java|3|3|100.00%|
|:large_blue_circle:|io/questdb/cutlass/line/tcp/LineTcpReceiver.java|13|13|100.00%|
|:large_blue_circle:|io/questdb/cutlass/http/HttpServer.java|2|2|100.00%|
|:large_blue_circle:|io/questdb/network/MutableIOContextFactory.java|15|15|100.00%|
|:large_blue_circle:|io/questdb/cutlass/pgwire/PGConnectionContext.java|10|10|100.00%|

**Comment by ideoma** [comment]
#### [PR Coverage check]

:heart_eyes: **pass** : 76 / 86 (88.37%)




#### file detail

|   |path|covered line|new line|coverage|
|----|----|----|----|----|
|:large_blue_circle:|io/questdb/std/Chars.java|0|2|00.00%|
|:large_blue_circle:|io/questdb/std/str/DirectUnboundedByteSink.java|0|5|00.00%|
|:large_blue_circle:|io/questdb/network/AbstractMutableIOContext.java|7|10|70.00%|
|:large_blue_circle:|io/questdb/network/IOContext.java|1|1|100.00%|
|:large_blue_circle:|io/questdb/cairo/vm/api/MemoryCARW.java|1|1|100.00%|
|:large_blue_circle:|io/questdb/std/Misc.java|3|3|100.00%|
|:large_blue_circle:|io/questdb/cutlass/pgwire/PGWireServer.java|5|5|100.00%|
|:large_blue_circle:|io/questdb/cutlass/http/HttpConnectionContext.java|3|3|100.00%|
|:large_blue_circle:|io/questdb/cutlass/line/tcp/LineTcpReceiver.java|13|13|100.00%|
|:large_blue_circle:|io/questdb/mp/WorkerPoolConfiguration.java|2|2|100.00%|
|:large_blue_circle:|io/questdb/cutlass/http/HttpServer.java|2|2|100.00%|
|:large_blue_circle:|io/questdb/network/MutableIOContextFactory.java|15|15|100.00%|
|:large_blue_circle:|io/questdb/log/LogFactory.java|1|1|100.00%|
|:large_blue_circle:|io/questdb/mp/WorkerPool.java|9|9|100.00%|
|:large_blue_circle:|io/questdb/WorkerPoolAwareConfiguration.java|1|1|100.00%|
|:large_blue_circle:|io/questdb/cairo/vm/MemoryPARWImpl.java|1|1|100.00%|
|:large_blue_circle:|io/questdb/cutlass/pgwire/PGConnectionContext.java|12|12|100.00%|

**Comment by ideoma** [comment]
#### [PR Coverage check]

:heart_eyes: **pass** : 76 / 86 (88.37%)




#### file detail

|   |path|covered line|new line|coverage|
|----|----|----|----|----|
|:large_blue_circle:|io/questdb/std/Chars.java|0|2|00.00%|
|:large_blue_circle:|io/questdb/std/str/DirectUnboundedByteSink.java|0|5|00.00%|
|:large_blue_circle:|io/questdb/network/AbstractMutableIOContext.java|7|10|70.00%|
|:large_blue_circle:|io/questdb/network/IOContext.java|1|1|100.00%|
|:large_blue_circle:|io/questdb/cairo/vm/api/MemoryCARW.java|1|1|100.00%|
|:large_blue_circle:|io/questdb/std/Misc.java|3|3|100.00%|
|:large_blue_circle:|io/questdb/cutlass/pgwire/PGWireServer.java|5|5|100.00%|
|:large_blue_circle:|io/questdb/cutlass/http/HttpConnectionContext.java|3|3|100.00%|
|:large_blue_circle:|io/questdb/cutlass/line/tcp/LineTcpReceiver.java|13|13|100.00%|
|:large_blue_circle:|io/questdb/mp/WorkerPoolConfiguration.java|2|2|100.00%|
|:large_blue_circle:|io/questdb/cutlass/http/HttpServer.java|2|2|100.00%|
|:large_blue_circle:|io/questdb/network/MutableIOContextFactory.java|15|15|100.00%|
|:large_blue_circle:|io/questdb/log/LogFactory.java|1|1|100.00%|
|:large_blue_circle:|io/questdb/mp/WorkerPool.java|9|9|100.00%|
|:large_blue_circle:|io/questdb/WorkerPoolAwareConfiguration.java|1|1|100.00%|
|:large_blue_circle:|io/questdb/cairo/vm/MemoryPARWImpl.java|1|1|100.00%|
|:large_blue_circle:|io/questdb/cutlass/pgwire/PGConnectionContext.java|12|12|100.00%|

**Comment by ideoma** [comment]
#### [PR Coverage check]

:heart_eyes: **pass** : 76 / 86 (88.37%)




#### file detail

|   |path|covered line|new line|coverage|
|----|----|----|----|----|
|:large_blue_circle:|io/questdb/std/Chars.java|0|2|00.00%|
|:large_blue_circle:|io/questdb/std/str/DirectUnboundedByteSink.java|0|5|00.00%|
|:large_blue_circle:|io/questdb/network/AbstractMutableIOContext.java|7|10|70.00%|
|:large_blue_circle:|io/questdb/network/IOContext.java|1|1|100.00%|
|:large_blue_circle:|io/questdb/cairo/vm/api/MemoryCARW.java|1|1|100.00%|
|:large_blue_circle:|io/questdb/std/Misc.java|3|3|100.00%|
|:large_blue_circle:|io/questdb/cutlass/pgwire/PGWireServer.java|5|5|100.00%|
|:large_blue_circle:|io/questdb/cutlass/http/HttpConnectionContext.java|3|3|100.00%|
|:large_blue_circle:|io/questdb/cutlass/line/tcp/LineTcpReceiver.java|13|13|100.00%|
|:large_blue_circle:|io/questdb/mp/WorkerPoolConfiguration.java|2|2|100.00%|
|:large_blue_circle:|io/questdb/cutlass/http/HttpServer.java|2|2|100.00%|
|:large_blue_circle:|io/questdb/network/MutableIOContextFactory.java|15|15|100.00%|
|:large_blue_circle:|io/questdb/log/LogFactory.java|1|1|100.00%|
|:large_blue_circle:|io/questdb/mp/WorkerPool.java|9|9|100.00%|
|:large_blue_circle:|io/questdb/WorkerPoolAwareConfiguration.java|1|1|100.00%|
|:large_blue_circle:|io/questdb/cairo/vm/MemoryPARWImpl.java|1|1|100.00%|
|:large_blue_circle:|io/questdb/cutlass/pgwire/PGConnectionContext.java|12|12|100.00%|

**Pull request merged**
