### PR TITLE
chore(core): add configurable per-class guaranteed logging

### PR DESCRIPTION
**Pull request by bziobrowski**
PR enables switching guaranteed logging for all messages issued by selected classes, via entry in log.conf . 
For the time being it's used to fix issues with acl query logging tests . 
Required by https://github.com/questdb/questdb-enterprise/pull/177 .

### CODE REVIEW

**Comment by ideoma** [comment]
#### [PR Coverage check]

:heart_eyes: **pass** : 99 / 145 (68.28%)




#### file detail

|   |path|covered line|new line|coverage|
|----|----|----|----|----|
|:large_blue_circle:|io/questdb/log/GuaranteedLogger.java|68|114|59.65%|
|:large_blue_circle:|io/questdb/log/LogFactory.java|31|31|100.00%|

**Comment by ideoma** [comment]
#### [PR Coverage check]

:heart_eyes: **pass** : 99 / 145 (68.28%)




#### file detail

|   |path|covered line|new line|coverage|
|----|----|----|----|----|
|:large_blue_circle:|io/questdb/log/GuaranteedLogger.java|68|114|59.65%|
|:large_blue_circle:|io/questdb/log/LogFactory.java|31|31|100.00%|

**Comment by ideoma** [comment]
#### [PR Coverage check]

:heart_eyes: **pass** : 99 / 145 (68.28%)




#### file detail

|   |path|covered line|new line|coverage|
|----|----|----|----|----|
|:large_blue_circle:|io/questdb/log/GuaranteedLogger.java|68|114|59.65%|
|:large_blue_circle:|io/questdb/log/LogFactory.java|31|31|100.00%|

**Review by glasstiger — APPROVED** [review]

**Comment by ideoma** [comment]
#### [PR Coverage check]

:heart_eyes: **pass** : 99 / 145 (68.28%)




#### file detail

|   |path|covered line|new line|coverage|
|----|----|----|----|----|
|:large_blue_circle:|io/questdb/log/GuaranteedLogger.java|68|114|59.65%|
|:large_blue_circle:|io/questdb/log/LogFactory.java|31|31|100.00%|

**Comment by ideoma** [comment]
#### [PR Coverage check]

:heart_eyes: **pass** : 99 / 145 (68.28%)




#### file detail

|   |path|covered line|new line|coverage|
|----|----|----|----|----|
|:large_blue_circle:|io/questdb/log/GuaranteedLogger.java|68|114|59.65%|
|:large_blue_circle:|io/questdb/log/LogFactory.java|31|31|100.00%|

**Pull request merged**
