### PR TITLE
chore(core): support enabling/disabling account

### PR DESCRIPTION
**Pull request by glasstiger**
adding back some code which was removed accidentally

### CODE REVIEW

**Review by ideoma — DISMISSED** [review]

**Comment by ideoma** [comment]
#### [PR Coverage check]

:heart_eyes: **pass** : 3 / 5 (60.00%)




#### file detail

|   |path|covered line|new line|coverage|
|----|----|----|----|----|
|:large_blue_circle:|io/questdb/cutlass/pgwire/PGConnectionContext.java|2|4|50.00%|
|:large_blue_circle:|io/questdb/griffin/SqlKeywords.java|1|1|100.00%|

**Review by bziobrowski — DISMISSED** [review]

**Review by ideoma — APPROVED** [review]

**Comment by ideoma** [comment]
#### [PR Coverage check]

:heart_eyes: **pass** : 4 / 6 (66.67%)




#### file detail

|   |path|covered line|new line|coverage|
|----|----|----|----|----|
|:large_blue_circle:|io/questdb/cutlass/pgwire/PGConnectionContext.java|2|4|50.00%|
|:large_blue_circle:|io/questdb/cutlass/line/tcp/LineTcpConnectionContext.java|1|1|100.00%|
|:large_blue_circle:|io/questdb/griffin/SqlKeywords.java|1|1|100.00%|

**Comment by ideoma** [comment]
#### [PR Coverage check]

:heart_eyes: **pass** : 4 / 6 (66.67%)




#### file detail

|   |path|covered line|new line|coverage|
|----|----|----|----|----|
|:large_blue_circle:|io/questdb/cutlass/pgwire/PGConnectionContext.java|2|4|50.00%|
|:large_blue_circle:|io/questdb/cutlass/line/tcp/LineTcpConnectionContext.java|1|1|100.00%|
|:large_blue_circle:|io/questdb/griffin/SqlKeywords.java|1|1|100.00%|

**Comment by ideoma** [comment]
#### [PR Coverage check]

:heart_eyes: **pass** : 4 / 6 (66.67%)




#### file detail

|   |path|covered line|new line|coverage|
|----|----|----|----|----|
|:large_blue_circle:|io/questdb/cutlass/pgwire/PGConnectionContext.java|2|4|50.00%|
|:large_blue_circle:|io/questdb/cutlass/line/tcp/LineTcpConnectionContext.java|1|1|100.00%|
|:large_blue_circle:|io/questdb/griffin/SqlKeywords.java|1|1|100.00%|

**Review by ideoma — APPROVED** [review]

**Pull request merged**
