### PR TITLE
feat(sql): include conf files and tab index in backups

### PR DESCRIPTION
**Pull request by marregui**
To start QuestDB you give it the root folder through parameter `-d /some/path/root`. This folder will end up having the following structure (`ls /some/path/root`):

1. **conf**, contains QuestDB's configuration files: server.conf, log-file.conf, date.formats, mime.types
2. **db**, contains one folder per table and the `_tab_index.d` (contains a number which is used to assign tables a unique id on creation).
3. **public**, contains the console (localhost:9000). This folder and contents are recreated by QuestDB on start (and you have to put them there yourself if you run from the IDE instead of from a release).
4. **log**, contains the logs of the running instance.

### SQL statement: `backup database`

This "command" takes the current state of QuestDB, i.e. its configuration and all of its tables, with the data as it is at the moment of running the command, and dumps it into a folder. This folder is a full backup and can be used directly through the `-d` parameter, as described above.

Only **conf** and **db** are considered, logs and public are not backed up.

The configuration settings that govern the destination folder are:
```
# output root directory for backups
cairo.sql.backup.root=/Users/uzulo/QUEST/BACKUP_ROOT

# date format for backup directory
cairo.sql.backup.dir.datetime.format=yyyy-MM-dd

# name of temp directory used during backup
#cairo.sql.backup.dir.tmp.name=tmp

# permission used when creating backup directories
#cairo.sql.backup.mkdir.mode=509
````
 and
```
cairo.root=db
```
the later is our **db**, which is configurable by the user. It could be called `prod` or something else. 

The backup command will copy the folder configured in setting `cairo.root` and folder `conf`, both, as found in the folder defined by the `-d` parameter, to folder `cairo.sql.backup.root` inside of a new folder named with pattern defined in `cairo.sql.backup.dir.datetime.format`. If you run another backup whose folder name would conflict, then a suffix `.1` will be added.

### CODE REVIEW

**Comment by ideoma** [comment]
#### [PR Coverage check]

:heart_eyes: **pass** : 30 / 33 (90.91%)




#### file detail

|   |path|covered line|new line|coverage|
|----|----|----|----|----|
|:large_blue_circle:|io/questdb/PropServerConfiguration.java|22|25|88.00%|
|:large_blue_circle:|io/questdb/cairo/DefaultCairoConfiguration.java|3|3|100.00%|
|:large_blue_circle:|io/questdb/griffin/SqlCompiler.java|5|5|100.00%|

**Comment by ideoma** [comment]
#### [PR Coverage check]

:heart_eyes: **pass** : 30 / 33 (90.91%)




#### file detail

|   |path|covered line|new line|coverage|
|----|----|----|----|----|
|:large_blue_circle:|io/questdb/PropServerConfiguration.java|22|25|88.00%|
|:large_blue_circle:|io/questdb/cairo/DefaultCairoConfiguration.java|3|3|100.00%|
|:large_blue_circle:|io/questdb/griffin/SqlCompiler.java|5|5|100.00%|

**Comment by ideoma** [comment]
#### [PR Coverage check]

:heart_eyes: **pass** : 30 / 33 (90.91%)




#### file detail

|   |path|covered line|new line|coverage|
|----|----|----|----|----|
|:large_blue_circle:|io/questdb/PropServerConfiguration.java|22|25|88.00%|
|:large_blue_circle:|io/questdb/cairo/DefaultCairoConfiguration.java|3|3|100.00%|
|:large_blue_circle:|io/questdb/griffin/SqlCompiler.java|5|5|100.00%|

**Comment by ideoma** [comment]
#### [PR Coverage check]

:heart_eyes: **pass** : 30 / 33 (90.91%)




#### file detail

|   |path|covered line|new line|coverage|
|----|----|----|----|----|
|:large_blue_circle:|io/questdb/PropServerConfiguration.java|22|25|88.00%|
|:large_blue_circle:|io/questdb/cairo/DefaultCairoConfiguration.java|3|3|100.00%|
|:large_blue_circle:|io/questdb/griffin/SqlCompiler.java|5|5|100.00%|

**Review by bluestreak01 — DISMISSED** [review]

**Comment by bluestreak01** [comment]
Good job Miguel, thanks 👌

I've added small refactoring to remove duplicate code, warnings and extra existence check before `mkdirs` call. Existence check isn't necessary, this call won't fail if dir already exists

**Review by bluestreak01 — APPROVED** [review]

**Comment by ideoma** [comment]
#### [PR Coverage check]

:heart_eyes: **pass** : 30 / 33 (90.91%)




#### file detail

|   |path|covered line|new line|coverage|
|----|----|----|----|----|
|:large_blue_circle:|io/questdb/PropServerConfiguration.java|22|25|88.00%|
|:large_blue_circle:|io/questdb/cairo/DefaultCairoConfiguration.java|3|3|100.00%|
|:large_blue_circle:|io/questdb/griffin/SqlCompiler.java|5|5|100.00%|

**Comment by ideoma** [comment]
#### [PR Coverage check]

:heart_eyes: **pass** : 30 / 33 (90.91%)




#### file detail

|   |path|covered line|new line|coverage|
|----|----|----|----|----|
|:large_blue_circle:|io/questdb/PropServerConfiguration.java|22|25|88.00%|
|:large_blue_circle:|io/questdb/cairo/DefaultCairoConfiguration.java|3|3|100.00%|
|:large_blue_circle:|io/questdb/griffin/SqlCompiler.java|5|5|100.00%|

**Comment by ideoma** [comment]
#### [PR Coverage check]

:heart_eyes: **pass** : 30 / 33 (90.91%)




#### file detail

|   |path|covered line|new line|coverage|
|----|----|----|----|----|
|:large_blue_circle:|io/questdb/PropServerConfiguration.java|22|25|88.00%|
|:large_blue_circle:|io/questdb/cairo/DefaultCairoConfiguration.java|3|3|100.00%|
|:large_blue_circle:|io/questdb/griffin/SqlCompiler.java|5|5|100.00%|

**Pull request merged**
