### PR TITLE
docs(core): add SECURITY policy

### PR DESCRIPTION
**Pull request by VanshajPoonia**
I request the maintainer to please replace the "youremail@email.com" with your support email ID.
I have also translated the file into some other languages to make it easier for contributors to understand

### CODE REVIEW

**Comment by pswu11** [comment]
Hi, @VanshajPoonia thanks a lot for the suggestion. Before approving this pull request, we'll review and discuss with the team on how it best applies to the existing workflow and then get back to this pull request.

**Comment by VanshajPoonia** [comment]
> Hi, @VanshajPoonia thanks a lot for the suggestion. Before approving this pull request, we'll review and discuss with the team on how it best applies to the existing workflow and then get back to this pull request.

Thanks for giving me a chance! :D

Please note that I have already contributed towards hacktoberfest and hence, not here just for swags. This file something I noticed wasn't there. The reason why I am mentioning this as recently I added Contributing guide and code of conduct file to a famous python library but the maintainer was too arrogant to accept it xD

**Review by pswu11 — CHANGES_REQUESTED** [review]
Hi @VanshajPoonia thanks a lot for the proposal. After some consideration, we think having lengthy multi-language sections for the security policy is not very ideal. Hence, we'd like to keep this part purely in English for now. 

As for the email to report any vulnerabilities, please use security@questdb.io.

**Comment by VanshajPoonia** [comment]
> Hi @VanshajPoonia thanks a lot for the proposal. After some consideration, we think having lengthy multi-language sections for the security policy is not very ideal. Hence, we'd like to keep this part purely in English for now.
> 
> As for the email to report any vulnerabilities, please use [security@questdb.io](mailto:security@questdb.io).

Sure! I will just edit it.

**Comment by VanshajPoonia** [comment]
> Hi @VanshajPoonia thanks a lot for the proposal. After some consideration, we think having lengthy multi-language sections for the security policy is not very ideal. Hence, we'd like to keep this part purely in English for now.
> 
> As for the email to report any vulnerabilities, please use [security@questdb.io](mailto:security@questdb.io).

I've just updated the pull request. I request you to please review it

**Comment by pswu11** [comment]
Hi @VanshajPoonia the changes I suggested above are not yet revised:
Screenshot 2022-10-25 at 19 21 30

**Comment by VanshajPoonia** [comment]
> Hi @VanshajPoonia the changes I suggested above are not done yet: Screenshot 2022-10-25 at 19 21 30


Hey, @pswu11 I have just done the changes that you recommended. Actually, the suggestion wasn't visible to me in this comment section and I am not aware of how to see the suggestions. Below are the screenshots of what I was able to see :
image
image
image

I request you to please tell me how to see the suggestions by the maintainers.

**Comment by pswu11** [comment]
Hi @VanshajPoonia that's weird, I believe they are usually visible under this section, 
Screenshot 2022-10-25 at 20 36 27
but all good.

**Review by pswu11 — APPROVED** [review]
LGTM

**Pull request merged**
