### PR TITLE
feat(sql): add aggregate function lag

### PR DESCRIPTION
**Pull request by marregui**
WIP

### CODE REVIEW

**Comment by ideoma** [comment]
#### [PR Coverage check]

:heart_eyes: **pass** : 25 / 27 (92.59%)




#### file detail

|   |path|covered line|new line|coverage|
|----|----|----|----|----|
|:large_blue_circle:|io/questdb/griffin/engine/functions/groupby/LagLongGroupByFunctionFactory.java|8|9|88.89%|
|:large_blue_circle:|io/questdb/griffin/engine/functions/groupby/LagLongGroupByFunction.java|17|18|94.44%|

**Comment by ideoma** [comment]
#### [PR Coverage check]

:heart_eyes: **pass** : 25 / 27 (92.59%)




#### file detail

|   |path|covered line|new line|coverage|
|----|----|----|----|----|
|:large_blue_circle:|io/questdb/griffin/engine/functions/groupby/LagLongGroupByFunctionFactory.java|8|9|88.89%|
|:large_blue_circle:|io/questdb/griffin/engine/functions/groupby/LagLongGroupByFunction.java|17|18|94.44%|

**Comment by ideoma** [comment]
#### [PR Coverage check]

:heart_eyes: **pass** : 34 / 35 (97.14%)




#### file detail

|   |path|covered line|new line|coverage|
|----|----|----|----|----|
|:large_blue_circle:|io/questdb/griffin/engine/functions/groupby/LagLongGroupByFunction.java|17|18|94.44%|
|:large_blue_circle:|io/questdb/griffin/engine/functions/groupby/LagLongGroupByFunctionFactory.java|17|17|100.00%|

**Comment by ideoma** [comment]
#### [PR Coverage check]

:heart_eyes: **pass** : 34 / 35 (97.14%)




#### file detail

|   |path|covered line|new line|coverage|
|----|----|----|----|----|
|:large_blue_circle:|io/questdb/griffin/engine/functions/groupby/LagLongGroupByFunction.java|17|18|94.44%|
|:large_blue_circle:|io/questdb/griffin/engine/functions/groupby/LagLongGroupByFunctionFactory.java|17|17|100.00%|

**Comment by ideoma** [comment]
#### [PR Coverage check]

:heart_eyes: **pass** : 34 / 35 (97.14%)




#### file detail

|   |path|covered line|new line|coverage|
|----|----|----|----|----|
|:large_blue_circle:|io/questdb/griffin/engine/functions/groupby/LagLongGroupByFunction.java|17|18|94.44%|
|:large_blue_circle:|io/questdb/griffin/engine/functions/groupby/LagLongGroupByFunctionFactory.java|17|17|100.00%|

**Comment by ideoma** [comment]
#### [PR Coverage check]

:heart_eyes: **pass** : 34 / 35 (97.14%)




#### file detail

|   |path|covered line|new line|coverage|
|----|----|----|----|----|
|:large_blue_circle:|io/questdb/griffin/engine/functions/groupby/LagLongGroupByFunction.java|17|18|94.44%|
|:large_blue_circle:|io/questdb/griffin/engine/functions/groupby/LagLongGroupByFunctionFactory.java|17|17|100.00%|

**Comment by ideoma** [comment]
#### [PR Coverage check]

:heart_eyes: **pass** : 38 / 39 (97.44%)




#### file detail

|   |path|covered line|new line|coverage|
|----|----|----|----|----|
|:large_blue_circle:|io/questdb/griffin/engine/functions/groupby/LagLongGroupByFunction.java|21|22|95.45%|
|:large_blue_circle:|io/questdb/griffin/engine/functions/groupby/LagLongGroupByFunctionFactory.java|17|17|100.00%|

**Comment by ideoma** [comment]
#### [PR Coverage check]

:heart_eyes: **pass** : 38 / 39 (97.44%)




#### file detail

|   |path|covered line|new line|coverage|
|----|----|----|----|----|
|:large_blue_circle:|io/questdb/griffin/engine/functions/groupby/LagLongGroupByFunction.java|21|22|95.45%|
|:large_blue_circle:|io/questdb/griffin/engine/functions/groupby/LagLongGroupByFunctionFactory.java|17|17|100.00%|

**Comment by ideoma** [comment]
#### [PR Coverage check]

:heart_eyes: **pass** : 38 / 39 (97.44%)




#### file detail

|   |path|covered line|new line|coverage|
|----|----|----|----|----|
|:large_blue_circle:|io/questdb/griffin/engine/functions/groupby/LagLongGroupByFunction.java|21|22|95.45%|
|:large_blue_circle:|io/questdb/griffin/engine/functions/groupby/LagLongGroupByFunctionFactory.java|17|17|100.00%|

**Comment by ideoma** [comment]
#### [PR Coverage check]

:heart_eyes: **pass** : 38 / 39 (97.44%)




#### file detail

|   |path|covered line|new line|coverage|
|----|----|----|----|----|
|:large_blue_circle:|io/questdb/griffin/engine/functions/groupby/LagLongGroupByFunction.java|21|22|95.45%|
|:large_blue_circle:|io/questdb/griffin/engine/functions/groupby/LagLongGroupByFunctionFactory.java|17|17|100.00%|

**Comment by ideoma** [comment]
#### [PR Coverage check]

:heart_eyes: **pass** : 38 / 39 (97.44%)




#### file detail

|   |path|covered line|new line|coverage|
|----|----|----|----|----|
|:large_blue_circle:|io/questdb/griffin/engine/functions/groupby/LagLongGroupByFunction.java|21|22|95.45%|
|:large_blue_circle:|io/questdb/griffin/engine/functions/groupby/LagLongGroupByFunctionFactory.java|17|17|100.00%|

**Comment by ideoma** [comment]
#### [PR Coverage check]

:heart_eyes: **pass** : 38 / 39 (97.44%)




#### file detail

|   |path|covered line|new line|coverage|
|----|----|----|----|----|
|:large_blue_circle:|io/questdb/griffin/engine/functions/groupby/LagLongGroupByFunction.java|21|22|95.45%|
|:large_blue_circle:|io/questdb/griffin/engine/functions/groupby/LagLongGroupByFunctionFactory.java|17|17|100.00%|

**Comment by marregui** [comment]
nobody actually needs to calculate lag, where lag is the row at offset rows before the last row in a group.

**Pull request closed without merging**
