### PR TITLE
perf(sql): support timestamp literals in JIT compiler

### PR DESCRIPTION
**Pull request by puzpuzpuz**
predicate searches for non-designated timestamp will be executed using JIT

### CODE REVIEW

**Comment by ideoma** [comment]
#### [PR Coverage check]

:heart_eyes: **pass** : 19 / 22 (86.36%)




#### file detail

|   |path|covered line|new line|coverage|
|----|----|----|----|----|
|:large_blue_circle:|io/questdb/jit/CompiledFilterIRSerializer.java|19|22|86.36%|

**Review by bluestreak01 — APPROVED** [review]

**Comment by bluestreak01** [comment]
the improvement is marginal for 64-core HT CPU:

image

vs non-JIT:

image

`in` is an easier to use syntax for `between`, but strangely it is not using JIT

**Comment by puzpuzpuz** [comment]
> `in` is an easier to use syntax for `between`, but strangely it is not using JIT

Yes, that's not yet supported.

**Comment by ideoma** [comment]
#### [PR Coverage check]

:heart_eyes: **pass** : 19 / 22 (86.36%)




#### file detail

|   |path|covered line|new line|coverage|
|----|----|----|----|----|
|:large_blue_circle:|io/questdb/jit/CompiledFilterIRSerializer.java|19|22|86.36%|

**Comment by puzpuzpuz** [comment]
The difference is bigger for larger filters. Java-based filters with many expressions are slower than the JIT ones.

**Pull request merged**
