### PR TITLE
fix(sql): force query cache expiration on table meta change

### LINKED ISSUE #1159: curl `overwrite=true` is not respected, corrupting data if types are changed in the second curl import
@eugenels  Submitting finding of bug per chat in Slack.

**Describe the bug**
When a csv table is created via curl, setting the field types by setting `schema=...`, and later another curl command modifies the types via `schema=...`, the data imported is corrupted.

**To Reproduce**
1. Create NYSE.csv:
```csv
ticker,ts,open,high,low,close,vol
A,20190102,66.5,66.57,65.3,65.69,2113300
```
2. Import, setting prices fields as DOUBLE via:
```bash
curl -F schema='[{"name":"ts", "type": "TIMESTAMP", "pattern": "yyyyMMdd"}, {"name":"ticker", "type": "SYMBOL"}, {"name":"open", "type": "DOUBLE"}, {"name":"high", "type": "DOUBLE"}, {"name":"low", "type": "DOUBLE"}, {"name":"close", "type": "DOUBLE"},{"name":"vol", "type": "INT"}]' -F data=@NYSE.csv 'http://localhost:9000/imp?overwrite=true&timestamp=ts&partitionBy=MONTH'
```
3. Verify data is imported correctly by running the SQL:
'NYSE.csv';
4. Re-import price fields as FLOAT:
```bash
curl -F schema='[{"name":"ts", "type": "TIMESTAMP", "pattern": "yyyyMMdd"}, {"name":"ticker", "type": "SYMBOL"}, {"name":"open", "type": "FLOAT"}, {"name":"high", "type": "FLOAT"}, {"name":"low", "type": "FLOAT"}, {"name":"close", "type": "FLOAT"},{"name":"vol", "type": "INT"}]' -F data=@NYSE.csv 'http://localhost:9000/imp?overwrite=true&timestamp=ts&partitionBy=MONTH'
```
5. Verify data is NOT imported correctly by running the SQL:
'NYSE.csv';
6. Drop the table, and reverse the curl orders, data is imported correctly as FLOAT, but corrupted when imported as DOUBLE the 2nd time.

**Expected behavior**
data should not be corrupted, `overwrite=true` is expected to truly overwrite the table

**Environment (please complete the following information):**
 - macOS 10.15.4
 - Browser: Chrome
 - QuestDB brew installed, 6.0.3, JDK 11.0.8, Commit Hash 2ea876e279b51a202f2853649785f111d9b0cdde 
 - curl 7.64.1 (x86_64-apple-darwin19.0) libcurl/7.64.1 (SecureTransport) LibreSSL/2.8.3 zlib/1.2.11 nghttp2/1.39.2

### PR DESCRIPTION
**Pull request by ideoma**
closes #1159, #1166

### CODE REVIEW

**Comment by ideoma** [comment]
#### [PR Coverage check]

:heart_eyes: **pass** : 110 / 122 (90.16%)




#### file detail

|   |path|covered line|new line|coverage|
|----|----|----|----|----|
|:large_blue_circle:|io/questdb/cairo/sql/ReaderOutOfDateException.java|9|12|75.00%|
|:large_blue_circle:|io/questdb/cutlass/http/processors/TextQueryProcessor.java|30|36|83.33%|
|:large_blue_circle:|io/questdb/cutlass/pgwire/PGConnectionContext.java|18|21|85.71%|
|:large_blue_circle:|io/questdb/cairo/IntervalFwdDataFrameCursorFactory.java|1|1|100.00%|
|:large_blue_circle:|io/questdb/cutlass/text/CairoTextWriter.java|3|3|100.00%|
|:large_blue_circle:|io/questdb/cairo/TableReplicationRecordCursorFactory.java|1|1|100.00%|
|:large_blue_circle:|io/questdb/cairo/IntervalBwdDataFrameCursorFactory.java|1|1|100.00%|
|:large_blue_circle:|io/questdb/cutlass/http/processors/JsonQueryProcessor.java|1|1|100.00%|
|:large_blue_circle:|io/questdb/cairo/FullBwdDataFrameCursorFactory.java|1|1|100.00%|
|:large_blue_circle:|io/questdb/cairo/CairoEngine.java|4|4|100.00%|
|:large_blue_circle:|io/questdb/griffin/engine/groupby/DistinctSymbolRecordCursorFactory.java|2|2|100.00%|
|:large_blue_circle:|io/questdb/cairo/TableReaderRecordCursorFactory.java|2|2|100.00%|
|:large_blue_circle:|io/questdb/griffin/model/QueryModel.java|4|4|100.00%|
|:large_blue_circle:|io/questdb/cairo/AbstractDataFrameCursorFactory.java|2|2|100.00%|
|:large_blue_circle:|io/questdb/griffin/SqlOptimiser.java|1|1|100.00%|
|:large_blue_circle:|io/questdb/griffin/engine/table/FilterOnExcludedValuesRecordCursorFactory.java|1|1|100.00%|
|:large_blue_circle:|io/questdb/griffin/SqlCompiler.java|19|19|100.00%|
|:large_blue_circle:|io/questdb/griffin/SqlCodeGenerator.java|9|9|100.00%|
|:large_blue_circle:|io/questdb/cairo/FullFwdDataFrameCursorFactory.java|1|1|100.00%|

**Comment by ideoma** [comment]
#### [PR Coverage check]

:heart_eyes: **pass** : 110 / 122 (90.16%)




#### file detail

|   |path|covered line|new line|coverage|
|----|----|----|----|----|
|:large_blue_circle:|io/questdb/cairo/sql/ReaderOutOfDateException.java|9|12|75.00%|
|:large_blue_circle:|io/questdb/cutlass/http/processors/TextQueryProcessor.java|30|36|83.33%|
|:large_blue_circle:|io/questdb/cutlass/pgwire/PGConnectionContext.java|18|21|85.71%|
|:large_blue_circle:|io/questdb/cairo/IntervalFwdDataFrameCursorFactory.java|1|1|100.00%|
|:large_blue_circle:|io/questdb/cutlass/text/CairoTextWriter.java|3|3|100.00%|
|:large_blue_circle:|io/questdb/cairo/TableReplicationRecordCursorFactory.java|1|1|100.00%|
|:large_blue_circle:|io/questdb/cairo/IntervalBwdDataFrameCursorFactory.java|1|1|100.00%|
|:large_blue_circle:|io/questdb/cutlass/http/processors/JsonQueryProcessor.java|1|1|100.00%|
|:large_blue_circle:|io/questdb/cairo/FullBwdDataFrameCursorFactory.java|1|1|100.00%|
|:large_blue_circle:|io/questdb/cairo/CairoEngine.java|4|4|100.00%|
|:large_blue_circle:|io/questdb/griffin/engine/groupby/DistinctSymbolRecordCursorFactory.java|2|2|100.00%|
|:large_blue_circle:|io/questdb/cairo/TableReaderRecordCursorFactory.java|2|2|100.00%|
|:large_blue_circle:|io/questdb/griffin/model/QueryModel.java|4|4|100.00%|
|:large_blue_circle:|io/questdb/cairo/AbstractDataFrameCursorFactory.java|2|2|100.00%|
|:large_blue_circle:|io/questdb/griffin/SqlOptimiser.java|1|1|100.00%|
|:large_blue_circle:|io/questdb/griffin/engine/table/FilterOnExcludedValuesRecordCursorFactory.java|1|1|100.00%|
|:large_blue_circle:|io/questdb/griffin/SqlCompiler.java|19|19|100.00%|
|:large_blue_circle:|io/questdb/griffin/SqlCodeGenerator.java|9|9|100.00%|
|:large_blue_circle:|io/questdb/cairo/FullFwdDataFrameCursorFactory.java|1|1|100.00%|

**Comment by ideoma** [comment]
#### [PR Coverage check]

:heart_eyes: **pass** : 88 / 92 (95.65%)




#### file detail

|   |path|covered line|new line|coverage|
|----|----|----|----|----|
|:large_blue_circle:|io/questdb/cutlass/pgwire/PGConnectionContext.java|16|19|84.21%|
|:large_blue_circle:|io/questdb/cairo/sql/ReaderOutOfDateException.java|9|10|90.00%|
|:large_blue_circle:|io/questdb/cairo/IntervalFwdDataFrameCursorFactory.java|1|1|100.00%|
|:large_blue_circle:|io/questdb/cutlass/text/CairoTextWriter.java|3|3|100.00%|
|:large_blue_circle:|io/questdb/cairo/TableReplicationRecordCursorFactory.java|1|1|100.00%|
|:large_blue_circle:|io/questdb/cairo/IntervalBwdDataFrameCursorFactory.java|1|1|100.00%|
|:large_blue_circle:|io/questdb/cutlass/http/processors/JsonQueryProcessor.java|1|1|100.00%|
|:large_blue_circle:|io/questdb/cairo/FullBwdDataFrameCursorFactory.java|1|1|100.00%|
|:large_blue_circle:|io/questdb/cairo/CairoEngine.java|4|4|100.00%|
|:large_blue_circle:|io/questdb/griffin/engine/groupby/DistinctSymbolRecordCursorFactory.java|2|2|100.00%|
|:large_blue_circle:|io/questdb/cairo/TableReaderRecordCursorFactory.java|2|2|100.00%|
|:large_blue_circle:|io/questdb/griffin/model/QueryModel.java|4|4|100.00%|
|:large_blue_circle:|io/questdb/cairo/AbstractDataFrameCursorFactory.java|2|2|100.00%|
|:large_blue_circle:|io/questdb/griffin/SqlOptimiser.java|1|1|100.00%|
|:large_blue_circle:|io/questdb/griffin/engine/table/FilterOnExcludedValuesRecordCursorFactory.java|1|1|100.00%|
|:large_blue_circle:|io/questdb/cutlass/http/processors/TextQueryProcessor.java|10|10|100.00%|
|:large_blue_circle:|io/questdb/griffin/SqlCompiler.java|19|19|100.00%|
|:large_blue_circle:|io/questdb/griffin/SqlCodeGenerator.java|9|9|100.00%|
|:large_blue_circle:|io/questdb/cairo/FullFwdDataFrameCursorFactory.java|1|1|100.00%|

**Comment by ideoma** [comment]
#### [PR Coverage check]

:heart_eyes: **pass** : 88 / 92 (95.65%)




#### file detail

|   |path|covered line|new line|coverage|
|----|----|----|----|----|
|:large_blue_circle:|io/questdb/cutlass/pgwire/PGConnectionContext.java|16|19|84.21%|
|:large_blue_circle:|io/questdb/cairo/sql/ReaderOutOfDateException.java|9|10|90.00%|
|:large_blue_circle:|io/questdb/cairo/IntervalFwdDataFrameCursorFactory.java|1|1|100.00%|
|:large_blue_circle:|io/questdb/cutlass/text/CairoTextWriter.java|3|3|100.00%|
|:large_blue_circle:|io/questdb/cairo/TableReplicationRecordCursorFactory.java|1|1|100.00%|
|:large_blue_circle:|io/questdb/cairo/IntervalBwdDataFrameCursorFactory.java|1|1|100.00%|
|:large_blue_circle:|io/questdb/cutlass/http/processors/JsonQueryProcessor.java|1|1|100.00%|
|:large_blue_circle:|io/questdb/cairo/FullBwdDataFrameCursorFactory.java|1|1|100.00%|
|:large_blue_circle:|io/questdb/cairo/CairoEngine.java|4|4|100.00%|
|:large_blue_circle:|io/questdb/griffin/engine/groupby/DistinctSymbolRecordCursorFactory.java|2|2|100.00%|
|:large_blue_circle:|io/questdb/cairo/TableReaderRecordCursorFactory.java|2|2|100.00%|
|:large_blue_circle:|io/questdb/griffin/model/QueryModel.java|4|4|100.00%|
|:large_blue_circle:|io/questdb/cairo/AbstractDataFrameCursorFactory.java|2|2|100.00%|
|:large_blue_circle:|io/questdb/griffin/SqlOptimiser.java|1|1|100.00%|
|:large_blue_circle:|io/questdb/griffin/engine/table/FilterOnExcludedValuesRecordCursorFactory.java|1|1|100.00%|
|:large_blue_circle:|io/questdb/cutlass/http/processors/TextQueryProcessor.java|10|10|100.00%|
|:large_blue_circle:|io/questdb/griffin/SqlCompiler.java|19|19|100.00%|
|:large_blue_circle:|io/questdb/griffin/SqlCodeGenerator.java|9|9|100.00%|
|:large_blue_circle:|io/questdb/cairo/FullFwdDataFrameCursorFactory.java|1|1|100.00%|

**Review by bluestreak01 — APPROVED** [review]

**Comment by ideoma** [comment]
#### [PR Coverage check]

:heart_eyes: **pass** : 88 / 92 (95.65%)




#### file detail

|   |path|covered line|new line|coverage|
|----|----|----|----|----|
|:large_blue_circle:|io/questdb/cutlass/pgwire/PGConnectionContext.java|16|19|84.21%|
|:large_blue_circle:|io/questdb/cairo/sql/ReaderOutOfDateException.java|9|10|90.00%|
|:large_blue_circle:|io/questdb/cairo/IntervalFwdDataFrameCursorFactory.java|1|1|100.00%|
|:large_blue_circle:|io/questdb/cutlass/text/CairoTextWriter.java|3|3|100.00%|
|:large_blue_circle:|io/questdb/cairo/TableReplicationRecordCursorFactory.java|1|1|100.00%|
|:large_blue_circle:|io/questdb/cairo/IntervalBwdDataFrameCursorFactory.java|1|1|100.00%|
|:large_blue_circle:|io/questdb/cutlass/http/processors/JsonQueryProcessor.java|1|1|100.00%|
|:large_blue_circle:|io/questdb/cairo/FullBwdDataFrameCursorFactory.java|1|1|100.00%|
|:large_blue_circle:|io/questdb/cairo/CairoEngine.java|4|4|100.00%|
|:large_blue_circle:|io/questdb/griffin/engine/groupby/DistinctSymbolRecordCursorFactory.java|2|2|100.00%|
|:large_blue_circle:|io/questdb/cairo/TableReaderRecordCursorFactory.java|2|2|100.00%|
|:large_blue_circle:|io/questdb/griffin/model/QueryModel.java|4|4|100.00%|
|:large_blue_circle:|io/questdb/cairo/AbstractDataFrameCursorFactory.java|2|2|100.00%|
|:large_blue_circle:|io/questdb/griffin/SqlOptimiser.java|1|1|100.00%|
|:large_blue_circle:|io/questdb/griffin/engine/table/FilterOnExcludedValuesRecordCursorFactory.java|1|1|100.00%|
|:large_blue_circle:|io/questdb/cutlass/http/processors/TextQueryProcessor.java|10|10|100.00%|
|:large_blue_circle:|io/questdb/griffin/SqlCompiler.java|19|19|100.00%|
|:large_blue_circle:|io/questdb/griffin/SqlCodeGenerator.java|9|9|100.00%|
|:large_blue_circle:|io/questdb/cairo/FullFwdDataFrameCursorFactory.java|1|1|100.00%|

**Comment by ideoma** [comment]
#### [PR Coverage check]

coverage check fail. please retry. :fearful:

[Please let me know](https://github.com/naver/cover-checker/issues/new) when error again.

com.naver.nid.cover.parser.coverage.exception.ParseException: java.io.FileNotFoundException: /usr/share/vsts-agent/_work/1/s/core/CCReport43F6D5EF/jacoco.xml (No such file or directory)

**Comment by ideoma** [comment]
#### [PR Coverage check]

:heart_eyes: **pass** : 88 / 92 (95.65%)




#### file detail

|   |path|covered line|new line|coverage|
|----|----|----|----|----|
|:large_blue_circle:|io/questdb/cutlass/pgwire/PGConnectionContext.java|16|19|84.21%|
|:large_blue_circle:|io/questdb/cairo/sql/ReaderOutOfDateException.java|9|10|90.00%|
|:large_blue_circle:|io/questdb/cairo/IntervalFwdDataFrameCursorFactory.java|1|1|100.00%|
|:large_blue_circle:|io/questdb/cutlass/text/CairoTextWriter.java|3|3|100.00%|
|:large_blue_circle:|io/questdb/cairo/TableReplicationRecordCursorFactory.java|1|1|100.00%|
|:large_blue_circle:|io/questdb/cairo/IntervalBwdDataFrameCursorFactory.java|1|1|100.00%|
|:large_blue_circle:|io/questdb/cutlass/http/processors/JsonQueryProcessor.java|1|1|100.00%|
|:large_blue_circle:|io/questdb/cairo/FullBwdDataFrameCursorFactory.java|1|1|100.00%|
|:large_blue_circle:|io/questdb/cairo/CairoEngine.java|4|4|100.00%|
|:large_blue_circle:|io/questdb/griffin/engine/groupby/DistinctSymbolRecordCursorFactory.java|2|2|100.00%|
|:large_blue_circle:|io/questdb/cairo/TableReaderRecordCursorFactory.java|2|2|100.00%|
|:large_blue_circle:|io/questdb/griffin/model/QueryModel.java|4|4|100.00%|
|:large_blue_circle:|io/questdb/cairo/AbstractDataFrameCursorFactory.java|2|2|100.00%|
|:large_blue_circle:|io/questdb/griffin/SqlOptimiser.java|1|1|100.00%|
|:large_blue_circle:|io/questdb/griffin/engine/table/FilterOnExcludedValuesRecordCursorFactory.java|1|1|100.00%|
|:large_blue_circle:|io/questdb/cutlass/http/processors/TextQueryProcessor.java|10|10|100.00%|
|:large_blue_circle:|io/questdb/griffin/SqlCompiler.java|19|19|100.00%|
|:large_blue_circle:|io/questdb/griffin/SqlCodeGenerator.java|9|9|100.00%|
|:large_blue_circle:|io/questdb/cairo/FullFwdDataFrameCursorFactory.java|1|1|100.00%|

**Pull request merged**
