### PR TITLE
ci(build): add redhat ubi docker build

### PR DESCRIPTION
**Pull request by sklarsa**
Adds docker builds based on the [redhat ubi](https://www.redhat.com/en/blog/introducing-red-hat-universal-base-image) to become compliant with [preflight checks](https://github.com/redhat-openshift-ecosystem/openshift-preflight) for RedHat certification.

One of the requirements is adding a license file to `/licenses` inside the image. Since I didn't want to expand our Docker build context (for build speed optimization), and we can't add files to an image from outside the context (not even symlinked), I copied the license file to the build context root (`./core`).

### CODE REVIEW

**Comment by questdb-butler** [comment]
<table>
  <thead>
    <tr>
      <th width="50"></th>
      <th width="100%" data-danger-table="true">Fails</th>
    </tr>
  </thead>
  <tbody><tr>
      <td>:no_entry_sign:</td>
      <td>

  Please update the PR title to match this format:
`type(subType): description`

Where `type` is one of:
`feat`, `fix`, `chore`, `docs`, `style`, `refactor`, `perf`, `test`, `ci`, `revert`

And: `subType` is one of:
`build`, `sql`, `log`, `mig`, `core`, `ilp`, `pgwire`, `http`, `conf`, `ui`, `wal`

For Example:

```
perf(sql): improve pattern matching performance for SELECT sub-queries
```
  </td>
    </tr>
  </tbody>
</table>




<p align="right">
  Generated by :no_entry_sign: <a href="https://danger.systems/js">dangerJS</a> against 6038a375f799ba38e3b6e3cfafd91455bac69bf2
</p>

**Comment by sklarsa** [comment]
Built an image using this command:
```
$ podman build --build-arg base_image=registry.access.redhat.com/ubi8/ubi --build-arg tag_name=8.0.3 -t sklarsa/qdbtest:rhel-test-4 .
```

Then using [redhat's preflight checker](https://github.com/redhat-openshift-ecosystem/openshift-preflight)...
```
$ ./preflight check container sklarsa/qdbtest:rhel-test-4
time="2024-07-16T13:50:27-04:00" level=info msg="certification library version" version="0.0.0 <commit: c9048da99aae76ddee5a708edcc94e14c034cd1d>"
time="2024-07-16T13:50:28-04:00" level=info msg="running checks for sklarsa/qdbtest:rhel-test-4 for platform arm64"
time="2024-07-16T13:50:28-04:00" level=info msg="target image" image="sklarsa/qdbtest:rhel-test-4"
time="2024-07-16T13:50:57-04:00" level=info msg="check completed" check=HasLicense result=PASSED
time="2024-07-16T13:50:57-04:00" level=info msg="check completed" check=HasUniqueTag result=PASSED
time="2024-07-16T13:50:57-04:00" level=info msg="check completed" check=LayerCountAcceptable result=PASSED
time="2024-07-16T13:50:57-04:00" level=info msg="check completed" check=HasNoProhibitedPackages result=PASSED
time="2024-07-16T13:50:57-04:00" level=info msg="check completed" check=HasRequiredLabel result=PASSED
time="2024-07-16T13:50:57-04:00" level=info msg="USER questdb specified that is non-root"
time="2024-07-16T13:50:57-04:00" level=info msg="check completed" check=RunAsNonRoot result=PASSED
time="2024-07-16T13:51:01-04:00" level=info msg="check completed" check=HasModifiedFiles result=PASSED
time="2024-07-16T13:51:02-04:00" level=info msg="check completed" check=BasedOnUbi result=PASSED
time="2024-07-16T13:51:02-04:00" level=info msg="This image's tag rhel-test-4 will be paired with digest sha256:ba06c56120d8887cadd488bf20c076e64de0717369c41c403c1541bfab2a20bf once this image has been published in accordance with Red Hat Certification policy. You may then add or remove any supplemental tags through your Red Hat Connect portal as you see fit."
{
    "image": "sklarsa/qdbtest:rhel-test-4",
    "passed": true,
    "test_library": {
        "name": "github.com/redhat-openshift-ecosystem/openshift-preflight",
        "version": "0.0.0",
        "commit": "c9048da99aae76ddee5a708edcc94e14c034cd1d"
    },
    "results": {
        "passed": [
            {
                "name": "HasLicense",
                "elapsed_time": 0,
                "description": "Checking if terms and conditions applicable to the software including open source licensing information are present. The license must be at /licenses"
            },
            {
                "name": "HasUniqueTag",
                "elapsed_time": 0,
                "description": "Checking if container has a tag other than 'latest', so that the image can be uniquely identified."
            },
            {
                "name": "LayerCountAcceptable",
                "elapsed_time": 0,
                "description": "Checking if container has less than 40 layers.  Too many layers within the container images can degrade container performance."
            },
            {
                "name": "HasNoProhibitedPackages",
                "elapsed_time": 39,
                "description": "Checks to ensure that the image in use does not include prohibited packages, such as Red Hat Enterprise Linux (RHEL) kernel packages."
            },
            {
                "name": "HasRequiredLabel",
                "elapsed_time": 0,
                "description": "Checking if the required labels (name, vendor, version, release, summary, description) are present in the container metadata."
            },
            {
                "name": "RunAsNonRoot",
                "elapsed_time": 0,
                "description": "Checking if container runs as the root user because a container that does not specify a non-root user will fail the automatic certification, and will be subject to a manual review before the container can be approved for publication"
            },
            {
                "name": "HasModifiedFiles",
                "elapsed_time": 4549,
                "description": "Checks that no files installed via RPM in the base Red Hat layer have been modified"
            },
            {
                "name": "BasedOnUbi",
                "elapsed_time": 639,
                "description": "Checking if the container's base image is based upon the Red Hat Universal Base Image (UBI)"
            }
        ],
        "failed": [],
        "errors": []
    }
}
time="2024-07-16T13:51:02-04:00" level=info msg="Preflight result: PASSED"
```

**Comment by bluestreak01** [comment]
hey @sklarsa how do we get alerted if this build fails? how is it triggered?

**Comment by sklarsa** [comment]
> hey @sklarsa how do we get alerted if this build fails? how is it triggered?

It looks like "nightly" is a misnomer. It runs on every `master` commit: https://dev.azure.com/questdb/questdb/_build?definitionId=22

**Review by bluestreak01 — APPROVED** [review]

**Pull request merged**
