### PR TITLE
Timestamps as strings in selects

### PR DESCRIPTION
**Pull request by ideoma**

### CODE REVIEW

**Review by bluestreak01 — CHANGES_REQUESTED** [review]

**Comment by ideoma** [comment]
#### [PR Coverage check]

:heart_eyes: **pass** : 360 / 390 (92.31%)




#### file detail

|   |path|covered line|new line|coverage|
|----|----|----|----|----|
|:large_blue_circle:|io/questdb/griffin/model/RuntimeIntervalModel.java|23|31|74.19%|
|:large_blue_circle:|io/questdb/griffin/engine/functions/bool/InTimestampTimestampFunctionFactory.java|21|27|77.78%|
|:large_blue_circle:|io/questdb/griffin/engine/functions/MultiArgFunction.java|13|14|92.86%|
|:large_blue_circle:|io/questdb/griffin/WhereClauseParser.java|94|101|93.07%|
|:large_blue_circle:|io/questdb/griffin/model/IntervalUtils.java|78|83|93.98%|
|:large_blue_circle:|io/questdb/griffin/model/RuntimeIntervalModelBuilder.java|66|69|95.65%|
|:large_blue_circle:|io/questdb/griffin/FunctionParser.java|13|13|100.00%|
|:large_blue_circle:|io/questdb/griffin/engine/functions/conditional/SwitchFunctionFactory.java|4|4|100.00%|
|:large_blue_circle:|io/questdb/griffin/engine/functions/bool/BetweenTimestampFunctionFactory.java|12|12|100.00%|
|:large_blue_circle:|io/questdb/griffin/model/IntrinsicModel.java|13|13|100.00%|
|:large_blue_circle:|io/questdb/griffin/engine/functions/date/TimestampAddFunctionFactory.java|1|1|100.00%|
|:large_blue_circle:|io/questdb/griffin/engine/functions/bool/InTimestampStrFunctionFactory.java|2|2|100.00%|
|:large_blue_circle:|io/questdb/griffin/engine/functions/TernaryFunction.java|7|7|100.00%|
|:large_blue_circle:|io/questdb/std/ObjList.java|2|2|100.00%|
|:large_blue_circle:|io/questdb/griffin/ExpressionParser.java|11|11|100.00%|

**Comment by ideoma** [comment]
#### [PR Coverage check]

:heart_eyes: **pass** : 360 / 390 (92.31%)




#### file detail

|   |path|covered line|new line|coverage|
|----|----|----|----|----|
|:large_blue_circle:|io/questdb/griffin/model/RuntimeIntervalModel.java|23|31|74.19%|
|:large_blue_circle:|io/questdb/griffin/engine/functions/bool/InTimestampTimestampFunctionFactory.java|21|27|77.78%|
|:large_blue_circle:|io/questdb/griffin/engine/functions/MultiArgFunction.java|13|14|92.86%|
|:large_blue_circle:|io/questdb/griffin/WhereClauseParser.java|94|101|93.07%|
|:large_blue_circle:|io/questdb/griffin/model/IntervalUtils.java|78|83|93.98%|
|:large_blue_circle:|io/questdb/griffin/model/RuntimeIntervalModelBuilder.java|66|69|95.65%|
|:large_blue_circle:|io/questdb/griffin/FunctionParser.java|13|13|100.00%|
|:large_blue_circle:|io/questdb/griffin/engine/functions/conditional/SwitchFunctionFactory.java|4|4|100.00%|
|:large_blue_circle:|io/questdb/griffin/engine/functions/bool/BetweenTimestampFunctionFactory.java|12|12|100.00%|
|:large_blue_circle:|io/questdb/griffin/model/IntrinsicModel.java|13|13|100.00%|
|:large_blue_circle:|io/questdb/griffin/engine/functions/date/TimestampAddFunctionFactory.java|1|1|100.00%|
|:large_blue_circle:|io/questdb/griffin/engine/functions/bool/InTimestampStrFunctionFactory.java|2|2|100.00%|
|:large_blue_circle:|io/questdb/griffin/engine/functions/TernaryFunction.java|7|7|100.00%|
|:large_blue_circle:|io/questdb/std/ObjList.java|2|2|100.00%|
|:large_blue_circle:|io/questdb/griffin/ExpressionParser.java|11|11|100.00%|

**Comment by ideoma** [comment]
#### [PR Coverage check]

coverage check fail. please retry. :fearful:

[Please let me know](https://github.com/naver/cover-checker/issues/new) when error again.

com.naver.nid.cover.parser.coverage.exception.ParseException: java.io.FileNotFoundException: /home/vsts/work/1/s/core/CCReport43F6D5EF/jacoco.xml (No such file or directory)

**Comment by ideoma** [comment]
#### [PR Coverage check]

:heart_eyes: **pass** : 317 / 407 (77.89%)




#### file detail

|   |path|covered line|new line|coverage|
|----|----|----|----|----|
|:large_blue_circle:|io/questdb/griffin/engine/functions/TernaryFunction.java|0|7|00.00%|
|:large_blue_circle:|io/questdb/griffin/engine/functions/bool/InTimestampTimestampFunctionFactory.java|2|27|07.41%|
|:large_blue_circle:|io/questdb/griffin/engine/functions/MultiArgFunction.java|5|14|35.71%|
|:large_blue_circle:|io/questdb/griffin/model/RuntimeIntervalModel.java|26|43|60.47%|
|:large_blue_circle:|io/questdb/griffin/model/RuntimeIntervalModelBuilder.java|53|69|76.81%|
|:large_blue_circle:|io/questdb/griffin/engine/functions/bool/BetweenTimestampFunctionFactory.java|11|12|91.67%|
|:large_blue_circle:|io/questdb/griffin/WhereClauseParser.java|92|101|91.09%|
|:large_blue_circle:|io/questdb/griffin/model/IntervalUtils.java|77|83|92.77%|
|:large_blue_circle:|io/questdb/griffin/FunctionParser.java|13|13|100.00%|
|:large_blue_circle:|io/questdb/griffin/engine/functions/conditional/SwitchFunctionFactory.java|4|4|100.00%|
|:large_blue_circle:|io/questdb/griffin/model/IntrinsicModel.java|13|13|100.00%|
|:large_blue_circle:|io/questdb/griffin/engine/functions/date/TimestampAddFunctionFactory.java|1|1|100.00%|
|:large_blue_circle:|io/questdb/griffin/engine/functions/bool/InTimestampStrFunctionFactory.java|2|2|100.00%|
|:large_blue_circle:|io/questdb/std/ObjList.java|2|2|100.00%|
|:large_blue_circle:|io/questdb/griffin/ExpressionParser.java|16|16|100.00%|

**Comment by ideoma** [comment]
#### [PR Coverage check]

:heart_eyes: **pass** : 376 / 400 (94.00%)




#### file detail

|   |path|covered line|new line|coverage|
|----|----|----|----|----|
|:large_blue_circle:|io/questdb/griffin/engine/functions/bool/InTimestampTimestampFunctionFactory.java|21|27|77.78%|
|:large_blue_circle:|io/questdb/griffin/model/RuntimeIntervalModel.java|33|36|91.67%|
|:large_blue_circle:|io/questdb/griffin/engine/functions/MultiArgFunction.java|13|14|92.86%|
|:large_blue_circle:|io/questdb/griffin/WhereClauseParser.java|94|101|93.07%|
|:large_blue_circle:|io/questdb/griffin/model/IntervalUtils.java|78|83|93.98%|
|:large_blue_circle:|io/questdb/griffin/model/RuntimeIntervalModelBuilder.java|67|69|97.10%|
|:large_blue_circle:|io/questdb/griffin/FunctionParser.java|13|13|100.00%|
|:large_blue_circle:|io/questdb/griffin/engine/functions/conditional/SwitchFunctionFactory.java|4|4|100.00%|
|:large_blue_circle:|io/questdb/griffin/engine/functions/bool/BetweenTimestampFunctionFactory.java|12|12|100.00%|
|:large_blue_circle:|io/questdb/griffin/model/IntrinsicModel.java|13|13|100.00%|
|:large_blue_circle:|io/questdb/griffin/engine/functions/date/TimestampAddFunctionFactory.java|1|1|100.00%|
|:large_blue_circle:|io/questdb/griffin/engine/functions/bool/InTimestampStrFunctionFactory.java|2|2|100.00%|
|:large_blue_circle:|io/questdb/griffin/engine/functions/TernaryFunction.java|7|7|100.00%|
|:large_blue_circle:|io/questdb/std/ObjList.java|2|2|100.00%|
|:large_blue_circle:|io/questdb/griffin/ExpressionParser.java|16|16|100.00%|

**Comment by ideoma** [comment]
#### [PR Coverage check]

:heart_eyes: **pass** : 376 / 400 (94.00%)




#### file detail

|   |path|covered line|new line|coverage|
|----|----|----|----|----|
|:large_blue_circle:|io/questdb/griffin/engine/functions/bool/InTimestampTimestampFunctionFactory.java|21|27|77.78%|
|:large_blue_circle:|io/questdb/griffin/model/RuntimeIntervalModel.java|33|36|91.67%|
|:large_blue_circle:|io/questdb/griffin/engine/functions/MultiArgFunction.java|13|14|92.86%|
|:large_blue_circle:|io/questdb/griffin/WhereClauseParser.java|94|101|93.07%|
|:large_blue_circle:|io/questdb/griffin/model/IntervalUtils.java|78|83|93.98%|
|:large_blue_circle:|io/questdb/griffin/model/RuntimeIntervalModelBuilder.java|67|69|97.10%|
|:large_blue_circle:|io/questdb/griffin/FunctionParser.java|13|13|100.00%|
|:large_blue_circle:|io/questdb/griffin/engine/functions/conditional/SwitchFunctionFactory.java|4|4|100.00%|
|:large_blue_circle:|io/questdb/griffin/engine/functions/bool/BetweenTimestampFunctionFactory.java|12|12|100.00%|
|:large_blue_circle:|io/questdb/griffin/model/IntrinsicModel.java|13|13|100.00%|
|:large_blue_circle:|io/questdb/griffin/engine/functions/date/TimestampAddFunctionFactory.java|1|1|100.00%|
|:large_blue_circle:|io/questdb/griffin/engine/functions/bool/InTimestampStrFunctionFactory.java|2|2|100.00%|
|:large_blue_circle:|io/questdb/griffin/engine/functions/TernaryFunction.java|7|7|100.00%|
|:large_blue_circle:|io/questdb/std/ObjList.java|2|2|100.00%|
|:large_blue_circle:|io/questdb/griffin/ExpressionParser.java|16|16|100.00%|

**Comment by ideoma** [comment]
#### [PR Coverage check]

:heart_eyes: **pass** : 386 / 398 (96.98%)




#### file detail

|   |path|covered line|new line|coverage|
|----|----|----|----|----|
|:large_blue_circle:|io/questdb/griffin/engine/functions/MultiArgFunction.java|13|14|92.86%|
|:large_blue_circle:|io/questdb/griffin/model/IntervalUtils.java|78|83|93.98%|
|:large_blue_circle:|io/questdb/griffin/model/RuntimeIntervalModelBuilder.java|67|69|97.10%|
|:large_blue_circle:|io/questdb/griffin/WhereClauseParser.java|98|101|97.03%|
|:large_blue_circle:|io/questdb/griffin/model/RuntimeIntervalModel.java|33|34|97.06%|
|:large_blue_circle:|io/questdb/griffin/FunctionParser.java|13|13|100.00%|
|:large_blue_circle:|io/questdb/griffin/engine/functions/conditional/SwitchFunctionFactory.java|4|4|100.00%|
|:large_blue_circle:|io/questdb/griffin/engine/functions/bool/BetweenTimestampFunctionFactory.java|12|12|100.00%|
|:large_blue_circle:|io/questdb/griffin/model/IntrinsicModel.java|13|13|100.00%|
|:large_blue_circle:|io/questdb/griffin/engine/functions/bool/InTimestampTimestampFunctionFactory.java|27|27|100.00%|
|:large_blue_circle:|io/questdb/griffin/engine/functions/date/TimestampAddFunctionFactory.java|1|1|100.00%|
|:large_blue_circle:|io/questdb/griffin/engine/functions/bool/InTimestampStrFunctionFactory.java|2|2|100.00%|
|:large_blue_circle:|io/questdb/griffin/engine/functions/TernaryFunction.java|7|7|100.00%|
|:large_blue_circle:|io/questdb/std/ObjList.java|2|2|100.00%|
|:large_blue_circle:|io/questdb/griffin/ExpressionParser.java|16|16|100.00%|

**Comment by ideoma** [comment]
#### [PR Coverage check]

:heart_eyes: **pass** : 393 / 399 (98.50%)




#### file detail

|   |path|covered line|new line|coverage|
|----|----|----|----|----|
|:large_blue_circle:|io/questdb/griffin/WhereClauseParser.java|98|101|97.03%|
|:large_blue_circle:|io/questdb/griffin/model/RuntimeIntervalModel.java|33|34|97.06%|
|:large_blue_circle:|io/questdb/griffin/model/RuntimeIntervalModelBuilder.java|67|68|98.53%|
|:large_blue_circle:|io/questdb/griffin/model/IntervalUtils.java|84|85|98.82%|
|:large_blue_circle:|io/questdb/griffin/FunctionParser.java|13|13|100.00%|
|:large_blue_circle:|io/questdb/griffin/engine/functions/conditional/SwitchFunctionFactory.java|4|4|100.00%|
|:large_blue_circle:|io/questdb/griffin/engine/functions/bool/BetweenTimestampFunctionFactory.java|12|12|100.00%|
|:large_blue_circle:|io/questdb/griffin/model/IntrinsicModel.java|13|13|100.00%|
|:large_blue_circle:|io/questdb/griffin/engine/functions/bool/InTimestampTimestampFunctionFactory.java|27|27|100.00%|
|:large_blue_circle:|io/questdb/griffin/engine/functions/date/TimestampAddFunctionFactory.java|1|1|100.00%|
|:large_blue_circle:|io/questdb/griffin/engine/functions/MultiArgFunction.java|14|14|100.00%|
|:large_blue_circle:|io/questdb/griffin/engine/functions/bool/InTimestampStrFunctionFactory.java|2|2|100.00%|
|:large_blue_circle:|io/questdb/griffin/engine/functions/TernaryFunction.java|7|7|100.00%|
|:large_blue_circle:|io/questdb/std/ObjList.java|2|2|100.00%|
|:large_blue_circle:|io/questdb/griffin/ExpressionParser.java|16|16|100.00%|

**Comment by ideoma** [comment]
#### [PR Coverage check]

:heart_eyes: **pass** : 394 / 402 (98.01%)




#### file detail

|   |path|covered line|new line|coverage|
|----|----|----|----|----|
|:large_blue_circle:|io/questdb/griffin/model/IntervalUtils.java|82|85|96.47%|
|:large_blue_circle:|io/questdb/griffin/WhereClauseParser.java|98|101|97.03%|
|:large_blue_circle:|io/questdb/griffin/model/RuntimeIntervalModel.java|33|34|97.06%|
|:large_blue_circle:|io/questdb/griffin/model/RuntimeIntervalModelBuilder.java|67|68|98.53%|
|:large_blue_circle:|io/questdb/griffin/FunctionParser.java|13|13|100.00%|
|:large_blue_circle:|io/questdb/griffin/engine/functions/conditional/SwitchFunctionFactory.java|4|4|100.00%|
|:large_blue_circle:|io/questdb/griffin/engine/functions/bool/BetweenTimestampFunctionFactory.java|12|12|100.00%|
|:large_blue_circle:|io/questdb/griffin/model/IntrinsicModel.java|13|13|100.00%|
|:large_blue_circle:|io/questdb/griffin/engine/functions/bool/InTimestampTimestampFunctionFactory.java|30|30|100.00%|
|:large_blue_circle:|io/questdb/griffin/engine/functions/date/TimestampAddFunctionFactory.java|1|1|100.00%|
|:large_blue_circle:|io/questdb/griffin/engine/functions/MultiArgFunction.java|14|14|100.00%|
|:large_blue_circle:|io/questdb/griffin/engine/functions/bool/InTimestampStrFunctionFactory.java|2|2|100.00%|
|:large_blue_circle:|io/questdb/griffin/engine/functions/TernaryFunction.java|7|7|100.00%|
|:large_blue_circle:|io/questdb/std/ObjList.java|2|2|100.00%|
|:large_blue_circle:|io/questdb/griffin/ExpressionParser.java|16|16|100.00%|

**Comment by ideoma** [comment]
#### [PR Coverage check]

:heart_eyes: **pass** : 394 / 402 (98.01%)




#### file detail

|   |path|covered line|new line|coverage|
|----|----|----|----|----|
|:large_blue_circle:|io/questdb/griffin/model/IntervalUtils.java|82|85|96.47%|
|:large_blue_circle:|io/questdb/griffin/WhereClauseParser.java|98|101|97.03%|
|:large_blue_circle:|io/questdb/griffin/model/RuntimeIntervalModel.java|33|34|97.06%|
|:large_blue_circle:|io/questdb/griffin/model/RuntimeIntervalModelBuilder.java|67|68|98.53%|
|:large_blue_circle:|io/questdb/griffin/FunctionParser.java|13|13|100.00%|
|:large_blue_circle:|io/questdb/griffin/engine/functions/conditional/SwitchFunctionFactory.java|4|4|100.00%|
|:large_blue_circle:|io/questdb/griffin/engine/functions/bool/BetweenTimestampFunctionFactory.java|12|12|100.00%|
|:large_blue_circle:|io/questdb/griffin/model/IntrinsicModel.java|13|13|100.00%|
|:large_blue_circle:|io/questdb/griffin/engine/functions/bool/InTimestampTimestampFunctionFactory.java|30|30|100.00%|
|:large_blue_circle:|io/questdb/griffin/engine/functions/date/TimestampAddFunctionFactory.java|1|1|100.00%|
|:large_blue_circle:|io/questdb/griffin/engine/functions/MultiArgFunction.java|14|14|100.00%|
|:large_blue_circle:|io/questdb/griffin/engine/functions/bool/InTimestampStrFunctionFactory.java|2|2|100.00%|
|:large_blue_circle:|io/questdb/griffin/engine/functions/TernaryFunction.java|7|7|100.00%|
|:large_blue_circle:|io/questdb/std/ObjList.java|2|2|100.00%|
|:large_blue_circle:|io/questdb/griffin/ExpressionParser.java|16|16|100.00%|

**Comment by ideoma** [comment]
#### [PR Coverage check]

:heart_eyes: **pass** : 394 / 402 (98.01%)




#### file detail

|   |path|covered line|new line|coverage|
|----|----|----|----|----|
|:large_blue_circle:|io/questdb/griffin/model/IntervalUtils.java|82|85|96.47%|
|:large_blue_circle:|io/questdb/griffin/WhereClauseParser.java|98|101|97.03%|
|:large_blue_circle:|io/questdb/griffin/model/RuntimeIntervalModel.java|33|34|97.06%|
|:large_blue_circle:|io/questdb/griffin/model/RuntimeIntervalModelBuilder.java|67|68|98.53%|
|:large_blue_circle:|io/questdb/griffin/FunctionParser.java|13|13|100.00%|
|:large_blue_circle:|io/questdb/griffin/engine/functions/conditional/SwitchFunctionFactory.java|4|4|100.00%|
|:large_blue_circle:|io/questdb/griffin/engine/functions/bool/BetweenTimestampFunctionFactory.java|12|12|100.00%|
|:large_blue_circle:|io/questdb/griffin/model/IntrinsicModel.java|13|13|100.00%|
|:large_blue_circle:|io/questdb/griffin/engine/functions/bool/InTimestampTimestampFunctionFactory.java|30|30|100.00%|
|:large_blue_circle:|io/questdb/griffin/engine/functions/date/TimestampAddFunctionFactory.java|1|1|100.00%|
|:large_blue_circle:|io/questdb/griffin/engine/functions/MultiArgFunction.java|14|14|100.00%|
|:large_blue_circle:|io/questdb/griffin/engine/functions/bool/InTimestampStrFunctionFactory.java|2|2|100.00%|
|:large_blue_circle:|io/questdb/griffin/engine/functions/TernaryFunction.java|7|7|100.00%|
|:large_blue_circle:|io/questdb/std/ObjList.java|2|2|100.00%|
|:large_blue_circle:|io/questdb/griffin/ExpressionParser.java|16|16|100.00%|

**Review by bluestreak01 — APPROVED** [review]

**Comment by ideoma** [comment]
#### [PR Coverage check]

:heart_eyes: **pass** : 394 / 402 (98.01%)




#### file detail

|   |path|covered line|new line|coverage|
|----|----|----|----|----|
|:large_blue_circle:|io/questdb/griffin/model/IntervalUtils.java|82|85|96.47%|
|:large_blue_circle:|io/questdb/griffin/WhereClauseParser.java|98|101|97.03%|
|:large_blue_circle:|io/questdb/griffin/model/RuntimeIntervalModel.java|33|34|97.06%|
|:large_blue_circle:|io/questdb/griffin/model/RuntimeIntervalModelBuilder.java|67|68|98.53%|
|:large_blue_circle:|io/questdb/griffin/FunctionParser.java|13|13|100.00%|
|:large_blue_circle:|io/questdb/griffin/engine/functions/conditional/SwitchFunctionFactory.java|4|4|100.00%|
|:large_blue_circle:|io/questdb/griffin/engine/functions/bool/BetweenTimestampFunctionFactory.java|12|12|100.00%|
|:large_blue_circle:|io/questdb/griffin/model/IntrinsicModel.java|13|13|100.00%|
|:large_blue_circle:|io/questdb/griffin/engine/functions/bool/InTimestampTimestampFunctionFactory.java|30|30|100.00%|
|:large_blue_circle:|io/questdb/griffin/engine/functions/date/TimestampAddFunctionFactory.java|1|1|100.00%|
|:large_blue_circle:|io/questdb/griffin/engine/functions/MultiArgFunction.java|14|14|100.00%|
|:large_blue_circle:|io/questdb/griffin/engine/functions/bool/InTimestampStrFunctionFactory.java|2|2|100.00%|
|:large_blue_circle:|io/questdb/griffin/engine/functions/TernaryFunction.java|7|7|100.00%|
|:large_blue_circle:|io/questdb/std/ObjList.java|2|2|100.00%|
|:large_blue_circle:|io/questdb/griffin/ExpressionParser.java|16|16|100.00%|

**Comment by ideoma** [comment]
#### [PR Coverage check]

:heart_eyes: **pass** : 391 / 399 (97.99%)




#### file detail

|   |path|covered line|new line|coverage|
|----|----|----|----|----|
|:large_blue_circle:|io/questdb/griffin/model/IntervalUtils.java|82|85|96.47%|
|:large_blue_circle:|io/questdb/griffin/WhereClauseParser.java|98|101|97.03%|
|:large_blue_circle:|io/questdb/griffin/model/RuntimeIntervalModel.java|33|34|97.06%|
|:large_blue_circle:|io/questdb/griffin/model/RuntimeIntervalModelBuilder.java|67|68|98.53%|
|:large_blue_circle:|io/questdb/griffin/FunctionParser.java|13|13|100.00%|
|:large_blue_circle:|io/questdb/griffin/engine/functions/conditional/SwitchFunctionFactory.java|4|4|100.00%|
|:large_blue_circle:|io/questdb/griffin/engine/functions/bool/BetweenTimestampFunctionFactory.java|12|12|100.00%|
|:large_blue_circle:|io/questdb/griffin/model/IntrinsicModel.java|13|13|100.00%|
|:large_blue_circle:|io/questdb/griffin/engine/functions/bool/InTimestampTimestampFunctionFactory.java|30|30|100.00%|
|:large_blue_circle:|io/questdb/griffin/engine/functions/date/TimestampAddFunctionFactory.java|1|1|100.00%|
|:large_blue_circle:|io/questdb/griffin/engine/functions/MultiArgFunction.java|11|11|100.00%|
|:large_blue_circle:|io/questdb/griffin/engine/functions/bool/InTimestampStrFunctionFactory.java|2|2|100.00%|
|:large_blue_circle:|io/questdb/griffin/engine/functions/TernaryFunction.java|7|7|100.00%|
|:large_blue_circle:|io/questdb/std/ObjList.java|2|2|100.00%|
|:large_blue_circle:|io/questdb/griffin/ExpressionParser.java|16|16|100.00%|

**Comment by ideoma** [comment]
#### [PR Coverage check]

:heart_eyes: **pass** : 391 / 399 (97.99%)




#### file detail

|   |path|covered line|new line|coverage|
|----|----|----|----|----|
|:large_blue_circle:|io/questdb/griffin/model/IntervalUtils.java|82|85|96.47%|
|:large_blue_circle:|io/questdb/griffin/WhereClauseParser.java|98|101|97.03%|
|:large_blue_circle:|io/questdb/griffin/model/RuntimeIntervalModel.java|33|34|97.06%|
|:large_blue_circle:|io/questdb/griffin/model/RuntimeIntervalModelBuilder.java|67|68|98.53%|
|:large_blue_circle:|io/questdb/griffin/FunctionParser.java|13|13|100.00%|
|:large_blue_circle:|io/questdb/griffin/engine/functions/conditional/SwitchFunctionFactory.java|4|4|100.00%|
|:large_blue_circle:|io/questdb/griffin/engine/functions/bool/BetweenTimestampFunctionFactory.java|12|12|100.00%|
|:large_blue_circle:|io/questdb/griffin/model/IntrinsicModel.java|13|13|100.00%|
|:large_blue_circle:|io/questdb/griffin/engine/functions/bool/InTimestampTimestampFunctionFactory.java|30|30|100.00%|
|:large_blue_circle:|io/questdb/griffin/engine/functions/date/TimestampAddFunctionFactory.java|1|1|100.00%|
|:large_blue_circle:|io/questdb/griffin/engine/functions/MultiArgFunction.java|11|11|100.00%|
|:large_blue_circle:|io/questdb/griffin/engine/functions/bool/InTimestampStrFunctionFactory.java|2|2|100.00%|
|:large_blue_circle:|io/questdb/griffin/engine/functions/TernaryFunction.java|7|7|100.00%|
|:large_blue_circle:|io/questdb/std/ObjList.java|2|2|100.00%|
|:large_blue_circle:|io/questdb/griffin/ExpressionParser.java|16|16|100.00%|

**Comment by ideoma** [comment]
#### [PR Coverage check]

:heart_eyes: **pass** : 391 / 399 (97.99%)




#### file detail

|   |path|covered line|new line|coverage|
|----|----|----|----|----|
|:large_blue_circle:|io/questdb/griffin/model/IntervalUtils.java|82|85|96.47%|
|:large_blue_circle:|io/questdb/griffin/WhereClauseParser.java|98|101|97.03%|
|:large_blue_circle:|io/questdb/griffin/model/RuntimeIntervalModel.java|33|34|97.06%|
|:large_blue_circle:|io/questdb/griffin/model/RuntimeIntervalModelBuilder.java|67|68|98.53%|
|:large_blue_circle:|io/questdb/griffin/FunctionParser.java|13|13|100.00%|
|:large_blue_circle:|io/questdb/griffin/engine/functions/conditional/SwitchFunctionFactory.java|4|4|100.00%|
|:large_blue_circle:|io/questdb/griffin/engine/functions/bool/BetweenTimestampFunctionFactory.java|12|12|100.00%|
|:large_blue_circle:|io/questdb/griffin/model/IntrinsicModel.java|13|13|100.00%|
|:large_blue_circle:|io/questdb/griffin/engine/functions/bool/InTimestampTimestampFunctionFactory.java|30|30|100.00%|
|:large_blue_circle:|io/questdb/griffin/engine/functions/date/TimestampAddFunctionFactory.java|1|1|100.00%|
|:large_blue_circle:|io/questdb/griffin/engine/functions/MultiArgFunction.java|11|11|100.00%|
|:large_blue_circle:|io/questdb/griffin/engine/functions/bool/InTimestampStrFunctionFactory.java|2|2|100.00%|
|:large_blue_circle:|io/questdb/griffin/engine/functions/TernaryFunction.java|7|7|100.00%|
|:large_blue_circle:|io/questdb/std/ObjList.java|2|2|100.00%|
|:large_blue_circle:|io/questdb/griffin/ExpressionParser.java|16|16|100.00%|

**Pull request merged**
