### PR TITLE
fix(core): fix unaligned msync address when merging split partitions

### LINKED ISSUE #3701: Invalid msync call on partition squashing
### Describe the bug

Looks like we don't provide a page size aligned address when calling `msync` from `ContiguousFileVarFrameColumn` on partition squashing. According to the [msync docs](https://man7.org/linux/man-pages/man2/msync.2.html), EINVAL (code 22) may be returned when `addr` is not a multiple of PAGESIZE.

We should make sure to add some tests around that when fixing the issue.

Error logs:
```
2023-09-01T00:00:31.006499Z I i.q.c.TableWriter switched partition [path='/root/.questdb/db/sensor_sample_test~22/2023-09.30886']
2023-09-01T00:00:31.097676Z I i.q.c.TableWriter switched partition [path='/root/.questdb/db/sensor_sample_test~21/2023-09.30719']
2023-09-01T00:00:31.267977Z I i.q.c.TableWriter squashing partitions [table=sensor_sample_431886, target=2023-08, targetSize=698317, source=2023-08-08T115429-150001.2667, sourceSize=382315]
2023-09-01T00:00:31.268110Z I i.q.c.TableWriter squashing partitions [table=sensor_sample_61661, target=2023-08, targetSize=540779, source=2023-08-08T115422-752001.44, sourceSize=362068]
2023-09-01T00:00:31.775472Z C i.q.c.TableWriter partition squashing failed [table=sensor_sample_431886, error=
io.questdb.cairo.CairoException: [22] could not msync
	at io.questdb.cairo.CairoException.critical(CairoException.java:63)
	at io.questdb.std.FilesFacadeImpl.msync(FilesFacadeImpl.java:307)
	at io.questdb.cairo.frm.file.ContiguousFileVarFrameColumn.append(ContiguousFileVarFrameColumn.java:151)
	at io.questdb.cairo.frm.FrameAlgebra.append(FrameAlgebra.java:63)
	at io.questdb.cairo.frm.FrameAlgebra.append(FrameAlgebra.java:37)
	at io.questdb.cairo.TableWriter.squashSplitPartitions(TableWriter.java:7202)
	at io.questdb.cairo.TableWriter.squashPartitionRange(TableWriter.java:7072)
	at io.questdb.cairo.TableWriter.squashSplitPartitions(TableWriter.java:7113)
	at io.questdb.cairo.TableWriter.commitWalTransaction(TableWriter.java:972)
	at io.questdb.cairo.wal.ApplyWal2TableJob.processWalCommit(ApplyWal2TableJob.java:409)
	at io.questdb.cairo.wal.ApplyWal2TableJob.applyOutstandingWalTransactions(ApplyWal2TableJob.java:335)
	at io.questdb.cairo.wal.ApplyWal2TableJob.applyWAL(ApplyWal2TableJob.java:523)
	at io.questdb.cairo.wal.ApplyWal2TableJob.doRun(ApplyWal2TableJob.java:572)
	at [io.questdb.mp](http://io.questdb.mp/).AbstractQueueConsumerJob.run(AbstractQueueConsumerJob.java:41)
	at [io.questdb.mp](http://io.questdb.mp/).Worker.run(Worker.java:118)
]
2023-09-01T00:00:31.775472Z C i.q.c.TableWriter partition squashing failed [table=sensor_sample_61661, error=
io.questdb.cairo.CairoException: [22] could not msync
	at io.questdb.cairo.CairoException.critical(CairoException.java:63)
	at io.questdb.std.FilesFacadeImpl.msync(FilesFacadeImpl.java:307)
	at io.questdb.cairo.frm.file.ContiguousFileVarFrameColumn.append(ContiguousFileVarFrameColumn.java:151)
	at io.questdb.cairo.frm.FrameAlgebra.append(FrameAlgebra.java:63)
	at io.questdb.cairo.frm.FrameAlgebra.append(FrameAlgebra.java:37)
	at io.questdb.cairo.TableWriter.squashSplitPartitions(TableWriter.java:7202)
	at io.questdb.cairo.TableWriter.squashPartitionRange(TableWriter.java:7072)
	at io.questdb.cairo.TableWriter.squashSplitPartitions(TableWriter.java:7113)
	at io.questdb.cairo.TableWriter.commitWalTransaction(TableWriter.java:972)
	at io.questdb.cairo.wal.ApplyWal2TableJob.processWalCommit(ApplyWal2TableJob.java:409)
	at io.questdb.cairo.wal.ApplyWal2TableJob.applyOutstandingWalTransactions(ApplyWal2TableJob.java:335)
	at io.questdb.cairo.wal.ApplyWal2TableJob.applyWAL(ApplyWal2TableJob.java:523)
	at io.questdb.cairo.wal.ApplyWal2TableJob.doRun(ApplyWal2TableJob.java:572)
	at [io.questdb.mp](http://io.questdb.mp/).AbstractQueueConsumerJob.run(AbstractQueueConsumerJob.java:41)
	at [io.questdb.mp](http://io.questdb.mp/).Worker.run(Worker.java:118)
]
2023-09-01T00:00:31.833707Z I i.q.c.p.WriterPool << [table=`sensor_sample_test~22`, thread=23]
2023-09-01T00:00:31.833709Z I i.q.c.p.WriterPool << [table=`sensor_sample_test~21`, thread=24]
2023-09-01T00:00:31.834078Z C i.q.c.w.ApplyWal2TableJob job failed, table suspended [table=sensor_sample_test~22, error=could not msync, errno=22]
2023-09-01T00:00:31.834328Z C i.q.c.w.ApplyWal2TableJob job failed, table suspended [table=sensor_sample_test~21, error=could not msync, errno=22]
2023-09-01T00:00:31.845292Z I i.q.c.p.WriterPool >> [table=`sensor_sample_test~23`, thread=23]
2023-09-01T00:00:31.846958Z I i.q.c.TableWriter processing WAL [path=/root/.questdb/db/sensor_sample_test~23/wal108/0, roLo=25196, roHi=25256, seqTxn=30887, tsMin=2023-08-31T23:59:30.337000Z, tsMax=2023-09-01T00:00:27.545000Z, commitToTimestamp=294247-01-10T04:00:54.775807Z]
2023-09-01T00:00:31.848506Z I i.q.c.TableWriter o3 partition task [table=sensor_sample_975429, partitionIsReadOnly=false, srcOooBatchRowSize=41, srcOooLo=25196, srcOooHi=25236, srcOooMax=25256, o3RowCount=60, o3LagRowCount=0, srcDataMax=182073, o3TimestampMin=2023-08-31T23:59:30.337000Z, o3Timestamp=2023-08-31T23:59:30.337000Z, o3TimestampMax=2023-09-01T00:00:27.545000Z, partitionTimestamp=2023-08-30T02:05:29.109001Z, partitionIndex=72, partitionSize=182114, maxTimestamp=2023-08-31T23:59:28.295000Z, last=true, append=true, pCount=1, flattenTimestamp=false, memUsed=2761995894]
2023-09-01T00:00:31.848609Z I i.q.c.TableWriter o3 partition task [table=sensor_sample_975429, partitionIsReadOnly=false, srcOooBatchRowSize=19, srcOooLo=25237, srcOooHi=25255, srcOooMax=25256, o3RowCount=60, o3LagRowCount=0, srcDataMax=0, o3TimestampMin=2023-08-31T23:59:30.337000Z, o3Timestamp=2023-09-01T00:00:01.080000Z, o3TimestampMax=2023-09-01T00:00:27.545000Z, partitionTimestamp=2023-09-01T00:00:00.000000Z, partitionIndex=-77, partitionSize=19, maxTimestamp=2023-08-31T23:59:28.295000Z, last=false, append=false, pCount=2, flattenTimestamp=false, memUsed=2761995894]
2023-09-01T00:00:32.199146Z I i.q.c.TableWriter switched partition [path='/root/.questdb/db/sensor_sample_test~23/2023-09.30889']
2023-09-01T00:00:32.245623Z I i.q.c.TableWriter squashing partitions [table=sensor_sample_975429, target=2023-08, targetSize=717381, source=2023-08-08T115428-791001.2366, sourceSize=342269]
2023-09-01T00:00:32.524333Z C i.q.c.TableWriter partition squashing failed [table=sensor_sample_975429, error=
io.questdb.cairo.CairoException: [22] could not msync
	at io.questdb.cairo.CairoException.critical(CairoException.java:63)
	at io.questdb.std.FilesFacadeImpl.msync(FilesFacadeImpl.java:307)
	at io.questdb.cairo.frm.file.ContiguousFileVarFrameColumn.append(ContiguousFileVarFrameColumn.java:151)
	at io.questdb.cairo.frm.FrameAlgebra.append(FrameAlgebra.java:63)
	at io.questdb.cairo.frm.FrameAlgebra.append(FrameAlgebra.java:37)
	at io.questdb.cairo.TableWriter.squashSplitPartitions(TableWriter.java:7202)
	at io.questdb.cairo.TableWriter.squashPartitionRange(TableWriter.java:7072)
	at io.questdb.cairo.TableWriter.squashSplitPartitions(TableWriter.java:7113)
	at io.questdb.cairo.TableWriter.commitWalTransaction(TableWriter.java:972)
	at io.questdb.cairo.wal.ApplyWal2TableJob.processWalCommit(ApplyWal2TableJob.java:409)
	at io.questdb.cairo.wal.ApplyWal2TableJob.applyOutstandingWalTransactions(ApplyWal2TableJob.java:335)
	at io.questdb.cairo.wal.ApplyWal2TableJob.applyWAL(ApplyWal2TableJob.java:523)
	at io.questdb.cairo.wal.ApplyWal2TableJob.doRun(ApplyWal2TableJob.java:572)
	at [io.questdb.mp](http://io.questdb.mp/).AbstractQueueConsumerJob.run(AbstractQueueConsumerJob.java:41)
	at [io.questdb.mp](http://io.questdb.mp/).Worker.run(Worker.java:118)
]
2023-09-01T00:00:32.524940Z I i.q.c.p.WriterPool << [table=`sensor_sample_test~23`, thread=23]
2023-09-01T00:00:32.524986Z C i.q.c.w.ApplyWal2TableJob job failed, table suspended [table=sensor_sample_test~23, error=could not msync, errno=22]
2023-09-01T00:00:41.640358Z I pg-server scheduling disconnect [fd=34, reason=15]
2023-09-01T00:00:41.640450Z I pg-server disconnected [ip=127.0.0.1, fd=34, src=queue]
2023-09-01T00:00:41.643122Z I pg-server connected [ip=127.0.0.1, fd=34]
```

### To reproduce

_No response_

### Expected Behavior

_No response_

### Environment

```markdown
- **QuestDB version**: 7.3.1
- **OS**:
- **Browser**:
```

### Additional context

_No response_

### PR DESCRIPTION
**Pull request by puzpuzpuz**
Fixes #3701

### CODE REVIEW

**Comment by ideoma** [comment]
#### [PR Coverage check]

:heart_eyes: **pass** : 12 / 12 (100.00%)




#### file detail

|   |path|covered line|new line|coverage|
|----|----|----|----|----|
|:large_blue_circle:|io/questdb/cairo/TableUtils.java|6|6|100.00%|
|:large_blue_circle:|io/questdb/cairo/frm/file/ContiguousFileVarFrameColumn.java|4|4|100.00%|
|:large_blue_circle:|io/questdb/cairo/frm/file/ContiguousFileFixFrameColumn.java|2|2|100.00%|

**Comment by ideoma** [comment]
#### [PR Coverage check]

:heart_eyes: **pass** : 12 / 12 (100.00%)




#### file detail

|   |path|covered line|new line|coverage|
|----|----|----|----|----|
|:large_blue_circle:|io/questdb/cairo/TableUtils.java|6|6|100.00%|
|:large_blue_circle:|io/questdb/cairo/frm/file/ContiguousFileVarFrameColumn.java|4|4|100.00%|
|:large_blue_circle:|io/questdb/cairo/frm/file/ContiguousFileFixFrameColumn.java|2|2|100.00%|

**Comment by ideoma** [comment]
#### [PR Coverage check]

:heart_eyes: **pass** : 12 / 12 (100.00%)




#### file detail

|   |path|covered line|new line|coverage|
|----|----|----|----|----|
|:large_blue_circle:|io/questdb/cairo/TableUtils.java|6|6|100.00%|
|:large_blue_circle:|io/questdb/cairo/frm/file/ContiguousFileVarFrameColumn.java|4|4|100.00%|
|:large_blue_circle:|io/questdb/cairo/frm/file/ContiguousFileFixFrameColumn.java|2|2|100.00%|

**Review by bluestreak01 — APPROVED** [review]

**Comment by ideoma** [comment]
#### [PR Coverage check]

:heart_eyes: **pass** : 10 / 12 (83.33%)




#### file detail

|   |path|covered line|new line|coverage|
|----|----|----|----|----|
|:large_blue_circle:|io/questdb/cairo/frm/file/ContiguousFileFixFrameColumn.java|1|2|50.00%|
|:large_blue_circle:|io/questdb/cairo/frm/file/ContiguousFileVarFrameColumn.java|3|4|75.00%|
|:large_blue_circle:|io/questdb/cairo/TableUtils.java|6|6|100.00%|

**Pull request merged**
