### PR TITLE
feat(sql): allow comparisons between geohash and string, for chars notation

### PR DESCRIPTION
**Pull request by marregui**

### CODE REVIEW

**Comment by ideoma** [comment]
#### [PR Coverage check]

:heart_eyes: **pass** : 8 / 10 (80.00%)




#### file detail

|   |path|covered line|new line|coverage|
|----|----|----|----|----|
|:large_blue_circle:|io/questdb/griffin/engine/functions/eq/EqStrGeoHashFunctionFactory.java|3|5|60.00%|
|:large_blue_circle:|io/questdb/griffin/engine/functions/eq/EqGeoHashStrFunctionFactory.java|5|5|100.00%|

**Comment by ideoma** [comment]
#### [PR Coverage check]

:heart_eyes: **pass** : 8 / 10 (80.00%)




#### file detail

|   |path|covered line|new line|coverage|
|----|----|----|----|----|
|:large_blue_circle:|io/questdb/griffin/engine/functions/eq/EqStrGeoHashFunctionFactory.java|3|5|60.00%|
|:large_blue_circle:|io/questdb/griffin/engine/functions/eq/EqGeoHashStrFunctionFactory.java|5|5|100.00%|

**Review by bluestreak01 — APPROVED** [review]

**Comment by ideoma** [comment]
#### [PR Coverage check]

:heart_eyes: **pass** : 8 / 10 (80.00%)




#### file detail

|   |path|covered line|new line|coverage|
|----|----|----|----|----|
|:large_blue_circle:|io/questdb/griffin/engine/functions/eq/EqStrGeoHashFunctionFactory.java|3|5|60.00%|
|:large_blue_circle:|io/questdb/griffin/engine/functions/eq/EqGeoHashStrFunctionFactory.java|5|5|100.00%|

**Comment by ideoma** [comment]
#### [PR Coverage check]

:heart_eyes: **pass** : 8 / 10 (80.00%)




#### file detail

|   |path|covered line|new line|coverage|
|----|----|----|----|----|
|:large_blue_circle:|io/questdb/griffin/engine/functions/eq/EqStrGeoHashFunctionFactory.java|3|5|60.00%|
|:large_blue_circle:|io/questdb/griffin/engine/functions/eq/EqGeoHashStrFunctionFactory.java|5|5|100.00%|

**Comment by ideoma** [comment]
#### [PR Coverage check]

:heart_eyes: **pass** : 8 / 10 (80.00%)




#### file detail

|   |path|covered line|new line|coverage|
|----|----|----|----|----|
|:large_blue_circle:|io/questdb/griffin/engine/functions/eq/EqStrGeoHashFunctionFactory.java|3|5|60.00%|
|:large_blue_circle:|io/questdb/griffin/engine/functions/eq/EqGeoHashStrFunctionFactory.java|5|5|100.00%|

**Comment by ideoma** [comment]
#### [PR Coverage check]

:heart_eyes: **pass** : 8 / 10 (80.00%)




#### file detail

|   |path|covered line|new line|coverage|
|----|----|----|----|----|
|:large_blue_circle:|io/questdb/griffin/engine/functions/eq/EqStrGeoHashFunctionFactory.java|3|5|60.00%|
|:large_blue_circle:|io/questdb/griffin/engine/functions/eq/EqGeoHashStrFunctionFactory.java|5|5|100.00%|

**Comment by ideoma** [comment]
#### [PR Coverage check]

:heart_eyes: **pass** : 8 / 10 (80.00%)




#### file detail

|   |path|covered line|new line|coverage|
|----|----|----|----|----|
|:large_blue_circle:|io/questdb/griffin/engine/functions/eq/EqStrGeoHashFunctionFactory.java|3|5|60.00%|
|:large_blue_circle:|io/questdb/griffin/engine/functions/eq/EqGeoHashStrFunctionFactory.java|5|5|100.00%|

**Comment by ideoma** [comment]
#### [PR Coverage check]

:heart_eyes: **pass** : 8 / 10 (80.00%)




#### file detail

|   |path|covered line|new line|coverage|
|----|----|----|----|----|
|:large_blue_circle:|io/questdb/griffin/engine/functions/eq/EqStrGeoHashFunctionFactory.java|3|5|60.00%|
|:large_blue_circle:|io/questdb/griffin/engine/functions/eq/EqGeoHashStrFunctionFactory.java|5|5|100.00%|

**Comment by ideoma** [comment]
#### [PR Coverage check]

:heart_eyes: **pass** : 8 / 10 (80.00%)




#### file detail

|   |path|covered line|new line|coverage|
|----|----|----|----|----|
|:large_blue_circle:|io/questdb/griffin/engine/functions/eq/EqStrGeoHashFunctionFactory.java|3|5|60.00%|
|:large_blue_circle:|io/questdb/griffin/engine/functions/eq/EqGeoHashStrFunctionFactory.java|5|5|100.00%|

**Comment by ideoma** [comment]
#### [PR Coverage check]

:heart_eyes: **pass** : 8 / 10 (80.00%)




#### file detail

|   |path|covered line|new line|coverage|
|----|----|----|----|----|
|:large_blue_circle:|io/questdb/griffin/engine/functions/eq/EqStrGeoHashFunctionFactory.java|3|5|60.00%|
|:large_blue_circle:|io/questdb/griffin/engine/functions/eq/EqGeoHashStrFunctionFactory.java|5|5|100.00%|

**Pull request merged**
