### PR TITLE
feat(cairo): Implemented write amplification metric in TableWriter.

### PR DESCRIPTION
**Pull request by amunra**
# New `physically_written_rows` metric

This change introduces a new metric `physically_written_rows` accessible within Prometheus that tracks the number of rows physically written to disk during insertions. This can be greater than the number of commited rows when records arrive out of order and partitions need to be re-written.
This allows us to calculate a database-wide write amplification metric using the pre-existing `committed_rows` metric.
In Prometheus: `write_amplification_rows = physically_written_rows / committed_rows`.

### CODE REVIEW

**Comment by ideoma** [comment]
#### [PR Coverage check]

:heart_eyes: **pass** : 25 / 25 (100.00%)




#### file detail

|   |path|covered line|new line|coverage|
|----|----|----|----|----|
|:large_blue_circle:|io/questdb/cairo/TableWriterMetrics.java|8|8|100.00%|
|:large_blue_circle:|io/questdb/cairo/O3PartitionJob.java|5|5|100.00%|
|:large_blue_circle:|io/questdb/cairo/O3OpenColumnJob.java|3|3|100.00%|
|:large_blue_circle:|io/questdb/cairo/TableWriter.java|9|9|100.00%|

**Comment by ideoma** [comment]
#### [PR Coverage check]

:heart_eyes: **pass** : 25 / 25 (100.00%)




#### file detail

|   |path|covered line|new line|coverage|
|----|----|----|----|----|
|:large_blue_circle:|io/questdb/cairo/TableWriterMetrics.java|8|8|100.00%|
|:large_blue_circle:|io/questdb/cairo/O3PartitionJob.java|5|5|100.00%|
|:large_blue_circle:|io/questdb/cairo/O3OpenColumnJob.java|3|3|100.00%|
|:large_blue_circle:|io/questdb/cairo/TableWriter.java|9|9|100.00%|

**Comment by bluestreak01** [comment]
Hey Adam, is this metric available via Promethius endpoint? https://questdb.io/docs/third-party-tools/prometheus/

**Comment by ideoma** [comment]
#### [PR Coverage check]

:heart_eyes: **pass** : 25 / 25 (100.00%)




#### file detail

|   |path|covered line|new line|coverage|
|----|----|----|----|----|
|:large_blue_circle:|io/questdb/cairo/TableWriterMetrics.java|8|8|100.00%|
|:large_blue_circle:|io/questdb/cairo/O3PartitionJob.java|5|5|100.00%|
|:large_blue_circle:|io/questdb/cairo/O3OpenColumnJob.java|3|3|100.00%|
|:large_blue_circle:|io/questdb/cairo/TableWriter.java|9|9|100.00%|

**Review by ideoma — COMMENTED** [review]
Please add tests with commit lag

**Comment by amunra** [comment]
> Please add tests with commit lag

Done.

**Comment by ideoma** [comment]
#### [PR Coverage check]

:heart_eyes: **pass** : 25 / 25 (100.00%)




#### file detail

|   |path|covered line|new line|coverage|
|----|----|----|----|----|
|:large_blue_circle:|io/questdb/cairo/TableWriterMetrics.java|8|8|100.00%|
|:large_blue_circle:|io/questdb/cairo/O3PartitionJob.java|5|5|100.00%|
|:large_blue_circle:|io/questdb/cairo/O3OpenColumnJob.java|3|3|100.00%|
|:large_blue_circle:|io/questdb/cairo/TableWriter.java|9|9|100.00%|

**Review by ideoma — APPROVED** [review]
Looks good.

We would be much better to have amplification per table though. A separate PR would be fine for that

**Pull request merged**
