### PR TITLE
chore(core): allow disabling query caches

### PR DESCRIPTION
**Pull request by puzpuzpuz**
Documentation PR: https://github.com/questdb/questdb.io/pull/663

We suggested setting associative cache settings to `1` in #1680, yet the `AssociativeCache` class was adjusting that to higher values. This PR changes the class to allow single entry cache size, disabling the cache effectively. Also updates `IntLongAssociativeCacheTest` for the sake of consistency.

Also includes the following:
* Clean up query cache setting names and default values. **Note**: there are some breaking naming changes for the settings.
* Introduce `.enabled` settings to allow disabling query caches
* Refactor `AssociativeCache#put()`

### CODE REVIEW

**Comment by bluestreak01** [comment]
Some QuestDB clients, such as python and grafana will never take advantage of caching SQL execution plans. Perhaps we should introduce simple switches such as:

- none
- moderate
- high
- custom 


For cache sizes. For most people it is hard to wrap their head around our caching mechanism. I feel we could simplify that

**Comment by ideoma** [comment]
#### [PR Coverage check]

:heart_eyes: **pass** : 2 / 2 (100.00%)




#### file detail

|   |path|covered line|new line|coverage|
|----|----|----|----|----|
|:large_blue_circle:|io/questdb/std/AssociativeCache.java|1|1|100.00%|
|:large_blue_circle:|io/questdb/std/IntLongAssociativeCache.java|1|1|100.00%|

**Comment by puzpuzpuz** [comment]
> Perhaps we should introduce simple switches

That makes sense to me. I'd propose to introduce `pg.factory.cache.enabled` and `cairo.cache.enabled` flags, without `moderate`/`high`/`custom`. Values like `moderate` and `high` are very subjective and depend on the exact user application.

**Comment by ideoma** [comment]
#### [PR Coverage check]

:heart_eyes: **pass** : 2 / 2 (100.00%)




#### file detail

|   |path|covered line|new line|coverage|
|----|----|----|----|----|
|:large_blue_circle:|io/questdb/std/AssociativeCache.java|1|1|100.00%|
|:large_blue_circle:|io/questdb/std/IntLongAssociativeCache.java|1|1|100.00%|

**Comment by puzpuzpuz** [comment]
Pushed the following changes:
* Refactor `AssociativeCache#put()` - 093d709055bbaf8a6cb45246d5b83457129c43d1
* Clean up query cache setting names and default values - 0a1bba0f4afdb6bd808e9e02453eac0b88ae4d06
* Introduce `.enabled` settings to allow disabling query caches - afbdfcb72b7f91812f93a1a1233072bdd77cfde4

Going to submit a follow-up PR with doc changes

**Comment by ideoma** [comment]
#### [PR Coverage check]

:heart_eyes: **pass** : 37 / 38 (97.37%)




#### file detail

|   |path|covered line|new line|coverage|
|----|----|----|----|----|
|:large_blue_circle:|io/questdb/std/AssociativeCache.java|10|11|90.91%|
|:large_blue_circle:|io/questdb/cutlass/http/DefaultHttpServerConfiguration.java|3|3|100.00%|
|:large_blue_circle:|io/questdb/cutlass/pgwire/DefaultPGWireConfiguration.java|2|2|100.00%|
|:large_blue_circle:|io/questdb/cutlass/http/processors/QueryCache.java|4|4|100.00%|
|:large_blue_circle:|io/questdb/cutlass/pgwire/PGJobContext.java|5|5|100.00%|
|:large_blue_circle:|io/questdb/PropServerConfiguration.java|7|7|100.00%|
|:large_blue_circle:|io/questdb/cutlass/pgwire/PGConnectionContext.java|5|5|100.00%|
|:large_blue_circle:|io/questdb/std/IntLongAssociativeCache.java|1|1|100.00%|

**Comment by ideoma** [comment]
#### [PR Coverage check]

:heart_eyes: **pass** : 37 / 38 (97.37%)




#### file detail

|   |path|covered line|new line|coverage|
|----|----|----|----|----|
|:large_blue_circle:|io/questdb/std/AssociativeCache.java|10|11|90.91%|
|:large_blue_circle:|io/questdb/cutlass/http/DefaultHttpServerConfiguration.java|3|3|100.00%|
|:large_blue_circle:|io/questdb/cutlass/pgwire/DefaultPGWireConfiguration.java|2|2|100.00%|
|:large_blue_circle:|io/questdb/cutlass/http/processors/QueryCache.java|4|4|100.00%|
|:large_blue_circle:|io/questdb/cutlass/pgwire/PGJobContext.java|5|5|100.00%|
|:large_blue_circle:|io/questdb/PropServerConfiguration.java|7|7|100.00%|
|:large_blue_circle:|io/questdb/cutlass/pgwire/PGConnectionContext.java|5|5|100.00%|
|:large_blue_circle:|io/questdb/std/IntLongAssociativeCache.java|1|1|100.00%|

**Review by bluestreak01 — APPROVED** [review]

**Comment by ideoma** [comment]
#### [PR Coverage check]

:heart_eyes: **pass** : 37 / 38 (97.37%)




#### file detail

|   |path|covered line|new line|coverage|
|----|----|----|----|----|
|:large_blue_circle:|io/questdb/std/AssociativeCache.java|10|11|90.91%|
|:large_blue_circle:|io/questdb/cutlass/http/DefaultHttpServerConfiguration.java|3|3|100.00%|
|:large_blue_circle:|io/questdb/cutlass/pgwire/DefaultPGWireConfiguration.java|2|2|100.00%|
|:large_blue_circle:|io/questdb/cutlass/http/processors/QueryCache.java|4|4|100.00%|
|:large_blue_circle:|io/questdb/cutlass/pgwire/PGJobContext.java|5|5|100.00%|
|:large_blue_circle:|io/questdb/PropServerConfiguration.java|7|7|100.00%|
|:large_blue_circle:|io/questdb/cutlass/pgwire/PGConnectionContext.java|5|5|100.00%|
|:large_blue_circle:|io/questdb/std/IntLongAssociativeCache.java|1|1|100.00%|

**Comment by ideoma** [comment]
#### [PR Coverage check]

:heart_eyes: **pass** : 37 / 38 (97.37%)




#### file detail

|   |path|covered line|new line|coverage|
|----|----|----|----|----|
|:large_blue_circle:|io/questdb/std/AssociativeCache.java|10|11|90.91%|
|:large_blue_circle:|io/questdb/cutlass/http/DefaultHttpServerConfiguration.java|3|3|100.00%|
|:large_blue_circle:|io/questdb/cutlass/pgwire/DefaultPGWireConfiguration.java|2|2|100.00%|
|:large_blue_circle:|io/questdb/cutlass/http/processors/QueryCache.java|4|4|100.00%|
|:large_blue_circle:|io/questdb/cutlass/pgwire/PGJobContext.java|5|5|100.00%|
|:large_blue_circle:|io/questdb/PropServerConfiguration.java|7|7|100.00%|
|:large_blue_circle:|io/questdb/cutlass/pgwire/PGConnectionContext.java|5|5|100.00%|
|:large_blue_circle:|io/questdb/std/IntLongAssociativeCache.java|1|1|100.00%|

**Pull request merged**
