### PR TITLE
fix(sql): fix designated timestamp in `WhereClauseParser` when using epoch

### LINKED ISSUE #874: Designated timestamps cannot be directly compared to epoch microseconds
Non designated fields of type timestamp can be directly compared to an integer value representing the epoch time in microseconds, thus

`select * from x where ts<1616170125000000`

However, for designated timestamps this does not work, you need to first cast to timestamp, thus

`select * from x where ts<cast(1616170125000000 as timestamp)`

or

`select * from x where cast(ts as timestamp)<1616170125000000`

### PR DESCRIPTION
**Pull request by stephenspol**
Added more checks before throwing an error when comparing against less than, greater than, equal and not equal to equate for epoch.

Fixes #874.

### CODE REVIEW

**Comment by bluestreak01** [comment]
@stephenspol `master` branch contains only code reformatting, if merge conflicts are too much you can go with accepting your changes and ignoring master

**Comment by bziobrowski** [comment]
I found the following side-effects : 
- "ts in 2020" works as "ts = 2020" but  "ts in ( 2020, 2021)" returns 'invalid date'  . ts in (2020::timestamp, 2021:timestamp) works . 
- ts = expression  doesn't work while it works fine for non-designated timestamp columns, e.g. 
ts = rnd_long()  returns 'invalid date'
while 
nonts = rnd_long() 
and
ts = rnd_long()::timestamp
work fine .

**Comment by stephenspol** [comment]
> Hi @stephenspol . I found the following side-effects :
> 
> * `ts in 2020` works as `ts = 2020`
>   but  `ts in ( 2020, 2021)` returns `invalid date`  . `ts in (2020::timestamp, 2021:timestamp)` works .
> * between doesn't work, e.g. ts between 100 and 200
> * ts = expression  doesn't work while it works fine for non-designated timestamp columns, e.g.
>   `ts = rnd_long()`  returns 'invalid date'
>   while
>   `nonts = rnd_long()`
>   and
>   `ts = rnd_long()::timestamp`
>   work fine .

Thanks for the feedback. I will take a look.

**Comment by stephenspol** [comment]
I have implemented the features listed above and provided tests for them. Please let me know if you would like more tests or more features.

Also, I was curious on how `in` interval would work with a single epoch timestamp as the range can vary greatly. Right now it is setup to return the same timestamp for both the high and low.

```
    @Test
    public void testEqualsToEpochInterval() throws Exception {
        runWhereTest("timestamp in 1424649600000000",
                "[{lo=2015-02-23T00:00:00.000000Z, hi=2015-02-23T00:00:00.000000Z}]");
    }
```

**Comment by bziobrowski** [comment]
Hi @stephenspol  . Code looks fine ! 
Could you add one last test for IN operator with multiple log args ?

**Comment by stephenspol** [comment]
I added a new test for `IN` interval. Let me know if this is the one you were expecting.

**Review by bziobrowski — APPROVED** [review]
👍

**Pull request merged**
