### PR TITLE
Add tar setting for maven assemble plugin

### PR DESCRIPTION
**Pull request by aahmed-se**
Signed-off-by: Ali Ahmed alahmed.se@gmail.com

### CODE REVIEW

**Comment by bluestreak01** [comment]
thanks! which platform did it fail on?

**Comment by aahmed-se** [comment]
OSX

**Comment by rhmrsioymd-pixel** [comment]
Ahmed Hridoy

**Comment by rhmrsioymd-pixel** [comment]
IMG_1885
Ahmed Hridoy

**Pull request merged**
