### PR TITLE
fix(sql): fix order by aliased column positions

### PR DESCRIPTION
**Pull request by puzpuzpuz**
Fixes positional ORDER BY in combination with column aliases. Such
combination was leading to a translating model being used to look
up the ORDER BY columns. Due to their nature, translating models
may not contain the full list of columns, so such queries ended up
with either "order column position is out of range" error or an NPE
in SqlOptimiser#getOrderByAdvice.

### CODE REVIEW

**Comment by ideoma** [comment]
#### [PR Coverage check]

:heart_eyes: **pass** : 8 / 8 (100.00%)




#### file detail

|   |path|covered line|new line|coverage|
|----|----|----|----|----|
|:large_blue_circle:|io/questdb/griffin/SqlOptimiser.java|3|3|100.00%|
|:large_blue_circle:|io/questdb/griffin/model/QueryModel.java|5|5|100.00%|

**Review by ideoma — DISMISSED** [review]
minor: would be good to add few more tests with real data

**Comment by puzpuzpuz** [comment]
> minor: would be good to add few more tests with real data

Good idea. Added a few integration tests in 40744f82b2b82023dbc9c27f85cd8f2d965d8ac6

**Comment by ideoma** [comment]
#### [PR Coverage check]

:heart_eyes: **pass** : 8 / 8 (100.00%)




#### file detail

|   |path|covered line|new line|coverage|
|----|----|----|----|----|
|:large_blue_circle:|io/questdb/griffin/SqlOptimiser.java|3|3|100.00%|
|:large_blue_circle:|io/questdb/griffin/model/QueryModel.java|5|5|100.00%|

**Review by ideoma — APPROVED** [review]

**Comment by ideoma** [comment]
#### [PR Coverage check]

:heart_eyes: **pass** : 8 / 8 (100.00%)




#### file detail

|   |path|covered line|new line|coverage|
|----|----|----|----|----|
|:large_blue_circle:|io/questdb/griffin/SqlOptimiser.java|3|3|100.00%|
|:large_blue_circle:|io/questdb/griffin/model/QueryModel.java|5|5|100.00%|

**Pull request merged**
