### PR TITLE
fix(sql): fix incorrect results from limit queries

### LINKED ISSUE #3081: ORDER BY TIMESTAMP DESC issues / crashes
### Describe the bug

Experiencing some unexpected behavior when using `order by timestamp desc`, including result counts that do not match what I expect and sometimes causes crashes of the QuestDB server

I have attached the logs for the quest server that include the crashes.

[LOGS.zip](https://github.com/questdb/questdb/files/11031934/LOGS.zip)

### To reproduce

I have attached a Gradle project that can be run with `./gradlew runSortDescRepro`

The source code is currently (but may change as I haven't gotten the same behavior as my actual system just yet):

[test-questdb.zip](https://github.com/questdb/questdb/files/11031913/test-questdb.zip)

```
package test.questdb;

import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.time.Instant;
import java.time.ZoneOffset;
import java.time.format.DateTimeFormatter;
import java.util.HashSet;
import java.util.Properties;
import java.util.Random;
import java.util.Set;
import io.questdb.client.Sender;

public class QuestDbSortDescRepro {

  // edit as needed
  static final String QUESTDB_ILP_ADDRESS = "questdb:9009";
  static final String QUESTDB_QUERY_JDBC_URL = "jdbc:postgresql://questdb:8812/qdb";
  static final Properties QUESTDB_QUERY_JDBC_PROPS = new Properties();
  static {
    QUESTDB_QUERY_JDBC_PROPS.put("user", "admin");
    QUESTDB_QUERY_JDBC_PROPS.put("password", "quest");
    QUESTDB_QUERY_JDBC_PROPS.put("sslmode", "disable");
  }

  static final String TABLE = "sort-desc-repro-3";
  
  static final String COL_ID = "id";
  static final String COL_LINKED_ID = "linkedId";
  static final String COL_STR_1 = "stringCol1";
  static final String COL_STR_2 = "stringCol2";
  static final String COL_DESC = "description";
  static final String COL_ACTIVE = "active";
  static final String COL_WHEN_START = "whenStartMs";
  static final String COL_WHEN_END = "whenEndMs";
  static final String COL_DESIGNATED_TIMESTAMP = "timestamp";

  static final Random RAND = new Random(System.currentTimeMillis());

  static final String[] IDS = genStrings(16, "generated-id-");
  static final String[] LINKED_IDS = genLinkedIds(IDS);
  static final String[] STR1_VALS = genStrings(8, "STR1-");
  static final String[] STR2_VALS = genStrings(4, "STR1-");

  static long minTimeMs = 0L;

  static String[] genStrings(int n, String base) {
    String[] out = new String[n];
    for (int j = 0; j < n; j++) {
      out[j] = base + j;
    }
    return out;
  }

  static String[] genLinkedIds(String[] idsBase) {
    String[] out = new String[idsBase.length];
    for (int j = 0; j < idsBase.length; j++) {
      out[j] = "linkedId-" + idsBase[j];
    }
    return out;
  }

  static String randString(int minLen, int maxLen) {
    StringBuilder buf = new StringBuilder();
    int len = RAND.nextInt(minLen, maxLen + 1);
    for (int j = 0; j < len; j++) {
      if (minLen > 10 && RAND.nextDouble() > 0.8) {
        // sometimes append a UTF-8 character
        buf.append("ü");
      } else {
        // A-Z, a-z
        buf.append((char) (RAND.nextBoolean() ? RAND.nextInt(0x41, 0x5B) : RAND.nextInt(0x61, 0x7b)));
      }
    }
    return buf.toString();
  }

  static <T> T randValue(T[] arr) {
    return arr[RAND.nextInt(0, arr.length)];
  }

  static final String t() {
    return String.format("[%-30s] ", Instant.now().atOffset(ZoneOffset.UTC).toString());
  }

  static void log(String fmt, Object... args) {
    System.out.printf(t() + fmt + "%n", args);
  }

  static void insertRow(int row, Sender ilp, Set<Long> allTimestamps) throws Exception {
    String id = randValue(IDS);
    String linkedId = randValue(LINKED_IDS);
    String desc = randString(32, 256);
    String str1 = randValue(STR1_VALS);
    String str2 = randValue(STR2_VALS);
    boolean active = RAND.nextBoolean();
    Long whenStartMs = System.currentTimeMillis() + RAND.nextInt(1, 1 + row);
    if (row > 2000) {
      whenStartMs += 300L;
    }
    if (minTimeMs == 0L || whenStartMs < minTimeMs) {
      minTimeMs = whenStartMs;
    }
    // mostly null
    Long whenEndMs = RAND.nextDouble() > 0.9 ? whenStartMs + RAND.nextLong(1000L, 2000L) : null;
    long tsNanos = whenStartMs * 1_000_000L;
    allTimestamps.add(tsNanos);
    ilp = ilp
        .table(TABLE)
        .symbol(COL_ID, id)
        .symbol(COL_LINKED_ID, linkedId)
        .stringColumn(COL_DESC, desc)
        .stringColumn(COL_STR_1, str1)
        .stringColumn(COL_STR_2, str2)
        .boolColumn(COL_ACTIVE, active)
        .longColumn(COL_WHEN_START, whenStartMs);
    if (whenEndMs != null) {
      ilp = ilp.longColumn(COL_WHEN_END, whenEndMs);
    }
    ilp.at(tsNanos);
  }

  static void insertData(int nRows) throws Exception {
    Set<Long> allTimestamps = new HashSet<>();
    try (Sender ilp = Sender.builder().address(QUESTDB_ILP_ADDRESS).build()) {
      log("insert [%d] rows into table [" + TABLE + "] ...", nRows);
      for (int j = 1; j <= nRows; j++) {
        insertRow(j, ilp, allTimestamps);
      }
      ilp.flush();
      log("insert [%d] rows - DONE [%d] unique timestamps", nRows, allTimestamps.size());
    }
    log("wait 5s for inserted data to settle ...");
    Thread.sleep(5000L);
    log("exit insertData()");
  }

  static int getCountStar(String query) throws Exception {
    int count = -1;
    try(Connection conn = DriverManager.getConnection(QUESTDB_QUERY_JDBC_URL, QUESTDB_QUERY_JDBC_PROPS);
        PreparedStatement stmt = conn.prepareStatement(query)) {
      log(" run query [%s] ...", stmt);
      try(ResultSet result = stmt.executeQuery()) {
        if (result.next()) {
          count = result.getInt(1);
        }
      }
      log(" query [%s] completed: count:[%d]", stmt, count);
    }
    return count;
  }

  static int getRowCount(String query) throws Exception {
    int count = 0;
    try(Connection conn = DriverManager.getConnection(QUESTDB_QUERY_JDBC_URL, QUESTDB_QUERY_JDBC_PROPS);
        PreparedStatement stmt = conn.prepareStatement(query)) {
      stmt.setFetchSize(100_000);
      log(" run query [%s] ...", stmt);
      try(ResultSet result = stmt.executeQuery()) {
        while(result.next()) {
          count++;
        }
      }
    } catch(Exception e) {
      log("  %n  ##### UNEXPECTED ERROR %s #####%n", e);
      e.printStackTrace();
      return -1;
    }
    log(" query [%s] completed: count:[%d]", query, count);
    return count;
  }

  static void performQueries() throws Exception {
    DateTimeFormatter timeFormat = DateTimeFormatter.ofPattern(
        "yyyy-MM-dd'T'HH:mm:ss.SSS'Z'");
    String queryTimeFilter = timeFormat.format(
        Instant.ofEpochMilli(minTimeMs - (2 * 86_400_000L) )
        .atOffset(ZoneOffset.UTC));
    String queryBase = "select * from '" + TABLE
        + "' WHERE timestamp >= '" + queryTimeFilter + "' ORDER BY " + COL_DESIGNATED_TIMESTAMP + " ";

    int countStar = getCountStar("SELECT COUNT(*) FROM '" + TABLE + "'");
    int ascCount = getRowCount(queryBase + "ASC");
    int ascLimitCount = getRowCount(queryBase + "ASC LIMIT 100000");
    int descLimitCount = getRowCount(queryBase + "DESC LIMIT 100000");
    int descCount = getRowCount(queryBase + "DESC");

    boolean allEqual = countStar == descCount
        && descCount == descLimitCount && descCount == ascCount && descCount == ascLimitCount;
    log("%n -- QUERY RESULTS -- %n"
        + "  count(*)       = [%d]%n"
        + "  descCount      = [%d]%n"
        + "  descLimitCount = [%d]%n"
        + "  ascCount       = [%d]%n"
        + "  ascLimitCount  = [%d]%n"
        + "  allEqual       = [%b]%n"
        + " -----------------%n",
        countStar, descCount, descLimitCount, ascCount, ascLimitCount, allEqual);
  }

  public static void main(String[] args) {
    int exitCode = 0;
    log("enter");
    try {
      insertData(RAND.nextInt(4096, 8192));
      log("%n performing queries ...%n%n");
      performQueries();
    } catch (Throwable t) {
      t.printStackTrace();
      exitCode = 1;
    }
    log("exit");
    System.exit(exitCode);
  }
}
```

### Expected Behavior

All query counts are equal

Actual shows that at minimum the desc limit count is usually 0 or sometimes causes an EOF error on the JDBC connection and a crash on the QuestDB server.

e.g.
```
 -- QUERY RESULTS --
  count(*)       = [35732]
  descCount      = [35732]
  descLimitCount = [0]
  ascCount       = [35732]
  ascLimitCount  = [35732]
  allEqual       = [false]
 -----------------
```

### Environment

```markdown
- **QuestDB version**: 7.0.1 - Docker Image
- **OS**: Amazon Linux
- **Browser**: N/A (Java ILP Client, JDBC Postgres Query Client)
```

### Additional context

_No response_

### PR DESCRIPTION
**Pull request by bluestreak01**
fixes #3081

Todo: tests, convert data and queries from repro to unit test. Stress test binary search

### CODE REVIEW

**Comment by ideoma** [comment]
#### [PR Coverage check]

:heart_eyes: **pass** : 22 / 37 (59.46%)




#### file detail

|   |path|covered line|new line|coverage|
|----|----|----|----|----|
|:large_blue_circle:|io/questdb/cairo/AbstractIntervalDataFrameCursor.java|22|37|59.46%|

**Comment by ideoma** [comment]
#### [PR Coverage check]

:heart_eyes: **pass** : 37 / 37 (100.00%)




#### file detail

|   |path|covered line|new line|coverage|
|----|----|----|----|----|
|:large_blue_circle:|io/questdb/cairo/AbstractIntervalDataFrameCursor.java|37|37|100.00%|

**Comment by ideoma** [comment]
#### [PR Coverage check]

:heart_eyes: **pass** : 4 / 4 (100.00%)




#### file detail

|   |path|covered line|new line|coverage|
|----|----|----|----|----|
|:large_blue_circle:|io/questdb/cairo/AbstractIntervalDataFrameCursor.java|4|4|100.00%|

**Comment by ideoma** [comment]
#### [PR Coverage check]

:heart_eyes: **pass** : 4 / 4 (100.00%)




#### file detail

|   |path|covered line|new line|coverage|
|----|----|----|----|----|
|:large_blue_circle:|io/questdb/cairo/AbstractIntervalDataFrameCursor.java|4|4|100.00%|

**Review by ideoma — APPROVED** [review]

**Comment by ideoma** [comment]
#### [PR Coverage check]

:heart_eyes: **pass** : 4 / 4 (100.00%)




#### file detail

|   |path|covered line|new line|coverage|
|----|----|----|----|----|
|:large_blue_circle:|io/questdb/cairo/AbstractIntervalDataFrameCursor.java|4|4|100.00%|

**Review by bziobrowski — APPROVED** [review]

**Pull request merged**
