### PR TITLE
Create Mindsdb_database integration.py

### PR DESCRIPTION
**Pull request by Adarsh357**
Pls accept this pull request

### CODE REVIEW

**Comment by Adarsh357** [comment]
Check this pull request and accept it

**Comment by marregui** [comment]
Hi @Adarsh357 ,

Thank you for the contribution. What does it do?, how would it be tested?, how would it be used?, is the python code  a rewrite of an existing class somewhere?

Thank you in advance!

**Comment by Adarsh357** [comment]
Yes, it is used for integration in database

**Comment by marregui** [comment]
hi @Adarsh357 

I really do, but I think the approach is going to be to merge the change onto the mindsdb repo. I am somewhat familiar with it. Would you please address these questions specifically:

1.- What does the contribution do? 
2.- How would it be tested? 
3.- How would it be used? 
4.- Is the python code a rewrite of an existing class somewhere?

gracias !

**Comment by ideoma** [comment]
I'm converting this PR to draft until the questions from @marregui are answered

**Pull request closed without merging**
