### PR TITLE
chore(cairo): added Row API to put geohash value from coordinates in degrees

### PR DESCRIPTION
**Pull request by bluestreak01**

### CODE REVIEW

**Comment by ideoma** [comment]
#### [PR Coverage check]

:heart_eyes: **pass** : 5 / 5 (100.00%)




#### file detail

|   |path|covered line|new line|coverage|
|----|----|----|----|----|
|:large_blue_circle:|io/questdb/griffin/engine/functions/geohash/GeoHashFromCoordinatesFunctionFactory.java|1|1|100.00%|
|:large_blue_circle:|io/questdb/std/Rnd.java|1|1|100.00%|
|:large_blue_circle:|io/questdb/cairo/GeoHashes.java|3|3|100.00%|

**Comment by ideoma** [comment]
#### [PR Coverage check]

:heart_eyes: **pass** : 5 / 5 (100.00%)




#### file detail

|   |path|covered line|new line|coverage|
|----|----|----|----|----|
|:large_blue_circle:|io/questdb/griffin/engine/functions/geohash/GeoHashFromCoordinatesFunctionFactory.java|1|1|100.00%|
|:large_blue_circle:|io/questdb/std/Rnd.java|1|1|100.00%|
|:large_blue_circle:|io/questdb/cairo/GeoHashes.java|3|3|100.00%|

**Comment by ideoma** [comment]
#### [PR Coverage check]

:heart_eyes: **pass** : 5 / 5 (100.00%)




#### file detail

|   |path|covered line|new line|coverage|
|----|----|----|----|----|
|:large_blue_circle:|io/questdb/griffin/engine/functions/geohash/GeoHashFromCoordinatesFunctionFactory.java|1|1|100.00%|
|:large_blue_circle:|io/questdb/std/Rnd.java|1|1|100.00%|
|:large_blue_circle:|io/questdb/cairo/GeoHashes.java|3|3|100.00%|

**Comment by ideoma** [comment]
#### [PR Coverage check]

:heart_eyes: **pass** : 5 / 5 (100.00%)




#### file detail

|   |path|covered line|new line|coverage|
|----|----|----|----|----|
|:large_blue_circle:|io/questdb/griffin/engine/functions/geohash/GeoHashFromCoordinatesFunctionFactory.java|1|1|100.00%|
|:large_blue_circle:|io/questdb/std/Rnd.java|1|1|100.00%|
|:large_blue_circle:|io/questdb/cairo/GeoHashes.java|3|3|100.00%|

**Review by ideoma — APPROVED** [review]

**Review by marregui — APPROVED** [review]
LGTM

**Comment by ideoma** [comment]
#### [PR Coverage check]

:heart_eyes: **pass** : 5 / 5 (100.00%)




#### file detail

|   |path|covered line|new line|coverage|
|----|----|----|----|----|
|:large_blue_circle:|io/questdb/griffin/engine/functions/geohash/GeoHashFromCoordinatesFunctionFactory.java|1|1|100.00%|
|:large_blue_circle:|io/questdb/std/Rnd.java|1|1|100.00%|
|:large_blue_circle:|io/questdb/cairo/GeoHashes.java|3|3|100.00%|

**Comment by ideoma** [comment]
#### [PR Coverage check]

:heart_eyes: **pass** : 5 / 5 (100.00%)




#### file detail

|   |path|covered line|new line|coverage|
|----|----|----|----|----|
|:large_blue_circle:|io/questdb/griffin/engine/functions/geohash/GeoHashFromCoordinatesFunctionFactory.java|1|1|100.00%|
|:large_blue_circle:|io/questdb/std/Rnd.java|1|1|100.00%|
|:large_blue_circle:|io/questdb/cairo/GeoHashes.java|3|3|100.00%|

**Comment by ideoma** [comment]
#### [PR Coverage check]

:heart_eyes: **pass** : 5 / 5 (100.00%)




#### file detail

|   |path|covered line|new line|coverage|
|----|----|----|----|----|
|:large_blue_circle:|io/questdb/griffin/engine/functions/geohash/GeoHashFromCoordinatesFunctionFactory.java|1|1|100.00%|
|:large_blue_circle:|io/questdb/std/Rnd.java|1|1|100.00%|
|:large_blue_circle:|io/questdb/cairo/GeoHashes.java|3|3|100.00%|

**Comment by ideoma** [comment]
#### [PR Coverage check]

:heart_eyes: **pass** : 5 / 5 (100.00%)




#### file detail

|   |path|covered line|new line|coverage|
|----|----|----|----|----|
|:large_blue_circle:|io/questdb/griffin/engine/functions/geohash/GeoHashFromCoordinatesFunctionFactory.java|1|1|100.00%|
|:large_blue_circle:|io/questdb/std/Rnd.java|1|1|100.00%|
|:large_blue_circle:|io/questdb/cairo/GeoHashes.java|3|3|100.00%|

**Comment by ideoma** [comment]
#### [PR Coverage check]

:heart_eyes: **pass** : 5 / 5 (100.00%)




#### file detail

|   |path|covered line|new line|coverage|
|----|----|----|----|----|
|:large_blue_circle:|io/questdb/griffin/engine/functions/geohash/GeoHashFromCoordinatesFunctionFactory.java|1|1|100.00%|
|:large_blue_circle:|io/questdb/std/Rnd.java|1|1|100.00%|
|:large_blue_circle:|io/questdb/cairo/GeoHashes.java|3|3|100.00%|

**Pull request merged**
