### PR TITLE
fix(core): improve compatibility with log-readers by adding config option for verbose log levels

### PR DESCRIPTION
**Pull request by nwoolmer**
Adds a new config option, `log.level.verbose`. This will change the usual terse log levels (I, C, A etc.) to be proper descriptors. This should improve compatibiltiy with log-readers that filter for certain terms.

```
2024-09-13T16:02:31.458444Z INFO i.q.c.CairoEngine metadata hydration completed [tables=14]
2024-09-13T16:02:31.475324Z ADVISORY server-main enjoy
2024-09-13T16:07:31.494075Z INFO i.q.c.p.ReaderPool closed 'sys.column_versions_purge_log' [at=0:0, reason=IDLE]
2024-09-13T16:07:31.500517Z INFO i.q.c.p.ReaderPool closed 'telemetry_config' [at=0:0, reason=IDLE]
2024-09-13T16:07:31.506381Z INFO i.q.c.p.TableMetadataPool closed 'telemetry_config' [at=0:0, reason=IDLE]
```

### CODE REVIEW

**Comment by ideoma** [comment]
#### [PR Coverage check]

:heart_eyes: **pass** : 20 / 26 (76.92%)




#### file detail

|   |path|covered line|new line|coverage|
|----|----|----|----|----|
|:large_blue_circle:|io/questdb/cairo/CairoConfigurationWrapper.java|0|1|00.00%|
|:large_blue_circle:|io/questdb/log/LogLevel.java|15|20|75.00%|
|:large_blue_circle:|io/questdb/Bootstrap.java|1|1|100.00%|
|:large_blue_circle:|io/questdb/PropServerConfiguration.java|2|2|100.00%|
|:large_blue_circle:|io/questdb/cairo/DefaultCairoConfiguration.java|1|1|100.00%|
|:large_blue_circle:|io/questdb/PropertyKey.java|1|1|100.00%|

**Comment by ideoma** [comment]
#### [PR Coverage check]

:heart_eyes: **pass** : 20 / 26 (76.92%)




#### file detail

|   |path|covered line|new line|coverage|
|----|----|----|----|----|
|:large_blue_circle:|io/questdb/cairo/CairoConfigurationWrapper.java|0|1|00.00%|
|:large_blue_circle:|io/questdb/log/LogLevel.java|15|20|75.00%|
|:large_blue_circle:|io/questdb/Bootstrap.java|1|1|100.00%|
|:large_blue_circle:|io/questdb/PropServerConfiguration.java|2|2|100.00%|
|:large_blue_circle:|io/questdb/cairo/DefaultCairoConfiguration.java|1|1|100.00%|
|:large_blue_circle:|io/questdb/PropertyKey.java|1|1|100.00%|

**Comment by ideoma** [comment]
#### [PR Coverage check]

:heart_eyes: **pass** : 20 / 26 (76.92%)




#### file detail

|   |path|covered line|new line|coverage|
|----|----|----|----|----|
|:large_blue_circle:|io/questdb/cairo/CairoConfigurationWrapper.java|0|1|00.00%|
|:large_blue_circle:|io/questdb/log/LogLevel.java|15|20|75.00%|
|:large_blue_circle:|io/questdb/Bootstrap.java|1|1|100.00%|
|:large_blue_circle:|io/questdb/PropServerConfiguration.java|2|2|100.00%|
|:large_blue_circle:|io/questdb/cairo/DefaultCairoConfiguration.java|1|1|100.00%|
|:large_blue_circle:|io/questdb/PropertyKey.java|1|1|100.00%|

**Comment by ideoma** [comment]
#### [PR Coverage check]

:heart_eyes: **pass** : 20 / 26 (76.92%)




#### file detail

|   |path|covered line|new line|coverage|
|----|----|----|----|----|
|:large_blue_circle:|io/questdb/cairo/CairoConfigurationWrapper.java|0|1|00.00%|
|:large_blue_circle:|io/questdb/log/LogLevel.java|15|20|75.00%|
|:large_blue_circle:|io/questdb/Bootstrap.java|1|1|100.00%|
|:large_blue_circle:|io/questdb/PropServerConfiguration.java|2|2|100.00%|
|:large_blue_circle:|io/questdb/cairo/DefaultCairoConfiguration.java|1|1|100.00%|
|:large_blue_circle:|io/questdb/PropertyKey.java|1|1|100.00%|

**Review by bluestreak01 — APPROVED** [review]

**Pull request merged**
