### PR TITLE
chore(core): rework skipTo() and calculateSize() to handle DataUnavailableException

### PR DESCRIPTION
**Pull request by bziobrowski**
PR changes skipTo() [renamed to skipRows()]  and calculateSize() methods to make them work even if cold storage exception is thrown in the middle.

### CODE REVIEW

**Comment by ideoma** [comment]
#### [PR Coverage check]

:heart_eyes: **pass** : 145 / 152 (95.39%)




#### file detail

|   |path|covered line|new line|coverage|
|----|----|----|----|----|
|:large_blue_circle:|io/questdb/griffin/engine/table/FilterOnSubQueryRecordCursorFactory.java|0|1|00.00%|
|:large_blue_circle:|io/questdb/griffin/engine/table/LatestBySubQueryRecordCursorFactory.java|0|1|00.00%|
|:large_blue_circle:|io/questdb/cutlass/http/processors/JsonQueryProcessorState.java|10|13|76.92%|
|:large_blue_circle:|io/questdb/griffin/engine/AbstractVirtualFunctionRecordCursor.java|4|5|80.00%|
|:large_blue_circle:|io/questdb/cairo/sql/RecordCursor.java|17|18|94.44%|
|:large_blue_circle:|io/questdb/cairo/FullBwdDataFrameCursor.java|4|4|100.00%|
|:large_blue_circle:|io/questdb/griffin/engine/table/AsyncFilteredRecordCursor.java|10|10|100.00%|
|:large_blue_circle:|io/questdb/griffin/engine/table/DataFrameRecordCursorImpl.java|9|9|100.00%|
|:large_blue_circle:|io/questdb/griffin/engine/join/CrossJoinRecordCursorFactory.java|60|60|100.00%|
|:large_blue_circle:|io/questdb/griffin/engine/window/WindowRecordCursorFactory.java|2|2|100.00%|
|:large_blue_circle:|io/questdb/griffin/engine/table/LatestByLightRecordCursorFactory.java|2|2|100.00%|
|:large_blue_circle:|io/questdb/cairo/FullFwdDataFrameCursor.java|4|4|100.00%|
|:large_blue_circle:|io/questdb/griffin/engine/table/SelectedRecordCursor.java|2|2|100.00%|
|:large_blue_circle:|io/questdb/griffin/engine/LimitRecordCursorFactory.java|8|8|100.00%|
|:large_blue_circle:|io/questdb/griffin/engine/window/CachedWindowRecordCursorFactory.java|3|3|100.00%|
|:large_blue_circle:|io/questdb/griffin/engine/groupby/CountRecordCursorFactory.java|5|5|100.00%|
|:large_blue_circle:|io/questdb/griffin/engine/union/UnionAllRecordCursor.java|5|5|100.00%|

**Comment by ideoma** [comment]
#### [PR Coverage check]

:heart_eyes: **pass** : 145 / 152 (95.39%)




#### file detail

|   |path|covered line|new line|coverage|
|----|----|----|----|----|
|:large_blue_circle:|io/questdb/griffin/engine/table/FilterOnSubQueryRecordCursorFactory.java|0|1|00.00%|
|:large_blue_circle:|io/questdb/griffin/engine/table/LatestBySubQueryRecordCursorFactory.java|0|1|00.00%|
|:large_blue_circle:|io/questdb/cutlass/http/processors/JsonQueryProcessorState.java|10|13|76.92%|
|:large_blue_circle:|io/questdb/griffin/engine/AbstractVirtualFunctionRecordCursor.java|4|5|80.00%|
|:large_blue_circle:|io/questdb/cairo/sql/RecordCursor.java|17|18|94.44%|
|:large_blue_circle:|io/questdb/cairo/FullBwdDataFrameCursor.java|4|4|100.00%|
|:large_blue_circle:|io/questdb/griffin/engine/table/AsyncFilteredRecordCursor.java|10|10|100.00%|
|:large_blue_circle:|io/questdb/griffin/engine/table/DataFrameRecordCursorImpl.java|9|9|100.00%|
|:large_blue_circle:|io/questdb/griffin/engine/join/CrossJoinRecordCursorFactory.java|60|60|100.00%|
|:large_blue_circle:|io/questdb/griffin/engine/window/WindowRecordCursorFactory.java|2|2|100.00%|
|:large_blue_circle:|io/questdb/griffin/engine/table/LatestByLightRecordCursorFactory.java|2|2|100.00%|
|:large_blue_circle:|io/questdb/cairo/FullFwdDataFrameCursor.java|4|4|100.00%|
|:large_blue_circle:|io/questdb/griffin/engine/table/SelectedRecordCursor.java|2|2|100.00%|
|:large_blue_circle:|io/questdb/griffin/engine/LimitRecordCursorFactory.java|8|8|100.00%|
|:large_blue_circle:|io/questdb/griffin/engine/window/CachedWindowRecordCursorFactory.java|3|3|100.00%|
|:large_blue_circle:|io/questdb/griffin/engine/groupby/CountRecordCursorFactory.java|5|5|100.00%|
|:large_blue_circle:|io/questdb/griffin/engine/union/UnionAllRecordCursor.java|5|5|100.00%|

**Comment by ideoma** [comment]
#### [PR Coverage check]

:heart_eyes: **pass** : 197 / 212 (92.92%)




#### file detail

|   |path|covered line|new line|coverage|
|----|----|----|----|----|
|:large_blue_circle:|io/questdb/cairo/sql/RecordCursor.java|20|28|71.43%|
|:large_blue_circle:|io/questdb/griffin/engine/table/VirtualFunctionDirectSymbolRecordCursor.java|6|8|75.00%|
|:large_blue_circle:|io/questdb/cutlass/http/processors/JsonQueryProcessorState.java|10|13|76.92%|
|:large_blue_circle:|io/questdb/griffin/engine/table/FilterOnSubQueryRecordCursorFactory.java|7|9|77.78%|
|:large_blue_circle:|io/questdb/cairo/FullBwdDataFrameCursor.java|4|4|100.00%|
|:large_blue_circle:|io/questdb/griffin/engine/table/AsyncFilteredRecordCursor.java|10|10|100.00%|
|:large_blue_circle:|io/questdb/griffin/engine/table/LatestBySubQueryRecordCursorFactory.java|9|9|100.00%|
|:large_blue_circle:|io/questdb/griffin/engine/table/DataFrameRecordCursorImpl.java|9|9|100.00%|
|:large_blue_circle:|io/questdb/griffin/engine/join/CrossJoinRecordCursorFactory.java|60|60|100.00%|
|:large_blue_circle:|io/questdb/griffin/engine/window/WindowRecordCursorFactory.java|3|3|100.00%|
|:large_blue_circle:|io/questdb/griffin/engine/table/LatestByLightRecordCursorFactory.java|2|2|100.00%|
|:large_blue_circle:|io/questdb/griffin/engine/groupby/vect/GroupByRecordCursorFactory.java|7|7|100.00%|
|:large_blue_circle:|io/questdb/cairo/FullFwdDataFrameCursor.java|4|4|100.00%|
|:large_blue_circle:|io/questdb/griffin/engine/table/SelectedRecordCursor.java|2|2|100.00%|
|:large_blue_circle:|io/questdb/griffin/engine/LimitRecordCursorFactory.java|13|13|100.00%|
|:large_blue_circle:|io/questdb/griffin/engine/window/CachedWindowRecordCursorFactory.java|3|3|100.00%|
|:large_blue_circle:|io/questdb/griffin/engine/groupby/CountRecordCursorFactory.java|5|5|100.00%|
|:large_blue_circle:|io/questdb/griffin/engine/union/UnionAllRecordCursor.java|5|5|100.00%|
|:large_blue_circle:|io/questdb/griffin/engine/table/AbstractDescendingRecordListCursor.java|18|18|100.00%|

**Comment by ideoma** [comment]
#### [PR Coverage check]

:heart_eyes: **pass** : 256 / 278 (92.09%)




#### file detail

|   |path|covered line|new line|coverage|
|----|----|----|----|----|
|:large_blue_circle:|io/questdb/griffin/engine/join/AsOfJoinRecordCursorFactory.java|0|2|00.00%|
|:large_blue_circle:|io/questdb/griffin/engine/join/LtJoinRecordCursorFactory.java|0|2|00.00%|
|:large_blue_circle:|io/questdb/cairo/sql/RecordCursor.java|20|28|71.43%|
|:large_blue_circle:|io/questdb/griffin/engine/table/VirtualFunctionDirectSymbolRecordCursor.java|6|8|75.00%|
|:large_blue_circle:|io/questdb/cutlass/http/processors/JsonQueryProcessorState.java|10|13|76.92%|
|:large_blue_circle:|io/questdb/griffin/engine/table/FilterOnSubQueryRecordCursorFactory.java|7|9|77.78%|
|:large_blue_circle:|io/questdb/griffin/engine/LimitRecordCursorFactory.java|21|24|87.50%|
|:large_blue_circle:|io/questdb/cairo/FullBwdDataFrameCursor.java|4|4|100.00%|
|:large_blue_circle:|io/questdb/griffin/engine/join/AsOfJoinNoKeyRecordCursorFactory.java|2|2|100.00%|
|:large_blue_circle:|io/questdb/griffin/engine/table/AsyncFilteredRecordCursor.java|10|10|100.00%|
|:large_blue_circle:|io/questdb/griffin/engine/table/LatestBySubQueryRecordCursorFactory.java|9|9|100.00%|
|:large_blue_circle:|io/questdb/griffin/engine/AbstractVirtualFunctionRecordCursor.java|1|1|100.00%|
|:large_blue_circle:|io/questdb/griffin/engine/groupby/vect/GroupByNotKeyedVectorRecordCursorFactory.java|5|5|100.00%|
|:large_blue_circle:|io/questdb/griffin/engine/table/DataFrameRecordCursorImpl.java|9|9|100.00%|
|:large_blue_circle:|io/questdb/cairo/RecordChain.java|6|6|100.00%|
|:large_blue_circle:|io/questdb/griffin/engine/groupby/GroupByRecordCursorFactory.java|18|18|100.00%|
|:large_blue_circle:|io/questdb/griffin/engine/join/CrossJoinRecordCursorFactory.java|60|60|100.00%|
|:large_blue_circle:|io/questdb/griffin/engine/window/WindowRecordCursorFactory.java|3|3|100.00%|
|:large_blue_circle:|io/questdb/griffin/engine/table/LatestByLightRecordCursorFactory.java|2|2|100.00%|
|:large_blue_circle:|io/questdb/cairo/map/FastMapCursor.java|4|4|100.00%|
|:large_blue_circle:|io/questdb/griffin/engine/join/LtJoinNoKeyRecordCursorFactory.java|2|2|100.00%|
|:large_blue_circle:|io/questdb/griffin/engine/groupby/vect/GroupByRecordCursorFactory.java|7|7|100.00%|
|:large_blue_circle:|io/questdb/cairo/FullFwdDataFrameCursor.java|4|4|100.00%|
|:large_blue_circle:|io/questdb/griffin/engine/table/SelectedRecordCursor.java|2|2|100.00%|
|:large_blue_circle:|io/questdb/griffin/engine/window/CachedWindowRecordCursorFactory.java|3|3|100.00%|
|:large_blue_circle:|io/questdb/griffin/engine/groupby/CountRecordCursorFactory.java|9|9|100.00%|
|:large_blue_circle:|io/questdb/griffin/engine/union/UnionAllRecordCursor.java|5|5|100.00%|
|:large_blue_circle:|io/questdb/griffin/engine/table/AbstractDescendingRecordListCursor.java|18|18|100.00%|
|:large_blue_circle:|io/questdb/griffin/engine/groupby/GroupByNotKeyedRecordCursorFactory.java|5|5|100.00%|
|:large_blue_circle:|io/questdb/griffin/engine/join/LtJoinLightRecordCursorFactory.java|2|2|100.00%|
|:large_blue_circle:|io/questdb/griffin/engine/join/AsOfJoinLightRecordCursorFactory.java|2|2|100.00%|

**Comment by ideoma** [comment]
#### [PR Coverage check]

:heart_eyes: **pass** : 256 / 278 (92.09%)




#### file detail

|   |path|covered line|new line|coverage|
|----|----|----|----|----|
|:large_blue_circle:|io/questdb/griffin/engine/join/AsOfJoinRecordCursorFactory.java|0|2|00.00%|
|:large_blue_circle:|io/questdb/griffin/engine/join/LtJoinRecordCursorFactory.java|0|2|00.00%|
|:large_blue_circle:|io/questdb/cairo/sql/RecordCursor.java|20|28|71.43%|
|:large_blue_circle:|io/questdb/griffin/engine/table/VirtualFunctionDirectSymbolRecordCursor.java|6|8|75.00%|
|:large_blue_circle:|io/questdb/cutlass/http/processors/JsonQueryProcessorState.java|10|13|76.92%|
|:large_blue_circle:|io/questdb/griffin/engine/table/FilterOnSubQueryRecordCursorFactory.java|7|9|77.78%|
|:large_blue_circle:|io/questdb/griffin/engine/LimitRecordCursorFactory.java|21|24|87.50%|
|:large_blue_circle:|io/questdb/cairo/FullBwdDataFrameCursor.java|4|4|100.00%|
|:large_blue_circle:|io/questdb/griffin/engine/join/AsOfJoinNoKeyRecordCursorFactory.java|2|2|100.00%|
|:large_blue_circle:|io/questdb/griffin/engine/table/AsyncFilteredRecordCursor.java|10|10|100.00%|
|:large_blue_circle:|io/questdb/griffin/engine/table/LatestBySubQueryRecordCursorFactory.java|9|9|100.00%|
|:large_blue_circle:|io/questdb/griffin/engine/AbstractVirtualFunctionRecordCursor.java|1|1|100.00%|
|:large_blue_circle:|io/questdb/griffin/engine/groupby/vect/GroupByNotKeyedVectorRecordCursorFactory.java|5|5|100.00%|
|:large_blue_circle:|io/questdb/griffin/engine/table/DataFrameRecordCursorImpl.java|9|9|100.00%|
|:large_blue_circle:|io/questdb/cairo/RecordChain.java|6|6|100.00%|
|:large_blue_circle:|io/questdb/griffin/engine/groupby/GroupByRecordCursorFactory.java|18|18|100.00%|
|:large_blue_circle:|io/questdb/griffin/engine/join/CrossJoinRecordCursorFactory.java|60|60|100.00%|
|:large_blue_circle:|io/questdb/griffin/engine/window/WindowRecordCursorFactory.java|3|3|100.00%|
|:large_blue_circle:|io/questdb/griffin/engine/table/LatestByLightRecordCursorFactory.java|2|2|100.00%|
|:large_blue_circle:|io/questdb/cairo/map/FastMapCursor.java|4|4|100.00%|
|:large_blue_circle:|io/questdb/griffin/engine/join/LtJoinNoKeyRecordCursorFactory.java|2|2|100.00%|
|:large_blue_circle:|io/questdb/griffin/engine/groupby/vect/GroupByRecordCursorFactory.java|7|7|100.00%|
|:large_blue_circle:|io/questdb/cairo/FullFwdDataFrameCursor.java|4|4|100.00%|
|:large_blue_circle:|io/questdb/griffin/engine/table/SelectedRecordCursor.java|2|2|100.00%|
|:large_blue_circle:|io/questdb/griffin/engine/window/CachedWindowRecordCursorFactory.java|3|3|100.00%|
|:large_blue_circle:|io/questdb/griffin/engine/groupby/CountRecordCursorFactory.java|9|9|100.00%|
|:large_blue_circle:|io/questdb/griffin/engine/union/UnionAllRecordCursor.java|5|5|100.00%|
|:large_blue_circle:|io/questdb/griffin/engine/table/AbstractDescendingRecordListCursor.java|18|18|100.00%|
|:large_blue_circle:|io/questdb/griffin/engine/groupby/GroupByNotKeyedRecordCursorFactory.java|5|5|100.00%|
|:large_blue_circle:|io/questdb/griffin/engine/join/LtJoinLightRecordCursorFactory.java|2|2|100.00%|
|:large_blue_circle:|io/questdb/griffin/engine/join/AsOfJoinLightRecordCursorFactory.java|2|2|100.00%|

**Review by bluestreak01 — APPROVED** [review]

**Pull request merged**
