### PR TITLE
chore(sql): improve FastMap's memory layout

### PR DESCRIPTION
**Pull request by puzpuzpuz**
Changes `FastMap`'s heap layout the layout from
```
|       length         | Value columns 0..V | Key columns 0..K |
+----------------------+--------------------+------------------+
|      4 bytes         |         -          |        -         |
+----------------------+--------------------+------------------+
```
to
```
|       length         | Key columns 0..K | Value columns 0..V |
+----------------------+------------------+--------------------+
|      4 bytes         |        -         |         -          |
+----------------------+------------------+--------------------+
```

The `length` now stores the key length instead of the key-value pair length. This way, we can read the key length for var-size keys to jump to value directly.

This way we increase the chances of the value being in the CPU cache when we access it. That's because we access the key first and only then the value.

### CODE REVIEW

**Comment by ideoma** [comment]
#### [PR Coverage check]

:heart_eyes: **pass** : 117 / 120 (97.50%)




#### file detail

|   |path|covered line|new line|coverage|
|----|----|----|----|----|
|:large_blue_circle:|io/questdb/griffin/engine/groupby/SimpleMapValue.java|0|1|00.00%|
|:large_blue_circle:|io/questdb/cairo/map/CompactMapValue.java|0|1|00.00%|
|:large_blue_circle:|io/questdb/cairo/map/FastMap.java|80|81|98.77%|
|:large_blue_circle:|io/questdb/cairo/map/FastMapCursor.java|2|2|100.00%|
|:large_blue_circle:|io/questdb/griffin/engine/join/SpliceJoinLightRecordCursorFactory.java|9|9|100.00%|
|:large_blue_circle:|io/questdb/cairo/map/FastMapValue.java|5|5|100.00%|
|:large_blue_circle:|io/questdb/cairo/map/FastMapRecord.java|21|21|100.00%|

**Comment by ideoma** [comment]
#### [PR Coverage check]

:heart_eyes: **pass** : 117 / 120 (97.50%)




#### file detail

|   |path|covered line|new line|coverage|
|----|----|----|----|----|
|:large_blue_circle:|io/questdb/griffin/engine/groupby/SimpleMapValue.java|0|1|00.00%|
|:large_blue_circle:|io/questdb/cairo/map/CompactMapValue.java|0|1|00.00%|
|:large_blue_circle:|io/questdb/cairo/map/FastMap.java|80|81|98.77%|
|:large_blue_circle:|io/questdb/cairo/map/FastMapCursor.java|2|2|100.00%|
|:large_blue_circle:|io/questdb/griffin/engine/join/SpliceJoinLightRecordCursorFactory.java|9|9|100.00%|
|:large_blue_circle:|io/questdb/cairo/map/FastMapValue.java|5|5|100.00%|
|:large_blue_circle:|io/questdb/cairo/map/FastMapRecord.java|21|21|100.00%|

**Comment by puzpuzpuz** [comment]
@jerrinot I'd like to hear your opinion on this one as it's a kind of an experiment.

**Comment by ideoma** [comment]
#### [PR Coverage check]

:heart_eyes: **pass** : 117 / 120 (97.50%)




#### file detail

|   |path|covered line|new line|coverage|
|----|----|----|----|----|
|:large_blue_circle:|io/questdb/griffin/engine/groupby/SimpleMapValue.java|0|1|00.00%|
|:large_blue_circle:|io/questdb/cairo/map/CompactMapValue.java|0|1|00.00%|
|:large_blue_circle:|io/questdb/cairo/map/FastMap.java|80|81|98.77%|
|:large_blue_circle:|io/questdb/cairo/map/FastMapCursor.java|2|2|100.00%|
|:large_blue_circle:|io/questdb/griffin/engine/join/SpliceJoinLightRecordCursorFactory.java|9|9|100.00%|
|:large_blue_circle:|io/questdb/cairo/map/FastMapValue.java|5|5|100.00%|
|:large_blue_circle:|io/questdb/cairo/map/FastMapRecord.java|21|21|100.00%|

**Comment by bluestreak01** [comment]
bug reproducer:

```sql
CREATE table tab as (select rnd_str(10, 50, 2) k, rnd_double() val from long_sequence(10000000));
select k, sum(val) from andrei;
```

Uh-oh:

```
2023-10-20T11:38:23.175159Z I i.q.c.TableReader open partition C:\qdb\db\andrei\default [rowCount=10000000, partitionNameTxn=-1, transientRowCount=10000000, partitionIndex=0, partitionCount=1]
2023-10-20T11:38:23.191917Z C i.q.c.h.p.JsonQueryProcessorState [3556] Uh-oh. Error!
java.lang.AssertionError
	at io.questdb.cairo.map.FastMapValue.putLong(FastMapValue.java:247)
	at io.questdb.griffin.engine.functions.groupby.SumDoubleGroupByFunction.computeFirst(SumDoubleGroupByFunction.java:51)
	at io.questdb.griffin.engine.groupby.GroupByRecordCursorFactory$GroupByRecordCursor.hasNext(GroupByRecordCursorFactory.java:179)
	at io.questdb.cutlass.http.processors.JsonQueryProcessorState.onQuerySetupFirstRecord(JsonQueryProcessorState.java:773)
	at io.questdb.cutlass.http.processors.JsonQueryProcessorState.doFirstRecordLoop(JsonQueryProcessorState.java:473)
	at io.questdb.cutlass.http.processors.JsonQueryProcessorState.onQueryPrefix(JsonQueryProcessorState.java:737)
	at io.questdb.cutlass.http.processors.JsonQueryProcessorState.resume(JsonQueryProcessorState.java:879)
	at io.questdb.cutlass.http.processors.JsonQueryProcessor.doResumeSend(JsonQueryProcessor.java:303)
	at io.questdb.cutlass.http.processors.JsonQueryProcessor.executeSelect(JsonQueryProcessor.java:560)
	at io.questdb.cutlass.http.processors.JsonQueryProcessor.executeNewSelect(JsonQueryProcessor.java:522)
	at io.questdb.cutlass.http.processors.JsonQueryProcessor.compileQuery(JsonQueryProcessor.java:429)
	at io.questdb.cutlass.http.processors.JsonQueryProcessor.execute0(JsonQueryProcessor.java:183)
	at io.questdb.cutlass.http.processors.JsonQueryProcessor.onRequestComplete(JsonQueryProcessor.java:237)
	at io.questdb.cutlass.http.HttpConnectionContext.handleClientRecv(HttpConnectionContext.java:668)
	at io.questdb.cutlass.http.HttpConnectionContext.handleClientOperation(HttpConnectionContext.java:224)
	at io.questdb.cutlass.http.HttpServer$1.lambda$$0(HttpServer.java:81)
	at io.questdb.network.AbstractIODispatcher.processIOQueue(AbstractIODispatcher.java:199)
	at io.questdb.cutlass.http.HttpServer$1.run(HttpServer.java:93)
	at io.questdb.mp.Worker.run(Worker.java:118)

```

**Comment by ideoma** [comment]
#### [PR Coverage check]

:heart_eyes: **pass** : 117 / 120 (97.50%)




#### file detail

|   |path|covered line|new line|coverage|
|----|----|----|----|----|
|:large_blue_circle:|io/questdb/griffin/engine/groupby/SimpleMapValue.java|0|1|00.00%|
|:large_blue_circle:|io/questdb/cairo/map/CompactMapValue.java|0|1|00.00%|
|:large_blue_circle:|io/questdb/cairo/map/FastMap.java|80|81|98.77%|
|:large_blue_circle:|io/questdb/cairo/map/FastMapCursor.java|2|2|100.00%|
|:large_blue_circle:|io/questdb/griffin/engine/join/SpliceJoinLightRecordCursorFactory.java|9|9|100.00%|
|:large_blue_circle:|io/questdb/cairo/map/FastMapValue.java|5|5|100.00%|
|:large_blue_circle:|io/questdb/cairo/map/FastMapRecord.java|21|21|100.00%|

**Comment by ideoma** [comment]
#### [PR Coverage check]

:heart_eyes: **pass** : 126 / 129 (97.67%)




#### file detail

|   |path|covered line|new line|coverage|
|----|----|----|----|----|
|:large_blue_circle:|io/questdb/griffin/engine/groupby/SimpleMapValue.java|0|1|00.00%|
|:large_blue_circle:|io/questdb/cairo/map/CompactMapValue.java|0|1|00.00%|
|:large_blue_circle:|io/questdb/cairo/map/FastMap.java|82|83|98.80%|
|:large_blue_circle:|io/questdb/cairo/map/FastMapCursor.java|2|2|100.00%|
|:large_blue_circle:|io/questdb/griffin/engine/join/SpliceJoinLightRecordCursorFactory.java|9|9|100.00%|
|:large_blue_circle:|io/questdb/cairo/map/FastMapValue.java|12|12|100.00%|
|:large_blue_circle:|io/questdb/cairo/map/FastMapRecord.java|21|21|100.00%|

**Comment by puzpuzpuz** [comment]
> bug reproducer

@bluestreak01 thanks for the reproducer. Relaxed the assertions and added the new tests in 9aa3e231e59dc59a2d4ff238b4bf675b0602e058

**Review by bluestreak01 — APPROVED** [review]

**Comment by ideoma** [comment]
#### [PR Coverage check]

:heart_eyes: **pass** : 127 / 130 (97.69%)




#### file detail

|   |path|covered line|new line|coverage|
|----|----|----|----|----|
|:large_blue_circle:|io/questdb/griffin/engine/groupby/SimpleMapValue.java|0|1|00.00%|
|:large_blue_circle:|io/questdb/cairo/map/CompactMapValue.java|0|1|00.00%|
|:large_blue_circle:|io/questdb/cairo/map/FastMap.java|83|84|98.81%|
|:large_blue_circle:|io/questdb/cairo/map/FastMapCursor.java|2|2|100.00%|
|:large_blue_circle:|io/questdb/griffin/engine/join/SpliceJoinLightRecordCursorFactory.java|9|9|100.00%|
|:large_blue_circle:|io/questdb/cairo/map/FastMapValue.java|12|12|100.00%|
|:large_blue_circle:|io/questdb/cairo/map/FastMapRecord.java|21|21|100.00%|

**Pull request merged**
