### PR TITLE
chore(core): java 17 support

### PR DESCRIPTION
**Pull request by puzpuzpuz**
Closes: #1503

Includes the following:
* Add explicit imports for `*.sql.Record` to avoid naming clashes with `java.lang.Record`
  - Alternatively we could rename the class to something like `SqlRecord`, but that would mean a breaking API change
* Use `MethodHandles.Lookup#defineHiddenClass` when deprecated `Unsafe#defineAnonymousClass` is not available
  - The detection is reflection based and done in the runtime, so we don't need to add another artifact profile
* Fix `en_GB` date locale dependent tests. The reason is that the short name for September was changed from `Sep` to `Sept` in Common Locale Data Repository (CLDR). OpenJDK [updated](https://github.com/openjdk/jdk/pull/1279/files) their CLDR snapshot in Java 17.
  - **Open question**. We could make users aware of this change, but on the other hand locales are a subject to change in any JDK version. Should we somehow inform users?

To get Java 17 and IntelliJ to work together, uncheck this (the problem is described [here](https://bugs.openjdk.java.net/browse/JDK-8178152)):

image

Ubuntu 20.04 has openjdk 17 in the standard repository:
```bash
$ sudo apt-cache search openjdk | grep 17
openjdk-17-dbg - Java runtime based on OpenJDK (debugging symbols)
openjdk-17-demo - Java runtime based on OpenJDK (demos and examples)
openjdk-17-doc - OpenJDK Development Kit (JDK) documentation
openjdk-17-jdk - OpenJDK Development Kit (JDK)
openjdk-17-jdk-headless - OpenJDK Development Kit (JDK) (headless)
openjdk-17-jre - OpenJDK Java runtime, using Hotspot JIT
openjdk-17-jre-headless - OpenJDK Java runtime, using Hotspot JIT (headless)
openjdk-17-jre-zero - Alternative JVM for OpenJDK, using Zero
openjdk-17-source - OpenJDK Development Kit (JDK) source files
```

Builds for manual installation are also available on https://jdk.java.net/17/

### CODE REVIEW

**Comment by ideoma** [comment]
#### [PR Coverage check]

:heart_eyes: **pass** : 7 / 9 (77.78%)




#### file detail

|   |path|covered line|new line|coverage|
|----|----|----|----|----|
|:large_blue_circle:|io/questdb/std/Unsafe.java|5|7|71.43%|
|:large_blue_circle:|io/questdb/std/BytecodeAssembler.java|2|2|100.00%|

**Comment by ideoma** [comment]
#### [PR Coverage check]

:heart_eyes: **pass** : 7 / 9 (77.78%)




#### file detail

|   |path|covered line|new line|coverage|
|----|----|----|----|----|
|:large_blue_circle:|io/questdb/std/Unsafe.java|5|7|71.43%|
|:large_blue_circle:|io/questdb/std/BytecodeAssembler.java|2|2|100.00%|

**Comment by ideoma** [comment]
#### [PR Coverage check]

:heart_eyes: **pass** : 7 / 9 (77.78%)




#### file detail

|   |path|covered line|new line|coverage|
|----|----|----|----|----|
|:large_blue_circle:|io/questdb/std/Unsafe.java|5|7|71.43%|
|:large_blue_circle:|io/questdb/std/BytecodeAssembler.java|2|2|100.00%|

**Comment by ideoma** [comment]
#### [PR Coverage check]

:heart_eyes: **pass** : 7 / 9 (77.78%)




#### file detail

|   |path|covered line|new line|coverage|
|----|----|----|----|----|
|:large_blue_circle:|io/questdb/std/Unsafe.java|5|7|71.43%|
|:large_blue_circle:|io/questdb/std/BytecodeAssembler.java|2|2|100.00%|

**Comment by ideoma** [comment]
#### [PR Coverage check]

:heart_eyes: **pass** : 7 / 9 (77.78%)




#### file detail

|   |path|covered line|new line|coverage|
|----|----|----|----|----|
|:large_blue_circle:|io/questdb/std/Unsafe.java|5|7|71.43%|
|:large_blue_circle:|io/questdb/std/BytecodeAssembler.java|2|2|100.00%|

**Comment by ideoma** [comment]
#### [PR Coverage check]

:heart_eyes: **pass** : 7 / 9 (77.78%)




#### file detail

|   |path|covered line|new line|coverage|
|----|----|----|----|----|
|:large_blue_circle:|io/questdb/std/Unsafe.java|5|7|71.43%|
|:large_blue_circle:|io/questdb/std/BytecodeAssembler.java|2|2|100.00%|

**Comment by ideoma** [comment]
#### [PR Coverage check]

:heart_eyes: **pass** : 7 / 9 (77.78%)




#### file detail

|   |path|covered line|new line|coverage|
|----|----|----|----|----|
|:large_blue_circle:|io/questdb/std/Unsafe.java|5|7|71.43%|
|:large_blue_circle:|io/questdb/std/BytecodeAssembler.java|2|2|100.00%|

**Comment by ideoma** [comment]
#### [PR Coverage check]

:heart_eyes: **pass** : 7 / 9 (77.78%)




#### file detail

|   |path|covered line|new line|coverage|
|----|----|----|----|----|
|:large_blue_circle:|io/questdb/std/Unsafe.java|5|7|71.43%|
|:large_blue_circle:|io/questdb/std/BytecodeAssembler.java|2|2|100.00%|

**Comment by ideoma** [comment]
#### [PR Coverage check]

:heart_eyes: **pass** : 7 / 9 (77.78%)




#### file detail

|   |path|covered line|new line|coverage|
|----|----|----|----|----|
|:large_blue_circle:|io/questdb/std/Unsafe.java|5|7|71.43%|
|:large_blue_circle:|io/questdb/std/BytecodeAssembler.java|2|2|100.00%|

**Comment by ideoma** [comment]
#### [PR Coverage check]

:heart_eyes: **pass** : 7 / 9 (77.78%)




#### file detail

|   |path|covered line|new line|coverage|
|----|----|----|----|----|
|:large_blue_circle:|io/questdb/std/Unsafe.java|5|7|71.43%|
|:large_blue_circle:|io/questdb/std/BytecodeAssembler.java|2|2|100.00%|

**Comment by ideoma** [comment]
#### [PR Coverage check]

:heart_eyes: **pass** : 7 / 9 (77.78%)




#### file detail

|   |path|covered line|new line|coverage|
|----|----|----|----|----|
|:large_blue_circle:|io/questdb/std/Unsafe.java|5|7|71.43%|
|:large_blue_circle:|io/questdb/std/BytecodeAssembler.java|2|2|100.00%|

**Comment by ideoma** [comment]
#### [PR Coverage check]

:heart_eyes: **pass** : 7 / 9 (77.78%)




#### file detail

|   |path|covered line|new line|coverage|
|----|----|----|----|----|
|:large_blue_circle:|io/questdb/std/Unsafe.java|5|7|71.43%|
|:large_blue_circle:|io/questdb/std/BytecodeAssembler.java|2|2|100.00%|

**Review by bluestreak01 — APPROVED** [review]

**Comment by ideoma** [comment]
#### [PR Coverage check]

:heart_eyes: **pass** : 7 / 9 (77.78%)




#### file detail

|   |path|covered line|new line|coverage|
|----|----|----|----|----|
|:large_blue_circle:|io/questdb/std/Unsafe.java|5|7|71.43%|
|:large_blue_circle:|io/questdb/std/BytecodeAssembler.java|2|2|100.00%|

**Pull request merged**
