### PR TITLE
fix(core): close all but N latest partitions when query execution finishes

### PR DESCRIPTION
**Pull request by puzpuzpuz**
Currently there is no limit for the number of open files retained by inactive table readers. This may lead to situation when the number of open files and mmap areas grows unboundedly due to queries run periodically on a large table.

This patch adds `cairo.inactive.reader.max.open.partitions` config prop (128 by default) that defines the number of the latest partitions to keep open when a table reader is returned to the pool after a query execution.

### CODE REVIEW

**Comment by ideoma** [comment]
#### [PR Coverage check]

:heart_eyes: **pass** : 73 / 74 (98.65%)




#### file detail

|   |path|covered line|new line|coverage|
|----|----|----|----|----|
|:large_blue_circle:|io/questdb/cairo/TableReader.java|67|68|98.53%|
|:large_blue_circle:|io/questdb/PropServerConfiguration.java|3|3|100.00%|
|:large_blue_circle:|io/questdb/cairo/DefaultCairoConfiguration.java|2|2|100.00%|
|:large_blue_circle:|io/questdb/PropertyKey.java|1|1|100.00%|

**Comment by ideoma** [comment]
#### [PR Coverage check]

:heart_eyes: **pass** : 75 / 76 (98.68%)




#### file detail

|   |path|covered line|new line|coverage|
|----|----|----|----|----|
|:large_blue_circle:|io/questdb/cairo/TableReader.java|69|70|98.57%|
|:large_blue_circle:|io/questdb/PropServerConfiguration.java|3|3|100.00%|
|:large_blue_circle:|io/questdb/cairo/DefaultCairoConfiguration.java|2|2|100.00%|
|:large_blue_circle:|io/questdb/PropertyKey.java|1|1|100.00%|

**Review by bluestreak01 — CHANGES_REQUESTED** [review]
Great PR @puzpuzpuz 

We also need tests that prove that partitions can be re-opened and accessed after being closed in this way. E.g. that table reader remains usable

**Comment by ideoma** [comment]
#### [PR Coverage check]

:heart_eyes: **pass** : 75 / 76 (98.68%)




#### file detail

|   |path|covered line|new line|coverage|
|----|----|----|----|----|
|:large_blue_circle:|io/questdb/cairo/TableReader.java|69|70|98.57%|
|:large_blue_circle:|io/questdb/PropServerConfiguration.java|3|3|100.00%|
|:large_blue_circle:|io/questdb/cairo/DefaultCairoConfiguration.java|2|2|100.00%|
|:large_blue_circle:|io/questdb/PropertyKey.java|1|1|100.00%|

**Review by bluestreak01 — APPROVED** [review]

**Comment by ideoma** [comment]
#### [PR Coverage check]

:heart_eyes: **pass** : 73 / 74 (98.65%)




#### file detail

|   |path|covered line|new line|coverage|
|----|----|----|----|----|
|:large_blue_circle:|io/questdb/cairo/TableReader.java|69|70|98.57%|
|:large_blue_circle:|io/questdb/PropServerConfiguration.java|2|2|100.00%|
|:large_blue_circle:|io/questdb/cairo/DefaultCairoConfiguration.java|1|1|100.00%|
|:large_blue_circle:|io/questdb/PropertyKey.java|1|1|100.00%|

**Pull request merged**
