### PR TITLE
feat(sql): support count(1) syntax

### LINKED ISSUE #1420: Support count(1) for queries on UI
`count(1)` for queries does not work on UI

image

### PR DESCRIPTION
**Pull request by puzpuzpuz**
Closes #1420

**Open question**. PostgreSQL [supports](https://www.postgresql.org/docs/8.2/functions-aggregate.html) `count(expression)` flavor of `count()` function where the result is the number of input rows for which the value of expression is not `NULL`. We could support it which would mean an overload function for each type. On the other hand, we may want to wait for users to request this feature.

### CODE REVIEW

**Comment by ideoma** [comment]
#### [PR Coverage check]

:disappointed: **fail** : 0 / 9 (00.00%)




#### file detail

|   |path|covered line|new line|coverage|
|----|----|----|----|----|
|:large_blue_circle:|io/questdb/griffin/engine/functions/groupby/CountIntGroupByFunctionFactory.java|0|9|00.00%|

**Comment by ideoma** [comment]
#### [PR Coverage check]

:heart_eyes: **pass** : 9 / 9 (100.00%)




#### file detail

|   |path|covered line|new line|coverage|
|----|----|----|----|----|
|:large_blue_circle:|io/questdb/griffin/engine/functions/groupby/CountIntGroupByFunctionFactory.java|9|9|100.00%|

**Comment by ideoma** [comment]
#### [PR Coverage check]

:heart_eyes: **pass** : 9 / 9 (100.00%)




#### file detail

|   |path|covered line|new line|coverage|
|----|----|----|----|----|
|:large_blue_circle:|io/questdb/griffin/engine/functions/groupby/CountIntGroupByFunctionFactory.java|9|9|100.00%|

**Comment by bluestreak01** [comment]
minor: why don't we support `CountLong...` semantic? `1` is automatically upcast to `1L` when only `long` signature is available

**Comment by puzpuzpuz** [comment]
> minor: why don't we support `CountLong...` semantic? `1` is automatically upcast to `1L` when only `long` signature is available

Makes sense. Applied the suggestion in f7fb524b9b6fafe3fa2885c0290a1e95871cb95e

**Comment by ideoma** [comment]
#### [PR Coverage check]

:heart_eyes: **pass** : 9 / 9 (100.00%)




#### file detail

|   |path|covered line|new line|coverage|
|----|----|----|----|----|
|:large_blue_circle:|io/questdb/griffin/engine/functions/groupby/CountLongGroupByFunctionFactory.java|9|9|100.00%|

**Comment by ideoma** [comment]
#### [PR Coverage check]

:heart_eyes: **pass** : 9 / 9 (100.00%)




#### file detail

|   |path|covered line|new line|coverage|
|----|----|----|----|----|
|:large_blue_circle:|io/questdb/griffin/engine/functions/groupby/CountLongGroupByFunctionFactory.java|9|9|100.00%|

**Comment by ideoma** [comment]
#### [PR Coverage check]

:heart_eyes: **pass** : 9 / 9 (100.00%)




#### file detail

|   |path|covered line|new line|coverage|
|----|----|----|----|----|
|:large_blue_circle:|io/questdb/griffin/engine/functions/groupby/CountLongGroupByFunctionFactory.java|9|9|100.00%|

**Comment by ideoma** [comment]
#### [PR Coverage check]

:heart_eyes: **pass** : 9 / 9 (100.00%)




#### file detail

|   |path|covered line|new line|coverage|
|----|----|----|----|----|
|:large_blue_circle:|io/questdb/griffin/engine/functions/groupby/CountLongGroupByFunctionFactory.java|9|9|100.00%|

**Comment by ideoma** [comment]
#### [PR Coverage check]

:heart_eyes: **pass** : 9 / 9 (100.00%)




#### file detail

|   |path|covered line|new line|coverage|
|----|----|----|----|----|
|:large_blue_circle:|io/questdb/griffin/engine/functions/groupby/CountLongGroupByFunctionFactory.java|9|9|100.00%|

**Comment by ideoma** [comment]
#### [PR Coverage check]

:heart_eyes: **pass** : 9 / 9 (100.00%)




#### file detail

|   |path|covered line|new line|coverage|
|----|----|----|----|----|
|:large_blue_circle:|io/questdb/griffin/engine/functions/groupby/CountLongGroupByFunctionFactory.java|9|9|100.00%|

**Comment by puzpuzpuz** [comment]
This one should be good to go.

**Review by bluestreak01 — APPROVED** [review]

**Pull request merged**
