### PR TITLE
chore(build): fix javadoc warnings

### PR DESCRIPTION
**Pull request by bluestreak01**
I really appreciate everyone adding Javadoc, the more the better. But Javadoc has to be in a correct format. From this PR onwards any Javadoc issue will fail the build

### CODE REVIEW

**Comment by ideoma** [comment]
#### [PR Coverage check]


:heart_eyes: **pass** : 0 / 0 (0%)

**Review by bziobrowski — APPROVED** [review]
Approved though I reckon javadoc requirements are artificial and force adding useless lines and we'd be better off writing simple simple comments only  . 

Example : 
_@param key symbol key_

(adds a great deal of new information!)

**Comment by bluestreak01** [comment]
This PR is bourn out of releasing QuestDB to maven central. They require javadoc. With each release out warnings grew and sometimes we fell into habit of not maintaining existing Javadoc. Such as adding undocumented param to documented method.

Additionally our Javadoc is automatically picked up by https://www.javadoc.io/doc/org.questdb/questdb/latest/index.html. It would be good to show good form where we can.

**Comment by bluestreak01** [comment]
JDK 17 killed it actually, they generate this as a "warning", doh:

```
[WARNING] Generating C:\Users\Vlad\dev\questdb\core\target\apidocs\io.questdb\io\questdb\std\str\class-use\DirectByteCharSequence.Factory.html...
```

**Comment by bluestreak01** [comment]
JDK17 onwards wants all public interfaces to be documented, if not - there will be warnings.

This PR is on hold until there is good time to revisit this

**Comment by bziobrowski** [comment]
Excessive warnings can be disabled with: <quiet>true</quiet>
Unfortunately there's no way to disable "no comment" only . 
The closes I found was : <doclint>all,-missing</doclint> but it also disables warnings about missing @param, @return, etc.

**Comment by bluestreak01** [comment]
Crazy, it was a good intention totally spoiled by Java's rigidity

**Pull request closed without merging**
