### PR TITLE
fix(pgwire): send empty query response when sql text contains no query

### PR DESCRIPTION
**Pull request by jerrinot**
fixes https://github.com/grafana/grafana/issues/64376

### CODE REVIEW

**Review by marregui — APPROVED** [review]
LGTM

Top job, blown away by the thoroughness.

**Comment by jerrinot** [comment]
fixing https://github.com/grafana/grafana/issues/64376

**Comment by ideoma** [comment]
#### [PR Coverage check]

:heart_eyes: **pass** : 8 / 8 (100.00%)




#### file detail

|   |path|covered line|new line|coverage|
|----|----|----|----|----|
|:large_blue_circle:|io/questdb/cutlass/pgwire/PGConnectionContext.java|8|8|100.00%|

**Review by bziobrowski — APPROVED** [review]

**Comment by ideoma** [comment]
#### [PR Coverage check]

:heart_eyes: **pass** : 8 / 8 (100.00%)




#### file detail

|   |path|covered line|new line|coverage|
|----|----|----|----|----|
|:large_blue_circle:|io/questdb/cutlass/pgwire/PGConnectionContext.java|8|8|100.00%|

**Pull request merged**
