### PR TITLE
fix(sql): fix date_trunc and timestamp_shuffle bugs

### LINKED ISSUE #3154: Both singular and plural forms of millisecond(s) and microsecond(s) should be supported
### Describe the bug

These work:
```
select date_trunc('milliseconds', '2022-03-11T22:00:30.555555Z');
select date_trunc('microseconds', '2022-03-11T22:00:30.555555Z');
```
These return invalid unit:
```
select date_trunc('millisecond', '2022-03-11T22:00:30.555555Z');
select date_trunc('microsecond', '2022-03-11T22:00:30.555555Z');
```

To be consistent with PG, both forms should be allowed.

### To reproduce

_No response_

### Expected Behavior

These should work:

```
select date_trunc('millisecond', '2022-03-11T22:00:30.555555Z');
select date_trunc('microsecond', '2022-03-11T22:00:30.555555Z');
```

### Environment

```markdown
https://demo.questdb.io/
```

### Additional context

_No response_

### PR DESCRIPTION
**Pull request by bziobrowski**
Fixes #3154 

Changes : 
- fix timestamp_shuffle output when timestamp_1 is after timestamp_2
- make date_trunc accept singular and plural time units

### CODE REVIEW

**Comment by ideoma** [comment]
#### [PR Coverage check]

:heart_eyes: **pass** : 26 / 26 (100.00%)




#### file detail

|   |path|covered line|new line|coverage|
|----|----|----|----|----|
|:large_blue_circle:|io/questdb/griffin/engine/functions/date/TimestampShuffleFunctionFactory.java|5|5|100.00%|
|:large_blue_circle:|io/questdb/griffin/engine/functions/date/DateTruncFunctionFactory.java|21|21|100.00%|

**Comment by ideoma** [comment]
#### [PR Coverage check]

:heart_eyes: **pass** : 26 / 26 (100.00%)




#### file detail

|   |path|covered line|new line|coverage|
|----|----|----|----|----|
|:large_blue_circle:|io/questdb/griffin/engine/functions/date/TimestampShuffleFunctionFactory.java|5|5|100.00%|
|:large_blue_circle:|io/questdb/griffin/engine/functions/date/DateTruncFunctionFactory.java|21|21|100.00%|

**Comment by ideoma** [comment]
#### [PR Coverage check]

:heart_eyes: **pass** : 26 / 26 (100.00%)




#### file detail

|   |path|covered line|new line|coverage|
|----|----|----|----|----|
|:large_blue_circle:|io/questdb/griffin/engine/functions/date/TimestampShuffleFunctionFactory.java|5|5|100.00%|
|:large_blue_circle:|io/questdb/griffin/engine/functions/date/DateTruncFunctionFactory.java|21|21|100.00%|

**Review by bluestreak01 — APPROVED** [review]

**Comment by ideoma** [comment]
#### [PR Coverage check]

:heart_eyes: **pass** : 26 / 26 (100.00%)




#### file detail

|   |path|covered line|new line|coverage|
|----|----|----|----|----|
|:large_blue_circle:|io/questdb/griffin/engine/functions/date/TimestampShuffleFunctionFactory.java|5|5|100.00%|
|:large_blue_circle:|io/questdb/griffin/engine/functions/date/DateTruncFunctionFactory.java|21|21|100.00%|

**Pull request merged**
