### PR TITLE
fix(http): make HTTP text import for WAL tables to write via WAL

### LINKED ISSUE #3632: Deduplication doesn't apply to /imp CSV upload
### Describe the bug

De-duplication is not applied to CSV uploads via the /imp endpoint. Repeated uploads of the same CSV file to the same table, with the same dedup upsert keys, results in duplicate row inserts.

If a subsequent value is inserted with the same keys via another method i.e /exec, all of the duplicate rows are updated to the new values, as if de-dupe had applied.

This is reproducible both through UI CSV uploads, and via /imp HTTP requests in C#.

Let me know if any more information is required.

### To reproduce

Go through the following script (inc. uploading CSV that looks like this):

```csv
"Foo","Bah","Baz","ts"
,"test2",3,"1970-01-01T00:00:00.000000Z"
```

```sql
-- 1. Create test table
create table "dedup_test" (
  Foo UUID,
  Bah SYMBOL,
  Baz INT,
  ts Timestamp
) timestamp(ts) partition by day WAL
DEDUP UPSERT keys(Bah, ts)

-- 2. Verify dedup upsert keys are set and enabled.
table_columns('dedup_test')

-- 3. Insert a test row.
insert into dedup_test values (null, 'test1', 5, to_timestamp('1970-01-01T00:00:00Z', 'yyyy-MM-ddTHH:mm:ssZ'))

-- 4. Check its there.
select * from dedup_test

-- 5. Table should look like the following CSV:
-- "Foo","Bah","Baz","ts"
-- ,"test1",5,"1970-01-01T00:00:00.000000Z"

-- 6. Insert new row with same keys but new value
insert into dedup_test values (null, 'test1', 10, to_timestamp('1970-01-01T00:00:00Z', 'yyyy-MM-ddTHH:mm:ssZ'))

-- 7. Table should look like the following CSV:
-- "Foo","Bah","Baz","ts"
-- ,"test1",10,"1970-01-01T00:00:00.000000Z"
select * from dedup_test


-- 8. Now upload the following CSV to the table:
-- either via UI or /imp, using forceHeader true, delimiter=',' and with append.
-- "Foo","Bah","Baz","ts"
-- ,"test2",3,"1970-01-01T00:00:00.000000Z"

-- 9. Table now looks like:
-- "Foo","Bah","Baz","ts"
-- ,"test1",10,"1970-01-01T00:00:00.000000Z"
-- ,"test2",3,"1970-01-01T00:00:00.000000Z"
select * from dedup_test


-- 10. Upload the CSV again.

-- 11. Table now looks like:
-- "Foo","Bah","Baz","ts"
-- ,"test1",10,"1970-01-01T00:00:00.000000Z"
-- ,"test2",3,"1970-01-01T00:00:00.000000Z"
-- ,"test2",3,"1970-01-01T00:00:00.000000Z"
select * from dedup_test

-- 12. Duplicate rows now observed. Upload same CSV as many times as you want and see more rows.

-- 13. Now insert via command to overwrite the non de-duped rows:
insert into dedup_test values (null, 'test2', 20, to_timestamp('1970-01-01T00:00:00Z', 'yyyy-MM-ddTHH:mm:ssZ'))

-- 14. Observe that the table now looks like this:
-- "Foo","Bah","Baz","ts"
-- ,"test1",10,"1970-01-01T00:00:00.000000Z"
-- ,"test2",20,"1970-01-01T00:00:00.000000Z"
-- ,"test2",20,"1970-01-01T00:00:00.000000Z"
select * from dedup_test
```

### Expected Behavior

I would expect that the rows that are imported via CSV do not create duplicates, but are instead upserted to existing rows in the table i.e same behaviour as the /exec endpoint (and hopefully ILP/pgwire).

### Environment

```markdown
- **QuestDB version**: 7.3.0
- **OS**: Windows 10 (also separately observed using the Docker image)
- **Browser**: Google Chrome Version 115.0.5790.171 (Official Build) (64-bit)
```

### Additional context

1
image

2
image

3,4
image

5,6,7
image

8,9
image
image

10,11,12
image

13,14
image

### PR DESCRIPTION
**Pull request by ideoma**
REST `imp` endpoint was not updated to write to WAL tables using WAL infrastructure. This PR makes the writing to behave as expected. Also fixes #3632

### CODE REVIEW

**Comment by ideoma** [comment]
#### [PR Coverage check]

:heart_eyes: **pass** : 29 / 29 (100.00%)




#### file detail

|   |path|covered line|new line|coverage|
|----|----|----|----|----|
|:large_blue_circle:|io/questdb/cutlass/text/CairoTextWriter.java|29|29|100.00%|

**Comment by ideoma** [comment]
#### [PR Coverage check]

:heart_eyes: **pass** : 26 / 26 (100.00%)




#### file detail

|   |path|covered line|new line|coverage|
|----|----|----|----|----|
|:large_blue_circle:|io/questdb/cutlass/text/CairoTextWriter.java|26|26|100.00%|

**Comment by ideoma** [comment]
#### [PR Coverage check]

:heart_eyes: **pass** : 26 / 26 (100.00%)




#### file detail

|   |path|covered line|new line|coverage|
|----|----|----|----|----|
|:large_blue_circle:|io/questdb/cutlass/text/CairoTextWriter.java|26|26|100.00%|

**Comment by ideoma** [comment]
#### [PR Coverage check]

:heart_eyes: **pass** : 70 / 73 (95.89%)




#### file detail

|   |path|covered line|new line|coverage|
|----|----|----|----|----|
|:large_blue_circle:|io/questdb/cairo/TableUtils.java|11|14|78.57%|
|:large_blue_circle:|io/questdb/cairo/TableReaderMetadata.java|1|1|100.00%|
|:large_blue_circle:|io/questdb/cutlass/text/CairoTextWriter.java|24|24|100.00%|
|:large_blue_circle:|io/questdb/cairo/pool/MetadataPool.java|17|17|100.00%|
|:large_blue_circle:|io/questdb/cairo/DynamicTableReaderMetadata.java|17|17|100.00%|

**Review by puzpuzpuz — APPROVED** [review]

**Comment by puzpuzpuz** [comment]
Looks like as a side effect of this change, the serial mode of SQL COPY also started writing to WAL. Probably, it's worth it to add some tests around it.

As for the parallel mode where we require the table to be empty, we should at least document that it writes to the end table instead of WAL and/or create a separate GH issue.

WDYT?

**Comment by puzpuzpuz** [comment]
> Looks like as a side effect of this change, the serial mode of SQL COPY also started writing to WAL. Probably, it's worth it to add some tests around it.

Hmm, I forgot that it's used for non-partitioned tables, so it's not applicable to WAL tables. On WAL tables COPY should be parallel always.

**Pull request merged**
