### PR TITLE
fix(rest): fix writer left locked after csv upload

### PR DESCRIPTION
**Pull request by ideoma**

### CODE REVIEW

**Comment by ideoma** [comment]
#### [PR Coverage check]

:heart_eyes: **pass** : 16 / 20 (80.00%)




#### file detail

|   |path|covered line|new line|coverage|
|----|----|----|----|----|
|:large_blue_circle:|io/questdb/cutlass/http/processors/TextImportProcessor.java|11|14|78.57%|
|:large_blue_circle:|io/questdb/cutlass/http/HttpConnectionContext.java|5|6|83.33%|

**Comment by ideoma** [comment]
#### [PR Coverage check]

:heart_eyes: **pass** : 16 / 20 (80.00%)




#### file detail

|   |path|covered line|new line|coverage|
|----|----|----|----|----|
|:large_blue_circle:|io/questdb/cutlass/http/processors/TextImportProcessor.java|11|14|78.57%|
|:large_blue_circle:|io/questdb/cutlass/http/HttpConnectionContext.java|5|6|83.33%|

**Comment by ideoma** [comment]
#### [PR Coverage check]

:heart_eyes: **pass** : 17 / 20 (85.00%)




#### file detail

|   |path|covered line|new line|coverage|
|----|----|----|----|----|
|:large_blue_circle:|io/questdb/cutlass/http/processors/TextImportProcessor.java|11|14|78.57%|
|:large_blue_circle:|io/questdb/cutlass/http/HttpConnectionContext.java|6|6|100.00%|

**Comment by ideoma** [comment]
#### [PR Coverage check]

:heart_eyes: **pass** : 16 / 20 (80.00%)




#### file detail

|   |path|covered line|new line|coverage|
|----|----|----|----|----|
|:large_blue_circle:|io/questdb/cutlass/http/processors/TextImportProcessor.java|11|14|78.57%|
|:large_blue_circle:|io/questdb/cutlass/http/HttpConnectionContext.java|5|6|83.33%|

**Comment by ideoma** [comment]
#### [PR Coverage check]

coverage check fail. please retry. :fearful:

[Please let me know](https://github.com/naver/cover-checker/issues/new) when error again.

com.naver.nid.cover.parser.coverage.exception.ParseException: java.io.FileNotFoundException: /home/vsts/work/1/s/core/CCReport43F6D5EF/jacoco.xml (No such file or directory)

**Comment by ideoma** [comment]
#### [PR Coverage check]

:heart_eyes: **pass** : 16 / 20 (80.00%)




#### file detail

|   |path|covered line|new line|coverage|
|----|----|----|----|----|
|:large_blue_circle:|io/questdb/cutlass/http/processors/TextImportProcessor.java|11|14|78.57%|
|:large_blue_circle:|io/questdb/cutlass/http/HttpConnectionContext.java|5|6|83.33%|

**Comment by ideoma** [comment]
#### [PR Coverage check]

:heart_eyes: **pass** : 16 / 20 (80.00%)




#### file detail

|   |path|covered line|new line|coverage|
|----|----|----|----|----|
|:large_blue_circle:|io/questdb/cutlass/http/processors/TextImportProcessor.java|11|14|78.57%|
|:large_blue_circle:|io/questdb/cutlass/http/HttpConnectionContext.java|5|6|83.33%|

**Review by bluestreak01 — APPROVED** [review]

**Comment by ideoma** [comment]
#### [PR Coverage check]

:heart_eyes: **pass** : 17 / 20 (85.00%)




#### file detail

|   |path|covered line|new line|coverage|
|----|----|----|----|----|
|:large_blue_circle:|io/questdb/cutlass/http/processors/TextImportProcessor.java|11|14|78.57%|
|:large_blue_circle:|io/questdb/cutlass/http/HttpConnectionContext.java|6|6|100.00%|

**Comment by ideoma** [comment]
#### [PR Coverage check]

:heart_eyes: **pass** : 16 / 20 (80.00%)




#### file detail

|   |path|covered line|new line|coverage|
|----|----|----|----|----|
|:large_blue_circle:|io/questdb/cutlass/http/processors/TextImportProcessor.java|11|14|78.57%|
|:large_blue_circle:|io/questdb/cutlass/http/HttpConnectionContext.java|5|6|83.33%|

**Pull request merged**
