### PR TITLE
fix(sql): non-keyed LT JOIN could return equal timestamps

### PR DESCRIPTION
**Pull request by jerrinot**
The right side of a LT JOIN must have strictly smaller timestamps. Returning equal timestamps is a bug.

### CODE REVIEW

**Comment by jerrinot** [comment]
This is reverting https://github.com/questdb/questdb/issues/1275
I believe the original behaviour before #1275 was correct. 
An alternative explanation: My understanding of LT JOIN is wrong.

**Comment by ideoma** [comment]
#### [PR Coverage check]

:heart_eyes: **pass** : 1 / 1 (100.00%)




#### file detail

|   |path|covered line|new line|coverage|
|----|----|----|----|----|
|:large_blue_circle:|io/questdb/griffin/engine/join/LtJoinNoKeyRecordCursorFactory.java|1|1|100.00%|

**Comment by ideoma** [comment]
#### [PR Coverage check]

:heart_eyes: **pass** : 1 / 1 (100.00%)




#### file detail

|   |path|covered line|new line|coverage|
|----|----|----|----|----|
|:large_blue_circle:|io/questdb/griffin/engine/join/LtJoinNoKeyRecordCursorFactory.java|1|1|100.00%|

**Comment by jerrinot** [comment]
the failure looks like Maven infra issues:
```
2023-02-17T17:47:29.6645310Z 
2023-02-17T17:47:41.5356250Z [ERROR] Plugin org.apache.maven.plugins:maven-clean-plugin:3.2.0 or one of its dependencies could not be resolved: Failed to read artifact descriptor for org.apache.maven.plugins:maven-clean-plugin:jar:3.2.0: Could not transfer artifact org.apache.maven.plugins:maven-clean-plugin:pom:3.2.0 from/to central (https://repo.maven.apache.org/maven2): Connection reset -> [Help 1]
```
-> restarting CI.

**Review by puzpuzpuz — APPROVED** [review]

**Comment by ideoma** [comment]
#### [PR Coverage check]

:heart_eyes: **pass** : 1 / 1 (100.00%)




#### file detail

|   |path|covered line|new line|coverage|
|----|----|----|----|----|
|:large_blue_circle:|io/questdb/griffin/engine/join/LtJoinNoKeyRecordCursorFactory.java|1|1|100.00%|

**Comment by jerrinot** [comment]
hm, again, that's odd:
```
2023-02-20T16:15:19.1806090Z [ERROR] Plugin org.apache.maven.plugins:maven-clean-plugin:3.2.0 or one of its dependencies could not be resolved: Failed to read artifact descriptor for org.apache.maven.plugins:maven-clean-plugin:jar:3.2.0: Could not transfer artifact org.apache.maven.plugins:maven-clean-plugin:pom:3.2.0 from/to central (https://repo.maven.apache.org/maven2): Connection reset -> [Help 1]
2023-02-20T16:15:19.1807950Z [ERROR] 
2023-02-20T16:15:19.1827390Z [ERROR] To see the full stack trace of the errors, re-run Maven with the -e switch.
2023-02-20T16:15:19.1829260Z [ERROR] Re-run Maven using the -X switch to enable full debug logging.
2023-02-20T16:15:19.1831400Z [ERROR] 
2023-02-20T16:15:19.1832700Z [ERROR] For more information about the errors and possible solutions, please read the following articles:
2023-02-20T16:15:19.1834280Z [ERROR] [Help 1] http://cwiki.apache.org/confluence/display/MAVEN/PluginResolutionException
2023-02-20T16:15:19.3001220Z The process '/usr/local/bin/mvn' failed with exit code 1
2023-02-20T16:15:19.3005010Z Could not retrieve code analysis results - Maven run failed.
```

**Pull request merged**
