### PR TITLE
Added a dutch translation to readme

### PR DESCRIPTION
**Pull request by AnirudhDaya**
PR solving issue #2695 
I have added a README file in the Dutch language.
I have also linked it to other README files and linked other README files to it.
I have updated all other README files with the Dutchoption.
I have also updated languages.md.
Kindly add the hacktoberfest label.

### CODE REVIEW

**Comment by bluestreak01** [comment]
thanks, are you a native Dutch speaker?

**Comment by AnirudhDaya** [comment]
No, but I have been learning dutch for the past year and a half, so I decided to sharpen my skills by contributing here.

**Comment by AnirudhDaya** [comment]
@bluestreak01 is this PR valid?

**Comment by bluestreak01** [comment]
it is valid, but we have no way of verifying language correctness here :(

**Comment by jerrinot** [comment]
maybe @pveentjer could chime in here? 🙏

**Comment by bluestreak01** [comment]
apologies, this looks like google translate and with no feedback with a Dutch speaker we cannot proceed

**Pull request closed without merging**
