### PR TITLE
fix(core): prevent ugly error message when log directory does not exist

### LINKED ISSUE #4662: Ugly error when starting in Docker
### To reproduce

1. Start `docker run questdb/questdb:8.0.0`
2. Observe sysout:
    ```shell
    2024-06-07T13:47:03.655436Z I server-main Failed to create /var/lib/questdb/log/hello.txt.tmp
    2024-06-07T13:47:03.655471Z I server-main Failed to rename /var/lib/questdb/log/hello.txt.tmp to hello.txt
    2024-06-07T13:47:03.671945Z A server-main enjoy
    ```

Non-actionable errors right after starting an empty database are unimpressive.

It looks it was introduced in https://github.com/questdb/questdb/pull/4349 - it assume that the `log` directory exists inside `dbroot`. That's not the case with containers since QuestDB container image logs to sysout by default -> the `log` directory is not created. 

### QuestDB version:

8.0.0

### OS, in case of Docker specify Docker and the Host OS:

Docker @ MacOS and Podman @ Linux

### File System, in case of Docker specify Host File System:

reproduces with both mounted and not mounted dbroot

### Full Name:

Jaromir Hamala

### Affiliation:

QuestDB

### Have you followed Linux, MacOs kernel configuration steps to increase Maximum open files and Maximum virtual memory areas limit?

- [X] Yes, I have

### Additional context

_No response_

### PR DESCRIPTION
**Pull request by jerrinot**
This PR removes the assumption that the log directory inside `dbroot` exists. QuestDB attempts to create a `hello.txt` file in this directory on startup. This usually works, because file loggers create the log directory. 

However, we don't use file loggers in some environments, such as inside containers. QuestDB containers log to sysout instead. So there is nothing to create the log directory. When QuestDB tries to create the `hello.txt` file and the `log` directory does not exist then QuestDB logs ugly messages like this:
```
2024-06-07T13:47:03.655436Z I server-main Failed to create /var/lib/questdb/log/hello.txt.tmp
2024-06-07T13:47:03.655471Z I server-main Failed to rename /var/lib/questdb/log/hello.txt.tmp to hello.txt
```

This PR makes QuestDB create the hello.txt file(s) right inside `dbroot` - which always must exist. 

fixes #4662

### CODE REVIEW

**Comment by jerrinot** [comment]
@mtopolnik: I figured out you know the most about this hello.txt shenanigans. I did not really check its purpose and whether the log directory is the best possible location. So chances are this is not the best possible fix. So a critical review is appreciated!

**Comment by ideoma** [comment]
#### [PR Coverage check]

:heart_eyes: **pass** : 4 / 5 (80.00%)




#### file detail

|   |path|covered line|new line|coverage|
|----|----|----|----|----|
|:large_blue_circle:|io/questdb/Bootstrap.java|4|5|80.00%|

**Comment by mtopolnik** [comment]
The goal behind creating this file is printing the hello message from a startup script, even in the cases where stdout of QuestDB server is directed into a file. Its location is assumed in [questdb.sh](https://github.com/questdb/questdb/blob/master/core/src/main/bin/questdb.sh#L216) and [questdb.c](https://github.com/questdb/questdb/blob/master/win64svc/src/questdb.c#L357C31-L357C40).

I felt it was the most logical place for it in `log`, but since it may not always exist, a better choice is the QuestDB root. We should change it in these two additional places.

**Comment by jerrinot** [comment]
@mtopolnik done. but it requires @bluestreak01 to rebuild the Windows Service wrapper.

**Review by bluestreak01 — APPROVED** [review]

**Comment by ideoma** [comment]
#### [PR Coverage check]

:heart_eyes: **pass** : 2 / 2 (100.00%)




#### file detail

|   |path|covered line|new line|coverage|
|----|----|----|----|----|
|:large_blue_circle:|io/questdb/Bootstrap.java|2|2|100.00%|

**Pull request merged**
