### PR TITLE
chore(core): table reader reload fuzz test

### PR DESCRIPTION
**Pull request by glasstiger**
Fuzz test for TableReader.reload() and some code cleanup.

### CODE REVIEW

**Comment by ideoma** [comment]
#### [PR Coverage check]

:heart_eyes: **pass** : 1 / 2 (50.00%)




#### file detail

|   |path|covered line|new line|coverage|
|----|----|----|----|----|
|:large_blue_circle:|io/questdb/ServerMain.java|0|1|00.00%|
|:large_blue_circle:|io/questdb/cairo/TableReaderMetadata.java|1|1|100.00%|

**Comment by ideoma** [comment]
#### [PR Coverage check]

:heart_eyes: **pass** : 1 / 2 (50.00%)




#### file detail

|   |path|covered line|new line|coverage|
|----|----|----|----|----|
|:large_blue_circle:|io/questdb/ServerMain.java|0|1|00.00%|
|:large_blue_circle:|io/questdb/cairo/TableReaderMetadata.java|1|1|100.00%|

**Comment by ideoma** [comment]
#### [PR Coverage check]

:heart_eyes: **pass** : 5 / 6 (83.33%)




#### file detail

|   |path|covered line|new line|coverage|
|----|----|----|----|----|
|:large_blue_circle:|io/questdb/ServerMain.java|0|1|00.00%|
|:large_blue_circle:|io/questdb/cairo/TableReaderMetadata.java|1|1|100.00%|
|:large_blue_circle:|io/questdb/std/ObjList.java|4|4|100.00%|

**Comment by ideoma** [comment]
#### [PR Coverage check]

:heart_eyes: **pass** : 27 / 28 (96.43%)




#### file detail

|   |path|covered line|new line|coverage|
|----|----|----|----|----|
|:large_blue_circle:|io/questdb/ServerMain.java|0|1|00.00%|
|:large_blue_circle:|io/questdb/cairo/TableReader.java|22|22|100.00%|
|:large_blue_circle:|io/questdb/cairo/TableReaderMetadata.java|1|1|100.00%|
|:large_blue_circle:|io/questdb/std/ObjList.java|4|4|100.00%|

**Comment by ideoma** [comment]
#### [PR Coverage check]

:heart_eyes: **pass** : 27 / 28 (96.43%)




#### file detail

|   |path|covered line|new line|coverage|
|----|----|----|----|----|
|:large_blue_circle:|io/questdb/ServerMain.java|0|1|00.00%|
|:large_blue_circle:|io/questdb/cairo/TableReader.java|22|22|100.00%|
|:large_blue_circle:|io/questdb/cairo/TableReaderMetadata.java|1|1|100.00%|
|:large_blue_circle:|io/questdb/std/ObjList.java|4|4|100.00%|

**Comment by ideoma** [comment]
#### [PR Coverage check]

:heart_eyes: **pass** : 27 / 28 (96.43%)




#### file detail

|   |path|covered line|new line|coverage|
|----|----|----|----|----|
|:large_blue_circle:|io/questdb/ServerMain.java|0|1|00.00%|
|:large_blue_circle:|io/questdb/cairo/TableReader.java|22|22|100.00%|
|:large_blue_circle:|io/questdb/cairo/TableReaderMetadata.java|1|1|100.00%|
|:large_blue_circle:|io/questdb/std/ObjList.java|4|4|100.00%|

**Review by bluestreak01 — APPROVED** [review]

**Pull request merged**
