### PR TITLE
chore(core): add tests to exemplify the difference between '' and NULL for column type SYMBOL

### PR DESCRIPTION
**Pull request by marregui**
closes https://github.com/questdb/questdb/issues/1914 

NULL and '' are equivalent for type SYMBOL.

```
create table tab (id int, val symbol);
insert into tab values (1, '');
select id from tab where val = '';
select id from tab where val = NULL;
select id from tab where val IS NULL;
```

```
create table tab2 (id int, val symbol);
insert into tabs values (1, NULL);
select id from tab2 where val = '';
select id from tab2 where val = NULL;
select id from tab2 where val IS NULL;
```

all selects return `id = 1`;

### CODE REVIEW

**Comment by puzpuzpuz** [comment]
> NULL and '' are equivalent for type SYMBOL.

This is counter-intuitive: NULL and empty string are different values in Postgres and other databases. Also, why only symbol type? Char and string column types need the same behavior.

**Comment by marregui** [comment]
> #1914

My understanding, a SYMBOL is an enum value, a member of a set, a numeric value that has an associated unique moniker.

Examples of symbols: 'EURO', 'DOLLAR', 'A BANANA'.

What does SYMBOL `''` represent?, nada, nothing, null, so it may be a synonym with NULL.

A null String and an empty String (same for chars) are not quite the same, one represents explicitly the absence of the content, the String is empty, the other represents the absence of the memory allocation.

In my mind this fix makes mathematical sense, but I may be missing some key information in my reasoning?

**Comment by bziobrowski** [comment]
I agree with Andrei - let's keep NULLs separate from empty string/symbol . 
Empty string is a concrete but empty value while null usually means lack of value. 
By the way - the examples given in #1914  work fine in latest master - so I suspect the issue was with FilterOnExcludedValues factory .

**Comment by marregui** [comment]
Thank you both for the reviews, ok, I can see it now. I will check that master passes the amended test.

**Review by bziobrowski — APPROVED** [review]

**Pull request merged**
