### PR TITLE
fix(core): reduce footprint of QuestDB data structures in Java Heap

### PR DESCRIPTION
**Pull request by jerrinot**
This pull request implements a pooling mechanism for SQLCompiler instances. Previously, these instances were reused, but their quantity exceeded the average number of concurrent compilation tasks, leading to inefficiencies.

In addition, the introduction of compiler pooling prompted a thorough review of our test infrastructure. During this review, we identified inconsistent execution of SQL queries, which occasionally resulted in bugs within our tests.

After this PR is merged all tests should (or even must):
- subclass `AbstractCairoTest` (`AbstractGriffinTest` has been removed)
- use correct version of the following methods to compile **constant** SQLs. These are thread-safe, provided execution context is accessed in read only mode. Otherwise there are overloads that accept execution context too:
   * `select()`
   * `insert()`
   * `update()`
   * `drop()`
   * `ddl()`
- when SQL is variable and can be anything other than `SELECT` you can use `compile()`

### Compilation example

Before:

```java
            compile("create table test (ts timestamp, name symbol, val int)", sqlExecutionContext);
            compiler.compile("snapshot prepare", sqlExecutionContext);
            compiler.compile("snapshot complete", sqlExecutionContext);
```

After:

```java
            ddl("create table test (ts timestamp, name symbol, val int)");
            ddl("snapshot prepare");
            ddl("snapshot complete");
```

### Another variant of compilation that used to exist:

Before:

```java
            executeOperation("alter table " + tableName + " add column iii int", CompiledQuery.ALTER);
            executeInsert("insert into " + tableName + " values (101, 'dfd', '2022-02-24T01', 'asd', 41)");

            executeOperation("alter table " + tableName + " add column jjj int", CompiledQuery.ALTER);

            executeInsert("insert into " + tableName + " values (102, 'dfd', '2022-02-24T02', 'asd', 41, 42)");

            executeOperation("UPDATE " + tableName + " SET iii = 0 where iii = null", CompiledQuery.UPDATE);
            executeOperation("UPDATE " + tableName + " SET jjj = 0 where iii = null", CompiledQuery.UPDATE);

```

After:

```java
            ddl("alter table " + tableName + " add column iii int");
            insert("insert into " + tableName + " values (101, 'dfd', '2022-02-24T01', 'asd', 41)");
            ddl("alter table " + tableName + " add column jjj int");
            insert("insert into " + tableName + " values (102, 'dfd', '2022-02-24T02', 'asd', 41, 42)");
            update("UPDATE " + tableName + " SET iii = 0 where iii = null");
            update("UPDATE " + tableName + " SET jjj = 0 where iii = null");

```

### Error assertion

Before:

```java
            try {
                compiler.compile("snapshot prepare", sqlExecutionContext);
                Assert.fail(); // this line is often missing
            } catch (CairoException ex) {
                // error position assert is often missing too
                Assert.assertTrue(ex.getMessage().contains("Cannot append. File does not exist"));
            }
```

After:

```java
            assertException("snapshot prepare", 0, "Cannot append. File does not exist");
```

### Custom error assertion

Before:

```java
            try {
                compiler.compile("snapshot prepare", sqlExecutionContext);
                Assert.fail();
            } catch (SqlException ex) {
                Assert.assertTrue(lock.isLocked());
                Assert.assertTrue(ex.getMessage().startsWith("[0] Waiting for SNAPSHOT COMPLETE to be called"));
            }
```

After:

```java
            try {
                assertException("snapshot prepare");
                // note that Assert.fail() is deliberately missing, the above method will fail is there is no exception
            } catch (SqlException ex) {
                Assert.assertTrue(lock.isLocked());
                Assert.assertTrue(ex.getMessage().startsWith("[0] Waiting for SNAPSHOT COMPLETE to be called"));
            }
```

### SQL result assertion

Unless we're testing a new implementation of `RecordCursorFactory` we should not be using `assertQuery` to assert results. Instead we should use `assertSql`, which is much more light weight and does not have ambiguous (and irrelevant) arguments. Have the look at this example:

Before: 

```java
    public void testCreateTableFromLikeTableWithPartition() throws Exception {
        ddl(
                "create table x (" +
                "a INT," +
                "t timestamp) timestamp(t) partition by MONTH"
        );
        assertQuery("a\tt\n", "select * from tab", "create table tab (like x)", "t");
        assertPartitionAndTimestamp();
    }
```

After:

```java
    @Test
    public void testCreateTableFromLikeTableWithPartition() throws Exception {
        ddl(
                "create table x (" +
                "a INT," +
                "t timestamp) timestamp(t) partition by MONTH"
        );
        ddl("create table tab (like x)");
        // you are not limited by number of DDLs you need to run before the assertion
        assertSql("a\tt\n", "select * from tab");
        assertPartitionAndTimestamp();
    }
```

### Another example why this simplification was needed:

image

Problems list with this small test:
- missing `fail()`, test will pass if nothing fails
- unclear which SQL is to fail (`select` or `create`), clue - it should be `create`
- all "expected" and "sql" values are just noise
- test does not assert error position
- error position is in fact incorrect, production code produces 13 wheras it should be 21
in this example there are two SQLs executed in `try...catch`, it is unclear which is expected to fail. Test will also pass if none fail.

### CODE REVIEW

**Comment by questdb-butler** [comment]
<table>
  <thead>
    <tr>
      <th width="50"></th>
      <th width="100%" data-danger-table="true">Fails</th>
    </tr>
  </thead>
  <tbody><tr>
      <td>:no_entry_sign:</td>
      <td>

  Please update the PR title to match this format:
`type(subType): description`

Where `type` is one of:
`feat`, `fix`, `chore`, `docs`, `style`, `refactor`, `perf`, `test`, `ci`, `chore`, `revert`

And: `subType` is one of:
`build`, `sql`, `log`, `mig`, `core`, `ilp`, `pgwire`, `http`, `conf`, `ui`, `wal`

For Example:

```
perf(sql): improve pattern matching performance for SELECT sub-queries
```
  </td>
    </tr>
  </tbody>
</table>




<p align="right">
  Generated by :no_entry_sign: <a href="https://danger.systems/js">dangerJS</a> against 981956e6521268db5a16427e512040cc5fc246dd
</p>

**Comment by ideoma** [comment]
#### [PR Coverage check]

:heart_eyes: **pass** : 369 / 412 (89.56%)




#### file detail

|   |path|covered line|new line|coverage|
|----|----|----|----|----|
|:large_blue_circle:|io/questdb/ServerMain.java|5|7|71.43%|
|:large_blue_circle:|io/questdb/cairo/DatabaseSnapshotAgent.java|108|139|77.70%|
|:large_blue_circle:|io/questdb/cairo/ColumnPurgeJob.java|47|52|90.38%|
|:large_blue_circle:|io/questdb/griffin/QueryBuilder.java|11|12|91.67%|
|:large_blue_circle:|io/questdb/cairo/pool/SqlCompilerPool.java|45|48|93.75%|
|:large_blue_circle:|io/questdb/cutlass/http/processors/TextQueryProcessor.java|17|18|94.44%|
|:large_blue_circle:|io/questdb/std/str/Path.java|14|14|100.00%|
|:large_blue_circle:|io/questdb/griffin/engine/ops/OperationFutureImpl.java|2|2|100.00%|
|:large_blue_circle:|io/questdb/MessageBusImpl.java|2|2|100.00%|
|:large_blue_circle:|io/questdb/cairo/VacuumColumnVersions.java|2|2|100.00%|
|:large_blue_circle:|io/questdb/PropServerConfiguration.java|2|2|100.00%|
|:large_blue_circle:|io/questdb/cairo/O3Utils.java|1|1|100.00%|
|:large_blue_circle:|io/questdb/cutlass/pgwire/PGWireServer.java|1|1|100.00%|
|:large_blue_circle:|io/questdb/cairo/pool/MetadataPool.java|1|1|100.00%|
|:large_blue_circle:|io/questdb/cutlass/http/processors/JsonQueryProcessor.java|9|9|100.00%|
|:large_blue_circle:|io/questdb/cutlass/text/CopyRequestJob.java|8|8|100.00%|
|:large_blue_circle:|io/questdb/griffin/FunctionParser.java|2|2|100.00%|
|:large_blue_circle:|io/questdb/griffin/SqlCompilerFactoryImpl.java|1|1|100.00%|
|:large_blue_circle:|io/questdb/cairo/CairoEngine.java|18|18|100.00%|
|:large_blue_circle:|io/questdb/cutlass/pgwire/PGJobContext.java|1|1|100.00%|
|:large_blue_circle:|io/questdb/griffin/CompiledQueryImpl.java|11|11|100.00%|
|:large_blue_circle:|io/questdb/cairo/sql/async/PageFrameReduceTask.java|3|3|100.00%|
|:large_blue_circle:|io/questdb/cairo/wal/ApplyWal2TableJob.java|1|1|100.00%|
|:large_blue_circle:|io/questdb/std/MemoryTag.java|1|1|100.00%|
|:large_blue_circle:|io/questdb/cairo/pool/AbstractMultiTenantPool.java|3|3|100.00%|
|:large_blue_circle:|io/questdb/TelemetryJob.java|2|2|100.00%|
|:large_blue_circle:|io/questdb/TelemetryConfigLogger.java|6|6|100.00%|
|:large_blue_circle:|io/questdb/cairo/pool/WalWriterPool.java|1|1|100.00%|
|:large_blue_circle:|io/questdb/griffin/SqlCodeGenerator.java|2|2|100.00%|
|:large_blue_circle:|io/questdb/cairo/pool/ReaderPool.java|1|1|100.00%|
|:large_blue_circle:|io/questdb/cairo/RebuildColumnBase.java|1|1|100.00%|
|:large_blue_circle:|io/questdb/cutlass/pgwire/PGConnectionContext.java|28|28|100.00%|
|:large_blue_circle:|io/questdb/cairo/ColumnPurgeOperator.java|4|4|100.00%|
|:large_blue_circle:|io/questdb/cairo/wal/OperationCompiler.java|7|7|100.00%|
|:large_blue_circle:|io/questdb/cutlass/text/TextLoader.java|1|1|100.00%|

**Comment by ideoma** [comment]
#### [PR Coverage check]

:heart_eyes: **pass** : 402 / 451 (89.14%)




#### file detail

|   |path|covered line|new line|coverage|
|----|----|----|----|----|
|:large_blue_circle:|io/questdb/cairo/DatabaseSnapshotAgent.java|108|139|77.70%|
|:large_blue_circle:|io/questdb/ServerMain.java|10|12|83.33%|
|:large_blue_circle:|io/questdb/cairo/CairoEngine.java|42|48|87.50%|
|:large_blue_circle:|io/questdb/cairo/ColumnPurgeJob.java|47|52|90.38%|
|:large_blue_circle:|io/questdb/griffin/QueryBuilder.java|11|12|91.67%|
|:large_blue_circle:|io/questdb/cairo/pool/SqlCompilerPool.java|45|48|93.75%|
|:large_blue_circle:|io/questdb/cutlass/http/processors/TextQueryProcessor.java|17|18|94.44%|
|:large_blue_circle:|io/questdb/Bootstrap.java|1|1|100.00%|
|:large_blue_circle:|io/questdb/std/str/Path.java|14|14|100.00%|
|:large_blue_circle:|io/questdb/griffin/engine/ops/OperationFutureImpl.java|2|2|100.00%|
|:large_blue_circle:|io/questdb/MessageBusImpl.java|2|2|100.00%|
|:large_blue_circle:|io/questdb/cairo/VacuumColumnVersions.java|2|2|100.00%|
|:large_blue_circle:|io/questdb/PropServerConfiguration.java|2|2|100.00%|
|:large_blue_circle:|io/questdb/cairo/O3Utils.java|1|1|100.00%|
|:large_blue_circle:|io/questdb/cutlass/pgwire/PGWireServer.java|1|1|100.00%|
|:large_blue_circle:|io/questdb/cairo/pool/MetadataPool.java|1|1|100.00%|
|:large_blue_circle:|io/questdb/griffin/SqlParser.java|5|5|100.00%|
|:large_blue_circle:|io/questdb/cutlass/http/processors/JsonQueryProcessor.java|9|9|100.00%|
|:large_blue_circle:|io/questdb/cutlass/text/CopyRequestJob.java|8|8|100.00%|
|:large_blue_circle:|io/questdb/griffin/FunctionParser.java|2|2|100.00%|
|:large_blue_circle:|io/questdb/griffin/SqlCompilerFactoryImpl.java|1|1|100.00%|
|:large_blue_circle:|io/questdb/cutlass/pgwire/PGJobContext.java|1|1|100.00%|
|:large_blue_circle:|io/questdb/griffin/CompiledQueryImpl.java|9|9|100.00%|
|:large_blue_circle:|io/questdb/cairo/sql/async/PageFrameReduceTask.java|3|3|100.00%|
|:large_blue_circle:|io/questdb/cairo/wal/ApplyWal2TableJob.java|1|1|100.00%|
|:large_blue_circle:|io/questdb/std/MemoryTag.java|1|1|100.00%|
|:large_blue_circle:|io/questdb/cairo/pool/AbstractMultiTenantPool.java|3|3|100.00%|
|:large_blue_circle:|io/questdb/TelemetryJob.java|2|2|100.00%|
|:large_blue_circle:|io/questdb/TelemetryConfigLogger.java|6|6|100.00%|
|:large_blue_circle:|io/questdb/cairo/pool/WalWriterPool.java|1|1|100.00%|
|:large_blue_circle:|io/questdb/griffin/SqlCodeGenerator.java|2|2|100.00%|
|:large_blue_circle:|io/questdb/cairo/pool/ReaderPool.java|1|1|100.00%|
|:large_blue_circle:|io/questdb/cairo/RebuildColumnBase.java|1|1|100.00%|
|:large_blue_circle:|io/questdb/cutlass/pgwire/PGConnectionContext.java|28|28|100.00%|
|:large_blue_circle:|io/questdb/cairo/ColumnPurgeOperator.java|4|4|100.00%|
|:large_blue_circle:|io/questdb/cairo/wal/OperationCompiler.java|7|7|100.00%|
|:large_blue_circle:|io/questdb/cutlass/text/TextLoader.java|1|1|100.00%|

**Comment by ideoma** [comment]
#### [PR Coverage check]

:heart_eyes: **pass** : 401 / 628 (63.85%)




#### file detail

|   |path|covered line|new line|coverage|
|----|----|----|----|----|
|:large_blue_circle:|io/questdb/cairo/CairoConfigurationWrapper.java|7|185|03.78%|
|:large_blue_circle:|io/questdb/cairo/DatabaseSnapshotAgent.java|108|139|77.70%|
|:large_blue_circle:|io/questdb/ServerMain.java|10|12|83.33%|
|:large_blue_circle:|io/questdb/cairo/CairoEngine.java|42|48|87.50%|
|:large_blue_circle:|io/questdb/cairo/ColumnPurgeJob.java|47|52|90.38%|
|:large_blue_circle:|io/questdb/griffin/QueryBuilder.java|11|12|91.67%|
|:large_blue_circle:|io/questdb/cairo/pool/SqlCompilerPool.java|45|48|93.75%|
|:large_blue_circle:|io/questdb/cutlass/http/processors/TextQueryProcessor.java|17|18|94.44%|
|:large_blue_circle:|io/questdb/Bootstrap.java|1|1|100.00%|
|:large_blue_circle:|io/questdb/std/str/Path.java|6|6|100.00%|
|:large_blue_circle:|io/questdb/griffin/engine/ops/OperationFutureImpl.java|2|2|100.00%|
|:large_blue_circle:|io/questdb/MessageBusImpl.java|1|1|100.00%|
|:large_blue_circle:|io/questdb/cairo/VacuumColumnVersions.java|2|2|100.00%|
|:large_blue_circle:|io/questdb/PropServerConfiguration.java|3|3|100.00%|
|:large_blue_circle:|io/questdb/cairo/O3Utils.java|1|1|100.00%|
|:large_blue_circle:|io/questdb/cutlass/pgwire/PGWireServer.java|1|1|100.00%|
|:large_blue_circle:|io/questdb/cairo/pool/MetadataPool.java|1|1|100.00%|
|:large_blue_circle:|io/questdb/griffin/SqlParser.java|5|5|100.00%|
|:large_blue_circle:|io/questdb/cutlass/http/processors/JsonQueryProcessor.java|9|9|100.00%|
|:large_blue_circle:|io/questdb/cutlass/text/CopyRequestJob.java|8|8|100.00%|
|:large_blue_circle:|io/questdb/griffin/FunctionParser.java|2|2|100.00%|
|:large_blue_circle:|io/questdb/griffin/SqlCompilerFactoryImpl.java|1|1|100.00%|
|:large_blue_circle:|io/questdb/cutlass/pgwire/PGJobContext.java|1|1|100.00%|
|:large_blue_circle:|io/questdb/griffin/CompiledQueryImpl.java|9|9|100.00%|
|:large_blue_circle:|io/questdb/cairo/sql/async/PageFrameReduceTask.java|3|3|100.00%|
|:large_blue_circle:|io/questdb/cairo/wal/ApplyWal2TableJob.java|1|1|100.00%|
|:large_blue_circle:|io/questdb/std/MemoryTag.java|1|1|100.00%|
|:large_blue_circle:|io/questdb/cairo/pool/AbstractMultiTenantPool.java|3|3|100.00%|
|:large_blue_circle:|io/questdb/TelemetryJob.java|2|2|100.00%|
|:large_blue_circle:|io/questdb/TelemetryConfigLogger.java|6|6|100.00%|
|:large_blue_circle:|io/questdb/cairo/pool/WalWriterPool.java|1|1|100.00%|
|:large_blue_circle:|io/questdb/griffin/SqlCodeGenerator.java|2|2|100.00%|
|:large_blue_circle:|io/questdb/cairo/pool/ReaderPool.java|1|1|100.00%|
|:large_blue_circle:|io/questdb/cairo/RebuildColumnBase.java|1|1|100.00%|
|:large_blue_circle:|io/questdb/cutlass/pgwire/PGConnectionContext.java|28|28|100.00%|
|:large_blue_circle:|io/questdb/cairo/ColumnPurgeOperator.java|4|4|100.00%|
|:large_blue_circle:|io/questdb/cairo/wal/OperationCompiler.java|7|7|100.00%|
|:large_blue_circle:|io/questdb/cutlass/text/TextLoader.java|1|1|100.00%|

**Comment by ideoma** [comment]
#### [PR Coverage check]

:heart_eyes: **pass** : 432 / 666 (64.86%)




#### file detail

|   |path|covered line|new line|coverage|
|----|----|----|----|----|
|:large_blue_circle:|io/questdb/cairo/CairoConfigurationWrapper.java|7|186|03.76%|
|:large_blue_circle:|io/questdb/cairo/DatabaseSnapshotAgent.java|108|139|77.70%|
|:large_blue_circle:|io/questdb/ServerMain.java|10|12|83.33%|
|:large_blue_circle:|io/questdb/cairo/CairoEngine.java|73|85|85.88%|
|:large_blue_circle:|io/questdb/cairo/ColumnPurgeJob.java|47|52|90.38%|
|:large_blue_circle:|io/questdb/griffin/QueryBuilder.java|11|12|91.67%|
|:large_blue_circle:|io/questdb/cairo/pool/SqlCompilerPool.java|45|48|93.75%|
|:large_blue_circle:|io/questdb/cutlass/http/processors/TextQueryProcessor.java|17|18|94.44%|
|:large_blue_circle:|io/questdb/Bootstrap.java|1|1|100.00%|
|:large_blue_circle:|io/questdb/std/str/Path.java|6|6|100.00%|
|:large_blue_circle:|io/questdb/griffin/engine/ops/OperationFutureImpl.java|2|2|100.00%|
|:large_blue_circle:|io/questdb/MessageBusImpl.java|1|1|100.00%|
|:large_blue_circle:|io/questdb/cairo/VacuumColumnVersions.java|2|2|100.00%|
|:large_blue_circle:|io/questdb/PropServerConfiguration.java|3|3|100.00%|
|:large_blue_circle:|io/questdb/cairo/O3Utils.java|1|1|100.00%|
|:large_blue_circle:|io/questdb/cutlass/pgwire/PGWireServer.java|1|1|100.00%|
|:large_blue_circle:|io/questdb/cairo/pool/MetadataPool.java|1|1|100.00%|
|:large_blue_circle:|io/questdb/griffin/SqlParser.java|5|5|100.00%|
|:large_blue_circle:|io/questdb/cutlass/http/processors/JsonQueryProcessor.java|9|9|100.00%|
|:large_blue_circle:|io/questdb/cutlass/text/CopyRequestJob.java|8|8|100.00%|
|:large_blue_circle:|io/questdb/griffin/FunctionParser.java|2|2|100.00%|
|:large_blue_circle:|io/questdb/griffin/SqlCompilerFactoryImpl.java|1|1|100.00%|
|:large_blue_circle:|io/questdb/cutlass/pgwire/PGJobContext.java|1|1|100.00%|
|:large_blue_circle:|io/questdb/griffin/CompiledQueryImpl.java|9|9|100.00%|
|:large_blue_circle:|io/questdb/cairo/sql/async/PageFrameReduceTask.java|3|3|100.00%|
|:large_blue_circle:|io/questdb/cairo/wal/ApplyWal2TableJob.java|1|1|100.00%|
|:large_blue_circle:|io/questdb/std/MemoryTag.java|1|1|100.00%|
|:large_blue_circle:|io/questdb/cairo/pool/AbstractMultiTenantPool.java|3|3|100.00%|
|:large_blue_circle:|io/questdb/TelemetryJob.java|2|2|100.00%|
|:large_blue_circle:|io/questdb/TelemetryConfigLogger.java|6|6|100.00%|
|:large_blue_circle:|io/questdb/cairo/pool/WalWriterPool.java|1|1|100.00%|
|:large_blue_circle:|io/questdb/griffin/SqlCodeGenerator.java|2|2|100.00%|
|:large_blue_circle:|io/questdb/cairo/pool/ReaderPool.java|1|1|100.00%|
|:large_blue_circle:|io/questdb/cairo/RebuildColumnBase.java|1|1|100.00%|
|:large_blue_circle:|io/questdb/cutlass/pgwire/PGConnectionContext.java|28|28|100.00%|
|:large_blue_circle:|io/questdb/cairo/ColumnPurgeOperator.java|4|4|100.00%|
|:large_blue_circle:|io/questdb/cairo/wal/OperationCompiler.java|7|7|100.00%|
|:large_blue_circle:|io/questdb/cutlass/text/TextLoader.java|1|1|100.00%|

**Comment by ideoma** [comment]
#### [PR Coverage check]

:heart_eyes: **pass** : 433 / 667 (64.92%)




#### file detail

|   |path|covered line|new line|coverage|
|----|----|----|----|----|
|:large_blue_circle:|io/questdb/cairo/CairoConfigurationWrapper.java|7|186|03.76%|
|:large_blue_circle:|io/questdb/cairo/DatabaseSnapshotAgent.java|108|139|77.70%|
|:large_blue_circle:|io/questdb/ServerMain.java|11|13|84.62%|
|:large_blue_circle:|io/questdb/cairo/CairoEngine.java|73|85|85.88%|
|:large_blue_circle:|io/questdb/cairo/ColumnPurgeJob.java|47|52|90.38%|
|:large_blue_circle:|io/questdb/griffin/QueryBuilder.java|11|12|91.67%|
|:large_blue_circle:|io/questdb/cairo/pool/SqlCompilerPool.java|45|48|93.75%|
|:large_blue_circle:|io/questdb/cutlass/http/processors/TextQueryProcessor.java|17|18|94.44%|
|:large_blue_circle:|io/questdb/Bootstrap.java|1|1|100.00%|
|:large_blue_circle:|io/questdb/std/str/Path.java|6|6|100.00%|
|:large_blue_circle:|io/questdb/griffin/engine/ops/OperationFutureImpl.java|2|2|100.00%|
|:large_blue_circle:|io/questdb/MessageBusImpl.java|1|1|100.00%|
|:large_blue_circle:|io/questdb/cairo/VacuumColumnVersions.java|2|2|100.00%|
|:large_blue_circle:|io/questdb/PropServerConfiguration.java|3|3|100.00%|
|:large_blue_circle:|io/questdb/cairo/O3Utils.java|1|1|100.00%|
|:large_blue_circle:|io/questdb/cutlass/pgwire/PGWireServer.java|1|1|100.00%|
|:large_blue_circle:|io/questdb/cairo/pool/MetadataPool.java|1|1|100.00%|
|:large_blue_circle:|io/questdb/griffin/SqlParser.java|5|5|100.00%|
|:large_blue_circle:|io/questdb/cutlass/http/processors/JsonQueryProcessor.java|9|9|100.00%|
|:large_blue_circle:|io/questdb/cutlass/text/CopyRequestJob.java|8|8|100.00%|
|:large_blue_circle:|io/questdb/griffin/FunctionParser.java|2|2|100.00%|
|:large_blue_circle:|io/questdb/griffin/SqlCompilerFactoryImpl.java|1|1|100.00%|
|:large_blue_circle:|io/questdb/cutlass/pgwire/PGJobContext.java|1|1|100.00%|
|:large_blue_circle:|io/questdb/griffin/CompiledQueryImpl.java|9|9|100.00%|
|:large_blue_circle:|io/questdb/cairo/sql/async/PageFrameReduceTask.java|3|3|100.00%|
|:large_blue_circle:|io/questdb/cairo/wal/ApplyWal2TableJob.java|1|1|100.00%|
|:large_blue_circle:|io/questdb/std/MemoryTag.java|1|1|100.00%|
|:large_blue_circle:|io/questdb/cairo/pool/AbstractMultiTenantPool.java|3|3|100.00%|
|:large_blue_circle:|io/questdb/TelemetryJob.java|2|2|100.00%|
|:large_blue_circle:|io/questdb/TelemetryConfigLogger.java|6|6|100.00%|
|:large_blue_circle:|io/questdb/cairo/pool/WalWriterPool.java|1|1|100.00%|
|:large_blue_circle:|io/questdb/griffin/SqlCodeGenerator.java|2|2|100.00%|
|:large_blue_circle:|io/questdb/cairo/pool/ReaderPool.java|1|1|100.00%|
|:large_blue_circle:|io/questdb/cairo/RebuildColumnBase.java|1|1|100.00%|
|:large_blue_circle:|io/questdb/cutlass/pgwire/PGConnectionContext.java|28|28|100.00%|
|:large_blue_circle:|io/questdb/cairo/ColumnPurgeOperator.java|4|4|100.00%|
|:large_blue_circle:|io/questdb/cairo/wal/OperationCompiler.java|7|7|100.00%|
|:large_blue_circle:|io/questdb/cutlass/text/TextLoader.java|1|1|100.00%|

**Comment by ideoma** [comment]
#### [PR Coverage check]

:heart_eyes: **pass** : 433 / 667 (64.92%)




#### file detail

|   |path|covered line|new line|coverage|
|----|----|----|----|----|
|:large_blue_circle:|io/questdb/cairo/CairoConfigurationWrapper.java|7|186|03.76%|
|:large_blue_circle:|io/questdb/cairo/DatabaseSnapshotAgent.java|108|139|77.70%|
|:large_blue_circle:|io/questdb/ServerMain.java|11|13|84.62%|
|:large_blue_circle:|io/questdb/cairo/CairoEngine.java|73|85|85.88%|
|:large_blue_circle:|io/questdb/cairo/ColumnPurgeJob.java|47|52|90.38%|
|:large_blue_circle:|io/questdb/griffin/QueryBuilder.java|11|12|91.67%|
|:large_blue_circle:|io/questdb/cairo/pool/SqlCompilerPool.java|45|48|93.75%|
|:large_blue_circle:|io/questdb/cutlass/http/processors/TextQueryProcessor.java|17|18|94.44%|
|:large_blue_circle:|io/questdb/Bootstrap.java|1|1|100.00%|
|:large_blue_circle:|io/questdb/std/str/Path.java|6|6|100.00%|
|:large_blue_circle:|io/questdb/griffin/engine/ops/OperationFutureImpl.java|2|2|100.00%|
|:large_blue_circle:|io/questdb/MessageBusImpl.java|1|1|100.00%|
|:large_blue_circle:|io/questdb/cairo/VacuumColumnVersions.java|2|2|100.00%|
|:large_blue_circle:|io/questdb/PropServerConfiguration.java|3|3|100.00%|
|:large_blue_circle:|io/questdb/cairo/O3Utils.java|1|1|100.00%|
|:large_blue_circle:|io/questdb/cutlass/pgwire/PGWireServer.java|1|1|100.00%|
|:large_blue_circle:|io/questdb/cairo/pool/MetadataPool.java|1|1|100.00%|
|:large_blue_circle:|io/questdb/griffin/SqlParser.java|5|5|100.00%|
|:large_blue_circle:|io/questdb/cutlass/http/processors/JsonQueryProcessor.java|9|9|100.00%|
|:large_blue_circle:|io/questdb/cutlass/text/CopyRequestJob.java|8|8|100.00%|
|:large_blue_circle:|io/questdb/griffin/FunctionParser.java|2|2|100.00%|
|:large_blue_circle:|io/questdb/griffin/SqlCompilerFactoryImpl.java|1|1|100.00%|
|:large_blue_circle:|io/questdb/cutlass/pgwire/PGJobContext.java|1|1|100.00%|
|:large_blue_circle:|io/questdb/griffin/CompiledQueryImpl.java|9|9|100.00%|
|:large_blue_circle:|io/questdb/cairo/sql/async/PageFrameReduceTask.java|3|3|100.00%|
|:large_blue_circle:|io/questdb/cairo/wal/ApplyWal2TableJob.java|1|1|100.00%|
|:large_blue_circle:|io/questdb/std/MemoryTag.java|1|1|100.00%|
|:large_blue_circle:|io/questdb/cairo/pool/AbstractMultiTenantPool.java|3|3|100.00%|
|:large_blue_circle:|io/questdb/TelemetryJob.java|2|2|100.00%|
|:large_blue_circle:|io/questdb/TelemetryConfigLogger.java|6|6|100.00%|
|:large_blue_circle:|io/questdb/cairo/pool/WalWriterPool.java|1|1|100.00%|
|:large_blue_circle:|io/questdb/griffin/SqlCodeGenerator.java|2|2|100.00%|
|:large_blue_circle:|io/questdb/cairo/pool/ReaderPool.java|1|1|100.00%|
|:large_blue_circle:|io/questdb/cairo/RebuildColumnBase.java|1|1|100.00%|
|:large_blue_circle:|io/questdb/cutlass/pgwire/PGConnectionContext.java|28|28|100.00%|
|:large_blue_circle:|io/questdb/cairo/ColumnPurgeOperator.java|4|4|100.00%|
|:large_blue_circle:|io/questdb/cairo/wal/OperationCompiler.java|7|7|100.00%|
|:large_blue_circle:|io/questdb/cutlass/text/TextLoader.java|1|1|100.00%|

**Pull request merged**
