### PR TITLE
perf(sql): optimize memory usage in order by

### PR DESCRIPTION
**Pull request by puzpuzpuz**
Migrates red-black tree-based tree chains to use a heap instead of `MemoryPages` for both keys (tree nodes) and values (row id chains). Thanks to this, we now store compressed offsets (`int`s) instead of addresses (`long`s):
* Red-black tree nodes now takes 24 bytes instead of 41 bytes.
* Value chain values in `LongTreeChain` and `LimitedSizeLongTreeChain` now take 12 bytes instead of 16 bytes.

These changes give a small speed-up in order by exec times:
```sql
-- master: 360s
-- patch: 320s
SELECT * FROM hits ORDER BY UserID;

-- master: 16s
-- patch: 14s
SELECT * FROM (hits LIMIT 10000000) ORDER BY UserID;
```

### CODE REVIEW

**Comment by ideoma** [comment]
#### [PR Coverage check]

:heart_eyes: **pass** : 170 / 188 (90.43%)




#### file detail

|   |path|covered line|new line|coverage|
|----|----|----|----|----|
|:large_blue_circle:|io/questdb/std/DirectLongList.java|3|4|75.00%|
|:large_blue_circle:|io/questdb/griffin/engine/orderby/LimitedSizeLongTreeChain.java|52|64|81.25%|
|:large_blue_circle:|io/questdb/griffin/engine/orderby/LongTreeChain.java|49|53|92.45%|
|:large_blue_circle:|io/questdb/griffin/engine/AbstractRedBlackTree.java|66|67|98.51%|

**Comment by ideoma** [comment]
#### [PR Coverage check]

:heart_eyes: **pass** : 229 / 248 (92.34%)




#### file detail

|   |path|covered line|new line|coverage|
|----|----|----|----|----|
|:large_blue_circle:|io/questdb/std/DirectIntList.java|3|4|75.00%|
|:large_blue_circle:|io/questdb/griffin/engine/orderby/LimitedSizeLongTreeChain.java|78|91|85.71%|
|:large_blue_circle:|io/questdb/griffin/engine/orderby/LongTreeChain.java|62|66|93.94%|
|:large_blue_circle:|io/questdb/griffin/engine/AbstractRedBlackTree.java|86|87|98.85%|

**Comment by ideoma** [comment]
#### [PR Coverage check]

:heart_eyes: **pass** : 229 / 248 (92.34%)




#### file detail

|   |path|covered line|new line|coverage|
|----|----|----|----|----|
|:large_blue_circle:|io/questdb/std/DirectIntList.java|3|4|75.00%|
|:large_blue_circle:|io/questdb/griffin/engine/orderby/LimitedSizeLongTreeChain.java|78|91|85.71%|
|:large_blue_circle:|io/questdb/griffin/engine/orderby/LongTreeChain.java|62|66|93.94%|
|:large_blue_circle:|io/questdb/griffin/engine/AbstractRedBlackTree.java|86|87|98.85%|

**Comment by ideoma** [comment]
#### [PR Coverage check]

:heart_eyes: **pass** : 242 / 253 (95.65%)




#### file detail

|   |path|covered line|new line|coverage|
|----|----|----|----|----|
|:large_blue_circle:|io/questdb/std/DirectIntList.java|3|4|75.00%|
|:large_blue_circle:|io/questdb/griffin/engine/orderby/LongTreeChain.java|62|66|93.94%|
|:large_blue_circle:|io/questdb/griffin/engine/orderby/LimitedSizeLongTreeChain.java|86|91|94.51%|
|:large_blue_circle:|io/questdb/griffin/engine/AbstractRedBlackTree.java|86|87|98.85%|
|:large_blue_circle:|io/questdb/PropServerConfiguration.java|2|2|100.00%|
|:large_blue_circle:|io/questdb/cairo/DefaultCairoConfiguration.java|3|3|100.00%|

**Comment by ideoma** [comment]
#### [PR Coverage check]

:heart_eyes: **pass** : 242 / 253 (95.65%)




#### file detail

|   |path|covered line|new line|coverage|
|----|----|----|----|----|
|:large_blue_circle:|io/questdb/std/DirectIntList.java|3|4|75.00%|
|:large_blue_circle:|io/questdb/griffin/engine/orderby/LongTreeChain.java|62|66|93.94%|
|:large_blue_circle:|io/questdb/griffin/engine/orderby/LimitedSizeLongTreeChain.java|86|91|94.51%|
|:large_blue_circle:|io/questdb/griffin/engine/AbstractRedBlackTree.java|86|87|98.85%|
|:large_blue_circle:|io/questdb/PropServerConfiguration.java|2|2|100.00%|
|:large_blue_circle:|io/questdb/cairo/DefaultCairoConfiguration.java|3|3|100.00%|

**Comment by ideoma** [comment]
#### [PR Coverage check]

:heart_eyes: **pass** : 242 / 253 (95.65%)




#### file detail

|   |path|covered line|new line|coverage|
|----|----|----|----|----|
|:large_blue_circle:|io/questdb/std/DirectIntList.java|3|4|75.00%|
|:large_blue_circle:|io/questdb/griffin/engine/orderby/LongTreeChain.java|62|66|93.94%|
|:large_blue_circle:|io/questdb/griffin/engine/orderby/LimitedSizeLongTreeChain.java|86|91|94.51%|
|:large_blue_circle:|io/questdb/griffin/engine/AbstractRedBlackTree.java|86|87|98.85%|
|:large_blue_circle:|io/questdb/PropServerConfiguration.java|2|2|100.00%|
|:large_blue_circle:|io/questdb/cairo/DefaultCairoConfiguration.java|3|3|100.00%|

**Review by glasstiger — APPROVED** [review]

**Comment by puzpuzpuz** [comment]
@glasstiger thanks for the review!

**Pull request merged**
