### PR TITLE
fix(core): add FreeBSD UFS (0x35) to the list of supported file systems

### LINKED ISSUE #2501: add UFS (0x35) to supported file system
Add UFS code 0x35 to list of supported file systems

### PR DESCRIPTION
**Pull request by nitram509**
* ✅ fix #2501 add the new UFS FS type
* ✅ refactor magic constant `-1` towards a named constant `FLAG_FS_SUPPORTED` for better readability
* ✅ trim trailing spaces

* ✅ I did test compile the code with `cmake` successfully, under OSX (Apple Silicon) and Linux (amd64).

----

One question I have though... could someone enlighten me, please?
Where do these magic string come from and is it correct, that there are two magic constants for UFS?
```c
case 0x00011954:
    strcpy((char *) lpszName, "UFS");
    return sb.f_type;
case 0x35:
    strcpy((char *) lpszName, "UFS");
    return FLAG_FS_SUPPORTED * sb.f_type;
```

### CODE REVIEW

**Comment by nitram509** [comment]
> Unfortunately we lost track of where 0x35 FS magic came from. When you said:
> 
> > I did test compile the code with cmake successfully, under OSX (Apple Silicon) and Linux (amd64).
> 
> Was FS showing UNSUPPORTED before and SUPPORTED after?
> 
> Regarding the
> 
> ```
>  strcpy((char *) lpszName, "UFS");
> ```
> 
> We return FS type back to Java layer for the purpose of logging it. Unfortuately it is not actually logged. Perhaps it should be?

Ouch, lost track of this magic number sounds not good.
Will try within a Linux VM what actually happens.
Also, will google something, to figure out if there are references we could reference to.

@bluestreak01 Frankly said, if there's no evidence on 0x35 nor some references "somewhere" I do suggest dropping the issue and this PR. Will share my investigation results shortly.

**Comment by nitram509** [comment]
@bluestreak01 I did a test with Freebsd on ARM64 ... here's the good news: it works.

Here's some information on the virtual machine config and disk partitions...
```text
➜  ~ uname -a
FreeBSD  13.2-RELEASE FreeBSD 13.2-RELEASE releng/13.2-n254617-525ecfdad597 GENERIC arm64
➜  ~ sysctl hw.model hw.machine hw.ncpu
hw.model: Apple Unknown CPU r0p0 (midr: 610f0000)
hw.machine: arm64
hw.ncpu: 4
➜  questdb gpart show
=>      40  41942960  nda0  GPT  (20G)
        40    532480     1  efi  (260M)
    532520  39313408     2  freebsd-ufs  (19G)
  39845928   2097072     3  freebsd-swap  (1.0G)
```

I did compile this branch locally and got this log when starting:
```text
➜  questdb java -jar ~/projects/questdb/core/target/questdb-7.3.4-SNAPSHOT.jar start -d $(pwd)
Reading log configuration from /root/questdb/conf/log.conf
2023-11-01T00:20:19.187179Z A server-main QuestDB 7.3.4-SNAPSHOT. Copyright (C) 2014-2023, all rights reserved.
2023-11-01T00:20:19.326730Z A server-main OS/ARCH freebsd/amd64 [Vanilla,-1241693368, 64 bits, 4 processors]
2023-11-01T00:20:19.337334Z I server-main Web Console is up to date
2023-11-01T00:20:19.348210Z A server-main Server config: /root/questdb/conf/server.conf
2023-11-01T00:20:19.385932Z I i.q.c.t.t.InputFormatConfiguration loading input format config [resource=/text_loader.json]
2023-11-01T00:20:19.408006Z A server-main Config:
2023-11-01T00:20:19.408028Z A server-main  - http.enabled : true
2023-11-01T00:20:19.408045Z A server-main  - tcp.enabled  : true
2023-11-01T00:20:19.408061Z A server-main  - pg.enabled   : true
2023-11-01T00:20:19.408071Z A server-main  - attach partition suffix: .attachable
2023-11-01T00:20:19.408086Z A server-main  - open database [id=8801407787604256709.-5024912037785444107]
2023-11-01T00:20:19.408166Z A server-main  - db root: [path=/root/questdb/db, magic=0x35] -> SUPPORTED
[...]
```

So, it seems the `0x35` on FreeBSD works just fine.

That said, I was not able to simply `mkfs.ufs` on Debian nor Ubuntu. I found a package called `ufsutils` which is no more supported for Linux == I'm not sure how to test that.

**Comment by bluestreak01** [comment]
Thank you Martin for going this far testing the magic! UFS on Linux seems to be quite niche. Before declaring FS support we typically run CI & Fuzz tests for extended period of time. UFS on FreeBSD is fair, but on Linux we do not have test facility either.

PR is great! Thank you very much for the support!

**Review by bluestreak01 — DISMISSED** [review]

**Comment by nitram509** [comment]
> Thank you Martin for going this far testing the magic! UFS on Linux seems to be quite niche. Before declaring FS support we typically run CI & Fuzz tests for extended period of time. UFS on FreeBSD is fair, but on Linux we do not have test facility either.
> 
> PR is great! Thank you very much for the support!

@bluestreak01 thank you for your feedback.

One last question and one last wish then ...

* shall I remove the 0x35 from the Linux-specific jni-code then == means it would be declared unsupported? (I do think it's better, considering the weak support)
* would you please consider the "hacktoberfest-accepted" label granting for this PR? ;)

**Comment by bluestreak01** [comment]
Hi Martin, yes, removing 0x35 from linux file is a good idea! I also added the label. Great job 👍

**Comment by nitram509** [comment]
> Hi Martin, yes, removing 0x35 from linux file is a good idea! I also added the label. Great job 👍

@bluestreak01 I did remove the Linux part as discussed.
Green lights from my side.
I guess, you need to approve again (because changes committed), yes?

**Review by bluestreak01 — APPROVED** [review]

**Comment by bluestreak01** [comment]
Excellent, thank you! When build passes we can merge :)

**Pull request merged**
