### PR TITLE
fix(core): rare segfault during o3 commit of a non-wal table

### PR DESCRIPTION
**Pull request by jerrinot**
Added an assertion to the affected code path.

### CODE REVIEW

**Comment by ideoma** [comment]
#### [PR Coverage check]

:heart_eyes: **pass** : 1 / 1 (100.00%)




#### file detail

|   |path|covered line|new line|coverage|
|----|----|----|----|----|
|:large_blue_circle:|io/questdb/cairo/TableWriter.java|1|1|100.00%|

**Comment by ideoma** [comment]
#### [PR Coverage check]

:heart_eyes: **pass** : 1 / 1 (100.00%)




#### file detail

|   |path|covered line|new line|coverage|
|----|----|----|----|----|
|:large_blue_circle:|io/questdb/cairo/TableWriter.java|1|1|100.00%|

**Comment by ideoma** [comment]
#### [PR Coverage check]

:heart_eyes: **pass** : 22 / 22 (100.00%)




#### file detail

|   |path|covered line|new line|coverage|
|----|----|----|----|----|
|:large_blue_circle:|io/questdb/cairo/O3CopyJob.java|3|3|100.00%|
|:large_blue_circle:|io/questdb/cairo/VarcharTypeDriver.java|1|1|100.00%|
|:large_blue_circle:|io/questdb/cairo/O3OpenColumnJob.java|2|2|100.00%|
|:large_blue_circle:|io/questdb/griffin/UpdateOperatorImpl.java|4|4|100.00%|
|:large_blue_circle:|io/questdb/cairo/TableWriter.java|11|11|100.00%|
|:large_blue_circle:|io/questdb/cairo/StringTypeDriver.java|1|1|100.00%|

**Comment by jerrinot** [comment]
a failure due to https://github.com/questdb/questdb/issues/4285

**Review by bluestreak01 — APPROVED** [review]

**Pull request merged**
