### PR TITLE
feat(sql): change default behaviour of SAMPLE BY to ALIGN TO CALENDAR instead of ALIGN TO FIRST OBSERVATION

### PR DESCRIPTION
**Pull request by nwoolmer**
This PR changes to the default behaviour of the SAMPLE BY clause to align to calendar dates, instead of to the first observation.

This is a **BREAKING** change.

**Rationale**
[SAMPLE BY](https://questdb.io/docs/reference/sql/sample-by/) is a clause which allows users to downsample their data. This has many uses, and a common one is to chart summarised data in real time.

For example, consider the [crypto-trading demo](https://questdb.io/dashboards/crypto/), in which both the volume heat map and Bitcoin candlestick chart use SAMPLE BY. 

The volume heat map uses SAMPLE BY with its current default behaviour - aligning to the first observation.

The candlestick chart summarises the data by calendar time, and therefore samples it by calendar 1s intervals.

[Recent changes](https://github.com/questdb/questdb/pull/4259) improve the performance of many calendar-aligned SAMPLE BY queries, and it has been observed that ALIGN TO CALENDAR is the more common/popular version of SAMPLE BY in use.

Therefore, this will be made the default behaviour, and the less common ALIGN TO FIRST OBSERVATION behaviour the special case.

**Migration notes**
- If you already use SAMPLE BY with ALIGN TO CALENDAR, you do not need to change your query.
- If you use SAMPLE BY with default behaviour prior to this PR, you may need to change your query:
    - You can add ALIGN TO FIRST OBSERVATION to force the prior behaviour for a single query.
    - You can set the `cairo.sql.sampleby.default.alignment.calendar` configuration option (located in server.conf) `false`.
- Since `ALIGN TO FIRST OBSERVATION` was default behaviour, you may not have seen this syntax before. This is a direct alternative to `ALIGN TO CALENDAR` which will perform a linear sampling from the first timestamp in your data set onwards. 

**Checklist**
- [x] Add configuration option to override default behaviour of sample by
    - `cairo.sql.sampleby.default.alignment.calendar`= true for calendar, false for first observation
- [x] Modify SAMPLE BY behaviour to respect new config option if `ALIGN TO (CALENDAR/FIRST OBSERVATION)` is not explicitly set.
- [x] Override setting for existing tests, and add new tests to cover new default behaviour and config option.
- [x] Update documentation to explain changes and how to use ALIGN TO FIRST OBSERVATION
- [x] Update console UI highlighting to correctly highlight 'first observation'
- [x] Also, review breaking tests with new parallel SAMPLE BY implementation
- [x] add documented entry to the production `server.conf`

### CODE REVIEW

**Comment by ideoma** [comment]
#### [PR Coverage check]

:heart_eyes: **pass** : 55 / 58 (94.83%)




#### file detail

|   |path|covered line|new line|coverage|
|----|----|----|----|----|
|:large_blue_circle:|io/questdb/griffin/SqlParser.java|3|4|75.00%|
|:large_blue_circle:|io/questdb/griffin/engine/functions/date/TimestampFloorFunctions.java|4|5|80.00%|
|:large_blue_circle:|io/questdb/griffin/SqlOptimiser.java|30|31|96.77%|
|:large_blue_circle:|io/questdb/PropServerConfiguration.java|7|7|100.00%|
|:large_blue_circle:|io/questdb/cairo/BitmapIndexFwdNullReader.java|1|1|100.00%|
|:large_blue_circle:|io/questdb/cairo/DefaultCairoConfiguration.java|1|1|100.00%|
|:large_blue_circle:|io/questdb/griffin/model/QueryModel.java|2|2|100.00%|
|:large_blue_circle:|io/questdb/PropertyKey.java|4|4|100.00%|
|:large_blue_circle:|io/questdb/std/datetime/microtime/Timestamps.java|1|1|100.00%|
|:large_blue_circle:|io/questdb/griffin/engine/functions/date/TimestampFloorFunctionFactory.java|1|1|100.00%|
|:large_blue_circle:|io/questdb/cairo/CairoConfigurationWrapper.java|1|1|100.00%|

**Review by bluestreak01 — CHANGES_REQUESTED** [review]
PR looks good overall, there are a couple of comments, but nothing serious.

One this we need to do is to add new entry in the production `server.conf` with the
notes on the new configuration property

**Comment by ideoma** [comment]
#### [PR Coverage check]

:heart_eyes: **pass** : 55 / 58 (94.83%)




#### file detail

|   |path|covered line|new line|coverage|
|----|----|----|----|----|
|:large_blue_circle:|io/questdb/griffin/SqlParser.java|3|4|75.00%|
|:large_blue_circle:|io/questdb/griffin/engine/functions/date/TimestampFloorFunctions.java|4|5|80.00%|
|:large_blue_circle:|io/questdb/griffin/SqlOptimiser.java|30|31|96.77%|
|:large_blue_circle:|io/questdb/PropServerConfiguration.java|7|7|100.00%|
|:large_blue_circle:|io/questdb/cairo/BitmapIndexFwdNullReader.java|1|1|100.00%|
|:large_blue_circle:|io/questdb/cairo/DefaultCairoConfiguration.java|1|1|100.00%|
|:large_blue_circle:|io/questdb/griffin/model/QueryModel.java|2|2|100.00%|
|:large_blue_circle:|io/questdb/PropertyKey.java|4|4|100.00%|
|:large_blue_circle:|io/questdb/std/datetime/microtime/Timestamps.java|1|1|100.00%|
|:large_blue_circle:|io/questdb/griffin/engine/functions/date/TimestampFloorFunctionFactory.java|1|1|100.00%|
|:large_blue_circle:|io/questdb/cairo/CairoConfigurationWrapper.java|1|1|100.00%|

**Comment by ideoma** [comment]
#### [PR Coverage check]

:heart_eyes: **pass** : 62 / 64 (96.88%)




#### file detail

|   |path|covered line|new line|coverage|
|----|----|----|----|----|
|:large_blue_circle:|io/questdb/griffin/engine/functions/date/TimestampFloorFunctions.java|4|5|80.00%|
|:large_blue_circle:|io/questdb/griffin/SqlOptimiser.java|30|31|96.77%|
|:large_blue_circle:|io/questdb/PropServerConfiguration.java|7|7|100.00%|
|:large_blue_circle:|io/questdb/griffin/SqlParser.java|4|4|100.00%|
|:large_blue_circle:|io/questdb/cairo/BitmapIndexFwdNullReader.java|1|1|100.00%|
|:large_blue_circle:|io/questdb/cairo/DefaultCairoConfiguration.java|1|1|100.00%|
|:large_blue_circle:|io/questdb/griffin/model/QueryModel.java|2|2|100.00%|
|:large_blue_circle:|io/questdb/ServerMain.java|6|6|100.00%|
|:large_blue_circle:|io/questdb/PropertyKey.java|4|4|100.00%|
|:large_blue_circle:|io/questdb/std/datetime/microtime/Timestamps.java|1|1|100.00%|
|:large_blue_circle:|io/questdb/griffin/engine/functions/date/TimestampFloorFunctionFactory.java|1|1|100.00%|
|:large_blue_circle:|io/questdb/cairo/CairoConfigurationWrapper.java|1|1|100.00%|

**Comment by ideoma** [comment]
#### [PR Coverage check]

:heart_eyes: **pass** : 62 / 64 (96.88%)




#### file detail

|   |path|covered line|new line|coverage|
|----|----|----|----|----|
|:large_blue_circle:|io/questdb/griffin/engine/functions/date/TimestampFloorFunctions.java|4|5|80.00%|
|:large_blue_circle:|io/questdb/griffin/SqlOptimiser.java|30|31|96.77%|
|:large_blue_circle:|io/questdb/PropServerConfiguration.java|7|7|100.00%|
|:large_blue_circle:|io/questdb/griffin/SqlParser.java|4|4|100.00%|
|:large_blue_circle:|io/questdb/cairo/BitmapIndexFwdNullReader.java|1|1|100.00%|
|:large_blue_circle:|io/questdb/cairo/DefaultCairoConfiguration.java|1|1|100.00%|
|:large_blue_circle:|io/questdb/griffin/model/QueryModel.java|2|2|100.00%|
|:large_blue_circle:|io/questdb/ServerMain.java|6|6|100.00%|
|:large_blue_circle:|io/questdb/PropertyKey.java|4|4|100.00%|
|:large_blue_circle:|io/questdb/std/datetime/microtime/Timestamps.java|1|1|100.00%|
|:large_blue_circle:|io/questdb/griffin/engine/functions/date/TimestampFloorFunctionFactory.java|1|1|100.00%|
|:large_blue_circle:|io/questdb/cairo/CairoConfigurationWrapper.java|1|1|100.00%|

**Review by bluestreak01 — APPROVED** [review]

**Pull request merged**
