### PR TITLE
feat(sql): checkpoint_status function for read-only checks of in-progress checkpoint

### LINKED ISSUE #4868: Add SQL to check snapshot status
### Is your feature request related to a problem?

The use case is that let's say you expect snapshot to be made around 22:00 (or rather you expect the process to start at that time, but it may take up to 15 minutes). You do not want to end up in a situation where the process breaks and nobody notices it for a long time, as database is in a copy-on-write mode and uses storage like there is no tomorrow. So it may be prudent to have an automatic check at 22:30 that the snapshotting is definitely over and if it is not - see it as as a serious incident and start calling people. In order to implement it, however, one needs a read-only way of asking QuestDB nicely "are you expecting that a snapshot is being taken right now?".

### Describe the solution you'd like.

SELECT * FROM checkpoint_status()

or 

SELECT * FROM snapshot_status()

Should return enough information to find out if the snapshot is running, maybe even the time it started.

### Describe alternatives you've considered.

_No response_

### Full Name:

Alex Pelagenko

### Affiliation:

QuestDB

### Additional context

_No response_

### PR DESCRIPTION
**Pull request by puzpuzpuz**
Depends on #4821

Closes #4868

### Usage example

```sql
SELECT * FROM checkpoint_status();
```

| in_progress   | started_at |
| ------ | --------- |
| true | 2024-08-14T01:35:10.000000Z |

### CODE REVIEW

**Comment by ideoma** [comment]
#### [PR Coverage check]

:heart_eyes: **pass** : 178 / 204 (87.25%)




#### file detail

|   |path|covered line|new line|coverage|
|----|----|----|----|----|
|:large_blue_circle:|io/questdb/cairo/CairoConfigurationWrapper.java|2|3|66.67%|
|:large_blue_circle:|io/questdb/cairo/TableWriter.java|3|4|75.00%|
|:large_blue_circle:|io/questdb/cairo/CairoEngine.java|15|19|78.95%|
|:large_blue_circle:|io/questdb/PropServerConfiguration.java|8|10|80.00%|
|:large_blue_circle:|io/questdb/griffin/engine/functions/catalogue/CheckpointStatusFunctionFactory.java|41|48|85.42%|
|:large_blue_circle:|io/questdb/griffin/SqlCompilerImpl.java|24|28|85.71%|
|:large_blue_circle:|io/questdb/cairo/DatabaseCheckpointAgent.java|62|69|89.86%|
|:large_blue_circle:|io/questdb/Bootstrap.java|2|2|100.00%|
|:large_blue_circle:|io/questdb/cairo/TableUtils.java|2|2|100.00%|
|:large_blue_circle:|io/questdb/cutlass/http/processors/JsonQueryProcessor.java|2|2|100.00%|
|:large_blue_circle:|io/questdb/cairo/DefaultCairoConfiguration.java|4|4|100.00%|
|:large_blue_circle:|io/questdb/cairo/O3PartitionPurgeJob.java|1|1|100.00%|
|:large_blue_circle:|io/questdb/griffin/CompiledQueryImpl.java|2|2|100.00%|
|:large_blue_circle:|io/questdb/cutlass/text/ParallelCsvFileImporter.java|1|1|100.00%|
|:large_blue_circle:|io/questdb/cairo/pool/WriterPool.java|3|3|100.00%|
|:large_blue_circle:|io/questdb/cairo/ColumnPurgeJob.java|2|2|100.00%|
|:large_blue_circle:|io/questdb/griffin/engine/functions/catalogue/ShowTablesFunctionFactory.java|1|1|100.00%|
|:large_blue_circle:|io/questdb/griffin/engine/functions/catalogue/InformationSchemaTablesFunctionFactory.java|1|1|100.00%|
|:large_blue_circle:|io/questdb/cutlass/text/CopyTask.java|2|2|100.00%|

**Comment by ideoma** [comment]
#### [PR Coverage check]

:heart_eyes: **pass** : 49 / 77 (63.64%)




#### file detail

|   |path|covered line|new line|coverage|
|----|----|----|----|----|
|:large_blue_circle:|io/questdb/griffin/engine/functions/catalogue/CheckpointStatusFunctionFactory.java|20|46|43.48%|
|:large_blue_circle:|io/questdb/cairo/CairoConfigurationWrapper.java|3|4|75.00%|
|:large_blue_circle:|io/questdb/cairo/DatabaseCheckpointAgent.java|16|17|94.12%|
|:large_blue_circle:|io/questdb/cairo/DefaultCairoConfiguration.java|4|4|100.00%|
|:large_blue_circle:|io/questdb/cairo/DatabaseCheckpointStatus.java|1|1|100.00%|
|:large_blue_circle:|io/questdb/griffin/SqlCompilerImpl.java|5|5|100.00%|

**Review by ideoma — APPROVED** [review]

**Comment by puzpuzpuz** [comment]
@ideoma thanks for the review!

**Comment by ideoma** [comment]
#### [PR Coverage check]

:heart_eyes: **pass** : 70 / 77 (90.91%)




#### file detail

|   |path|covered line|new line|coverage|
|----|----|----|----|----|
|:large_blue_circle:|io/questdb/cairo/CairoConfigurationWrapper.java|3|4|75.00%|
|:large_blue_circle:|io/questdb/griffin/engine/functions/catalogue/CheckpointStatusFunctionFactory.java|41|46|89.13%|
|:large_blue_circle:|io/questdb/cairo/DatabaseCheckpointAgent.java|16|17|94.12%|
|:large_blue_circle:|io/questdb/cairo/DefaultCairoConfiguration.java|4|4|100.00%|
|:large_blue_circle:|io/questdb/cairo/DatabaseCheckpointStatus.java|1|1|100.00%|
|:large_blue_circle:|io/questdb/griffin/SqlCompilerImpl.java|5|5|100.00%|

**Pull request merged**
