### PR TITLE
perf(sql): more efficient pattern lookup for short ASCII patterns

### PR DESCRIPTION
**Pull request by puzpuzpuz**
Found a way to simplify `ConstContainsSwarVarcharFunction`'s SWAR loop while looking at Rosti.

```sql
-- master: 1s
-- patch:  866ms
SELECT COUNT(*) FROM hits WHERE URL LIKE '%google%';
```

### CODE REVIEW

**Comment by ideoma** [comment]
#### [PR Coverage check]

:heart_eyes: **pass** : 8 / 8 (100.00%)




#### file detail

|   |path|covered line|new line|coverage|
|----|----|----|----|----|
|:large_blue_circle:|io/questdb/griffin/engine/functions/regex/AbstractLikeVarcharFunctionFactory.java|8|8|100.00%|

**Review by mtopolnik — APPROVED** [review]

**Comment by puzpuzpuz** [comment]
@mtopolnik thanks for the review!

**Comment by ideoma** [comment]
#### [PR Coverage check]

:heart_eyes: **pass** : 9 / 9 (100.00%)




#### file detail

|   |path|covered line|new line|coverage|
|----|----|----|----|----|
|:large_blue_circle:|io/questdb/std/SwarUtils.java|1|1|100.00%|
|:large_blue_circle:|io/questdb/griffin/engine/functions/regex/AbstractLikeVarcharFunctionFactory.java|8|8|100.00%|

**Comment by puzpuzpuz** [comment]
@mtopolnik could you reapprove? I had to remove anchor from the URL in the javadoc since it looks broken and javadoc report dislikes that. See 679531aa8f3198472bffce46070a5e186c36ce9c

**Comment by ideoma** [comment]
#### [PR Coverage check]

:heart_eyes: **pass** : 9 / 9 (100.00%)




#### file detail

|   |path|covered line|new line|coverage|
|----|----|----|----|----|
|:large_blue_circle:|io/questdb/std/SwarUtils.java|1|1|100.00%|
|:large_blue_circle:|io/questdb/griffin/engine/functions/regex/AbstractLikeVarcharFunctionFactory.java|8|8|100.00%|

**Review by mtopolnik — APPROVED** [review]

**Comment by ideoma** [comment]
#### [PR Coverage check]

:heart_eyes: **pass** : 9 / 9 (100.00%)




#### file detail

|   |path|covered line|new line|coverage|
|----|----|----|----|----|
|:large_blue_circle:|io/questdb/std/SwarUtils.java|1|1|100.00%|
|:large_blue_circle:|io/questdb/griffin/engine/functions/regex/AbstractLikeVarcharFunctionFactory.java|8|8|100.00%|

**Pull request merged**
