### PR TITLE
feat(sql): parallel `sample by` implementation

### PR DESCRIPTION
**Pull request by bluestreak01**
This PR also fixes SQL issue:

- incorrect "duplicate column" error, for example from this (try on demo):
```sql
select min(timestamp), timestamp_floor('10m', timestamp) timestamp from trades;
```

- incorrect column name propagation (model merge bug)
image

Todo:
- [x] recursive `sample by` rewrite, right now it will rewrite top level SQL only
- [x] tests to assert recursive rewrites
- [x] sort out test table model memory leak in https://github.com/questdb/questdb/pull/4259/commits/d42789dc87a30627665d04f2d8a95fa05653594b
- [x] deal with scenarios, when timestamp is selected multiple times using different aliases, e.g. 
```sql
select pickup_datetime a, pickup_datetime b, avg(trip_distance) from trips where pickup_datetime in '2010' sample by 5m ALIGN to CALENDAR;
```
- [x] collapse redundant `CHOOSE` models, which leads to simpler and slightly quicker SQL execution
- [x] test that `with` clauses are also rewritten
- [x] transfer "order by" clause when collapsing "choose" models, right now these models are unnecesserily avoided
- [x] add doc to describe collapsing behaviour and the motivation
- [x] modified `order by` generator to set designated timestamp provided it is the first field in the `order by` list

Changes in test framework necessitate Enterprise PR: https://github.com/questdb/questdb-enterprise/pull/386

### CODE REVIEW

**Comment by ideoma** [comment]
#### [PR Coverage check]

:heart_eyes: **pass** : 97 / 98 (98.98%)




#### file detail

|   |path|covered line|new line|coverage|
|----|----|----|----|----|
|:large_blue_circle:|io/questdb/griffin/SqlOptimiser.java|73|74|98.65%|
|:large_blue_circle:|io/questdb/griffin/model/QueryModel.java|9|9|100.00%|
|:large_blue_circle:|io/questdb/cutlass/line/http/LineHttpSender.java|1|1|100.00%|
|:large_blue_circle:|io/questdb/griffin/SqlCodeGenerator.java|14|14|100.00%|

**Comment by ideoma** [comment]
#### [PR Coverage check]

:heart_eyes: **pass** : 153 / 154 (99.35%)




#### file detail

|   |path|covered line|new line|coverage|
|----|----|----|----|----|
|:large_blue_circle:|io/questdb/griffin/SqlOptimiser.java|107|108|99.07%|
|:large_blue_circle:|io/questdb/std/LowerCaseCharSequenceObjHashMap.java|1|1|100.00%|
|:large_blue_circle:|io/questdb/griffin/model/QueryModel.java|30|30|100.00%|
|:large_blue_circle:|io/questdb/cutlass/line/http/LineHttpSender.java|1|1|100.00%|
|:large_blue_circle:|io/questdb/griffin/SqlCodeGenerator.java|14|14|100.00%|

**Comment by ideoma** [comment]
#### [PR Coverage check]

:heart_eyes: **pass** : 156 / 161 (96.89%)




#### file detail

|   |path|covered line|new line|coverage|
|----|----|----|----|----|
|:large_blue_circle:|io/questdb/cairo/TableUtils.java|3|7|42.86%|
|:large_blue_circle:|io/questdb/griffin/SqlOptimiser.java|107|108|99.07%|
|:large_blue_circle:|io/questdb/std/LowerCaseCharSequenceObjHashMap.java|1|1|100.00%|
|:large_blue_circle:|io/questdb/griffin/model/QueryModel.java|30|30|100.00%|
|:large_blue_circle:|io/questdb/cutlass/line/http/LineHttpSender.java|1|1|100.00%|
|:large_blue_circle:|io/questdb/griffin/SqlCodeGenerator.java|14|14|100.00%|

**Comment by ideoma** [comment]
#### [PR Coverage check]

:heart_eyes: **pass** : 161 / 167 (96.41%)




#### file detail

|   |path|covered line|new line|coverage|
|----|----|----|----|----|
|:large_blue_circle:|io/questdb/cairo/TableUtils.java|3|7|42.86%|
|:large_blue_circle:|io/questdb/griffin/SqlOptimiser.java|112|114|98.25%|
|:large_blue_circle:|io/questdb/std/LowerCaseCharSequenceObjHashMap.java|1|1|100.00%|
|:large_blue_circle:|io/questdb/griffin/model/QueryModel.java|30|30|100.00%|
|:large_blue_circle:|io/questdb/cutlass/line/http/LineHttpSender.java|1|1|100.00%|
|:large_blue_circle:|io/questdb/griffin/SqlCodeGenerator.java|14|14|100.00%|

**Comment by ideoma** [comment]
#### [PR Coverage check]

:heart_eyes: **pass** : 167 / 172 (97.09%)




#### file detail

|   |path|covered line|new line|coverage|
|----|----|----|----|----|
|:large_blue_circle:|io/questdb/cairo/TableUtils.java|3|7|42.86%|
|:large_blue_circle:|io/questdb/griffin/SqlOptimiser.java|118|119|99.16%|
|:large_blue_circle:|io/questdb/std/LowerCaseCharSequenceObjHashMap.java|1|1|100.00%|
|:large_blue_circle:|io/questdb/griffin/model/QueryModel.java|30|30|100.00%|
|:large_blue_circle:|io/questdb/cutlass/line/http/LineHttpSender.java|1|1|100.00%|
|:large_blue_circle:|io/questdb/griffin/SqlCodeGenerator.java|14|14|100.00%|

**Comment by ideoma** [comment]
#### [PR Coverage check]

:heart_eyes: **pass** : 238 / 243 (97.94%)




#### file detail

|   |path|covered line|new line|coverage|
|----|----|----|----|----|
|:large_blue_circle:|io/questdb/cairo/TableUtils.java|3|7|42.86%|
|:large_blue_circle:|io/questdb/griffin/SqlOptimiser.java|170|171|99.42%|
|:large_blue_circle:|io/questdb/std/LowerCaseCharSequenceObjHashMap.java|1|1|100.00%|
|:large_blue_circle:|io/questdb/griffin/model/QueryModel.java|49|49|100.00%|
|:large_blue_circle:|io/questdb/cutlass/line/http/LineHttpSender.java|1|1|100.00%|
|:large_blue_circle:|io/questdb/griffin/SqlCodeGenerator.java|14|14|100.00%|

**Comment by ideoma** [comment]
#### [PR Coverage check]

:heart_eyes: **pass** : 250 / 255 (98.04%)




#### file detail

|   |path|covered line|new line|coverage|
|----|----|----|----|----|
|:large_blue_circle:|io/questdb/cairo/TableUtils.java|3|7|42.86%|
|:large_blue_circle:|io/questdb/griffin/SqlOptimiser.java|170|171|99.42%|
|:large_blue_circle:|io/questdb/std/LowerCaseCharSequenceObjHashMap.java|1|1|100.00%|
|:large_blue_circle:|io/questdb/griffin/model/QueryModel.java|61|61|100.00%|
|:large_blue_circle:|io/questdb/cutlass/line/http/LineHttpSender.java|1|1|100.00%|
|:large_blue_circle:|io/questdb/griffin/SqlCodeGenerator.java|14|14|100.00%|

**Comment by ideoma** [comment]
This query 

```SQL
  SELECT EventTime AS M, COUNT(*)  AS PageViews 
  FROM hits 
  SAMPLE BY 1m 
  ALIGN to calendar
  time zone 'UTC'
  ORDER BY  M
```

has designated timestamp in the results
but the newly rewritten one doesn't not

```SQL
  SELECT EventTime AS M, COUNT(*)  AS PageViews 
  FROM hits 
  SAMPLE BY 1m 
  ALIGN to calendar
  ORDER BY  M
```

**Comment by ideoma** [comment]
This query returns the same timestamp result when it's supposed to return timestamp 1 min apart

```SQL
select timestamp
from table
SAMPLE BY 1m 
ALIGN to calendar
```

**Review by ideoma — APPROVED** [review]

**Comment by bluestreak01** [comment]
order by has been stabilized in https://github.com/questdb/questdb/pull/4259/commits/80132197ded64b4ef149d0d7a137774ca846c4f5

**Comment by ideoma** [comment]
#### [PR Coverage check]

:heart_eyes: **pass** : 230 / 234 (98.29%)




#### file detail

|   |path|covered line|new line|coverage|
|----|----|----|----|----|
|:large_blue_circle:|io/questdb/cairo/TableUtils.java|3|7|42.86%|
|:large_blue_circle:|io/questdb/std/LowerCaseCharSequenceObjHashMap.java|1|1|100.00%|
|:large_blue_circle:|io/questdb/griffin/model/QueryModel.java|56|56|100.00%|
|:large_blue_circle:|io/questdb/cutlass/line/http/LineHttpSender.java|1|1|100.00%|
|:large_blue_circle:|io/questdb/griffin/SqlCodeGenerator.java|16|16|100.00%|
|:large_blue_circle:|io/questdb/griffin/SqlOptimiser.java|136|136|100.00%|
|:large_blue_circle:|io/questdb/griffin/SqlKeywords.java|17|17|100.00%|

**Comment by bluestreak01** [comment]
fixed second SQL behaviour in https://github.com/questdb/questdb/pull/4259/commits/abfd47f9135b204afd014e3c56644de60ab9976e

**Comment by ideoma** [comment]
#### [PR Coverage check]

:heart_eyes: **pass** : 235 / 240 (97.92%)




#### file detail

|   |path|covered line|new line|coverage|
|----|----|----|----|----|
|:large_blue_circle:|io/questdb/cairo/TableUtils.java|3|7|42.86%|
|:large_blue_circle:|io/questdb/griffin/SqlOptimiser.java|141|142|99.30%|
|:large_blue_circle:|io/questdb/std/LowerCaseCharSequenceObjHashMap.java|1|1|100.00%|
|:large_blue_circle:|io/questdb/griffin/model/QueryModel.java|56|56|100.00%|
|:large_blue_circle:|io/questdb/cutlass/line/http/LineHttpSender.java|1|1|100.00%|
|:large_blue_circle:|io/questdb/griffin/SqlCodeGenerator.java|16|16|100.00%|
|:large_blue_circle:|io/questdb/griffin/SqlKeywords.java|17|17|100.00%|

**Review by ideoma — APPROVED** [review]

**Pull request merged**
