### PR TITLE
fix(sql): tweak hash function to speed up FastMap

### LINKED ISSUE #1635: Very slow queries can make quest db unresponsible
### Describe the bug

When query has long time to execute (expensive join) from PgWire interface (Grafana query for example) and it is repeated for a number of times it can make QuestDB to be unresponsible and look like hanging. QuestDB cannot response to any queries then, including schema queries from WebConsole.

### To reproduce

If `msgs` tables has 12 millions of distinct `sid`, tcid` this can start to be very slow

```
select ib.ts ts1,  ob.ts-ib.ts
from msgs as ob asof join msgs as ib on ib.cid=ob.cid and ib.scid=ob.tcid
where
  ib.ts BETWEEN '2021-11-29T09:29:21.833Z' AND '2021-11-29T15:29:21.833Z' and ob.ts BETWEEN '2021-11-29T09:29:21.833Z' AND '2021-11-29T15:29:21.833Z' and
  ib.t='D' and ob.t='8' and ob.e='0'
```

this can start to process very slowly in the call stack

```
   java.lang.Thread.State: RUNNABLE
	at io.questdb.cairo.map.FastMap.probe0(io.questdb@6.1.2/FastMap.java:263)
	at io.questdb.cairo.map.FastMap$Key.createValue(io.questdb@6.1.2/FastMap.java:430)
	at io.questdb.cairo.map.FastMap$Key.createValue(io.questdb@6.1.2/FastMap.java:390)
	at io.questdb.griffin.engine.join.AsOfJoinLightRecordCursorFactory$AsOfLightJoinRecordCursor.hasNext(io.questdb@6.1.2/AsOfJoinLightRecordCursorFactory.java:174)
	at io.questdb.griffin.engine.table.FilteredRecordCursor.hasNext(io.questdb@6.1.2/FilteredRecordCursor.java:64)
	at io.questdb.griffin.engine.table.SelectedRecordCursor.hasNext(io.questdb@6.1.2/SelectedRecordCursor.java:70)
	at io.questdb.griffin.engine.AbstractVirtualFunctionRecordCursor.hasNext(io.questdb@6.1.2/AbstractVirtualFunctionRecordCursor.java:63)
	at io.questdb.cutlass.pgwire.PGConnectionContext.sendCursor0(io.questdb@6.1.2/PGConnectionContext.java:2173)
	at io.questdb.cutlass.pgwire.PGConnectionContext.sendCursor(io.questdb@6.1.2/PGConnectionContext.java:2168)
	at io.questdb.cutlass.pgwire.PGConnectionContext.processQuery(io.questdb@6.1.2/PGConnectionContext.java:2013)
	at io.questdb.cutlass.pgwire.PGConnectionContext.parse(io.questdb@6.1.2/PGConnectionContext.java:1440)
	at io.questdb.cutlass.pgwire.PGConnectionContext.handleClientOperation(io.questdb@6.1.2/PGConnectionContext.java:365)
	at io.questdb.cutlass.pgwire.PGJobContext.handleClientOperation(io.questdb@6.1.2/PGJobContext.java:68)
	at io.questdb.cutlass.pgwire.PGWireServer$1.lambda$$0(io.questdb@6.1.2/PGWireServer.java:72)
	at io.questdb.cutlass.pgwire.PGWireServer$1$$Lambda$288/0x00000008001e2440.onRequest(io.questdb@6.1.2/Unknown Source)
	at io.questdb.network.AbstractIODispatcher.processIOQueue(io.questdb@6.1.2/AbstractIODispatcher.java:162)
	at io.questdb.cutlass.pgwire.PGWireServer$1.run(io.questdb@6.1.2/PGWireServer.java:87)
	at io.questdb.mp.Worker.run(io.questdb@6.1.2/Worker.java:111)
```

### Expected Behavior

Fix Asof speed

Introduce max query timeout and abort if the time exceeded expected time. Ideally respect client setting on the query if it's set on PgWire

### Environment

```markdown
- **QuestDB version**: 6.1.2
- **OS**:
- **Browser**:
```

### Additional context

_No response_

### PR DESCRIPTION
**Pull request by ideoma**
Fixes #1635

Run time of new `testCollisionPerformanceStringKeys` before the change - 7mins, after 2 secs

### CODE REVIEW

**Comment by ideoma** [comment]
#### [PR Coverage check]

:heart_eyes: **pass** : 10 / 14 (71.43%)




#### file detail

|   |path|covered line|new line|coverage|
|----|----|----|----|----|
|:large_blue_circle:|io/questdb/std/DirectLongList.java|0|4|00.00%|
|:large_blue_circle:|io/questdb/std/Hash.java|8|8|100.00%|
|:large_blue_circle:|io/questdb/cairo/vm/api/MemoryR.java|2|2|100.00%|

**Comment by ideoma** [comment]
#### [PR Coverage check]

:heart_eyes: **pass** : 10 / 14 (71.43%)




#### file detail

|   |path|covered line|new line|coverage|
|----|----|----|----|----|
|:large_blue_circle:|io/questdb/std/DirectLongList.java|0|4|00.00%|
|:large_blue_circle:|io/questdb/std/Hash.java|8|8|100.00%|
|:large_blue_circle:|io/questdb/cairo/vm/api/MemoryR.java|2|2|100.00%|

**Comment by ideoma** [comment]
#### [PR Coverage check]

:heart_eyes: **pass** : 14 / 14 (100.00%)




#### file detail

|   |path|covered line|new line|coverage|
|----|----|----|----|----|
|:large_blue_circle:|io/questdb/std/Hash.java|8|8|100.00%|
|:large_blue_circle:|io/questdb/std/DirectLongList.java|4|4|100.00%|
|:large_blue_circle:|io/questdb/cairo/vm/api/MemoryR.java|2|2|100.00%|

**Comment by ideoma** [comment]
#### [PR Coverage check]

:heart_eyes: **pass** : 14 / 14 (100.00%)




#### file detail

|   |path|covered line|new line|coverage|
|----|----|----|----|----|
|:large_blue_circle:|io/questdb/std/Hash.java|8|8|100.00%|
|:large_blue_circle:|io/questdb/std/DirectLongList.java|4|4|100.00%|
|:large_blue_circle:|io/questdb/cairo/vm/api/MemoryR.java|2|2|100.00%|

**Review by bluestreak01 — APPROVED** [review]

**Pull request merged**
