### PR TITLE
chore(core): add two tests to exmplify use of double quotes in references to columns in ORDER BY clauses

### PR DESCRIPTION
**Pull request by marregui**
Apache Superset produces SQL that contains double quoted aliases to select columns. In the example, an aggregate function is called on a column and the resulting select column is aliased  `"SUM(sine)"`. From the SQL alchemy driver it it is difficult to discern when a token should be single/double quoted so everything that requires quotes is emitted with double quotes. The token is `SUM(sine)`, this is the name of the select column, but it contains "illegal" characters, hence the token must be double quoted. However `ORDER BY` is not expecting quoted constants (single quotes), rather contant strings (double quotes).

This PR adds two tests to exemplify usage.

## Example:

Create a table and select some aggregate data ordered by a program generaged column alias.

```sql
CREATE TABLE trigonometry AS (
    SELECT
        rnd_int(-180, 180, 1) * 1.0 angle_rad,
        rnd_symbol('A', 'B', 'C') sym,
        rnd_double() sine
    FROM long_sequence(1000)
);

SELECT 
    sym AS "sym",
    avg(angle_rad) AS angle_rad,
    sum(sine) AS "SUM(sine)"
FROM trigonometry
GROUP BY sym
ORDER BY "SUM(sine)" DESC
LIMIT 1000;
```

### CODE REVIEW

**Comment by ideoma** [comment]
#### [PR Coverage check]

:heart_eyes: **pass** : 6 / 6 (100.00%)




#### file detail

|   |path|covered line|new line|coverage|
|----|----|----|----|----|
|:large_blue_circle:|io/questdb/griffin/SqlParser.java|3|3|100.00%|
|:large_blue_circle:|io/questdb/griffin/ExpressionParser.java|3|3|100.00%|

**Review by puzpuzpuz — DISMISSED** [review]

**Comment by puzpuzpuz** [comment]
> String literals should not be accepted as aliases

That's been around for quite a while and this particular PR doesn't change this aspect of our SQL flavor. If we ban single quotes in aliases, that might break a lot of user code, so we need to be extra cautious.

**Comment by bziobrowski** [comment]
While we can't rectify the issue with single-quoted identifiers quickly, we should not encourage users to use them.
Instead, we should point users to the standard double-quoted identifiers. 
Single quoted identifiers create unnecessary ambiguities  that result in issues like this one: 

```sql
SELECT 
    sym AS 'sym',
    avg(angle_rad) AS avg_angle_rad,
    sum(sine) AS 'SUM(sine)'
FROM trigonometry
GROUP BY sym
ORDER BY 'prefix' || sym, SUM(sine) DESC
LIMIT 1000;
```

is fine in master but returns `'invalid constant: prefix'` error in this branch .

**Comment by puzpuzpuz** [comment]
> While we can't rectify the issue with single-quoted identifiers quickly, we should not encourage users to use them.

Maybe we could start with a docs update to be closer to ANSI SQL? Most of the examples in our docs use single quotes for aliases.

cc @amyshwang

**Comment by puzpuzpuz** [comment]
> amending this PR in the process.

I'd suggest merging this PR as is. We already treat quotes in the same way for object names, so this PR doesn't make anything worse.

@bziobrowski WDYT?

**Comment by bziobrowski** [comment]
While it does fix the issue of 'SUM(sine)' in order by it also introduces the error I mentioned above.

**Comment by marregui** [comment]
@bziobrowski and @puzpuzpuz I have amended the PR to keep the semantics of the single quote as a constant definitor, while double quote is kept for string definition. It blows my mind, but having amended questdb-connect to only emit double quotes seems to be working just fine. I have added just two tests to exemplify use.

@amyshwang are you confused by single/double quotes ?

**Review by bziobrowski — APPROVED** [review]
👍

**Comment by ideoma** [comment]
#### [PR Coverage check]


:heart_eyes: **pass** : 0 / 0 (0%)

**Pull request merged**
