### PR TITLE
chore(cairo): extract id generation from CairoEngine

### PR DESCRIPTION
**Pull request by glasstiger**
Extracting the logic of table id generation from CairoEngine into another class.
IDGenerator eventually will also be used to generate WalWriter ids.

### CODE REVIEW

**Comment by ideoma** [comment]
#### [PR Coverage check]

:heart_eyes: **pass** : 45 / 45 (100.00%)




#### file detail

|   |path|covered line|new line|coverage|
|----|----|----|----|----|
|:large_blue_circle:|io/questdb/cairo/mig/MigrationContext.java|1|1|100.00%|
|:large_blue_circle:|io/questdb/cairo/CairoEngine.java|9|9|100.00%|
|:large_blue_circle:|io/questdb/cairo/IDGenerator.java|35|35|100.00%|

**Comment by ideoma** [comment]
#### [PR Coverage check]

:heart_eyes: **pass** : 45 / 45 (100.00%)




#### file detail

|   |path|covered line|new line|coverage|
|----|----|----|----|----|
|:large_blue_circle:|io/questdb/cairo/mig/MigrationContext.java|1|1|100.00%|
|:large_blue_circle:|io/questdb/cairo/CairoEngine.java|9|9|100.00%|
|:large_blue_circle:|io/questdb/cairo/IDGenerator.java|35|35|100.00%|

**Review by bziobrowski — APPROVED** [review]
Looks good .

**Comment by ideoma** [comment]
#### [PR Coverage check]

:heart_eyes: **pass** : 45 / 45 (100.00%)




#### file detail

|   |path|covered line|new line|coverage|
|----|----|----|----|----|
|:large_blue_circle:|io/questdb/cairo/mig/MigrationContext.java|1|1|100.00%|
|:large_blue_circle:|io/questdb/cairo/CairoEngine.java|9|9|100.00%|
|:large_blue_circle:|io/questdb/cairo/IDGenerator.java|35|35|100.00%|

**Comment by ideoma** [comment]
#### [PR Coverage check]

:heart_eyes: **pass** : 45 / 45 (100.00%)




#### file detail

|   |path|covered line|new line|coverage|
|----|----|----|----|----|
|:large_blue_circle:|io/questdb/cairo/mig/MigrationContext.java|1|1|100.00%|
|:large_blue_circle:|io/questdb/cairo/CairoEngine.java|9|9|100.00%|
|:large_blue_circle:|io/questdb/cairo/IDGenerator.java|35|35|100.00%|

**Pull request merged**
