### PR TITLE
fix(core): restart IO syscall on EINTR

### PR DESCRIPTION
**Pull request by jerrinot**
also fixing a bug in places where restart was manually implemented. this was the old code:
```c
do {
        size_t count = len > MAX_RW_COUNT ? MAX_RW_COUNT : len;
        written = pwrite((int) fd, (void *) (address), count, writeOffset);
        if (written < 0
            // Signals should not interrupt pwrite on Linux but just to align with POSIX standards
            && errno != EINTR) {
            // If process interrupted, do another spin.
            // Negative means error. Return negative.
            return written;
        }
        len -= written;
        writeOffset += written;
        address += written;
        // Exit if written == 0 or there is nothing to write
} while (len > 0 && written > 0);
```
1. `pwrite()` returns a negative number. say `-1` 
2. check `errno` and it is `EINTR` -> you do another round
3. but before starting another round you do this:
  ```
  len -= written;
  writeOffset += written;
  address += written;
  ```
4. at this point `written` does not contain written bytes. it’s just an error code. which we treat as actual bytes written -> 💥**boom**💥

Also: As pointed out by @eugenels - `pwrite()` can actually return `EINTR` -> the comment _(Signals should not interrupt pwrite on Linux but just to align with POSIX standards)_ was misleading.

### CODE REVIEW

**Review by bluestreak01 — CHANGES_REQUESTED** [review]
great spot, thank you!

couple of places missing:
- freebsd/files.c (copy)
- readULong()

I am also dubious about necessity to check EINTR on non-blocking `send()/recv()`, why ?

**Comment by jerrinot** [comment]
@bluestreak01 will add the missing bits, somehow FreeBSD slipped out of my mind.
the ILP client actually uses `recv()` and `send()` in the blocking mode.

**Review by eugenels — COMMENTED** [review]
have you missed this pread call?

**Review by eugenels — COMMENTED** [review]
have you missed this call in freebsd/files.c:
```
while ((read_sz = pread(input, buf, sizeof buf, wrt_off)) > 0) {
```

**Review by eugenels — COMMENTED** [review]
probably the write/send/recv in the following functions should also be wrapped in a macro:
```
Java_io_questdb_std_Files_append
Java_io_questdb_network_Net_peek
Java_io_questdb_network_Net_isDead
```

**Comment by bluestreak01** [comment]
@eugenels could you review one more time pls ?

**Comment by eugenels** [comment]
looks good to me

**Comment by jerrinot** [comment]
I created an issue for the failure: https://github.com/questdb/questdb/issues/2751

**Review by bluestreak01 — APPROVED** [review]

**Pull request merged**
