### PR TITLE
chore(core): reduce disk and memory footprint of system tables

### PR DESCRIPTION
**Pull request by puzpuzpuz**
As we're getting more and more system tables, their overhead may become noticeable for the user. This PR makes the footprint of system tables much smaller than the footprint of user's tables: 256KB for append pages and O3 memory.

### CODE REVIEW

**Comment by ideoma** [comment]
#### [PR Coverage check]

:heart_eyes: **pass** : 54 / 65 (83.08%)




#### file detail

|   |path|covered line|new line|coverage|
|----|----|----|----|----|
|:large_blue_circle:|io/questdb/cairo/CairoConfigurationWrapper.java|0|3|00.00%|
|:large_blue_circle:|io/questdb/cairo/wal/WalWriter.java|2|3|66.67%|
|:large_blue_circle:|io/questdb/cairo/DefaultCairoConfiguration.java|2|3|66.67%|
|:large_blue_circle:|io/questdb/cairo/TableNameRegistryStore.java|6|9|66.67%|
|:large_blue_circle:|io/questdb/cairo/TableToken.java|16|19|84.21%|
|:large_blue_circle:|io/questdb/cairo/TableConverter.java|2|2|100.00%|
|:large_blue_circle:|io/questdb/cairo/TableNameRegistry.java|1|1|100.00%|
|:large_blue_circle:|io/questdb/PropServerConfiguration.java|6|6|100.00%|
|:large_blue_circle:|io/questdb/cairo/TableUtils.java|2|2|100.00%|
|:large_blue_circle:|io/questdb/griffin/engine/functions/test/TestDataUnavailableFunctionFactory.java|1|1|100.00%|
|:large_blue_circle:|io/questdb/cairo/TableNameRegistryRW.java|2|2|100.00%|
|:large_blue_circle:|io/questdb/PropertyKey.java|3|3|100.00%|
|:large_blue_circle:|io/questdb/griffin/UpdateOperatorImpl.java|1|1|100.00%|
|:large_blue_circle:|io/questdb/griffin/SqlCompilerImpl.java|1|1|100.00%|
|:large_blue_circle:|io/questdb/cairo/TableWriter.java|6|6|100.00%|
|:large_blue_circle:|io/questdb/cairo/AbstractTableNameRegistry.java|1|1|100.00%|
|:large_blue_circle:|io/questdb/cutlass/text/CopyTask.java|2|2|100.00%|

**Comment by ideoma** [comment]
#### [PR Coverage check]

:heart_eyes: **pass** : 54 / 65 (83.08%)




#### file detail

|   |path|covered line|new line|coverage|
|----|----|----|----|----|
|:large_blue_circle:|io/questdb/cairo/CairoConfigurationWrapper.java|0|3|00.00%|
|:large_blue_circle:|io/questdb/cairo/wal/WalWriter.java|2|3|66.67%|
|:large_blue_circle:|io/questdb/cairo/DefaultCairoConfiguration.java|2|3|66.67%|
|:large_blue_circle:|io/questdb/cairo/TableNameRegistryStore.java|6|9|66.67%|
|:large_blue_circle:|io/questdb/cairo/TableToken.java|16|19|84.21%|
|:large_blue_circle:|io/questdb/cairo/TableConverter.java|2|2|100.00%|
|:large_blue_circle:|io/questdb/cairo/TableNameRegistry.java|1|1|100.00%|
|:large_blue_circle:|io/questdb/PropServerConfiguration.java|6|6|100.00%|
|:large_blue_circle:|io/questdb/cairo/TableUtils.java|2|2|100.00%|
|:large_blue_circle:|io/questdb/griffin/engine/functions/test/TestDataUnavailableFunctionFactory.java|1|1|100.00%|
|:large_blue_circle:|io/questdb/cairo/TableNameRegistryRW.java|2|2|100.00%|
|:large_blue_circle:|io/questdb/PropertyKey.java|3|3|100.00%|
|:large_blue_circle:|io/questdb/griffin/UpdateOperatorImpl.java|1|1|100.00%|
|:large_blue_circle:|io/questdb/griffin/SqlCompilerImpl.java|1|1|100.00%|
|:large_blue_circle:|io/questdb/cairo/TableWriter.java|6|6|100.00%|
|:large_blue_circle:|io/questdb/cairo/AbstractTableNameRegistry.java|1|1|100.00%|
|:large_blue_circle:|io/questdb/cutlass/text/CopyTask.java|2|2|100.00%|

**Comment by bluestreak01** [comment]
looks good notwithstanding test failure!

**Comment by ideoma** [comment]
#### [PR Coverage check]

:heart_eyes: **pass** : 54 / 65 (83.08%)




#### file detail

|   |path|covered line|new line|coverage|
|----|----|----|----|----|
|:large_blue_circle:|io/questdb/cairo/CairoConfigurationWrapper.java|0|3|00.00%|
|:large_blue_circle:|io/questdb/cairo/wal/WalWriter.java|2|3|66.67%|
|:large_blue_circle:|io/questdb/cairo/DefaultCairoConfiguration.java|2|3|66.67%|
|:large_blue_circle:|io/questdb/cairo/TableNameRegistryStore.java|6|9|66.67%|
|:large_blue_circle:|io/questdb/cairo/TableToken.java|16|19|84.21%|
|:large_blue_circle:|io/questdb/cairo/TableConverter.java|2|2|100.00%|
|:large_blue_circle:|io/questdb/cairo/TableNameRegistry.java|1|1|100.00%|
|:large_blue_circle:|io/questdb/PropServerConfiguration.java|6|6|100.00%|
|:large_blue_circle:|io/questdb/cairo/TableUtils.java|2|2|100.00%|
|:large_blue_circle:|io/questdb/griffin/engine/functions/test/TestDataUnavailableFunctionFactory.java|1|1|100.00%|
|:large_blue_circle:|io/questdb/cairo/TableNameRegistryRW.java|2|2|100.00%|
|:large_blue_circle:|io/questdb/PropertyKey.java|3|3|100.00%|
|:large_blue_circle:|io/questdb/griffin/UpdateOperatorImpl.java|1|1|100.00%|
|:large_blue_circle:|io/questdb/griffin/SqlCompilerImpl.java|1|1|100.00%|
|:large_blue_circle:|io/questdb/cairo/TableWriter.java|6|6|100.00%|
|:large_blue_circle:|io/questdb/cairo/AbstractTableNameRegistry.java|1|1|100.00%|
|:large_blue_circle:|io/questdb/cutlass/text/CopyTask.java|2|2|100.00%|

**Comment by puzpuzpuz** [comment]
> looks good notwithstanding test failure!

Should be fixed now.

**Review by bluestreak01 — APPROVED** [review]

**Pull request merged**
