### PR TITLE
fix(sql): incorrect results returned from parallel GROUP BY with single varchar function key

### PR DESCRIPTION
**Pull request by puzpuzpuz**
`UnorderedVarcharMapRecord#copyToKey()` was copying pointers from another `UnorderedVarcharMap`, even unstable ones.

Also, reduces memory overhead for such queries by getting rid of redundant key allocations.

### CODE REVIEW

**Comment by puzpuzpuz** [comment]
Linter issues are fixed in #4796

**Comment by ideoma** [comment]
#### [PR Coverage check]

:heart_eyes: **pass** : 25 / 26 (96.15%)




#### file detail

|   |path|covered line|new line|coverage|
|----|----|----|----|----|
|:large_blue_circle:|io/questdb/cairo/map/UnorderedVarcharMap.java|25|26|96.15%|

**Comment by ideoma** [comment]
#### [PR Coverage check]

:heart_eyes: **pass** : 30 / 30 (100.00%)




#### file detail

|   |path|covered line|new line|coverage|
|----|----|----|----|----|
|:large_blue_circle:|io/questdb/cairo/map/UnorderedVarcharMap.java|30|30|100.00%|

**Review by bluestreak01 — APPROVED** [review]

**Comment by ideoma** [comment]
#### [PR Coverage check]

:heart_eyes: **pass** : 30 / 30 (100.00%)




#### file detail

|   |path|covered line|new line|coverage|
|----|----|----|----|----|
|:large_blue_circle:|io/questdb/cairo/map/UnorderedVarcharMap.java|30|30|100.00%|

**Pull request merged**
