### PR TITLE
fix(sql): fix parsing and execution of indexed symbol predicates

### PR DESCRIPTION
**Pull request by bziobrowski**
PR fixes following issues related to processing of predicates using indexed symbol, including :  
- s = function call gave wrong results because s was compared not to result but name of function.  
- lack of type  meant ':a' or '$x' literals could either be interpreted as bind variables 
- s not in () set  calculation 
- merging of s in () and s not in () sets 
- in some cases both key and keyExcluded sets were set making sql code generator produce wrong factory (that used only excluded keys but)
- duplicates appearing in included or excluded keys (via bind variables) produced wrong results 
- ...

### CODE REVIEW

**Comment by bziobrowski** [comment]
Ready for review but I've to refactor WhereClauseParser a bit .

**Comment by ideoma** [comment]
#### [PR Coverage check]

:heart_eyes: **pass** : 334 / 342 (97.66%)




#### file detail

|   |path|covered line|new line|coverage|
|----|----|----|----|----|
|:large_blue_circle:|io/questdb/griffin/engine/table/FilterOnValuesRecordCursorFactory.java|25|26|96.15%|
|:large_blue_circle:|io/questdb/griffin/WhereClauseParser.java|282|289|97.58%|
|:large_blue_circle:|io/questdb/griffin/engine/table/HeapRowCursor.java|1|1|100.00%|
|:large_blue_circle:|io/questdb/griffin/engine/table/FilterOnSubQueryRecordCursorFactory.java|4|4|100.00%|
|:large_blue_circle:|io/questdb/std/IntList.java|1|1|100.00%|
|:large_blue_circle:|io/questdb/griffin/engine/table/HeapRowCursorFactory.java|3|3|100.00%|
|:large_blue_circle:|io/questdb/griffin/engine/table/SequentialRowCursorFactory.java|5|5|100.00%|
|:large_blue_circle:|io/questdb/std/CharSequenceHashSet.java|1|1|100.00%|
|:large_blue_circle:|io/questdb/griffin/FunctionParser.java|2|2|100.00%|
|:large_blue_circle:|io/questdb/griffin/engine/table/FilterOnExcludedValuesRecordCursorFactory.java|10|10|100.00%|

**Comment by ideoma** [comment]
#### [PR Coverage check]

:heart_eyes: **pass** : 362 / 377 (96.02%)




#### file detail

|   |path|covered line|new line|coverage|
|----|----|----|----|----|
|:large_blue_circle:|io/questdb/griffin/WhereClauseParser.java|310|324|95.68%|
|:large_blue_circle:|io/questdb/griffin/engine/table/FilterOnValuesRecordCursorFactory.java|25|26|96.15%|
|:large_blue_circle:|io/questdb/griffin/engine/table/HeapRowCursor.java|1|1|100.00%|
|:large_blue_circle:|io/questdb/griffin/engine/table/FilterOnSubQueryRecordCursorFactory.java|4|4|100.00%|
|:large_blue_circle:|io/questdb/std/IntList.java|1|1|100.00%|
|:large_blue_circle:|io/questdb/griffin/engine/table/HeapRowCursorFactory.java|3|3|100.00%|
|:large_blue_circle:|io/questdb/griffin/engine/table/SequentialRowCursorFactory.java|5|5|100.00%|
|:large_blue_circle:|io/questdb/std/CharSequenceHashSet.java|1|1|100.00%|
|:large_blue_circle:|io/questdb/griffin/FunctionParser.java|2|2|100.00%|
|:large_blue_circle:|io/questdb/griffin/engine/table/FilterOnExcludedValuesRecordCursorFactory.java|10|10|100.00%|

**Comment by ideoma** [comment]
#### [PR Coverage check]

:heart_eyes: **pass** : 401 / 417 (96.16%)




#### file detail

|   |path|covered line|new line|coverage|
|----|----|----|----|----|
|:large_blue_circle:|io/questdb/std/IntList.java|0|1|00.00%|
|:large_blue_circle:|io/questdb/griffin/engine/table/FilterOnValuesRecordCursorFactory.java|25|26|96.15%|
|:large_blue_circle:|io/questdb/griffin/WhereClauseParser.java|350|364|96.15%|
|:large_blue_circle:|io/questdb/griffin/engine/table/HeapRowCursor.java|1|1|100.00%|
|:large_blue_circle:|io/questdb/griffin/engine/table/FilterOnSubQueryRecordCursorFactory.java|4|4|100.00%|
|:large_blue_circle:|io/questdb/griffin/engine/table/HeapRowCursorFactory.java|3|3|100.00%|
|:large_blue_circle:|io/questdb/griffin/engine/table/SequentialRowCursorFactory.java|5|5|100.00%|
|:large_blue_circle:|io/questdb/std/CharSequenceHashSet.java|1|1|100.00%|
|:large_blue_circle:|io/questdb/griffin/FunctionParser.java|2|2|100.00%|
|:large_blue_circle:|io/questdb/griffin/engine/table/FilterOnExcludedValuesRecordCursorFactory.java|10|10|100.00%|

**Comment by ideoma** [comment]
#### [PR Coverage check]

:heart_eyes: **pass** : 401 / 417 (96.16%)




#### file detail

|   |path|covered line|new line|coverage|
|----|----|----|----|----|
|:large_blue_circle:|io/questdb/std/IntList.java|0|1|00.00%|
|:large_blue_circle:|io/questdb/griffin/engine/table/FilterOnValuesRecordCursorFactory.java|25|26|96.15%|
|:large_blue_circle:|io/questdb/griffin/WhereClauseParser.java|350|364|96.15%|
|:large_blue_circle:|io/questdb/griffin/engine/table/HeapRowCursor.java|1|1|100.00%|
|:large_blue_circle:|io/questdb/griffin/engine/table/FilterOnSubQueryRecordCursorFactory.java|4|4|100.00%|
|:large_blue_circle:|io/questdb/griffin/engine/table/HeapRowCursorFactory.java|3|3|100.00%|
|:large_blue_circle:|io/questdb/griffin/engine/table/SequentialRowCursorFactory.java|5|5|100.00%|
|:large_blue_circle:|io/questdb/std/CharSequenceHashSet.java|1|1|100.00%|
|:large_blue_circle:|io/questdb/griffin/FunctionParser.java|2|2|100.00%|
|:large_blue_circle:|io/questdb/griffin/engine/table/FilterOnExcludedValuesRecordCursorFactory.java|10|10|100.00%|

**Comment by ideoma** [comment]
#### [PR Coverage check]

:heart_eyes: **pass** : 401 / 417 (96.16%)




#### file detail

|   |path|covered line|new line|coverage|
|----|----|----|----|----|
|:large_blue_circle:|io/questdb/std/IntList.java|0|1|00.00%|
|:large_blue_circle:|io/questdb/griffin/engine/table/FilterOnValuesRecordCursorFactory.java|25|26|96.15%|
|:large_blue_circle:|io/questdb/griffin/WhereClauseParser.java|350|364|96.15%|
|:large_blue_circle:|io/questdb/griffin/engine/table/HeapRowCursor.java|1|1|100.00%|
|:large_blue_circle:|io/questdb/griffin/engine/table/FilterOnSubQueryRecordCursorFactory.java|4|4|100.00%|
|:large_blue_circle:|io/questdb/griffin/engine/table/HeapRowCursorFactory.java|3|3|100.00%|
|:large_blue_circle:|io/questdb/griffin/engine/table/SequentialRowCursorFactory.java|5|5|100.00%|
|:large_blue_circle:|io/questdb/std/CharSequenceHashSet.java|1|1|100.00%|
|:large_blue_circle:|io/questdb/griffin/FunctionParser.java|2|2|100.00%|
|:large_blue_circle:|io/questdb/griffin/engine/table/FilterOnExcludedValuesRecordCursorFactory.java|10|10|100.00%|

**Pull request merged**
