### PR TITLE
chore(ilp): reducing ILP writer idle timeout default settings

### PR DESCRIPTION
**Pull request by glasstiger**
Reducing ILP writer idle timeout default settings so users would not have to wait 20-30 seconds for the ingested data to be available for queries.
With the new defaults the data becomes visible within 1.5 seconds after ingestion stops.
```
line.tcp.maintenance.job.interval:          30000 -> 1000
line.tcp.min.idle.ms.before.writer.release: 10000 ->  500
```

--------------------------------------------------------------------------
Run TSBS test to validate that the new defaults have no impact on the benchmark.
Top 3 results out of 15 runs with OLD defaults:
```
	1240635.76 rows/sec
	1277743.29 rows/sec
	1285371.49 rows/sec
```
Top 3 results out of 15 runs with NEW defaults:
```
	1238491.44 rows/sec
	1266766.31 rows/sec
	1295807.82 rows/sec
```
--------------------------------------------------------------------------
Documentation will be updated to reflect the changes in a separate PR.

### CODE REVIEW

**Comment by ideoma** [comment]
#### [PR Coverage check]

:heart_eyes: **pass** : 2 / 2 (100.00%)




#### file detail

|   |path|covered line|new line|coverage|
|----|----|----|----|----|
|:large_blue_circle:|io/questdb/PropServerConfiguration.java|2|2|100.00%|

**Review by bluestreak01 — APPROVED** [review]

**Comment by ideoma** [comment]
#### [PR Coverage check]

:heart_eyes: **pass** : 2 / 2 (100.00%)




#### file detail

|   |path|covered line|new line|coverage|
|----|----|----|----|----|
|:large_blue_circle:|io/questdb/PropServerConfiguration.java|2|2|100.00%|

**Review by bluestreak01 — APPROVED** [review]

**Comment by ideoma** [comment]
#### [PR Coverage check]

:heart_eyes: **pass** : 2 / 2 (100.00%)




#### file detail

|   |path|covered line|new line|coverage|
|----|----|----|----|----|
|:large_blue_circle:|io/questdb/PropServerConfiguration.java|2|2|100.00%|

**Comment by puzpuzpuz** [comment]
@amyshwang this PR changes default settings, so probably it should be on your radar.

**Pull request merged**
