### PR TITLE
chore(wal): non-WAL to WAL, WAL to non-WAL table conversions

### PR DESCRIPTION
**Pull request by glasstiger**
- non-WAL to WAL table conversion
- WAL to non-WAL table conversion

syntax:
```
ALTER TABLE <tablename>` SET TYPE WAL;
ALTER TABLE <tablename>` SET TYPE BYPASS WAL;
```

### CODE REVIEW

**Comment by ideoma** [comment]
#### [PR Coverage check]

:heart_eyes: **pass** : 47 / 53 (88.68%)




#### file detail

|   |path|covered line|new line|coverage|
|----|----|----|----|----|
|:large_blue_circle:|io/questdb/cairo/TableNameRegistryRO.java|0|1|00.00%|
|:large_blue_circle:|io/questdb/cairo/TableNameRegistryRW.java|9|11|81.82%|
|:large_blue_circle:|io/questdb/cairo/CairoEngine.java|27|30|90.00%|
|:large_blue_circle:|io/questdb/cairo/wal/seq/TableSequencerImpl.java|1|1|100.00%|
|:large_blue_circle:|io/questdb/cairo/wal/seq/SequencerMetadata.java|5|5|100.00%|
|:large_blue_circle:|io/questdb/cairo/wal/seq/TableSequencerAPI.java|5|5|100.00%|

**Comment by ideoma** [comment]
#### [PR Coverage check]

:heart_eyes: **pass** : 61 / 70 (87.14%)




#### file detail

|   |path|covered line|new line|coverage|
|----|----|----|----|----|
|:large_blue_circle:|io/questdb/cairo/TableNameRegistryRO.java|0|1|00.00%|
|:large_blue_circle:|io/questdb/cairo/TableNameRegistryRW.java|8|10|80.00%|
|:large_blue_circle:|io/questdb/cairo/CairoEngine.java|36|42|85.71%|
|:large_blue_circle:|io/questdb/cairo/wal/seq/TableSequencerImpl.java|1|1|100.00%|
|:large_blue_circle:|io/questdb/cairo/wal/seq/SequencerMetadata.java|5|5|100.00%|
|:large_blue_circle:|io/questdb/cairo/wal/seq/TableSequencerAPI.java|11|11|100.00%|

**Comment by bluestreak01** [comment]
before we release WAL everything should be a chore :)

**Comment by glasstiger** [comment]
superseded by #2947

**Comment by glasstiger** [comment]
> @glasstiger should we delete this branch?

just did.
thanks for the reminder.

**Pull request closed without merging**
