### PR TITLE
fix(sql): ORDER BY symbol column from table UNION query

### PR DESCRIPTION
**Pull request by ideoma**
Order by symbol column over a UNION query returned incorrect results. Here sym, sym2 are of type SYMBOL:

```
select * from 
(
  select sym from table1
  union all
  select sym2 from table2
)
order by sym
```

The result can contains random values.

Underlying reason for the problem is that UNION and UNION ALL record factories could not resolve symbol key (int) back to string value since the key can belong to 2 different symbol tables.
To solve that a special `DelegatingSymbolRecordImpl` is created with `DelegateSymbolTable` which shifts second table symbol keys making the keys unique across the whole  set.

Also in SQL `UNION` will remove duplicates even on master table. If there is a table like

```
create table x (a int);

insert into x values(1);
insert into x values(1);
insert into x values(2);

create table y (a int);
insert into x values(3);

select a from x
union 
select a from y
```

This will return 

```
1
2
3
```

While it used to return 

```
1
1
2
3
```

This will align QuestDB UNION with ANSI SQL UNION.

This PR replaces https://github.com/questdb/questdb/pull/2123

### CODE REVIEW

**Comment by ideoma** [comment]
#### [PR Coverage check]

:heart_eyes: **pass** : 128 / 135 (94.81%)




#### file detail

|   |path|covered line|new line|coverage|
|----|----|----|----|----|
|:large_blue_circle:|io/questdb/cairo/sql/DelegatingRecordImpl.java|10|12|83.33%|
|:large_blue_circle:|io/questdb/cairo/sql/RecordMetadata.java|5|6|83.33%|
|:large_blue_circle:|io/questdb/griffin/engine/functions/catalogue/AttributeCatalogueFunctionFactory.java|5|6|83.33%|
|:large_blue_circle:|io/questdb/griffin/engine/union/UnionAllRecordCursor.java|18|19|94.74%|
|:large_blue_circle:|io/questdb/griffin/engine/union/UnionRecordCursor.java|23|24|95.83%|
|:large_blue_circle:|io/questdb/griffin/engine/union/DelegatingSymbolRecordImpl.java|53|54|98.15%|
|:large_blue_circle:|io/questdb/griffin/engine/union/ExceptRecordCursorFactory.java|1|1|100.00%|
|:large_blue_circle:|io/questdb/griffin/engine/union/UnionAllRecordCursorFactory.java|1|1|100.00%|
|:large_blue_circle:|io/questdb/griffin/engine/table/VirtualRecordCursorFactory.java|1|1|100.00%|
|:large_blue_circle:|io/questdb/griffin/engine/groupby/SampleByInterpolateRecordCursorFactory.java|1|1|100.00%|
|:large_blue_circle:|io/questdb/griffin/engine/functions/catalogue/AbstractClassCatalogueFunctionFactory.java|3|3|100.00%|
|:large_blue_circle:|io/questdb/griffin/engine/orderby/SortedLightRecordCursorFactory.java|1|1|100.00%|
|:large_blue_circle:|io/questdb/griffin/engine/union/UnionRecordCursorFactory.java|1|1|100.00%|
|:large_blue_circle:|io/questdb/griffin/engine/groupby/GroupByRecordCursorFactory.java|1|1|100.00%|
|:large_blue_circle:|io/questdb/griffin/engine/union/IntersectRecordCursorFactory.java|1|1|100.00%|
|:large_blue_circle:|io/questdb/griffin/engine/orderby/SortedRecordCursorFactory.java|1|1|100.00%|
|:large_blue_circle:|io/questdb/griffin/engine/union/IntersectRecordCursor.java|2|2|100.00%|

**Comment by ideoma** [comment]
#### [PR Coverage check]

:heart_eyes: **pass** : 128 / 135 (94.81%)




#### file detail

|   |path|covered line|new line|coverage|
|----|----|----|----|----|
|:large_blue_circle:|io/questdb/cairo/sql/DelegatingRecordImpl.java|10|12|83.33%|
|:large_blue_circle:|io/questdb/cairo/sql/RecordMetadata.java|5|6|83.33%|
|:large_blue_circle:|io/questdb/griffin/engine/functions/catalogue/AttributeCatalogueFunctionFactory.java|5|6|83.33%|
|:large_blue_circle:|io/questdb/griffin/engine/union/UnionAllRecordCursor.java|18|19|94.74%|
|:large_blue_circle:|io/questdb/griffin/engine/union/UnionRecordCursor.java|23|24|95.83%|
|:large_blue_circle:|io/questdb/griffin/engine/union/DelegatingSymbolRecordImpl.java|53|54|98.15%|
|:large_blue_circle:|io/questdb/griffin/engine/union/ExceptRecordCursorFactory.java|1|1|100.00%|
|:large_blue_circle:|io/questdb/griffin/engine/union/UnionAllRecordCursorFactory.java|1|1|100.00%|
|:large_blue_circle:|io/questdb/griffin/engine/table/VirtualRecordCursorFactory.java|1|1|100.00%|
|:large_blue_circle:|io/questdb/griffin/engine/groupby/SampleByInterpolateRecordCursorFactory.java|1|1|100.00%|
|:large_blue_circle:|io/questdb/griffin/engine/functions/catalogue/AbstractClassCatalogueFunctionFactory.java|3|3|100.00%|
|:large_blue_circle:|io/questdb/griffin/engine/orderby/SortedLightRecordCursorFactory.java|1|1|100.00%|
|:large_blue_circle:|io/questdb/griffin/engine/union/UnionRecordCursorFactory.java|1|1|100.00%|
|:large_blue_circle:|io/questdb/griffin/engine/groupby/GroupByRecordCursorFactory.java|1|1|100.00%|
|:large_blue_circle:|io/questdb/griffin/engine/union/IntersectRecordCursorFactory.java|1|1|100.00%|
|:large_blue_circle:|io/questdb/griffin/engine/orderby/SortedRecordCursorFactory.java|1|1|100.00%|
|:large_blue_circle:|io/questdb/griffin/engine/union/IntersectRecordCursor.java|2|2|100.00%|

**Comment by ideoma** [comment]
#### [PR Coverage check]

:heart_eyes: **pass** : 128 / 135 (94.81%)




#### file detail

|   |path|covered line|new line|coverage|
|----|----|----|----|----|
|:large_blue_circle:|io/questdb/cairo/sql/DelegatingRecordImpl.java|10|12|83.33%|
|:large_blue_circle:|io/questdb/cairo/sql/RecordMetadata.java|5|6|83.33%|
|:large_blue_circle:|io/questdb/griffin/engine/functions/catalogue/AttributeCatalogueFunctionFactory.java|5|6|83.33%|
|:large_blue_circle:|io/questdb/griffin/engine/union/UnionAllRecordCursor.java|18|19|94.74%|
|:large_blue_circle:|io/questdb/griffin/engine/union/UnionRecordCursor.java|23|24|95.83%|
|:large_blue_circle:|io/questdb/griffin/engine/union/DelegatingSymbolRecordImpl.java|53|54|98.15%|
|:large_blue_circle:|io/questdb/griffin/engine/union/ExceptRecordCursorFactory.java|1|1|100.00%|
|:large_blue_circle:|io/questdb/griffin/engine/union/UnionAllRecordCursorFactory.java|1|1|100.00%|
|:large_blue_circle:|io/questdb/griffin/engine/table/VirtualRecordCursorFactory.java|1|1|100.00%|
|:large_blue_circle:|io/questdb/griffin/engine/groupby/SampleByInterpolateRecordCursorFactory.java|1|1|100.00%|
|:large_blue_circle:|io/questdb/griffin/engine/functions/catalogue/AbstractClassCatalogueFunctionFactory.java|3|3|100.00%|
|:large_blue_circle:|io/questdb/griffin/engine/orderby/SortedLightRecordCursorFactory.java|1|1|100.00%|
|:large_blue_circle:|io/questdb/griffin/engine/union/UnionRecordCursorFactory.java|1|1|100.00%|
|:large_blue_circle:|io/questdb/griffin/engine/groupby/GroupByRecordCursorFactory.java|1|1|100.00%|
|:large_blue_circle:|io/questdb/griffin/engine/union/IntersectRecordCursorFactory.java|1|1|100.00%|
|:large_blue_circle:|io/questdb/griffin/engine/orderby/SortedRecordCursorFactory.java|1|1|100.00%|
|:large_blue_circle:|io/questdb/griffin/engine/union/IntersectRecordCursor.java|2|2|100.00%|

**Comment by ideoma** [comment]
#### [PR Coverage check]

:heart_eyes: **pass** : 128 / 135 (94.81%)




#### file detail

|   |path|covered line|new line|coverage|
|----|----|----|----|----|
|:large_blue_circle:|io/questdb/cairo/sql/DelegatingRecordImpl.java|10|12|83.33%|
|:large_blue_circle:|io/questdb/cairo/sql/RecordMetadata.java|5|6|83.33%|
|:large_blue_circle:|io/questdb/griffin/engine/functions/catalogue/AttributeCatalogueFunctionFactory.java|5|6|83.33%|
|:large_blue_circle:|io/questdb/griffin/engine/union/UnionAllRecordCursor.java|18|19|94.74%|
|:large_blue_circle:|io/questdb/griffin/engine/union/UnionRecordCursor.java|23|24|95.83%|
|:large_blue_circle:|io/questdb/griffin/engine/union/DelegatingSymbolRecordImpl.java|53|54|98.15%|
|:large_blue_circle:|io/questdb/griffin/engine/union/ExceptRecordCursorFactory.java|1|1|100.00%|
|:large_blue_circle:|io/questdb/griffin/engine/union/UnionAllRecordCursorFactory.java|1|1|100.00%|
|:large_blue_circle:|io/questdb/griffin/engine/table/VirtualRecordCursorFactory.java|1|1|100.00%|
|:large_blue_circle:|io/questdb/griffin/engine/groupby/SampleByInterpolateRecordCursorFactory.java|1|1|100.00%|
|:large_blue_circle:|io/questdb/griffin/engine/functions/catalogue/AbstractClassCatalogueFunctionFactory.java|3|3|100.00%|
|:large_blue_circle:|io/questdb/griffin/engine/orderby/SortedLightRecordCursorFactory.java|1|1|100.00%|
|:large_blue_circle:|io/questdb/griffin/engine/union/UnionRecordCursorFactory.java|1|1|100.00%|
|:large_blue_circle:|io/questdb/griffin/engine/groupby/GroupByRecordCursorFactory.java|1|1|100.00%|
|:large_blue_circle:|io/questdb/griffin/engine/union/IntersectRecordCursorFactory.java|1|1|100.00%|
|:large_blue_circle:|io/questdb/griffin/engine/orderby/SortedRecordCursorFactory.java|1|1|100.00%|
|:large_blue_circle:|io/questdb/griffin/engine/union/IntersectRecordCursor.java|2|2|100.00%|

**Review by bluestreak01 — CHANGES_REQUESTED** [review]

**Comment by ideoma** [comment]
back to the version of making string out of symbol in Unions

**Pull request closed without merging**
