### PR TITLE
chore(build): scaffolding to build Rust in QuestDB

### PR DESCRIPTION
**Pull request by amunra**
# Overview

Advanced Rust build integration into QuestDB.
This improves over the Rust integration we have in `master` by avoiding to check in binaries into the source repo.

# Tasks

- [x] Introduce a new Rust crate
- [x] Wire it up with Maven
- [x] Get CI building and running existing tests
- [x] Start "tandem" ent PR, only one dynamic lib for both.
- [x] Logging infra.
- [x] Failpoints infra. 
- [x] Move maven build logic to a profile.
  - This is so we don't need to build it from `ent` where we will build a single combined dynamic lib.
- [x] Enhance `io.questdb.std.Qdb` so it can be initialised without loading the dynamic lib from ent.
- [x] IntelliJ integration via Ant
- [x] A new CI job to `cargo clippy`, `cargo fmt` and `cargo test`.
- [x] Cut and upgrade `rust-maven-plugin`: https://github.com/questdb/rust-maven-plugin/pull/40
  - [x] Remove use of profile and use `<skip>${qdb.skip}</skip>` instead: This will allow the IntelliJ-via-Ant integration to work.

- [ ] Add rust building docs, e.g. to configure the intellij ant plugin accordingly.
- [ ] Update contributor's guide docs.
- [ ] enhance CI jobs to cut Rust binaries for all the platforms we require during release process.

### CODE REVIEW

**Comment by questdb-butler** [comment]
<table>
  <thead>
    <tr>
      <th width="50"></th>
      <th width="100%" data-danger-table="true">Fails</th>
    </tr>
  </thead>
  <tbody><tr>
      <td>:no_entry_sign:</td>
      <td>

  Please update the PR title to match this format:
`type(subType): description`

Where `type` is one of:
`feat`, `fix`, `chore`, `docs`, `style`, `refactor`, `perf`, `test`, `ci`, `revert`

And: `subType` is one of:
`build`, `sql`, `log`, `mig`, `core`, `ilp`, `pgwire`, `http`, `conf`, `ui`, `wal`

For Example:

```
perf(sql): improve pattern matching performance for SELECT sub-queries
```
  </td>
    </tr>
  </tbody>
</table>




<p align="right">
  Generated by :no_entry_sign: <a href="https://danger.systems/js">dangerJS</a> against 808d9b65b3219f60cd6165549d11b56a8e423704
</p>

**Comment by ideoma** [comment]
#### [PR Coverage check]

:heart_eyes: **pass** : 4 / 5 (80.00%)




#### file detail

|   |path|covered line|new line|coverage|
|----|----|----|----|----|
|:large_blue_circle:|io/questdb/std/Qdb.java|4|5|80.00%|

**Comment by ideoma** [comment]
#### [PR Coverage check]

:heart_eyes: **pass** : 4 / 5 (80.00%)




#### file detail

|   |path|covered line|new line|coverage|
|----|----|----|----|----|
|:large_blue_circle:|io/questdb/std/Qdb.java|4|5|80.00%|

**Comment by ideoma** [comment]
#### [PR Coverage check]

:heart_eyes: **pass** : 4 / 5 (80.00%)




#### file detail

|   |path|covered line|new line|coverage|
|----|----|----|----|----|
|:large_blue_circle:|io/questdb/std/Qdb.java|4|5|80.00%|

**Comment by ideoma** [comment]
#### [PR Coverage check]

:heart_eyes: **pass** : 12 / 16 (75.00%)




#### file detail

|   |path|covered line|new line|coverage|
|----|----|----|----|----|
|:large_blue_circle:|io/questdb/std/Qdb.java|12|16|75.00%|

**Comment by ideoma** [comment]
#### [PR Coverage check]

:heart_eyes: **pass** : 12 / 16 (75.00%)




#### file detail

|   |path|covered line|new line|coverage|
|----|----|----|----|----|
|:large_blue_circle:|io/questdb/std/Qdb.java|12|16|75.00%|

**Comment by ideoma** [comment]
#### [PR Coverage check]

:heart_eyes: **pass** : 12 / 16 (75.00%)




#### file detail

|   |path|covered line|new line|coverage|
|----|----|----|----|----|
|:large_blue_circle:|io/questdb/std/Qdb.java|12|16|75.00%|

**Comment by ideoma** [comment]
#### [PR Coverage check]

:heart_eyes: **pass** : 13 / 17 (76.47%)




#### file detail

|   |path|covered line|new line|coverage|
|----|----|----|----|----|
|:large_blue_circle:|io/questdb/std/Qdb.java|13|17|76.47%|

**Comment by questdb-butler** [comment]
<table>
  <thead>
    <tr>
      <th width="50"></th>
      <th width="100%" data-danger-table="true">Fails</th>
    </tr>
  </thead>
  <tbody><tr>
      <td>:no_entry_sign:</td>
      <td>

  Please update the PR title to match this format:
`type(subType): description`

Where `type` is one of:
`feat`, `fix`, `chore`, `docs`, `style`, `refactor`, `perf`, `test`, `ci`, `revert`

And: `subType` is one of:
`build`, `sql`, `log`, `mig`, `core`, `ilp`, `pgwire`, `http`, `conf`, `ui`, `wal`

For Example:

```
perf(sql): improve pattern matching performance for SELECT sub-queries
```
  </td>
    </tr>
  </tbody>
</table>




<p align="right">
  Generated by :no_entry_sign: <a href="https://danger.systems/js">dangerJS</a> against 535941733b2a14176d6ed0d7bf449e7960376042
</p>

**Comment by ideoma** [comment]
#### [PR Coverage check]

:heart_eyes: **pass** : 29 / 40 (72.50%)




#### file detail

|   |path|covered line|new line|coverage|
|----|----|----|----|----|
|:large_blue_circle:|io/questdb/RustCodeFailScenario.java|0|9|00.00%|
|:large_blue_circle:|io/questdb/std/Qdb.java|5|6|83.33%|
|:large_blue_circle:|io/questdb/log/RustLogging.java|11|12|91.67%|
|:large_blue_circle:|io/questdb/Bootstrap.java|2|2|100.00%|
|:large_blue_circle:|io/questdb/log/RustLogAdaptor.java|11|11|100.00%|

**Comment by ideoma** [comment]
#### [PR Coverage check]

:heart_eyes: **pass** : 29 / 40 (72.50%)




#### file detail

|   |path|covered line|new line|coverage|
|----|----|----|----|----|
|:large_blue_circle:|io/questdb/RustCodeFailScenario.java|0|9|00.00%|
|:large_blue_circle:|io/questdb/std/Qdb.java|5|6|83.33%|
|:large_blue_circle:|io/questdb/log/RustLogging.java|11|12|91.67%|
|:large_blue_circle:|io/questdb/Bootstrap.java|2|2|100.00%|
|:large_blue_circle:|io/questdb/log/RustLogAdaptor.java|11|11|100.00%|

**Comment by ideoma** [comment]
#### [PR Coverage check]

:heart_eyes: **pass** : 29 / 40 (72.50%)




#### file detail

|   |path|covered line|new line|coverage|
|----|----|----|----|----|
|:large_blue_circle:|io/questdb/RustCodeFailScenario.java|0|9|00.00%|
|:large_blue_circle:|io/questdb/std/Qdb.java|5|6|83.33%|
|:large_blue_circle:|io/questdb/log/RustLogging.java|11|12|91.67%|
|:large_blue_circle:|io/questdb/Bootstrap.java|2|2|100.00%|
|:large_blue_circle:|io/questdb/log/RustLogAdaptor.java|11|11|100.00%|

**Pull request closed without merging**
