### PR TITLE
fix(core): fix segfault due to closed LogFactory instances on start-up

### PR DESCRIPTION
**Pull request by puzpuzpuz**
**Note**: this is a breaking change for embedded API users. Instead of
```java
LogFactory.configureFromSystemProperties(new LogFactory(), rootDirectory);
```
embedders who want to specify the root directory holding logging configuration now should make sure to call
```java
LogFactory.configureRootDir(rootDirectory);
```
before any `LogFactory.getLog()` call.

This patch fixes segfaults in the following scenario:
1. A `LogFactory.configureFromSystemProperties(new LogFactory(), rootDirectory)` call happens when the application starts.
2. The provided configuration includes `LogRollingFileWriter` which in its turn uses classes that include some logging (`TemplateParser` -> `TimestampFormatCompiler` -> `BytecodeAssembler`).
3. Those classes lead to `LogFactory.getLog()` calls being made while the original `LogFactory` is still being configured.
4. Since the singleton (`INSTANCE`) is `null`, those classes get a new copy of `LogFactory`.
5. This new `LogFactory` gets closed as a part of the initial `configureFromSystemProperties()` call thanks to `replacePrevInstance` being `true`.
6. Any logging attempt in the unlucky classes (`BytecodeAssembler`) leads to a segfault since the factory is already closed.

### CODE REVIEW

**Comment by ideoma** [comment]
#### [PR Coverage check]

:heart_eyes: **pass** : 42 / 50 (84.00%)




#### file detail

|   |path|covered line|new line|coverage|
|----|----|----|----|----|
|:large_blue_circle:|io/questdb/Bootstrap.java|0|1|00.00%|
|:large_blue_circle:|io/questdb/log/LogFactory.java|42|49|85.71%|

**Comment by ideoma** [comment]
#### [PR Coverage check]

:heart_eyes: **pass** : 42 / 50 (84.00%)




#### file detail

|   |path|covered line|new line|coverage|
|----|----|----|----|----|
|:large_blue_circle:|io/questdb/Bootstrap.java|0|1|00.00%|
|:large_blue_circle:|io/questdb/log/LogFactory.java|42|49|85.71%|

**Comment by ideoma** [comment]
#### [PR Coverage check]

:heart_eyes: **pass** : 108 / 143 (75.52%)




#### file detail

|   |path|covered line|new line|coverage|
|----|----|----|----|----|
|:large_blue_circle:|io/questdb/Bootstrap.java|0|1|00.00%|
|:large_blue_circle:|io/questdb/log/LogFactory.java|107|141|75.89%|
|:large_blue_circle:|io/questdb/log/Logger.java|1|1|100.00%|

**Comment by ideoma** [comment]
#### [PR Coverage check]

:heart_eyes: **pass** : 106 / 146 (72.60%)




#### file detail

|   |path|covered line|new line|coverage|
|----|----|----|----|----|
|:large_blue_circle:|io/questdb/Bootstrap.java|0|1|00.00%|
|:large_blue_circle:|io/questdb/log/SyncLogger.java|0|4|00.00%|
|:large_blue_circle:|io/questdb/log/LogFactory.java|105|140|75.00%|
|:large_blue_circle:|io/questdb/log/Logger.java|1|1|100.00%|

**Review by bluestreak01 — APPROVED** [review]

**Comment by ideoma** [comment]
#### [PR Coverage check]

:heart_eyes: **pass** : 106 / 146 (72.60%)




#### file detail

|   |path|covered line|new line|coverage|
|----|----|----|----|----|
|:large_blue_circle:|io/questdb/Bootstrap.java|0|1|00.00%|
|:large_blue_circle:|io/questdb/log/SyncLogger.java|0|4|00.00%|
|:large_blue_circle:|io/questdb/log/LogFactory.java|105|140|75.00%|
|:large_blue_circle:|io/questdb/log/Logger.java|1|1|100.00%|

**Pull request merged**
