### PR TITLE
fix(pgwire): fix cursor fetch for asyncpg

### LINKED ISSUE #1897: Empty query result in case of pg-cursor + pg-query-stream Node.js packages
### Describe the bug

QuestDB doesn't seem to work correctly with `pg` + `pg-cursor` + `pg-query-stream` npm packages. These packages allow to use PG Wire cursors to fetch the query result in batches without loading it to memory in one go.

### To reproduce

```js
"use strict"

const { Client, types } = require("pg")
const QueryStream = require('pg-query-stream')
const JSONStream = require('JSONStream')

const start = async () => {
  const client = new Client({
    database: "qdb",
    host: "127.0.0.1",
    password: "quest",
    port: 8812,
    user: "admin",
  })
  await client.connect()

  const res = await client.query('SELECT * FROM long_sequence(5)')
  console.log(res.rows)

  const query = new QueryStream('SELECT * FROM long_sequence(5)', [1000],
    {
      types: {
        getTypeParser: (dataTypeID, format) => {
          return types.getTypeParser(dataTypeID, format)
        },
      }
    }
  )
  const stream = client.query(query)
  stream.pipe(JSONStream.stringify()).pipe(process.stdout)

  // release the client when the stream is finished
  const streamEndPromise = deferredPromise()
  stream.on('end', streamEndPromise.resolve)
  stream.on('error', streamEndPromise.reject)

  await streamEndPromise
  client.end()
}

function deferredPromise() {
  let resolve, reject
  const p = new Promise((_resolve, _reject) => {
    resolve = _resolve
    reject = _reject
  })
  p.resolve = resolve
  p.reject = reject
  return p
}

start()
  .then(() => console.log('Done'))
  .catch(console.error)
```

Prints the following:
```
[ { x: '1' }, { x: '2' }, { x: '3' }, { x: '4' }, { x: '5' } ]
[

]
Done
```

### Expected Behavior

Both arrays should contain the same 5 rows.

### Environment

```markdown
- **QuestDB version**: latest 6.2.1 snapshot
- **OS**: Ubuntu 20.04, Node.js v16.13.1
- **Browser**:
```

### Additional context

_No response_

### PR DESCRIPTION
**Pull request by bziobrowski**
Fixes #1897

Fixes cursor fetches from asyncpg code with: 
-  bind variables -   asyncpg doesn't seem to specify type of bind variables in Bind message but uses those sent back by server in  ParameterDescription
- Flush commands in between - Flush command shouldn't clear current state on server side but trigger processing pending messaged and pushing buffer content to client .

### CODE REVIEW

**Comment by questdb-butler** [comment]
<table>
  <thead>
    <tr>
      <th width="50"></th>
      <th width="100%" data-danger-table="true">Fails</th>
    </tr>
  </thead>
  <tbody><tr>
      <td>:no_entry_sign:</td>
      <td>

  Please update the PR title to match this format:
`type(subType): description`

Where `type` is one of:
`feat`, `fix`, `chore`, `docs`, `style`, `refactor`, `perf`, `test`, `ci`, `chore`, `revert`

And: `subType` is one of:
`build`, `sql`, `log`, `mig`, `core`, `ilp`, `pgwire`, `http`, `conf`, `ui`, `wal`

For Example:

```
perf(sql): improve pattern matching performance for SELECT sub-queries
```
  </td>
    </tr>
  </tbody>
</table>




<p align="right">
  Generated by :no_entry_sign: <a href="https://danger.systems/js">dangerJS</a> against 2b18af87cae277455536d2317befd74ff9be3e32
</p>

**Comment by ideoma** [comment]
#### [PR Coverage check]

:heart_eyes: **pass** : 3 / 3 (100.00%)




#### file detail

|   |path|covered line|new line|coverage|
|----|----|----|----|----|
|:large_blue_circle:|io/questdb/cutlass/pgwire/PGConnectionContext.java|3|3|100.00%|

**Comment by ideoma** [comment]
#### [PR Coverage check]

:heart_eyes: **pass** : 3 / 3 (100.00%)




#### file detail

|   |path|covered line|new line|coverage|
|----|----|----|----|----|
|:large_blue_circle:|io/questdb/cutlass/pgwire/PGConnectionContext.java|3|3|100.00%|

**Review by bluestreak01 — APPROVED** [review]

**Comment by ideoma** [comment]
#### [PR Coverage check]

:heart_eyes: **pass** : 3 / 3 (100.00%)




#### file detail

|   |path|covered line|new line|coverage|
|----|----|----|----|----|
|:large_blue_circle:|io/questdb/cutlass/pgwire/PGConnectionContext.java|3|3|100.00%|

**Pull request merged**
