### PR TITLE
chore(core): fix Utf8s.strCpy() when used with DirectUtf8Sink

### PR DESCRIPTION
**Pull request by glasstiger**
Reviewed usages of `Utf8Sink.put(byte)` and `Utf8Sink.putAny(byte)`, fixed usages at few places.

Also changed `Utf8StringSink.put(byte)` behaviour to be the same as `DirectUtf8Sink.put(byte)`.
Now `Utf8StringSink.put(byte)` also asserts if the byte to be inserted is non-ASCII.

### CODE REVIEW

**Comment by ideoma** [comment]
#### [PR Coverage check]

:heart_eyes: **pass** : 2 / 2 (100.00%)




#### file detail

|   |path|covered line|new line|coverage|
|----|----|----|----|----|
|:large_blue_circle:|io/questdb/std/str/Utf8s.java|2|2|100.00%|

**Comment by ideoma** [comment]
#### [PR Coverage check]

:heart_eyes: **pass** : 2 / 2 (100.00%)




#### file detail

|   |path|covered line|new line|coverage|
|----|----|----|----|----|
|:large_blue_circle:|io/questdb/std/str/Utf8s.java|2|2|100.00%|

**Comment by ideoma** [comment]
#### [PR Coverage check]

:disappointed: **fail** : 3 / 8 (37.50%)




#### file detail

|   |path|covered line|new line|coverage|
|----|----|----|----|----|
|:large_blue_circle:|io/questdb/std/str/Utf8Sink.java|0|4|00.00%|
|:large_blue_circle:|io/questdb/std/str/Utf8s.java|2|3|66.67%|
|:large_blue_circle:|io/questdb/std/str/Utf8StringSink.java|1|1|100.00%|

**Comment by ideoma** [comment]
#### [PR Coverage check]

:heart_eyes: **pass** : 7 / 8 (87.50%)




#### file detail

|   |path|covered line|new line|coverage|
|----|----|----|----|----|
|:large_blue_circle:|io/questdb/std/str/Utf8s.java|2|3|66.67%|
|:large_blue_circle:|io/questdb/std/str/Utf8StringSink.java|1|1|100.00%|
|:large_blue_circle:|io/questdb/std/str/Utf8Sink.java|4|4|100.00%|

**Review by mtopolnik — APPROVED** [review]

**Comment by bluestreak01** [comment]
there was OOM in windows CI, waiting for @glasstiger to review

**Comment by glasstiger** [comment]
> there was OOM in windows CI, waiting for @glasstiger to review

Now the OOM happened twice.
Both on the same build, and both in `WalWriterFuzzTest`: `windows-griffin-O3-Fuzz`.
The first one happened during query execution in `WalWriterFuzzTest.testSimpleDataTransaction()`.
The second happened during an O3 commit in `WalWriterFuzzTest.testWalWriteFullRandom()`.

Tried to reproduce the issue by taking the random seeds from the tests, and running them locally.
No luck.
However, I work on Mac, and not on Windows.

Similar issues had been reported earlier, but not exactly the same.
https://github.com/questdb/questdb/issues/3171

Logs related to the 2 OOM:
[227.txt](https://github.com/questdb/questdb/files/15200626/227.txt)
[229.txt](https://github.com/questdb/questdb/files/15200628/229.txt)

It is unlikely that the issue is related to the changes in the PR, but cannot be 100% sure.
We need to try to reproduce it on Windows.

**Comment by ideoma** [comment]
#### [PR Coverage check]

:heart_eyes: **pass** : 7 / 8 (87.50%)




#### file detail

|   |path|covered line|new line|coverage|
|----|----|----|----|----|
|:large_blue_circle:|io/questdb/std/str/Utf8s.java|2|3|66.67%|
|:large_blue_circle:|io/questdb/std/str/Utf8StringSink.java|1|1|100.00%|
|:large_blue_circle:|io/questdb/std/str/Utf8Sink.java|4|4|100.00%|

**Pull request merged**
