### PR TITLE
perf(sql): execute complex sum aggregates on short column in parallel

### PR DESCRIPTION
**Pull request by puzpuzpuz**
This change is required to make sure that query 29 from ClickBench is executed by `GroupByNotKeyedVectorRecordCursorFactory`:
```sql
SELECT SUM(ResolutionWidth), SUM(ResolutionWidth + 1), SUM(ResolutionWidth + 2), SUM(ResolutionWidth + 3),
       SUM(ResolutionWidth + 5), ..., SUM(ResolutionWidth + 88), SUM(ResolutionWidth + 89) 
FROM hits;
```

Here, the `ResolutionWidth` column is of SHORT type. Internally the query was re-written with the following sub-query:
```sql
SELECT SUM(ResolutionWidth), COUNT(ResolutionWidth) FROM hits;
```

Note the `COUNT(ResolutionWidth)` function. SHORT is a non-nullable type and we don't have `CountShortVectorAggregateFunction`, so the multi-threaded factory wasn't used. With this patch, we use `COUNT()` in the translated query, so that the execution is multi-threaded.

### CODE REVIEW

**Comment by ideoma** [comment]
#### [PR Coverage check]

:heart_eyes: **pass** : 66 / 66 (100.00%)




#### file detail

|   |path|covered line|new line|coverage|
|----|----|----|----|----|
|:large_blue_circle:|io/questdb/griffin/engine/functions/groupby/AbstractCovarGroupByFunction.java|14|14|100.00%|
|:large_blue_circle:|io/questdb/griffin/engine/functions/groupby/CorrGroupByFunction.java|21|21|100.00%|
|:large_blue_circle:|io/questdb/griffin/SqlOptimiser.java|21|21|100.00%|
|:large_blue_circle:|io/questdb/griffin/engine/functions/groupby/AbstractStdDevGroupByFunction.java|10|10|100.00%|

**Comment by bziobrowski** [comment]
I think it'd be good to assert the query plan in a test like it's done e.g.  in ExplainPlanTest.testRewriteAggregateWithAddition().

**Review by bziobrowski — DISMISSED** [review]

**Comment by puzpuzpuz** [comment]
> I think it'd be good to assert the query plan in a test like it's done e.g. in ExplainPlanTest.testRewriteAggregateWithAddition().

Good idea. Added more tests to `ExplainPlanTest` in 5ac2a158d17764a117505bdbca2dfd08838505ef

**Review by bziobrowski — APPROVED** [review]
:+1:

**Comment by ideoma** [comment]
#### [PR Coverage check]

:heart_eyes: **pass** : 66 / 66 (100.00%)




#### file detail

|   |path|covered line|new line|coverage|
|----|----|----|----|----|
|:large_blue_circle:|io/questdb/griffin/engine/functions/groupby/AbstractCovarGroupByFunction.java|14|14|100.00%|
|:large_blue_circle:|io/questdb/griffin/engine/functions/groupby/CorrGroupByFunction.java|21|21|100.00%|
|:large_blue_circle:|io/questdb/griffin/SqlOptimiser.java|21|21|100.00%|
|:large_blue_circle:|io/questdb/griffin/engine/functions/groupby/AbstractStdDevGroupByFunction.java|10|10|100.00%|

**Pull request merged**
