### PR TITLE
feat(cairo): wait for writer if it's about to be released by maintanance from the pool

### PR DESCRIPTION
**Pull request by ideoma**
Few issues with Engine maintanance and Writer pool fixed:

- When CairoEngine examines WriterPool periodically to evict and close old unused entries it blocks writer for a period of time needed to close the instance. If an Insert statement is processed at the same time it will get writer busy error with empty reason. To prevent it WriterPool will lock the entries about to be evicted with negative thread id and if such a lock found in get method another attempt to re-acquire the writer will be performed.
- When Writer Pool is examined by CairoEngine it will unconditionally unlock all locked table entries. If a table is being created at the time where maintanance the creation fails
Make busy writer Alter table test more stable in PgWire and Http Json integration tests.

### CODE REVIEW

**Comment by ideoma** [comment]
#### [PR Coverage check]

:heart_eyes: **pass** : 50 / 54 (92.59%)




#### file detail

|   |path|covered line|new line|coverage|
|----|----|----|----|----|
|:large_blue_circle:|io/questdb/cairo/pool/WriterPool.java|23|27|85.19%|
|:large_blue_circle:|io/questdb/cutlass/pgwire/PGWireServer.java|5|5|100.00%|
|:large_blue_circle:|io/questdb/cairo/TableWriter.java|1|1|100.00%|
|:large_blue_circle:|io/questdb/griffin/QueryFutureUpdateListener.java|1|1|100.00%|
|:large_blue_circle:|io/questdb/griffin/SqlExecutionContextImpl.java|1|1|100.00%|
|:large_blue_circle:|io/questdb/cutlass/pgwire/PGConnectionContext.java|2|2|100.00%|
|:large_blue_circle:|io/questdb/log/LogAlertSocket.java|13|13|100.00%|
|:large_blue_circle:|io/questdb/cutlass/http/processors/JsonQueryProcessor.java|3|3|100.00%|
|:large_blue_circle:|io/questdb/griffin/CompiledQueryImpl.java|1|1|100.00%|

**Comment by ideoma** [comment]
#### [PR Coverage check]

:heart_eyes: **pass** : 49 / 54 (90.74%)




#### file detail

|   |path|covered line|new line|coverage|
|----|----|----|----|----|
|:large_blue_circle:|io/questdb/cairo/pool/WriterPool.java|22|27|81.48%|
|:large_blue_circle:|io/questdb/cutlass/pgwire/PGWireServer.java|5|5|100.00%|
|:large_blue_circle:|io/questdb/cairo/TableWriter.java|1|1|100.00%|
|:large_blue_circle:|io/questdb/griffin/QueryFutureUpdateListener.java|1|1|100.00%|
|:large_blue_circle:|io/questdb/griffin/SqlExecutionContextImpl.java|1|1|100.00%|
|:large_blue_circle:|io/questdb/cutlass/pgwire/PGConnectionContext.java|2|2|100.00%|
|:large_blue_circle:|io/questdb/log/LogAlertSocket.java|13|13|100.00%|
|:large_blue_circle:|io/questdb/cutlass/http/processors/JsonQueryProcessor.java|3|3|100.00%|
|:large_blue_circle:|io/questdb/griffin/CompiledQueryImpl.java|1|1|100.00%|

**Comment by ideoma** [comment]
#### [PR Coverage check]

:heart_eyes: **pass** : 50 / 54 (92.59%)




#### file detail

|   |path|covered line|new line|coverage|
|----|----|----|----|----|
|:large_blue_circle:|io/questdb/cairo/pool/WriterPool.java|23|27|85.19%|
|:large_blue_circle:|io/questdb/cutlass/pgwire/PGWireServer.java|5|5|100.00%|
|:large_blue_circle:|io/questdb/cairo/TableWriter.java|1|1|100.00%|
|:large_blue_circle:|io/questdb/griffin/QueryFutureUpdateListener.java|1|1|100.00%|
|:large_blue_circle:|io/questdb/griffin/SqlExecutionContextImpl.java|1|1|100.00%|
|:large_blue_circle:|io/questdb/cutlass/pgwire/PGConnectionContext.java|2|2|100.00%|
|:large_blue_circle:|io/questdb/log/LogAlertSocket.java|13|13|100.00%|
|:large_blue_circle:|io/questdb/cutlass/http/processors/JsonQueryProcessor.java|3|3|100.00%|
|:large_blue_circle:|io/questdb/griffin/CompiledQueryImpl.java|1|1|100.00%|

**Comment by ideoma** [comment]
#### [PR Coverage check]

:heart_eyes: **pass** : 50 / 54 (92.59%)




#### file detail

|   |path|covered line|new line|coverage|
|----|----|----|----|----|
|:large_blue_circle:|io/questdb/cairo/pool/WriterPool.java|23|27|85.19%|
|:large_blue_circle:|io/questdb/cutlass/pgwire/PGWireServer.java|5|5|100.00%|
|:large_blue_circle:|io/questdb/cairo/TableWriter.java|1|1|100.00%|
|:large_blue_circle:|io/questdb/griffin/QueryFutureUpdateListener.java|1|1|100.00%|
|:large_blue_circle:|io/questdb/griffin/SqlExecutionContextImpl.java|1|1|100.00%|
|:large_blue_circle:|io/questdb/cutlass/pgwire/PGConnectionContext.java|2|2|100.00%|
|:large_blue_circle:|io/questdb/log/LogAlertSocket.java|13|13|100.00%|
|:large_blue_circle:|io/questdb/cutlass/http/processors/JsonQueryProcessor.java|3|3|100.00%|
|:large_blue_circle:|io/questdb/griffin/CompiledQueryImpl.java|1|1|100.00%|

**Comment by ideoma** [comment]
#### [PR Coverage check]

:heart_eyes: **pass** : 49 / 54 (90.74%)




#### file detail

|   |path|covered line|new line|coverage|
|----|----|----|----|----|
|:large_blue_circle:|io/questdb/cairo/pool/WriterPool.java|22|27|81.48%|
|:large_blue_circle:|io/questdb/cutlass/pgwire/PGWireServer.java|5|5|100.00%|
|:large_blue_circle:|io/questdb/cairo/TableWriter.java|1|1|100.00%|
|:large_blue_circle:|io/questdb/griffin/QueryFutureUpdateListener.java|1|1|100.00%|
|:large_blue_circle:|io/questdb/griffin/SqlExecutionContextImpl.java|1|1|100.00%|
|:large_blue_circle:|io/questdb/cutlass/pgwire/PGConnectionContext.java|2|2|100.00%|
|:large_blue_circle:|io/questdb/log/LogAlertSocket.java|13|13|100.00%|
|:large_blue_circle:|io/questdb/cutlass/http/processors/JsonQueryProcessor.java|3|3|100.00%|
|:large_blue_circle:|io/questdb/griffin/CompiledQueryImpl.java|1|1|100.00%|

**Comment by ideoma** [comment]
#### [PR Coverage check]

:heart_eyes: **pass** : 72 / 79 (91.14%)




#### file detail

|   |path|covered line|new line|coverage|
|----|----|----|----|----|
|:large_blue_circle:|io/questdb/cairo/pool/WriterPool.java|42|49|85.71%|
|:large_blue_circle:|io/questdb/cutlass/pgwire/PGWireServer.java|5|5|100.00%|
|:large_blue_circle:|io/questdb/cairo/TableWriter.java|1|1|100.00%|
|:large_blue_circle:|io/questdb/griffin/QueryFutureUpdateListener.java|1|1|100.00%|
|:large_blue_circle:|io/questdb/griffin/SqlExecutionContextImpl.java|1|1|100.00%|
|:large_blue_circle:|io/questdb/cutlass/pgwire/PGConnectionContext.java|2|2|100.00%|
|:large_blue_circle:|io/questdb/log/LogAlertSocket.java|13|13|100.00%|
|:large_blue_circle:|io/questdb/cutlass/http/processors/JsonQueryProcessor.java|3|3|100.00%|
|:large_blue_circle:|io/questdb/griffin/CompiledQueryImpl.java|4|4|100.00%|

**Comment by ideoma** [comment]
#### [PR Coverage check]

:heart_eyes: **pass** : 72 / 80 (90.00%)




#### file detail

|   |path|covered line|new line|coverage|
|----|----|----|----|----|
|:large_blue_circle:|io/questdb/cairo/pool/WriterPool.java|41|49|83.67%|
|:large_blue_circle:|io/questdb/cutlass/pgwire/PGWireServer.java|5|5|100.00%|
|:large_blue_circle:|io/questdb/cairo/TableWriter.java|1|1|100.00%|
|:large_blue_circle:|io/questdb/griffin/QueryFutureUpdateListener.java|1|1|100.00%|
|:large_blue_circle:|io/questdb/griffin/SqlExecutionContextImpl.java|1|1|100.00%|
|:large_blue_circle:|io/questdb/cutlass/pgwire/PGConnectionContext.java|2|2|100.00%|
|:large_blue_circle:|io/questdb/log/LogAlertSocket.java|13|13|100.00%|
|:large_blue_circle:|io/questdb/griffin/SqlCompiler.java|1|1|100.00%|
|:large_blue_circle:|io/questdb/cutlass/http/processors/JsonQueryProcessor.java|3|3|100.00%|
|:large_blue_circle:|io/questdb/griffin/CompiledQueryImpl.java|4|4|100.00%|

**Comment by ideoma** [comment]
#### [PR Coverage check]

:heart_eyes: **pass** : 72 / 80 (90.00%)




#### file detail

|   |path|covered line|new line|coverage|
|----|----|----|----|----|
|:large_blue_circle:|io/questdb/cairo/pool/WriterPool.java|41|49|83.67%|
|:large_blue_circle:|io/questdb/cutlass/pgwire/PGWireServer.java|5|5|100.00%|
|:large_blue_circle:|io/questdb/cairo/TableWriter.java|1|1|100.00%|
|:large_blue_circle:|io/questdb/griffin/QueryFutureUpdateListener.java|1|1|100.00%|
|:large_blue_circle:|io/questdb/griffin/SqlExecutionContextImpl.java|1|1|100.00%|
|:large_blue_circle:|io/questdb/cutlass/pgwire/PGConnectionContext.java|2|2|100.00%|
|:large_blue_circle:|io/questdb/log/LogAlertSocket.java|13|13|100.00%|
|:large_blue_circle:|io/questdb/griffin/SqlCompiler.java|1|1|100.00%|
|:large_blue_circle:|io/questdb/cutlass/http/processors/JsonQueryProcessor.java|3|3|100.00%|
|:large_blue_circle:|io/questdb/griffin/CompiledQueryImpl.java|4|4|100.00%|

**Comment by ideoma** [comment]
#### [PR Coverage check]

:heart_eyes: **pass** : 73 / 80 (91.25%)




#### file detail

|   |path|covered line|new line|coverage|
|----|----|----|----|----|
|:large_blue_circle:|io/questdb/cairo/pool/WriterPool.java|42|49|85.71%|
|:large_blue_circle:|io/questdb/cutlass/pgwire/PGWireServer.java|5|5|100.00%|
|:large_blue_circle:|io/questdb/cairo/TableWriter.java|1|1|100.00%|
|:large_blue_circle:|io/questdb/griffin/QueryFutureUpdateListener.java|1|1|100.00%|
|:large_blue_circle:|io/questdb/griffin/SqlExecutionContextImpl.java|1|1|100.00%|
|:large_blue_circle:|io/questdb/cutlass/pgwire/PGConnectionContext.java|2|2|100.00%|
|:large_blue_circle:|io/questdb/log/LogAlertSocket.java|13|13|100.00%|
|:large_blue_circle:|io/questdb/griffin/SqlCompiler.java|1|1|100.00%|
|:large_blue_circle:|io/questdb/cutlass/http/processors/JsonQueryProcessor.java|3|3|100.00%|
|:large_blue_circle:|io/questdb/griffin/CompiledQueryImpl.java|4|4|100.00%|

**Comment by ideoma** [comment]
#### [PR Coverage check]

:heart_eyes: **pass** : 72 / 80 (90.00%)




#### file detail

|   |path|covered line|new line|coverage|
|----|----|----|----|----|
|:large_blue_circle:|io/questdb/cairo/pool/WriterPool.java|41|49|83.67%|
|:large_blue_circle:|io/questdb/cutlass/pgwire/PGWireServer.java|5|5|100.00%|
|:large_blue_circle:|io/questdb/cairo/TableWriter.java|1|1|100.00%|
|:large_blue_circle:|io/questdb/griffin/QueryFutureUpdateListener.java|1|1|100.00%|
|:large_blue_circle:|io/questdb/griffin/SqlExecutionContextImpl.java|1|1|100.00%|
|:large_blue_circle:|io/questdb/cutlass/pgwire/PGConnectionContext.java|2|2|100.00%|
|:large_blue_circle:|io/questdb/log/LogAlertSocket.java|13|13|100.00%|
|:large_blue_circle:|io/questdb/griffin/SqlCompiler.java|1|1|100.00%|
|:large_blue_circle:|io/questdb/cutlass/http/processors/JsonQueryProcessor.java|3|3|100.00%|
|:large_blue_circle:|io/questdb/griffin/CompiledQueryImpl.java|4|4|100.00%|

**Comment by ideoma** [comment]
#### [PR Coverage check]

:heart_eyes: **pass** : 73 / 80 (91.25%)




#### file detail

|   |path|covered line|new line|coverage|
|----|----|----|----|----|
|:large_blue_circle:|io/questdb/cairo/pool/WriterPool.java|42|49|85.71%|
|:large_blue_circle:|io/questdb/cutlass/pgwire/PGWireServer.java|5|5|100.00%|
|:large_blue_circle:|io/questdb/cairo/TableWriter.java|1|1|100.00%|
|:large_blue_circle:|io/questdb/griffin/QueryFutureUpdateListener.java|1|1|100.00%|
|:large_blue_circle:|io/questdb/griffin/SqlExecutionContextImpl.java|1|1|100.00%|
|:large_blue_circle:|io/questdb/cutlass/pgwire/PGConnectionContext.java|2|2|100.00%|
|:large_blue_circle:|io/questdb/log/LogAlertSocket.java|13|13|100.00%|
|:large_blue_circle:|io/questdb/griffin/SqlCompiler.java|1|1|100.00%|
|:large_blue_circle:|io/questdb/cutlass/http/processors/JsonQueryProcessor.java|3|3|100.00%|
|:large_blue_circle:|io/questdb/griffin/CompiledQueryImpl.java|4|4|100.00%|

**Comment by ideoma** [comment]
#### [PR Coverage check]

:heart_eyes: **pass** : 70 / 80 (87.50%)




#### file detail

|   |path|covered line|new line|coverage|
|----|----|----|----|----|
|:large_blue_circle:|io/questdb/cairo/pool/WriterPool.java|39|49|79.59%|
|:large_blue_circle:|io/questdb/cutlass/pgwire/PGWireServer.java|5|5|100.00%|
|:large_blue_circle:|io/questdb/cairo/TableWriter.java|1|1|100.00%|
|:large_blue_circle:|io/questdb/griffin/QueryFutureUpdateListener.java|1|1|100.00%|
|:large_blue_circle:|io/questdb/griffin/SqlExecutionContextImpl.java|1|1|100.00%|
|:large_blue_circle:|io/questdb/cutlass/pgwire/PGConnectionContext.java|2|2|100.00%|
|:large_blue_circle:|io/questdb/log/LogAlertSocket.java|13|13|100.00%|
|:large_blue_circle:|io/questdb/griffin/SqlCompiler.java|1|1|100.00%|
|:large_blue_circle:|io/questdb/cutlass/http/processors/JsonQueryProcessor.java|3|3|100.00%|
|:large_blue_circle:|io/questdb/griffin/CompiledQueryImpl.java|4|4|100.00%|

**Review by bluestreak01 — APPROVED** [review]

**Pull request merged**
