### PR TITLE
fix(sql): improve error reporting on non-boolean join conditions

### LINKED ISSUE #3386: Unexpected UnsupportedOperationException with `join` query on non-boolean expression
### Describe the bug

```
QuestDB Exception:
	consuming input failed: server closed the connection unexpectedly
	This probably means the server terminated abnormally
	before or while processing the request.
```
Exception logs:
```
2023-05-23T09:58:10.731824Z C i.q.c.p.PGWireServer internal error [ex=
java.lang.UnsupportedOperationException
	at io.questdb.griffin.engine.functions.LongFunction.getBool(LongFunction.java:50)
	at io.questdb.griffin.engine.table.FilteredRecordCursor.hasNext(FilteredRecordCursor.java:67)
	at io.questdb.griffin.engine.groupby.CountRecordCursorFactory$CountRecordCursor.hasNext(CountRecordCursorFactory.java:100)
	at io.questdb.cutlass.pgwire.PGConnectionContext.sendCursor0(PGConnectionContext.java:2635)
	at io.questdb.cutlass.pgwire.PGConnectionContext.sendCursor(PGConnectionContext.java:2622)
	at io.questdb.cutlass.pgwire.PGConnectionContext$PGConnectionBatchCallback.postCompile(PGConnectionContext.java:2913)
	at io.questdb.griffin.SqlCompiler.compileBatch(SqlCompiler.java:265)
	at io.questdb.cutlass.pgwire.PGConnectionContext.processQuery(PGConnectionContext.java:2414)
	at io.questdb.cutlass.pgwire.PGConnectionContext.parse(PGConnectionContext.java:1691)
	at io.questdb.cutlass.pgwire.PGConnectionContext.handleClientOperation(PGConnectionContext.java:421)
	at io.questdb.cutlass.pgwire.PGJobContext.handleClientOperation(PGJobContext.java:89)
	at io.questdb.cutlass.pgwire.PGWireServer$1.lambda$$0(PGWireServer.java:91)
	at io.questdb.network.AbstractIODispatcher.processIOQueue(AbstractIODispatcher.java:189)
	at io.questdb.cutlass.pgwire.PGWireServer$1.run(PGWireServer.java:128)
	at io.questdb.mp.Worker.run(Worker.java:118)
]
```

### To reproduce

```
select count(*) from telemetry as a join telemetry as b on a.created-b.created
```

### Expected Behavior

It should alert:
```
QuestDB Exception:
	boolean expression expected
```

### Environment

```markdown
- **QuestDB version**: 7.1.3
- **OS**: ubuntu 20.04
```

### Additional context

_No response_

### PR DESCRIPTION
**Pull request by bziobrowski**
Fixes #3386

PR makes compiler reject non-boolean join filters, e.g. 

```sql
create table a ( ts timestamp, i int) timestamp(ts);
create table b ( ts timestamp, i int) timestamp(ts);

select * from a left join b on a.i - b.i;
select * from a join b on a.ts = b.ts and a.i - b.i;
```

Queries above now return `boolean expression expected` during compilation instead of `UnsupportedOperationException` during query execution.

### CODE REVIEW

**Comment by ideoma** [comment]
#### [PR Coverage check]

:heart_eyes: **pass** : 7 / 9 (77.78%)




#### file detail

|   |path|covered line|new line|coverage|
|----|----|----|----|----|
|:large_blue_circle:|io/questdb/griffin/SqlCodeGenerator.java|7|9|77.78%|

**Review by jerrinot — APPROVED** [review]
the impl looks good. 

I was trying to figure out how to improve the title. "non-boolean" and "filters" so close to each other make me slightly uncomfortable:) but I could not come up with anything sufficiently succinct and descriptive.

**Comment by bziobrowski** [comment]
How about the current one ?

**Comment by ideoma** [comment]
#### [PR Coverage check]

:heart_eyes: **pass** : 7 / 9 (77.78%)




#### file detail

|   |path|covered line|new line|coverage|
|----|----|----|----|----|
|:large_blue_circle:|io/questdb/griffin/SqlCodeGenerator.java|7|9|77.78%|

**Comment by ideoma** [comment]
#### [PR Coverage check]

:heart_eyes: **pass** : 7 / 9 (77.78%)




#### file detail

|   |path|covered line|new line|coverage|
|----|----|----|----|----|
|:large_blue_circle:|io/questdb/griffin/SqlCodeGenerator.java|7|9|77.78%|

**Comment by ideoma** [comment]
#### [PR Coverage check]

:heart_eyes: **pass** : 7 / 9 (77.78%)




#### file detail

|   |path|covered line|new line|coverage|
|----|----|----|----|----|
|:large_blue_circle:|io/questdb/griffin/SqlCodeGenerator.java|7|9|77.78%|

**Comment by ideoma** [comment]
#### [PR Coverage check]

:heart_eyes: **pass** : 7 / 9 (77.78%)




#### file detail

|   |path|covered line|new line|coverage|
|----|----|----|----|----|
|:large_blue_circle:|io/questdb/griffin/SqlCodeGenerator.java|7|9|77.78%|

**Comment by ideoma** [comment]
#### [PR Coverage check]

:heart_eyes: **pass** : 7 / 9 (77.78%)




#### file detail

|   |path|covered line|new line|coverage|
|----|----|----|----|----|
|:large_blue_circle:|io/questdb/griffin/SqlCodeGenerator.java|7|9|77.78%|

**Pull request merged**
