### PR TITLE
perf(sql): unrolled group by functions in GroupByFunctionsUpdater

### PR DESCRIPTION
**Pull request by jerrinot**
ObjList with group by functions is unrolled into fields. So the tight aggregation loop does not have to get individual functions from the ObjList. This yields small, but consistent performance improvement. Test code:
```java
    @Test
    public void testFoo() throws Exception {
        runQueries(
                "create table sorttest(l long);",
                "insert into sorttest select rnd_int(1, 1000, 0) from long_sequence( 200 * 1000 * 1000 );");

        StringSink sink = new StringSink();
        long totalStart = System.currentTimeMillis();
        for (int i = 0; i < 15; i++) {
            sink.clear();
            long t = System.currentTimeMillis();
            try (RecordCursorFactory rcf = compiler.compile("select l, count(*) as c from sorttest order by c desc limit 5", sqlExecutionContext).getRecordCursorFactory()) {
                RecordMetadata metadata = rcf.getMetadata();
                try (RecordCursor cursor = rcf.getCursor(sqlExecutionContext)) {
                    TestUtils.assertCursor("493\t201383\n" +
                            "746\t201381\n" +
                            "990\t201247\n" +
                            "109\t201192\n" +
                            "613\t201160\n", cursor, metadata, false, sink);
                }
            }
            System.out.println("Query took " + (System.currentTimeMillis() - t) + "ms");
        }
        System.out.println("Total time " + (System.currentTimeMillis() - totalStart) + "ms");
    }
 ```
 Before this changeset each query takes about 5300ms (M1 Macbook).
 After this change it's around 5150ms.

### CODE REVIEW

**Comment by questdb-butler** [comment]
<table>
  <thead>
    <tr>
      <th width="50"></th>
      <th width="100%" data-danger-table="true">Fails</th>
    </tr>
  </thead>
  <tbody><tr>
      <td>:no_entry_sign:</td>
      <td>

  Please update the PR title to match this format:
`type(subType): description`

Where `type` is one of:
`feat`, `fix`, `chore`, `docs`, `style`, `refactor`, `perf`, `test`, `ci`, `chore`, `revert`

And: `subType` is one of:
`build`, `sql`, `log`, `mig`, `core`, `ilp`, `pgwire`, `http`, `conf`, `ui`, `wal`

For Example:

```
perf(sql): improve pattern matching performance for SELECT sub-queries
```
  </td>
    </tr>
  </tbody>
</table>




<p align="right">
  Generated by :no_entry_sign: <a href="https://danger.systems/js">dangerJS</a> against e0d1a0310e076ac991dcd61560544f82d247c489
</p>

**Comment by questdb-butler** [comment]
<table>
  <thead>
    <tr>
      <th width="50"></th>
      <th width="100%" data-danger-table="true">Fails</th>
    </tr>
  </thead>
  <tbody><tr>
      <td>:no_entry_sign:</td>
      <td>

  Please update the PR title to match this format:
`type(subType): description`

Where `type` is one of:
`feat`, `fix`, `chore`, `docs`, `style`, `refactor`, `perf`, `test`, `ci`, `chore`, `revert`

And: `subType` is one of:
`build`, `sql`, `log`, `mig`, `core`, `ilp`, `pgwire`, `http`, `conf`, `ui`, `wal`

For Example:

```
perf(sql): improve pattern matching performance for SELECT sub-queries
```
  </td>
    </tr>
  </tbody>
</table>




<p align="right">
  Generated by :no_entry_sign: <a href="https://danger.systems/js">dangerJS</a> against e0d1a0310e076ac991dcd61560544f82d247c489
</p>

**Comment by ideoma** [comment]
#### [PR Coverage check]

:heart_eyes: **pass** : 47 / 47 (100.00%)




#### file detail

|   |path|covered line|new line|coverage|
|----|----|----|----|----|
|:large_blue_circle:|io/questdb/griffin/engine/groupby/GroupByFunctionsUpdaterFactory.java|47|47|100.00%|

**Review by puzpuzpuz — APPROVED** [review]

**Comment by ideoma** [comment]
#### [PR Coverage check]

:heart_eyes: **pass** : 47 / 47 (100.00%)




#### file detail

|   |path|covered line|new line|coverage|
|----|----|----|----|----|
|:large_blue_circle:|io/questdb/griffin/engine/groupby/GroupByFunctionsUpdaterFactory.java|47|47|100.00%|

**Pull request merged**
