### PR TITLE
test(build): introduce maven submodule for compatibility tests

### PR DESCRIPTION
**Pull request by puzpuzpuz**
Moves all tests that use InfluxDB client, OkHttp client to separate compatibility Maven submodule. The submodule also includes compatibility tests for QDB's HttpClient based on Jetty server.

Also renames `Ilp*` classes to `Line*` to consistency with the rest of code base.

### CODE REVIEW

**Comment by questdb-butler** [comment]
<table>
  <thead>
    <tr>
      <th width="50"></th>
      <th width="100%" data-danger-table="true">Fails</th>
    </tr>
  </thead>
  <tbody><tr>
      <td>:no_entry_sign:</td>
      <td>

  Please update the PR title to match this format:
`type(subType): description`

Where `type` is one of:
`feat`, `fix`, `chore`, `docs`, `style`, `refactor`, `perf`, `test`, `ci`, `revert`

And: `subType` is one of:
`build`, `sql`, `log`, `mig`, `core`, `ilp`, `pgwire`, `http`, `conf`, `ui`, `wal`

For Example:

```
perf(sql): improve pattern matching performance for SELECT sub-queries
```
  </td>
    </tr>
  </tbody>
</table>




<p align="right">
  Generated by :no_entry_sign: <a href="https://danger.systems/js">dangerJS</a> against 4ae82650df9af09633e1f6b19f9770308d18f386
</p>

**Comment by ideoma** [comment]
#### [PR Coverage check]

:heart_eyes: **pass** : 17 / 18 (94.44%)




#### file detail

|   |path|covered line|new line|coverage|
|----|----|----|----|----|
|:large_blue_circle:|io/questdb/cutlass/line/http/LineHttpSender.java|4|5|80.00%|
|:large_blue_circle:|io/questdb/cutlass/line/tcp/LineWalAppender.java|2|2|100.00%|
|:large_blue_circle:|io/questdb/cutlass/line/tcp/LineTcpMeasurementScheduler.java|2|2|100.00%|
|:large_blue_circle:|io/questdb/cutlass/http/processors/LineHttpProcessorState.java|4|4|100.00%|
|:large_blue_circle:|io/questdb/cutlass/line/tcp/LineProtocolException.java|5|5|100.00%|

**Comment by bluestreak01** [comment]
wow @puzpuzpuz this is a solid restructuring effort! I really like the idea!

I don't see new tests run in CI, what's the intention here? Can we have them run together (concurrently) when branch changes?

**Comment by puzpuzpuz** [comment]
> I don't see new tests run in CI, what's the intention here? Can we have them run together (concurrently) when branch changes?

There is "New pull request (Hosted Running Compat tests on linux-jdk17)" CI run in the checks list. It should run on each PR + `master` commit, just like other tests. I can add runs on other OSes, but considering that these are compatibility tests Linux + JDK 17 may be sufficient. WDYT?

**Comment by puzpuzpuz** [comment]
> yep, that's great, it did not run for this PR though. I thought CI should pickup CI config from the PR

Good catch. Fixed the condition in bd0b3c2e1ed9483119d370fc94342d81378fa884

Seems to be running as expected now.

**Comment by ideoma** [comment]
#### [PR Coverage check]

:heart_eyes: **pass** : 17 / 18 (94.44%)




#### file detail

|   |path|covered line|new line|coverage|
|----|----|----|----|----|
|:large_blue_circle:|io/questdb/cutlass/line/http/LineHttpSender.java|4|5|80.00%|
|:large_blue_circle:|io/questdb/cutlass/line/tcp/LineWalAppender.java|2|2|100.00%|
|:large_blue_circle:|io/questdb/cutlass/line/tcp/LineTcpMeasurementScheduler.java|2|2|100.00%|
|:large_blue_circle:|io/questdb/cutlass/http/processors/LineHttpProcessorState.java|4|4|100.00%|
|:large_blue_circle:|io/questdb/cutlass/line/tcp/LineProtocolException.java|5|5|100.00%|

**Review by bluestreak01 — APPROVED** [review]

**Pull request merged**
