### PR TITLE
feat(ilp): breaking change💥 - ILP Sender requires explicit Transport selection

### PR DESCRIPTION
**Pull request by jerrinot**
This PR intentionally breaks both source and binary backward compatibility for Java ILP clients users.
It forces a user to choose between HTTP and TCP transport explicitly. 

The minimal change required is to pass the TCP transport selector when creating a builder. 

Before (this no longer compiles after this change):
```java
try (Sender sender = Sender.builder().address("localhost:9009").build()) {
    sender.table("mytable")
            .longColumn("id", 0)
            .stringColumn("name", "Joe Adams")
            .atNow();
}
```

After:
```java
try (Sender sender = Sender.builder(Sender.Transport.TCP).address("localhost:9009").build()) {
   sender.table("mytable")
           .longColumn("id", 0)
           .stringColumn("name", "Joe Adams")
           .atNow();
}
```
_Note how the `builder()` receives a transport selector._

Most people should switch to the HTTP transport. The code would look like this:
```java
try (Sender sender = Sender.builder(Sender.Transport.HTTP).address("localhost:9000").build()) {
   sender.table("mytable")
           .longColumn("id", 0)
           .stringColumn("name", "Joe Adams")
           .atNow();
}
```
_Note how also the port changed from 9009 to 9000._

**Other Consideration**
The HTTP transport implements proper error reporting, automatic retries for recoverable errors and simpler configuration. The TCP transport might still be useful on high-latency networks. If you experience performance issues with the HTTP transport then please let us now.

### CODE REVIEW

**Comment by ideoma** [comment]
#### [PR Coverage check]

:heart_eyes: **pass** : 9 / 9 (100.00%)




#### file detail

|   |path|covered line|new line|coverage|
|----|----|----|----|----|
|:large_blue_circle:|io/questdb/client/Sender.java|9|9|100.00%|

**Comment by ideoma** [comment]
#### [PR Coverage check]

:heart_eyes: **pass** : 9 / 9 (100.00%)




#### file detail

|   |path|covered line|new line|coverage|
|----|----|----|----|----|
|:large_blue_circle:|io/questdb/client/Sender.java|9|9|100.00%|

**Comment by ideoma** [comment]
#### [PR Coverage check]

:heart_eyes: **pass** : 9 / 9 (100.00%)




#### file detail

|   |path|covered line|new line|coverage|
|----|----|----|----|----|
|:large_blue_circle:|io/questdb/client/Sender.java|9|9|100.00%|

**Comment by ideoma** [comment]
#### [PR Coverage check]

:heart_eyes: **pass** : 9 / 9 (100.00%)




#### file detail

|   |path|covered line|new line|coverage|
|----|----|----|----|----|
|:large_blue_circle:|io/questdb/client/Sender.java|9|9|100.00%|

**Review by ideoma — APPROVED** [review]

**Review by bluestreak01 — CHANGES_REQUESTED** [review]
title does not reflect the nature of the breaking change, this change should be announced to the users

**Comment by jerrinot** [comment]
@bluestreak01 I changed the title and amended the PR description.

**Comment by ideoma** [comment]
#### [PR Coverage check]

:heart_eyes: **pass** : 9 / 9 (100.00%)




#### file detail

|   |path|covered line|new line|coverage|
|----|----|----|----|----|
|:large_blue_circle:|io/questdb/client/Sender.java|9|9|100.00%|

**Review by bluestreak01 — APPROVED** [review]
title does not reflect the nature of the breaking change, this change should be announced to the users

**Pull request merged**
