### PR TITLE
chore(core): use madvise with MADV_RANDOM for column files in table writer

### PR DESCRIPTION
**Pull request by puzpuzpuz**
Aims to get rid of disk reads in ingestion-only scenarios with memory pressure, i.e. when the amount of free memory available to OS for page caching is low.

### Experiment

Environment: c6a.xlarge (4 vCPU, 8GB RAM) instance running Ubuntu 22.04.

Scenario: a Java application ingest data via ILP client over 64 connections (connection per table); 64 tables with 1122 columns each (string, boolean, long and double types).

6.5.3 version:
Screenshot from 2022-10-05 11-15-15

This patch:
Screenshot from 2022-10-05 11-02-46

Notice near-zero disk read rate and significantly higher write rate.

### Potential regressions

I also did a few TSBS runs on my laptop (8 HT cores, 32GB RAM, 1TB NVMe SSD) to check if there is a regression in the scenario when there is no memory pressure. There is certain jitter in the results, so I'm including the best runs.

6.5.3:
```
$ GOMAXPROCS=3 ./tsbs_load_questdb --file /tmp/data --workers 3
time,per. metric/s,metric total,overall metric/s,per. row/s,row total,overall row/s
1664958753,8239600.68,8.240000E+07,8239600.68,823960.07,8.240000E+06,823960.07
1664958763,8539793.35,1.678000E+08,8389695.20,853979.34,1.678000E+07,838969.52
1664958773,7690021.95,2.447000E+08,8156476.87,769002.19,2.447000E+07,815647.69
1664958783,7760215.70,3.223000E+08,8057415.37,776021.57,3.223000E+07,805741.54
1664958793,6310168.88,3.854000E+08,7707976.49,631016.89,3.854000E+07,770797.65
1664958803,6029539.97,4.457000E+08,7428220.00,602954.00,4.457000E+07,742822.00
1664958813,6190198.94,5.076000E+08,7251367.03,619019.89,5.076000E+07,725136.70
1664958823,5779780.71,5.654000E+08,7067414.00,577978.07,5.654000E+07,706741.40
1664958833,6220235.19,6.276000E+08,6973287.20,622023.52,6.276000E+07,697328.72
1664958843,6110083.63,6.887000E+08,6886968.42,611008.36,6.887000E+07,688696.84

Summary:
loaded 691200000 metrics in 100.411sec with 3 workers (mean rate 6883738.17 metrics/sec)
loaded 69120000 rows in 100.411sec with 3 workers (mean rate 688373.82 rows/sec)
```

This patch:
```
$ GOMAXPROCS=3 ./tsbs_load_questdb --file /tmp/data --workers 3
time,per. metric/s,metric total,overall metric/s,per. row/s,row total,overall row/s
1664959407,8798769.80,8.800000E+07,8798769.80,879876.98,8.800000E+06,879876.98
1664959417,8919835.47,1.772000E+08,8859298.96,891983.55,1.772000E+07,885929.90
1664959427,8840395.84,2.656000E+08,8852998.44,884039.58,2.656000E+07,885299.84
1664959437,8319832.91,3.488000E+08,8719708.83,831983.29,3.488000E+07,871970.88
1664959447,7899579.76,4.278000E+08,8555680.42,789957.98,4.278000E+07,855568.04
1664959457,6530352.29,4.931000E+08,8218151.41,653035.23,4.931000E+07,821815.14
1664959467,6510242.31,5.582000E+08,7974176.81,651024.23,5.582000E+07,797417.68
1664959477,6509339.48,6.233000E+08,7791058.08,650933.95,6.233000E+07,779105.81
1664959487,6560316.68,6.889000E+08,7654317.89,656031.67,6.889000E+07,765431.79

Summary:
loaded 691200000 metrics in 90.360sec with 3 workers (mean rate 7649381.08 metrics/sec)
loaded 69120000 rows in 90.360sec with 3 workers (mean rate 764938.11 rows/sec)
```

So, hopefully there is no significant regression.

### CODE REVIEW

**Comment by ideoma** [comment]
#### [PR Coverage check]

:heart_eyes: **pass** : 39 / 46 (84.78%)




#### file detail

|   |path|covered line|new line|coverage|
|----|----|----|----|----|
|:large_blue_circle:|io/questdb/cairo/vm/MemoryCMRImpl.java|6|9|66.67%|
|:large_blue_circle:|io/questdb/cairo/vm/MemoryCMARWImpl.java|4|6|66.67%|
|:large_blue_circle:|io/questdb/std/Files.java|5|7|71.43%|
|:large_blue_circle:|io/questdb/std/FilesFacadeImpl.java|2|2|100.00%|
|:large_blue_circle:|io/questdb/cairo/vm/api/MemoryM.java|5|5|100.00%|
|:large_blue_circle:|io/questdb/cairo/vm/MemoryPMARImpl.java|13|13|100.00%|
|:large_blue_circle:|io/questdb/cairo/TableWriter.java|2|2|100.00%|
|:large_blue_circle:|io/questdb/cairo/WalWriter.java|2|2|100.00%|

**Comment by ideoma** [comment]
#### [PR Coverage check]

:heart_eyes: **pass** : 45 / 49 (91.84%)




#### file detail

|   |path|covered line|new line|coverage|
|----|----|----|----|----|
|:large_blue_circle:|io/questdb/std/Files.java|5|9|55.56%|
|:large_blue_circle:|io/questdb/std/FilesFacadeImpl.java|5|5|100.00%|
|:large_blue_circle:|io/questdb/cairo/vm/api/MemoryM.java|5|5|100.00%|
|:large_blue_circle:|io/questdb/cairo/vm/MemoryCMRImpl.java|8|8|100.00%|
|:large_blue_circle:|io/questdb/cairo/vm/MemoryPMARImpl.java|13|13|100.00%|
|:large_blue_circle:|io/questdb/cairo/TableWriter.java|2|2|100.00%|
|:large_blue_circle:|io/questdb/cairo/vm/MemoryCMARWImpl.java|5|5|100.00%|
|:large_blue_circle:|io/questdb/cairo/WalWriter.java|2|2|100.00%|

**Comment by ideoma** [comment]
#### [PR Coverage check]

:heart_eyes: **pass** : 45 / 49 (91.84%)




#### file detail

|   |path|covered line|new line|coverage|
|----|----|----|----|----|
|:large_blue_circle:|io/questdb/std/Files.java|5|9|55.56%|
|:large_blue_circle:|io/questdb/std/FilesFacadeImpl.java|5|5|100.00%|
|:large_blue_circle:|io/questdb/cairo/vm/api/MemoryM.java|5|5|100.00%|
|:large_blue_circle:|io/questdb/cairo/vm/MemoryCMRImpl.java|8|8|100.00%|
|:large_blue_circle:|io/questdb/cairo/vm/MemoryPMARImpl.java|13|13|100.00%|
|:large_blue_circle:|io/questdb/cairo/TableWriter.java|2|2|100.00%|
|:large_blue_circle:|io/questdb/cairo/vm/MemoryCMARWImpl.java|5|5|100.00%|
|:large_blue_circle:|io/questdb/cairo/WalWriter.java|2|2|100.00%|

**Comment by bluestreak01** [comment]
@puzpuzpuz  there is no macos binary, does this not compile on mac ?

**Comment by puzpuzpuz** [comment]
> @puzpuzpuz there is no macos binary, does this not compile on mac ?

I've only added a native function for Linux, just like we do it for `fadvise`. Do you think we need `madvise` and `fadvise` on MacOS?

**Comment by ideoma** [comment]
#### [PR Coverage check]

:heart_eyes: **pass** : 46 / 50 (92.00%)




#### file detail

|   |path|covered line|new line|coverage|
|----|----|----|----|----|
|:large_blue_circle:|io/questdb/std/Files.java|5|9|55.56%|
|:large_blue_circle:|io/questdb/std/FilesFacadeImpl.java|5|5|100.00%|
|:large_blue_circle:|io/questdb/cairo/vm/api/MemoryM.java|5|5|100.00%|
|:large_blue_circle:|io/questdb/cairo/vm/MemoryCMRImpl.java|8|8|100.00%|
|:large_blue_circle:|io/questdb/cairo/vm/MemoryPMARImpl.java|13|13|100.00%|
|:large_blue_circle:|io/questdb/cairo/TableWriter.java|2|2|100.00%|
|:large_blue_circle:|io/questdb/cutlass/text/TextImportTask.java|1|1|100.00%|
|:large_blue_circle:|io/questdb/cairo/vm/MemoryCMARWImpl.java|5|5|100.00%|
|:large_blue_circle:|io/questdb/cairo/WalWriter.java|2|2|100.00%|

**Pull request merged**
