### PR TITLE
chore(core): fixed Files.isDirOrSoftLinkDir behaviour to not list directory

### PR DESCRIPTION
**Pull request by amunra**
The old logic would apply the `isDir` check on the first child of the directory, instead of the the directory itself.

Closes https://github.com/questdb/questdb/issues/5054

### CODE REVIEW

**Comment by questdb-butler** [comment]
<table>
  <thead>
    <tr>
      <th width="50"></th>
      <th width="100%" data-danger-table="true">Fails</th>
    </tr>
  </thead>
  <tbody><tr>
      <td>:no_entry_sign:</td>
      <td>

  Please update the PR title to match this format:
`type(subType): description`

Where `type` is one of:
`feat`, `fix`, `chore`, `docs`, `style`, `refactor`, `perf`, `test`, `ci`, `revert`

And: `subType` is one of:
`build`, `sql`, `log`, `mig`, `core`, `ilp`, `pgwire`, `http`, `conf`, `ui`, `wal`

For Example:

```
perf(sql): improve pattern matching performance for SELECT sub-queries
```
  </td>
    </tr>
  </tbody>
</table>




<p align="right">
  Generated by :no_entry_sign: <a href="https://danger.systems/js">dangerJS</a> against a8f807649b082de9c91120476ad7dc7cb13868ae
</p>

**Comment by ideoma** [comment]
#### [PR Coverage check]

:heart_eyes: **pass** : 1 / 1 (100.00%)




#### file detail

|   |path|covered line|new line|coverage|
|----|----|----|----|----|
|:large_blue_circle:|io/questdb/std/Files.java|1|1|100.00%|

**Comment by amunra** [comment]
Reason it fails in PR is that `isDir` was somehow never implemented on Windows..

**Comment by amunra** [comment]
Yeah, Win32..

So it turns out that Windows doesn't really have an API to resolve a reparse point (symlink, hardlink, etc) in one go.
I tried to get this working in the C code, but I now understand the issue (and why most blog posts on this matter are wrong - they only work for files, not directories), so it's proved to be quite time-consuming.
Should we still want to do this in C we'd realistically need to port the following functions from the Rust standard lib:
* https://github.com/rust-lang/rust/blob/ca87b535a05097df6abbe2a031b057de2cefac5b/library/std/src/sys/pal/windows/fs.rs#L1140
* https://github.com/rust-lang/rust/blob/ca87b535a05097df6abbe2a031b057de2cefac5b/library/std/src/sys/pal/windows/fs.rs#L539

Leaving the impl in Rust is the more pragmatic solution, I think.

**Comment by amunra** [comment]
Closing and recreating.

**Pull request closed without merging**
