### PR TITLE
feat(pgwire): add support for configurable read-only user

### PR DESCRIPTION
**Pull request by puzpuzpuz**
Adds configurable additional read-only user for PGWire. By default, that user is disabled. To enable it, one has to change the config
```
pg.readonly.user.enabled=true
# default username is "user"
pg.readonly.user=my_ro_user
# default password is "quest"
pg.readonly.password=pwd
```

### CODE REVIEW

**Comment by ideoma** [comment]
#### [PR Coverage check]

:heart_eyes: **pass** : 23 / 24 (95.83%)




#### file detail

|   |path|covered line|new line|coverage|
|----|----|----|----|----|
|:large_blue_circle:|io/questdb/cutlass/pgwire/PGConnectionContext.java|11|12|91.67%|
|:large_blue_circle:|io/questdb/PropServerConfiguration.java|6|6|100.00%|
|:large_blue_circle:|io/questdb/PropertyKey.java|3|3|100.00%|
|:large_blue_circle:|io/questdb/cutlass/pgwire/DefaultPGWireConfiguration.java|3|3|100.00%|

**Comment by ideoma** [comment]
#### [PR Coverage check]

:heart_eyes: **pass** : 24 / 24 (100.00%)




#### file detail

|   |path|covered line|new line|coverage|
|----|----|----|----|----|
|:large_blue_circle:|io/questdb/PropServerConfiguration.java|6|6|100.00%|
|:large_blue_circle:|io/questdb/PropertyKey.java|3|3|100.00%|
|:large_blue_circle:|io/questdb/cutlass/pgwire/DefaultPGWireConfiguration.java|3|3|100.00%|
|:large_blue_circle:|io/questdb/cutlass/pgwire/PGConnectionContext.java|12|12|100.00%|

**Comment by ideoma** [comment]
#### [PR Coverage check]

:heart_eyes: **pass** : 22 / 22 (100.00%)




#### file detail

|   |path|covered line|new line|coverage|
|----|----|----|----|----|
|:large_blue_circle:|io/questdb/PropServerConfiguration.java|6|6|100.00%|
|:large_blue_circle:|io/questdb/PropertyKey.java|3|3|100.00%|
|:large_blue_circle:|io/questdb/cutlass/pgwire/DefaultPGWireConfiguration.java|3|3|100.00%|
|:large_blue_circle:|io/questdb/cutlass/pgwire/PGConnectionContext.java|10|10|100.00%|

**Review by marregui — APPROVED** [review]
LGTM 

tested it with quest. Admin maintains write access, user does not, well done.

**Comment by jerrinot** [comment]
@puzpuzpuz will you send a documentation PR?

**Comment by puzpuzpuz** [comment]
> @puzpuzpuz will you send a documentation PR?

@jerrinot sure. I planned to do it once the PR is merged. Going to submit a doc PR now.

**Comment by puzpuzpuz** [comment]
Here goes the doc PR: https://github.com/questdb/questdb.io/pull/1233

**Pull request merged**
