### PR TITLE
fix(sql): fix group by performance when selected columns have aliases

### LINKED ISSUE #2566: Performance degradation when aliasing columns
### Describe the bug

This query executes on the demo box in around 100ms:
```
select symbol, count() 
from trades 
group by symbol;
```

but this query executes 10s (100x more!)
```
select symbol as s, count() 
from trades 
group by s;
```

Both queries are functionally equivalent and should result in the same query plan. Apparently, that's not the case. 
I reckon aliasing disables an optimization. 

### Environment
https://demo.questdb.io/
- **QuestDB version**: 6.5.3

### PR DESCRIPTION
**Pull request by puzpuzpuz**
Fixes #2566

Changes `SelectedRecordCursorFactory` to support page frame when the underlying base factory supports them. This enables vectorization for queries with transitioning query model such as `select s as symbol, count() from x`. In such queries `SelectedRecordCursorFactory` is used as an intermediate factory between the upper-level group by factory and lower-level `DataFrameRecordCursorFactory`.

### CODE REVIEW

**Comment by ideoma** [comment]
#### [PR Coverage check]

:heart_eyes: **pass** : 31 / 40 (77.50%)




#### file detail

|   |path|covered line|new line|coverage|
|----|----|----|----|----|
|:large_blue_circle:|io/questdb/griffin/engine/table/SelectedRecordCursorFactory.java|28|37|75.68%|
|:large_blue_circle:|io/questdb/griffin/SqlOptimiser.java|3|3|100.00%|

**Comment by ideoma** [comment]
#### [PR Coverage check]

:heart_eyes: **pass** : 31 / 40 (77.50%)




#### file detail

|   |path|covered line|new line|coverage|
|----|----|----|----|----|
|:large_blue_circle:|io/questdb/griffin/engine/table/SelectedRecordCursorFactory.java|28|37|75.68%|
|:large_blue_circle:|io/questdb/griffin/SqlOptimiser.java|3|3|100.00%|

**Comment by jerrinot** [comment]
@puzpuzpuz I haven't started the review yet, but I already have one ask: Please add the idea behind the fix as a PR description. Just a sentence or two explaining why it was slower before and what about this PR makes it faster. Thanks a lot!

**Comment by puzpuzpuz** [comment]
> @puzpuzpuz I haven't started the review yet, but I already have one ask: Please add the idea behind the fix as a PR description. Just a sentence or two explaining why it was slower before and what about this PR makes it faster. Thanks a lot!

Good point. Did my best to describe the changes. See the PR description.

**Review by bluestreak01 — APPROVED** [review]

**Comment by ideoma** [comment]
#### [PR Coverage check]

:heart_eyes: **pass** : 31 / 40 (77.50%)




#### file detail

|   |path|covered line|new line|coverage|
|----|----|----|----|----|
|:large_blue_circle:|io/questdb/griffin/engine/table/SelectedRecordCursorFactory.java|28|37|75.68%|
|:large_blue_circle:|io/questdb/griffin/SqlOptimiser.java|3|3|100.00%|

**Pull request merged**
