### PR TITLE
fix(ilp): fixed missing index update when ingesting data over ILP

### LINKED ISSUE #1278: Inconsistent filtering on indexed SYMBOL columns when ILP modifies table schema
**Describe the bug**
When an indexed symbol column exists in a table, adding new columns via ILP produces inconsistent results

**To Reproduce**

1. Create table with indexed `symbol` column:
```sql
create table tbl (ReceiveTime timestamp, messageType symbol index)
timestamp(ReceiveTime) 
partition by DAY;
```
2. Add records with additional column, e.g.:
```python
import socket
sock = socket.socket(socket.AF_INET, socket.SOCK_STREAM)
try:
  sock.connect(('localhost', 9009))
  sock.send(('tbl,messageType=1801 description="test1"\n').encode())
  sock.send(('tbl,messageType=1802 description="test2"\n').encode()) 
except socket.error as e:
  print("Got error: %s" % (e))
sock.close()
```
3. Run this query:
```sql
select * from tbl where messageType = '1802'
```

**Expected behavior**
Filtering of table results based on indexed column, instead, no results are returned.

**Environment (please complete the following information):**
 - OS: MacOS (reported on Windows, also)
 - Version: Docker 6.0.4 (2d16df8f0846707f34f76f96864e93f0cafe85f3)

### PR DESCRIPTION
**Pull request by bluestreak01**
Closes #1278

### CODE REVIEW

**Comment by ideoma** [comment]
#### [PR Coverage check]

:heart_eyes: **pass** : 14 / 14 (100.00%)




#### file detail

|   |path|covered line|new line|coverage|
|----|----|----|----|----|
|:large_blue_circle:|io/questdb/cairo/TableWriter.java|4|4|100.00%|
|:large_blue_circle:|io/questdb/std/ObjList.java|10|10|100.00%|

**Comment by ideoma** [comment]
#### [PR Coverage check]

coverage check fail. please retry. :fearful:

[Please let me know](https://github.com/naver/cover-checker/issues/new) when error again.

com.naver.nid.cover.parser.coverage.exception.ParseException: java.io.FileNotFoundException: /home/vsts/work/1/s/core/CCReport43F6D5EF/jacoco.xml (No such file or directory)

**Comment by ideoma** [comment]
#### [PR Coverage check]

:heart_eyes: **pass** : 14 / 14 (100.00%)




#### file detail

|   |path|covered line|new line|coverage|
|----|----|----|----|----|
|:large_blue_circle:|io/questdb/cairo/TableWriter.java|4|4|100.00%|
|:large_blue_circle:|io/questdb/std/ObjList.java|10|10|100.00%|

**Review by ideoma — DISMISSED** [review]

**Comment by ideoma** [comment]
#### [PR Coverage check]

:heart_eyes: **pass** : 14 / 14 (100.00%)




#### file detail

|   |path|covered line|new line|coverage|
|----|----|----|----|----|
|:large_blue_circle:|io/questdb/cairo/TableWriter.java|4|4|100.00%|
|:large_blue_circle:|io/questdb/std/ObjList.java|10|10|100.00%|

**Comment by ideoma** [comment]
#### [PR Coverage check]

:heart_eyes: **pass** : 14 / 14 (100.00%)




#### file detail

|   |path|covered line|new line|coverage|
|----|----|----|----|----|
|:large_blue_circle:|io/questdb/cairo/TableWriter.java|4|4|100.00%|
|:large_blue_circle:|io/questdb/std/ObjList.java|10|10|100.00%|

**Comment by ideoma** [comment]
#### [PR Coverage check]

:heart_eyes: **pass** : 14 / 14 (100.00%)




#### file detail

|   |path|covered line|new line|coverage|
|----|----|----|----|----|
|:large_blue_circle:|io/questdb/cairo/TableWriter.java|4|4|100.00%|
|:large_blue_circle:|io/questdb/std/ObjList.java|10|10|100.00%|

**Comment by ideoma** [comment]
#### [PR Coverage check]

:heart_eyes: **pass** : 14 / 14 (100.00%)




#### file detail

|   |path|covered line|new line|coverage|
|----|----|----|----|----|
|:large_blue_circle:|io/questdb/cairo/TableWriter.java|4|4|100.00%|
|:large_blue_circle:|io/questdb/std/ObjList.java|10|10|100.00%|

**Comment by ideoma** [comment]
#### [PR Coverage check]

:heart_eyes: **pass** : 27 / 31 (87.10%)




#### file detail

|   |path|covered line|new line|coverage|
|----|----|----|----|----|
|:large_blue_circle:|io/questdb/cutlass/http/HttpConnectionContext.java|12|16|75.00%|
|:large_blue_circle:|io/questdb/cairo/TableWriter.java|4|4|100.00%|
|:large_blue_circle:|io/questdb/network/AbstractIODispatcher.java|1|1|100.00%|
|:large_blue_circle:|io/questdb/std/ObjList.java|10|10|100.00%|

**Comment by ideoma** [comment]
#### [PR Coverage check]

:heart_eyes: **pass** : 27 / 31 (87.10%)




#### file detail

|   |path|covered line|new line|coverage|
|----|----|----|----|----|
|:large_blue_circle:|io/questdb/cutlass/http/HttpConnectionContext.java|12|16|75.00%|
|:large_blue_circle:|io/questdb/cairo/TableWriter.java|4|4|100.00%|
|:large_blue_circle:|io/questdb/network/AbstractIODispatcher.java|1|1|100.00%|
|:large_blue_circle:|io/questdb/std/ObjList.java|10|10|100.00%|

**Comment by ideoma** [comment]
#### [PR Coverage check]

:heart_eyes: **pass** : 27 / 31 (87.10%)




#### file detail

|   |path|covered line|new line|coverage|
|----|----|----|----|----|
|:large_blue_circle:|io/questdb/cutlass/http/HttpConnectionContext.java|12|16|75.00%|
|:large_blue_circle:|io/questdb/cairo/TableWriter.java|4|4|100.00%|
|:large_blue_circle:|io/questdb/network/AbstractIODispatcher.java|1|1|100.00%|
|:large_blue_circle:|io/questdb/std/ObjList.java|10|10|100.00%|

**Comment by ideoma** [comment]
#### [PR Coverage check]

:heart_eyes: **pass** : 27 / 31 (87.10%)




#### file detail

|   |path|covered line|new line|coverage|
|----|----|----|----|----|
|:large_blue_circle:|io/questdb/cutlass/http/HttpConnectionContext.java|12|16|75.00%|
|:large_blue_circle:|io/questdb/cairo/TableWriter.java|4|4|100.00%|
|:large_blue_circle:|io/questdb/network/AbstractIODispatcher.java|1|1|100.00%|
|:large_blue_circle:|io/questdb/std/ObjList.java|10|10|100.00%|

**Review by marregui — APPROVED** [review]
LGTM

**Pull request merged**
