### PR TITLE
#1701 Null value for short/byte in where clause gives error

### PR DESCRIPTION
**Pull request by hemantgs**
For queries such as `SELECT * from sensors where make= NULL ;` , where make is a short column , an error will be displayed like below 

Screenshot from 2021-12-21 13-35-21

### CODE REVIEW

**Comment by hemantgs** [comment]
Hi , thought I'll give this a shot , please do have a look

**Comment by bluestreak01** [comment]
Hi Hemant, thank you for the PR. Tests are required to pass though

**Comment by bluestreak01** [comment]
Closing due to lack of response

**Comment by hemantgs** [comment]
@bluestreak01 Apologies , couldnt respond sooner ,  since an exception is thrown when eqShort/eqByteFunctionFactory is parsed by FunctionParser , the corresponding tests failed .. Just wondering if this is the correct approach , 
Meanwhile , will check and fix why the tests are failing

**Pull request closed without merging**
