### PR TITLE
fix(test): add missing wait to flaky flush query cache tests

### PR DESCRIPTION
**Pull request by puzpuzpuz**

### CODE REVIEW

**Comment by puzpuzpuz** [comment]
@bluestreak01 I couldn't reproduce the `testJsonQueryFlushQueryCache` flakiness on my local machine, as well as after around 5 builds on CI. I'd propose merging this PR, so that next time it fails we at least get some understand on the measured memory consumption values. WDYT?

**Review by bluestreak01 — APPROVED** [review]

**Review by jerrinot — APPROVED** [review]
optional improvement: consider dumping memory per tag. this could tell us a bit more.

the current master will only tell you that memory after flush was not lesser than memory after join. 

this PR will add absolute values. that's the new information. but will it really help us to diagnose the issue? I guess the absolute numbers help us to form a hypothesis. knowing allocations per tag could help us more. perhaps there is something else allocating, completely unrelated to query cache? 

caveat: I don't know what's the granularity of our tagging.

**Comment by bluestreak01** [comment]
the most recent failure is on the test in question, we can validate PR usefulness without merging to master :)

**Comment by puzpuzpuz** [comment]
> Is this PR helping?

It's certainly helping. I'll convert it into draft and add more diagnostic information around memory consumption.

**Review by jerrinot — DISMISSED** [review]

**Review by ideoma — APPROVED** [review]

**Review by bluestreak01 — APPROVED** [review]

**Review by ideoma — APPROVED** [review]

**Pull request merged**
