### PR TITLE
fix(sql): fix long256 comparisons on different columns of the same table

### PR DESCRIPTION
**Pull request by jerrinot**
root cause:
Different columns of the same record share the same Long256 wrapper. So for long256 comparisons on the same record we have to compare WrapperA with WrapperB.

### CODE REVIEW

**Review by puzpuzpuz — APPROVED** [review]
Nice catch!

**Comment by ideoma** [comment]
#### [PR Coverage check]

:heart_eyes: **pass** : 2 / 2 (100.00%)




#### file detail

|   |path|covered line|new line|coverage|
|----|----|----|----|----|
|:large_blue_circle:|io/questdb/griffin/engine/functions/lt/LtLong256FunctionFactory.java|1|1|100.00%|
|:large_blue_circle:|io/questdb/griffin/engine/functions/eq/EqLong256FunctionFactory.java|1|1|100.00%|

**Comment by ideoma** [comment]
#### [PR Coverage check]

:heart_eyes: **pass** : 2 / 2 (100.00%)




#### file detail

|   |path|covered line|new line|coverage|
|----|----|----|----|----|
|:large_blue_circle:|io/questdb/griffin/engine/functions/lt/LtLong256FunctionFactory.java|1|1|100.00%|
|:large_blue_circle:|io/questdb/griffin/engine/functions/eq/EqLong256FunctionFactory.java|1|1|100.00%|

**Comment by ideoma** [comment]
#### [PR Coverage check]

:heart_eyes: **pass** : 2 / 2 (100.00%)




#### file detail

|   |path|covered line|new line|coverage|
|----|----|----|----|----|
|:large_blue_circle:|io/questdb/griffin/engine/functions/lt/LtLong256FunctionFactory.java|1|1|100.00%|
|:large_blue_circle:|io/questdb/griffin/engine/functions/eq/EqLong256FunctionFactory.java|1|1|100.00%|

**Pull request merged**
