### PR TITLE
fix(cutlass): allow single row csv import

### LINKED ISSUE #1652: Saving data from a csv with only one row.
### Describe the bug

If a csv file is send only with one row (no column names row) the data is not saved in the DB.
image

Python code used:
`csv = {'schema': '[{"name":"timestamp", "type": "TIMESTAMP", "pattern": "yyyy-MM-ddTHH:mm:ss.SSSUUUNNNZ"}]',
       'data': ('table_name', open('test.csv', 'r'))}
host = 'http://localhost:9000'
requests.post(host + '/imp', files=csv)`

### To reproduce

1. Create csv with only one row containing data.
2. Insert in the QuestDB
3. The one row is not saved in the DB.

### Expected Behavior

The row should be saved in the DB.
If the csv file contains two rows (without column names) both rows will be saved in the DB correctly.

### Environment

```markdown
- **QuestDB version**: 6.1.1
- **OS**: Ubuntu
- **Browser**: Firefox
```

### Additional context

_No response_

### PR DESCRIPTION
**Pull request by puzpuzpuz**
Fixes #1652

Adds a new `delimiter` query parameter to POST `/imp` endpoint. The parameter forces column delimiter detection to be skipped, allowing single row import. The delimiter value has to be URL encoded.

An example (notice the `delimiter=%2C` query param which means a comma delimiter):
```bash
$ curl -v -F schema='[{"name":"timestamp", "type": "TIMESTAMP", "pattern": "yyyy-MM-ddTHH:mm:ss.SSSUUUNNNZ"}]' -F data=@test.csv 'http://localhost:9000/imp?delimiter=%2C'
*   Trying 127.0.0.1:9000...
* TCP_NODELAY set
* Connected to localhost (127.0.0.1) port 9000 (#0)
> POST /imp?delimiter=%2C HTTP/1.1
> Host: localhost:9000
> User-Agent: curl/7.68.0
> Accept: */*
> Content-Length: 435
> Content-Type: multipart/form-data; boundary=------------------------88fecc9950fc698b
> 
* We are completely uploaded and fine
* Mark bundle as not supporting multiuse
< HTTP/1.1 200 OK
< Server: questDB/1.0
< Date: Thu, 9 Dec 2021 13:16:54 GMT
< Transfer-Encoding: chunked
< Content-Type: text/plain; charset=utf-8
< 
+-----------------------------------------------------------------------------------------------------------------+
|      Location:  |                                          test.csv  |        Pattern  | Locale  |      Errors  |
|   Partition by  |                                              NONE  |                 |         |              |
|      Timestamp  |                                              NONE  |                 |         |              |
+-----------------------------------------------------------------------------------------------------------------+
|   Rows handled  |                                                 1  |                 |         |              |
|  Rows imported  |                                                 1  |                 |         |              |
+-----------------------------------------------------------------------------------------------------------------+
|              0  |                                                f0  |                   STRING  |           0  |
|              1  |                                                f1  |                   STRING  |           0  |
|              2  |                                                f2  |                   STRING  |           0  |
|              3  |                                                f3  |                   STRING  |           0  |
|              4  |                                                f4  |                TIMESTAMP  |           0  |
+-----------------------------------------------------------------------------------------------------------------+
```

### CODE REVIEW

**Comment by ideoma** [comment]
#### [PR Coverage check]

:heart_eyes: **pass** : 1 / 1 (100.00%)




#### file detail

|   |path|covered line|new line|coverage|
|----|----|----|----|----|
|:large_blue_circle:|io/questdb/cutlass/text/TextDelimiterScanner.java|1|1|100.00%|

**Comment by ideoma** [comment]
#### [PR Coverage check]

:heart_eyes: **pass** : 1 / 1 (100.00%)




#### file detail

|   |path|covered line|new line|coverage|
|----|----|----|----|----|
|:large_blue_circle:|io/questdb/cutlass/text/TextDelimiterScanner.java|1|1|100.00%|

**Comment by ideoma** [comment]
#### [PR Coverage check]

:heart_eyes: **pass** : 13 / 14 (92.86%)




#### file detail

|   |path|covered line|new line|coverage|
|----|----|----|----|----|
|:large_blue_circle:|io/questdb/griffin/SqlCompiler.java|1|2|50.00%|
|:large_blue_circle:|io/questdb/cutlass/http/processors/TextImportProcessor.java|3|3|100.00%|
|:large_blue_circle:|io/questdb/cutlass/http/HttpMultipartContentParser.java|2|2|100.00%|
|:large_blue_circle:|io/questdb/cutlass/http/WaitProcessor.java|1|1|100.00%|
|:large_blue_circle:|io/questdb/cutlass/http/processors/TextImportProcessorState.java|2|2|100.00%|
|:large_blue_circle:|io/questdb/cutlass/text/TextLoader.java|2|2|100.00%|
|:large_blue_circle:|io/questdb/cutlass/text/TextDelimiterScanner.java|2|2|100.00%|

**Comment by ideoma** [comment]
#### [PR Coverage check]

:heart_eyes: **pass** : 13 / 14 (92.86%)




#### file detail

|   |path|covered line|new line|coverage|
|----|----|----|----|----|
|:large_blue_circle:|io/questdb/griffin/SqlCompiler.java|1|2|50.00%|
|:large_blue_circle:|io/questdb/cutlass/http/processors/TextImportProcessor.java|3|3|100.00%|
|:large_blue_circle:|io/questdb/cutlass/http/HttpMultipartContentParser.java|2|2|100.00%|
|:large_blue_circle:|io/questdb/cutlass/http/WaitProcessor.java|1|1|100.00%|
|:large_blue_circle:|io/questdb/cutlass/http/processors/TextImportProcessorState.java|2|2|100.00%|
|:large_blue_circle:|io/questdb/cutlass/text/TextLoader.java|2|2|100.00%|
|:large_blue_circle:|io/questdb/cutlass/text/TextDelimiterScanner.java|2|2|100.00%|

**Comment by ideoma** [comment]
#### [PR Coverage check]

:heart_eyes: **pass** : 4 / 4 (100.00%)




#### file detail

|   |path|covered line|new line|coverage|
|----|----|----|----|----|
|:large_blue_circle:|io/questdb/cutlass/http/processors/TextImportProcessor.java|3|3|100.00%|
|:large_blue_circle:|io/questdb/cutlass/http/WaitProcessor.java|1|1|100.00%|

**Comment by ideoma** [comment]
#### [PR Coverage check]

:heart_eyes: **pass** : 4 / 4 (100.00%)




#### file detail

|   |path|covered line|new line|coverage|
|----|----|----|----|----|
|:large_blue_circle:|io/questdb/cutlass/http/processors/TextImportProcessor.java|3|3|100.00%|
|:large_blue_circle:|io/questdb/cutlass/http/WaitProcessor.java|1|1|100.00%|

**Comment by ideoma** [comment]
#### [PR Coverage check]

:heart_eyes: **pass** : 4 / 4 (100.00%)




#### file detail

|   |path|covered line|new line|coverage|
|----|----|----|----|----|
|:large_blue_circle:|io/questdb/cutlass/http/processors/TextImportProcessor.java|3|3|100.00%|
|:large_blue_circle:|io/questdb/cutlass/http/WaitProcessor.java|1|1|100.00%|

**Review by bluestreak01 — APPROVED** [review]

**Comment by ideoma** [comment]
#### [PR Coverage check]

:heart_eyes: **pass** : 7 / 7 (100.00%)




#### file detail

|   |path|covered line|new line|coverage|
|----|----|----|----|----|
|:large_blue_circle:|io/questdb/cutlass/http/processors/TextImportProcessor.java|3|3|100.00%|
|:large_blue_circle:|io/questdb/cutlass/http/WaitProcessor.java|4|4|100.00%|

**Comment by ideoma** [comment]
#### [PR Coverage check]

:heart_eyes: **pass** : 7 / 7 (100.00%)




#### file detail

|   |path|covered line|new line|coverage|
|----|----|----|----|----|
|:large_blue_circle:|io/questdb/cutlass/http/processors/TextImportProcessor.java|3|3|100.00%|
|:large_blue_circle:|io/questdb/cutlass/http/WaitProcessor.java|4|4|100.00%|

**Pull request merged**
