### PR TITLE
fix(sql): fix possible errors when casting strings to double

### LINKED ISSUE #2677: Select sampleby
### Describe the bug

I have a query for a table: 

```sql
select ts,id,  avg(cast(value as double))  
                                from 'pvs_f3a11bb6_bc4a_44bd_b187_abfe1a22495e'
                                where ( id = '79cd6344-837e-4f0f-80b6-bb0e5a51b3d9')
                                and ts >= '2022-10-24 11:00:00'
                                and ts < '2022-10-24 11:19:00'
                                and state = 'Ok'
                                sample by 5s 
```
Columns ts = TimeStamp, id = symbol, value = string

For some intervalls on the Id , we get this error in the log below: But all other interval it works as excpected and when we select the values raw we cant see any reason in the data for any error, it looks the same as on interval that works.

Log Dump.
```
2022-10-24T12:12:27.596901Z I i.q.c.h.p.QueryCache miss [thread=questdb-worker-3, sql=select ts,id,  avg(cast(value as double))  
                                from 'pvs_f3a11bb6_bc4a_44bd_b187_abfe1a22495e'
                                where ( id = '79cd6344-837e-4f0f-80b6-bb0e5a51b3d9')
                                and ts >= '2022-10-24 11:00:00'
                                and ts < '2022-10-24 11:19:00'
                                and state = 'Ok'
                                sample by 5s ]
2022-10-24T12:12:27.599787Z I i.q.g.SqlCompiler plan [q=`select-group-by ts, id, avg(cast(value,double)) avg from (select [ts, id, value, state] from pvs_f3a11bb6_bc4a_44bd_b187_abfe1a22495e timestamp (ts) where id = '79cd6344-837e-4f0f-80b6-bb0e5a51b3d9' and ts >= '2022-10-24 11:00:00' and ts < '2022-10-24 11:19:00' and state = 'Ok') sample by 5s`, fd=4344]
2022-10-24T12:12:27.600180Z I i.q.g.SqlCodeGenerator JIT enabled for (sub)query [tableName=pvs_f3a11bb6_bc4a_44bd_b187_abfe1a22495e, fd=4344]
2022-10-24T12:12:27.600755Z I i.q.c.h.p.JsonQueryProcessorState [4344] execute-new [skip: 0, stop: 1000]
2022-10-24T12:12:27.602034Z C i.q.c.h.p.JsonQueryProcessorState [4344] Uh-oh. Error!
java.lang.UnsupportedOperationException
	at io.questdb.std.str.AbstractCharSequence.subSequence(AbstractCharSequence.java:63)
	at io.questdb.std.fastdouble.FastDouble.fallbackToJavaParser(FastDouble.java:534)
	at io.questdb.std.fastdouble.FastDouble.valueOfFloatLiteral(FastDouble.java:524)
	at io.questdb.std.fastdouble.FastDouble.parseDecFloatLiteral(FastDouble.java:291)
	at io.questdb.std.fastdouble.FastDouble.parseFloatingPointLiteral(FastDouble.java:150)
	at io.questdb.std.fastdouble.FastDoubleParser.parseDouble(FastDoubleParser.java:83)
	at io.questdb.std.fastdouble.FastDoubleParser.parseDouble(FastDoubleParser.java:50)
	at io.questdb.std.Numbers.parseDouble(Numbers.java:606)
	at io.questdb.griffin.engine.functions.cast.CastStrToDoubleFunctionFactory$Func.getDouble(CastStrToDoubleFunctionFactory.java:72)
	at io.questdb.griffin.engine.functions.groupby.AvgDoubleGroupByFunction.computeFirst(AvgDoubleGroupByFunction.java:49)
	at io.questdb.griffin.engine.groupby.GroupByUtils.updateNew(GroupByUtils.java:271)
	at io.questdb.griffin.engine.groupby.GroupByUtils.updateFunctions(GroupByUtils.java:370)
	at io.questdb.griffin.engine.groupby.SampleByFillNoneRecordCursor.hasNext(SampleByFillNoneRecordCursor.java:107)
	at io.questdb.cutlass.http.processors.JsonQueryProcessorState.doQueryNextRecord(JsonQueryProcessorState.java:483)
	at io.questdb.cutlass.http.processors.JsonQueryProcessorState.doRecordFetchLoop(JsonQueryProcessorState.java:642)
	at io.questdb.cutlass.http.processors.JsonQueryProcessorState.doFirstRecordLoop(JsonQueryProcessorState.java:443)
	at io.questdb.cutlass.http.processors.JsonQueryProcessorState.onQueryPrefix(JsonQueryProcessorState.java:755)
	at io.questdb.cutlass.http.processors.JsonQueryProcessorState.resume(JsonQueryProcessorState.java:815)
	at io.questdb.cutlass.http.processors.JsonQueryProcessor.doResumeSend(JsonQueryProcessor.java:269)
	at io.questdb.cutlass.http.processors.JsonQueryProcessor.executeSelect(JsonQueryProcessor.java:530)
	at io.questdb.cutlass.http.processors.JsonQueryProcessor.executeNewSelect(JsonQueryProcessor.java:515)
	at io.questdb.cutlass.http.processors.JsonQueryProcessor.compileQuery(JsonQueryProcessor.java:338)
	at io.questdb.cutlass.http.processors.JsonQueryProcessor.execute0(JsonQueryProcessor.java:182)
	at io.questdb.cutlass.http.processors.JsonQueryProcessor.onRequestComplete(JsonQueryProcessor.java:229)
	at io.questdb.cutlass.http.HttpConnectionContext.handleClientRecv(HttpConnectionContext.java:574)
	at io.questdb.cutlass.http.HttpConnectionContext.handleClientOperation(HttpConnectionContext.java:241)
	at io.questdb.cutlass.http.HttpServer$1.lambda$$0(HttpServer.java:96)
	at io.questdb.network.AbstractIODispatcher.processIOQueue(AbstractIODispatcher.java:181)
	at io.questdb.cutlass.http.HttpServer$1.run(HttpServer.java:108)
	at io.questdb.mp.Worker.run(Worker.java:118)
```

### To reproduce

hard to do with out our data:)

### Expected Behavior

_No response_

### Environment

```markdown
QuestDB server 6.5.4-SNAPSHOT
Windows 
Chrome
```

### Additional context

If we just could get an explanation on the exception that trow this it would be help full.

### PR DESCRIPTION
**Pull request by jerrinot**
fixes #2677

### CODE REVIEW

**Comment by ideoma** [comment]
#### [PR Coverage check]

:heart_eyes: **pass** : 2 / 2 (100.00%)




#### file detail

|   |path|covered line|new line|coverage|
|----|----|----|----|----|
|:large_blue_circle:|io/questdb/std/str/AbstractCharSequence.java|2|2|100.00%|

**Comment by bluestreak01** [comment]
there is a room for optimisation in the existing `subSequence()` implementations

**Comment by bluestreak01** [comment]
@jerrinot thanks, this is what I had in mind.

As far as PR title, it should be read from the database user perspective, not perspective of hardcore developer, who has context of database implementation.

**Comment by bluestreak01** [comment]
hardcore comment can be left in PR description :)

**Comment by ideoma** [comment]
#### [PR Coverage check]

:heart_eyes: **pass** : 5 / 5 (100.00%)




#### file detail

|   |path|covered line|new line|coverage|
|----|----|----|----|----|
|:large_blue_circle:|io/questdb/std/str/AbstractCharSequence.java|4|4|100.00%|
|:large_blue_circle:|io/questdb/std/str/DirectByteCharSequence.java|1|1|100.00%|

**Comment by jerrinot** [comment]
I simplified it a bit, but I consider the title to be already quite user centric.

**Review by bluestreak01 — APPROVED** [review]

**Pull request merged**
