### PR TITLE
chore(sql): speed up sequential reads via io_uring in parallel import

### PR DESCRIPTION
**Pull request by puzpuzpuz**
Adds coalescing of near by lines for io_uring-based file reads using in parallel SQL COPY's phase 3. This improves import execution time for the case of in-order CSV files (see some numbers below as an example).

Also includes an important bugfix for the io_uring-based import: io_uring specific code was loosing each 33rd row from the index file during phase 3. This patch makes sure that in-flight read operations are consumed before attempting to add a new one.

### In-order file import performance improvement

138GB CSV file with in-order data; Linux machine with Ubuntu 20.04 x64, NVMe SSD, 8 HT cores, 32GB RAM

Import execution time:
```
2022-07-22T11:30:35.986443Z I i.q.c.t.ParallelCsvFileImporter import complete [file='all_types.csv', time=1247s]
```

Same, but with `cairo.iouring.enabled=false`:
```
2022-07-22T11:44:34.099300Z I i.q.c.t.ParallelCsvFileImporter import complete [file='all_types.csv', time=716s]
```

Same, but with enabled io_uring and this patch:
```
2022-07-23T06:29:24.380238Z I i.q.c.t.ParallelCsvFileImporter import complete [file='all_types.csv', time=698s]
```

### CODE REVIEW

**Comment by ideoma** [comment]
#### [PR Coverage check]

:heart_eyes: **pass** : 44 / 47 (93.62%)




#### file detail

|   |path|covered line|new line|coverage|
|----|----|----|----|----|
|:large_blue_circle:|io/questdb/cutlass/text/TextImportTask.java|44|47|93.62%|

**Comment by ideoma** [comment]
#### [PR Coverage check]

:heart_eyes: **pass** : 44 / 47 (93.62%)




#### file detail

|   |path|covered line|new line|coverage|
|----|----|----|----|----|
|:large_blue_circle:|io/questdb/cutlass/text/TextImportTask.java|44|47|93.62%|

**Comment by ideoma** [comment]
#### [PR Coverage check]

:heart_eyes: **pass** : 44 / 47 (93.62%)




#### file detail

|   |path|covered line|new line|coverage|
|----|----|----|----|----|
|:large_blue_circle:|io/questdb/cutlass/text/TextImportTask.java|44|47|93.62%|

**Comment by bluestreak01** [comment]
I do not have Linux machine until Monday. What is test coverage around io uring? 3 lines seem to be missing, I’m not yet sure where

**Comment by puzpuzpuz** [comment]
> I do not have Linux machine until Monday. What is test coverage around io uring? 3 lines seem to be missing, I’m not yet sure where

The following lines are still uncovered after the changes from this PR:
https://github.com/questdb/questdb/blob/792cca6fea2fc2a153940dabae690f4c669a3304/core/src/main/java/io/questdb/cutlass/text/TextImportTask.java#L991-L993 (`ff.length()`'s error - doesn't seem to be critical)
https://github.com/questdb/questdb/blob/792cca6fea2fc2a153940dabae690f4c669a3304/core/src/main/java/io/questdb/cutlass/text/TextImportTask.java#L894 (`Os.pause()` on `!ring.nextCqe()` - doesn't seem to be critical too)
https://github.com/questdb/questdb/blob/792cca6fea2fc2a153940dabae690f4c669a3304/core/src/main/java/io/questdb/cutlass/text/TextImportTask.java#L913 (out-of-order cqe handling in `consumeURing` - impossible to cover without some complicated mockery)

Which ones we should cover in your opinion?

**Comment by bluestreak01** [comment]
there is test `testImportURingShuffleCqe()`, which shuffles CQEs. On `master` this test is able to submit multiple SQEs, have shuffling code to work and test that CQEs can be consumed unordered. On this branch it seems that only one SQE is submitted at all times, shuffling code is a no-op and unordered CQE pickup is not covered by test

**Comment by puzpuzpuz** [comment]
> there is test `testImportURingShuffleCqe()`, which shuffles CQEs

Updated the test to use out-of-order CSV file in 4a9f9a14ce2224a1109440117b04f9e6ffdc6646. Also includes some minor renaming.

**Comment by ideoma** [comment]
#### [PR Coverage check]

:heart_eyes: **pass** : 45 / 47 (95.74%)




#### file detail

|   |path|covered line|new line|coverage|
|----|----|----|----|----|
|:large_blue_circle:|io/questdb/cutlass/text/TextImportTask.java|45|47|95.74%|

**Review by bluestreak01 — APPROVED** [review]

**Pull request merged**
