### PR TITLE
Implement logarithm function

### PR DESCRIPTION
**Pull request by mrecht**
Implement math log function.

### CODE REVIEW

**Review by bluestreak01 — CHANGES_REQUESTED** [review]

**Review by mrecht — COMMENTED** [review]
use vlad's comments

**Review by mrecht — COMMENTED** [review]
use changes

**Comment by bluestreak01** [comment]
doesn't compile :( I still have to provide example of tests. Crazy day today. Sorry for the delay!

**Review by ideoma — CHANGES_REQUESTED** [review]

**Comment by bluestreak01** [comment]
I cleaned up conflicts and tests, but could not commit to Mark's fork. So there is new PR #1050 based on Mark's contribution, thank you Mark 👍

**Pull request closed without merging**
