### PR TITLE
feat(net): automatically derive io dispatcher configuration from a single parameter

### PR DESCRIPTION
**Pull request by bluestreak01**
## Motivation

`IODispatcher` has multiple parameters that needed coordinated change if user is to change `active connection limit`. This was impractical and error-prone. Changing one parameter without changing other could lead to unstable runtime. Knowing right values implied digging thru the source code.

## Outcome

User changes `active connection limit` and all other necessary parameters automatically updated for stable performance. These parameters are now removed from the configuration.

## Fixes

- fixed https://github.com/questdb/questdb/issues/1775 test to work reliably without getting stuck on either backlog randomness or connect timeouts. As Bolek pointed out, while we are calculating TCP backlog size from max connection, OS in fact has a limit of its own. This limit varies from one OS to another.
- fixed `IODispatcherOsx` to use unique and consistently incrementing descriptor IDs

### CODE REVIEW

**Comment by ideoma** [comment]
#### [PR Coverage check]

:heart_eyes: **pass** : 15 / 17 (88.24%)




#### file detail

|   |path|covered line|new line|coverage|
|----|----|----|----|----|
|:large_blue_circle:|io/questdb/network/IODispatcherConfiguration.java|5|7|71.43%|
|:large_blue_circle:|io/questdb/PropServerConfiguration.java|10|10|100.00%|

**Comment by ideoma** [comment]
#### [PR Coverage check]

:heart_eyes: **pass** : 15 / 17 (88.24%)




#### file detail

|   |path|covered line|new line|coverage|
|----|----|----|----|----|
|:large_blue_circle:|io/questdb/network/IODispatcherConfiguration.java|5|7|71.43%|
|:large_blue_circle:|io/questdb/PropServerConfiguration.java|10|10|100.00%|

**Comment by ideoma** [comment]
#### [PR Coverage check]

:heart_eyes: **pass** : 15 / 17 (88.24%)




#### file detail

|   |path|covered line|new line|coverage|
|----|----|----|----|----|
|:large_blue_circle:|io/questdb/network/IODispatcherConfiguration.java|5|7|71.43%|
|:large_blue_circle:|io/questdb/PropServerConfiguration.java|10|10|100.00%|

**Comment by ideoma** [comment]
#### [PR Coverage check]

:heart_eyes: **pass** : 21 / 34 (61.76%)




#### file detail

|   |path|covered line|new line|coverage|
|----|----|----|----|----|
|:large_blue_circle:|io/questdb/network/IODispatcherOsx.java|0|11|00.00%|
|:large_blue_circle:|io/questdb/network/IODispatcherConfiguration.java|5|7|71.43%|
|:large_blue_circle:|io/questdb/PropServerConfiguration.java|10|10|100.00%|
|:large_blue_circle:|io/questdb/network/AbstractIODispatcher.java|6|6|100.00%|

**Comment by ideoma** [comment]
#### [PR Coverage check]

:heart_eyes: **pass** : 21 / 34 (61.76%)




#### file detail

|   |path|covered line|new line|coverage|
|----|----|----|----|----|
|:large_blue_circle:|io/questdb/network/IODispatcherOsx.java|0|11|00.00%|
|:large_blue_circle:|io/questdb/network/IODispatcherConfiguration.java|5|7|71.43%|
|:large_blue_circle:|io/questdb/PropServerConfiguration.java|10|10|100.00%|
|:large_blue_circle:|io/questdb/network/AbstractIODispatcher.java|6|6|100.00%|

**Comment by ideoma** [comment]
#### [PR Coverage check]

:heart_eyes: **pass** : 21 / 34 (61.76%)




#### file detail

|   |path|covered line|new line|coverage|
|----|----|----|----|----|
|:large_blue_circle:|io/questdb/network/IODispatcherOsx.java|0|11|00.00%|
|:large_blue_circle:|io/questdb/network/IODispatcherConfiguration.java|5|7|71.43%|
|:large_blue_circle:|io/questdb/PropServerConfiguration.java|10|10|100.00%|
|:large_blue_circle:|io/questdb/network/AbstractIODispatcher.java|6|6|100.00%|

**Comment by ideoma** [comment]
#### [PR Coverage check]

:heart_eyes: **pass** : 21 / 34 (61.76%)




#### file detail

|   |path|covered line|new line|coverage|
|----|----|----|----|----|
|:large_blue_circle:|io/questdb/network/IODispatcherOsx.java|0|11|00.00%|
|:large_blue_circle:|io/questdb/network/IODispatcherConfiguration.java|5|7|71.43%|
|:large_blue_circle:|io/questdb/PropServerConfiguration.java|10|10|100.00%|
|:large_blue_circle:|io/questdb/network/AbstractIODispatcher.java|6|6|100.00%|

**Comment by ideoma** [comment]
#### [PR Coverage check]

:heart_eyes: **pass** : 21 / 34 (61.76%)




#### file detail

|   |path|covered line|new line|coverage|
|----|----|----|----|----|
|:large_blue_circle:|io/questdb/network/IODispatcherOsx.java|0|11|00.00%|
|:large_blue_circle:|io/questdb/network/IODispatcherConfiguration.java|5|7|71.43%|
|:large_blue_circle:|io/questdb/PropServerConfiguration.java|10|10|100.00%|
|:large_blue_circle:|io/questdb/network/AbstractIODispatcher.java|6|6|100.00%|

**Comment by ideoma** [comment]
#### [PR Coverage check]

:heart_eyes: **pass** : 21 / 34 (61.76%)




#### file detail

|   |path|covered line|new line|coverage|
|----|----|----|----|----|
|:large_blue_circle:|io/questdb/network/IODispatcherOsx.java|0|11|00.00%|
|:large_blue_circle:|io/questdb/network/IODispatcherConfiguration.java|5|7|71.43%|
|:large_blue_circle:|io/questdb/PropServerConfiguration.java|10|10|100.00%|
|:large_blue_circle:|io/questdb/network/AbstractIODispatcher.java|6|6|100.00%|

**Review by bziobrowski — APPROVED** [review]
Looks good . 
It might be worth mentioning that tcp backlog is truncated to /proc/sys/net/ipv4/tcp_max_syn_backlog on Linux but that is rather well documented .

**Pull request merged**
