### PR TITLE
fix(test): fixed WriterPoolTest.testGetAndCloseRace()

### LINKED ISSUE #1513: Flaky WriterPoolTest.testGetAndCloseRace test
### Describe the bug

`WriterPoolTest` fails infrequently (3 runs out of ~300):
```
2021-11-03T13:27:00.338825Z E i.q.TestListener ***** Test Failed *****io.questdb.cairo.pool.WriterPoolTest.testGetAndCloseRace : 
java.lang.AssertionError: expected:<2> but was:<8>
	at org.junit.Assert.fail(Assert.java:89)
	at org.junit.Assert.failNotEquals(Assert.java:835)
	at org.junit.Assert.assertEquals(Assert.java:647)
	at org.junit.Assert.assertEquals(Assert.java:633)
	at io.questdb.test.tools.TestUtils.assertMemoryLeak(TestUtils.java:389)
	at io.questdb.cairo.pool.WriterPoolTest.assertWithPool(WriterPoolTest.java:764)
	at io.questdb.cairo.pool.WriterPoolTest.assertWithPool(WriterPoolTest.java:772)
	at io.questdb.cairo.pool.WriterPoolTest.testGetAndCloseRace(WriterPoolTest.java:264)
```
https://dev.azure.com/questdb/questdb/_build/results?buildId=3257&view=logs&j=e0a155a9-5858-51f3-7a0d-fdfd007d5c7f&t=bdb03b31-3467-53ab-ff1a-f5b57273bbae&l=62862

### To reproduce

_No response_

### Expected Behavior

_No response_

### Environment

```markdown
- **QuestDB version**:
- **OS**:
- **Browser**:
```

### Additional context

_No response_

### PR DESCRIPTION
**Pull request by bluestreak01**
Closes #1513

### CODE REVIEW

**Comment by ideoma** [comment]
#### [PR Coverage check]

:heart_eyes: **pass** : 5 / 5 (100.00%)




#### file detail

|   |path|covered line|new line|coverage|
|----|----|----|----|----|
|:large_blue_circle:|io/questdb/cairo/pool/WriterPool.java|5|5|100.00%|

**Comment by ideoma** [comment]
#### [PR Coverage check]

:heart_eyes: **pass** : 5 / 5 (100.00%)




#### file detail

|   |path|covered line|new line|coverage|
|----|----|----|----|----|
|:large_blue_circle:|io/questdb/cairo/pool/WriterPool.java|5|5|100.00%|

**Comment by ideoma** [comment]
#### [PR Coverage check]

:heart_eyes: **pass** : 5 / 5 (100.00%)




#### file detail

|   |path|covered line|new line|coverage|
|----|----|----|----|----|
|:large_blue_circle:|io/questdb/cairo/pool/WriterPool.java|5|5|100.00%|

**Comment by ideoma** [comment]
#### [PR Coverage check]

:heart_eyes: **pass** : 5 / 5 (100.00%)




#### file detail

|   |path|covered line|new line|coverage|
|----|----|----|----|----|
|:large_blue_circle:|io/questdb/cairo/pool/WriterPool.java|5|5|100.00%|

**Comment by ideoma** [comment]
#### [PR Coverage check]

:heart_eyes: **pass** : 5 / 5 (100.00%)




#### file detail

|   |path|covered line|new line|coverage|
|----|----|----|----|----|
|:large_blue_circle:|io/questdb/cairo/pool/WriterPool.java|5|5|100.00%|

**Comment by ideoma** [comment]
#### [PR Coverage check]

:heart_eyes: **pass** : 5 / 5 (100.00%)




#### file detail

|   |path|covered line|new line|coverage|
|----|----|----|----|----|
|:large_blue_circle:|io/questdb/cairo/pool/WriterPool.java|5|5|100.00%|

**Review by puzpuzpuz — APPROVED** [review]

**Pull request merged**
