### PR TITLE
perf(sql): use StringBuilder instead of StringBuffer when possible in regexp_replace

### PR DESCRIPTION
**Pull request by puzpuzpuz**
Considering that biased locking was removed from OpenJDK, `StringBuffer` became noticeably more expensive than before. On my machine, this change cut down the `regexp_replace` query in ClickBench by ~20 seconds.

Also includes the following changes:
* Fixes no entry values in integer `Compact*HashSet` used in `count_distinct()` functions. The default value was -1 which led to incorrect results
* `CompactCharSequenceHashSet` no longer inherits from `AbstractCharSequenceHashSet`. That's to be able to use `String[]` array to store the keys and use `String#hashCode()` (which is cached) when comparing keys

### CODE REVIEW

**Comment by ideoma** [comment]
#### [PR Coverage check]

:heart_eyes: **pass** : 43 / 45 (95.56%)




#### file detail

|   |path|covered line|new line|coverage|
|----|----|----|----|----|
|:large_blue_circle:|io/questdb/std/CompactCharSequenceHashSet.java|27|29|93.10%|
|:large_blue_circle:|io/questdb/griffin/engine/functions/groupby/CountDistinctUuidGroupByFunction.java|1|1|100.00%|
|:large_blue_circle:|io/questdb/std/CompactLongHashSet.java|1|1|100.00%|
|:large_blue_circle:|io/questdb/griffin/engine/functions/groupby/CountDistinctStringGroupByFunction.java|1|1|100.00%|
|:large_blue_circle:|io/questdb/griffin/engine/functions/regex/RegexpReplaceStrFunctionFactory.java|4|4|100.00%|
|:large_blue_circle:|io/questdb/std/AbstractLongHashSet.java|4|4|100.00%|
|:large_blue_circle:|io/questdb/griffin/engine/functions/groupby/CountDistinctSymbolGroupByFunction.java|1|1|100.00%|
|:large_blue_circle:|io/questdb/std/CompactIntHashSet.java|1|1|100.00%|
|:large_blue_circle:|io/questdb/griffin/engine/functions/groupby/CountDistinctIPv4GroupByFunction.java|1|1|100.00%|
|:large_blue_circle:|io/questdb/griffin/engine/functions/groupby/CountDistinctLongGroupByFunction.java|1|1|100.00%|
|:large_blue_circle:|io/questdb/griffin/engine/functions/groupby/CountDistinctIntGroupByFunction.java|1|1|100.00%|

**Review by jerrinot — APPROVED** [review]

**Comment by puzpuzpuz** [comment]
@jerrinot sorry, my last minute changes dismissed your review. :(

I've pushed a few tests for the compact hash set fix here: 49d6f07448104be193e870062427bbae2fc78c74
Could you take a look and re-approve?

**Comment by ideoma** [comment]
#### [PR Coverage check]

:heart_eyes: **pass** : 43 / 45 (95.56%)




#### file detail

|   |path|covered line|new line|coverage|
|----|----|----|----|----|
|:large_blue_circle:|io/questdb/std/CompactCharSequenceHashSet.java|27|29|93.10%|
|:large_blue_circle:|io/questdb/griffin/engine/functions/groupby/CountDistinctUuidGroupByFunction.java|1|1|100.00%|
|:large_blue_circle:|io/questdb/std/CompactLongHashSet.java|1|1|100.00%|
|:large_blue_circle:|io/questdb/griffin/engine/functions/groupby/CountDistinctStringGroupByFunction.java|1|1|100.00%|
|:large_blue_circle:|io/questdb/griffin/engine/functions/regex/RegexpReplaceStrFunctionFactory.java|4|4|100.00%|
|:large_blue_circle:|io/questdb/std/AbstractLongHashSet.java|4|4|100.00%|
|:large_blue_circle:|io/questdb/griffin/engine/functions/groupby/CountDistinctSymbolGroupByFunction.java|1|1|100.00%|
|:large_blue_circle:|io/questdb/std/CompactIntHashSet.java|1|1|100.00%|
|:large_blue_circle:|io/questdb/griffin/engine/functions/groupby/CountDistinctIPv4GroupByFunction.java|1|1|100.00%|
|:large_blue_circle:|io/questdb/griffin/engine/functions/groupby/CountDistinctLongGroupByFunction.java|1|1|100.00%|
|:large_blue_circle:|io/questdb/griffin/engine/functions/groupby/CountDistinctIntGroupByFunction.java|1|1|100.00%|

**Review by jerrinot — APPROVED** [review]

**Comment by puzpuzpuz** [comment]
@jerrinot thanks for the snappy review!

**Pull request merged**
