### PR TITLE
chore(ui): fix keyboard shortcuts

### PR DESCRIPTION
**Pull request by insmac**
Fix `F9` and `CMD`+`Enter` shortcuts that are broken due to typos.

### CODE REVIEW

**Review by bluestreak01 — CHANGES_REQUESTED** [review]
I don't understand, shortcuts work, but we regressed toasters ?

image

**Comment by bluestreak01** [comment]
it looks like i had a 6.1.1 running, not master, but still odd that UI looks like this

**Review by bluestreak01 — APPROVED** [review]

**Comment by insmac** [comment]
@bluestreak01 This seems to be a very old version of the web console, the logo is different, settings icon is missing on the left, etc. Not sure how it got there

**Comment by bluestreak01** [comment]
do you mind downloading 6.1.1 and checking ?

**Pull request merged**
