### PR TITLE
fix(core): prevent server deadlock when logging too many errors

### PR DESCRIPTION
**Pull request by ideoma**
Make error logging non-waiting, as it used to be before.
Too many waited error message can occasionally deadlock worker threads on low CPU boxes. This can lead to incidents where the server is deadlocked with no logs written.

### CODE REVIEW

**Comment by ideoma** [comment]
#### [PR Coverage check]

:heart_eyes: **pass** : 1 / 1 (100.00%)




#### file detail

|   |path|covered line|new line|coverage|
|----|----|----|----|----|
|:large_blue_circle:|io/questdb/log/Logger.java|1|1|100.00%|

**Comment by ideoma** [comment]
#### [PR Coverage check]

:heart_eyes: **pass** : 1 / 1 (100.00%)




#### file detail

|   |path|covered line|new line|coverage|
|----|----|----|----|----|
|:large_blue_circle:|io/questdb/log/Logger.java|1|1|100.00%|

**Comment by ideoma** [comment]
#### [PR Coverage check]

:heart_eyes: **pass** : 3 / 5 (60.00%)




#### file detail

|   |path|covered line|new line|coverage|
|----|----|----|----|----|
|:large_blue_circle:|io/questdb/mp/Worker.java|1|3|33.33%|
|:large_blue_circle:|io/questdb/log/LogFactory.java|1|1|100.00%|
|:large_blue_circle:|io/questdb/log/Logger.java|1|1|100.00%|

**Comment by ideoma** [comment]
#### [PR Coverage check]

:heart_eyes: **pass** : 10 / 13 (76.92%)




#### file detail

|   |path|covered line|new line|coverage|
|----|----|----|----|----|
|:large_blue_circle:|io/questdb/mp/Worker.java|8|11|72.73%|
|:large_blue_circle:|io/questdb/log/LogFactory.java|1|1|100.00%|
|:large_blue_circle:|io/questdb/log/Logger.java|1|1|100.00%|

**Review by bluestreak01 — APPROVED** [review]

**Pull request merged**
