### PR TITLE
feat(ilp): allow users to change default column type when ILP adds new column automatically

### PR DESCRIPTION
**Pull request by glasstiger**
When a new column is added on the fly via ILP ingestion QuestDB decides on the type of the field.
In case of a floating point value we chose to use DOUBLE, for integers we picked LONG.
It makes sense to use the largest types by default as we do not know what range of values will be inserted into the field.
However, if the user knows that they do not require double precision or that the range of integer values could fit in a SHORT, for example, they should have the option to configure which type should be used for new columns.
This helps to save disk space as they can avoid using 64-bit types where 32-bit or even smaller types could suffice.
This PR adds the config options to be able to override the default add column types.

Example config:
```
# possible values: DOUBLE, FLOAT
# default is DOUBLE
line.float.default.column.type=FLOAT

# possible values: LONG, INT, SHORT, BYTE
# default is LONG
line.integer.default.column.type=INT
```

Outstanding:
- documentation update
- follow up PR to send the actual column type to the writer instead of the ILP entity type

### CODE REVIEW

**Comment by ideoma** [comment]
#### [PR Coverage check]

:heart_eyes: **pass** : 63 / 69 (91.30%)




#### file detail

|   |path|covered line|new line|coverage|
|----|----|----|----|----|
|:large_blue_circle:|io/questdb/PropServerConfiguration.java|8|14|57.14%|
|:large_blue_circle:|io/questdb/cutlass/line/tcp/LineTcpMeasurementScheduler.java|4|4|100.00%|
|:large_blue_circle:|io/questdb/cutlass/line/tcp/DefaultColumnTypes.java|23|23|100.00%|
|:large_blue_circle:|io/questdb/PropertyKey.java|2|2|100.00%|
|:large_blue_circle:|io/questdb/cutlass/line/udp/LineUdpParserSupport.java|4|4|100.00%|
|:large_blue_circle:|io/questdb/cutlass/line/udp/LineUdpParserImpl.java|12|12|100.00%|
|:large_blue_circle:|io/questdb/cutlass/line/udp/DefaultLineUdpReceiverConfiguration.java|2|2|100.00%|
|:large_blue_circle:|io/questdb/cutlass/line/tcp/TableStructureAdapter.java|3|3|100.00%|
|:large_blue_circle:|io/questdb/cutlass/line/tcp/DefaultLineTcpReceiverConfiguration.java|2|2|100.00%|
|:large_blue_circle:|io/questdb/cutlass/line/tcp/LineTcpMeasurementEvent.java|3|3|100.00%|

**Comment by ideoma** [comment]
#### [PR Coverage check]

:heart_eyes: **pass** : 67 / 69 (97.10%)




#### file detail

|   |path|covered line|new line|coverage|
|----|----|----|----|----|
|:large_blue_circle:|io/questdb/PropServerConfiguration.java|12|14|85.71%|
|:large_blue_circle:|io/questdb/cutlass/line/tcp/LineTcpMeasurementScheduler.java|4|4|100.00%|
|:large_blue_circle:|io/questdb/cutlass/line/tcp/DefaultColumnTypes.java|23|23|100.00%|
|:large_blue_circle:|io/questdb/PropertyKey.java|2|2|100.00%|
|:large_blue_circle:|io/questdb/cutlass/line/udp/LineUdpParserSupport.java|4|4|100.00%|
|:large_blue_circle:|io/questdb/cutlass/line/udp/LineUdpParserImpl.java|12|12|100.00%|
|:large_blue_circle:|io/questdb/cutlass/line/udp/DefaultLineUdpReceiverConfiguration.java|2|2|100.00%|
|:large_blue_circle:|io/questdb/cutlass/line/tcp/TableStructureAdapter.java|3|3|100.00%|
|:large_blue_circle:|io/questdb/cutlass/line/tcp/DefaultLineTcpReceiverConfiguration.java|2|2|100.00%|
|:large_blue_circle:|io/questdb/cutlass/line/tcp/LineTcpMeasurementEvent.java|3|3|100.00%|

**Comment by ideoma** [comment]
#### [PR Coverage check]

:heart_eyes: **pass** : 66 / 68 (97.06%)




#### file detail

|   |path|covered line|new line|coverage|
|----|----|----|----|----|
|:large_blue_circle:|io/questdb/PropServerConfiguration.java|12|14|85.71%|
|:large_blue_circle:|io/questdb/cutlass/line/tcp/LineTcpMeasurementScheduler.java|4|4|100.00%|
|:large_blue_circle:|io/questdb/cutlass/line/tcp/DefaultColumnTypes.java|22|22|100.00%|
|:large_blue_circle:|io/questdb/PropertyKey.java|2|2|100.00%|
|:large_blue_circle:|io/questdb/cutlass/line/udp/LineUdpParserSupport.java|4|4|100.00%|
|:large_blue_circle:|io/questdb/cutlass/line/udp/LineUdpParserImpl.java|12|12|100.00%|
|:large_blue_circle:|io/questdb/cutlass/line/udp/DefaultLineUdpReceiverConfiguration.java|2|2|100.00%|
|:large_blue_circle:|io/questdb/cutlass/line/tcp/TableStructureAdapter.java|3|3|100.00%|
|:large_blue_circle:|io/questdb/cutlass/line/tcp/DefaultLineTcpReceiverConfiguration.java|2|2|100.00%|
|:large_blue_circle:|io/questdb/cutlass/line/tcp/LineTcpMeasurementEvent.java|3|3|100.00%|

**Review by bluestreak01 — APPROVED** [review]

**Comment by ideoma** [comment]
#### [PR Coverage check]

:heart_eyes: **pass** : 66 / 68 (97.06%)




#### file detail

|   |path|covered line|new line|coverage|
|----|----|----|----|----|
|:large_blue_circle:|io/questdb/PropServerConfiguration.java|12|14|85.71%|
|:large_blue_circle:|io/questdb/cutlass/line/tcp/LineTcpMeasurementScheduler.java|4|4|100.00%|
|:large_blue_circle:|io/questdb/cutlass/line/tcp/DefaultColumnTypes.java|22|22|100.00%|
|:large_blue_circle:|io/questdb/PropertyKey.java|2|2|100.00%|
|:large_blue_circle:|io/questdb/cutlass/line/udp/LineUdpParserSupport.java|4|4|100.00%|
|:large_blue_circle:|io/questdb/cutlass/line/udp/LineUdpParserImpl.java|12|12|100.00%|
|:large_blue_circle:|io/questdb/cutlass/line/udp/DefaultLineUdpReceiverConfiguration.java|2|2|100.00%|
|:large_blue_circle:|io/questdb/cutlass/line/tcp/TableStructureAdapter.java|3|3|100.00%|
|:large_blue_circle:|io/questdb/cutlass/line/tcp/DefaultLineTcpReceiverConfiguration.java|2|2|100.00%|
|:large_blue_circle:|io/questdb/cutlass/line/tcp/LineTcpMeasurementEvent.java|3|3|100.00%|

**Pull request merged**
