### PR TITLE
feat(metrics): framework for exposing metrics to Prometheus

### PR DESCRIPTION
**Pull request by piotrrzysko**
In this PR I would like to introduce the framework for gathering and exposing metrics to Prometheus.  This is the first step to implement the functionality described in #532. 

The PR adds support for:
* counters with 0-2 [labels](https://prometheus.io/docs/concepts/data_model/#metric-names-and-labels) 
* gauges without labels
* endpoint exposing metrics in [Prometheus format ](https://prometheus.io/docs/instrumenting/exposition_formats/)- I added it as a part of the min HTTP server and I am wondering if it is ok for you as it requires a change of the contract described in [the documentation](https://questdb.io/docs/operations/health-monitoring#usage).

Currently, there is only one metric available (counter of JSON queries) as I wanted to receive early feedback from you about    the framework. In the next iterations, I’m going to add more metrics and perhaps the support for histograms to expose timings. 

Also, I’ve compared the performance of the implementation of counter/gauge from the PR with the official Prometheus client. Here is the result of the benchmarks on my laptop:

The PR:
```
Benchmark                                                      Mode  Cnt   Score    Error   Units
MetricsBenchmark.testCounterWithOneLabel                       avgt    5   7,504 ±  0,285   ns/op
MetricsBenchmark.testCounterWithOneLabel:·gc.alloc.rate        avgt    5  ≈ 10⁻⁴           MB/sec
MetricsBenchmark.testCounterWithOneLabel:·gc.alloc.rate.norm   avgt    5  ≈ 10⁻⁶             B/op
MetricsBenchmark.testCounterWithOneLabel:·gc.count             avgt    5     ≈ 0           counts
MetricsBenchmark.testCounterWithTwoLabels                      avgt    5   7,822 ±  1,423   ns/op
MetricsBenchmark.testCounterWithTwoLabels:·gc.alloc.rate       avgt    5  ≈ 10⁻⁴           MB/sec
MetricsBenchmark.testCounterWithTwoLabels:·gc.alloc.rate.norm  avgt    5  ≈ 10⁻⁶             B/op
MetricsBenchmark.testCounterWithTwoLabels:·gc.count            avgt    5     ≈ 0           counts
MetricsBenchmark.testCounterWithoutLabels                      avgt    5   7,458 ±  0,075   ns/op
MetricsBenchmark.testCounterWithoutLabels:·gc.alloc.rate       avgt    5  ≈ 10⁻⁴           MB/sec
MetricsBenchmark.testCounterWithoutLabels:·gc.alloc.rate.norm  avgt    5  ≈ 10⁻⁶             B/op
MetricsBenchmark.testCounterWithoutLabels:·gc.count            avgt    5     ≈ 0           counts
MetricsBenchmark.testGauge                                     avgt    5  15,094 ±  0,962   ns/op
MetricsBenchmark.testGauge:·gc.alloc.rate                      avgt    5  ≈ 10⁻⁴           MB/sec
MetricsBenchmark.testGauge:·gc.alloc.rate.norm                 avgt    5  ≈ 10⁻⁶             B/op
MetricsBenchmark.testGauge:·gc.count                           avgt    5     ≈ 0           counts
```

The official Prometheus client:
```
Benchmark                                                                              Mode  Cnt     Score      Error   Units
PrometheusSimpleClientBenchmark.testCounterWithOneLabel                                avgt    5    47,936 ±   25,932   ns/op
PrometheusSimpleClientBenchmark.testCounterWithOneLabel:·gc.alloc.rate                 avgt    5  6154,394 ± 3003,951  MB/sec
PrometheusSimpleClientBenchmark.testCounterWithOneLabel:·gc.alloc.rate.norm            avgt    5    80,000 ±    0,001    B/op
PrometheusSimpleClientBenchmark.testCounterWithOneLabel:·gc.churn.G1_Eden_Space        avgt    5  6168,366 ± 3063,321  MB/sec
PrometheusSimpleClientBenchmark.testCounterWithOneLabel:·gc.churn.G1_Eden_Space.norm   avgt    5    80,164 ±    1,410    B/op
PrometheusSimpleClientBenchmark.testCounterWithOneLabel:·gc.churn.G1_Old_Gen           avgt    5     0,011 ±    0,008  MB/sec
PrometheusSimpleClientBenchmark.testCounterWithOneLabel:·gc.churn.G1_Old_Gen.norm      avgt    5    ≈ 10⁻⁴               B/op
PrometheusSimpleClientBenchmark.testCounterWithOneLabel:·gc.count                      avgt    5   585,000             counts
PrometheusSimpleClientBenchmark.testCounterWithOneLabel:·gc.time                       avgt    5   499,000                 ms
PrometheusSimpleClientBenchmark.testCounterWithTwoLabels                               avgt    5    51,565 ±    8,362   ns/op
PrometheusSimpleClientBenchmark.testCounterWithTwoLabels:·gc.alloc.rate                avgt    5  5642,601 ±  937,680  MB/sec
PrometheusSimpleClientBenchmark.testCounterWithTwoLabels:·gc.alloc.rate.norm           avgt    5    80,000 ±    0,001    B/op
PrometheusSimpleClientBenchmark.testCounterWithTwoLabels:·gc.churn.G1_Eden_Space       avgt    5  5663,165 ±  863,405  MB/sec
PrometheusSimpleClientBenchmark.testCounterWithTwoLabels:·gc.churn.G1_Eden_Space.norm  avgt    5    80,302 ±    1,608    B/op
PrometheusSimpleClientBenchmark.testCounterWithTwoLabels:·gc.churn.G1_Old_Gen          avgt    5     0,011 ±    0,002  MB/sec
PrometheusSimpleClientBenchmark.testCounterWithTwoLabels:·gc.churn.G1_Old_Gen.norm     avgt    5    ≈ 10⁻⁴               B/op
PrometheusSimpleClientBenchmark.testCounterWithTwoLabels:·gc.count                     avgt    5   616,000             counts
PrometheusSimpleClientBenchmark.testCounterWithTwoLabels:·gc.time                      avgt    5   457,000                 ms
PrometheusSimpleClientBenchmark.testCounterWithoutLabels                               avgt    5    11,166 ±    1,474   ns/op
PrometheusSimpleClientBenchmark.testCounterWithoutLabels:·gc.alloc.rate                avgt    5    ≈ 10⁻⁴             MB/sec
PrometheusSimpleClientBenchmark.testCounterWithoutLabels:·gc.alloc.rate.norm           avgt    5    ≈ 10⁻⁶               B/op
PrometheusSimpleClientBenchmark.testCounterWithoutLabels:·gc.count                     avgt    5       ≈ 0             counts
PrometheusSimpleClientBenchmark.testGauge                                              avgt    5    21,225 ±    2,550   ns/op
PrometheusSimpleClientBenchmark.testGauge:·gc.alloc.rate                               avgt    5    ≈ 10⁻⁴             MB/sec
PrometheusSimpleClientBenchmark.testGauge:·gc.alloc.rate.norm                          avgt    5    ≈ 10⁻⁶               B/op
PrometheusSimpleClientBenchmark.testGauge:·gc.count                                    avgt    5       ≈ 0             counts
```

### CODE REVIEW

**Comment by bluestreak01** [comment]
Hi Piotr, 

First of all I'd like to apologise for the delay getting back to you. We've been overwhelmed with out-of-order release. Now things are settled a little and I would like to provide some feedback on your PR.

The PR is very helpful and thanks for being so thorough with the benchmark results. I would say that despite that your proposed solution is nearly 7x faster than prometheus client, if you take into context that we are just incrementing a counter here - 7 micros is super slow. I would expect counter increment should be in single digit nanosecond in ideal world :) 

QuestDB is generally executed by a pool of fixed threads. I would suggest the following approach:

- Each thread could have its own set of counters. When application updates these counters we'd effectively update thread-local, private data structure
- When Promethius polls the end-point - this is the time we can go around multiuple data structures and merge them together. Of course the assumption here that counter updates are much more frequent than poll invocations
- When you have multi-dimensional metric, I would suggest we have open-array system, e.g.  one-dimensional array[] where index is a function of `(x,y) -> x*block_size+y`

Please let me know what you think. Happy to discuss further!

**Review by piotrrzysko — COMMENTED** [review]
Thanks for the feedback! 

The benchmark result shows that the average time per operation is 7 nanoseconds, not 7 microseconds :). To make sure I interpret the JMH format correctly, I benchmarked the null implementation (I think that we can use it as a baseline): 
```
Benchmark                                             Mode  Cnt   Score    Error   Units
MetricsBenchmark.testNullCounter                      avgt    5   0,635 ±  0,080   ns/op
MetricsBenchmark.testNullCounter:·gc.alloc.rate       avgt    5  ≈ 10⁻⁴           MB/sec
MetricsBenchmark.testNullCounter:·gc.alloc.rate.norm  avgt    5  ≈ 10⁻⁷             B/op
MetricsBenchmark.testNullCounter:·gc.count            avgt    5     ≈ 0           counts
```

As far as I know, `java.util.concurrent.atomic.LongAdder` used in this PR is implemented in a similar way to what you described. But of course I can try to find out if replacing LongAdder with a custom implementation will improve performance :).

**Comment by bluestreak01** [comment]
thanks Piotr, I was referring to this bench from post above:
```
Benchmark                                                      Mode  Cnt   Score    Error   Units
MetricsBenchmark.testCounterWithOneLabel                       avgt    5   7,504 ±  0,285   ns/op
```

this is 7500 nanos, e.g. 7.5 micros :)

**Comment by piotrrzysko** [comment]
I see where the problem is. I had the locale set to pl-PL, where a comma is used to indicate the decimal place.

The results after switching to en-GB:
```
Benchmark                                                      Mode  Cnt   Score    Error   Units
MetricsBenchmark.testCounterWithOneLabel                       avgt    5   7.849 ±  0.760   ns/op
MetricsBenchmark.testCounterWithOneLabel:·gc.alloc.rate        avgt    5  ≈ 10⁻⁴           MB/sec
MetricsBenchmark.testCounterWithOneLabel:·gc.alloc.rate.norm   avgt    5  ≈ 10⁻⁶             B/op
MetricsBenchmark.testCounterWithOneLabel:·gc.count             avgt    5     ≈ 0           counts
MetricsBenchmark.testCounterWithTwoLabels                      avgt    5   7.597 ±  0.507   ns/op
MetricsBenchmark.testCounterWithTwoLabels:·gc.alloc.rate       avgt    5  ≈ 10⁻⁴           MB/sec
MetricsBenchmark.testCounterWithTwoLabels:·gc.alloc.rate.norm  avgt    5  ≈ 10⁻⁶             B/op
MetricsBenchmark.testCounterWithTwoLabels:·gc.count            avgt    5     ≈ 0           counts
MetricsBenchmark.testCounterWithoutLabels                      avgt    5   7.478 ±  0.067   ns/op
MetricsBenchmark.testCounterWithoutLabels:·gc.alloc.rate       avgt    5  ≈ 10⁻⁴           MB/sec
MetricsBenchmark.testCounterWithoutLabels:·gc.alloc.rate.norm  avgt    5  ≈ 10⁻⁶             B/op
MetricsBenchmark.testCounterWithoutLabels:·gc.count            avgt    5     ≈ 0           counts
MetricsBenchmark.testGauge                                     avgt    5  14.931 ±  0.097   ns/op
MetricsBenchmark.testGauge:·gc.alloc.rate                      avgt    5  ≈ 10⁻⁴           MB/sec
MetricsBenchmark.testGauge:·gc.alloc.rate.norm                 avgt    5  ≈ 10⁻⁶             B/op
MetricsBenchmark.testGauge:·gc.count                           avgt    5     ≈ 0           counts
MetricsBenchmark.testNullCounter                               avgt    5   0.552 ±  0.024   ns/op
MetricsBenchmark.testNullCounter:·gc.alloc.rate                avgt    5  ≈ 10⁻⁴           MB/sec
MetricsBenchmark.testNullCounter:·gc.alloc.rate.norm           avgt    5  ≈ 10⁻⁸             B/op
MetricsBenchmark.testNullCounter:·gc.count                     avgt    5     ≈ 0           counts
MetricsBenchmark.testNullGauge                                 avgt    5   0.549 ±  0.017   ns/op
MetricsBenchmark.testNullGauge:·gc.alloc.rate                  avgt    5  ≈ 10⁻⁴           MB/sec
MetricsBenchmark.testNullGauge:·gc.alloc.rate.norm             avgt    5  ≈ 10⁻⁸             B/op
MetricsBenchmark.testNullGauge:·gc.count                       avgt    5     ≈ 0           counts
```

**Comment by bluestreak01** [comment]
oh, sorry about the misunderstanding! Do you mind resolving conflicts to get the PR ready ?

**Comment by piotrrzysko** [comment]
I resolved conflicts. 

I am wondering about this comment:

> When you have multi-dimensional metric, I would suggest we have open-array system, e.g. one-dimensional array[] where index is a function of (x,y) -> x*block_size+y

I changed the implementation of class `CounterWithTwoLabelsImpl` to use this approach. Is that what you meant?

**Comment by bluestreak01** [comment]
Thanks Piotr! `CounterWithTwoLabelsImpl` is exactly what I meant. It could be even better if in code like:

```java
    counters[i * n + j] = new LongAdder();
```

`n` was power of 2 and `I*n + j` is replaceable with `(i << shl) + j'

**Comment by bluestreak01** [comment]
Apologies for the delay merging this! We're having trouble with test coverage pipeline running on forks. We're going to fix this soon and then merge!

**Comment by ideoma** [comment]
I created issue to the tool used to measure coverage on the PR. They seem to be quite responsive, perhaps they will suggest a solution soon.

https://github.com/naver/cover-checker/issues/36

**Comment by ideoma** [comment]
#### [PR Coverage check]


:heart_eyes: **pass** : 0 / 0 (0%)

**Comment by ideoma** [comment]
#### [PR Coverage check]

:heart_eyes: **pass** : 115 / 146 (78.77%)




#### file detail

|   |path|covered line|new line|coverage|
|----|----|----|----|----|
|:large_blue_circle:|io/questdb/ServerMain.java|0|5|00.00%|
|:large_blue_circle:|io/questdb/DefaultServerConfiguration.java|0|2|00.00%|
|:large_blue_circle:|io/questdb/metrics/DefaultMetricsConfiguration.java|0|2|00.00%|
|:large_blue_circle:|io/questdb/cutlass/http/HttpServer.java|0|2|00.00%|
|:large_blue_circle:|io/questdb/cutlass/http/processors/PrometheusMetricsProcessor.java|0|10|00.00%|
|:large_blue_circle:|io/questdb/metrics/NullCounter.java|3|5|60.00%|
|:large_blue_circle:|io/questdb/Metrics.java|7|11|63.64%|
|:large_blue_circle:|io/questdb/metrics/MetricsRegistryImpl.java|14|18|77.78%|
|:large_blue_circle:|io/questdb/PropServerConfiguration.java|3|3|100.00%|
|:large_blue_circle:|io/questdb/cutlass/http/processors/JsonQueryProcessor.java|4|4|100.00%|
|:large_blue_circle:|io/questdb/WorkerPoolAwareConfiguration.java|1|1|100.00%|
|:large_blue_circle:|io/questdb/cutlass/pgwire/PGWireServer.java|1|1|100.00%|
|:large_blue_circle:|io/questdb/metrics/GaugeImpl.java|20|20|100.00%|
|:large_blue_circle:|io/questdb/metrics/CounterWithOneLabelImpl.java|19|19|100.00%|
|:large_blue_circle:|io/questdb/metrics/CounterWithTwoLabelsImpl.java|27|27|100.00%|
|:large_blue_circle:|io/questdb/cutlass/http/processors/JsonQueryMetrics.java|5|5|100.00%|
|:large_blue_circle:|io/questdb/metrics/CounterImpl.java|11|11|100.00%|

**Review by bluestreak01 — APPROVED** [review]

**Pull request merged**
