### PR TITLE
feat(console): add timings + improve error messages

### PR DESCRIPTION
**Pull request by mpsq**
New timings:
2020-04-23-190447_grim

Better error messages:
2020-04-23-190459_grim

Default state:
2020-04-23-190440_grim

### CODE REVIEW

**Comment by mpsq** [comment]
Still WIP. This is to get some feedback.

**Comment by mpsq** [comment]
Still WIP. This is to get some feedback.

**Comment by bluestreak01** [comment]
Could you try to see what backup table error message looks like when backup is disabled?

**Comment by mpsq** [comment]
I added a `white-space` prop to the error message, it wraps nicely now:
2020-04-23-205932_grim

**Pull request merged**
