### PR TITLE
chore(core): add unbounded array based concurrent queue

### PR DESCRIPTION
**Pull request by ideoma**
Motivation:

We need a queue to notify our jobs about tasks to do. In current implementations, `RingQueue` is fixed size and we have to deal with "queue full" on the attempt to publish to it. Usually, it is work stealing but in some cases, we do not want to do work stealing to increase the throughput. A case like this can be a materialized view refresh notification, under pressure it is better to wait longer and refresh many commits in one go.

Adding additional workflow to handle `queue full` increases the complexity and it is error-prone because it is not easy to cover with the tests.

Implementation:

JDK concurrent queue implementation uses a Linked List data structure and does not allow reusing its slots.

This implementation is a stripped-down copy of .NET Core ConcurrentQueue class, available under MIT license. It uses multiple `ConcurrentQueueSegment` which are essentially Ring queues as low-level building blocks. In addition, it can resize the underlying ring queue by creating new, bigger instances when needed.

### CODE REVIEW

**Comment by ideoma** [comment]
#### [PR Coverage check]

:heart_eyes: **pass** : 88 / 93 (94.62%)




#### file detail

|   |path|covered line|new line|coverage|
|----|----|----|----|----|
|:large_blue_circle:|io/questdb/mp/ConcurrentQueueSegment.java|46|49|93.88%|
|:large_blue_circle:|io/questdb/mp/ConcurrentQueue.java|42|44|95.45%|

**Comment by ideoma** [comment]
#### [PR Coverage check]

:heart_eyes: **pass** : 89 / 93 (95.70%)




#### file detail

|   |path|covered line|new line|coverage|
|----|----|----|----|----|
|:large_blue_circle:|io/questdb/mp/ConcurrentQueue.java|42|44|95.45%|
|:large_blue_circle:|io/questdb/mp/ConcurrentQueueSegment.java|47|49|95.92%|

**Comment by ideoma** [comment]
#### [PR Coverage check]

:heart_eyes: **pass** : 89 / 94 (94.68%)




#### file detail

|   |path|covered line|new line|coverage|
|----|----|----|----|----|
|:large_blue_circle:|io/questdb/mp/ConcurrentQueueSegment.java|47|50|94.00%|
|:large_blue_circle:|io/questdb/mp/ConcurrentQueue.java|42|44|95.45%|

**Review by mtopolnik — DISMISSED** [review]

**Comment by ideoma** [comment]
#### [PR Coverage check]

:heart_eyes: **pass** : 88 / 93 (94.62%)




#### file detail

|   |path|covered line|new line|coverage|
|----|----|----|----|----|
|:large_blue_circle:|io/questdb/mp/ConcurrentQueueSegment.java|46|49|93.88%|
|:large_blue_circle:|io/questdb/mp/ConcurrentQueue.java|42|44|95.45%|

**Comment by ideoma** [comment]
#### [PR Coverage check]

:heart_eyes: **pass** : 88 / 93 (94.62%)




#### file detail

|   |path|covered line|new line|coverage|
|----|----|----|----|----|
|:large_blue_circle:|io/questdb/mp/ConcurrentQueueSegment.java|46|49|93.88%|
|:large_blue_circle:|io/questdb/mp/ConcurrentQueue.java|42|44|95.45%|

**Review by mtopolnik — APPROVED** [review]

**Comment by ideoma** [comment]
#### [PR Coverage check]

:heart_eyes: **pass** : 88 / 93 (94.62%)




#### file detail

|   |path|covered line|new line|coverage|
|----|----|----|----|----|
|:large_blue_circle:|io/questdb/mp/ConcurrentQueueSegment.java|46|49|93.88%|
|:large_blue_circle:|io/questdb/mp/ConcurrentQueue.java|42|44|95.45%|

**Pull request merged**
