### PR TITLE
fix(wal): Reset transaction number on non-WAL to WAL table conversion

### PR DESCRIPTION
**Pull request by glasstiger**
Resetting sequencer txn number on non-WAL to WAL table conversion.
This is necessary because when a non-WAL table is converted to WAL, the memory location where the seqTxn field is, not initialised.

### CODE REVIEW

**Comment by ideoma** [comment]
Related to #2947

**Review by ideoma — APPROVED** [review]

**Comment by ideoma** [comment]
#### [PR Coverage check]

:heart_eyes: **pass** : 2 / 2 (100.00%)




#### file detail

|   |path|covered line|new line|coverage|
|----|----|----|----|----|
|:large_blue_circle:|io/questdb/cairo/CairoEngine.java|2|2|100.00%|

**Comment by bluestreak01** [comment]
@glasstiger what do we do about tests ?

**Comment by ideoma** [comment]
#### [PR Coverage check]

:heart_eyes: **pass** : 2 / 2 (100.00%)




#### file detail

|   |path|covered line|new line|coverage|
|----|----|----|----|----|
|:large_blue_circle:|io/questdb/cairo/CairoEngine.java|2|2|100.00%|

**Comment by ideoma** [comment]
#### [PR Coverage check]

:heart_eyes: **pass** : 2 / 2 (100.00%)




#### file detail

|   |path|covered line|new line|coverage|
|----|----|----|----|----|
|:large_blue_circle:|io/questdb/cairo/CairoEngine.java|2|2|100.00%|

**Pull request merged**
