### PR TITLE
fix(core): disable query cancellation and timeout in WAL apply job

### PR DESCRIPTION
**Pull request by bziobrowski**
PR:
- disables timeout being applied to update statements executed by WAL job via page frames
- returns error when query to canel is being executed in WAL job.
- adds is_wal boolean column to result of query_activity() function

### CODE REVIEW

**Comment by ideoma** [comment]
#### [PR Coverage check]

:heart_eyes: **pass** : 19 / 20 (95.00%)




#### file detail

|   |path|covered line|new line|coverage|
|----|----|----|----|----|
|:large_blue_circle:|io/questdb/griffin/engine/functions/activity/QueryActivityFunctionFactory.java|4|5|80.00%|
|:large_blue_circle:|io/questdb/cairo/sql/async/PageFrameReduceJob.java|3|3|100.00%|
|:large_blue_circle:|io/questdb/griffin/SqlCompilerImpl.java|6|6|100.00%|
|:large_blue_circle:|io/questdb/griffin/QueryRegistry.java|6|6|100.00%|

**Comment by ideoma** [comment]
Fixes #4160

**Review by jerrinot — DISMISSED** [review]

**Comment by ideoma** [comment]
#### [PR Coverage check]

:heart_eyes: **pass** : 19 / 20 (95.00%)




#### file detail

|   |path|covered line|new line|coverage|
|----|----|----|----|----|
|:large_blue_circle:|io/questdb/griffin/engine/functions/activity/QueryActivityFunctionFactory.java|4|5|80.00%|
|:large_blue_circle:|io/questdb/cairo/sql/async/PageFrameReduceJob.java|3|3|100.00%|
|:large_blue_circle:|io/questdb/griffin/SqlCompilerImpl.java|6|6|100.00%|
|:large_blue_circle:|io/questdb/griffin/QueryRegistry.java|6|6|100.00%|

**Review by ideoma — CHANGES_REQUESTED** [review]
When I run `IODispatcherTest.testUpdateCommandRunningInWALCantBeCancelled`

I see in the logs 

```
2024-01-31T13:54:29.528032Z E i.q.g.UpdateOperatorImpl could not update
io.questdb.cairo.CairoException: [666] cancelling WAL application!
	at io.questdb.cairo.CairoException.instance(CairoException.java:310)
	at io.questdb.cairo.CairoException.critical(CairoException.java:69)
	at io.questdb.test.cutlass.http.IODispatcherTest$DelayedWALListener.onRegister(IODispatcherTest.java:9364)
	at io.questdb.griffin.QueryRegistry.register(QueryRegistry.java:150)
	at io.questdb.griffin.UpdateOperatorImpl.executeUpdate(UpdateOperatorImpl.java:88)
	at io.questdb.griffin.engine.ops.UpdateOperation.apply(UpdateOperation.java:74)
	at io.questdb.cairo.TableWriter.apply(TableWriter.java:691)
	at io.questdb.cairo.wal.OperationExecutor.executeUpdate(OperationExecutor.java:98)
	at io.questdb.cairo.wal.ApplyWal2TableJob.processWalSql(ApplyWal2TableJob.java:449)
	at io.questdb.cairo.wal.ApplyWal2TableJob.processWalCommit(ApplyWal2TableJob.java:420)
	at io.questdb.cairo.wal.ApplyWal2TableJob.applyOutstandingWalTransactions(ApplyWal2TableJob.java:323)
	at io.questdb.cairo.wal.ApplyWal2TableJob.applyWal(ApplyWal2TableJob.java:506)
	at io.questdb.cairo.wal.ApplyWal2TableJob.doRun(ApplyWal2TableJob.java:561)
	at io.questdb.mp.AbstractQueueConsumerJob.run(AbstractQueueConsumerJob.java:44)
	at io.questdb.mp.Job.run(Job.java:57)
	at io.questdb.mp.Job.drain(Job.java:35)
	at io.questdb.test.cutlass.http.IODispatcherTest.lambda$testUpdateCommandRunningInWALCantBeCancelled$86(IODispatcherTest.java:7788)
	at java.lang.Thread.run(Thread.java:840)

```

This looks like the test still cancels the update Query for WAL table

**Comment by ideoma** [comment]
#### [PR Coverage check]

:heart_eyes: **pass** : 19 / 20 (95.00%)




#### file detail

|   |path|covered line|new line|coverage|
|----|----|----|----|----|
|:large_blue_circle:|io/questdb/griffin/engine/functions/activity/QueryActivityFunctionFactory.java|4|5|80.00%|
|:large_blue_circle:|io/questdb/cairo/sql/async/PageFrameReduceJob.java|3|3|100.00%|
|:large_blue_circle:|io/questdb/griffin/SqlCompilerImpl.java|6|6|100.00%|
|:large_blue_circle:|io/questdb/griffin/QueryRegistry.java|6|6|100.00%|

**Review by ideoma — APPROVED** [review]

**Pull request merged**
