### PR TITLE
fix(wal): Housekeeping to ignore deprecated sequencer directory

### PR DESCRIPTION
**Pull request by glasstiger**
QuestDB 6.5 creates tables with a `seq` directory.
The path is: `<dbRoot>/db/<tableName>/seq`

This directory is present in these versions because some of the code implementing the WAL feature was merged before 6.5 was released.
Later this directory was renamed to `txn_seq`.
QuestDB 6.6 does not know what `seq` is and complains:
```
E i.q.c.TableWriter invalid partition directory inside table folder: /opt/questdb/db/table/seq
```

This PR is a small change to ignore `seq` directories during housekeeping.

### CODE REVIEW

**Comment by ideoma** [comment]
#### [PR Coverage check]

:heart_eyes: **pass** : 7 / 9 (77.78%)




#### file detail

|   |path|covered line|new line|coverage|
|----|----|----|----|----|
|:large_blue_circle:|io/questdb/cairo/mig/Mig670.java|6|8|75.00%|
|:large_blue_circle:|io/questdb/cairo/mig/EngineMigration.java|1|1|100.00%|

**Comment by ideoma** [comment]
#### [PR Coverage check]

:heart_eyes: **pass** : 7 / 10 (70.00%)




#### file detail

|   |path|covered line|new line|coverage|
|----|----|----|----|----|
|:large_blue_circle:|io/questdb/cairo/mig/MigrationActions.java|0|1|00.00%|
|:large_blue_circle:|io/questdb/cairo/mig/Mig670.java|6|8|75.00%|
|:large_blue_circle:|io/questdb/cairo/mig/EngineMigration.java|1|1|100.00%|

**Review by ideoma — CHANGES_REQUESTED** [review]
I'd simply whitelist `seq` directories for deletion in `TableWriter` instead of doing a migrations.

in the code
 
```java
                path.trimTo(rootLen);
                path.concat(pUtf8NameZ).$();
                LOG.error().$("invalid partition directory inside table folder: ").utf8(path).$();
                return;
```

I'd add 

```java
           if (!Chars.equals("seq", fileNameSink) {
                path.trimTo(rootLen);
                path.concat(pUtf8NameZ).$();
                LOG.error().$("invalid partition directory inside table folder: ").utf8(path).$();
                return;
          }
```

**Comment by glasstiger** [comment]
> I'd simply whitelist `seq` directories for deletion in `TableWriter` instead of doing a migrations.
> 
> in the code
> 
> ```java
>                 path.trimTo(rootLen);
>                 path.concat(pUtf8NameZ).$();
>                 LOG.error().$("invalid partition directory inside table folder: ").utf8(path).$();
>                 return;
> ```
> 
> I'd add
> 
> ```java
>            if (!Chars.equals("seq", fileNameSink) {
>                 path.trimTo(rootLen);
>                 path.concat(pUtf8NameZ).$();
>                 LOG.error().$("invalid partition directory inside table folder: ").utf8(path).$();
>                 return;
>           }
> ```

Implemented it on a different way, just added it to the already existing whitelist check.

**Comment by ideoma** [comment]
#### [PR Coverage check]

:heart_eyes: **pass** : 4 / 4 (100.00%)




#### file detail

|   |path|covered line|new line|coverage|
|----|----|----|----|----|
|:large_blue_circle:|io/questdb/cairo/TableWriter.java|4|4|100.00%|

**Comment by ideoma** [comment]
#### [PR Coverage check]

:heart_eyes: **pass** : 4 / 4 (100.00%)




#### file detail

|   |path|covered line|new line|coverage|
|----|----|----|----|----|
|:large_blue_circle:|io/questdb/cairo/TableWriter.java|4|4|100.00%|

**Review by ideoma — APPROVED** [review]

**Pull request merged**
