### PR TITLE
chore(core): fix flaky acl logging tests

### PR DESCRIPTION
**Pull request by glasstiger**

### CODE REVIEW

**Comment by ideoma** [comment]
#### [PR Coverage check]

:disappointed: **fail** : 0 / 12 (00.00%)




#### file detail

|   |path|covered line|new line|coverage|
|----|----|----|----|----|
|:large_blue_circle:|io/questdb/log/SyncLogger.java|0|7|00.00%|
|:large_blue_circle:|io/questdb/log/LogFactory.java|0|5|00.00%|

**Review by ideoma — COMMENTED** [review]
It doesn't look like this is the solution, the corresponding build is all red

**Comment by glasstiger** [comment]
> It doesn't look like this is the solution, the corresponding build is all red

yes, unfortunately this works only when ACL logging tests run in isolation.
when they run together with the rest of the test suite, the static state messes things up.
the loggers are created before the tests would create them.

did not close the PRs because i have another idea, discussed it with Bolek and Jaromir already.
moved the PRs to draft state for now.
will come back to this on Monday/Tuesday.

**Comment by ideoma** [comment]
#### [PR Coverage check]

:disappointed: **fail** : 0 / 12 (00.00%)




#### file detail

|   |path|covered line|new line|coverage|
|----|----|----|----|----|
|:large_blue_circle:|io/questdb/log/SyncLogger.java|0|7|00.00%|
|:large_blue_circle:|io/questdb/log/LogFactory.java|0|5|00.00%|

**Comment by ideoma** [comment]
Hey @glasstiger, do we still need this? It may be already fixed

**Comment by glasstiger** [comment]
not needed anymore

**Pull request closed without merging**
