### PR TITLE
chore(ilp): get rid of remaining megamorphic calls on ILP hot path

### PR DESCRIPTION
**Pull request by puzpuzpuz**
Also changes the following:
* Decreases default worker sleep timeout from 100ms to 10ms
* Tweaks parameters of slow tests
* Improves `Path` handling in tests, including potential `Path.clearThreadLocals()` races
* A few changes around code consistency in tests (`Random` -> `Rnd`, `Thread.yield()` -> `Os.pause()`)

With all of these changes execution time of all other tests (`^(?!(.*cairo$|.*griffin$)).*$`) on my x86 Linux machine went from 50 minutes (with 1 failing test) down to 16 (with 0 failing tests).

### CODE REVIEW

**Comment by ideoma** [comment]
#### [PR Coverage check]

:heart_eyes: **pass** : 114 / 115 (99.13%)




#### file detail

|   |path|covered line|new line|coverage|
|----|----|----|----|----|
|:large_blue_circle:|io/questdb/std/DirectByteCharSequenceObjHashMap.java|112|113|99.12%|
|:large_blue_circle:|io/questdb/cutlass/line/tcp/LineTcpMeasurementScheduler.java|1|1|100.00%|
|:large_blue_circle:|io/questdb/cutlass/line/tcp/LineTcpNetworkIOJob.java|1|1|100.00%|

**Comment by ideoma** [comment]
#### [PR Coverage check]

:heart_eyes: **pass** : 134 / 135 (99.26%)




#### file detail

|   |path|covered line|new line|coverage|
|----|----|----|----|----|
|:large_blue_circle:|io/questdb/std/DirectByteCharSequenceObjHashMap.java|117|118|99.15%|
|:large_blue_circle:|io/questdb/cutlass/line/tcp/LineTcpMeasurementScheduler.java|1|1|100.00%|
|:large_blue_circle:|io/questdb/PropServerConfiguration.java|3|3|100.00%|
|:large_blue_circle:|io/questdb/std/Chars.java|8|8|100.00%|
|:large_blue_circle:|io/questdb/mp/WorkerPoolConfiguration.java|1|1|100.00%|
|:large_blue_circle:|io/questdb/cutlass/line/tcp/LineTcpNetworkIOJob.java|1|1|100.00%|
|:large_blue_circle:|io/questdb/mp/WorkerPool.java|1|1|100.00%|
|:large_blue_circle:|io/questdb/std/DirectByteCharSequenceIntHashMap.java|2|2|100.00%|

**Comment by ideoma** [comment]
#### [PR Coverage check]

:heart_eyes: **pass** : 134 / 135 (99.26%)




#### file detail

|   |path|covered line|new line|coverage|
|----|----|----|----|----|
|:large_blue_circle:|io/questdb/std/DirectByteCharSequenceObjHashMap.java|117|118|99.15%|
|:large_blue_circle:|io/questdb/cutlass/line/tcp/LineTcpMeasurementScheduler.java|1|1|100.00%|
|:large_blue_circle:|io/questdb/PropServerConfiguration.java|3|3|100.00%|
|:large_blue_circle:|io/questdb/std/Chars.java|8|8|100.00%|
|:large_blue_circle:|io/questdb/mp/WorkerPoolConfiguration.java|1|1|100.00%|
|:large_blue_circle:|io/questdb/cutlass/line/tcp/LineTcpNetworkIOJob.java|1|1|100.00%|
|:large_blue_circle:|io/questdb/mp/WorkerPool.java|1|1|100.00%|
|:large_blue_circle:|io/questdb/std/DirectByteCharSequenceIntHashMap.java|2|2|100.00%|

**Comment by ideoma** [comment]
#### [PR Coverage check]

:heart_eyes: **pass** : 134 / 135 (99.26%)




#### file detail

|   |path|covered line|new line|coverage|
|----|----|----|----|----|
|:large_blue_circle:|io/questdb/std/DirectByteCharSequenceObjHashMap.java|117|118|99.15%|
|:large_blue_circle:|io/questdb/cutlass/line/tcp/LineTcpMeasurementScheduler.java|1|1|100.00%|
|:large_blue_circle:|io/questdb/PropServerConfiguration.java|3|3|100.00%|
|:large_blue_circle:|io/questdb/std/Chars.java|8|8|100.00%|
|:large_blue_circle:|io/questdb/mp/WorkerPoolConfiguration.java|1|1|100.00%|
|:large_blue_circle:|io/questdb/cutlass/line/tcp/LineTcpNetworkIOJob.java|1|1|100.00%|
|:large_blue_circle:|io/questdb/mp/WorkerPool.java|1|1|100.00%|
|:large_blue_circle:|io/questdb/std/DirectByteCharSequenceIntHashMap.java|2|2|100.00%|

**Comment by ideoma** [comment]
#### [PR Coverage check]

:heart_eyes: **pass** : 134 / 135 (99.26%)




#### file detail

|   |path|covered line|new line|coverage|
|----|----|----|----|----|
|:large_blue_circle:|io/questdb/std/DirectByteCharSequenceObjHashMap.java|117|118|99.15%|
|:large_blue_circle:|io/questdb/cutlass/line/tcp/LineTcpMeasurementScheduler.java|1|1|100.00%|
|:large_blue_circle:|io/questdb/PropServerConfiguration.java|3|3|100.00%|
|:large_blue_circle:|io/questdb/std/Chars.java|8|8|100.00%|
|:large_blue_circle:|io/questdb/mp/WorkerPoolConfiguration.java|1|1|100.00%|
|:large_blue_circle:|io/questdb/cutlass/line/tcp/LineTcpNetworkIOJob.java|1|1|100.00%|
|:large_blue_circle:|io/questdb/mp/WorkerPool.java|1|1|100.00%|
|:large_blue_circle:|io/questdb/std/DirectByteCharSequenceIntHashMap.java|2|2|100.00%|

**Comment by puzpuzpuz** [comment]
The failed test is #2340

**Comment by ideoma** [comment]
#### [PR Coverage check]

:heart_eyes: **pass** : 143 / 144 (99.31%)




#### file detail

|   |path|covered line|new line|coverage|
|----|----|----|----|----|
|:large_blue_circle:|io/questdb/std/DirectByteCharSequenceObjHashMap.java|117|118|99.15%|
|:large_blue_circle:|io/questdb/cutlass/line/tcp/LineTcpMeasurementScheduler.java|1|1|100.00%|
|:large_blue_circle:|io/questdb/PropServerConfiguration.java|10|10|100.00%|
|:large_blue_circle:|io/questdb/std/Chars.java|8|8|100.00%|
|:large_blue_circle:|io/questdb/mp/WorkerPoolConfiguration.java|1|1|100.00%|
|:large_blue_circle:|io/questdb/cutlass/line/tcp/LineTcpNetworkIOJob.java|1|1|100.00%|
|:large_blue_circle:|io/questdb/PropertyKey.java|1|1|100.00%|
|:large_blue_circle:|io/questdb/std/DirectByteCharSequenceIntHashMap.java|2|2|100.00%|
|:large_blue_circle:|io/questdb/mp/Worker.java|2|2|100.00%|

**Comment by ideoma** [comment]
#### [PR Coverage check]

:heart_eyes: **pass** : 144 / 145 (99.31%)




#### file detail

|   |path|covered line|new line|coverage|
|----|----|----|----|----|
|:large_blue_circle:|io/questdb/std/DirectByteCharSequenceObjHashMap.java|117|118|99.15%|
|:large_blue_circle:|io/questdb/cutlass/line/tcp/LineTcpMeasurementScheduler.java|1|1|100.00%|
|:large_blue_circle:|io/questdb/PropServerConfiguration.java|10|10|100.00%|
|:large_blue_circle:|io/questdb/std/Chars.java|8|8|100.00%|
|:large_blue_circle:|io/questdb/mp/WorkerPoolConfiguration.java|1|1|100.00%|
|:large_blue_circle:|io/questdb/cutlass/line/tcp/LineTcpNetworkIOJob.java|1|1|100.00%|
|:large_blue_circle:|io/questdb/std/ConcurrentHashMap.java|1|1|100.00%|
|:large_blue_circle:|io/questdb/PropertyKey.java|1|1|100.00%|
|:large_blue_circle:|io/questdb/std/DirectByteCharSequenceIntHashMap.java|2|2|100.00%|
|:large_blue_circle:|io/questdb/mp/Worker.java|2|2|100.00%|

**Comment by ideoma** [comment]
#### [PR Coverage check]

:heart_eyes: **pass** : 144 / 145 (99.31%)




#### file detail

|   |path|covered line|new line|coverage|
|----|----|----|----|----|
|:large_blue_circle:|io/questdb/std/DirectByteCharSequenceObjHashMap.java|117|118|99.15%|
|:large_blue_circle:|io/questdb/cutlass/line/tcp/LineTcpMeasurementScheduler.java|1|1|100.00%|
|:large_blue_circle:|io/questdb/PropServerConfiguration.java|10|10|100.00%|
|:large_blue_circle:|io/questdb/std/Chars.java|8|8|100.00%|
|:large_blue_circle:|io/questdb/mp/WorkerPoolConfiguration.java|1|1|100.00%|
|:large_blue_circle:|io/questdb/cutlass/line/tcp/LineTcpNetworkIOJob.java|1|1|100.00%|
|:large_blue_circle:|io/questdb/std/ConcurrentHashMap.java|1|1|100.00%|
|:large_blue_circle:|io/questdb/PropertyKey.java|1|1|100.00%|
|:large_blue_circle:|io/questdb/std/DirectByteCharSequenceIntHashMap.java|2|2|100.00%|
|:large_blue_circle:|io/questdb/mp/Worker.java|2|2|100.00%|

**Pull request merged**
