### PR TITLE
fix(core): fix potential and unlikely numeric overlflow that could lead to incorrect query results

### LINKED ISSUE #4087: integer_overflow in binary_search
### To reproduce

[`const int64_t mid = (low + high) / 2;`](https://github.com/questdb/questdb/blob/fc23804602485c75bf70f1b247aba8d0d4f0ac65/core/src/main/c/share/util.h#L154) potentially introduces integer overflow.
Write `low + (high - low) / 2` to fix the issue.
Check out [here](https://blog.research.google/2006/06/extra-extra-read-all-about-it-nearly.html) for all possible solutions to this problem

### QuestDB version:

master

### OS, in case of Docker specify Docker and the Host OS:

all

### File System, in case of Docker specify Host File System:

ext4

### Full Name:

Siddharth Bhardwaj

### Affiliation:

Dalhousie

### Have you followed Linux, MacOs kernel configuration steps to increase Maximum open files and Maximum virtual memory areas limit?

- [ ] Yes, I have

### Additional context

_No response_

### PR DESCRIPTION
**Pull request by pompeiifreckles**
```
	mid = (low + high) / 2;
	      ^^^^^^^^^^^^
		   |
		potential integer overflow
```
Fix :
```
	diff = high - low;
	mid = low + diff / 2;
```

fixes #4087

### CODE REVIEW

**Comment by jerrinot** [comment]
@pompeiifreckles: thank you for fixing this. The change looks good to me. 

There is the same issue on the Java side of QuestDB: `DoubleList`, `LongList` and `IntList`. Do you want to fix these too? Up to you, your report and this PR is already a great help!

**Comment by pompeiifreckles** [comment]
@jerrinot , sure would love to. I'll try to find all the segments on java side experiencing this problem. Would be a great help, if you could mention the file names if you are aware about them.

Secondly, do I need to send a separate PR for the Java overflows or do I retract the prev PR and send all the fixes in a single PR?

**Comment by jerrinot** [comment]
@pompeiifreckles wow, I see you found a whole bunch of specialized bin searchers, well done!

**Comment by jerrinot** [comment]
@pompeiifreckles the test failure is unrelated, a known flaky test failed, @bluestreak01 is looking into it. let's re-run it.

**Review by jerrinot — APPROVED** [review]

**Comment by jerrinot** [comment]
@pompeiifreckles the code looks good to me, many thanks! is there any way to credit you? I mean beyond mentioning this in release notes. do you have a Twitter account or something?

**Comment by pompeiifreckles** [comment]
OMG thanks! I am not really active on twitter but my username is _Pompeiifreckles_. I appreciate the shoutout.

Let me know if there is anywhere else I can contribute in the code. I would love to be an active part of an opensource project.

**Comment by jerrinot** [comment]
@pompeiifreckles it depends on what you are up to. There is a list of "Good first issues": https://github.com/questdb/questdb/issues?q=is%3Aopen+is%3Aissue+label%3A%22Good+first+issue%22
These issue are meant to be accessible for people without prior exposure to QuestDB code. 

If you would like to stay on the data structure side of things then I (or @puzpuzpuz) might have some ideas too. It's best to join QuestDB Slack and give me a shout there: http://slack.questdb.io/ - there is a channel for new contributors.

**Comment by amunra** [comment]
Given how subtle the bug is, it's probably worth adding a reference to the article explaining the issue above each of those lines in a comment: https://blog.research.google/2006/06/extra-extra-read-all-about-it-nearly.html

**Pull request merged**
