### PR TITLE
Collapsable schema

### LINKED ISSUE #1486: Collapsible table list
### Is your feature request related to a problem?

Add an ability to collapse the table list on the top left so that more spaces is given to the SQL editor.

### Describe the solution you'd like.

1. Allow the vertical divider to go all the way to the left (in a similar fashion to left sidebar behaviour in Slack app) so that it would collapse the Table panel and display a relevant icon (keep the "storage" icon in place so that when clicked it'll expand to a default (fallback) width. 
2. Save the state of the pane in local storage.

### Describe alternatives you've considered.

_No response_

### Additional context.

_No response_

### PR DESCRIPTION
**Pull request by enolal826**
Fixes #1486

In the issue it was stated that we should keep an icon for the user to open the component again. With that approach, we should also include the storage icon in the Editor component and make them work together using Redux.

In the approach of this PR, we simply "hide" the schema by letting the user scroll all the way to the left, but without actually hiding the component. This way, the scroll bar is always visible and the user can resize it at any time. When the bar reaches the `min` size, the ghost icon is directly sent to the very left of the screen.

https://user-images.githubusercontent.com/51820585/142474197-68435002-3e11-415f-9128-d07f093fcaa5.mov

### CODE REVIEW

**Comment by bluestreak01** [comment]
When collapsed, could we get an icon appear on top bar? When window is collapsed there is no indication that it can be expanded.

**Comment by insmac** [comment]
@enolal826 Thanks for your another contribution! 🎉 

Regarding having the storage icon in the Editor, my suggestion would be to go simpler than redux, because we can leverage already existing `useLocalStorage()` hook to get `editorSplitterBasis` and then display that icon conditionally.

Upon clicking the icon to toggle the table panel back to its original position I would probably use an onClick action similar to:

```
updateSettings(StoreKey.EDITOR_SPLITTER_BASIS, defaultConfig.editorSplitterBasis)
```

(although you would first need to export defaultConfig object from `LocalStorageProvider`.

Alternatively we could also add a conditional so that the `<Schema />` component is not rendered if hidden, i.e. `{editorSplitterBasis !== 0 && <Schema />`

The icon can be added on the left of the `Run` button when schema panel is collapsed to maintain integrity.

**Review by insmac — APPROVED** [review]
Good job! 👏 It works as intended on my end.

**Review by bluestreak01 — CHANGES_REQUESTED** [review]
run and cancel buttons are simultaneously visible:

image


I could have caused by my attempt to resolve conflicts. Regardless this needs a fix

**Comment by enolal826** [comment]
@bluestreak01 It should be fixed now

**Comment by bluestreak01** [comment]
this is very cool 👍 works really well, thank you @enolal826

**Review by bluestreak01 — APPROVED** [review]

**Pull request merged**
