### PR TITLE
fix(o3): size memory2 correctly for O3 sort

### LINKED ISSUE #1666: SIGSEGV on QuestDB 6.1.2
### Describe the bug

We have started encountering segmentation faults on our QuestDB instance this morning.
Unfortunately we're unable to pinpoint exactly what caused them, as neither our configuration nor the environment changed recently. 

### To reproduce

N/A

### Expected Behavior

N/A

### Environment

```markdown
- **QuestDB version**:
OpenJDK Runtime Environment Corretto-11.0.13.8.1 (build 11.0.13+8-LTS)
QuestDB 6.1.2
- **OS**:
CentOS Stream 8
- **Browser**:
N/A
```

### Additional context

https://pastebin.com/uVR9sNC4 - jvm notifying about sigsegv.
https://pastebin.com/D5zGHhUD - crashlog (note - after the initial crashes the instance was restarted, this is the latest one, thus low uptime).

### PR DESCRIPTION
**Pull request by bluestreak01**
Possibly fixes #1666

### CODE REVIEW

**Review by ideoma — APPROVED** [review]

**Comment by ideoma** [comment]
#### [PR Coverage check]

:heart_eyes: **pass** : 76 / 79 (96.20%)




#### file detail

|   |path|covered line|new line|coverage|
|----|----|----|----|----|
|:large_blue_circle:|io/questdb/cairo/TableWriter.java|76|79|96.20%|

**Comment by ideoma** [comment]
#### [PR Coverage check]

:heart_eyes: **pass** : 76 / 79 (96.20%)




#### file detail

|   |path|covered line|new line|coverage|
|----|----|----|----|----|
|:large_blue_circle:|io/questdb/cairo/TableWriter.java|76|79|96.20%|

**Comment by ideoma** [comment]
#### [PR Coverage check]

:heart_eyes: **pass** : 76 / 79 (96.20%)




#### file detail

|   |path|covered line|new line|coverage|
|----|----|----|----|----|
|:large_blue_circle:|io/questdb/cairo/TableWriter.java|76|79|96.20%|

**Comment by ideoma** [comment]
#### [PR Coverage check]

:heart_eyes: **pass** : 76 / 79 (96.20%)




#### file detail

|   |path|covered line|new line|coverage|
|----|----|----|----|----|
|:large_blue_circle:|io/questdb/cairo/TableWriter.java|76|79|96.20%|

**Comment by ideoma** [comment]
#### [PR Coverage check]

:heart_eyes: **pass** : 76 / 79 (96.20%)




#### file detail

|   |path|covered line|new line|coverage|
|----|----|----|----|----|
|:large_blue_circle:|io/questdb/cairo/TableWriter.java|76|79|96.20%|

**Comment by bluestreak01** [comment]
this change doesn't have any effect

**Pull request closed without merging**
