### PR TITLE
fix(sql): apply query timeout to insert statements and improve timeout reliability

### LINKED ISSUE #2541: Table is locked by INSERT AS SELECT if query times out
### Describe the bug

Client runs a slow INSERT AS SELECT.
SELECT takes so long that client connection times out, client receives HTTP 504.
Table stays locked by INSERT AS SELECT operation.

SQL in question:
```
insert into 'link_events_new'
(created_at, link_id, destination_id, event, type, device, link_variant, country, region, city, referrer, utm_term, utm_content, utm_campaign, utm_medium, utm_source, user_hash)
select created_at, link_id, destination_id, event, type, device, link_variant, country, region, city, referrer, utm_term, utm_content, utm_campaign, utm_medium, utm_source, user_hash
from link_events where created_at between '2010' and '2022-09-15'
```

Subsequently client tries to drop the table and gets the error:
```
Could not lock 'link_events_new' [reason='insertAsSelect']
```

Not sure if it is because the operation is still running or ended (likely with an error) and failed to release the lock.
If the insert is still running we should be using a circuit breaker to cancel it and release the lock.
If it is failed to release the lock we should fix it.

### To reproduce

In theory this could do:
1. Create a huge table
2. Create an empty table
3. Run INSERT AS SELECT from the huge table to the empty one
4. Disconnect your client before the operation finished
5. Reconnect and try to drop the table which you are inserting into

### Expected Behavior

When client disconnects/disconnected INSERT AS SELECT should be cancelled and lock on the table should be released

### Environment

```markdown
- **QuestDB version**: 6.5.1
- **OS**:
- **Browser**:
```

### Additional context

_No response_

### PR DESCRIPTION
**Pull request by bziobrowski**
Fixes #2541 
by adding timeout to create table as select and insert as select . 

Also : 
- applies timeout not only to query execution but also compilation phase 
- adds timeout check to sample by, vectorized group by and row_number() implementations  
- changes default max memory limits for row_number() implementation (from Long.MAX_VALUE): 
  - cairo.sql.analytic.store.max.pages
  - cairo.sql.analytic.rowid.max.pages
  - cairo.sql.analytic.tree.max.pages
  to reduce risk of triggering OOM on big data sets 
- fixes issue with timeout for complex queries . Factories used to reset timer just by getting circuit breaker instance from sql context so their runtime could exceed timeout significantly before cancellation. 

NOTE 1: I changed circuit breaker to time out on first test if timeout is Long.MIN_VALUE. 
NOTE 2: On Windows it seems that microsecond clock time can be ahead of System.currentTimeMillis() by 16 ms . 

```java
    @Test
    public void testClockDiff() {
        long maxDiff = Long.MIN_VALUE;
        long minDiff = Long.MAX_VALUE;
        long diff;
        for (int i = 0; i < 1000000000; i++) {
            long os = Os.currentTimeMicros() / 1000;
            long java = System.currentTimeMillis();

            diff = os - java;

            if (diff > maxDiff) {
                maxDiff = diff;

            }
            if (diff < minDiff) {
                minDiff = diff;
            }
        }

        System.out.println(maxDiff);
        System.out.println(minDiff);
    }
```    

produces : 
16
-1

so mixing microsecond with millisecond clock times might produce surprising results .

### CODE REVIEW

**Comment by ideoma** [comment]
#### [PR Coverage check]

:heart_eyes: **pass** : 156 / 174 (89.66%)




#### file detail

|   |path|covered line|new line|coverage|
|----|----|----|----|----|
|:large_blue_circle:|io/questdb/griffin/engine/table/LatestByAllIndexedRecordCursor.java|2|3|66.67%|
|:large_blue_circle:|io/questdb/cairo/sql/SqlExecutionCircuitBreaker.java|2|3|66.67%|
|:large_blue_circle:|io/questdb/griffin/engine/groupby/vect/GroupByNotKeyedVectorRecordCursorFactory.java|21|29|72.41%|
|:large_blue_circle:|io/questdb/griffin/engine/groupby/vect/GroupByRecordCursorFactory.java|44|50|88.00%|
|:large_blue_circle:|io/questdb/griffin/SqlCompiler.java|21|23|91.30%|
|:large_blue_circle:|io/questdb/griffin/engine/table/LatestByValueListRecordCursor.java|9|9|100.00%|
|:large_blue_circle:|io/questdb/PropServerConfiguration.java|3|3|100.00%|
|:large_blue_circle:|io/questdb/griffin/engine/table/LatestByValueFilteredRecordCursor.java|3|3|100.00%|
|:large_blue_circle:|io/questdb/griffin/engine/table/LatestByAllRecordCursor.java|2|2|100.00%|
|:large_blue_circle:|io/questdb/griffin/engine/table/LatestByValuesRecordCursor.java|2|2|100.00%|
|:large_blue_circle:|io/questdb/cutlass/http/processors/JsonQueryProcessor.java|1|1|100.00%|
|:large_blue_circle:|io/questdb/griffin/engine/table/LatestByValueRecordCursor.java|3|3|100.00%|
|:large_blue_circle:|io/questdb/griffin/engine/table/LatestByValuesFilteredRecordCursor.java|2|2|100.00%|
|:large_blue_circle:|io/questdb/griffin/engine/table/LatestByValuesIndexedRecordCursor.java|3|3|100.00%|
|:large_blue_circle:|io/questdb/griffin/engine/groupby/vect/VectorAggregateEntry.java|10|10|100.00%|
|:large_blue_circle:|io/questdb/griffin/engine/analytic/CachedAnalyticRecordCursorFactory.java|7|7|100.00%|
|:large_blue_circle:|io/questdb/cairo/sql/NetworkSqlExecutionCircuitBreaker.java|9|9|100.00%|
|:large_blue_circle:|io/questdb/griffin/engine/table/LatestByValuesIndexedFilteredRecordCursor.java|2|2|100.00%|
|:large_blue_circle:|io/questdb/griffin/engine/table/LatestByAllFilteredRecordCursor.java|2|2|100.00%|
|:large_blue_circle:|io/questdb/griffin/engine/table/LatestByValueIndexedFilteredRecordCursor.java|4|4|100.00%|
|:large_blue_circle:|io/questdb/cutlass/pgwire/PGConnectionContext.java|4|4|100.00%|

**Comment by ideoma** [comment]
#### [PR Coverage check]

:heart_eyes: **pass** : 156 / 174 (89.66%)




#### file detail

|   |path|covered line|new line|coverage|
|----|----|----|----|----|
|:large_blue_circle:|io/questdb/griffin/engine/table/LatestByAllIndexedRecordCursor.java|2|3|66.67%|
|:large_blue_circle:|io/questdb/cairo/sql/SqlExecutionCircuitBreaker.java|2|3|66.67%|
|:large_blue_circle:|io/questdb/griffin/engine/groupby/vect/GroupByNotKeyedVectorRecordCursorFactory.java|21|29|72.41%|
|:large_blue_circle:|io/questdb/griffin/engine/groupby/vect/GroupByRecordCursorFactory.java|44|50|88.00%|
|:large_blue_circle:|io/questdb/griffin/SqlCompiler.java|21|23|91.30%|
|:large_blue_circle:|io/questdb/griffin/engine/table/LatestByValueListRecordCursor.java|9|9|100.00%|
|:large_blue_circle:|io/questdb/PropServerConfiguration.java|3|3|100.00%|
|:large_blue_circle:|io/questdb/griffin/engine/table/LatestByValueFilteredRecordCursor.java|3|3|100.00%|
|:large_blue_circle:|io/questdb/griffin/engine/table/LatestByAllRecordCursor.java|2|2|100.00%|
|:large_blue_circle:|io/questdb/griffin/engine/table/LatestByValuesRecordCursor.java|2|2|100.00%|
|:large_blue_circle:|io/questdb/cutlass/http/processors/JsonQueryProcessor.java|1|1|100.00%|
|:large_blue_circle:|io/questdb/griffin/engine/table/LatestByValueRecordCursor.java|3|3|100.00%|
|:large_blue_circle:|io/questdb/griffin/engine/table/LatestByValuesFilteredRecordCursor.java|2|2|100.00%|
|:large_blue_circle:|io/questdb/griffin/engine/table/LatestByValuesIndexedRecordCursor.java|3|3|100.00%|
|:large_blue_circle:|io/questdb/griffin/engine/groupby/vect/VectorAggregateEntry.java|10|10|100.00%|
|:large_blue_circle:|io/questdb/griffin/engine/analytic/CachedAnalyticRecordCursorFactory.java|7|7|100.00%|
|:large_blue_circle:|io/questdb/cairo/sql/NetworkSqlExecutionCircuitBreaker.java|9|9|100.00%|
|:large_blue_circle:|io/questdb/griffin/engine/table/LatestByValuesIndexedFilteredRecordCursor.java|2|2|100.00%|
|:large_blue_circle:|io/questdb/griffin/engine/table/LatestByAllFilteredRecordCursor.java|2|2|100.00%|
|:large_blue_circle:|io/questdb/griffin/engine/table/LatestByValueIndexedFilteredRecordCursor.java|4|4|100.00%|
|:large_blue_circle:|io/questdb/cutlass/pgwire/PGConnectionContext.java|4|4|100.00%|

**Review by bluestreak01 — CHANGES_REQUESTED** [review]

**Comment by ideoma** [comment]
#### [PR Coverage check]

:heart_eyes: **pass** : 276 / 287 (96.17%)




#### file detail

|   |path|covered line|new line|coverage|
|----|----|----|----|----|
|:large_blue_circle:|io/questdb/cairo/sql/SqlExecutionCircuitBreaker.java|2|3|66.67%|
|:large_blue_circle:|io/questdb/griffin/engine/groupby/vect/GroupByNotKeyedVectorRecordCursorFactory.java|26|29|89.66%|
|:large_blue_circle:|io/questdb/griffin/SqlCompiler.java|21|23|91.30%|
|:large_blue_circle:|io/questdb/cutlass/pgwire/PGConnectionContext.java|44|46|95.65%|
|:large_blue_circle:|io/questdb/griffin/engine/table/LatestByAllIndexedRecordCursor.java|65|67|97.01%|
|:large_blue_circle:|io/questdb/griffin/engine/groupby/vect/GroupByRecordCursorFactory.java|50|51|98.04%|
|:large_blue_circle:|io/questdb/griffin/engine/table/LatestByValueListRecordCursor.java|9|9|100.00%|
|:large_blue_circle:|io/questdb/PropServerConfiguration.java|3|3|100.00%|
|:large_blue_circle:|io/questdb/griffin/engine/table/LatestByValueFilteredRecordCursor.java|3|3|100.00%|
|:large_blue_circle:|io/questdb/griffin/engine/table/LatestByAllRecordCursor.java|2|2|100.00%|
|:large_blue_circle:|io/questdb/griffin/engine/table/LatestByValuesRecordCursor.java|2|2|100.00%|
|:large_blue_circle:|io/questdb/cutlass/http/processors/JsonQueryProcessor.java|1|1|100.00%|
|:large_blue_circle:|io/questdb/griffin/engine/table/LatestByValueRecordCursor.java|3|3|100.00%|
|:large_blue_circle:|io/questdb/griffin/engine/table/LatestByValuesFilteredRecordCursor.java|2|2|100.00%|
|:large_blue_circle:|io/questdb/griffin/engine/table/LatestByValuesIndexedRecordCursor.java|3|3|100.00%|
|:large_blue_circle:|io/questdb/tasks/LatestByTask.java|3|3|100.00%|
|:large_blue_circle:|io/questdb/griffin/engine/groupby/vect/VectorAggregateEntry.java|10|10|100.00%|
|:large_blue_circle:|io/questdb/griffin/engine/analytic/CachedAnalyticRecordCursorFactory.java|7|7|100.00%|
|:large_blue_circle:|io/questdb/cairo/sql/NetworkSqlExecutionCircuitBreaker.java|12|12|100.00%|
|:large_blue_circle:|io/questdb/griffin/engine/table/LatestByValuesIndexedFilteredRecordCursor.java|2|2|100.00%|
|:large_blue_circle:|io/questdb/griffin/engine/table/LatestByAllFilteredRecordCursor.java|2|2|100.00%|
|:large_blue_circle:|io/questdb/griffin/engine/table/LatestByValueIndexedFilteredRecordCursor.java|4|4|100.00%|

**Comment by ideoma** [comment]
#### [PR Coverage check]

:heart_eyes: **pass** : 276 / 287 (96.17%)




#### file detail

|   |path|covered line|new line|coverage|
|----|----|----|----|----|
|:large_blue_circle:|io/questdb/cairo/sql/SqlExecutionCircuitBreaker.java|2|3|66.67%|
|:large_blue_circle:|io/questdb/griffin/engine/groupby/vect/GroupByNotKeyedVectorRecordCursorFactory.java|26|29|89.66%|
|:large_blue_circle:|io/questdb/griffin/SqlCompiler.java|21|23|91.30%|
|:large_blue_circle:|io/questdb/cutlass/pgwire/PGConnectionContext.java|44|46|95.65%|
|:large_blue_circle:|io/questdb/griffin/engine/table/LatestByAllIndexedRecordCursor.java|65|67|97.01%|
|:large_blue_circle:|io/questdb/griffin/engine/groupby/vect/GroupByRecordCursorFactory.java|50|51|98.04%|
|:large_blue_circle:|io/questdb/griffin/engine/table/LatestByValueListRecordCursor.java|9|9|100.00%|
|:large_blue_circle:|io/questdb/PropServerConfiguration.java|3|3|100.00%|
|:large_blue_circle:|io/questdb/griffin/engine/table/LatestByValueFilteredRecordCursor.java|3|3|100.00%|
|:large_blue_circle:|io/questdb/griffin/engine/table/LatestByAllRecordCursor.java|2|2|100.00%|
|:large_blue_circle:|io/questdb/griffin/engine/table/LatestByValuesRecordCursor.java|2|2|100.00%|
|:large_blue_circle:|io/questdb/cutlass/http/processors/JsonQueryProcessor.java|1|1|100.00%|
|:large_blue_circle:|io/questdb/griffin/engine/table/LatestByValueRecordCursor.java|3|3|100.00%|
|:large_blue_circle:|io/questdb/griffin/engine/table/LatestByValuesFilteredRecordCursor.java|2|2|100.00%|
|:large_blue_circle:|io/questdb/griffin/engine/table/LatestByValuesIndexedRecordCursor.java|3|3|100.00%|
|:large_blue_circle:|io/questdb/tasks/LatestByTask.java|3|3|100.00%|
|:large_blue_circle:|io/questdb/griffin/engine/groupby/vect/VectorAggregateEntry.java|10|10|100.00%|
|:large_blue_circle:|io/questdb/griffin/engine/analytic/CachedAnalyticRecordCursorFactory.java|7|7|100.00%|
|:large_blue_circle:|io/questdb/cairo/sql/NetworkSqlExecutionCircuitBreaker.java|12|12|100.00%|
|:large_blue_circle:|io/questdb/griffin/engine/table/LatestByValuesIndexedFilteredRecordCursor.java|2|2|100.00%|
|:large_blue_circle:|io/questdb/griffin/engine/table/LatestByAllFilteredRecordCursor.java|2|2|100.00%|
|:large_blue_circle:|io/questdb/griffin/engine/table/LatestByValueIndexedFilteredRecordCursor.java|4|4|100.00%|

**Comment by ideoma** [comment]
#### [PR Coverage check]

:heart_eyes: **pass** : 276 / 287 (96.17%)




#### file detail

|   |path|covered line|new line|coverage|
|----|----|----|----|----|
|:large_blue_circle:|io/questdb/cairo/sql/SqlExecutionCircuitBreaker.java|2|3|66.67%|
|:large_blue_circle:|io/questdb/griffin/engine/groupby/vect/GroupByNotKeyedVectorRecordCursorFactory.java|26|29|89.66%|
|:large_blue_circle:|io/questdb/griffin/SqlCompiler.java|21|23|91.30%|
|:large_blue_circle:|io/questdb/cutlass/pgwire/PGConnectionContext.java|44|46|95.65%|
|:large_blue_circle:|io/questdb/griffin/engine/table/LatestByAllIndexedRecordCursor.java|65|67|97.01%|
|:large_blue_circle:|io/questdb/griffin/engine/groupby/vect/GroupByRecordCursorFactory.java|50|51|98.04%|
|:large_blue_circle:|io/questdb/griffin/engine/table/LatestByValueListRecordCursor.java|9|9|100.00%|
|:large_blue_circle:|io/questdb/PropServerConfiguration.java|3|3|100.00%|
|:large_blue_circle:|io/questdb/griffin/engine/table/LatestByValueFilteredRecordCursor.java|3|3|100.00%|
|:large_blue_circle:|io/questdb/griffin/engine/table/LatestByAllRecordCursor.java|2|2|100.00%|
|:large_blue_circle:|io/questdb/griffin/engine/table/LatestByValuesRecordCursor.java|2|2|100.00%|
|:large_blue_circle:|io/questdb/cutlass/http/processors/JsonQueryProcessor.java|1|1|100.00%|
|:large_blue_circle:|io/questdb/griffin/engine/table/LatestByValueRecordCursor.java|3|3|100.00%|
|:large_blue_circle:|io/questdb/griffin/engine/table/LatestByValuesFilteredRecordCursor.java|2|2|100.00%|
|:large_blue_circle:|io/questdb/griffin/engine/table/LatestByValuesIndexedRecordCursor.java|3|3|100.00%|
|:large_blue_circle:|io/questdb/tasks/LatestByTask.java|3|3|100.00%|
|:large_blue_circle:|io/questdb/griffin/engine/groupby/vect/VectorAggregateEntry.java|10|10|100.00%|
|:large_blue_circle:|io/questdb/griffin/engine/analytic/CachedAnalyticRecordCursorFactory.java|7|7|100.00%|
|:large_blue_circle:|io/questdb/cairo/sql/NetworkSqlExecutionCircuitBreaker.java|12|12|100.00%|
|:large_blue_circle:|io/questdb/griffin/engine/table/LatestByValuesIndexedFilteredRecordCursor.java|2|2|100.00%|
|:large_blue_circle:|io/questdb/griffin/engine/table/LatestByAllFilteredRecordCursor.java|2|2|100.00%|
|:large_blue_circle:|io/questdb/griffin/engine/table/LatestByValueIndexedFilteredRecordCursor.java|4|4|100.00%|

**Comment by ideoma** [comment]
#### [PR Coverage check]

:heart_eyes: **pass** : 276 / 287 (96.17%)




#### file detail

|   |path|covered line|new line|coverage|
|----|----|----|----|----|
|:large_blue_circle:|io/questdb/cairo/sql/SqlExecutionCircuitBreaker.java|2|3|66.67%|
|:large_blue_circle:|io/questdb/griffin/engine/groupby/vect/GroupByNotKeyedVectorRecordCursorFactory.java|26|29|89.66%|
|:large_blue_circle:|io/questdb/griffin/SqlCompiler.java|21|23|91.30%|
|:large_blue_circle:|io/questdb/cutlass/pgwire/PGConnectionContext.java|44|46|95.65%|
|:large_blue_circle:|io/questdb/griffin/engine/table/LatestByAllIndexedRecordCursor.java|65|67|97.01%|
|:large_blue_circle:|io/questdb/griffin/engine/groupby/vect/GroupByRecordCursorFactory.java|50|51|98.04%|
|:large_blue_circle:|io/questdb/griffin/engine/table/LatestByValueListRecordCursor.java|9|9|100.00%|
|:large_blue_circle:|io/questdb/PropServerConfiguration.java|3|3|100.00%|
|:large_blue_circle:|io/questdb/griffin/engine/table/LatestByValueFilteredRecordCursor.java|3|3|100.00%|
|:large_blue_circle:|io/questdb/griffin/engine/table/LatestByAllRecordCursor.java|2|2|100.00%|
|:large_blue_circle:|io/questdb/griffin/engine/table/LatestByValuesRecordCursor.java|2|2|100.00%|
|:large_blue_circle:|io/questdb/cutlass/http/processors/JsonQueryProcessor.java|1|1|100.00%|
|:large_blue_circle:|io/questdb/griffin/engine/table/LatestByValueRecordCursor.java|3|3|100.00%|
|:large_blue_circle:|io/questdb/griffin/engine/table/LatestByValuesFilteredRecordCursor.java|2|2|100.00%|
|:large_blue_circle:|io/questdb/griffin/engine/table/LatestByValuesIndexedRecordCursor.java|3|3|100.00%|
|:large_blue_circle:|io/questdb/tasks/LatestByTask.java|3|3|100.00%|
|:large_blue_circle:|io/questdb/griffin/engine/groupby/vect/VectorAggregateEntry.java|10|10|100.00%|
|:large_blue_circle:|io/questdb/griffin/engine/analytic/CachedAnalyticRecordCursorFactory.java|7|7|100.00%|
|:large_blue_circle:|io/questdb/cairo/sql/NetworkSqlExecutionCircuitBreaker.java|12|12|100.00%|
|:large_blue_circle:|io/questdb/griffin/engine/table/LatestByValuesIndexedFilteredRecordCursor.java|2|2|100.00%|
|:large_blue_circle:|io/questdb/griffin/engine/table/LatestByAllFilteredRecordCursor.java|2|2|100.00%|
|:large_blue_circle:|io/questdb/griffin/engine/table/LatestByValueIndexedFilteredRecordCursor.java|4|4|100.00%|

**Comment by ideoma** [comment]
#### [PR Coverage check]

:heart_eyes: **pass** : 276 / 287 (96.17%)




#### file detail

|   |path|covered line|new line|coverage|
|----|----|----|----|----|
|:large_blue_circle:|io/questdb/cairo/sql/SqlExecutionCircuitBreaker.java|2|3|66.67%|
|:large_blue_circle:|io/questdb/griffin/engine/groupby/vect/GroupByNotKeyedVectorRecordCursorFactory.java|26|29|89.66%|
|:large_blue_circle:|io/questdb/griffin/SqlCompiler.java|21|23|91.30%|
|:large_blue_circle:|io/questdb/cutlass/pgwire/PGConnectionContext.java|44|46|95.65%|
|:large_blue_circle:|io/questdb/griffin/engine/table/LatestByAllIndexedRecordCursor.java|65|67|97.01%|
|:large_blue_circle:|io/questdb/griffin/engine/groupby/vect/GroupByRecordCursorFactory.java|50|51|98.04%|
|:large_blue_circle:|io/questdb/griffin/engine/table/LatestByValueListRecordCursor.java|9|9|100.00%|
|:large_blue_circle:|io/questdb/PropServerConfiguration.java|3|3|100.00%|
|:large_blue_circle:|io/questdb/griffin/engine/table/LatestByValueFilteredRecordCursor.java|3|3|100.00%|
|:large_blue_circle:|io/questdb/griffin/engine/table/LatestByAllRecordCursor.java|2|2|100.00%|
|:large_blue_circle:|io/questdb/griffin/engine/table/LatestByValuesRecordCursor.java|2|2|100.00%|
|:large_blue_circle:|io/questdb/cutlass/http/processors/JsonQueryProcessor.java|1|1|100.00%|
|:large_blue_circle:|io/questdb/griffin/engine/table/LatestByValueRecordCursor.java|3|3|100.00%|
|:large_blue_circle:|io/questdb/griffin/engine/table/LatestByValuesFilteredRecordCursor.java|2|2|100.00%|
|:large_blue_circle:|io/questdb/griffin/engine/table/LatestByValuesIndexedRecordCursor.java|3|3|100.00%|
|:large_blue_circle:|io/questdb/tasks/LatestByTask.java|3|3|100.00%|
|:large_blue_circle:|io/questdb/griffin/engine/groupby/vect/VectorAggregateEntry.java|10|10|100.00%|
|:large_blue_circle:|io/questdb/griffin/engine/analytic/CachedAnalyticRecordCursorFactory.java|7|7|100.00%|
|:large_blue_circle:|io/questdb/cairo/sql/NetworkSqlExecutionCircuitBreaker.java|12|12|100.00%|
|:large_blue_circle:|io/questdb/griffin/engine/table/LatestByValuesIndexedFilteredRecordCursor.java|2|2|100.00%|
|:large_blue_circle:|io/questdb/griffin/engine/table/LatestByAllFilteredRecordCursor.java|2|2|100.00%|
|:large_blue_circle:|io/questdb/griffin/engine/table/LatestByValueIndexedFilteredRecordCursor.java|4|4|100.00%|

**Review by bluestreak01 — APPROVED** [review]

**Comment by ideoma** [comment]
#### [PR Coverage check]

:heart_eyes: **pass** : 276 / 287 (96.17%)




#### file detail

|   |path|covered line|new line|coverage|
|----|----|----|----|----|
|:large_blue_circle:|io/questdb/cairo/sql/SqlExecutionCircuitBreaker.java|2|3|66.67%|
|:large_blue_circle:|io/questdb/griffin/engine/groupby/vect/GroupByNotKeyedVectorRecordCursorFactory.java|26|29|89.66%|
|:large_blue_circle:|io/questdb/griffin/SqlCompiler.java|21|23|91.30%|
|:large_blue_circle:|io/questdb/cutlass/pgwire/PGConnectionContext.java|44|46|95.65%|
|:large_blue_circle:|io/questdb/griffin/engine/table/LatestByAllIndexedRecordCursor.java|65|67|97.01%|
|:large_blue_circle:|io/questdb/griffin/engine/groupby/vect/GroupByRecordCursorFactory.java|50|51|98.04%|
|:large_blue_circle:|io/questdb/griffin/engine/table/LatestByValueListRecordCursor.java|9|9|100.00%|
|:large_blue_circle:|io/questdb/PropServerConfiguration.java|3|3|100.00%|
|:large_blue_circle:|io/questdb/griffin/engine/table/LatestByValueFilteredRecordCursor.java|3|3|100.00%|
|:large_blue_circle:|io/questdb/griffin/engine/table/LatestByAllRecordCursor.java|2|2|100.00%|
|:large_blue_circle:|io/questdb/griffin/engine/table/LatestByValuesRecordCursor.java|2|2|100.00%|
|:large_blue_circle:|io/questdb/cutlass/http/processors/JsonQueryProcessor.java|1|1|100.00%|
|:large_blue_circle:|io/questdb/griffin/engine/table/LatestByValueRecordCursor.java|3|3|100.00%|
|:large_blue_circle:|io/questdb/griffin/engine/table/LatestByValuesFilteredRecordCursor.java|2|2|100.00%|
|:large_blue_circle:|io/questdb/griffin/engine/table/LatestByValuesIndexedRecordCursor.java|3|3|100.00%|
|:large_blue_circle:|io/questdb/tasks/LatestByTask.java|3|3|100.00%|
|:large_blue_circle:|io/questdb/griffin/engine/groupby/vect/VectorAggregateEntry.java|10|10|100.00%|
|:large_blue_circle:|io/questdb/griffin/engine/analytic/CachedAnalyticRecordCursorFactory.java|7|7|100.00%|
|:large_blue_circle:|io/questdb/cairo/sql/NetworkSqlExecutionCircuitBreaker.java|12|12|100.00%|
|:large_blue_circle:|io/questdb/griffin/engine/table/LatestByValuesIndexedFilteredRecordCursor.java|2|2|100.00%|
|:large_blue_circle:|io/questdb/griffin/engine/table/LatestByAllFilteredRecordCursor.java|2|2|100.00%|
|:large_blue_circle:|io/questdb/griffin/engine/table/LatestByValueIndexedFilteredRecordCursor.java|4|4|100.00%|

**Pull request merged**
