### PR TITLE
chore(cairo): small code cleanup

### PR DESCRIPTION
**Pull request by glasstiger**
Small code cleanup, removed unused security context parameters on methods of CairoEngine.

### CODE REVIEW

**Comment by ideoma** [comment]
#### [PR Coverage check]

:heart_eyes: **pass** : 17 / 20 (85.00%)




#### file detail

|   |path|covered line|new line|coverage|
|----|----|----|----|----|
|:large_blue_circle:|io/questdb/cutlass/pgwire/PGConnectionContext.java|0|3|00.00%|
|:large_blue_circle:|io/questdb/cairo/CairoEngine.java|4|4|100.00%|
|:large_blue_circle:|io/questdb/cutlass/line/tcp/LineTcpMeasurementScheduler.java|1|1|100.00%|
|:large_blue_circle:|io/questdb/cutlass/text/CairoTextWriter.java|1|1|100.00%|
|:large_blue_circle:|io/questdb/cutlass/http/processors/TableStatusCheckProcessor.java|1|1|100.00%|
|:large_blue_circle:|io/questdb/griffin/SqlCompiler.java|8|8|100.00%|
|:large_blue_circle:|io/questdb/cutlass/line/udp/LineUdpParserImpl.java|1|1|100.00%|
|:large_blue_circle:|io/questdb/griffin/SqlOptimiser.java|1|1|100.00%|

**Comment by ideoma** [comment]
#### [PR Coverage check]

:heart_eyes: **pass** : 17 / 20 (85.00%)




#### file detail

|   |path|covered line|new line|coverage|
|----|----|----|----|----|
|:large_blue_circle:|io/questdb/cutlass/pgwire/PGConnectionContext.java|0|3|00.00%|
|:large_blue_circle:|io/questdb/cairo/CairoEngine.java|4|4|100.00%|
|:large_blue_circle:|io/questdb/cutlass/line/tcp/LineTcpMeasurementScheduler.java|1|1|100.00%|
|:large_blue_circle:|io/questdb/cutlass/text/CairoTextWriter.java|1|1|100.00%|
|:large_blue_circle:|io/questdb/cutlass/http/processors/TableStatusCheckProcessor.java|1|1|100.00%|
|:large_blue_circle:|io/questdb/griffin/SqlCompiler.java|8|8|100.00%|
|:large_blue_circle:|io/questdb/cutlass/line/udp/LineUdpParserImpl.java|1|1|100.00%|
|:large_blue_circle:|io/questdb/griffin/SqlOptimiser.java|1|1|100.00%|

**Review by ideoma — COMMENTED** [review]
Security Context supposed to be for future use

**Comment by glasstiger** [comment]
> Security Context supposed to be for future use

I would add it when needed but can close the PR if you insist. :)

**Comment by ideoma** [comment]
#### [PR Coverage check]

:heart_eyes: **pass** : 17 / 20 (85.00%)




#### file detail

|   |path|covered line|new line|coverage|
|----|----|----|----|----|
|:large_blue_circle:|io/questdb/cutlass/pgwire/PGConnectionContext.java|0|3|00.00%|
|:large_blue_circle:|io/questdb/cairo/CairoEngine.java|4|4|100.00%|
|:large_blue_circle:|io/questdb/cutlass/line/tcp/LineTcpMeasurementScheduler.java|1|1|100.00%|
|:large_blue_circle:|io/questdb/cutlass/text/CairoTextWriter.java|1|1|100.00%|
|:large_blue_circle:|io/questdb/cutlass/http/processors/TableStatusCheckProcessor.java|1|1|100.00%|
|:large_blue_circle:|io/questdb/griffin/SqlCompiler.java|8|8|100.00%|
|:large_blue_circle:|io/questdb/cutlass/line/udp/LineUdpParserImpl.java|1|1|100.00%|
|:large_blue_circle:|io/questdb/griffin/SqlOptimiser.java|1|1|100.00%|

**Comment by ideoma** [comment]
#### [PR Coverage check]

:heart_eyes: **pass** : 17 / 20 (85.00%)




#### file detail

|   |path|covered line|new line|coverage|
|----|----|----|----|----|
|:large_blue_circle:|io/questdb/cutlass/pgwire/PGConnectionContext.java|0|3|00.00%|
|:large_blue_circle:|io/questdb/cairo/CairoEngine.java|4|4|100.00%|
|:large_blue_circle:|io/questdb/cutlass/line/tcp/LineTcpMeasurementScheduler.java|1|1|100.00%|
|:large_blue_circle:|io/questdb/cutlass/text/CairoTextWriter.java|1|1|100.00%|
|:large_blue_circle:|io/questdb/cutlass/http/processors/TableStatusCheckProcessor.java|1|1|100.00%|
|:large_blue_circle:|io/questdb/griffin/SqlCompiler.java|8|8|100.00%|
|:large_blue_circle:|io/questdb/cutlass/line/udp/LineUdpParserImpl.java|1|1|100.00%|
|:large_blue_circle:|io/questdb/griffin/SqlOptimiser.java|1|1|100.00%|

**Comment by glasstiger** [comment]
Let's close this one

**Pull request closed without merging**
