### PR TITLE
fix(core): fix stale table suspended flag not cleared after auto resume on restart

### PR DESCRIPTION
**Pull request by ideoma**
When QuestDB re-tries applying transactions to a suspended state after a restart it does not change the state of the table to non-suspended if successful. This PR fixes this problem. It also ignores the suspended flag persisted in the table metadata files.

This PR also reduces file descriptor usage in SELECT/UPDATE queries by closing down file descriptors after mapping the data into the memory in `TableReaders` for all but the last partition.

### CODE REVIEW

**Comment by ideoma** [comment]
#### [PR Coverage check]

:heart_eyes: **pass** : 42 / 60 (70.00%)




#### file detail

|   |path|covered line|new line|coverage|
|----|----|----|----|----|
|:large_blue_circle:|io/questdb/griffin/engine/functions/catalogue/WalTableListFunctionFactory.java|13|29|44.83%|
|:large_blue_circle:|io/questdb/cairo/vm/MemoryCMRDetachedImpl.java|9|11|81.82%|
|:large_blue_circle:|io/questdb/cairo/TableReader.java|2|2|100.00%|
|:large_blue_circle:|io/questdb/cairo/vm/Vm.java|1|1|100.00%|
|:large_blue_circle:|io/questdb/cairo/wal/seq/SeqTxnTracker.java|7|7|100.00%|
|:large_blue_circle:|io/questdb/cairo/CairoEngine.java|1|1|100.00%|
|:large_blue_circle:|io/questdb/cairo/wal/ApplyWal2TableJob.java|5|5|100.00%|
|:large_blue_circle:|io/questdb/cairo/wal/seq/TableSequencerAPI.java|4|4|100.00%|

**Comment by ideoma** [comment]
#### [PR Coverage check]

:heart_eyes: **pass** : 83 / 89 (93.26%)




#### file detail

|   |path|covered line|new line|coverage|
|----|----|----|----|----|
|:large_blue_circle:|io/questdb/cairo/vm/MemoryCMRDetachedImpl.java|14|18|77.78%|
|:large_blue_circle:|io/questdb/cairo/TableReader.java|19|20|95.00%|
|:large_blue_circle:|io/questdb/griffin/engine/functions/catalogue/WalTableListFunctionFactory.java|33|34|97.06%|
|:large_blue_circle:|io/questdb/cairo/wal/seq/SeqTxnTracker.java|7|7|100.00%|
|:large_blue_circle:|io/questdb/cairo/CairoEngine.java|1|1|100.00%|
|:large_blue_circle:|io/questdb/cairo/wal/ApplyWal2TableJob.java|5|5|100.00%|
|:large_blue_circle:|io/questdb/cairo/wal/seq/TableSequencerAPI.java|4|4|100.00%|

**Comment by bluestreak01** [comment]
we will review and merge this after the release

**Comment by bluestreak01** [comment]
@ideoma could you please update the PR title to reflect the symptoms this fix is addressing?

**Comment by ideoma** [comment]
#### [PR Coverage check]

:heart_eyes: **pass** : 91 / 98 (92.86%)




#### file detail

|   |path|covered line|new line|coverage|
|----|----|----|----|----|
|:large_blue_circle:|io/questdb/cairo/vm/MemoryCMRDetachedImpl.java|14|18|77.78%|
|:large_blue_circle:|io/questdb/cairo/wal/ApplyWal2TableJob.java|9|10|90.00%|
|:large_blue_circle:|io/questdb/cairo/TableReader.java|19|20|95.00%|
|:large_blue_circle:|io/questdb/griffin/engine/functions/catalogue/WalTableListFunctionFactory.java|33|34|97.06%|
|:large_blue_circle:|io/questdb/cairo/wal/seq/SeqTxnTracker.java|10|10|100.00%|
|:large_blue_circle:|io/questdb/cairo/CairoEngine.java|1|1|100.00%|
|:large_blue_circle:|io/questdb/cairo/wal/seq/TableSequencerAPI.java|5|5|100.00%|

**Comment by ideoma** [comment]
#### [PR Coverage check]

:heart_eyes: **pass** : 89 / 98 (90.82%)




#### file detail

|   |path|covered line|new line|coverage|
|----|----|----|----|----|
|:large_blue_circle:|io/questdb/cairo/vm/MemoryCMRDetachedImpl.java|13|18|72.22%|
|:large_blue_circle:|io/questdb/cairo/TableReader.java|18|20|90.00%|
|:large_blue_circle:|io/questdb/cairo/wal/ApplyWal2TableJob.java|9|10|90.00%|
|:large_blue_circle:|io/questdb/griffin/engine/functions/catalogue/WalTableListFunctionFactory.java|33|34|97.06%|
|:large_blue_circle:|io/questdb/cairo/wal/seq/SeqTxnTracker.java|10|10|100.00%|
|:large_blue_circle:|io/questdb/cairo/CairoEngine.java|1|1|100.00%|
|:large_blue_circle:|io/questdb/cairo/wal/seq/TableSequencerAPI.java|5|5|100.00%|

**Review by bluestreak01 — APPROVED** [review]

**Comment by glasstiger** [comment]
#### [PR Coverage check]

:heart_eyes: **pass** : 103 / 111 (92.79%)




#### file detail

|   |path|covered line|new line|coverage|
|----|----|----|----|----|
|:large_blue_circle:|io/questdb/cairo/vm/MemoryCMRDetachedImpl.java|23|29|79.31%|
|:large_blue_circle:|io/questdb/cairo/wal/ApplyWal2TableJob.java|9|10|90.00%|
|:large_blue_circle:|io/questdb/griffin/engine/functions/catalogue/WalTableListFunctionFactory.java|33|34|97.06%|
|:large_blue_circle:|io/questdb/cairo/TableReader.java|22|22|100.00%|
|:large_blue_circle:|io/questdb/cairo/wal/seq/SeqTxnTracker.java|10|10|100.00%|
|:large_blue_circle:|io/questdb/cairo/CairoEngine.java|1|1|100.00%|
|:large_blue_circle:|io/questdb/cairo/wal/seq/TableSequencerAPI.java|5|5|100.00%|

**Comment by glasstiger** [comment]
#### [PR Coverage check]

:heart_eyes: **pass** : 100 / 107 (93.46%)




#### file detail

|   |path|covered line|new line|coverage|
|----|----|----|----|----|
|:large_blue_circle:|io/questdb/cairo/vm/MemoryCMRDetachedImpl.java|23|29|79.31%|
|:large_blue_circle:|io/questdb/griffin/engine/functions/catalogue/WalTableListFunctionFactory.java|33|34|97.06%|
|:large_blue_circle:|io/questdb/cairo/TableReader.java|22|22|100.00%|
|:large_blue_circle:|io/questdb/cairo/wal/seq/SeqTxnTracker.java|10|10|100.00%|
|:large_blue_circle:|io/questdb/cairo/CairoEngine.java|1|1|100.00%|
|:large_blue_circle:|io/questdb/cairo/wal/ApplyWal2TableJob.java|6|6|100.00%|
|:large_blue_circle:|io/questdb/cairo/wal/seq/TableSequencerAPI.java|5|5|100.00%|

**Review by bluestreak01 — APPROVED** [review]

**Comment by glasstiger** [comment]
#### [PR Coverage check]

:heart_eyes: **pass** : 138 / 145 (95.17%)




#### file detail

|   |path|covered line|new line|coverage|
|----|----|----|----|----|
|:large_blue_circle:|io/questdb/cairo/vm/MemoryCMRDetachedImpl.java|17|23|73.91%|
|:large_blue_circle:|io/questdb/griffin/engine/functions/catalogue/WalTableListFunctionFactory.java|33|34|97.06%|
|:large_blue_circle:|io/questdb/cairo/TableReader.java|66|66|100.00%|
|:large_blue_circle:|io/questdb/cairo/wal/seq/SeqTxnTracker.java|10|10|100.00%|
|:large_blue_circle:|io/questdb/cairo/CairoEngine.java|1|1|100.00%|
|:large_blue_circle:|io/questdb/cairo/wal/ApplyWal2TableJob.java|6|6|100.00%|
|:large_blue_circle:|io/questdb/cairo/wal/seq/TableSequencerAPI.java|5|5|100.00%|

**Comment by glasstiger** [comment]
#### [PR Coverage check]

:heart_eyes: **pass** : 138 / 145 (95.17%)




#### file detail

|   |path|covered line|new line|coverage|
|----|----|----|----|----|
|:large_blue_circle:|io/questdb/cairo/vm/MemoryCMRDetachedImpl.java|17|23|73.91%|
|:large_blue_circle:|io/questdb/griffin/engine/functions/catalogue/WalTableListFunctionFactory.java|33|34|97.06%|
|:large_blue_circle:|io/questdb/cairo/TableReader.java|66|66|100.00%|
|:large_blue_circle:|io/questdb/cairo/wal/seq/SeqTxnTracker.java|10|10|100.00%|
|:large_blue_circle:|io/questdb/cairo/CairoEngine.java|1|1|100.00%|
|:large_blue_circle:|io/questdb/cairo/wal/ApplyWal2TableJob.java|6|6|100.00%|
|:large_blue_circle:|io/questdb/cairo/wal/seq/TableSequencerAPI.java|5|5|100.00%|

**Comment by glasstiger** [comment]
#### [PR Coverage check]

:heart_eyes: **pass** : 138 / 145 (95.17%)




#### file detail

|   |path|covered line|new line|coverage|
|----|----|----|----|----|
|:large_blue_circle:|io/questdb/cairo/vm/MemoryCMRDetachedImpl.java|17|23|73.91%|
|:large_blue_circle:|io/questdb/griffin/engine/functions/catalogue/WalTableListFunctionFactory.java|33|34|97.06%|
|:large_blue_circle:|io/questdb/cairo/TableReader.java|66|66|100.00%|
|:large_blue_circle:|io/questdb/cairo/wal/seq/SeqTxnTracker.java|10|10|100.00%|
|:large_blue_circle:|io/questdb/cairo/CairoEngine.java|1|1|100.00%|
|:large_blue_circle:|io/questdb/cairo/wal/ApplyWal2TableJob.java|6|6|100.00%|
|:large_blue_circle:|io/questdb/cairo/wal/seq/TableSequencerAPI.java|5|5|100.00%|

**Comment by glasstiger** [comment]
#### [PR Coverage check]

:heart_eyes: **pass** : 143 / 150 (95.33%)




#### file detail

|   |path|covered line|new line|coverage|
|----|----|----|----|----|
|:large_blue_circle:|io/questdb/cairo/vm/MemoryCMRDetachedImpl.java|17|23|73.91%|
|:large_blue_circle:|io/questdb/griffin/engine/functions/catalogue/WalTableListFunctionFactory.java|33|34|97.06%|
|:large_blue_circle:|io/questdb/cairo/TableReader.java|71|71|100.00%|
|:large_blue_circle:|io/questdb/cairo/wal/seq/SeqTxnTracker.java|10|10|100.00%|
|:large_blue_circle:|io/questdb/cairo/CairoEngine.java|1|1|100.00%|
|:large_blue_circle:|io/questdb/cairo/wal/ApplyWal2TableJob.java|6|6|100.00%|
|:large_blue_circle:|io/questdb/cairo/wal/seq/TableSequencerAPI.java|5|5|100.00%|

**Comment by glasstiger** [comment]
#### [PR Coverage check]

:heart_eyes: **pass** : 143 / 150 (95.33%)




#### file detail

|   |path|covered line|new line|coverage|
|----|----|----|----|----|
|:large_blue_circle:|io/questdb/cairo/vm/MemoryCMRDetachedImpl.java|17|23|73.91%|
|:large_blue_circle:|io/questdb/griffin/engine/functions/catalogue/WalTableListFunctionFactory.java|33|34|97.06%|
|:large_blue_circle:|io/questdb/cairo/TableReader.java|71|71|100.00%|
|:large_blue_circle:|io/questdb/cairo/wal/seq/SeqTxnTracker.java|10|10|100.00%|
|:large_blue_circle:|io/questdb/cairo/CairoEngine.java|1|1|100.00%|
|:large_blue_circle:|io/questdb/cairo/wal/ApplyWal2TableJob.java|6|6|100.00%|
|:large_blue_circle:|io/questdb/cairo/wal/seq/TableSequencerAPI.java|5|5|100.00%|

**Comment by glasstiger** [comment]
#### [PR Coverage check]

:heart_eyes: **pass** : 143 / 150 (95.33%)




#### file detail

|   |path|covered line|new line|coverage|
|----|----|----|----|----|
|:large_blue_circle:|io/questdb/cairo/vm/MemoryCMRDetachedImpl.java|17|23|73.91%|
|:large_blue_circle:|io/questdb/griffin/engine/functions/catalogue/WalTableListFunctionFactory.java|33|34|97.06%|
|:large_blue_circle:|io/questdb/cairo/TableReader.java|71|71|100.00%|
|:large_blue_circle:|io/questdb/cairo/wal/seq/SeqTxnTracker.java|10|10|100.00%|
|:large_blue_circle:|io/questdb/cairo/CairoEngine.java|1|1|100.00%|
|:large_blue_circle:|io/questdb/cairo/wal/ApplyWal2TableJob.java|6|6|100.00%|
|:large_blue_circle:|io/questdb/cairo/wal/seq/TableSequencerAPI.java|5|5|100.00%|

**Review by bluestreak01 — APPROVED** [review]

**Comment by glasstiger** [comment]
#### [PR Coverage check]

:heart_eyes: **pass** : 143 / 150 (95.33%)




#### file detail

|   |path|covered line|new line|coverage|
|----|----|----|----|----|
|:large_blue_circle:|io/questdb/cairo/vm/MemoryCMRDetachedImpl.java|17|23|73.91%|
|:large_blue_circle:|io/questdb/griffin/engine/functions/catalogue/WalTableListFunctionFactory.java|33|34|97.06%|
|:large_blue_circle:|io/questdb/cairo/TableReader.java|71|71|100.00%|
|:large_blue_circle:|io/questdb/cairo/wal/seq/SeqTxnTracker.java|10|10|100.00%|
|:large_blue_circle:|io/questdb/cairo/CairoEngine.java|1|1|100.00%|
|:large_blue_circle:|io/questdb/cairo/wal/ApplyWal2TableJob.java|6|6|100.00%|
|:large_blue_circle:|io/questdb/cairo/wal/seq/TableSequencerAPI.java|5|5|100.00%|

**Pull request merged**
