### PR TITLE
fix(sql): enable parallel group-by on servers with fewer than 4 cores

### PR DESCRIPTION
**Pull request by nwoolmer**
Changed lineTcpWriterWorkerCount to default to 0 instead of 1. This field is used to dedicate threads for ILP ingestion for non-WAL tables. This will increase default eligibility for AsyncGroupBy optimisation for 4 vCPUs.

Increase minimum shared.worker.count to 4, up from 2. This increases eligibility for AsyncGroupBy optimisation for small instances <4 vCPUs.

Updated testAllDefaults() to account for new default value.

Added test for shared workers to guarantee a minimum of 4.

Changed cpuSpare to allocate one core from 16-31 cores (previously 8-15 cores) and 2 cores from 32+ cores.

Note:

This is a modification to prior default behaviour. By default, one core will no longer be dedicated to ILP for non-partitioned tables.

Without modifications to the config, this means that `shared.worker.count` will equal one thread per core I.e for 4 vCPUs, 4, instead of the prior 3.

To maintain current behaviour with a fresh config, users of non-partitioned tables will need to set the `line.tcp.writer.worker.count` config option to `1`.

Secondly, this change raises the minimum shared workers from 2 to 4, for core counts less than 4.

It is recommended to migrate non-partitioned tables to partitioned tables where possible, and to review `shared.worker.count` for your use case, as increasing this to 2 per core will often improve overall performance.

Finally, the cpuShare changes will free up a core for servers with smaller core counts.

### CODE REVIEW

**Comment by ideoma** [comment]
#### [PR Coverage check]

:heart_eyes: **pass** : 2 / 2 (100.00%)




#### file detail

|   |path|covered line|new line|coverage|
|----|----|----|----|----|
|:large_blue_circle:|io/questdb/PropServerConfiguration.java|2|2|100.00%|

**Comment by ideoma** [comment]
#### [PR Coverage check]

:heart_eyes: **pass** : 2 / 2 (100.00%)




#### file detail

|   |path|covered line|new line|coverage|
|----|----|----|----|----|
|:large_blue_circle:|io/questdb/PropServerConfiguration.java|2|2|100.00%|

**Comment by puzpuzpuz** [comment]
Disabling ILP writer pool by default makes sense to me - after all we want users to migrate to WAL tables. As for increasing the minimum `shared.worker.count` to 4, up from 2, I'm not so sure. The idea behind disabling parallel SQL execution on instances with < 5 workers was to avoid thread starvation when someone runs a "slow" query. I'd rather keep the minimum as is as disabling ILP writer pool will already enable parallel SQL on machines with 4 cores.

**Review by puzpuzpuz — DISMISSED** [review]

**Review by puzpuzpuz — APPROVED** [review]

**Comment by ideoma** [comment]
#### [PR Coverage check]

:heart_eyes: **pass** : 4 / 4 (100.00%)




#### file detail

|   |path|covered line|new line|coverage|
|----|----|----|----|----|
|:large_blue_circle:|io/questdb/PropServerConfiguration.java|4|4|100.00%|

**Pull request merged**
