### PR TITLE
chore(core): support pending table renames, sequencer drop delay

### PR DESCRIPTION
**Pull request by ideoma**
A set of changes to support pending WAL table rename. The table can be attached to the database with a temporary name suffix because another table can use the desired table name. In this case, Wal Check Job will attempt to rename to the correct table name.

Also added support for pending deletes of sequencer files of a dropped table.

### CODE REVIEW

**Comment by ideoma** [comment]
#### [PR Coverage check]

:heart_eyes: **pass** : 80 / 130 (61.54%)




#### file detail

|   |path|covered line|new line|coverage|
|----|----|----|----|----|
|:large_blue_circle:|io/questdb/cairo/CairoConfigurationWrapper.java|0|1|00.00%|
|:large_blue_circle:|io/questdb/cairo/wal/CheckWalTransactionsJob.java|4|33|12.12%|
|:large_blue_circle:|io/questdb/cairo/wal/seq/TableTransactionLog.java|14|25|56.00%|
|:large_blue_circle:|io/questdb/cairo/wal/seq/TableSequencerImpl.java|6|9|66.67%|
|:large_blue_circle:|io/questdb/cairo/CairoEngine.java|6|8|75.00%|
|:large_blue_circle:|io/questdb/cairo/wal/WalPurgeJob.java|20|24|83.33%|
|:large_blue_circle:|io/questdb/griffin/engine/functions/catalogue/TableListFunctionFactory.java|3|3|100.00%|
|:large_blue_circle:|io/questdb/cairo/wal/BasicWalInitializer.java|1|1|100.00%|
|:large_blue_circle:|io/questdb/PropServerConfiguration.java|3|3|100.00%|
|:large_blue_circle:|io/questdb/DefaultFactoryProvider.java|1|1|100.00%|
|:large_blue_circle:|io/questdb/cairo/wal/WalWriter.java|15|15|100.00%|
|:large_blue_circle:|io/questdb/cairo/TableUtils.java|1|1|100.00%|
|:large_blue_circle:|io/questdb/cairo/DefaultCairoConfiguration.java|1|1|100.00%|
|:large_blue_circle:|io/questdb/FactoryProviderImpl.java|1|1|100.00%|
|:large_blue_circle:|io/questdb/cairo/wal/seq/EmptyOperationCursor.java|1|1|100.00%|
|:large_blue_circle:|io/questdb/ServerMain.java|1|1|100.00%|
|:large_blue_circle:|io/questdb/PropertyKey.java|2|2|100.00%|

**Comment by ideoma** [comment]
#### [PR Coverage check]

:heart_eyes: **pass** : 77 / 129 (59.69%)




#### file detail

|   |path|covered line|new line|coverage|
|----|----|----|----|----|
|:large_blue_circle:|io/questdb/DefaultFactoryProvider.java|0|1|00.00%|
|:large_blue_circle:|io/questdb/FactoryProviderImpl.java|0|1|00.00%|
|:large_blue_circle:|io/questdb/cairo/CairoConfigurationWrapper.java|0|1|00.00%|
|:large_blue_circle:|io/questdb/cairo/wal/CheckWalTransactionsJob.java|4|33|12.12%|
|:large_blue_circle:|io/questdb/cairo/wal/seq/TableTransactionLog.java|14|25|56.00%|
|:large_blue_circle:|io/questdb/cairo/wal/seq/TableSequencerImpl.java|6|9|66.67%|
|:large_blue_circle:|io/questdb/cairo/CairoEngine.java|6|8|75.00%|
|:large_blue_circle:|io/questdb/cairo/wal/WalPurgeJob.java|20|24|83.33%|
|:large_blue_circle:|io/questdb/griffin/engine/functions/catalogue/TableListFunctionFactory.java|3|3|100.00%|
|:large_blue_circle:|io/questdb/cairo/wal/BasicWalInitializer.java|1|1|100.00%|
|:large_blue_circle:|io/questdb/PropServerConfiguration.java|2|2|100.00%|
|:large_blue_circle:|io/questdb/cairo/wal/WalWriter.java|15|15|100.00%|
|:large_blue_circle:|io/questdb/cairo/TableUtils.java|1|1|100.00%|
|:large_blue_circle:|io/questdb/cairo/DefaultCairoConfiguration.java|1|1|100.00%|
|:large_blue_circle:|io/questdb/cairo/wal/seq/EmptyOperationCursor.java|1|1|100.00%|
|:large_blue_circle:|io/questdb/ServerMain.java|1|1|100.00%|
|:large_blue_circle:|io/questdb/PropertyKey.java|2|2|100.00%|

**Comment by ideoma** [comment]
#### [PR Coverage check]

:heart_eyes: **pass** : 76 / 128 (59.38%)




#### file detail

|   |path|covered line|new line|coverage|
|----|----|----|----|----|
|:large_blue_circle:|io/questdb/DefaultFactoryProvider.java|0|1|00.00%|
|:large_blue_circle:|io/questdb/FactoryProviderImpl.java|0|1|00.00%|
|:large_blue_circle:|io/questdb/cairo/CairoConfigurationWrapper.java|0|1|00.00%|
|:large_blue_circle:|io/questdb/cairo/wal/CheckWalTransactionsJob.java|3|32|09.38%|
|:large_blue_circle:|io/questdb/cairo/wal/seq/TableTransactionLog.java|14|25|56.00%|
|:large_blue_circle:|io/questdb/cairo/wal/seq/TableSequencerImpl.java|6|9|66.67%|
|:large_blue_circle:|io/questdb/cairo/CairoEngine.java|6|8|75.00%|
|:large_blue_circle:|io/questdb/cairo/wal/WalPurgeJob.java|20|24|83.33%|
|:large_blue_circle:|io/questdb/griffin/engine/functions/catalogue/TableListFunctionFactory.java|3|3|100.00%|
|:large_blue_circle:|io/questdb/cairo/wal/BasicWalInitializer.java|1|1|100.00%|
|:large_blue_circle:|io/questdb/PropServerConfiguration.java|2|2|100.00%|
|:large_blue_circle:|io/questdb/cairo/wal/WalWriter.java|15|15|100.00%|
|:large_blue_circle:|io/questdb/cairo/TableUtils.java|1|1|100.00%|
|:large_blue_circle:|io/questdb/cairo/DefaultCairoConfiguration.java|1|1|100.00%|
|:large_blue_circle:|io/questdb/cairo/wal/seq/EmptyOperationCursor.java|1|1|100.00%|
|:large_blue_circle:|io/questdb/ServerMain.java|1|1|100.00%|
|:large_blue_circle:|io/questdb/PropertyKey.java|2|2|100.00%|

**Comment by ideoma** [comment]
#### [PR Coverage check]

:heart_eyes: **pass** : 76 / 128 (59.38%)




#### file detail

|   |path|covered line|new line|coverage|
|----|----|----|----|----|
|:large_blue_circle:|io/questdb/DefaultFactoryProvider.java|0|1|00.00%|
|:large_blue_circle:|io/questdb/FactoryProviderImpl.java|0|1|00.00%|
|:large_blue_circle:|io/questdb/cairo/CairoConfigurationWrapper.java|0|1|00.00%|
|:large_blue_circle:|io/questdb/cairo/wal/CheckWalTransactionsJob.java|3|32|09.38%|
|:large_blue_circle:|io/questdb/cairo/wal/seq/TableTransactionLog.java|14|25|56.00%|
|:large_blue_circle:|io/questdb/cairo/wal/seq/TableSequencerImpl.java|6|9|66.67%|
|:large_blue_circle:|io/questdb/cairo/CairoEngine.java|6|8|75.00%|
|:large_blue_circle:|io/questdb/cairo/wal/WalPurgeJob.java|20|24|83.33%|
|:large_blue_circle:|io/questdb/griffin/engine/functions/catalogue/TableListFunctionFactory.java|3|3|100.00%|
|:large_blue_circle:|io/questdb/cairo/wal/BasicWalInitializer.java|1|1|100.00%|
|:large_blue_circle:|io/questdb/PropServerConfiguration.java|2|2|100.00%|
|:large_blue_circle:|io/questdb/cairo/wal/WalWriter.java|15|15|100.00%|
|:large_blue_circle:|io/questdb/cairo/TableUtils.java|1|1|100.00%|
|:large_blue_circle:|io/questdb/cairo/DefaultCairoConfiguration.java|1|1|100.00%|
|:large_blue_circle:|io/questdb/cairo/wal/seq/EmptyOperationCursor.java|1|1|100.00%|
|:large_blue_circle:|io/questdb/ServerMain.java|1|1|100.00%|
|:large_blue_circle:|io/questdb/PropertyKey.java|2|2|100.00%|

**Comment by ideoma** [comment]
#### [PR Coverage check]

:heart_eyes: **pass** : 75 / 125 (60.00%)




#### file detail

|   |path|covered line|new line|coverage|
|----|----|----|----|----|
|:large_blue_circle:|io/questdb/cairo/CairoConfigurationWrapper.java|0|1|00.00%|
|:large_blue_circle:|io/questdb/cairo/wal/CheckWalTransactionsJob.java|3|32|09.38%|
|:large_blue_circle:|io/questdb/cairo/wal/seq/TableTransactionLog.java|14|25|56.00%|
|:large_blue_circle:|io/questdb/cairo/wal/seq/TableSequencerImpl.java|6|9|66.67%|
|:large_blue_circle:|io/questdb/cairo/CairoEngine.java|6|8|75.00%|
|:large_blue_circle:|io/questdb/cairo/wal/WalPurgeJob.java|20|24|83.33%|
|:large_blue_circle:|io/questdb/griffin/engine/functions/catalogue/TableListFunctionFactory.java|2|2|100.00%|
|:large_blue_circle:|io/questdb/PropServerConfiguration.java|2|2|100.00%|
|:large_blue_circle:|io/questdb/cairo/wal/WalWriter.java|15|15|100.00%|
|:large_blue_circle:|io/questdb/cairo/TableUtils.java|1|1|100.00%|
|:large_blue_circle:|io/questdb/cairo/DefaultCairoConfiguration.java|1|1|100.00%|
|:large_blue_circle:|io/questdb/cairo/wal/seq/EmptyOperationCursor.java|1|1|100.00%|
|:large_blue_circle:|io/questdb/ServerMain.java|1|1|100.00%|
|:large_blue_circle:|io/questdb/PropertyKey.java|2|2|100.00%|
|:large_blue_circle:|io/questdb/cairo/wal/DefaultWalInitializer.java|1|1|100.00%|

**Review by eugenels — APPROVED** [review]
looks good

**Comment by ideoma** [comment]
#### [PR Coverage check]

:heart_eyes: **pass** : 75 / 125 (60.00%)




#### file detail

|   |path|covered line|new line|coverage|
|----|----|----|----|----|
|:large_blue_circle:|io/questdb/cairo/CairoConfigurationWrapper.java|0|1|00.00%|
|:large_blue_circle:|io/questdb/cairo/wal/CheckWalTransactionsJob.java|3|32|09.38%|
|:large_blue_circle:|io/questdb/cairo/wal/seq/TableTransactionLog.java|14|25|56.00%|
|:large_blue_circle:|io/questdb/cairo/wal/seq/TableSequencerImpl.java|6|9|66.67%|
|:large_blue_circle:|io/questdb/cairo/CairoEngine.java|6|8|75.00%|
|:large_blue_circle:|io/questdb/cairo/wal/WalPurgeJob.java|20|24|83.33%|
|:large_blue_circle:|io/questdb/griffin/engine/functions/catalogue/TableListFunctionFactory.java|2|2|100.00%|
|:large_blue_circle:|io/questdb/PropServerConfiguration.java|2|2|100.00%|
|:large_blue_circle:|io/questdb/cairo/wal/WalWriter.java|15|15|100.00%|
|:large_blue_circle:|io/questdb/cairo/TableUtils.java|1|1|100.00%|
|:large_blue_circle:|io/questdb/cairo/DefaultCairoConfiguration.java|1|1|100.00%|
|:large_blue_circle:|io/questdb/cairo/wal/seq/EmptyOperationCursor.java|1|1|100.00%|
|:large_blue_circle:|io/questdb/ServerMain.java|1|1|100.00%|
|:large_blue_circle:|io/questdb/PropertyKey.java|2|2|100.00%|
|:large_blue_circle:|io/questdb/cairo/wal/DefaultWalInitializer.java|1|1|100.00%|

**Pull request merged**
