### PR TITLE
feat: support Postgres literal cast

### LINKED ISSUE #740: Postgres timestamp function
It seems questdb doesn't support the "timestamp" function.
https://www.postgresql.org/docs/12/functions-datetime.html

**To Reproduce**
insert into "test" ("test_timestamp","test_value") 
values (timestamp with time zone '2020-12-31 15:15:51.663+00:00', '256')

**Expected behavior**
Data being inserted

**Current behavior**
[18:05:05] insert into "test" ("test_timestamp","test_value") 
values (timestamp with time zone '2020-12-31 15:15:51.663+00:00', '256')  ')' expected

**Environment (please complete the following information):**
 - QuestDB 5.0.5

### PR DESCRIPTION
**Pull request by ideoma**
support cast to "timestamp with time zone" as timestamp
closes #740, #980

### CODE REVIEW

**Comment by ideoma** [comment]
#### [PR Coverage check]

:heart_eyes: **pass** : 28 / 31 (90.32%)




#### file detail

|   |path|covered line|new line|coverage|
|----|----|----|----|----|
|:large_blue_circle:|io/questdb/griffin/SqlKeywords.java|12|14|85.71%|
|:large_blue_circle:|io/questdb/griffin/ExpressionParser.java|15|16|93.75%|
|:large_blue_circle:|io/questdb/griffin/SqlParser.java|1|1|100.00%|

**Comment by ideoma** [comment]
#### [PR Coverage check]

:heart_eyes: **pass** : 46 / 47 (97.87%)




#### file detail

|   |path|covered line|new line|coverage|
|----|----|----|----|----|
|:large_blue_circle:|io/questdb/griffin/engine/functions/catalogue/ShowTimeZoneFactory.java|9|10|90.00%|
|:large_blue_circle:|io/questdb/griffin/SqlKeywords.java|14|14|100.00%|
|:large_blue_circle:|io/questdb/griffin/SqlParser.java|1|1|100.00%|
|:large_blue_circle:|io/questdb/griffin/ExpressionParser.java|16|16|100.00%|
|:large_blue_circle:|io/questdb/griffin/SqlCompiler.java|6|6|100.00%|

**Comment by ideoma** [comment]
#### [PR Coverage check]

:heart_eyes: **pass** : 47 / 47 (100.00%)




#### file detail

|   |path|covered line|new line|coverage|
|----|----|----|----|----|
|:large_blue_circle:|io/questdb/griffin/SqlKeywords.java|14|14|100.00%|
|:large_blue_circle:|io/questdb/griffin/SqlParser.java|1|1|100.00%|
|:large_blue_circle:|io/questdb/griffin/engine/functions/catalogue/ShowTimeZoneFactory.java|10|10|100.00%|
|:large_blue_circle:|io/questdb/griffin/ExpressionParser.java|16|16|100.00%|
|:large_blue_circle:|io/questdb/griffin/SqlCompiler.java|6|6|100.00%|

**Review by bluestreak01 — APPROVED** [review]

**Comment by ideoma** [comment]
#### [PR Coverage check]

:heart_eyes: **pass** : 47 / 47 (100.00%)




#### file detail

|   |path|covered line|new line|coverage|
|----|----|----|----|----|
|:large_blue_circle:|io/questdb/griffin/SqlKeywords.java|14|14|100.00%|
|:large_blue_circle:|io/questdb/griffin/SqlParser.java|1|1|100.00%|
|:large_blue_circle:|io/questdb/griffin/engine/functions/catalogue/ShowTimeZoneFactory.java|10|10|100.00%|
|:large_blue_circle:|io/questdb/griffin/ExpressionParser.java|16|16|100.00%|
|:large_blue_circle:|io/questdb/griffin/SqlCompiler.java|6|6|100.00%|

**Pull request merged**
