### PR TITLE
chore(core): replace busy spinning with LockSupport#park() in count down latches

### PR DESCRIPTION
**Pull request by puzpuzpuz**

### CODE REVIEW

**Comment by ideoma** [comment]
#### [PR Coverage check]

:heart_eyes: **pass** : 11 / 11 (100.00%)




#### file detail

|   |path|covered line|new line|coverage|
|----|----|----|----|----|
|:large_blue_circle:|io/questdb/mp/SOCountDownLatch.java|1|1|100.00%|
|:large_blue_circle:|io/questdb/mp/SOUnboundedCountDownLatch.java|10|10|100.00%|

**Comment by ideoma** [comment]
#### [PR Coverage check]

:heart_eyes: **pass** : 14 / 14 (100.00%)




#### file detail

|   |path|covered line|new line|coverage|
|----|----|----|----|----|
|:large_blue_circle:|io/questdb/mp/SOCountDownLatch.java|1|1|100.00%|
|:large_blue_circle:|io/questdb/mp/SOUnboundedCountDownLatch.java|13|13|100.00%|

**Review by amunra — DISMISSED** [review]
This looks good to me.

Internally `park` and `unpark` use a condition variable. So this is exactly what we want.
I've read through the code and I don't think this would cause any allocations.

```
void Parker::unpark() {
  int status = pthread_mutex_lock(_mutex);
  assert_status(status == 0, status, "invariant");
  const int s = _counter;
  _counter = 1;
  // must capture correct index before unlocking
  int index = _cur_index;
  status = pthread_mutex_unlock(_mutex);
  assert_status(status == 0, status, "invariant");

  // Note that we signal() *after* dropping the lock for "immortal" Events.
  // This is safe and avoids a common class of futile wakeups.  In rare
  // circumstances this can cause a thread to return prematurely from
  // cond_{timed}wait() but the spurious wakeup is benign and the victim
  // will simply re-test the condition and re-park itself.
  // This provides particular benefit if the underlying platform does not
  // provide wait morphing.

  if (s < 1 && index != -1) {
    // thread is definitely parked
    status = pthread_cond_signal(&_cond[index]);
    assert_status(status == 0, status, "invariant");
  }
}
```

Nice one!

**Review by bluestreak01 — CHANGES_REQUESTED** [review]
Can we please run benchmarks before and after ? There is micro-bench, testing latencies of various "sleep" methods. We have been thru exercise of working out whichever has min overhead across platforms.

**Comment by puzpuzpuz** [comment]
> Can we please run benchmarks before and after ? There is micro-bench, testing latencies of various "sleep" methods. We have been thru exercise of working out whichever has min overhead across platforms.

I failed to find the microbenchmark, so I've added one in a325a6d1949740ba6e18d19c938a2351a4f8c7ff (and also ported table writer benchmark improvements from one of previous closed PRs).

`SOCountDownLatch#await()` with `LockSupport.park()` call:
```
Benchmark                                    Mode  Cnt      Score      Error  Units
SOCountDownLatchBenchmark.testBaseline       avgt    3  77826.005 ± 6612.967  ns/op
SOCountDownLatchBenchmark.testLatchPingPong  avgt    3  89269.286 ± 2395.790  ns/op
```

`SOCountDownLatch#await()` with `Os.sleep()` call:
```
Benchmark                                    Mode  Cnt      Score      Error  Units
SOCountDownLatchBenchmark.testBaseline       avgt    3  78256.196 ± 5877.293  ns/op
SOCountDownLatchBenchmark.testLatchPingPong  avgt    3  89704.706 ± 2119.867  ns/op
```

So, no noticeable difference in latency, at least in this benchmark.

**Comment by ideoma** [comment]
#### [PR Coverage check]

:heart_eyes: **pass** : 14 / 14 (100.00%)




#### file detail

|   |path|covered line|new line|coverage|
|----|----|----|----|----|
|:large_blue_circle:|io/questdb/mp/SOCountDownLatch.java|1|1|100.00%|
|:large_blue_circle:|io/questdb/mp/SOUnboundedCountDownLatch.java|13|13|100.00%|

**Pull request merged**
