### PR TITLE
fix(wal): fix wal table suspension on a race condition

### PR DESCRIPTION
**Pull request by ideoma**
Fixes error in reading WAL-E files when `rollback()` is called in the WAL Writer concurrently. 

```
2023-02-23T12:21:03.152610Z C i.q.c.w.ApplyWal2TableJob WAL apply job failed, table suspended [table=testWalMetadataChangeHeavy_wal_parallel~2, error=segment /var/folders/24/8k48jl6d249_n_qfxwsl6xvm0000gn/T/junit9998452327719299136/dbRoot/testWalMetadataChangeHeavy_wal_parallel~2/wal1/5/_event.i does not have txn with id 0, errno=2]
```

### CODE REVIEW

**Comment by ideoma** [comment]
#### [PR Coverage check]

:disappointed: **fail** : 1 / 7 (14.29%)




#### file detail

|   |path|covered line|new line|coverage|
|----|----|----|----|----|
|:large_blue_circle:|io/questdb/cairo/wal/WalEventReader.java|0|6|00.00%|
|:large_blue_circle:|io/questdb/cairo/wal/WalWriterEvents.java|1|1|100.00%|

**Review by bluestreak01 — DISMISSED** [review]

**Comment by ideoma** [comment]
#### [PR Coverage check]

:disappointed: **fail** : 1 / 7 (14.29%)




#### file detail

|   |path|covered line|new line|coverage|
|----|----|----|----|----|
|:large_blue_circle:|io/questdb/cairo/wal/WalEventReader.java|0|6|00.00%|
|:large_blue_circle:|io/questdb/cairo/wal/WalWriterEvents.java|1|1|100.00%|

**Comment by ideoma** [comment]
#### [PR Coverage check]

:heart_eyes: **pass** : 7 / 7 (100.00%)




#### file detail

|   |path|covered line|new line|coverage|
|----|----|----|----|----|
|:large_blue_circle:|io/questdb/cairo/wal/WalWriterEvents.java|1|1|100.00%|
|:large_blue_circle:|io/questdb/cairo/wal/WalEventReader.java|6|6|100.00%|

**Comment by ideoma** [comment]
#### [PR Coverage check]

:heart_eyes: **pass** : 7 / 7 (100.00%)




#### file detail

|   |path|covered line|new line|coverage|
|----|----|----|----|----|
|:large_blue_circle:|io/questdb/cairo/wal/WalWriterEvents.java|1|1|100.00%|
|:large_blue_circle:|io/questdb/cairo/wal/WalEventReader.java|6|6|100.00%|

**Review by bluestreak01 — APPROVED** [review]

**Pull request merged**
