### PR TITLE
chore: increase default dispatcher connection limit

### PR DESCRIPTION
**Pull request by ideoma**
add timeout wait in SOUnboundedCountDownLatch

### CODE REVIEW

**Comment by ideoma** [comment]
#### [PR Coverage check]

:heart_eyes: **pass** : 4 / 4 (100.00%)




#### file detail

|   |path|covered line|new line|coverage|
|----|----|----|----|----|
|:large_blue_circle:|io/questdb/network/DefaultIODispatcherConfiguration.java|1|1|100.00%|
|:large_blue_circle:|io/questdb/mp/SOUnboundedCountDownLatch.java|3|3|100.00%|

**Comment by ideoma** [comment]
#### [PR Coverage check]

:heart_eyes: **pass** : 4 / 4 (100.00%)




#### file detail

|   |path|covered line|new line|coverage|
|----|----|----|----|----|
|:large_blue_circle:|io/questdb/network/DefaultIODispatcherConfiguration.java|1|1|100.00%|
|:large_blue_circle:|io/questdb/mp/SOUnboundedCountDownLatch.java|3|3|100.00%|

**Comment by ideoma** [comment]
#### [PR Coverage check]

:heart_eyes: **pass** : 12 / 12 (100.00%)




#### file detail

|   |path|covered line|new line|coverage|
|----|----|----|----|----|
|:large_blue_circle:|io/questdb/network/AbstractIODispatcher.java|3|3|100.00%|
|:large_blue_circle:|io/questdb/network/IODispatcherConfiguration.java|1|1|100.00%|
|:large_blue_circle:|io/questdb/network/DefaultIODispatcherConfiguration.java|5|5|100.00%|
|:large_blue_circle:|io/questdb/mp/SOUnboundedCountDownLatch.java|3|3|100.00%|

**Comment by ideoma** [comment]
#### [PR Coverage check]

:heart_eyes: **pass** : 101 / 165 (61.21%)




#### file detail

|   |path|covered line|new line|coverage|
|----|----|----|----|----|
|:large_blue_circle:|io/questdb/network/IODispatcherOsx.java|0|1|00.00%|
|:large_blue_circle:|io/questdb/network/IODispatcherWindows.java|0|1|00.00%|
|:large_blue_circle:|io/questdb/network/NetworkFacadeImpl.java|0|1|00.00%|
|:large_blue_circle:|io/questdb/cutlass/http/processors/JsonQueryProcessor.java|0|4|00.00%|
|:large_blue_circle:|io/questdb/cutlass/http/processors/TextImportProcessor.java|6|26|23.08%|
|:large_blue_circle:|io/questdb/cutlass/http/HttpResponseSink.java|2|3|66.67%|
|:large_blue_circle:|io/questdb/cutlass/http/HttpConnectionContext.java|70|105|66.67%|
|:large_blue_circle:|io/questdb/network/AbstractIODispatcher.java|13|14|92.86%|
|:large_blue_circle:|io/questdb/network/DefaultIODispatcherConfiguration.java|5|5|100.00%|
|:large_blue_circle:|io/questdb/mp/SOUnboundedCountDownLatch.java|3|3|100.00%|
|:large_blue_circle:|io/questdb/network/IODispatcherLinux.java|1|1|100.00%|
|:large_blue_circle:|io/questdb/network/IODispatcherConfiguration.java|1|1|100.00%|

**Comment by ideoma** [comment]
#### [PR Coverage check]

:heart_eyes: **pass** : 103 / 165 (62.42%)




#### file detail

|   |path|covered line|new line|coverage|
|----|----|----|----|----|
|:large_blue_circle:|io/questdb/network/IODispatcherOsx.java|0|1|00.00%|
|:large_blue_circle:|io/questdb/network/IODispatcherWindows.java|0|1|00.00%|
|:large_blue_circle:|io/questdb/network/NetworkFacadeImpl.java|0|1|00.00%|
|:large_blue_circle:|io/questdb/cutlass/http/processors/JsonQueryProcessor.java|0|4|00.00%|
|:large_blue_circle:|io/questdb/cutlass/http/processors/TextImportProcessor.java|6|26|23.08%|
|:large_blue_circle:|io/questdb/cutlass/http/HttpResponseSink.java|2|3|66.67%|
|:large_blue_circle:|io/questdb/cutlass/http/HttpConnectionContext.java|72|105|68.57%|
|:large_blue_circle:|io/questdb/network/AbstractIODispatcher.java|13|14|92.86%|
|:large_blue_circle:|io/questdb/network/DefaultIODispatcherConfiguration.java|5|5|100.00%|
|:large_blue_circle:|io/questdb/mp/SOUnboundedCountDownLatch.java|3|3|100.00%|
|:large_blue_circle:|io/questdb/network/IODispatcherLinux.java|1|1|100.00%|
|:large_blue_circle:|io/questdb/network/IODispatcherConfiguration.java|1|1|100.00%|

**Comment by ideoma** [comment]
#### [PR Coverage check]

:heart_eyes: **pass** : 119 / 165 (72.12%)




#### file detail

|   |path|covered line|new line|coverage|
|----|----|----|----|----|
|:large_blue_circle:|io/questdb/network/IODispatcherOsx.java|0|1|00.00%|
|:large_blue_circle:|io/questdb/network/IODispatcherWindows.java|0|1|00.00%|
|:large_blue_circle:|io/questdb/cutlass/http/processors/JsonQueryProcessor.java|0|4|00.00%|
|:large_blue_circle:|io/questdb/cutlass/http/processors/TextImportProcessor.java|13|26|50.00%|
|:large_blue_circle:|io/questdb/cutlass/http/HttpResponseSink.java|2|3|66.67%|
|:large_blue_circle:|io/questdb/cutlass/http/HttpConnectionContext.java|80|105|76.19%|
|:large_blue_circle:|io/questdb/network/AbstractIODispatcher.java|13|14|92.86%|
|:large_blue_circle:|io/questdb/network/NetworkFacadeImpl.java|1|1|100.00%|
|:large_blue_circle:|io/questdb/network/DefaultIODispatcherConfiguration.java|5|5|100.00%|
|:large_blue_circle:|io/questdb/mp/SOUnboundedCountDownLatch.java|3|3|100.00%|
|:large_blue_circle:|io/questdb/network/IODispatcherLinux.java|1|1|100.00%|
|:large_blue_circle:|io/questdb/network/IODispatcherConfiguration.java|1|1|100.00%|

**Comment by ideoma** [comment]
#### [PR Coverage check]

:heart_eyes: **pass** : 123 / 165 (74.55%)




#### file detail

|   |path|covered line|new line|coverage|
|----|----|----|----|----|
|:large_blue_circle:|io/questdb/network/IODispatcherOsx.java|0|1|00.00%|
|:large_blue_circle:|io/questdb/network/IODispatcherWindows.java|0|1|00.00%|
|:large_blue_circle:|io/questdb/cutlass/http/processors/JsonQueryProcessor.java|0|4|00.00%|
|:large_blue_circle:|io/questdb/cutlass/http/processors/TextImportProcessor.java|13|26|50.00%|
|:large_blue_circle:|io/questdb/cutlass/http/HttpResponseSink.java|2|3|66.67%|
|:large_blue_circle:|io/questdb/cutlass/http/HttpConnectionContext.java|84|105|80.00%|
|:large_blue_circle:|io/questdb/network/AbstractIODispatcher.java|13|14|92.86%|
|:large_blue_circle:|io/questdb/network/NetworkFacadeImpl.java|1|1|100.00%|
|:large_blue_circle:|io/questdb/network/DefaultIODispatcherConfiguration.java|5|5|100.00%|
|:large_blue_circle:|io/questdb/mp/SOUnboundedCountDownLatch.java|3|3|100.00%|
|:large_blue_circle:|io/questdb/network/IODispatcherLinux.java|1|1|100.00%|
|:large_blue_circle:|io/questdb/network/IODispatcherConfiguration.java|1|1|100.00%|

**Comment by ideoma** [comment]
#### [PR Coverage check]

:heart_eyes: **pass** : 117 / 165 (70.91%)




#### file detail

|   |path|covered line|new line|coverage|
|----|----|----|----|----|
|:large_blue_circle:|io/questdb/network/IODispatcherOsx.java|0|1|00.00%|
|:large_blue_circle:|io/questdb/network/IODispatcherWindows.java|0|1|00.00%|
|:large_blue_circle:|io/questdb/cutlass/http/processors/JsonQueryProcessor.java|0|4|00.00%|
|:large_blue_circle:|io/questdb/cutlass/http/processors/TextImportProcessor.java|13|26|50.00%|
|:large_blue_circle:|io/questdb/cutlass/http/HttpResponseSink.java|2|3|66.67%|
|:large_blue_circle:|io/questdb/cutlass/http/HttpConnectionContext.java|78|105|74.29%|
|:large_blue_circle:|io/questdb/network/AbstractIODispatcher.java|13|14|92.86%|
|:large_blue_circle:|io/questdb/network/NetworkFacadeImpl.java|1|1|100.00%|
|:large_blue_circle:|io/questdb/network/DefaultIODispatcherConfiguration.java|5|5|100.00%|
|:large_blue_circle:|io/questdb/mp/SOUnboundedCountDownLatch.java|3|3|100.00%|
|:large_blue_circle:|io/questdb/network/IODispatcherLinux.java|1|1|100.00%|
|:large_blue_circle:|io/questdb/network/IODispatcherConfiguration.java|1|1|100.00%|

**Review by bluestreak01 — APPROVED** [review]

**Review by ideoma — COMMENTED** [review]
LGTM

**Pull request merged**
