### PR TITLE
fix(wal): fix cleaning up after dropped tables

### PR DESCRIPTION
**Pull request by ideoma**
Sometimes when QuestDB is restarted often some dropped tables can be left on the disk and QuestDB logs a critical error on startup that they will not be available to query. This happens especially often on Windows.

Also removes the error message

 ```
2023-02-22T14:25:55.185855Z E i.q.c.O3PartitionPurgeJob unknown directory [table=cpu~2741, dir=txn_seq]
```

### CODE REVIEW

**Comment by ideoma** [comment]
#### [PR Coverage check]

:heart_eyes: **pass** : 40 / 61 (65.57%)




#### file detail

|   |path|covered line|new line|coverage|
|----|----|----|----|----|
|:large_blue_circle:|io/questdb/cairo/DefaultCairoConfiguration.java|0|2|00.00%|
|:large_blue_circle:|io/questdb/cairo/wal/seq/TableSequencerAPI.java|10|21|47.62%|
|:large_blue_circle:|io/questdb/cairo/wal/WalPurgeJob.java|5|10|50.00%|
|:large_blue_circle:|io/questdb/cairo/wal/ApplyWal2TableJob.java|2|4|50.00%|
|:large_blue_circle:|io/questdb/cairo/CairoException.java|1|2|50.00%|
|:large_blue_circle:|io/questdb/PropServerConfiguration.java|2|2|100.00%|
|:large_blue_circle:|io/questdb/cairo/wal/seq/TableSequencerImpl.java|1|1|100.00%|
|:large_blue_circle:|io/questdb/cairo/O3PartitionPurgeJob.java|1|1|100.00%|
|:large_blue_circle:|io/questdb/PropertyKey.java|2|2|100.00%|
|:large_blue_circle:|io/questdb/cairo/TableNameRegistryFileStore.java|16|16|100.00%|

**Comment by ideoma** [comment]
#### [PR Coverage check]

:heart_eyes: **pass** : 40 / 61 (65.57%)




#### file detail

|   |path|covered line|new line|coverage|
|----|----|----|----|----|
|:large_blue_circle:|io/questdb/cairo/DefaultCairoConfiguration.java|0|2|00.00%|
|:large_blue_circle:|io/questdb/cairo/wal/seq/TableSequencerAPI.java|10|21|47.62%|
|:large_blue_circle:|io/questdb/cairo/wal/WalPurgeJob.java|5|10|50.00%|
|:large_blue_circle:|io/questdb/cairo/wal/ApplyWal2TableJob.java|2|4|50.00%|
|:large_blue_circle:|io/questdb/cairo/CairoException.java|1|2|50.00%|
|:large_blue_circle:|io/questdb/PropServerConfiguration.java|2|2|100.00%|
|:large_blue_circle:|io/questdb/cairo/wal/seq/TableSequencerImpl.java|1|1|100.00%|
|:large_blue_circle:|io/questdb/cairo/O3PartitionPurgeJob.java|1|1|100.00%|
|:large_blue_circle:|io/questdb/PropertyKey.java|2|2|100.00%|
|:large_blue_circle:|io/questdb/cairo/TableNameRegistryFileStore.java|16|16|100.00%|

**Comment by ideoma** [comment]
#### [PR Coverage check]

:heart_eyes: **pass** : 40 / 61 (65.57%)




#### file detail

|   |path|covered line|new line|coverage|
|----|----|----|----|----|
|:large_blue_circle:|io/questdb/cairo/DefaultCairoConfiguration.java|0|2|00.00%|
|:large_blue_circle:|io/questdb/cairo/wal/seq/TableSequencerAPI.java|10|21|47.62%|
|:large_blue_circle:|io/questdb/cairo/wal/WalPurgeJob.java|5|10|50.00%|
|:large_blue_circle:|io/questdb/cairo/wal/ApplyWal2TableJob.java|2|4|50.00%|
|:large_blue_circle:|io/questdb/cairo/CairoException.java|1|2|50.00%|
|:large_blue_circle:|io/questdb/PropServerConfiguration.java|2|2|100.00%|
|:large_blue_circle:|io/questdb/cairo/wal/seq/TableSequencerImpl.java|1|1|100.00%|
|:large_blue_circle:|io/questdb/cairo/O3PartitionPurgeJob.java|1|1|100.00%|
|:large_blue_circle:|io/questdb/PropertyKey.java|2|2|100.00%|
|:large_blue_circle:|io/questdb/cairo/TableNameRegistryFileStore.java|16|16|100.00%|

**Comment by ideoma** [comment]
#### [PR Coverage check]

:heart_eyes: **pass** : 40 / 61 (65.57%)




#### file detail

|   |path|covered line|new line|coverage|
|----|----|----|----|----|
|:large_blue_circle:|io/questdb/cairo/DefaultCairoConfiguration.java|0|2|00.00%|
|:large_blue_circle:|io/questdb/cairo/wal/seq/TableSequencerAPI.java|10|21|47.62%|
|:large_blue_circle:|io/questdb/cairo/wal/WalPurgeJob.java|5|10|50.00%|
|:large_blue_circle:|io/questdb/cairo/wal/ApplyWal2TableJob.java|2|4|50.00%|
|:large_blue_circle:|io/questdb/cairo/CairoException.java|1|2|50.00%|
|:large_blue_circle:|io/questdb/PropServerConfiguration.java|2|2|100.00%|
|:large_blue_circle:|io/questdb/cairo/wal/seq/TableSequencerImpl.java|1|1|100.00%|
|:large_blue_circle:|io/questdb/cairo/O3PartitionPurgeJob.java|1|1|100.00%|
|:large_blue_circle:|io/questdb/PropertyKey.java|2|2|100.00%|
|:large_blue_circle:|io/questdb/cairo/TableNameRegistryFileStore.java|16|16|100.00%|

**Comment by ideoma** [comment]
#### [PR Coverage check]

:heart_eyes: **pass** : 45 / 57 (78.95%)




#### file detail

|   |path|covered line|new line|coverage|
|----|----|----|----|----|
|:large_blue_circle:|io/questdb/cairo/DefaultCairoConfiguration.java|0|2|00.00%|
|:large_blue_circle:|io/questdb/cairo/wal/seq/TableSequencerAPI.java|10|17|58.82%|
|:large_blue_circle:|io/questdb/cairo/wal/ApplyWal2TableJob.java|3|5|60.00%|
|:large_blue_circle:|io/questdb/cairo/wal/WalPurgeJob.java|8|9|88.89%|
|:large_blue_circle:|io/questdb/PropServerConfiguration.java|2|2|100.00%|
|:large_blue_circle:|io/questdb/cairo/wal/seq/TableSequencerImpl.java|1|1|100.00%|
|:large_blue_circle:|io/questdb/cairo/O3PartitionPurgeJob.java|1|1|100.00%|
|:large_blue_circle:|io/questdb/PropertyKey.java|2|2|100.00%|
|:large_blue_circle:|io/questdb/cairo/TableNameRegistryFileStore.java|16|16|100.00%|
|:large_blue_circle:|io/questdb/cairo/CairoException.java|2|2|100.00%|

**Comment by ideoma** [comment]
#### [PR Coverage check]

:heart_eyes: **pass** : 47 / 57 (82.46%)




#### file detail

|   |path|covered line|new line|coverage|
|----|----|----|----|----|
|:large_blue_circle:|io/questdb/cairo/DefaultCairoConfiguration.java|0|2|00.00%|
|:large_blue_circle:|io/questdb/cairo/wal/ApplyWal2TableJob.java|3|5|60.00%|
|:large_blue_circle:|io/questdb/cairo/wal/seq/TableSequencerAPI.java|12|17|70.59%|
|:large_blue_circle:|io/questdb/cairo/wal/WalPurgeJob.java|8|9|88.89%|
|:large_blue_circle:|io/questdb/PropServerConfiguration.java|2|2|100.00%|
|:large_blue_circle:|io/questdb/cairo/wal/seq/TableSequencerImpl.java|1|1|100.00%|
|:large_blue_circle:|io/questdb/cairo/O3PartitionPurgeJob.java|1|1|100.00%|
|:large_blue_circle:|io/questdb/PropertyKey.java|2|2|100.00%|
|:large_blue_circle:|io/questdb/cairo/TableNameRegistryFileStore.java|16|16|100.00%|
|:large_blue_circle:|io/questdb/cairo/CairoException.java|2|2|100.00%|

**Comment by ideoma** [comment]
#### [PR Coverage check]

:heart_eyes: **pass** : 127 / 151 (84.11%)




#### file detail

|   |path|covered line|new line|coverage|
|----|----|----|----|----|
|:large_blue_circle:|io/questdb/cairo/DefaultCairoConfiguration.java|0|2|00.00%|
|:large_blue_circle:|io/questdb/cutlass/line/tcp/TableUpdateDetails.java|6|18|33.33%|
|:large_blue_circle:|io/questdb/cairo/wal/seq/TableSequencerAPI.java|12|17|70.59%|
|:large_blue_circle:|io/questdb/cairo/wal/ApplyWal2TableJob.java|10|12|83.33%|
|:large_blue_circle:|io/questdb/cutlass/line/tcp/LineTcpMeasurementScheduler.java|11|13|84.62%|
|:large_blue_circle:|io/questdb/cairo/wal/WalPurgeJob.java|56|57|98.25%|
|:large_blue_circle:|io/questdb/PropServerConfiguration.java|2|2|100.00%|
|:large_blue_circle:|io/questdb/cairo/wal/seq/TableSequencerImpl.java|1|1|100.00%|
|:large_blue_circle:|io/questdb/cairo/wal/CheckWalTransactionsJob.java|2|2|100.00%|
|:large_blue_circle:|io/questdb/cairo/CommitFailedException.java|2|2|100.00%|
|:large_blue_circle:|io/questdb/cairo/O3PartitionPurgeJob.java|1|1|100.00%|
|:large_blue_circle:|io/questdb/PropertyKey.java|2|2|100.00%|
|:large_blue_circle:|io/questdb/cairo/TableNameRegistryFileStore.java|16|16|100.00%|
|:large_blue_circle:|io/questdb/cairo/AbstractTableNameRegistry.java|1|1|100.00%|
|:large_blue_circle:|io/questdb/cairo/CairoException.java|5|5|100.00%|

**Comment by ideoma** [comment]
#### [PR Coverage check]

:heart_eyes: **pass** : 148 / 177 (83.62%)




#### file detail

|   |path|covered line|new line|coverage|
|----|----|----|----|----|
|:large_blue_circle:|io/questdb/cairo/DefaultCairoConfiguration.java|0|2|00.00%|
|:large_blue_circle:|io/questdb/cutlass/line/tcp/TableUpdateDetails.java|6|20|30.00%|
|:large_blue_circle:|io/questdb/cairo/wal/seq/TableSequencerAPI.java|12|17|70.59%|
|:large_blue_circle:|io/questdb/cairo/CommitFailedException.java|6|8|75.00%|
|:large_blue_circle:|io/questdb/cutlass/line/tcp/LineTcpMeasurementScheduler.java|11|13|84.62%|
|:large_blue_circle:|io/questdb/cairo/wal/ApplyWal2TableJob.java|12|14|85.71%|
|:large_blue_circle:|io/questdb/cairo/wal/seq/TableSequencerImpl.java|15|16|93.75%|
|:large_blue_circle:|io/questdb/cairo/wal/WalPurgeJob.java|56|57|98.25%|
|:large_blue_circle:|io/questdb/PropServerConfiguration.java|2|2|100.00%|
|:large_blue_circle:|io/questdb/cairo/wal/CheckWalTransactionsJob.java|2|2|100.00%|
|:large_blue_circle:|io/questdb/cairo/O3PartitionPurgeJob.java|1|1|100.00%|
|:large_blue_circle:|io/questdb/PropertyKey.java|2|2|100.00%|
|:large_blue_circle:|io/questdb/cairo/pool/AbstractMultiTenantPool.java|1|1|100.00%|
|:large_blue_circle:|io/questdb/cairo/TableNameRegistryFileStore.java|16|16|100.00%|
|:large_blue_circle:|io/questdb/cairo/AbstractTableNameRegistry.java|1|1|100.00%|
|:large_blue_circle:|io/questdb/cairo/CairoException.java|5|5|100.00%|

**Comment by ideoma** [comment]
#### [PR Coverage check]

:heart_eyes: **pass** : 148 / 177 (83.62%)




#### file detail

|   |path|covered line|new line|coverage|
|----|----|----|----|----|
|:large_blue_circle:|io/questdb/cairo/DefaultCairoConfiguration.java|0|2|00.00%|
|:large_blue_circle:|io/questdb/cutlass/line/tcp/TableUpdateDetails.java|6|20|30.00%|
|:large_blue_circle:|io/questdb/cairo/wal/seq/TableSequencerAPI.java|12|17|70.59%|
|:large_blue_circle:|io/questdb/cairo/CommitFailedException.java|6|8|75.00%|
|:large_blue_circle:|io/questdb/cutlass/line/tcp/LineTcpMeasurementScheduler.java|11|13|84.62%|
|:large_blue_circle:|io/questdb/cairo/wal/ApplyWal2TableJob.java|12|14|85.71%|
|:large_blue_circle:|io/questdb/cairo/wal/seq/TableSequencerImpl.java|15|16|93.75%|
|:large_blue_circle:|io/questdb/cairo/wal/WalPurgeJob.java|56|57|98.25%|
|:large_blue_circle:|io/questdb/PropServerConfiguration.java|2|2|100.00%|
|:large_blue_circle:|io/questdb/cairo/wal/CheckWalTransactionsJob.java|2|2|100.00%|
|:large_blue_circle:|io/questdb/cairo/O3PartitionPurgeJob.java|1|1|100.00%|
|:large_blue_circle:|io/questdb/PropertyKey.java|2|2|100.00%|
|:large_blue_circle:|io/questdb/cairo/pool/AbstractMultiTenantPool.java|1|1|100.00%|
|:large_blue_circle:|io/questdb/cairo/TableNameRegistryFileStore.java|16|16|100.00%|
|:large_blue_circle:|io/questdb/cairo/AbstractTableNameRegistry.java|1|1|100.00%|
|:large_blue_circle:|io/questdb/cairo/CairoException.java|5|5|100.00%|

**Review by bluestreak01 — APPROVED** [review]

**Comment by ideoma** [comment]
#### [PR Coverage check]

:heart_eyes: **pass** : 148 / 177 (83.62%)




#### file detail

|   |path|covered line|new line|coverage|
|----|----|----|----|----|
|:large_blue_circle:|io/questdb/cairo/DefaultCairoConfiguration.java|0|2|00.00%|
|:large_blue_circle:|io/questdb/cutlass/line/tcp/TableUpdateDetails.java|6|20|30.00%|
|:large_blue_circle:|io/questdb/cairo/wal/seq/TableSequencerAPI.java|12|17|70.59%|
|:large_blue_circle:|io/questdb/cairo/CommitFailedException.java|6|8|75.00%|
|:large_blue_circle:|io/questdb/cutlass/line/tcp/LineTcpMeasurementScheduler.java|11|13|84.62%|
|:large_blue_circle:|io/questdb/cairo/wal/ApplyWal2TableJob.java|12|14|85.71%|
|:large_blue_circle:|io/questdb/cairo/wal/seq/TableSequencerImpl.java|15|16|93.75%|
|:large_blue_circle:|io/questdb/cairo/wal/WalPurgeJob.java|56|57|98.25%|
|:large_blue_circle:|io/questdb/PropServerConfiguration.java|2|2|100.00%|
|:large_blue_circle:|io/questdb/cairo/wal/CheckWalTransactionsJob.java|2|2|100.00%|
|:large_blue_circle:|io/questdb/cairo/O3PartitionPurgeJob.java|1|1|100.00%|
|:large_blue_circle:|io/questdb/PropertyKey.java|2|2|100.00%|
|:large_blue_circle:|io/questdb/cairo/pool/AbstractMultiTenantPool.java|1|1|100.00%|
|:large_blue_circle:|io/questdb/cairo/TableNameRegistryFileStore.java|16|16|100.00%|
|:large_blue_circle:|io/questdb/cairo/AbstractTableNameRegistry.java|1|1|100.00%|
|:large_blue_circle:|io/questdb/cairo/CairoException.java|5|5|100.00%|

**Pull request merged**
