### PR TITLE
fix(core): fix invalid table writer state after ALTER TABLE SQUASH PARTITIONS

### LINKED ISSUE #4149: Suspended WAL: cannot resolve WAL table last partition
### To reproduce

QuestDB suspends a table on import:
`2024-01-22T11:16:52.477401Z C i.q.c.w.ApplyWal2TableJob job failed, table suspended [table=mytable~5, error=system error, cannot resolve WAL table last partition [path=/root/.questdb/db/mytable~5], errno=0]`

Steps to reproduce:

Remove /root/.questdb/ with exception of conf/. See modified server.con in section "additional context"
Start QuestDB

Create table:
```
drop table 'mytable';
CREATE TABLE IF NOT EXISTS "mytable" ( time TIMESTAMP ) timestamp (time) PARTITION BY DAY WAL DEDUP UPSERT KEYS( time );
```

Import data as ILP: `./mync0.sh` (see section "additional context")

Squash partitions and prepare next import
```
ALTER TABLE "mytable" SQUASH PARTITIONS;CREATE TABLE IF NOT EXISTS "mytable" ( time TIMESTAMP ) timestamp (time) PARTITION BY DAY WAL DEDUP UPSERT KEYS( time );
```
Import data as ILP: `./mync1.sh` (same as mync1.sh; using another data file)

Check logfile for error message.

The issue seems to be timing related. Calling just nc without a loop with delay does not trigger the error.
The issue is not related to the filesystem. I've tried ext4 and ZFS with compression enabled.

### QuestDB version:

7.3.9

### OS, in case of Docker specify Docker and the Host OS:

Ubuntu 22.04

### File System, in case of Docker specify Host File System:

ext4, ZFS with LZ4

### Full Name:

Jan Bartels

### Affiliation:

Siempelkamp

### Have you followed Linux, MacOs kernel configuration steps to increase Maximum open files and Maximum virtual memory areas limit?

- [X] Yes, I have

### Additional context

netcat a file with delay: ([scripts.tar.gz](https://github.com/questdb/questdb/files/14009451/scripts.tar.gz))
```
$ cat mync0.sh 
#!/bin/bash
while read -r line ; do 
  echo "$line"
  sleep 0.001
done < "mytable.0.data.txt" | nc -q 0 127.0.0.1 9009
```
I'll provide you with a download link for the data files via slack. The tgz file is about 90 MiB.

Altered configuration:
```
root@tuxi:~/.questdb/conf# diff server.conf server.conf~
545d544
< line.tcp.msg.buffer.size=524288

```

Log: [questdb.log.tar.gz](https://github.com/questdb/questdb/files/14009368/questdb.log.tar.gz)
See line 7491 for message:
`2024-01-22T11:16:52.477401Z C i.q.c.w.ApplyWal2TableJob job failed, table suspended [table=mytable~5, error=system error, cannot resolve WAL table last partition [path=/root/.questdb/db/mytable~5], errno=0]`

### PR DESCRIPTION
**Pull request by puzpuzpuz**
Fixes #4149

### CODE REVIEW

**Comment by ideoma** [comment]
#### [PR Coverage check]

:heart_eyes: **pass** : 1 / 1 (100.00%)




#### file detail

|   |path|covered line|new line|coverage|
|----|----|----|----|----|
|:large_blue_circle:|io/questdb/cairo/TableWriter.java|1|1|100.00%|

**Review by ideoma — APPROVED** [review]

**Comment by puzpuzpuz** [comment]
@ideoma thanks for the quick review. I've noticed a bug around squash partitions on an empty table and fixed it. The fix is here: 3128c4e461d88b71542513670ca2f345230ea53d

**Comment by bluestreak01** [comment]
there is fuzz test failure, possibly unrelated to the change, but still not ideal
```
2024-01-23T09:35:52.7106850Z 2024-01-23T09:35:52.710040Z E i.q.t.c.l.t.AbstractLineTcpReceiverTest Data sending failed [rc=-2, sent=0, bufferSize=129]
2024-01-23T09:35:52.7112610Z Exception in thread "Thread-5472" java.lang.AssertionError: Data sending failed [e=java.lang.RuntimeException: Data sending failed [rc=-2]]
2024-01-23T09:35:52.7113740Z 	at org.junit.Assert.fail(Assert.java:89)
2024-01-23T09:35:52.7116680Z 	at io.questdb.test.cutlass.line.tcp.AbstractLineTcpReceiverFuzzTest.lambda$startThread$3(AbstractLineTcpReceiverFuzzTest.java:560)
2024-01-23T09:35:52.7117960Z 	at java.base/java.lang.Thread.run(Thread.java:829)
2024-01-23T09:35:52.7176520Z 2024-01-23T09:35:52.713838Z I i.q.c.CairoEngine locked [table=`weather1~9`, thread=6475]
```

This code doesn't even log OS error.

This is server part:
```
2024-01-23T09:35:52.2835470Z 2024-01-23T09:35:52.280010Z C i.q.c.l.t.LineTcpConnectionContext [40] could not process line data [table=weather2, ex=
2024-01-23T09:35:52.2837260Z java.lang.NullPointerException
2024-01-23T09:35:52.2839820Z 	at io.questdb.cairo.CairoEngine.isWalTable(CairoEngine.java:758)
2024-01-23T09:35:52.2842070Z 	at io.questdb.cutlass.line.tcp.LineTcpMeasurementScheduler.getTableUpdateDetailsFromSharedArea(LineTcpMeasurementScheduler.java:433)
2024-01-23T09:35:52.2844050Z 	at io.questdb.cutlass.line.tcp.LineTcpMeasurementScheduler.scheduleEvent(LineTcpMeasurementScheduler.java:272)
2024-01-23T09:35:52.2846990Z 	at io.questdb.cutlass.line.tcp.LineTcpConnectionContext.parseMeasurements(LineTcpConnectionContext.java:362)
2024-01-23T09:35:52.2849270Z 	at io.questdb.cutlass.line.tcp.LineTcpConnectionContext.handleIO(LineTcpConnectionContext.java:187)
2024-01-23T09:35:52.2852720Z 	at io.questdb.cutlass.line.tcp.LineTcpNetworkIOJob.handleIO(LineTcpNetworkIOJob.java:134)
2024-01-23T09:35:52.2855100Z 	at io.questdb.cutlass.line.tcp.LineTcpNetworkIOJob.onRequest(LineTcpNetworkIOJob.java:157)
2024-01-23T09:35:52.2856640Z 	at io.questdb.network.AbstractIODispatcher.processIOQueue(AbstractIODispatcher.java:199)
2024-01-23T09:35:52.2857490Z 	at io.questdb.cutlass.line.tcp.LineTcpNetworkIOJob.run(LineTcpNetworkIOJob.java:117)
2024-01-23T09:35:52.2864200Z 	at io.questdb.mp.Worker.run(Worker.java:148)
2024-01-23T09:35:52.2868570Z ]
2024-01-23T09:35:52.2870800Z 2024-01-23T09:35:52.280368Z I IODispatcher scheduling disconnect [fd=40, reason=0]


Full log: 
[187.zip](https://github.com/questdb/questdb/files/14023674/187.zip)



```

**Comment by ideoma** [comment]
#### [PR Coverage check]

:heart_eyes: **pass** : 2 / 2 (100.00%)




#### file detail

|   |path|covered line|new line|coverage|
|----|----|----|----|----|
|:large_blue_circle:|io/questdb/cairo/TableWriter.java|2|2|100.00%|

**Comment by ideoma** [comment]
#### [PR Coverage check]

:heart_eyes: **pass** : 2 / 2 (100.00%)




#### file detail

|   |path|covered line|new line|coverage|
|----|----|----|----|----|
|:large_blue_circle:|io/questdb/cairo/TableWriter.java|2|2|100.00%|

**Comment by puzpuzpuz** [comment]
> there is fuzz test failure, possibly unrelated to the change, but still not ideal

@bluestreak01 thanks for the heads-up. I was able to reproduce the flakiness and here is the fix: 74b437015f13fbbd111a5098b844a74fc12b797b

**Comment by ideoma** [comment]
#### [PR Coverage check]

:heart_eyes: **pass** : 59 / 67 (88.06%)




#### file detail

|   |path|covered line|new line|coverage|
|----|----|----|----|----|
|:large_blue_circle:|io/questdb/cairo/ConcurrentBitmapIndexFwdReader.java|1|2|50.00%|
|:large_blue_circle:|io/questdb/cutlass/line/tcp/LineTcpMeasurementScheduler.java|47|54|87.04%|
|:large_blue_circle:|io/questdb/cairo/BitmapIndexFwdReader.java|2|2|100.00%|
|:large_blue_circle:|io/questdb/cairo/BitmapIndexBwdReader.java|2|2|100.00%|
|:large_blue_circle:|io/questdb/cairo/AbstractIndexReader.java|5|5|100.00%|
|:large_blue_circle:|io/questdb/cairo/TableWriter.java|2|2|100.00%|

**Comment by ideoma** [comment]
#### [PR Coverage check]

:heart_eyes: **pass** : 61 / 69 (88.41%)




#### file detail

|   |path|covered line|new line|coverage|
|----|----|----|----|----|
|:large_blue_circle:|io/questdb/cairo/ConcurrentBitmapIndexFwdReader.java|1|2|50.00%|
|:large_blue_circle:|io/questdb/cutlass/line/tcp/LineTcpMeasurementScheduler.java|47|54|87.04%|
|:large_blue_circle:|io/questdb/cairo/BitmapIndexFwdReader.java|2|2|100.00%|
|:large_blue_circle:|io/questdb/cairo/BitmapIndexBwdReader.java|2|2|100.00%|
|:large_blue_circle:|io/questdb/cairo/AbstractIndexReader.java|5|5|100.00%|
|:large_blue_circle:|io/questdb/cairo/TableWriter.java|4|4|100.00%|

**Comment by ideoma** [comment]
Good fix, we'd need to copy the retry logic to IlpTudCache too, I can take care of it

**Review by ideoma — APPROVED** [review]

**Comment by ideoma** [comment]
#### [PR Coverage check]

:heart_eyes: **pass** : 61 / 69 (88.41%)




#### file detail

|   |path|covered line|new line|coverage|
|----|----|----|----|----|
|:large_blue_circle:|io/questdb/cairo/ConcurrentBitmapIndexFwdReader.java|1|2|50.00%|
|:large_blue_circle:|io/questdb/cutlass/line/tcp/LineTcpMeasurementScheduler.java|47|54|87.04%|
|:large_blue_circle:|io/questdb/cairo/BitmapIndexFwdReader.java|2|2|100.00%|
|:large_blue_circle:|io/questdb/cairo/BitmapIndexBwdReader.java|2|2|100.00%|
|:large_blue_circle:|io/questdb/cairo/AbstractIndexReader.java|5|5|100.00%|
|:large_blue_circle:|io/questdb/cairo/TableWriter.java|4|4|100.00%|

**Comment by bluestreak01** [comment]
i think the fix for ILP is non-ideal, lets roll it back form this PR and fix in separate one?

**Comment by puzpuzpuz** [comment]
> i think the fix for ILP is non-ideal, lets roll it back form this PR and fix in separate one?

Which parts should be improved? I can fix them here.

**Comment by ideoma** [comment]
#### [PR Coverage check]

:heart_eyes: **pass** : 61 / 69 (88.41%)




#### file detail

|   |path|covered line|new line|coverage|
|----|----|----|----|----|
|:large_blue_circle:|io/questdb/cairo/ConcurrentBitmapIndexFwdReader.java|1|2|50.00%|
|:large_blue_circle:|io/questdb/cutlass/line/tcp/LineTcpMeasurementScheduler.java|47|54|87.04%|
|:large_blue_circle:|io/questdb/cairo/BitmapIndexFwdReader.java|2|2|100.00%|
|:large_blue_circle:|io/questdb/cairo/BitmapIndexBwdReader.java|2|2|100.00%|
|:large_blue_circle:|io/questdb/cairo/AbstractIndexReader.java|5|5|100.00%|
|:large_blue_circle:|io/questdb/cairo/TableWriter.java|4|4|100.00%|

**Comment by ideoma** [comment]
#### [PR Coverage check]

:heart_eyes: **pass** : 61 / 69 (88.41%)




#### file detail

|   |path|covered line|new line|coverage|
|----|----|----|----|----|
|:large_blue_circle:|io/questdb/cairo/ConcurrentBitmapIndexFwdReader.java|1|2|50.00%|
|:large_blue_circle:|io/questdb/cutlass/line/tcp/LineTcpMeasurementScheduler.java|47|54|87.04%|
|:large_blue_circle:|io/questdb/cairo/BitmapIndexFwdReader.java|2|2|100.00%|
|:large_blue_circle:|io/questdb/cairo/BitmapIndexBwdReader.java|2|2|100.00%|
|:large_blue_circle:|io/questdb/cairo/AbstractIndexReader.java|5|5|100.00%|
|:large_blue_circle:|io/questdb/cairo/TableWriter.java|4|4|100.00%|

**Pull request merged**
