### PR TITLE
fix #3164, add show server_version

### LINKED ISSUE #3164: Add `QuestDB` to returned value of `SHOW VERSION()` via pg-wire
### Is your feature request related to a problem?

We wanted to use flyway to set up the tables in QuestDB. Flyway does not support QuestDB and found an [open ticket](https://github.com/questdb/questdb/issues/2681) mentioning [community database drivers for flyway](https://github.com/flyway/flyway/tree/main/flyway-community-db-support/src/main/java/org/flywaydb/community/database).

We have implemented one which works, but we have found no good way to know, via pg-wire, that we are for sure connected to a QuestDB instance and not connected to a PostgreSQL database.

### Describe the solution you'd like.

The regular flyway PostgreSQL driver looks at the output of `SHOW VERSION`.
There is a similar driver for YugabyteDB, which is postgres compatible, that checks for a `YB` in the version string.

We think QuestDB could do something similar.

e.g. `VersionFunctionFactory` could have:

```java
private final StrFunction INSTANCE = new StrConstant("PostgreSQL 12.3, compiled by Visual C++ build 1914, 64-bit, QuestDB");
```

### Describe alternatives you've considered.

We could implement another function that is QuestDB specific, but this would require the flyway driver we wrote to handle that function not being there for regular PostgreSQL connections.

### Additional context.

We have looked at the original issue #430 where the version function was seemingly first implemented and there doesn't seem to be anything special about the string returned currently.

That work was done for the python pg driver, and looking at the source there we don't see it making much use of `SHOW VERSION()` outside a few tests. We did not notice any parsing of that string which might break by changing it in the manner we suggested.

### PR DESCRIPTION
**Pull request by nitram509**
fix #3164 add show server_version

As suggested in the issue, this PR implements `show server_version`.
Since phrasing an exact version string as expected result within a test is somewhat difficult,
I did refactor the proposed code snipped (see issue) somewhat and hope it's in the common interest.

Unfortunately, I couldn't find the sources to https://questdb.io/docs/reference/sql/show/ , so I was not able to extend documentation.

### CODE REVIEW

**Comment by nitram509** [comment]
Dear maintainers, could you please guide me on how to deal with the failing tests, please?

* I did run JDK11 tests locally and they worked fine.
* Why is there a JDK8 test in place (documentation says JDK11 required), which fails ... shall I fix that?
* The JDK 17 + 18 tests do fail also on master branch ... that's unrelated to my change, so I tend to ignore them, no?

**Comment by bluestreak01** [comment]
hi Martin, thank you for yet another contribution!

This is compilation error in JDK8 and JDK17. To reproduce locally:

```bash
export JAVA_HOME=/path/to/jdk8 (or 17)

mvn clean package -DskipTests
```

**Comment by bluestreak01** [comment]
in JDK17 they introduced standard `Record` class, which name-clashes with our `Record` class. This require correct `import` to exist.

**Comment by nitram509** [comment]
Ping @bluestreak01 I did fix the compiler issues, may I ask for a re-review, please?

**Comment by jerrinot** [comment]
Hello @nitram509,

first of all: Many thanks for this contribution. Improvements like this are really important for compatibility with Postgres tooling! 

I've been thinking about what `show server_version` command should report. As part of this, I investigated what some of the other Postgres-compatible databases are doing. Here are the results:

**Postgres 14**
`show server_version`: 14.10 (Homebrew)
`select version()`: PostgreSQL 14.10 (Homebrew) on aarch64-apple-darwin23.0.0, compiled by Apple clang version 15.0.0 (clang-1500.0.40.1), 64-bit

**Neon**
`show server_version`: 14.9
`select version()`: PostgreSQL 14.9 on x86_64-pc-linux-gnu, compiled by gcc (Debian 10.2.1-6) 10.2.1 20210110, 64-bit

**Cockroach**
`show server_version`: 13.0.0
`select version()`: CockroachDB CCL v23.1.11-596-gfb1ed73d9d8 (x86_64-pc-linux-gnu, built 2023/10/30 20:59:38, go1.19.13)

**QuestDB**
`show server_version`: currently unsupported
`select version()`: PostgreSQL 12.3, compiled by Visual C++ build 1914, 64-bit, QuestDB

Conclusion:
`show server_version` should not return all the nitty-gritty implementation details. It should rather respond with the PostgreSQL version QuestDB is trying to mimic, perhaps with a small tag to indicate it's QuestDB (as Homebrew Postgres builds do and https://github.com/questdb/questdb/issues/3164 tells me Yugabyte also add a short string). 

What version it should report? `select version()` already returns 12.3 so `show server_version` should be consistent with that. So I would recommend reporting `12.3 (questdb)` 
Ideally, the version string should be defined on a single place in the codebase and it should be used for both `select version()` and `show server_version`. 

Please let me know if this makes sense to you! And once more thanks for spending your time on improving QuestDB! ❤️

**Comment by nitram509** [comment]
@jerrinot thanks for your feedback, I fully agree with your argumentation and did shorten the version string as expected.

**Comment by jerrinot** [comment]
hello @nitram509 thanks for the update. I think there have been a misunderstanding. The `show server_version` command should not display QuestDB version. It should display the emulated PostgreSQL version. Which is currently 12.3. That's what other databases do.

**Comment by nitram509** [comment]
> hello @nitram509 thanks for the update. I think there have been a misunderstanding. The `show server_version` command should not display QuestDB version. It should display the emulated PostgreSQL version. Which is currently 12.3. That's what other databases do.

oops. thanks for clarification.

**Comment by nitram509** [comment]
@jerrinot fix implemented

**Review by bluestreak01 — APPROVED** [review]

**Comment by bluestreak01** [comment]
looks great, thank you! 👍

**Pull request merged**
