### PR TITLE
Optimize fromCoordinatesUnsafe function

### PR DESCRIPTION
**Pull request by eugenels**

### CODE REVIEW

**Comment by ideoma** [comment]
#### [PR Coverage check]

:heart_eyes: **pass** : 10 / 10 (100.00%)




#### file detail

|   |path|covered line|new line|coverage|
|----|----|----|----|----|
|:large_blue_circle:|io/questdb/std/Numbers.java|7|7|100.00%|
|:large_blue_circle:|io/questdb/cairo/GeoHashes.java|3|3|100.00%|

**Comment by ideoma** [comment]
#### [PR Coverage check]

:heart_eyes: **pass** : 10 / 10 (100.00%)




#### file detail

|   |path|covered line|new line|coverage|
|----|----|----|----|----|
|:large_blue_circle:|io/questdb/std/Numbers.java|7|7|100.00%|
|:large_blue_circle:|io/questdb/cairo/GeoHashes.java|3|3|100.00%|

**Comment by ideoma** [comment]
#### [PR Coverage check]

:heart_eyes: **pass** : 10 / 10 (100.00%)




#### file detail

|   |path|covered line|new line|coverage|
|----|----|----|----|----|
|:large_blue_circle:|io/questdb/std/Numbers.java|7|7|100.00%|
|:large_blue_circle:|io/questdb/cairo/GeoHashes.java|3|3|100.00%|

**Comment by ideoma** [comment]
#### [PR Coverage check]

:heart_eyes: **pass** : 10 / 10 (100.00%)




#### file detail

|   |path|covered line|new line|coverage|
|----|----|----|----|----|
|:large_blue_circle:|io/questdb/std/Numbers.java|7|7|100.00%|
|:large_blue_circle:|io/questdb/cairo/GeoHashes.java|3|3|100.00%|

**Review by marregui — APPROVED** [review]
LGTM

**Pull request merged**
