### PR TITLE
chore(core): refactor security context for added flexibility

### PR DESCRIPTION
**Pull request by glasstiger**
changing signature of `authorizeGrant()` and removing defaults from interface

### CODE REVIEW

**Comment by ideoma** [comment]
#### [PR Coverage check]

:heart_eyes: **pass** : 24 / 46 (52.17%)




#### file detail

|   |path|covered line|new line|coverage|
|----|----|----|----|----|
|:large_blue_circle:|io/questdb/cairo/security/ReadOnlySecurityContext.java|1|4|25.00%|
|:large_blue_circle:|io/questdb/cairo/security/AllowAllSecurityContext.java|23|42|54.76%|

**Comment by ideoma** [comment]
#### [PR Coverage check]

:heart_eyes: **pass** : 28 / 50 (56.00%)




#### file detail

|   |path|covered line|new line|coverage|
|----|----|----|----|----|
|:large_blue_circle:|io/questdb/cairo/security/ReadOnlySecurityContext.java|1|4|25.00%|
|:large_blue_circle:|io/questdb/cairo/security/AllowAllSecurityContext.java|23|42|54.76%|
|:large_blue_circle:|io/questdb/cairo/wal/seq/TableSequencerAPI.java|4|4|100.00%|

**Comment by ideoma** [comment]
#### [PR Coverage check]

:heart_eyes: **pass** : 24 / 46 (52.17%)




#### file detail

|   |path|covered line|new line|coverage|
|----|----|----|----|----|
|:large_blue_circle:|io/questdb/cairo/security/ReadOnlySecurityContext.java|1|4|25.00%|
|:large_blue_circle:|io/questdb/cairo/security/AllowAllSecurityContext.java|23|42|54.76%|

**Comment by ideoma** [comment]
#### [PR Coverage check]

:heart_eyes: **pass** : 24 / 46 (52.17%)




#### file detail

|   |path|covered line|new line|coverage|
|----|----|----|----|----|
|:large_blue_circle:|io/questdb/cairo/security/ReadOnlySecurityContext.java|1|4|25.00%|
|:large_blue_circle:|io/questdb/cairo/security/AllowAllSecurityContext.java|23|42|54.76%|

**Review by bziobrowski — APPROVED** [review]

**Pull request merged**
