### PR TITLE
fix(ilp): ilp type conversions

### PR DESCRIPTION
**Pull request by glasstiger**
PR moves type conversions from writer thread to io job.
Type conversions will not fail silently if ILP is configured to disconnect on error.

Also wraps mem read/writes into a class which makes the code cleaner.
Next step will be to turn this class into a TableWriterRowBuilder which could act as a generic API for TableWriter.

### CODE REVIEW

**Comment by ideoma** [comment]
#### [PR Coverage check]

:heart_eyes: **pass** : 369 / 371 (99.46%)




#### file detail

|   |path|covered line|new line|coverage|
|----|----|----|----|----|
|:large_blue_circle:|io/questdb/cutlass/line/tcp/LineTcpMeasurementEvent.java|250|252|99.21%|
|:large_blue_circle:|io/questdb/cutlass/line/tcp/LineTcpEventBuffer.java|103|103|100.00%|
|:large_blue_circle:|io/questdb/cutlass/line/tcp/LineTcpMeasurementScheduler.java|9|9|100.00%|
|:large_blue_circle:|io/questdb/cutlass/line/tcp/DefaultColumnTypes.java|2|2|100.00%|
|:large_blue_circle:|io/questdb/cutlass/line/tcp/TableUpdateDetails.java|4|4|100.00%|
|:large_blue_circle:|io/questdb/std/str/FloatingDirectCharSink.java|1|1|100.00%|

**Comment by ideoma** [comment]
#### [PR Coverage check]

:heart_eyes: **pass** : 369 / 371 (99.46%)




#### file detail

|   |path|covered line|new line|coverage|
|----|----|----|----|----|
|:large_blue_circle:|io/questdb/cutlass/line/tcp/LineTcpMeasurementEvent.java|250|252|99.21%|
|:large_blue_circle:|io/questdb/cutlass/line/tcp/LineTcpEventBuffer.java|103|103|100.00%|
|:large_blue_circle:|io/questdb/cutlass/line/tcp/LineTcpMeasurementScheduler.java|9|9|100.00%|
|:large_blue_circle:|io/questdb/cutlass/line/tcp/DefaultColumnTypes.java|2|2|100.00%|
|:large_blue_circle:|io/questdb/cutlass/line/tcp/TableUpdateDetails.java|4|4|100.00%|
|:large_blue_circle:|io/questdb/std/str/FloatingDirectCharSink.java|1|1|100.00%|

**Comment by ideoma** [comment]
#### [PR Coverage check]

:heart_eyes: **pass** : 369 / 371 (99.46%)




#### file detail

|   |path|covered line|new line|coverage|
|----|----|----|----|----|
|:large_blue_circle:|io/questdb/cutlass/line/tcp/LineTcpMeasurementEvent.java|250|252|99.21%|
|:large_blue_circle:|io/questdb/cutlass/line/tcp/LineTcpEventBuffer.java|103|103|100.00%|
|:large_blue_circle:|io/questdb/cutlass/line/tcp/LineTcpMeasurementScheduler.java|9|9|100.00%|
|:large_blue_circle:|io/questdb/cutlass/line/tcp/DefaultColumnTypes.java|2|2|100.00%|
|:large_blue_circle:|io/questdb/cutlass/line/tcp/TableUpdateDetails.java|4|4|100.00%|
|:large_blue_circle:|io/questdb/std/str/FloatingDirectCharSink.java|1|1|100.00%|

**Comment by ideoma** [comment]
#### [PR Coverage check]

:heart_eyes: **pass** : 348 / 352 (98.86%)




#### file detail

|   |path|covered line|new line|coverage|
|----|----|----|----|----|
|:large_blue_circle:|io/questdb/cutlass/line/tcp/LineTcpParser.java|10|12|83.33%|
|:large_blue_circle:|io/questdb/cutlass/line/tcp/LineTcpMeasurementEvent.java|216|218|99.08%|
|:large_blue_circle:|io/questdb/cutlass/line/tcp/LineTcpEventBuffer.java|103|103|100.00%|
|:large_blue_circle:|io/questdb/cutlass/line/tcp/LineTcpMeasurementScheduler.java|9|9|100.00%|
|:large_blue_circle:|io/questdb/cutlass/line/tcp/DefaultColumnTypes.java|2|2|100.00%|
|:large_blue_circle:|io/questdb/cutlass/line/tcp/TableUpdateDetails.java|4|4|100.00%|
|:large_blue_circle:|io/questdb/cutlass/line/tcp/LineTcpConnectionContext.java|3|3|100.00%|
|:large_blue_circle:|io/questdb/std/str/FloatingDirectCharSink.java|1|1|100.00%|

**Comment by ideoma** [comment]
#### [PR Coverage check]

:heart_eyes: **pass** : 350 / 354 (98.87%)




#### file detail

|   |path|covered line|new line|coverage|
|----|----|----|----|----|
|:large_blue_circle:|io/questdb/cutlass/line/tcp/LineTcpParser.java|10|12|83.33%|
|:large_blue_circle:|io/questdb/cutlass/line/tcp/LineTcpMeasurementEvent.java|218|220|99.09%|
|:large_blue_circle:|io/questdb/cutlass/line/tcp/LineTcpEventBuffer.java|103|103|100.00%|
|:large_blue_circle:|io/questdb/cutlass/line/tcp/LineTcpMeasurementScheduler.java|9|9|100.00%|
|:large_blue_circle:|io/questdb/cutlass/line/tcp/DefaultColumnTypes.java|2|2|100.00%|
|:large_blue_circle:|io/questdb/cutlass/line/tcp/TableUpdateDetails.java|4|4|100.00%|
|:large_blue_circle:|io/questdb/cutlass/line/tcp/LineTcpConnectionContext.java|3|3|100.00%|
|:large_blue_circle:|io/questdb/std/str/FloatingDirectCharSink.java|1|1|100.00%|

**Comment by ideoma** [comment]
#### [PR Coverage check]

:heart_eyes: **pass** : 372 / 386 (96.37%)




#### file detail

|   |path|covered line|new line|coverage|
|----|----|----|----|----|
|:large_blue_circle:|io/questdb/cutlass/line/tcp/LineTcpMeasurementEvent.java|226|240|94.17%|
|:large_blue_circle:|io/questdb/cutlass/line/tcp/LineTcpParser.java|11|11|100.00%|
|:large_blue_circle:|io/questdb/cutlass/line/tcp/LineTcpEventBuffer.java|103|103|100.00%|
|:large_blue_circle:|io/questdb/cutlass/line/tcp/LineTcpMeasurementScheduler.java|12|12|100.00%|
|:large_blue_circle:|io/questdb/PropServerConfiguration.java|6|6|100.00%|
|:large_blue_circle:|io/questdb/cutlass/line/tcp/DefaultColumnTypes.java|2|2|100.00%|
|:large_blue_circle:|io/questdb/cutlass/line/tcp/TableUpdateDetails.java|4|4|100.00%|
|:large_blue_circle:|io/questdb/cutlass/line/tcp/DefaultLineTcpReceiverConfiguration.java|3|3|100.00%|
|:large_blue_circle:|io/questdb/cutlass/line/tcp/LineTcpConnectionContext.java|4|4|100.00%|
|:large_blue_circle:|io/questdb/std/str/FloatingDirectCharSink.java|1|1|100.00%|

**Comment by ideoma** [comment]
#### [PR Coverage check]

:heart_eyes: **pass** : 375 / 386 (97.15%)




#### file detail

|   |path|covered line|new line|coverage|
|----|----|----|----|----|
|:large_blue_circle:|io/questdb/cutlass/line/tcp/DefaultLineTcpReceiverConfiguration.java|2|3|66.67%|
|:large_blue_circle:|io/questdb/cutlass/line/tcp/LineTcpMeasurementEvent.java|230|240|95.83%|
|:large_blue_circle:|io/questdb/cutlass/line/tcp/LineTcpParser.java|11|11|100.00%|
|:large_blue_circle:|io/questdb/cutlass/line/tcp/LineTcpEventBuffer.java|103|103|100.00%|
|:large_blue_circle:|io/questdb/cutlass/line/tcp/LineTcpMeasurementScheduler.java|12|12|100.00%|
|:large_blue_circle:|io/questdb/PropServerConfiguration.java|6|6|100.00%|
|:large_blue_circle:|io/questdb/cutlass/line/tcp/DefaultColumnTypes.java|2|2|100.00%|
|:large_blue_circle:|io/questdb/cutlass/line/tcp/TableUpdateDetails.java|4|4|100.00%|
|:large_blue_circle:|io/questdb/cutlass/line/tcp/LineTcpConnectionContext.java|4|4|100.00%|
|:large_blue_circle:|io/questdb/std/str/FloatingDirectCharSink.java|1|1|100.00%|

**Comment by ideoma** [comment]
#### [PR Coverage check]

:heart_eyes: **pass** : 372 / 383 (97.13%)




#### file detail

|   |path|covered line|new line|coverage|
|----|----|----|----|----|
|:large_blue_circle:|io/questdb/cutlass/line/tcp/DefaultLineTcpReceiverConfiguration.java|2|3|66.67%|
|:large_blue_circle:|io/questdb/cutlass/line/tcp/LineTcpMeasurementEvent.java|230|240|95.83%|
|:large_blue_circle:|io/questdb/cutlass/line/tcp/LineTcpParser.java|8|8|100.00%|
|:large_blue_circle:|io/questdb/cutlass/line/tcp/LineTcpEventBuffer.java|103|103|100.00%|
|:large_blue_circle:|io/questdb/cutlass/line/tcp/LineTcpMeasurementScheduler.java|12|12|100.00%|
|:large_blue_circle:|io/questdb/PropServerConfiguration.java|6|6|100.00%|
|:large_blue_circle:|io/questdb/cutlass/line/tcp/DefaultColumnTypes.java|2|2|100.00%|
|:large_blue_circle:|io/questdb/cutlass/line/tcp/TableUpdateDetails.java|4|4|100.00%|
|:large_blue_circle:|io/questdb/cutlass/line/tcp/LineTcpConnectionContext.java|4|4|100.00%|
|:large_blue_circle:|io/questdb/std/str/FloatingDirectCharSink.java|1|1|100.00%|

**Comment by ideoma** [comment]
#### [PR Coverage check]

:heart_eyes: **pass** : 374 / 385 (97.14%)




#### file detail

|   |path|covered line|new line|coverage|
|----|----|----|----|----|
|:large_blue_circle:|io/questdb/cutlass/line/tcp/DefaultLineTcpReceiverConfiguration.java|2|3|66.67%|
|:large_blue_circle:|io/questdb/cutlass/line/tcp/LineTcpMeasurementEvent.java|164|174|94.25%|
|:large_blue_circle:|io/questdb/cutlass/line/tcp/LineTcpParser.java|8|8|100.00%|
|:large_blue_circle:|io/questdb/cutlass/line/tcp/LineTcpEventBuffer.java|171|171|100.00%|
|:large_blue_circle:|io/questdb/cutlass/line/tcp/LineTcpMeasurementScheduler.java|12|12|100.00%|
|:large_blue_circle:|io/questdb/PropServerConfiguration.java|6|6|100.00%|
|:large_blue_circle:|io/questdb/cutlass/line/tcp/DefaultColumnTypes.java|2|2|100.00%|
|:large_blue_circle:|io/questdb/cutlass/line/tcp/TableUpdateDetails.java|4|4|100.00%|
|:large_blue_circle:|io/questdb/cutlass/line/tcp/LineTcpConnectionContext.java|4|4|100.00%|
|:large_blue_circle:|io/questdb/std/str/FloatingDirectCharSink.java|1|1|100.00%|

**Comment by ideoma** [comment]
#### [PR Coverage check]

:heart_eyes: **pass** : 404 / 421 (95.96%)




#### file detail

|   |path|covered line|new line|coverage|
|----|----|----|----|----|
|:large_blue_circle:|io/questdb/cutlass/line/tcp/DefaultLineTcpReceiverConfiguration.java|2|3|66.67%|
|:large_blue_circle:|io/questdb/cutlass/line/tcp/TableUpdateDetails.java|39|46|84.78%|
|:large_blue_circle:|io/questdb/cutlass/line/tcp/LineTcpMeasurementEvent.java|151|160|94.38%|
|:large_blue_circle:|io/questdb/cutlass/line/tcp/LineTcpParser.java|8|8|100.00%|
|:large_blue_circle:|io/questdb/cutlass/line/tcp/LineTcpEventBuffer.java|172|172|100.00%|
|:large_blue_circle:|io/questdb/cutlass/line/tcp/LineTcpMeasurementScheduler.java|12|12|100.00%|
|:large_blue_circle:|io/questdb/PropServerConfiguration.java|6|6|100.00%|
|:large_blue_circle:|io/questdb/cutlass/line/tcp/DefaultColumnTypes.java|2|2|100.00%|
|:large_blue_circle:|io/questdb/cutlass/line/tcp/LineTcpWriterJob.java|1|1|100.00%|
|:large_blue_circle:|io/questdb/cutlass/line/tcp/SymbolCache.java|1|1|100.00%|
|:large_blue_circle:|io/questdb/cutlass/line/tcp/LineTcpConnectionContext.java|4|4|100.00%|
|:large_blue_circle:|io/questdb/std/str/FloatingDirectCharSink.java|1|1|100.00%|
|:large_blue_circle:|io/questdb/cutlass/line/tcp/LineTcpUtils.java|5|5|100.00%|

**Comment by ideoma** [comment]
#### [PR Coverage check]

:heart_eyes: **pass** : 407 / 424 (95.99%)




#### file detail

|   |path|covered line|new line|coverage|
|----|----|----|----|----|
|:large_blue_circle:|io/questdb/cutlass/line/tcp/DefaultLineTcpReceiverConfiguration.java|2|3|66.67%|
|:large_blue_circle:|io/questdb/cutlass/line/tcp/TableUpdateDetails.java|39|46|84.78%|
|:large_blue_circle:|io/questdb/cutlass/line/tcp/LineTcpMeasurementEvent.java|151|160|94.38%|
|:large_blue_circle:|io/questdb/cutlass/line/tcp/LineTcpParser.java|8|8|100.00%|
|:large_blue_circle:|io/questdb/cutlass/line/tcp/LineTcpEventBuffer.java|175|175|100.00%|
|:large_blue_circle:|io/questdb/cutlass/line/tcp/LineTcpMeasurementScheduler.java|12|12|100.00%|
|:large_blue_circle:|io/questdb/PropServerConfiguration.java|6|6|100.00%|
|:large_blue_circle:|io/questdb/cutlass/line/tcp/DefaultColumnTypes.java|2|2|100.00%|
|:large_blue_circle:|io/questdb/cutlass/line/tcp/LineTcpWriterJob.java|1|1|100.00%|
|:large_blue_circle:|io/questdb/cutlass/line/tcp/SymbolCache.java|1|1|100.00%|
|:large_blue_circle:|io/questdb/cutlass/line/tcp/LineTcpConnectionContext.java|4|4|100.00%|
|:large_blue_circle:|io/questdb/std/str/FloatingDirectCharSink.java|1|1|100.00%|
|:large_blue_circle:|io/questdb/cutlass/line/tcp/LineTcpUtils.java|5|5|100.00%|

**Comment by ideoma** [comment]
#### [PR Coverage check]

:heart_eyes: **pass** : 387 / 404 (95.79%)




#### file detail

|   |path|covered line|new line|coverage|
|----|----|----|----|----|
|:large_blue_circle:|io/questdb/cutlass/line/tcp/DefaultLineTcpReceiverConfiguration.java|2|3|66.67%|
|:large_blue_circle:|io/questdb/cutlass/line/tcp/TableUpdateDetails.java|39|46|84.78%|
|:large_blue_circle:|io/questdb/cutlass/line/tcp/LineTcpMeasurementEvent.java|173|182|95.05%|
|:large_blue_circle:|io/questdb/cutlass/line/tcp/LineTcpParser.java|14|14|100.00%|
|:large_blue_circle:|io/questdb/cutlass/line/tcp/LineTcpEventBuffer.java|127|127|100.00%|
|:large_blue_circle:|io/questdb/cutlass/line/tcp/LineTcpMeasurementScheduler.java|12|12|100.00%|
|:large_blue_circle:|io/questdb/PropServerConfiguration.java|6|6|100.00%|
|:large_blue_circle:|io/questdb/cutlass/line/tcp/DefaultColumnTypes.java|2|2|100.00%|
|:large_blue_circle:|io/questdb/cutlass/line/tcp/LineTcpWriterJob.java|1|1|100.00%|
|:large_blue_circle:|io/questdb/cutlass/line/tcp/SymbolCache.java|1|1|100.00%|
|:large_blue_circle:|io/questdb/cutlass/line/tcp/LineTcpConnectionContext.java|4|4|100.00%|
|:large_blue_circle:|io/questdb/std/str/FloatingDirectCharSink.java|1|1|100.00%|
|:large_blue_circle:|io/questdb/cutlass/line/tcp/LineTcpUtils.java|5|5|100.00%|

**Comment by ideoma** [comment]
#### [PR Coverage check]

:heart_eyes: **pass** : 391 / 408 (95.83%)




#### file detail

|   |path|covered line|new line|coverage|
|----|----|----|----|----|
|:large_blue_circle:|io/questdb/cutlass/line/tcp/DefaultLineTcpReceiverConfiguration.java|2|3|66.67%|
|:large_blue_circle:|io/questdb/cutlass/line/tcp/TableUpdateDetails.java|39|46|84.78%|
|:large_blue_circle:|io/questdb/cutlass/line/tcp/LineTcpMeasurementEvent.java|173|182|95.05%|
|:large_blue_circle:|io/questdb/cutlass/line/tcp/LineTcpParser.java|17|17|100.00%|
|:large_blue_circle:|io/questdb/cutlass/line/tcp/LineTcpEventBuffer.java|128|128|100.00%|
|:large_blue_circle:|io/questdb/cutlass/line/tcp/LineTcpMeasurementScheduler.java|12|12|100.00%|
|:large_blue_circle:|io/questdb/PropServerConfiguration.java|6|6|100.00%|
|:large_blue_circle:|io/questdb/cutlass/line/tcp/DefaultColumnTypes.java|2|2|100.00%|
|:large_blue_circle:|io/questdb/cutlass/line/tcp/LineTcpWriterJob.java|1|1|100.00%|
|:large_blue_circle:|io/questdb/cutlass/line/tcp/SymbolCache.java|1|1|100.00%|
|:large_blue_circle:|io/questdb/cutlass/line/tcp/LineTcpConnectionContext.java|4|4|100.00%|
|:large_blue_circle:|io/questdb/std/str/FloatingDirectCharSink.java|1|1|100.00%|
|:large_blue_circle:|io/questdb/cutlass/line/tcp/LineTcpUtils.java|5|5|100.00%|

**Comment by ideoma** [comment]
#### [PR Coverage check]

:heart_eyes: **pass** : 391 / 408 (95.83%)




#### file detail

|   |path|covered line|new line|coverage|
|----|----|----|----|----|
|:large_blue_circle:|io/questdb/cutlass/line/tcp/DefaultLineTcpReceiverConfiguration.java|2|3|66.67%|
|:large_blue_circle:|io/questdb/cutlass/line/tcp/TableUpdateDetails.java|39|46|84.78%|
|:large_blue_circle:|io/questdb/cutlass/line/tcp/LineTcpMeasurementEvent.java|173|182|95.05%|
|:large_blue_circle:|io/questdb/cutlass/line/tcp/LineTcpParser.java|17|17|100.00%|
|:large_blue_circle:|io/questdb/cutlass/line/tcp/LineTcpEventBuffer.java|128|128|100.00%|
|:large_blue_circle:|io/questdb/cutlass/line/tcp/LineTcpMeasurementScheduler.java|12|12|100.00%|
|:large_blue_circle:|io/questdb/PropServerConfiguration.java|6|6|100.00%|
|:large_blue_circle:|io/questdb/cutlass/line/tcp/DefaultColumnTypes.java|2|2|100.00%|
|:large_blue_circle:|io/questdb/cutlass/line/tcp/LineTcpWriterJob.java|1|1|100.00%|
|:large_blue_circle:|io/questdb/cutlass/line/tcp/SymbolCache.java|1|1|100.00%|
|:large_blue_circle:|io/questdb/cutlass/line/tcp/LineTcpConnectionContext.java|4|4|100.00%|
|:large_blue_circle:|io/questdb/std/str/FloatingDirectCharSink.java|1|1|100.00%|
|:large_blue_circle:|io/questdb/cutlass/line/tcp/LineTcpUtils.java|5|5|100.00%|

**Comment by ideoma** [comment]
#### [PR Coverage check]

:heart_eyes: **pass** : 392 / 408 (96.08%)




#### file detail

|   |path|covered line|new line|coverage|
|----|----|----|----|----|
|:large_blue_circle:|io/questdb/cutlass/line/tcp/DefaultLineTcpReceiverConfiguration.java|2|3|66.67%|
|:large_blue_circle:|io/questdb/cutlass/line/tcp/TableUpdateDetails.java|40|46|86.96%|
|:large_blue_circle:|io/questdb/cutlass/line/tcp/LineTcpMeasurementEvent.java|173|182|95.05%|
|:large_blue_circle:|io/questdb/cutlass/line/tcp/LineTcpParser.java|17|17|100.00%|
|:large_blue_circle:|io/questdb/cutlass/line/tcp/LineTcpEventBuffer.java|128|128|100.00%|
|:large_blue_circle:|io/questdb/cutlass/line/tcp/LineTcpMeasurementScheduler.java|12|12|100.00%|
|:large_blue_circle:|io/questdb/PropServerConfiguration.java|6|6|100.00%|
|:large_blue_circle:|io/questdb/cutlass/line/tcp/DefaultColumnTypes.java|2|2|100.00%|
|:large_blue_circle:|io/questdb/cutlass/line/tcp/LineTcpWriterJob.java|1|1|100.00%|
|:large_blue_circle:|io/questdb/cutlass/line/tcp/SymbolCache.java|1|1|100.00%|
|:large_blue_circle:|io/questdb/cutlass/line/tcp/LineTcpConnectionContext.java|4|4|100.00%|
|:large_blue_circle:|io/questdb/std/str/FloatingDirectCharSink.java|1|1|100.00%|
|:large_blue_circle:|io/questdb/cutlass/line/tcp/LineTcpUtils.java|5|5|100.00%|

**Comment by ideoma** [comment]
#### [PR Coverage check]

:heart_eyes: **pass** : 391 / 408 (95.83%)




#### file detail

|   |path|covered line|new line|coverage|
|----|----|----|----|----|
|:large_blue_circle:|io/questdb/cutlass/line/tcp/DefaultLineTcpReceiverConfiguration.java|2|3|66.67%|
|:large_blue_circle:|io/questdb/cutlass/line/tcp/TableUpdateDetails.java|39|46|84.78%|
|:large_blue_circle:|io/questdb/cutlass/line/tcp/LineTcpMeasurementEvent.java|173|182|95.05%|
|:large_blue_circle:|io/questdb/cutlass/line/tcp/LineTcpParser.java|17|17|100.00%|
|:large_blue_circle:|io/questdb/cutlass/line/tcp/LineTcpEventBuffer.java|128|128|100.00%|
|:large_blue_circle:|io/questdb/cutlass/line/tcp/LineTcpMeasurementScheduler.java|12|12|100.00%|
|:large_blue_circle:|io/questdb/PropServerConfiguration.java|6|6|100.00%|
|:large_blue_circle:|io/questdb/cutlass/line/tcp/DefaultColumnTypes.java|2|2|100.00%|
|:large_blue_circle:|io/questdb/cutlass/line/tcp/LineTcpWriterJob.java|1|1|100.00%|
|:large_blue_circle:|io/questdb/cutlass/line/tcp/SymbolCache.java|1|1|100.00%|
|:large_blue_circle:|io/questdb/cutlass/line/tcp/LineTcpConnectionContext.java|4|4|100.00%|
|:large_blue_circle:|io/questdb/std/str/FloatingDirectCharSink.java|1|1|100.00%|
|:large_blue_circle:|io/questdb/cutlass/line/tcp/LineTcpUtils.java|5|5|100.00%|

**Comment by ideoma** [comment]
#### [PR Coverage check]

:heart_eyes: **pass** : 389 / 407 (95.58%)




#### file detail

|   |path|covered line|new line|coverage|
|----|----|----|----|----|
|:large_blue_circle:|io/questdb/cutlass/line/tcp/DefaultLineTcpReceiverConfiguration.java|2|3|66.67%|
|:large_blue_circle:|io/questdb/PropServerConfiguration.java|4|5|80.00%|
|:large_blue_circle:|io/questdb/cutlass/line/tcp/TableUpdateDetails.java|39|46|84.78%|
|:large_blue_circle:|io/questdb/cutlass/line/tcp/LineTcpMeasurementEvent.java|173|182|95.05%|
|:large_blue_circle:|io/questdb/cutlass/line/tcp/LineTcpParser.java|17|17|100.00%|
|:large_blue_circle:|io/questdb/cutlass/line/tcp/LineTcpEventBuffer.java|128|128|100.00%|
|:large_blue_circle:|io/questdb/cutlass/line/tcp/LineTcpMeasurementScheduler.java|12|12|100.00%|
|:large_blue_circle:|io/questdb/cutlass/line/tcp/DefaultColumnTypes.java|2|2|100.00%|
|:large_blue_circle:|io/questdb/cutlass/line/tcp/LineTcpWriterJob.java|1|1|100.00%|
|:large_blue_circle:|io/questdb/cutlass/line/tcp/SymbolCache.java|1|1|100.00%|
|:large_blue_circle:|io/questdb/cutlass/line/tcp/LineTcpConnectionContext.java|4|4|100.00%|
|:large_blue_circle:|io/questdb/std/str/FloatingDirectCharSink.java|1|1|100.00%|
|:large_blue_circle:|io/questdb/cutlass/line/tcp/LineTcpUtils.java|5|5|100.00%|

**Comment by ideoma** [comment]
#### [PR Coverage check]

:heart_eyes: **pass** : 391 / 408 (95.83%)




#### file detail

|   |path|covered line|new line|coverage|
|----|----|----|----|----|
|:large_blue_circle:|io/questdb/cutlass/line/tcp/DefaultLineTcpReceiverConfiguration.java|2|3|66.67%|
|:large_blue_circle:|io/questdb/cutlass/line/tcp/TableUpdateDetails.java|39|46|84.78%|
|:large_blue_circle:|io/questdb/cutlass/line/tcp/LineTcpMeasurementEvent.java|173|182|95.05%|
|:large_blue_circle:|io/questdb/cutlass/line/tcp/LineTcpParser.java|17|17|100.00%|
|:large_blue_circle:|io/questdb/cutlass/line/tcp/LineTcpEventBuffer.java|128|128|100.00%|
|:large_blue_circle:|io/questdb/cutlass/line/tcp/LineTcpMeasurementScheduler.java|12|12|100.00%|
|:large_blue_circle:|io/questdb/PropServerConfiguration.java|6|6|100.00%|
|:large_blue_circle:|io/questdb/cutlass/line/tcp/DefaultColumnTypes.java|2|2|100.00%|
|:large_blue_circle:|io/questdb/cutlass/line/tcp/LineTcpWriterJob.java|1|1|100.00%|
|:large_blue_circle:|io/questdb/cutlass/line/tcp/SymbolCache.java|1|1|100.00%|
|:large_blue_circle:|io/questdb/cutlass/line/tcp/LineTcpConnectionContext.java|4|4|100.00%|
|:large_blue_circle:|io/questdb/std/str/FloatingDirectCharSink.java|1|1|100.00%|
|:large_blue_circle:|io/questdb/cutlass/line/tcp/LineTcpUtils.java|5|5|100.00%|

**Review by bluestreak01 — APPROVED** [review]

**Pull request merged**
