### PR TITLE
review ILP/UDP value parser and fix corner cases

### PR DESCRIPTION
**Pull request by marregui**
Reviewed and added clarifications on the way it is implemented at present, and then fixed some corner cases.

### CODE REVIEW

**Comment by ideoma** [comment]
#### [PR Coverage check]

:heart_eyes: **pass** : 18 / 18 (100.00%)




#### file detail

|   |path|covered line|new line|coverage|
|----|----|----|----|----|
|:large_blue_circle:|io/questdb/cutlass/line/CairoLineProtoParserSupport.java|9|9|100.00%|
|:large_blue_circle:|io/questdb/std/Chars.java|7|7|100.00%|
|:large_blue_circle:|io/questdb/cutlass/line/udp/CairoLineProtoParser.java|2|2|100.00%|

**Comment by ideoma** [comment]
#### [PR Coverage check]

:heart_eyes: **pass** : 18 / 18 (100.00%)




#### file detail

|   |path|covered line|new line|coverage|
|----|----|----|----|----|
|:large_blue_circle:|io/questdb/cutlass/line/CairoLineProtoParserSupport.java|9|9|100.00%|
|:large_blue_circle:|io/questdb/std/Chars.java|7|7|100.00%|
|:large_blue_circle:|io/questdb/cutlass/line/udp/CairoLineProtoParser.java|2|2|100.00%|

**Comment by ideoma** [comment]
#### [PR Coverage check]

:heart_eyes: **pass** : 18 / 18 (100.00%)




#### file detail

|   |path|covered line|new line|coverage|
|----|----|----|----|----|
|:large_blue_circle:|io/questdb/cutlass/line/CairoLineProtoParserSupport.java|18|18|100.00%|

**Comment by ideoma** [comment]
#### [PR Coverage check]

:heart_eyes: **pass** : 18 / 18 (100.00%)




#### file detail

|   |path|covered line|new line|coverage|
|----|----|----|----|----|
|:large_blue_circle:|io/questdb/cutlass/line/CairoLineProtoParserSupport.java|18|18|100.00%|

**Review by bluestreak01 — APPROVED** [review]

**Pull request merged**
