### PR TITLE
fix(core): fix race in reader pool locking

### LINKED ISSUE #2060: Flaky ReaderPoolTest.testLockBusyReader test
Happened on arm64
```
2022-04-25T08:28:52.7652307Z 2022-04-25T08:28:52.682177Z I i.q.c.AbstractCairoTest Tearing down test ReaderPoolTest#testLockBusyReader
2022-04-25T08:28:52.7653866Z 2022-04-25T08:28:52.685198Z E i.q.TestListener ***** Test Failed *****io.questdb.cairo.pool.ReaderPoolTest.testLockBusyReader : 
2022-04-25T08:28:52.7654950Z java.lang.AssertionError: expected null, but was:<io.questdb.cairo.pool.ReaderPool$R@190e2c62>
2022-04-25T08:28:52.7655733Z 	at org.junit.Assert.fail(Assert.java:89)
2022-04-25T08:28:52.7656455Z 	at org.junit.Assert.failNotNull(Assert.java:756)
2022-04-25T08:28:52.7657202Z 	at org.junit.Assert.assertNull(Assert.java:738)
2022-04-25T08:28:52.7657951Z 	at org.junit.Assert.assertNull(Assert.java:748)
2022-04-25T08:28:52.7658879Z 	at io.questdb.cairo.pool.ReaderPoolTest$4.testLockBusyReaderRollTheDice(ReaderPoolTest.java:578)
2022-04-25T08:28:52.7659763Z 	at io.questdb.cairo.pool.ReaderPoolTest$4.run(ReaderPoolTest.java:545)
2022-04-25T08:28:52.7663052Z 	at io.questdb.cairo.pool.ReaderPoolTest.lambda$assertWithPool$32(ReaderPoolTest.java:885)
2022-04-25T08:28:52.7665269Z 	at io.questdb.test.tools.TestUtils.assertMemoryLeak(TestUtils.java:408)
2022-04-25T08:28:52.7667517Z 	at io.questdb.cairo.pool.ReaderPoolTest.assertWithPool(ReaderPoolTest.java:883)
2022-04-25T08:28:52.7668475Z 	at io.questdb.cairo.pool.ReaderPoolTest.assertWithPool(ReaderPoolTest.java:879)
2022-04-25T08:28:52.7669431Z 	at io.questdb.cairo.pool.ReaderPoolTest.testLockBusyReader(ReaderPoolTest.java:536)
2022-04-25T08:28:52.7670296Z 	at jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
2022-04-25T08:28:52.7671171Z 	at jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
2022-04-25T08:28:52.7672150Z 	at jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
2022-04-25T08:28:52.7673014Z 	at java.lang.reflect.Method.invoke(Method.java:566)
2022-04-25T08:28:52.7674051Z 	at org.junit.runners.model.FrameworkMethod$1.runReflectiveCall(FrameworkMethod.java:59)
2022-04-25T08:28:52.7674983Z 	at org.junit.internal.runners.model.ReflectiveCallable.run(ReflectiveCallable.java:12)
2022-04-25T08:28:52.7675930Z 	at org.junit.runners.model.FrameworkMethod.invokeExplosively(FrameworkMethod.java:56)
2022-04-25T08:28:52.7676859Z 	at org.junit.internal.runners.statements.InvokeMethod.evaluate(InvokeMethod.java:17)
2022-04-25T08:28:52.7677781Z 	at org.junit.internal.runners.statements.RunBefores.evaluate(RunBefores.java:26)
2022-04-25T08:28:52.7681394Z 	at org.junit.internal.runners.statements.RunAfters.evaluate(RunAfters.java:27)
2022-04-25T08:28:52.7682406Z 	at org.junit.rules.TestWatcher$1.evaluate(TestWatcher.java:61)
2022-04-25T08:28:52.7685429Z 	at org.junit.internal.runners.statements.FailOnTimeout$CallableStatement.call(FailOnTimeout.java:288)
2022-04-25T08:28:52.7686444Z 	at org.junit.internal.runners.statements.FailOnTimeout$CallableStatement.call(FailOnTimeout.java:282)
2022-04-25T08:28:52.7687333Z 	at java.util.concurrent.FutureTask.run(FutureTask.java:264)
2022-04-25T08:28:52.7688048Z 	at java.lang.Thread.run(Thread.java:829)
```

### PR DESCRIPTION
**Pull request by puzpuzpuz**
Fixes #2060

We had a "classical" race between two threads executing a couple of atomic operations:
* Thread A in a `get()` call won in a CAS for the `nextStatus` field and was supposed to set a value to the volatile `e.next` field after that
* Thread B in a `lock()` call lost a CAS for the `nextStatus` field and then immediately read volatile `e.next` field without waiting for thread A to write the new value

### CODE REVIEW

**Review by bluestreak01 — APPROVED** [review]

**Review by bluestreak01 — CHANGES_REQUESTED** [review]
boke tests

**Comment by puzpuzpuz** [comment]
> broke tests

looking into it

**Comment by puzpuzpuz** [comment]
> broke tests

Fixed in 89caae56b54abc55e5194359cd2e3c748c25da0c

BTW I noticed that we're using expensive CAS operations instead of a volatile read and a equality check. Example: `Unsafe.cas(e, LOCK_OWNER, thread, thread)`. Why not `Unsafe.getUnsafe().getLongVolatile(e, LOCK_OWNER) == thread`? Is it on purpose?

**Comment by ideoma** [comment]
#### [PR Coverage check]

:heart_eyes: **pass** : 4 / 6 (66.67%)




#### file detail

|   |path|covered line|new line|coverage|
|----|----|----|----|----|
|:large_blue_circle:|io/questdb/cairo/pool/ReaderPool.java|4|6|66.67%|

**Comment by ideoma** [comment]
#### [PR Coverage check]

:heart_eyes: **pass** : 4 / 6 (66.67%)




#### file detail

|   |path|covered line|new line|coverage|
|----|----|----|----|----|
|:large_blue_circle:|io/questdb/cairo/pool/ReaderPool.java|4|6|66.67%|

**Comment by puzpuzpuz** [comment]
> This should be an easy enough question to answer if you replace both with `volatile`. Check if tests pass.

Did that in #2726 and got a green CI run. Also, kept the tests running locally for a few minutes and also saw no failures.

**Comment by ideoma** [comment]
#### [PR Coverage check]

:heart_eyes: **pass** : 4 / 6 (66.67%)




#### file detail

|   |path|covered line|new line|coverage|
|----|----|----|----|----|
|:large_blue_circle:|io/questdb/cairo/pool/ReaderPool.java|4|6|66.67%|

**Comment by puzpuzpuz** [comment]
The failed test is #2731

**Comment by jerrinot** [comment]
nice!

**Comment by ideoma** [comment]
@puzpuzpuz  can you please set to reformat and rearrange code on save. 
https://www.jetbrains.com/help/idea/rearrange-code.html#rearrange-on-save

**Comment by puzpuzpuz** [comment]
> @puzpuzpuz can you please set to reformat and rearrange code on save.

Sure, will do. Is there a particular reason why you leave this comment on this PR? It didn't introduce any new methods and has no formatting issues.

**Pull request merged**
