### PR TITLE
fix(core): fix intermittent writing failures

### PR DESCRIPTION
**Pull request by jerrinot**
an attempt to address https://github.com/questdb/questdb-enterprise/issues/95 

The idea behind the fix: `WriterPool.releaseAll()` sets a negative owner to entries which are about to be closed and `getWriterEntry()` was [designed to retry](https://github.com/questdb/questdb/pull/1695) when failing to acquire an entry, but it is racy. This PR improves the likelihood that it'll retry when failing to acquire an entry which is about to be closed. Also, this retrying mechanism is now added to `lock()` where it was completely missing. 

~this is still an experiment as I am not sure about perf. impact: `VarHandles` signature looks scary (boxing, vararg, etc), but chances are it's optimized away, as it's annotated with `@MethodHandle.PolymorphicSignature` and `@IntrinsicCandidate`~

edit: indeed `@MethodHandle.PolymorphicSignature` does the trick: it specializes invocation based on the actual arguments and the callsite. generated bytecode:
```
FRAME CHOP 1
GETSTATIC io/questdb/cairo/pool/WriterPool.ENTRY_OWNER_HANDLER : Ljava/lang/invoke/VarHandle;
ALOAD 6
LDC -1
LLOAD 4
INVOKEVIRTUAL java/lang/invoke/VarHandle.compareAndExchange (Lio/questdb/cairo/pool/WriterPool$Entry;JJ)J
LSTORE 7
```

edit2: VarHandle cannot be used due to our support for JDK8. Unfortunately, `compareAndExchange()` is only available from JDK9+. Thus I implemented a suboptimal yet good enough and hopefully correct alternative.

### CODE REVIEW

**Comment by ideoma** [comment]
#### [PR Coverage check]

:heart_eyes: **pass** : 4 / 8 (50.00%)




#### file detail

|   |path|covered line|new line|coverage|
|----|----|----|----|----|
|:large_blue_circle:|io/questdb/cairo/pool/WriterPool.java|4|8|50.00%|

**Comment by bluestreak01** [comment]
@jerrinot is there a test to reproduce the issue addressed in this PR ?

**Comment by jerrinot** [comment]
@bluestreak01 this was triggered by a flaky test in EE - the test is stable with this change. but let me add a test to this repo too.

**Comment by ideoma** [comment]
#### [PR Coverage check]

:heart_eyes: **pass** : 20 / 22 (90.91%)




#### file detail

|   |path|covered line|new line|coverage|
|----|----|----|----|----|
|:large_blue_circle:|io/questdb/cairo/pool/WriterPool.java|20|22|90.91%|

**Comment by ideoma** [comment]
#### [PR Coverage check]

:heart_eyes: **pass** : 18 / 22 (81.82%)




#### file detail

|   |path|covered line|new line|coverage|
|----|----|----|----|----|
|:large_blue_circle:|io/questdb/cairo/pool/WriterPool.java|18|22|81.82%|

**Comment by jerrinot** [comment]
@bluestreak01 I added a test for the retrying in the `lock()` method. As this mechanism was missing completely the failure could be reproduced with a relatively high probability. 

However, I failed to reproduce the failure for the `getWriterEntry()` case - the racy window is extremely narrow: We would need to change writer ownership between loading the owner and failing CAS here: https://github.com/questdb/questdb/pull/3844/files#diff-1ff170fd00d1f08e9f86e424cb8a93f6b78b85145ae484a20f29dfae214c3477L440-L442

That being said - I think this change can also be seen as a performance micro-optimization: In the happy scenario where the calling thread wins CAS the new code saves one (volatile) load.

**Review by bluestreak01 — APPROVED** [review]

**Comment by ideoma** [comment]
#### [PR Coverage check]

:heart_eyes: **pass** : 18 / 22 (81.82%)




#### file detail

|   |path|covered line|new line|coverage|
|----|----|----|----|----|
|:large_blue_circle:|io/questdb/cairo/pool/WriterPool.java|18|22|81.82%|

**Pull request merged**
