### PR TITLE
fix(sql): fix COPY performance for pre-created tables with non-default symbol capacity

### PR DESCRIPTION
**Pull request by puzpuzpuz**
Refs #3269

COPY was using default symbol table capacity for temporary tables. This led to sub-optimal ingestion performance due to slow symbol lookups. With this patch, temporary tables use the same symbol capacities as the end table.

## Benchmark

Create a 100M test CSV file with this Golang program:
```go
package main

import (
	"bufio"
	"os"
	"strconv"
	"time"
)

func main() {
	f, err := os.Create("/tmp/input.csv")
	if err != nil {
		panic(err)
	}

	defer f.Close()

	_, err = f.WriteString("sym,ts\n")
	if err != nil {
		panic(err)
	}
	f.Sync()

	w := bufio.NewWriter(f)
	for i := 1; i <= 100_000_000; i++ {
		t := time.UnixMicro(int64(i) * 1_000_000)
		_, err := w.WriteString(strconv.Itoa(i%234870) + "," + t.Format("2006-01-02T15:04:05.000000Z") + "\n")
		if err != nil {
			panic(err)
		}
	}

	w.Flush()
	f.Sync()
}
```

Pre-create the table and run COPY on it:
```sql
CREATE TABLE test (sym SYMBOL CAPACITY 300000, ts TIMESTAMP) TIMESTAMP(ts) PARTITION BY YEAR;
COPY test FROM 'input.csv' WITH HEADER true;
```

Before this patch:
```
2023-05-05T08:31:18.791182Z I i.q.c.t.ParallelCsvFileImporter import complete [importId=76f11f07197e248b, file=`/tmp/input.csv`', time=1180s]
```

With this patch:
```
2023-05-05T08:10:23.145525Z I i.q.c.t.ParallelCsvFileImporter import complete [importId=76ee51f64b9008b9, file=`/tmp/input.csv`', time=16s]
```

### CODE REVIEW

**Comment by puzpuzpuz** [comment]
@amyshwang we might want to stress the importance of symbol capacity configuration in the COPY guide in the docs.

**Comment by ideoma** [comment]
#### [PR Coverage check]

:heart_eyes: **pass** : 17 / 18 (94.44%)




#### file detail

|   |path|covered line|new line|coverage|
|----|----|----|----|----|
|:large_blue_circle:|io/questdb/cairo/vm/NullMapWriter.java|0|1|00.00%|
|:large_blue_circle:|io/questdb/cairo/SymbolMapWriter.java|2|2|100.00%|
|:large_blue_circle:|io/questdb/cutlass/text/ParallelCsvFileImporter.java|15|15|100.00%|

**Comment by ideoma** [comment]
#### [PR Coverage check]

:heart_eyes: **pass** : 19 / 20 (95.00%)




#### file detail

|   |path|covered line|new line|coverage|
|----|----|----|----|----|
|:large_blue_circle:|io/questdb/cairo/vm/NullMapWriter.java|0|1|00.00%|
|:large_blue_circle:|io/questdb/cairo/SymbolMapWriter.java|2|2|100.00%|
|:large_blue_circle:|io/questdb/cutlass/text/ParallelCsvFileImporter.java|17|17|100.00%|

**Comment by ideoma** [comment]
#### [PR Coverage check]

:heart_eyes: **pass** : 19 / 20 (95.00%)




#### file detail

|   |path|covered line|new line|coverage|
|----|----|----|----|----|
|:large_blue_circle:|io/questdb/cairo/vm/NullMapWriter.java|0|1|00.00%|
|:large_blue_circle:|io/questdb/cairo/SymbolMapWriter.java|2|2|100.00%|
|:large_blue_circle:|io/questdb/cutlass/text/ParallelCsvFileImporter.java|17|17|100.00%|

**Review by bluestreak01 — APPROVED** [review]

**Comment by ideoma** [comment]
#### [PR Coverage check]

:heart_eyes: **pass** : 19 / 20 (95.00%)




#### file detail

|   |path|covered line|new line|coverage|
|----|----|----|----|----|
|:large_blue_circle:|io/questdb/cairo/vm/NullMapWriter.java|0|1|00.00%|
|:large_blue_circle:|io/questdb/cairo/SymbolMapWriter.java|2|2|100.00%|
|:large_blue_circle:|io/questdb/cutlass/text/ParallelCsvFileImporter.java|17|17|100.00%|

**Review by bluestreak01 — APPROVED** [review]

**Pull request merged**
