### PR TITLE
feat(http): consider unhandled errors in health check endpoint

### PR DESCRIPTION
**Pull request by puzpuzpuz**
Implements https://github.com/questdb/rfc/discussions/47

Also includes the following:
* Fixes NPE on root path health check with enabled metrics (`curl -v http://127.0.0.1:9003` on an instance with enabled metrics to reproduce)
* Exposes basic table writer metrics

New metrics are the following (a fragment from the `/metrics` endpoint's response):
```
# TYPE questdb_unhandled_errors_total counter
questdb_unhandled_errors_total 0

# TYPE questdb_commits_total counter
questdb_commits_total 600

# TYPE questdb_o3_commits_total counter
questdb_o3_commits_total 0

# TYPE questdb_committed_rows_total counter
questdb_committed_rows_total 599001

# TYPE questdb_rollbacks_total counter
questdb_rollbacks_total 0
```

`questdb_committed_rows_total` visualized in Prometheus:
Screenshot from 2022-02-10 17-40-16

### CODE REVIEW

**Comment by puzpuzpuz** [comment]
> LineTcpWriterJob

Added a counter increment there (see 751557382e5d0b613b0f8ee3647f9c68469854f4) and checked other similar places. Nothing caught my eye. Do you have any suggestions?

**Comment by bluestreak01** [comment]
Perhaps this:

image

**Comment by bluestreak01** [comment]
LineTcpConnectionContext:

image

**Comment by ideoma** [comment]
#### [PR Coverage check]

:heart_eyes: **pass** : 104 / 113 (92.04%)




#### file detail

|   |path|covered line|new line|coverage|
|----|----|----|----|----|
|:large_blue_circle:|io/questdb/ServerMain.java|0|7|00.00%|
|:large_blue_circle:|io/questdb/cutlass/http/processors/TextQueryProcessor.java|1|2|50.00%|
|:large_blue_circle:|io/questdb/cutlass/http/processors/JsonQueryProcessor.java|3|4|75.00%|
|:large_blue_circle:|io/questdb/cairo/CairoEngine.java|7|7|100.00%|
|:large_blue_circle:|io/questdb/log/LogFactory.java|1|1|100.00%|
|:large_blue_circle:|io/questdb/cutlass/line/tcp/LineTcpMeasurementScheduler.java|2|2|100.00%|
|:large_blue_circle:|io/questdb/mp/WorkerPool.java|2|2|100.00%|
|:large_blue_circle:|io/questdb/WorkerPoolAwareConfiguration.java|2|2|100.00%|
|:large_blue_circle:|io/questdb/cairo/TableWriterMetrics.java|14|14|100.00%|
|:large_blue_circle:|io/questdb/cairo/pool/WriterPool.java|3|3|100.00%|
|:large_blue_circle:|io/questdb/Metrics.java|4|4|100.00%|
|:large_blue_circle:|io/questdb/cutlass/line/tcp/LineTcpWriterJob.java|2|2|100.00%|
|:large_blue_circle:|io/questdb/metrics/Counter.java|2|2|100.00%|
|:large_blue_circle:|io/questdb/mp/Worker.java|2|2|100.00%|
|:large_blue_circle:|io/questdb/cutlass/http/processors/HealthCheckMetrics.java|6|6|100.00%|
|:large_blue_circle:|io/questdb/griffin/SqlCompiler.java|1|1|100.00%|
|:large_blue_circle:|io/questdb/metrics/NullCounter.java|1|1|100.00%|
|:large_blue_circle:|io/questdb/cutlass/http/processors/HealthCheckProcessor.java|11|11|100.00%|
|:large_blue_circle:|io/questdb/cutlass/http/HttpConnectionContext.java|3|3|100.00%|
|:large_blue_circle:|io/questdb/cutlass/line/tcp/LineTcpReceiver.java|8|8|100.00%|
|:large_blue_circle:|io/questdb/cairo/TableWriter.java|12|12|100.00%|
|:large_blue_circle:|io/questdb/cutlass/http/HttpServer.java|12|12|100.00%|
|:large_blue_circle:|io/questdb/metrics/CounterImpl.java|1|1|100.00%|
|:large_blue_circle:|io/questdb/cutlass/line/tcp/LineTcpAuthConnectionContext.java|1|1|100.00%|
|:large_blue_circle:|io/questdb/cutlass/line/tcp/LineTcpConnectionContext.java|3|3|100.00%|

**Comment by puzpuzpuz** [comment]
Added suggested unhandled error counter increments in b85d8ce51417f99f15384c88c71de9169c3f7e22.

Also, added a separate handler for `HttpException` in `JsonQueryProcessor` in f7348705f5ed1bf8610f837090713e7d841a2ea6. That's because I don't think we should treat these exception as an unhanded (critical, non-recoverable) error.

**Comment by ideoma** [comment]
#### [PR Coverage check]

:heart_eyes: **pass** : 107 / 118 (90.68%)




#### file detail

|   |path|covered line|new line|coverage|
|----|----|----|----|----|
|:large_blue_circle:|io/questdb/ServerMain.java|0|7|00.00%|
|:large_blue_circle:|io/questdb/cutlass/http/processors/JsonQueryProcessor.java|3|6|50.00%|
|:large_blue_circle:|io/questdb/cutlass/http/processors/TextQueryProcessor.java|1|2|50.00%|
|:large_blue_circle:|io/questdb/cairo/CairoEngine.java|7|7|100.00%|
|:large_blue_circle:|io/questdb/log/LogFactory.java|1|1|100.00%|
|:large_blue_circle:|io/questdb/cutlass/line/tcp/LineTcpMeasurementScheduler.java|2|2|100.00%|
|:large_blue_circle:|io/questdb/network/NoSpaceLeftInResponseBufferException.java|3|3|100.00%|
|:large_blue_circle:|io/questdb/mp/WorkerPool.java|2|2|100.00%|
|:large_blue_circle:|io/questdb/WorkerPoolAwareConfiguration.java|2|2|100.00%|
|:large_blue_circle:|io/questdb/cairo/TableWriterMetrics.java|14|14|100.00%|
|:large_blue_circle:|io/questdb/cairo/pool/WriterPool.java|3|3|100.00%|
|:large_blue_circle:|io/questdb/Metrics.java|4|4|100.00%|
|:large_blue_circle:|io/questdb/cutlass/line/tcp/LineTcpWriterJob.java|2|2|100.00%|
|:large_blue_circle:|io/questdb/metrics/Counter.java|2|2|100.00%|
|:large_blue_circle:|io/questdb/mp/Worker.java|2|2|100.00%|
|:large_blue_circle:|io/questdb/cutlass/http/processors/HealthCheckMetrics.java|6|6|100.00%|
|:large_blue_circle:|io/questdb/griffin/SqlCompiler.java|1|1|100.00%|
|:large_blue_circle:|io/questdb/metrics/NullCounter.java|1|1|100.00%|
|:large_blue_circle:|io/questdb/cutlass/http/processors/HealthCheckProcessor.java|11|11|100.00%|
|:large_blue_circle:|io/questdb/cutlass/http/HttpConnectionContext.java|3|3|100.00%|
|:large_blue_circle:|io/questdb/cutlass/line/tcp/LineTcpReceiver.java|8|8|100.00%|
|:large_blue_circle:|io/questdb/cairo/TableWriter.java|12|12|100.00%|
|:large_blue_circle:|io/questdb/cutlass/http/HttpServer.java|12|12|100.00%|
|:large_blue_circle:|io/questdb/metrics/CounterImpl.java|1|1|100.00%|
|:large_blue_circle:|io/questdb/cutlass/line/tcp/LineTcpAuthConnectionContext.java|1|1|100.00%|
|:large_blue_circle:|io/questdb/cutlass/line/tcp/LineTcpConnectionContext.java|3|3|100.00%|

**Review by bluestreak01 — APPROVED** [review]

**Comment by ideoma** [comment]
#### [PR Coverage check]

:heart_eyes: **pass** : 107 / 118 (90.68%)




#### file detail

|   |path|covered line|new line|coverage|
|----|----|----|----|----|
|:large_blue_circle:|io/questdb/ServerMain.java|0|7|00.00%|
|:large_blue_circle:|io/questdb/cutlass/http/processors/JsonQueryProcessor.java|3|6|50.00%|
|:large_blue_circle:|io/questdb/cutlass/http/processors/TextQueryProcessor.java|1|2|50.00%|
|:large_blue_circle:|io/questdb/cairo/CairoEngine.java|7|7|100.00%|
|:large_blue_circle:|io/questdb/log/LogFactory.java|1|1|100.00%|
|:large_blue_circle:|io/questdb/cutlass/line/tcp/LineTcpMeasurementScheduler.java|2|2|100.00%|
|:large_blue_circle:|io/questdb/network/NoSpaceLeftInResponseBufferException.java|3|3|100.00%|
|:large_blue_circle:|io/questdb/mp/WorkerPool.java|2|2|100.00%|
|:large_blue_circle:|io/questdb/WorkerPoolAwareConfiguration.java|2|2|100.00%|
|:large_blue_circle:|io/questdb/cairo/TableWriterMetrics.java|14|14|100.00%|
|:large_blue_circle:|io/questdb/cairo/pool/WriterPool.java|3|3|100.00%|
|:large_blue_circle:|io/questdb/Metrics.java|4|4|100.00%|
|:large_blue_circle:|io/questdb/cutlass/line/tcp/LineTcpWriterJob.java|2|2|100.00%|
|:large_blue_circle:|io/questdb/metrics/Counter.java|2|2|100.00%|
|:large_blue_circle:|io/questdb/mp/Worker.java|2|2|100.00%|
|:large_blue_circle:|io/questdb/cutlass/http/processors/HealthCheckMetrics.java|6|6|100.00%|
|:large_blue_circle:|io/questdb/griffin/SqlCompiler.java|1|1|100.00%|
|:large_blue_circle:|io/questdb/metrics/NullCounter.java|1|1|100.00%|
|:large_blue_circle:|io/questdb/cutlass/http/processors/HealthCheckProcessor.java|11|11|100.00%|
|:large_blue_circle:|io/questdb/cutlass/http/HttpConnectionContext.java|3|3|100.00%|
|:large_blue_circle:|io/questdb/cutlass/line/tcp/LineTcpReceiver.java|8|8|100.00%|
|:large_blue_circle:|io/questdb/cairo/TableWriter.java|12|12|100.00%|
|:large_blue_circle:|io/questdb/cutlass/http/HttpServer.java|12|12|100.00%|
|:large_blue_circle:|io/questdb/metrics/CounterImpl.java|1|1|100.00%|
|:large_blue_circle:|io/questdb/cutlass/line/tcp/LineTcpAuthConnectionContext.java|1|1|100.00%|
|:large_blue_circle:|io/questdb/cutlass/line/tcp/LineTcpConnectionContext.java|3|3|100.00%|

**Pull request merged**
