### PR TITLE
fix(sql): fix keyed group by crashing on int column with high cardinality 

### PR DESCRIPTION
**Pull request by bziobrowski**
This PR fixes crash occuring on :

```sql
create table tab as  (select cast(x as int) x1, cast(x as date) dt from long_sequence(1000000000));
select count(*) from tab  ; 

select x1, count(*) from tab group by x1 ; 
```

If column cardinality is high then rosti can allocate ~ 100 bytes * distinct_values * num_of_workers . 
In this case it's 10GB+ but could be multiplied by factories being cached per thread . 

PR also :
- fixes oom handling in rosti that leads to crash on bad memory access
- improves memory tracking using new NATIVE_ROSTI tag 
- releases rosti memory as early as possible (important especially when cardinality is big and there are many workers) 
- tests rosti in various worker & queue setups (and works around id issue)

### CODE REVIEW

**Comment by ideoma** [comment]
#### [PR Coverage check]

:disappointed: **fail** : 23 / 62 (37.10%)




#### file detail

|   |path|covered line|new line|coverage|
|----|----|----|----|----|
|:large_blue_circle:|io/questdb/std/Rosti.java|10|31|32.26%|
|:large_blue_circle:|io/questdb/griffin/engine/groupby/vect/GroupByRecordCursorFactory.java|10|28|35.71%|
|:large_blue_circle:|io/questdb/griffin/engine/groupby/vect/VectorAggregateEntry.java|2|2|100.00%|
|:large_blue_circle:|io/questdb/std/MemoryTag.java|1|1|100.00%|

**Comment by questdb-butler** [comment]
<table>
  <thead>
    <tr>
      <th width="50"></th>
      <th width="100%" data-danger-table="true">Fails</th>
    </tr>
  </thead>
  <tbody><tr>
      <td>:no_entry_sign:</td>
      <td>

  Please update the PR title to match this format:
`type(subType): description`

Where `type` is one of:
`feat`, `fix`, `chore`, `docs`, `style`, `refactor`, `perf`, `test`, `build`, `ci`, `chore`, `revert`

And: `subType` is one of:
`build`, `sql`, `log`, `mig`, `core`, `ilp`, `pgwire`, `http`, `conf`

For Example:

```
perf(sql): improve pattern matching performance for SELECT sub-queries
```
  </td>
    </tr>
  </tbody>
</table>




<p align="right">
  Generated by :no_entry_sign: <a href="https://danger.systems/js">dangerJS</a> against 2c9d56bf4987b19c5a62a2e663c018776974ebe1
</p>

**Comment by ideoma** [comment]
#### [PR Coverage check]

:disappointed: **fail** : 44 / 90 (48.89%)




#### file detail

|   |path|covered line|new line|coverage|
|----|----|----|----|----|
|:large_blue_circle:|io/questdb/griffin/engine/groupby/vect/MaxDateVectorAggregateFunction.java|0|1|00.00%|
|:large_blue_circle:|io/questdb/griffin/engine/groupby/vect/AvgDoubleVectorAggregateFunction.java|0|1|00.00%|
|:large_blue_circle:|io/questdb/griffin/engine/groupby/vect/CountVectorAggregateFunction.java|0|1|00.00%|
|:large_blue_circle:|io/questdb/griffin/engine/groupby/vect/MaxDoubleVectorAggregateFunction.java|0|1|00.00%|
|:large_blue_circle:|io/questdb/griffin/engine/groupby/vect/MaxLongVectorAggregateFunction.java|0|1|00.00%|
|:large_blue_circle:|io/questdb/griffin/engine/groupby/vect/MinIntVectorAggregateFunction.java|0|1|00.00%|
|:large_blue_circle:|io/questdb/griffin/engine/groupby/vect/MinTimestampVectorAggregateFunction.java|0|1|00.00%|
|:large_blue_circle:|io/questdb/griffin/engine/groupby/vect/SumDoubleVectorAggregateFunction.java|0|1|00.00%|
|:large_blue_circle:|io/questdb/griffin/engine/groupby/vect/SumLong256VectorAggregateFunction.java|0|1|00.00%|
|:large_blue_circle:|io/questdb/griffin/engine/groupby/vect/MaxIntVectorAggregateFunction.java|0|1|00.00%|
|:large_blue_circle:|io/questdb/griffin/engine/groupby/vect/NSumDoubleVectorAggregateFunction.java|0|1|00.00%|
|:large_blue_circle:|io/questdb/griffin/engine/groupby/vect/SumLongVectorAggregateFunction.java|0|1|00.00%|
|:large_blue_circle:|io/questdb/griffin/engine/groupby/vect/AvgLongVectorAggregateFunction.java|0|1|00.00%|
|:large_blue_circle:|io/questdb/griffin/engine/groupby/vect/SumIntVectorAggregateFunction.java|0|1|00.00%|
|:large_blue_circle:|io/questdb/griffin/engine/groupby/vect/AvgIntVectorAggregateFunction.java|0|1|00.00%|
|:large_blue_circle:|io/questdb/griffin/engine/groupby/vect/MinDoubleVectorAggregateFunction.java|0|1|00.00%|
|:large_blue_circle:|io/questdb/griffin/engine/groupby/vect/SumTimestampVectorAggregateFunction.java|0|1|00.00%|
|:large_blue_circle:|io/questdb/griffin/engine/groupby/vect/MinLongVectorAggregateFunction.java|0|1|00.00%|
|:large_blue_circle:|io/questdb/griffin/engine/groupby/vect/KSumDoubleVectorAggregateFunction.java|0|1|00.00%|
|:large_blue_circle:|io/questdb/griffin/engine/groupby/vect/SumDateVectorAggregateFunction.java|0|1|00.00%|
|:large_blue_circle:|io/questdb/griffin/engine/groupby/vect/MaxTimestampVectorAggregateFunction.java|0|1|00.00%|
|:large_blue_circle:|io/questdb/griffin/engine/groupby/vect/MinDateVectorAggregateFunction.java|0|1|00.00%|
|:large_blue_circle:|io/questdb/griffin/engine/groupby/vect/GroupByRecordCursorFactory.java|11|34|32.35%|
|:large_blue_circle:|io/questdb/std/Rosti.java|30|31|96.77%|
|:large_blue_circle:|io/questdb/griffin/engine/groupby/vect/VectorAggregateEntry.java|2|2|100.00%|
|:large_blue_circle:|io/questdb/std/MemoryTag.java|1|1|100.00%|

**Comment by bziobrowski** [comment]
For some reason coverage on GroupByRecordCursorFactory is badly calculated .

**Comment by ideoma** [comment]
#### [PR Coverage check]

:disappointed: **fail** : 41 / 90 (45.56%)




#### file detail

|   |path|covered line|new line|coverage|
|----|----|----|----|----|
|:large_blue_circle:|io/questdb/griffin/engine/groupby/vect/MaxDateVectorAggregateFunction.java|0|1|00.00%|
|:large_blue_circle:|io/questdb/griffin/engine/groupby/vect/AvgDoubleVectorAggregateFunction.java|0|1|00.00%|
|:large_blue_circle:|io/questdb/griffin/engine/groupby/vect/CountVectorAggregateFunction.java|0|1|00.00%|
|:large_blue_circle:|io/questdb/griffin/engine/groupby/vect/MaxDoubleVectorAggregateFunction.java|0|1|00.00%|
|:large_blue_circle:|io/questdb/griffin/engine/groupby/vect/MaxLongVectorAggregateFunction.java|0|1|00.00%|
|:large_blue_circle:|io/questdb/griffin/engine/groupby/vect/MinIntVectorAggregateFunction.java|0|1|00.00%|
|:large_blue_circle:|io/questdb/griffin/engine/groupby/vect/MinTimestampVectorAggregateFunction.java|0|1|00.00%|
|:large_blue_circle:|io/questdb/griffin/engine/groupby/vect/SumDoubleVectorAggregateFunction.java|0|1|00.00%|
|:large_blue_circle:|io/questdb/griffin/engine/groupby/vect/SumLong256VectorAggregateFunction.java|0|1|00.00%|
|:large_blue_circle:|io/questdb/griffin/engine/groupby/vect/MaxIntVectorAggregateFunction.java|0|1|00.00%|
|:large_blue_circle:|io/questdb/griffin/engine/groupby/vect/NSumDoubleVectorAggregateFunction.java|0|1|00.00%|
|:large_blue_circle:|io/questdb/griffin/engine/groupby/vect/SumLongVectorAggregateFunction.java|0|1|00.00%|
|:large_blue_circle:|io/questdb/griffin/engine/groupby/vect/AvgLongVectorAggregateFunction.java|0|1|00.00%|
|:large_blue_circle:|io/questdb/griffin/engine/groupby/vect/SumIntVectorAggregateFunction.java|0|1|00.00%|
|:large_blue_circle:|io/questdb/griffin/engine/groupby/vect/AvgIntVectorAggregateFunction.java|0|1|00.00%|
|:large_blue_circle:|io/questdb/griffin/engine/groupby/vect/MinDoubleVectorAggregateFunction.java|0|1|00.00%|
|:large_blue_circle:|io/questdb/griffin/engine/groupby/vect/SumTimestampVectorAggregateFunction.java|0|1|00.00%|
|:large_blue_circle:|io/questdb/griffin/engine/groupby/vect/MinLongVectorAggregateFunction.java|0|1|00.00%|
|:large_blue_circle:|io/questdb/griffin/engine/groupby/vect/KSumDoubleVectorAggregateFunction.java|0|1|00.00%|
|:large_blue_circle:|io/questdb/griffin/engine/groupby/vect/SumDateVectorAggregateFunction.java|0|1|00.00%|
|:large_blue_circle:|io/questdb/griffin/engine/groupby/vect/MaxTimestampVectorAggregateFunction.java|0|1|00.00%|
|:large_blue_circle:|io/questdb/griffin/engine/groupby/vect/MinDateVectorAggregateFunction.java|0|1|00.00%|
|:large_blue_circle:|io/questdb/griffin/engine/groupby/vect/GroupByRecordCursorFactory.java|11|34|32.35%|
|:large_blue_circle:|io/questdb/std/Rosti.java|27|31|87.10%|
|:large_blue_circle:|io/questdb/griffin/engine/groupby/vect/VectorAggregateEntry.java|2|2|100.00%|
|:large_blue_circle:|io/questdb/std/MemoryTag.java|1|1|100.00%|

**Comment by bluestreak01** [comment]
I could not crash on `master` Windows using described method

**Review by bluestreak01 — CHANGES_REQUESTED** [review]
I think test coverage issue is genuine. This code block is not tested on my machine either:

image

Additionally none of `griffin` tests stop on breakpoint inside this code block.

**Comment by bziobrowski** [comment]
It depends on how much ram you have . Add another zero and you'll trigger it in one run, otheriwise it might take a few runs for cached factories to fill memory .

**Comment by ideoma** [comment]
#### [PR Coverage check]

:heart_eyes: **pass** : 82 / 90 (91.11%)




#### file detail

|   |path|covered line|new line|coverage|
|----|----|----|----|----|
|:large_blue_circle:|io/questdb/griffin/engine/groupby/vect/MaxLongVectorAggregateFunction.java|0|1|00.00%|
|:large_blue_circle:|io/questdb/griffin/engine/groupby/vect/SumLongVectorAggregateFunction.java|0|1|00.00%|
|:large_blue_circle:|io/questdb/griffin/engine/groupby/vect/MinLongVectorAggregateFunction.java|0|1|00.00%|
|:large_blue_circle:|io/questdb/griffin/engine/groupby/vect/GroupByRecordCursorFactory.java|30|34|88.24%|
|:large_blue_circle:|io/questdb/std/Rosti.java|30|31|96.77%|
|:large_blue_circle:|io/questdb/griffin/engine/groupby/vect/MaxDateVectorAggregateFunction.java|1|1|100.00%|
|:large_blue_circle:|io/questdb/griffin/engine/groupby/vect/AvgDoubleVectorAggregateFunction.java|1|1|100.00%|
|:large_blue_circle:|io/questdb/griffin/engine/groupby/vect/CountVectorAggregateFunction.java|1|1|100.00%|
|:large_blue_circle:|io/questdb/griffin/engine/groupby/vect/MaxDoubleVectorAggregateFunction.java|1|1|100.00%|
|:large_blue_circle:|io/questdb/griffin/engine/groupby/vect/MinIntVectorAggregateFunction.java|1|1|100.00%|
|:large_blue_circle:|io/questdb/griffin/engine/groupby/vect/MinTimestampVectorAggregateFunction.java|1|1|100.00%|
|:large_blue_circle:|io/questdb/griffin/engine/groupby/vect/SumDoubleVectorAggregateFunction.java|1|1|100.00%|
|:large_blue_circle:|io/questdb/griffin/engine/groupby/vect/SumLong256VectorAggregateFunction.java|1|1|100.00%|
|:large_blue_circle:|io/questdb/griffin/engine/groupby/vect/MaxIntVectorAggregateFunction.java|1|1|100.00%|
|:large_blue_circle:|io/questdb/griffin/engine/groupby/vect/NSumDoubleVectorAggregateFunction.java|1|1|100.00%|
|:large_blue_circle:|io/questdb/griffin/engine/groupby/vect/AvgLongVectorAggregateFunction.java|1|1|100.00%|
|:large_blue_circle:|io/questdb/griffin/engine/groupby/vect/SumIntVectorAggregateFunction.java|1|1|100.00%|
|:large_blue_circle:|io/questdb/griffin/engine/groupby/vect/AvgIntVectorAggregateFunction.java|1|1|100.00%|
|:large_blue_circle:|io/questdb/griffin/engine/groupby/vect/MinDoubleVectorAggregateFunction.java|1|1|100.00%|
|:large_blue_circle:|io/questdb/griffin/engine/groupby/vect/VectorAggregateEntry.java|2|2|100.00%|
|:large_blue_circle:|io/questdb/std/MemoryTag.java|1|1|100.00%|
|:large_blue_circle:|io/questdb/griffin/engine/groupby/vect/SumTimestampVectorAggregateFunction.java|1|1|100.00%|
|:large_blue_circle:|io/questdb/griffin/engine/groupby/vect/KSumDoubleVectorAggregateFunction.java|1|1|100.00%|
|:large_blue_circle:|io/questdb/griffin/engine/groupby/vect/SumDateVectorAggregateFunction.java|1|1|100.00%|
|:large_blue_circle:|io/questdb/griffin/engine/groupby/vect/MaxTimestampVectorAggregateFunction.java|1|1|100.00%|
|:large_blue_circle:|io/questdb/griffin/engine/groupby/vect/MinDateVectorAggregateFunction.java|1|1|100.00%|

**Comment by ideoma** [comment]
#### [PR Coverage check]

:heart_eyes: **pass** : 82 / 90 (91.11%)




#### file detail

|   |path|covered line|new line|coverage|
|----|----|----|----|----|
|:large_blue_circle:|io/questdb/std/Rosti.java|27|31|87.10%|
|:large_blue_circle:|io/questdb/griffin/engine/groupby/vect/GroupByRecordCursorFactory.java|30|34|88.24%|
|:large_blue_circle:|io/questdb/griffin/engine/groupby/vect/MaxDateVectorAggregateFunction.java|1|1|100.00%|
|:large_blue_circle:|io/questdb/griffin/engine/groupby/vect/AvgDoubleVectorAggregateFunction.java|1|1|100.00%|
|:large_blue_circle:|io/questdb/griffin/engine/groupby/vect/CountVectorAggregateFunction.java|1|1|100.00%|
|:large_blue_circle:|io/questdb/griffin/engine/groupby/vect/MaxDoubleVectorAggregateFunction.java|1|1|100.00%|
|:large_blue_circle:|io/questdb/griffin/engine/groupby/vect/MaxLongVectorAggregateFunction.java|1|1|100.00%|
|:large_blue_circle:|io/questdb/griffin/engine/groupby/vect/MinIntVectorAggregateFunction.java|1|1|100.00%|
|:large_blue_circle:|io/questdb/griffin/engine/groupby/vect/MinTimestampVectorAggregateFunction.java|1|1|100.00%|
|:large_blue_circle:|io/questdb/griffin/engine/groupby/vect/SumDoubleVectorAggregateFunction.java|1|1|100.00%|
|:large_blue_circle:|io/questdb/griffin/engine/groupby/vect/SumLong256VectorAggregateFunction.java|1|1|100.00%|
|:large_blue_circle:|io/questdb/griffin/engine/groupby/vect/MaxIntVectorAggregateFunction.java|1|1|100.00%|
|:large_blue_circle:|io/questdb/griffin/engine/groupby/vect/NSumDoubleVectorAggregateFunction.java|1|1|100.00%|
|:large_blue_circle:|io/questdb/griffin/engine/groupby/vect/SumLongVectorAggregateFunction.java|1|1|100.00%|
|:large_blue_circle:|io/questdb/griffin/engine/groupby/vect/AvgLongVectorAggregateFunction.java|1|1|100.00%|
|:large_blue_circle:|io/questdb/griffin/engine/groupby/vect/SumIntVectorAggregateFunction.java|1|1|100.00%|
|:large_blue_circle:|io/questdb/griffin/engine/groupby/vect/AvgIntVectorAggregateFunction.java|1|1|100.00%|
|:large_blue_circle:|io/questdb/griffin/engine/groupby/vect/MinDoubleVectorAggregateFunction.java|1|1|100.00%|
|:large_blue_circle:|io/questdb/griffin/engine/groupby/vect/VectorAggregateEntry.java|2|2|100.00%|
|:large_blue_circle:|io/questdb/std/MemoryTag.java|1|1|100.00%|
|:large_blue_circle:|io/questdb/griffin/engine/groupby/vect/SumTimestampVectorAggregateFunction.java|1|1|100.00%|
|:large_blue_circle:|io/questdb/griffin/engine/groupby/vect/MinLongVectorAggregateFunction.java|1|1|100.00%|
|:large_blue_circle:|io/questdb/griffin/engine/groupby/vect/KSumDoubleVectorAggregateFunction.java|1|1|100.00%|
|:large_blue_circle:|io/questdb/griffin/engine/groupby/vect/SumDateVectorAggregateFunction.java|1|1|100.00%|
|:large_blue_circle:|io/questdb/griffin/engine/groupby/vect/MaxTimestampVectorAggregateFunction.java|1|1|100.00%|
|:large_blue_circle:|io/questdb/griffin/engine/groupby/vect/MinDateVectorAggregateFunction.java|1|1|100.00%|

**Comment by ideoma** [comment]
#### [PR Coverage check]

:heart_eyes: **pass** : 82 / 90 (91.11%)




#### file detail

|   |path|covered line|new line|coverage|
|----|----|----|----|----|
|:large_blue_circle:|io/questdb/std/Rosti.java|27|31|87.10%|
|:large_blue_circle:|io/questdb/griffin/engine/groupby/vect/GroupByRecordCursorFactory.java|30|34|88.24%|
|:large_blue_circle:|io/questdb/griffin/engine/groupby/vect/MaxDateVectorAggregateFunction.java|1|1|100.00%|
|:large_blue_circle:|io/questdb/griffin/engine/groupby/vect/AvgDoubleVectorAggregateFunction.java|1|1|100.00%|
|:large_blue_circle:|io/questdb/griffin/engine/groupby/vect/CountVectorAggregateFunction.java|1|1|100.00%|
|:large_blue_circle:|io/questdb/griffin/engine/groupby/vect/MaxDoubleVectorAggregateFunction.java|1|1|100.00%|
|:large_blue_circle:|io/questdb/griffin/engine/groupby/vect/MaxLongVectorAggregateFunction.java|1|1|100.00%|
|:large_blue_circle:|io/questdb/griffin/engine/groupby/vect/MinIntVectorAggregateFunction.java|1|1|100.00%|
|:large_blue_circle:|io/questdb/griffin/engine/groupby/vect/MinTimestampVectorAggregateFunction.java|1|1|100.00%|
|:large_blue_circle:|io/questdb/griffin/engine/groupby/vect/SumDoubleVectorAggregateFunction.java|1|1|100.00%|
|:large_blue_circle:|io/questdb/griffin/engine/groupby/vect/SumLong256VectorAggregateFunction.java|1|1|100.00%|
|:large_blue_circle:|io/questdb/griffin/engine/groupby/vect/MaxIntVectorAggregateFunction.java|1|1|100.00%|
|:large_blue_circle:|io/questdb/griffin/engine/groupby/vect/NSumDoubleVectorAggregateFunction.java|1|1|100.00%|
|:large_blue_circle:|io/questdb/griffin/engine/groupby/vect/SumLongVectorAggregateFunction.java|1|1|100.00%|
|:large_blue_circle:|io/questdb/griffin/engine/groupby/vect/AvgLongVectorAggregateFunction.java|1|1|100.00%|
|:large_blue_circle:|io/questdb/griffin/engine/groupby/vect/SumIntVectorAggregateFunction.java|1|1|100.00%|
|:large_blue_circle:|io/questdb/griffin/engine/groupby/vect/AvgIntVectorAggregateFunction.java|1|1|100.00%|
|:large_blue_circle:|io/questdb/griffin/engine/groupby/vect/MinDoubleVectorAggregateFunction.java|1|1|100.00%|
|:large_blue_circle:|io/questdb/griffin/engine/groupby/vect/VectorAggregateEntry.java|2|2|100.00%|
|:large_blue_circle:|io/questdb/std/MemoryTag.java|1|1|100.00%|
|:large_blue_circle:|io/questdb/griffin/engine/groupby/vect/SumTimestampVectorAggregateFunction.java|1|1|100.00%|
|:large_blue_circle:|io/questdb/griffin/engine/groupby/vect/MinLongVectorAggregateFunction.java|1|1|100.00%|
|:large_blue_circle:|io/questdb/griffin/engine/groupby/vect/KSumDoubleVectorAggregateFunction.java|1|1|100.00%|
|:large_blue_circle:|io/questdb/griffin/engine/groupby/vect/SumDateVectorAggregateFunction.java|1|1|100.00%|
|:large_blue_circle:|io/questdb/griffin/engine/groupby/vect/MaxTimestampVectorAggregateFunction.java|1|1|100.00%|
|:large_blue_circle:|io/questdb/griffin/engine/groupby/vect/MinDateVectorAggregateFunction.java|1|1|100.00%|

**Comment by bluestreak01** [comment]
I not certain on how to do that, perhaps @eugenels has more ideas?

**Comment by bziobrowski** [comment]
I think we should merge this PR and leave adding more tests around OOM to another one. 
OOM could be triggered artificially if we replace direct malloc call with a function pointer and then - in test - replace it with stub that returns nullptr (via JNI) .

**Comment by ideoma** [comment]
#### [PR Coverage check]

:heart_eyes: **pass** : 85 / 91 (93.41%)




#### file detail

|   |path|covered line|new line|coverage|
|----|----|----|----|----|
|:large_blue_circle:|io/questdb/griffin/engine/groupby/vect/GroupByRecordCursorFactory.java|31|35|88.57%|
|:large_blue_circle:|io/questdb/std/Rosti.java|29|31|93.55%|
|:large_blue_circle:|io/questdb/griffin/engine/groupby/vect/MaxDateVectorAggregateFunction.java|1|1|100.00%|
|:large_blue_circle:|io/questdb/griffin/engine/groupby/vect/AvgDoubleVectorAggregateFunction.java|1|1|100.00%|
|:large_blue_circle:|io/questdb/griffin/engine/groupby/vect/CountVectorAggregateFunction.java|1|1|100.00%|
|:large_blue_circle:|io/questdb/griffin/engine/groupby/vect/MaxDoubleVectorAggregateFunction.java|1|1|100.00%|
|:large_blue_circle:|io/questdb/griffin/engine/groupby/vect/MaxLongVectorAggregateFunction.java|1|1|100.00%|
|:large_blue_circle:|io/questdb/griffin/engine/groupby/vect/MinIntVectorAggregateFunction.java|1|1|100.00%|
|:large_blue_circle:|io/questdb/griffin/engine/groupby/vect/MinTimestampVectorAggregateFunction.java|1|1|100.00%|
|:large_blue_circle:|io/questdb/griffin/engine/groupby/vect/SumDoubleVectorAggregateFunction.java|1|1|100.00%|
|:large_blue_circle:|io/questdb/griffin/engine/groupby/vect/SumLong256VectorAggregateFunction.java|1|1|100.00%|
|:large_blue_circle:|io/questdb/griffin/engine/groupby/vect/MaxIntVectorAggregateFunction.java|1|1|100.00%|
|:large_blue_circle:|io/questdb/griffin/engine/groupby/vect/NSumDoubleVectorAggregateFunction.java|1|1|100.00%|
|:large_blue_circle:|io/questdb/griffin/engine/groupby/vect/SumLongVectorAggregateFunction.java|1|1|100.00%|
|:large_blue_circle:|io/questdb/griffin/engine/groupby/vect/AvgLongVectorAggregateFunction.java|1|1|100.00%|
|:large_blue_circle:|io/questdb/griffin/engine/groupby/vect/SumIntVectorAggregateFunction.java|1|1|100.00%|
|:large_blue_circle:|io/questdb/griffin/engine/groupby/vect/AvgIntVectorAggregateFunction.java|1|1|100.00%|
|:large_blue_circle:|io/questdb/griffin/engine/groupby/vect/MinDoubleVectorAggregateFunction.java|1|1|100.00%|
|:large_blue_circle:|io/questdb/griffin/engine/groupby/vect/VectorAggregateEntry.java|2|2|100.00%|
|:large_blue_circle:|io/questdb/std/MemoryTag.java|1|1|100.00%|
|:large_blue_circle:|io/questdb/griffin/engine/groupby/vect/SumTimestampVectorAggregateFunction.java|1|1|100.00%|
|:large_blue_circle:|io/questdb/griffin/engine/groupby/vect/MinLongVectorAggregateFunction.java|1|1|100.00%|
|:large_blue_circle:|io/questdb/griffin/engine/groupby/vect/KSumDoubleVectorAggregateFunction.java|1|1|100.00%|
|:large_blue_circle:|io/questdb/griffin/engine/groupby/vect/SumDateVectorAggregateFunction.java|1|1|100.00%|
|:large_blue_circle:|io/questdb/griffin/engine/groupby/vect/MaxTimestampVectorAggregateFunction.java|1|1|100.00%|
|:large_blue_circle:|io/questdb/griffin/engine/groupby/vect/MinDateVectorAggregateFunction.java|1|1|100.00%|

**Comment by eugenels** [comment]
>  in test - replace it with stub that returns nullptr (via JNI) .
It can be a problem to pass the address of a C function from the Java side.
On Linux we can use a trick with LD_PRELOAD, but it's clearly not portable.

**Review by bluestreak01 — APPROVED** [review]

**Pull request merged**
