### PR TITLE
chore(http): customizable HTTP behaviour

### PR DESCRIPTION
**Pull request by jerrinot**
allows to hook in custom HTTP processors and HTTP header parsers

### CODE REVIEW

**Comment by ideoma** [comment]
#### [PR Coverage check]

:heart_eyes: **pass** : 20 / 29 (68.97%)




#### file detail

|   |path|covered line|new line|coverage|
|----|----|----|----|----|
|:large_blue_circle:|io/questdb/cutlass/http/HttpRequestProcessor.java|0|1|00.00%|
|:large_blue_circle:|io/questdb/cutlass/http/processors/TlsErrorProcessor.java|3|11|27.27%|
|:large_blue_circle:|io/questdb/cutlass/http/HttpHeaderParser.java|5|5|100.00%|
|:large_blue_circle:|io/questdb/cutlass/http/HttpConnectionContext.java|8|8|100.00%|
|:large_blue_circle:|io/questdb/cutlass/http/HttpServer.java|3|3|100.00%|
|:large_blue_circle:|io/questdb/cutlass/http/processors/StaticContentProcessor.java|1|1|100.00%|

**Review by puzpuzpuz — APPROVED** [review]

**Comment by ideoma** [comment]
#### [PR Coverage check]

:heart_eyes: **pass** : 25 / 28 (89.29%)




#### file detail

|   |path|covered line|new line|coverage|
|----|----|----|----|----|
|:large_blue_circle:|io/questdb/cutlass/http/HttpConnectionContext.java|5|8|62.50%|
|:large_blue_circle:|io/questdb/cutlass/http/HttpHeaderParser.java|1|1|100.00%|
|:large_blue_circle:|io/questdb/DefaultFactoryProvider.java|1|1|100.00%|
|:large_blue_circle:|io/questdb/cutlass/http/DefaultHttpHeaderParserFactory.java|3|3|100.00%|
|:large_blue_circle:|io/questdb/cutlass/http/HttpServer.java|3|3|100.00%|
|:large_blue_circle:|io/questdb/cutlass/http/processors/StaticContentProcessor.java|1|1|100.00%|
|:large_blue_circle:|io/questdb/FactoryProviderImpl.java|1|1|100.00%|
|:large_blue_circle:|io/questdb/ServerMain.java|6|6|100.00%|
|:large_blue_circle:|io/questdb/cutlass/Services.java|4|4|100.00%|

**Comment by ideoma** [comment]
#### [PR Coverage check]

:heart_eyes: **pass** : 25 / 28 (89.29%)




#### file detail

|   |path|covered line|new line|coverage|
|----|----|----|----|----|
|:large_blue_circle:|io/questdb/cutlass/http/HttpConnectionContext.java|5|8|62.50%|
|:large_blue_circle:|io/questdb/cutlass/http/HttpHeaderParser.java|1|1|100.00%|
|:large_blue_circle:|io/questdb/DefaultFactoryProvider.java|1|1|100.00%|
|:large_blue_circle:|io/questdb/cutlass/http/DefaultHttpHeaderParserFactory.java|3|3|100.00%|
|:large_blue_circle:|io/questdb/cutlass/http/HttpServer.java|3|3|100.00%|
|:large_blue_circle:|io/questdb/cutlass/http/processors/StaticContentProcessor.java|1|1|100.00%|
|:large_blue_circle:|io/questdb/FactoryProviderImpl.java|1|1|100.00%|
|:large_blue_circle:|io/questdb/ServerMain.java|6|6|100.00%|
|:large_blue_circle:|io/questdb/cutlass/Services.java|4|4|100.00%|

**Comment by jerrinot** [comment]
created https://github.com/questdb/questdb/issues/3952

**Pull request merged**
