### PR TITLE
fix(sql): support latest by over sub-query

### LINKED ISSUE #1553: Refactor `latest by` syntax
## The status quo

We had quite a few questions on how `latest by` works and it has always been a confusing subject for pretty much everybody. This includes ourselves where various implementations of `latest by` do not agree in results. We do [have a PR to fix this](https://github.com/questdb/questdb/pull/1478) but I thought we should also address the syntax.

The goal is to make `latest by` syntax intuitive and easy to understand. Consider this SQL:

```sql
pos latest by id where geo6 within(#wtq) and time < '2021-09-19T00:00:00.000000Z';
```

Here the "rule" dictates that `where` is executed before `latest by`. However it is not intuitive because of the actual order of clauses in the SQL. That's one problem.

Another problem is that, if we follow the execution "rule", the SQL will actually execute as follows:

```sql
(pos latest by id where time < '2021-09-19T00:00:00.000000Z') where geo6 within(#wtq);
```

so it is breaking the "rule" in effect making things even harder to comprehend.

## The proposal

There are proposals actually, one we discusses offline with @marregui 

```sql
(pos where x > 0 latest on ts partition by id end at '2021-09-19T00:00:00.000000Z') where geo6 within(#wtq);
```

The changes are:
- `where` is now syntactically preceding `latest` keyword
- `latest` keyword now has `on` to specify timestamp column explicitly
- `latest` has its own interval definition `start at` and `end at`. Here there are keywords `end` and `start` to open the interval bounds
- `by` is replaced with `partition by` to be more explicit what this column means
- `where` clauses that execute __after__ `latest by` should be outside of the sub-query

I also discussed this with @ideoma and he pointed out what interval could also be specified like so:

```sql
(pos where x > 0 and ts < '2021-09-19T00:00:00.000000Z' latest on ts partition by id) where geo6 within(#wtq);
```

in this case we do not need to program against a case where timestamp interval is in two places at the same time. I tend to side with @ideoma here.

## The ask

Please let us know if these syntax changes make `latest` keywork more intuitive, ask questions if you have any and propose changes and alternatives.

_Originally posted by @bluestreak01 in https://github.com/questdb/questdb/discussions/1545_

### PR DESCRIPTION
**Pull request by puzpuzpuz**
Closes #1553

Refs: https://github.com/questdb/rfc/discussions/23

Prior to this PR queries like the following were not supported:
```sql
(tab order by another_ts) timestamp(another_ts) latest by id
```

Users could work that around with `WITH` clause used to define the sub-query, but then latest by wasn't working as expected. The new `latest on partition by` syntax allowed such queries, but again the returned data set was incorrect.

This PR adds support for latest by over both ordered and unordered sub-queries.

For sub-queries that do not allow random access, a stable result set order is assumed since such queries need to be iterated two times.

### CODE REVIEW

**Comment by ideoma** [comment]
#### [PR Coverage check]

:heart_eyes: **pass** : 150 / 165 (90.91%)




#### file detail

|   |path|covered line|new line|coverage|
|----|----|----|----|----|
|:large_blue_circle:|io/questdb/griffin/model/QueryModel.java|6|11|54.55%|
|:large_blue_circle:|io/questdb/griffin/engine/table/LatestByLightRecordCursorFactory.java|52|56|92.86%|
|:large_blue_circle:|io/questdb/griffin/engine/table/LatestByRecordCursorFactory.java|54|58|93.10%|
|:large_blue_circle:|io/questdb/griffin/SqlCodeGenerator.java|32|34|94.12%|
|:large_blue_circle:|io/questdb/griffin/SqlOptimiser.java|6|6|100.00%|

**Comment by ideoma** [comment]
#### [PR Coverage check]

:heart_eyes: **pass** : 144 / 154 (93.51%)




#### file detail

|   |path|covered line|new line|coverage|
|----|----|----|----|----|
|:large_blue_circle:|io/questdb/griffin/engine/table/LatestByLightRecordCursorFactory.java|52|56|92.86%|
|:large_blue_circle:|io/questdb/griffin/engine/table/LatestByRecordCursorFactory.java|54|58|93.10%|
|:large_blue_circle:|io/questdb/griffin/SqlCodeGenerator.java|32|34|94.12%|
|:large_blue_circle:|io/questdb/griffin/SqlOptimiser.java|6|6|100.00%|

**Comment by ideoma** [comment]
#### [PR Coverage check]

:heart_eyes: **pass** : 144 / 154 (93.51%)




#### file detail

|   |path|covered line|new line|coverage|
|----|----|----|----|----|
|:large_blue_circle:|io/questdb/griffin/engine/table/LatestByLightRecordCursorFactory.java|52|56|92.86%|
|:large_blue_circle:|io/questdb/griffin/engine/table/LatestByRecordCursorFactory.java|54|58|93.10%|
|:large_blue_circle:|io/questdb/griffin/SqlCodeGenerator.java|32|34|94.12%|
|:large_blue_circle:|io/questdb/griffin/SqlOptimiser.java|6|6|100.00%|

**Comment by ideoma** [comment]
#### [PR Coverage check]

:heart_eyes: **pass** : 144 / 154 (93.51%)




#### file detail

|   |path|covered line|new line|coverage|
|----|----|----|----|----|
|:large_blue_circle:|io/questdb/griffin/engine/table/LatestByLightRecordCursorFactory.java|52|56|92.86%|
|:large_blue_circle:|io/questdb/griffin/engine/table/LatestByRecordCursorFactory.java|54|58|93.10%|
|:large_blue_circle:|io/questdb/griffin/SqlCodeGenerator.java|32|34|94.12%|
|:large_blue_circle:|io/questdb/griffin/SqlOptimiser.java|6|6|100.00%|

**Comment by ideoma** [comment]
#### [PR Coverage check]

:heart_eyes: **pass** : 145 / 155 (93.55%)




#### file detail

|   |path|covered line|new line|coverage|
|----|----|----|----|----|
|:large_blue_circle:|io/questdb/griffin/engine/table/LatestByLightRecordCursorFactory.java|52|56|92.86%|
|:large_blue_circle:|io/questdb/griffin/engine/table/LatestByRecordCursorFactory.java|55|59|93.22%|
|:large_blue_circle:|io/questdb/griffin/SqlCodeGenerator.java|32|34|94.12%|
|:large_blue_circle:|io/questdb/griffin/SqlOptimiser.java|6|6|100.00%|

**Comment by ideoma** [comment]
#### [PR Coverage check]

:heart_eyes: **pass** : 145 / 155 (93.55%)




#### file detail

|   |path|covered line|new line|coverage|
|----|----|----|----|----|
|:large_blue_circle:|io/questdb/griffin/engine/table/LatestByLightRecordCursorFactory.java|52|56|92.86%|
|:large_blue_circle:|io/questdb/griffin/engine/table/LatestByRecordCursorFactory.java|55|59|93.22%|
|:large_blue_circle:|io/questdb/griffin/SqlCodeGenerator.java|32|34|94.12%|
|:large_blue_circle:|io/questdb/griffin/SqlOptimiser.java|6|6|100.00%|

**Comment by ideoma** [comment]
#### [PR Coverage check]

:heart_eyes: **pass** : 145 / 155 (93.55%)




#### file detail

|   |path|covered line|new line|coverage|
|----|----|----|----|----|
|:large_blue_circle:|io/questdb/griffin/engine/table/LatestByLightRecordCursorFactory.java|52|56|92.86%|
|:large_blue_circle:|io/questdb/griffin/engine/table/LatestByRecordCursorFactory.java|55|59|93.22%|
|:large_blue_circle:|io/questdb/griffin/SqlCodeGenerator.java|32|34|94.12%|
|:large_blue_circle:|io/questdb/griffin/SqlOptimiser.java|6|6|100.00%|

**Comment by ideoma** [comment]
#### [PR Coverage check]

:heart_eyes: **pass** : 146 / 156 (93.59%)




#### file detail

|   |path|covered line|new line|coverage|
|----|----|----|----|----|
|:large_blue_circle:|io/questdb/griffin/engine/table/LatestByLightRecordCursorFactory.java|52|56|92.86%|
|:large_blue_circle:|io/questdb/griffin/engine/table/LatestByRecordCursorFactory.java|56|60|93.33%|
|:large_blue_circle:|io/questdb/griffin/SqlCodeGenerator.java|32|34|94.12%|
|:large_blue_circle:|io/questdb/griffin/SqlOptimiser.java|6|6|100.00%|

**Comment by ideoma** [comment]
#### [PR Coverage check]

:heart_eyes: **pass** : 146 / 156 (93.59%)




#### file detail

|   |path|covered line|new line|coverage|
|----|----|----|----|----|
|:large_blue_circle:|io/questdb/griffin/engine/table/LatestByLightRecordCursorFactory.java|52|56|92.86%|
|:large_blue_circle:|io/questdb/griffin/engine/table/LatestByRecordCursorFactory.java|56|60|93.33%|
|:large_blue_circle:|io/questdb/griffin/SqlCodeGenerator.java|32|34|94.12%|
|:large_blue_circle:|io/questdb/griffin/SqlOptimiser.java|6|6|100.00%|

**Review by bluestreak01 — CHANGES_REQUESTED** [review]
Could we have test coverage improved a bit:

image

**Comment by ideoma** [comment]
#### [PR Coverage check]

:heart_eyes: **pass** : 146 / 156 (93.59%)




#### file detail

|   |path|covered line|new line|coverage|
|----|----|----|----|----|
|:large_blue_circle:|io/questdb/griffin/engine/table/LatestByLightRecordCursorFactory.java|52|56|92.86%|
|:large_blue_circle:|io/questdb/griffin/engine/table/LatestByRecordCursorFactory.java|56|60|93.33%|
|:large_blue_circle:|io/questdb/griffin/SqlCodeGenerator.java|32|34|94.12%|
|:large_blue_circle:|io/questdb/griffin/SqlOptimiser.java|6|6|100.00%|

**Comment by ideoma** [comment]
#### [PR Coverage check]

:heart_eyes: **pass** : 146 / 156 (93.59%)




#### file detail

|   |path|covered line|new line|coverage|
|----|----|----|----|----|
|:large_blue_circle:|io/questdb/griffin/engine/table/LatestByLightRecordCursorFactory.java|52|56|92.86%|
|:large_blue_circle:|io/questdb/griffin/engine/table/LatestByRecordCursorFactory.java|56|60|93.33%|
|:large_blue_circle:|io/questdb/griffin/SqlCodeGenerator.java|32|34|94.12%|
|:large_blue_circle:|io/questdb/griffin/SqlOptimiser.java|6|6|100.00%|

**Comment by ideoma** [comment]
#### [PR Coverage check]

:heart_eyes: **pass** : 148 / 156 (94.87%)




#### file detail

|   |path|covered line|new line|coverage|
|----|----|----|----|----|
|:large_blue_circle:|io/questdb/griffin/engine/table/LatestByLightRecordCursorFactory.java|52|56|92.86%|
|:large_blue_circle:|io/questdb/griffin/engine/table/LatestByRecordCursorFactory.java|56|60|93.33%|
|:large_blue_circle:|io/questdb/griffin/SqlOptimiser.java|6|6|100.00%|
|:large_blue_circle:|io/questdb/griffin/SqlCodeGenerator.java|34|34|100.00%|

**Comment by ideoma** [comment]
#### [PR Coverage check]

:heart_eyes: **pass** : 148 / 156 (94.87%)




#### file detail

|   |path|covered line|new line|coverage|
|----|----|----|----|----|
|:large_blue_circle:|io/questdb/griffin/engine/table/LatestByLightRecordCursorFactory.java|52|56|92.86%|
|:large_blue_circle:|io/questdb/griffin/engine/table/LatestByRecordCursorFactory.java|56|60|93.33%|
|:large_blue_circle:|io/questdb/griffin/SqlOptimiser.java|6|6|100.00%|
|:large_blue_circle:|io/questdb/griffin/SqlCodeGenerator.java|34|34|100.00%|

**Review by bluestreak01 — APPROVED** [review]

**Comment by ideoma** [comment]
#### [PR Coverage check]

:heart_eyes: **pass** : 148 / 156 (94.87%)




#### file detail

|   |path|covered line|new line|coverage|
|----|----|----|----|----|
|:large_blue_circle:|io/questdb/griffin/engine/table/LatestByLightRecordCursorFactory.java|52|56|92.86%|
|:large_blue_circle:|io/questdb/griffin/engine/table/LatestByRecordCursorFactory.java|56|60|93.33%|
|:large_blue_circle:|io/questdb/griffin/SqlOptimiser.java|6|6|100.00%|
|:large_blue_circle:|io/questdb/griffin/SqlCodeGenerator.java|34|34|100.00%|

**Comment by ideoma** [comment]
#### [PR Coverage check]

:heart_eyes: **pass** : 148 / 156 (94.87%)




#### file detail

|   |path|covered line|new line|coverage|
|----|----|----|----|----|
|:large_blue_circle:|io/questdb/griffin/engine/table/LatestByLightRecordCursorFactory.java|52|56|92.86%|
|:large_blue_circle:|io/questdb/griffin/engine/table/LatestByRecordCursorFactory.java|56|60|93.33%|
|:large_blue_circle:|io/questdb/griffin/SqlOptimiser.java|6|6|100.00%|
|:large_blue_circle:|io/questdb/griffin/SqlCodeGenerator.java|34|34|100.00%|

**Comment by puzpuzpuz** [comment]
@bsmth might be a good idea to include a few latest by over sub-query examples in the docs. WDYT?

**Pull request merged**
