### PR TITLE
 fix(core): add sort to ShowTables (#353)

### PR DESCRIPTION
**Pull request by jttmtv**
**Fix issue #353**

Two important variables were introduced.

- Created a `CharSequence`  type array `sinks`  with the length of 10000 to store all of the table names.

  ```java
  private static final StringSink[] sinks;
  static {
  	sinks = IntStream.range(0, 100000).mapToObj(i -> new StringSink()).toArray(StringSink[]::new);
      }
  ```

- Created a `ObjList` which is a list to store `CharSequence` type variable. The reason why choose `ObjList` is to use the `sort` function from this data structure.

  ```java
  private final ObjList<CharSequence> sink_list = new ObjList<CharSequence>();
  ```

One important method was introduced.

- This method is to sort the table names with alphabetical order.

  ```java
  public void sortTable() {
      if (this.flag) {
          int i = 0;
          while (next()) {
              sinks[i].put(sink);
              sink_list.add(sinks[i]);
              ++i;
          }
          length = sink_list.size();
          sink_list.sort(CSC);
          this.flag = false;
      }
  }
  ```

The general procedure is as follow:

- When there is an external method calling the `hasNext()` method, we first go to the `sortTable()` method, there is a variable `flag` to mark the status whether we have finished the sorting procedure. If we have finished this procedure, there is no need to do again. Then we check the variable `length` which is the length of the list of table names originally. Each time the `hasNext` method was executed, we subtract one from `length`. Finally all we need to do is to fetch the table name from sorted table names' list one by one.

  ```java
  @Override
  public boolean hasNext() {
      sortTable();
      if (length == 0) {
          for (StringSink stringSink : sinks) {
              stringSink.clear();
          }
          sink_list.clear();
          this.flag = true;
          return false;
      }
      sink.clear();
      sink.put(sink_list.get(sink_list.size() - length));
      --length;
      return length >= 0;
  }
  ```

### CODE REVIEW

**Comment by jerrinot** [comment]
Hello @jttmtv,

thank you for jumping on this enhancement!

I see 2 issues in this PR:
1. Memory footprint: It eagerly allocates 100k instances of `StringSink`. Each instance of `StringSink` instantiates `StringBuilder`. This means 100k instances of `StringSink` will retain >1MB of memory. I don't think it's justifiable. Can you think of anything else? Would it be possible to allocate the memory lazily? `show tables` is not performance critical so you can be creative.  
2. The 100k instances of `StringSink` are static. This means 2 concurrent execution of `show tables` will likely interact with each other. That's undesirable. 

Can you think of a different solution?

**Comment by jttmtv** [comment]
I don't have a better solusion for now. Beacuse of the strict memory leak detection policy of questdb.

**Comment by bluestreak01** [comment]
I would suggest that `show tables` syntax should leverage already existing implementation of `order by`. E.g. wrap `TableListRecordCursorFactory` in a factory that implements `order by`

**Comment by jerrinot** [comment]
@bluestreak01 indeed, this does sound like _the right option_. but doesn't it imply creating `QueryModel` and all that jazz?

**Comment by bluestreak01** [comment]
> 

Not at all

**Comment by jerrinot** [comment]
I saw `SortedRecordCursorFactory`. It requires `RecordComparator` which is only generated dynamically inside `SqlCodeGenerator`. but I guess we could have a comparator for `show tables` which is statically sitting on a classpath.

**Comment by bluestreak01** [comment]
we can't merge this approach, sorry

**Pull request closed without merging**
