### PR TITLE
fix(sql): make sure that order by is not ignored by row_number() function

### LINKED ISSUE #2620: Window function row_number() result out of order
### Describe the bug

if use order by clause in select sql like this:
```
select row_number() over(partition by sensorId order by temp),temp,ts from 'readings' where sensorId = 5109 order by temp;
```
the result out of order
```
 row_number |        temp        |             ts             
------------+--------------------+----------------------------
        582 | 15.004434478999105 | 2019-11-25 21:29:54.200000
        497 |  15.02493720762422 | 2019-11-20 17:06:55.200000
```

### To reproduce

1. run this sql
```
select row_number() over(partition by sensorId order by temp),temp,ts from 'readings' where sensorId = 5109 order by temp;
```
2. return result 
```
row_number |        temp        |             ts             
------------+--------------------+----------------------------
        582 | 15.004434478999105 | 2019-11-25 21:29:54.200000
        497 |  15.02493720762422 | 2019-11-20 17:06:55.200000
         28 | 15.027997591584324 | 2019-10-19 07:09:02.300000
         90 | 15.046235126104243 | 2019-10-23 07:44:49.800000
        396 | 15.047976089120429 | 2019-11-14 07:48:38.600000
        573 | 15.052348178001584 | 2019-11-24 21:35:39.700000
         69 | 15.059114960868015 | 2019-10-21 22:11:40.600000
        700 | 15.080164510482806 | 2019-12-04 20:56:32.900000
        727 | 15.081847565313176 | 2019-12-07 06:20:40.500000
        776 | 15.096766057248669 | 2019-12-10 22:21:52.300000
        754 | 15.097841725312733 | 2019-12-08 22:01:43.700000
```

### Expected Behavior

return result
```
row_number |        temp        |             ts             
------------+--------------------+----------------------------
          0 | 15.004434478999105 | 2019-11-25 21:29:54.200000
          1 |  15.02493720762422 | 2019-11-20 17:06:55.200000
          2 | 15.027997591584324 | 2019-10-19 07:09:02.300000
          3 | 15.046235126104243 | 2019-10-23 07:44:49.800000
          4 | 15.047976089120429 | 2019-11-14 07:48:38.600000
          5 | 15.052348178001584 | 2019-11-24 21:35:39.700000
          6 | 15.059114960868015 | 2019-10-21 22:11:40.600000
          7 | 15.080164510482806 | 2019-12-04 20:56:32.900000
          8 | 15.081847565313176 | 2019-12-07 06:20:40.500000
          9 | 15.096766057248669 | 2019-12-10 22:21:52.300000
         10 | 15.097841725312733 | 2019-12-08 22:01:43.700000
         11 | 15.104586453742463 | 2019-12-19 13:33:19.700000
```

### Environment

```markdown
- **QuestDB version**: main
- **OS**: MacOS
- **Browser**: Chrome
```

### Additional context

_No response_

### LINKED ISSUE #2705: row_number() doesn't respect order by clause if partition by clause is missing and order is same as in base query
### Describe the bug

_No response_

### To reproduce

```sql
create table rntest as ( select x, x%10 from long_sequence(100));

select *, row_number() over (order by x desc ) as rn from rntest order by x desc  ;

 select *, row_number() over (order by column ) as rn from rntest order by column  ;

  x  | column | rn
-----+--------+-----
 100 |      0 | 100
  90 |      0 |  90
  80 |      0 |  80
  70 |      0 |  70
  60 |      0 |  60
  50 |      0 |  50
  40 |      0 |  40
  30 |      0 |  30
  20 |      0 |  20
  10 |      0 |  10


select *, row_number() over (order by column, x ) as rn from rntest order by column, x   ;

  x  | column | rn
-----+--------+-----
  10 |      0 |  10
  20 |      0 |  20
  30 |      0 |  30
  40 |      0 |  40
  50 |      0 |  50
  60 |      0 |  60
  70 |      0 |  70
  80 |      0 |  80
  90 |      0 |  90
 100 |      0 | 100
```

in PostgreSQL : 

```sql
create table rntest as ( select x, x%10 column from generate_series(1,100,1) as s(x));

select *, row_number() over (order by "column" ) as rn from rntest order by "column"  ;

 x  | column | rn
-----+--------+-----
  40 |      0 |   1
  20 |      0 |   2
  50 |      0 |   3
  80 |      0 |   4
  70 |      0 |   5
  30 |      0 |   6
  90 |      0 |   7
  60 |      0 |   8
 100 |      0 |   9
  10 |      0 |  10
  71 |      1 |  11

select *, row_number() over (order by "column", x ) as rn from rntest order by "column", x   ;
  x  | column | rn
-----+--------+----
  10 |      0 |  1
  20 |      0 |  2
  30 |      0 |  3
  40 |      0 |  4
  50 |      0 |  5
  60 |      0 |  6
  70 |      0 |  7
  80 |      0 |  8
  90 |      0 |  9
 100 |      0 | 10
   1 |      1 | 11
```

### Expected Behavior

_No response_

### Environment

```markdown
- **QuestDB version**:6.5.5-SNAPSHOT/master
- **OS**:
- **Browser**:
```

### Additional context

_No response_

### PR DESCRIPTION
**Pull request by puzpuzpuz**
Closes #2620
Closes #2705

Also fixes an invalid assertion in `ReaderPoolTest#testConcurrentRead()`.

### CODE REVIEW

**Comment by ideoma** [comment]
#### [PR Coverage check]

:heart_eyes: **pass** : 5 / 5 (100.00%)




#### file detail

|   |path|covered line|new line|coverage|
|----|----|----|----|----|
|:large_blue_circle:|io/questdb/griffin/engine/table/FilterOnValuesRecordCursorFactory.java|1|1|100.00%|
|:large_blue_circle:|io/questdb/griffin/engine/functions/analytic/RowNumberFunctionFactory.java|1|1|100.00%|
|:large_blue_circle:|io/questdb/griffin/engine/analytic/CachedAnalyticRecordCursorFactory.java|1|1|100.00%|
|:large_blue_circle:|io/questdb/griffin/SqlCodeGenerator.java|2|2|100.00%|

**Comment by puzpuzpuz** [comment]
The failed mac-other run is due to Maven repos being unreachable to the CI worker.

**Review by jerrinot — APPROVED** [review]
the code change looks good. 
the PR title is alright too.

**Comment by puzpuzpuz** [comment]
@jerrinot thanks for the review!

**Pull request merged**
