### PR TITLE
feat: index rebuild, string col index recover utils

### PR DESCRIPTION
**Pull request by ideoma**
- build single jar with dependencies of utils project
- fix logging of `io.questdb.cliutil.RebuildIndex`
- new `io.questdb.cliutil.RecoverVarIndex`

see more in utils\README.md

### CODE REVIEW

**Comment by ideoma** [comment]
#### [PR Coverage check]

:heart_eyes: **pass** : 183 / 286 (63.99%)




#### file detail

|   |path|covered line|new line|coverage|
|----|----|----|----|----|
|:large_blue_circle:|io/questdb/log/SyncLogger.java|0|93|00.00%|
|:large_blue_circle:|io/questdb/log/LogFactory.java|14|17|82.35%|
|:large_blue_circle:|io/questdb/cairo/RecoverVarIndex.java|42|46|91.30%|
|:large_blue_circle:|io/questdb/cairo/RebuildIndex.java|35|36|97.22%|
|:large_blue_circle:|io/questdb/cairo/RebuildColumnBase.java|92|94|97.87%|

**Comment by ideoma** [comment]
#### [PR Coverage check]

:heart_eyes: **pass** : 222 / 288 (77.08%)




#### file detail

|   |path|covered line|new line|coverage|
|----|----|----|----|----|
|:large_blue_circle:|io/questdb/log/SyncLogger.java|34|93|36.56%|
|:large_blue_circle:|io/questdb/cairo/RecoverVarIndex.java|42|46|91.30%|
|:large_blue_circle:|io/questdb/cairo/RebuildIndex.java|35|36|97.22%|
|:large_blue_circle:|io/questdb/cairo/RebuildColumnBase.java|92|94|97.87%|
|:large_blue_circle:|io/questdb/log/LogFactory.java|19|19|100.00%|

**Comment by ideoma** [comment]
#### [PR Coverage check]

:heart_eyes: **pass** : 222 / 288 (77.08%)




#### file detail

|   |path|covered line|new line|coverage|
|----|----|----|----|----|
|:large_blue_circle:|io/questdb/log/SyncLogger.java|34|93|36.56%|
|:large_blue_circle:|io/questdb/cairo/RecoverVarIndex.java|42|46|91.30%|
|:large_blue_circle:|io/questdb/cairo/RebuildIndex.java|35|36|97.22%|
|:large_blue_circle:|io/questdb/cairo/RebuildColumnBase.java|92|94|97.87%|
|:large_blue_circle:|io/questdb/log/LogFactory.java|19|19|100.00%|

**Comment by ideoma** [comment]
#### [PR Coverage check]

:heart_eyes: **pass** : 222 / 288 (77.08%)




#### file detail

|   |path|covered line|new line|coverage|
|----|----|----|----|----|
|:large_blue_circle:|io/questdb/log/SyncLogger.java|34|93|36.56%|
|:large_blue_circle:|io/questdb/cairo/RecoverVarIndex.java|42|46|91.30%|
|:large_blue_circle:|io/questdb/cairo/RebuildIndex.java|35|36|97.22%|
|:large_blue_circle:|io/questdb/cairo/RebuildColumnBase.java|92|94|97.87%|
|:large_blue_circle:|io/questdb/log/LogFactory.java|19|19|100.00%|

**Review by bluestreak01 — APPROVED** [review]

**Pull request merged**
