### PR TITLE
fix(core): fixed numerous flapping tests

### PR DESCRIPTION
**Pull request by bluestreak01**
another attempt to fix test, same as https://github.com/questdb/questdb/pull/1670

The rationale for this PR was that all of our existing PRs were failing for reasons unrelated to the PR. We have a lot of flapping tests.

Following the async alter table PR the writer maintenance job was introduced in the TcpILP tests:

- testWriterRelease* tests were intermittently disrupted by maintenance job expiring writers (10s idle timeout)
- removal of maintenance job from thread pool upset some of the `alter table` tests
- both tests use the same test code, so I made using writer maintenance job optional per test
- tests were failing with message "cannot lock table, reason `unlocking`". This made no sense. I refactored use of lock reason
- refactoring lock reason perhaps saved us some yet unreported grief: we do not lock and update reason atomically, yet lock reason is used as the indicator if table is locked or not. So it was entirely possible to get "table unlocked" from the `lock()` call while table was actually locked. Code acting on "unlocked" table was prone to failure
- fixed flapping test `WriterPoolTest.testGetAndCloseRace()` https://github.com/questdb/questdb/pull/1671/commits/bb65a22a9d6e788049ae60e30def7212e601ebf3

### CODE REVIEW

**Comment by ideoma** [comment]
#### [PR Coverage check]

:heart_eyes: **pass** : 20 / 20 (100.00%)




#### file detail

|   |path|covered line|new line|coverage|
|----|----|----|----|----|
|:large_blue_circle:|io/questdb/cutlass/line/udp/LineUdpParserImpl.java|8|8|100.00%|
|:large_blue_circle:|io/questdb/cairo/pool/WriterPool.java|12|12|100.00%|

**Comment by ideoma** [comment]
#### [PR Coverage check]

:heart_eyes: **pass** : 20 / 20 (100.00%)




#### file detail

|   |path|covered line|new line|coverage|
|----|----|----|----|----|
|:large_blue_circle:|io/questdb/cutlass/line/udp/LineUdpParserImpl.java|8|8|100.00%|
|:large_blue_circle:|io/questdb/cairo/pool/WriterPool.java|12|12|100.00%|

**Comment by ideoma** [comment]
#### [PR Coverage check]

:heart_eyes: **pass** : 20 / 20 (100.00%)




#### file detail

|   |path|covered line|new line|coverage|
|----|----|----|----|----|
|:large_blue_circle:|io/questdb/cutlass/line/udp/LineUdpParserImpl.java|8|8|100.00%|
|:large_blue_circle:|io/questdb/cairo/pool/WriterPool.java|12|12|100.00%|

**Comment by ideoma** [comment]
#### [PR Coverage check]

:heart_eyes: **pass** : 20 / 20 (100.00%)




#### file detail

|   |path|covered line|new line|coverage|
|----|----|----|----|----|
|:large_blue_circle:|io/questdb/cutlass/line/udp/LineUdpParserImpl.java|8|8|100.00%|
|:large_blue_circle:|io/questdb/cairo/pool/WriterPool.java|12|12|100.00%|

**Comment by ideoma** [comment]
#### [PR Coverage check]

:heart_eyes: **pass** : 25 / 26 (96.15%)




#### file detail

|   |path|covered line|new line|coverage|
|----|----|----|----|----|
|:large_blue_circle:|io/questdb/cairo/pool/WriterPool.java|17|18|94.44%|
|:large_blue_circle:|io/questdb/cutlass/line/udp/LineUdpParserImpl.java|8|8|100.00%|

**Comment by ideoma** [comment]
#### [PR Coverage check]

:heart_eyes: **pass** : 25 / 26 (96.15%)




#### file detail

|   |path|covered line|new line|coverage|
|----|----|----|----|----|
|:large_blue_circle:|io/questdb/cairo/pool/WriterPool.java|17|18|94.44%|
|:large_blue_circle:|io/questdb/cutlass/line/udp/LineUdpParserImpl.java|8|8|100.00%|

**Comment by ideoma** [comment]
#### [PR Coverage check]

:heart_eyes: **pass** : 25 / 26 (96.15%)




#### file detail

|   |path|covered line|new line|coverage|
|----|----|----|----|----|
|:large_blue_circle:|io/questdb/cairo/pool/WriterPool.java|17|18|94.44%|
|:large_blue_circle:|io/questdb/cutlass/line/udp/LineUdpParserImpl.java|8|8|100.00%|

**Comment by ideoma** [comment]
#### [PR Coverage check]

:heart_eyes: **pass** : 27 / 31 (87.10%)




#### file detail

|   |path|covered line|new line|coverage|
|----|----|----|----|----|
|:large_blue_circle:|io/questdb/cairo/pool/WriterPool.java|19|23|82.61%|
|:large_blue_circle:|io/questdb/cutlass/line/udp/LineUdpParserImpl.java|8|8|100.00%|

**Comment by ideoma** [comment]
#### [PR Coverage check]

:heart_eyes: **pass** : 27 / 31 (87.10%)




#### file detail

|   |path|covered line|new line|coverage|
|----|----|----|----|----|
|:large_blue_circle:|io/questdb/cairo/pool/WriterPool.java|19|23|82.61%|
|:large_blue_circle:|io/questdb/cutlass/line/udp/LineUdpParserImpl.java|8|8|100.00%|

**Comment by ideoma** [comment]
#### [PR Coverage check]

:heart_eyes: **pass** : 27 / 28 (96.43%)




#### file detail

|   |path|covered line|new line|coverage|
|----|----|----|----|----|
|:large_blue_circle:|io/questdb/cairo/pool/WriterPool.java|19|20|95.00%|
|:large_blue_circle:|io/questdb/cutlass/line/udp/LineUdpParserImpl.java|8|8|100.00%|

**Comment by ideoma** [comment]
#### [PR Coverage check]

:heart_eyes: **pass** : 27 / 28 (96.43%)




#### file detail

|   |path|covered line|new line|coverage|
|----|----|----|----|----|
|:large_blue_circle:|io/questdb/cairo/pool/WriterPool.java|19|20|95.00%|
|:large_blue_circle:|io/questdb/cutlass/line/udp/LineUdpParserImpl.java|8|8|100.00%|

**Review by eugenels — APPROVED** [review]

**Pull request merged**
