### PR TITLE
perf(sql): speed up GROUP BY and JOIN in case of very small fixed-size keys

### PR DESCRIPTION
**Pull request by puzpuzpuz**
Adds `Unordered4Map` hash table (up to 4 byte keys) and lookup table-based `Unordered2Map`. The default prop values around map sharding and unordered map creation are tweaked for more efficient map usage.

Also swaps `MapFactory#createOrderedMap()` with `createUnorderedMap()` in all JOIN factories to speed up joins.

A few microbenchmark results:

```
Benchmark                                (size)  Mode  Cnt   Score    Error  Units
MapReadShortBenchmark.testUnordered2Map    3000  avgt    3  10.253 ±  3.018  ns/op
MapReadShortBenchmark.testUnordered2Map   30000  avgt    3  11.339 ±  0.073  ns/op
MapReadShortBenchmark.testUnordered4Map    3000  avgt    3  22.438 ±  3.867  ns/op
MapReadShortBenchmark.testUnordered4Map   30000  avgt    3  24.013 ± 13.154  ns/op
```

```
Benchmark                                 (size)  Mode  Cnt    Score    Error  Units
MapReadLongBenchmark.testHashMap            5000  avgt    3    8.183 ±  1.592  ns/op
MapReadLongBenchmark.testHashMap           50000  avgt    3   13.225 ±  2.606  ns/op
MapReadLongBenchmark.testHashMap          500000  avgt    3   63.719 ± 13.147  ns/op
MapReadLongBenchmark.testHashMap         5000000  avgt    3   87.739 ± 18.957  ns/op
MapReadLongBenchmark.testOrderedMap         5000  avgt    3   20.282 ±  2.421  ns/op
MapReadLongBenchmark.testOrderedMap        50000  avgt    3   19.420 ±  6.028  ns/op
MapReadLongBenchmark.testOrderedMap       500000  avgt    3   73.109 ± 46.018  ns/op
MapReadLongBenchmark.testOrderedMap      5000000  avgt    3  153.665 ±  9.000  ns/op
MapReadLongBenchmark.testUnordered8Map      5000  avgt    3   14.404 ±  0.713  ns/op
MapReadLongBenchmark.testUnordered8Map     50000  avgt    3   13.163 ±  7.181  ns/op
MapReadLongBenchmark.testUnordered8Map    500000  avgt    3   29.731 ±  2.903  ns/op
MapReadLongBenchmark.testUnordered8Map   5000000  avgt    3   51.347 ±  2.259  ns/op
MapReadLongBenchmark.testUnordered16Map     5000  avgt    3   13.372 ±  0.644  ns/op
MapReadLongBenchmark.testUnordered16Map    50000  avgt    3   12.469 ±  2.764  ns/op
MapReadLongBenchmark.testUnordered16Map   500000  avgt    3   39.769 ±  8.894  ns/op
MapReadLongBenchmark.testUnordered16Map  5000000  avgt    3   56.153 ±  6.272  ns/op
```

### CODE REVIEW

**Comment by ideoma** [comment]
#### [PR Coverage check]

:heart_eyes: **pass** : 486 / 559 (86.94%)




#### file detail

|   |path|covered line|new line|coverage|
|----|----|----|----|----|
|:large_blue_circle:|io/questdb/cairo/map/Unordered2MapValue.java|2|3|66.67%|
|:large_blue_circle:|io/questdb/cairo/map/Unordered4MapValue.java|89|112|79.46%|
|:large_blue_circle:|io/questdb/cairo/map/Unordered4MapRecord.java|101|118|85.59%|
|:large_blue_circle:|io/questdb/cairo/map/Unordered2Map.java|149|171|87.13%|
|:large_blue_circle:|io/questdb/cairo/map/Unordered2MapCursor.java|34|38|89.47%|
|:large_blue_circle:|io/questdb/cairo/map/Unordered8Map.java|10|11|90.91%|
|:large_blue_circle:|io/questdb/cairo/map/Unordered4Map.java|65|70|92.86%|
|:large_blue_circle:|io/questdb/griffin/engine/join/AsOfJoinRecordCursorFactory.java|1|1|100.00%|
|:large_blue_circle:|io/questdb/griffin/engine/join/HashOuterJoinFilteredRecordCursorFactory.java|1|1|100.00%|
|:large_blue_circle:|io/questdb/PropServerConfiguration.java|2|2|100.00%|
|:large_blue_circle:|io/questdb/std/Hash.java|2|2|100.00%|
|:large_blue_circle:|io/questdb/std/bytes/Bytes.java|2|2|100.00%|
|:large_blue_circle:|io/questdb/cairo/map/Unordered8MapRecord.java|1|1|100.00%|
|:large_blue_circle:|io/questdb/griffin/engine/join/HashOuterJoinLightRecordCursorFactory.java|1|1|100.00%|
|:large_blue_circle:|io/questdb/cairo/DefaultCairoConfiguration.java|1|1|100.00%|
|:large_blue_circle:|io/questdb/griffin/engine/join/LtJoinRecordCursorFactory.java|1|1|100.00%|
|:large_blue_circle:|io/questdb/griffin/engine/join/SpliceJoinLightRecordCursorFactory.java|1|1|100.00%|
|:large_blue_circle:|io/questdb/griffin/engine/join/HashJoinRecordCursorFactory.java|1|1|100.00%|
|:large_blue_circle:|io/questdb/cairo/map/Unordered4MapCursor.java|2|2|100.00%|
|:large_blue_circle:|io/questdb/cairo/map/Unordered2MapRecord.java|9|9|100.00%|
|:large_blue_circle:|io/questdb/griffin/engine/join/HashOuterJoinFilteredLightRecordCursorFactory.java|1|1|100.00%|
|:large_blue_circle:|io/questdb/griffin/engine/join/HashOuterJoinRecordCursorFactory.java|1|1|100.00%|
|:large_blue_circle:|io/questdb/griffin/engine/join/HashJoinLightRecordCursorFactory.java|1|1|100.00%|
|:large_blue_circle:|io/questdb/cairo/map/MapFactory.java|6|6|100.00%|
|:large_blue_circle:|io/questdb/griffin/engine/join/LtJoinLightRecordCursorFactory.java|1|1|100.00%|
|:large_blue_circle:|io/questdb/griffin/engine/join/AsOfJoinLightRecordCursorFactory.java|1|1|100.00%|

**Comment by ideoma** [comment]
#### [PR Coverage check]

:heart_eyes: **pass** : 486 / 559 (86.94%)




#### file detail

|   |path|covered line|new line|coverage|
|----|----|----|----|----|
|:large_blue_circle:|io/questdb/cairo/map/Unordered2MapValue.java|2|3|66.67%|
|:large_blue_circle:|io/questdb/cairo/map/Unordered4MapValue.java|89|112|79.46%|
|:large_blue_circle:|io/questdb/cairo/map/Unordered4MapRecord.java|101|118|85.59%|
|:large_blue_circle:|io/questdb/cairo/map/Unordered2Map.java|149|171|87.13%|
|:large_blue_circle:|io/questdb/cairo/map/Unordered2MapCursor.java|34|38|89.47%|
|:large_blue_circle:|io/questdb/cairo/map/Unordered8Map.java|10|11|90.91%|
|:large_blue_circle:|io/questdb/cairo/map/Unordered4Map.java|65|70|92.86%|
|:large_blue_circle:|io/questdb/griffin/engine/join/AsOfJoinRecordCursorFactory.java|1|1|100.00%|
|:large_blue_circle:|io/questdb/griffin/engine/join/HashOuterJoinFilteredRecordCursorFactory.java|1|1|100.00%|
|:large_blue_circle:|io/questdb/PropServerConfiguration.java|2|2|100.00%|
|:large_blue_circle:|io/questdb/std/Hash.java|2|2|100.00%|
|:large_blue_circle:|io/questdb/std/bytes/Bytes.java|2|2|100.00%|
|:large_blue_circle:|io/questdb/cairo/map/Unordered8MapRecord.java|1|1|100.00%|
|:large_blue_circle:|io/questdb/griffin/engine/join/HashOuterJoinLightRecordCursorFactory.java|1|1|100.00%|
|:large_blue_circle:|io/questdb/cairo/DefaultCairoConfiguration.java|1|1|100.00%|
|:large_blue_circle:|io/questdb/griffin/engine/join/LtJoinRecordCursorFactory.java|1|1|100.00%|
|:large_blue_circle:|io/questdb/griffin/engine/join/SpliceJoinLightRecordCursorFactory.java|1|1|100.00%|
|:large_blue_circle:|io/questdb/griffin/engine/join/HashJoinRecordCursorFactory.java|1|1|100.00%|
|:large_blue_circle:|io/questdb/cairo/map/Unordered4MapCursor.java|2|2|100.00%|
|:large_blue_circle:|io/questdb/cairo/map/Unordered2MapRecord.java|9|9|100.00%|
|:large_blue_circle:|io/questdb/griffin/engine/join/HashOuterJoinFilteredLightRecordCursorFactory.java|1|1|100.00%|
|:large_blue_circle:|io/questdb/griffin/engine/join/HashOuterJoinRecordCursorFactory.java|1|1|100.00%|
|:large_blue_circle:|io/questdb/griffin/engine/join/HashJoinLightRecordCursorFactory.java|1|1|100.00%|
|:large_blue_circle:|io/questdb/cairo/map/MapFactory.java|6|6|100.00%|
|:large_blue_circle:|io/questdb/griffin/engine/join/LtJoinLightRecordCursorFactory.java|1|1|100.00%|
|:large_blue_circle:|io/questdb/griffin/engine/join/AsOfJoinLightRecordCursorFactory.java|1|1|100.00%|

**Comment by puzpuzpuz** [comment]
@bluestreak01 I've updated this one based on #4138 changes, so it should be ready for review.

**Comment by ideoma** [comment]
#### [PR Coverage check]

:heart_eyes: **pass** : 498 / 574 (86.76%)




#### file detail

|   |path|covered line|new line|coverage|
|----|----|----|----|----|
|:large_blue_circle:|io/questdb/cairo/map/Unordered2MapValue.java|2|3|66.67%|
|:large_blue_circle:|io/questdb/cairo/map/Unordered4MapValue.java|102|125|81.60%|
|:large_blue_circle:|io/questdb/cairo/map/Unordered2Map.java|149|174|85.63%|
|:large_blue_circle:|io/questdb/cairo/map/Unordered4MapRecord.java|101|118|85.59%|
|:large_blue_circle:|io/questdb/cairo/map/Unordered2MapCursor.java|34|38|89.47%|
|:large_blue_circle:|io/questdb/cairo/map/Unordered8Map.java|10|11|90.91%|
|:large_blue_circle:|io/questdb/cairo/map/Unordered4Map.java|65|70|92.86%|
|:large_blue_circle:|io/questdb/griffin/engine/join/AsOfJoinRecordCursorFactory.java|1|1|100.00%|
|:large_blue_circle:|io/questdb/griffin/engine/join/HashOuterJoinFilteredRecordCursorFactory.java|1|1|100.00%|
|:large_blue_circle:|io/questdb/PropServerConfiguration.java|1|1|100.00%|
|:large_blue_circle:|io/questdb/std/Hash.java|2|2|100.00%|
|:large_blue_circle:|io/questdb/std/bytes/Bytes.java|2|2|100.00%|
|:large_blue_circle:|io/questdb/cairo/map/Unordered8MapRecord.java|1|1|100.00%|
|:large_blue_circle:|io/questdb/griffin/engine/join/HashOuterJoinLightRecordCursorFactory.java|1|1|100.00%|
|:large_blue_circle:|io/questdb/cairo/DefaultCairoConfiguration.java|1|1|100.00%|
|:large_blue_circle:|io/questdb/griffin/engine/join/LtJoinRecordCursorFactory.java|1|1|100.00%|
|:large_blue_circle:|io/questdb/griffin/engine/join/SpliceJoinLightRecordCursorFactory.java|1|1|100.00%|
|:large_blue_circle:|io/questdb/griffin/engine/join/HashJoinRecordCursorFactory.java|1|1|100.00%|
|:large_blue_circle:|io/questdb/cairo/map/Unordered4MapCursor.java|2|2|100.00%|
|:large_blue_circle:|io/questdb/cairo/map/Unordered2MapRecord.java|9|9|100.00%|
|:large_blue_circle:|io/questdb/griffin/engine/join/HashOuterJoinFilteredLightRecordCursorFactory.java|1|1|100.00%|
|:large_blue_circle:|io/questdb/griffin/engine/join/HashOuterJoinRecordCursorFactory.java|1|1|100.00%|
|:large_blue_circle:|io/questdb/griffin/engine/join/HashJoinLightRecordCursorFactory.java|1|1|100.00%|
|:large_blue_circle:|io/questdb/cairo/map/MapFactory.java|6|6|100.00%|
|:large_blue_circle:|io/questdb/griffin/engine/join/LtJoinLightRecordCursorFactory.java|1|1|100.00%|
|:large_blue_circle:|io/questdb/griffin/engine/join/AsOfJoinLightRecordCursorFactory.java|1|1|100.00%|

**Comment by ideoma** [comment]
#### [PR Coverage check]

:heart_eyes: **pass** : 498 / 574 (86.76%)




#### file detail

|   |path|covered line|new line|coverage|
|----|----|----|----|----|
|:large_blue_circle:|io/questdb/cairo/map/Unordered2MapValue.java|2|3|66.67%|
|:large_blue_circle:|io/questdb/cairo/map/Unordered4MapValue.java|102|125|81.60%|
|:large_blue_circle:|io/questdb/cairo/map/Unordered2Map.java|149|174|85.63%|
|:large_blue_circle:|io/questdb/cairo/map/Unordered4MapRecord.java|101|118|85.59%|
|:large_blue_circle:|io/questdb/cairo/map/Unordered2MapCursor.java|34|38|89.47%|
|:large_blue_circle:|io/questdb/cairo/map/Unordered8Map.java|10|11|90.91%|
|:large_blue_circle:|io/questdb/cairo/map/Unordered4Map.java|65|70|92.86%|
|:large_blue_circle:|io/questdb/griffin/engine/join/AsOfJoinRecordCursorFactory.java|1|1|100.00%|
|:large_blue_circle:|io/questdb/griffin/engine/join/HashOuterJoinFilteredRecordCursorFactory.java|1|1|100.00%|
|:large_blue_circle:|io/questdb/PropServerConfiguration.java|1|1|100.00%|
|:large_blue_circle:|io/questdb/std/Hash.java|2|2|100.00%|
|:large_blue_circle:|io/questdb/std/bytes/Bytes.java|2|2|100.00%|
|:large_blue_circle:|io/questdb/cairo/map/Unordered8MapRecord.java|1|1|100.00%|
|:large_blue_circle:|io/questdb/griffin/engine/join/HashOuterJoinLightRecordCursorFactory.java|1|1|100.00%|
|:large_blue_circle:|io/questdb/cairo/DefaultCairoConfiguration.java|1|1|100.00%|
|:large_blue_circle:|io/questdb/griffin/engine/join/LtJoinRecordCursorFactory.java|1|1|100.00%|
|:large_blue_circle:|io/questdb/griffin/engine/join/SpliceJoinLightRecordCursorFactory.java|1|1|100.00%|
|:large_blue_circle:|io/questdb/griffin/engine/join/HashJoinRecordCursorFactory.java|1|1|100.00%|
|:large_blue_circle:|io/questdb/cairo/map/Unordered4MapCursor.java|2|2|100.00%|
|:large_blue_circle:|io/questdb/cairo/map/Unordered2MapRecord.java|9|9|100.00%|
|:large_blue_circle:|io/questdb/griffin/engine/join/HashOuterJoinFilteredLightRecordCursorFactory.java|1|1|100.00%|
|:large_blue_circle:|io/questdb/griffin/engine/join/HashOuterJoinRecordCursorFactory.java|1|1|100.00%|
|:large_blue_circle:|io/questdb/griffin/engine/join/HashJoinLightRecordCursorFactory.java|1|1|100.00%|
|:large_blue_circle:|io/questdb/cairo/map/MapFactory.java|6|6|100.00%|
|:large_blue_circle:|io/questdb/griffin/engine/join/LtJoinLightRecordCursorFactory.java|1|1|100.00%|
|:large_blue_circle:|io/questdb/griffin/engine/join/AsOfJoinLightRecordCursorFactory.java|1|1|100.00%|

**Comment by ideoma** [comment]
#### [PR Coverage check]

:heart_eyes: **pass** : 498 / 574 (86.76%)




#### file detail

|   |path|covered line|new line|coverage|
|----|----|----|----|----|
|:large_blue_circle:|io/questdb/cairo/map/Unordered2MapValue.java|2|3|66.67%|
|:large_blue_circle:|io/questdb/cairo/map/Unordered4MapValue.java|102|125|81.60%|
|:large_blue_circle:|io/questdb/cairo/map/Unordered2Map.java|149|174|85.63%|
|:large_blue_circle:|io/questdb/cairo/map/Unordered4MapRecord.java|101|118|85.59%|
|:large_blue_circle:|io/questdb/cairo/map/Unordered2MapCursor.java|34|38|89.47%|
|:large_blue_circle:|io/questdb/cairo/map/Unordered8Map.java|10|11|90.91%|
|:large_blue_circle:|io/questdb/cairo/map/Unordered4Map.java|65|70|92.86%|
|:large_blue_circle:|io/questdb/griffin/engine/join/AsOfJoinRecordCursorFactory.java|1|1|100.00%|
|:large_blue_circle:|io/questdb/griffin/engine/join/HashOuterJoinFilteredRecordCursorFactory.java|1|1|100.00%|
|:large_blue_circle:|io/questdb/PropServerConfiguration.java|1|1|100.00%|
|:large_blue_circle:|io/questdb/std/Hash.java|2|2|100.00%|
|:large_blue_circle:|io/questdb/std/bytes/Bytes.java|2|2|100.00%|
|:large_blue_circle:|io/questdb/cairo/map/Unordered8MapRecord.java|1|1|100.00%|
|:large_blue_circle:|io/questdb/griffin/engine/join/HashOuterJoinLightRecordCursorFactory.java|1|1|100.00%|
|:large_blue_circle:|io/questdb/cairo/DefaultCairoConfiguration.java|1|1|100.00%|
|:large_blue_circle:|io/questdb/griffin/engine/join/LtJoinRecordCursorFactory.java|1|1|100.00%|
|:large_blue_circle:|io/questdb/griffin/engine/join/SpliceJoinLightRecordCursorFactory.java|1|1|100.00%|
|:large_blue_circle:|io/questdb/griffin/engine/join/HashJoinRecordCursorFactory.java|1|1|100.00%|
|:large_blue_circle:|io/questdb/cairo/map/Unordered4MapCursor.java|2|2|100.00%|
|:large_blue_circle:|io/questdb/cairo/map/Unordered2MapRecord.java|9|9|100.00%|
|:large_blue_circle:|io/questdb/griffin/engine/join/HashOuterJoinFilteredLightRecordCursorFactory.java|1|1|100.00%|
|:large_blue_circle:|io/questdb/griffin/engine/join/HashOuterJoinRecordCursorFactory.java|1|1|100.00%|
|:large_blue_circle:|io/questdb/griffin/engine/join/HashJoinLightRecordCursorFactory.java|1|1|100.00%|
|:large_blue_circle:|io/questdb/cairo/map/MapFactory.java|6|6|100.00%|
|:large_blue_circle:|io/questdb/griffin/engine/join/LtJoinLightRecordCursorFactory.java|1|1|100.00%|
|:large_blue_circle:|io/questdb/griffin/engine/join/AsOfJoinLightRecordCursorFactory.java|1|1|100.00%|

**Comment by ideoma** [comment]
#### [PR Coverage check]

:heart_eyes: **pass** : 925 / 1075 (86.05%)




#### file detail

|   |path|covered line|new line|coverage|
|----|----|----|----|----|
|:large_blue_circle:|io/questdb/cairo/map/Unordered2MapValue.java|94|125|75.20%|
|:large_blue_circle:|io/questdb/cairo/map/Unordered2MapRecord.java|95|118|80.51%|
|:large_blue_circle:|io/questdb/cairo/map/Unordered4MapValue.java|102|125|81.60%|
|:large_blue_circle:|io/questdb/cairo/map/Unordered2Map.java|149|174|85.63%|
|:large_blue_circle:|io/questdb/cairo/map/Unordered4MapRecord.java|101|118|85.59%|
|:large_blue_circle:|io/questdb/cairo/map/Unordered2MapCursor.java|34|38|89.47%|
|:large_blue_circle:|io/questdb/cairo/map/Unordered8Map.java|10|11|90.91%|
|:large_blue_circle:|io/questdb/cairo/map/Unordered16Map.java|10|11|90.91%|
|:large_blue_circle:|io/questdb/cairo/map/Unordered4Map.java|262|287|91.29%|
|:large_blue_circle:|io/questdb/griffin/engine/join/AsOfJoinRecordCursorFactory.java|1|1|100.00%|
|:large_blue_circle:|io/questdb/griffin/engine/join/HashOuterJoinFilteredRecordCursorFactory.java|1|1|100.00%|
|:large_blue_circle:|io/questdb/PropServerConfiguration.java|1|1|100.00%|
|:large_blue_circle:|io/questdb/std/Hash.java|2|2|100.00%|
|:large_blue_circle:|io/questdb/std/bytes/Bytes.java|2|2|100.00%|
|:large_blue_circle:|io/questdb/cairo/map/Unordered8MapRecord.java|1|1|100.00%|
|:large_blue_circle:|io/questdb/griffin/engine/join/HashOuterJoinLightRecordCursorFactory.java|1|1|100.00%|
|:large_blue_circle:|io/questdb/cairo/DefaultCairoConfiguration.java|1|1|100.00%|
|:large_blue_circle:|io/questdb/griffin/engine/join/LtJoinRecordCursorFactory.java|1|1|100.00%|
|:large_blue_circle:|io/questdb/griffin/engine/join/SpliceJoinLightRecordCursorFactory.java|1|1|100.00%|
|:large_blue_circle:|io/questdb/griffin/engine/join/HashJoinRecordCursorFactory.java|1|1|100.00%|
|:large_blue_circle:|io/questdb/cairo/map/Unordered16MapRecord.java|1|1|100.00%|
|:large_blue_circle:|io/questdb/cairo/map/Unordered4MapCursor.java|42|42|100.00%|
|:large_blue_circle:|io/questdb/griffin/engine/join/HashOuterJoinFilteredLightRecordCursorFactory.java|1|1|100.00%|
|:large_blue_circle:|io/questdb/griffin/engine/join/HashOuterJoinRecordCursorFactory.java|1|1|100.00%|
|:large_blue_circle:|io/questdb/griffin/engine/join/HashJoinLightRecordCursorFactory.java|1|1|100.00%|
|:large_blue_circle:|io/questdb/cairo/map/MapFactory.java|7|7|100.00%|
|:large_blue_circle:|io/questdb/griffin/engine/join/LtJoinLightRecordCursorFactory.java|1|1|100.00%|
|:large_blue_circle:|io/questdb/griffin/engine/join/AsOfJoinLightRecordCursorFactory.java|1|1|100.00%|

**Comment by ideoma** [comment]
#### [PR Coverage check]

:heart_eyes: **pass** : 925 / 1075 (86.05%)




#### file detail

|   |path|covered line|new line|coverage|
|----|----|----|----|----|
|:large_blue_circle:|io/questdb/cairo/map/Unordered2MapValue.java|94|125|75.20%|
|:large_blue_circle:|io/questdb/cairo/map/Unordered2MapRecord.java|95|118|80.51%|
|:large_blue_circle:|io/questdb/cairo/map/Unordered4MapValue.java|102|125|81.60%|
|:large_blue_circle:|io/questdb/cairo/map/Unordered2Map.java|149|174|85.63%|
|:large_blue_circle:|io/questdb/cairo/map/Unordered4MapRecord.java|101|118|85.59%|
|:large_blue_circle:|io/questdb/cairo/map/Unordered2MapCursor.java|34|38|89.47%|
|:large_blue_circle:|io/questdb/cairo/map/Unordered8Map.java|10|11|90.91%|
|:large_blue_circle:|io/questdb/cairo/map/Unordered16Map.java|10|11|90.91%|
|:large_blue_circle:|io/questdb/cairo/map/Unordered4Map.java|262|287|91.29%|
|:large_blue_circle:|io/questdb/griffin/engine/join/AsOfJoinRecordCursorFactory.java|1|1|100.00%|
|:large_blue_circle:|io/questdb/griffin/engine/join/HashOuterJoinFilteredRecordCursorFactory.java|1|1|100.00%|
|:large_blue_circle:|io/questdb/PropServerConfiguration.java|1|1|100.00%|
|:large_blue_circle:|io/questdb/std/Hash.java|2|2|100.00%|
|:large_blue_circle:|io/questdb/std/bytes/Bytes.java|2|2|100.00%|
|:large_blue_circle:|io/questdb/cairo/map/Unordered8MapRecord.java|1|1|100.00%|
|:large_blue_circle:|io/questdb/griffin/engine/join/HashOuterJoinLightRecordCursorFactory.java|1|1|100.00%|
|:large_blue_circle:|io/questdb/cairo/DefaultCairoConfiguration.java|1|1|100.00%|
|:large_blue_circle:|io/questdb/griffin/engine/join/LtJoinRecordCursorFactory.java|1|1|100.00%|
|:large_blue_circle:|io/questdb/griffin/engine/join/SpliceJoinLightRecordCursorFactory.java|1|1|100.00%|
|:large_blue_circle:|io/questdb/griffin/engine/join/HashJoinRecordCursorFactory.java|1|1|100.00%|
|:large_blue_circle:|io/questdb/cairo/map/Unordered16MapRecord.java|1|1|100.00%|
|:large_blue_circle:|io/questdb/cairo/map/Unordered4MapCursor.java|42|42|100.00%|
|:large_blue_circle:|io/questdb/griffin/engine/join/HashOuterJoinFilteredLightRecordCursorFactory.java|1|1|100.00%|
|:large_blue_circle:|io/questdb/griffin/engine/join/HashOuterJoinRecordCursorFactory.java|1|1|100.00%|
|:large_blue_circle:|io/questdb/griffin/engine/join/HashJoinLightRecordCursorFactory.java|1|1|100.00%|
|:large_blue_circle:|io/questdb/cairo/map/MapFactory.java|7|7|100.00%|
|:large_blue_circle:|io/questdb/griffin/engine/join/LtJoinLightRecordCursorFactory.java|1|1|100.00%|
|:large_blue_circle:|io/questdb/griffin/engine/join/AsOfJoinLightRecordCursorFactory.java|1|1|100.00%|

**Review by bluestreak01 — APPROVED** [review]

**Pull request merged**
