### PR TITLE
fix(sql): rename column from `name` to `table_name` in cursor function tables

### PR DESCRIPTION
**Pull request by marregui**

### CODE REVIEW

**Comment by ideoma** [comment]
#### [PR Coverage check]

:heart_eyes: **pass** : 3 / 3 (100.00%)




#### file detail

|   |path|covered line|new line|coverage|
|----|----|----|----|----|
|:large_blue_circle:|io/questdb/griffin/engine/functions/catalogue/TableListFunctionFactory.java|3|3|100.00%|

**Review by bluestreak01 — CHANGES_REQUESTED** [review]
This PR breaks Web Console. It has canned SQLs that broke:
image
Ideally this PR should include new Web Console release

**Comment by ideoma** [comment]
#### [PR Coverage check]

:heart_eyes: **pass** : 3 / 3 (100.00%)




#### file detail

|   |path|covered line|new line|coverage|
|----|----|----|----|----|
|:large_blue_circle:|io/questdb/griffin/engine/functions/catalogue/TableListFunctionFactory.java|3|3|100.00%|

**Comment by ideoma** [comment]
#### [PR Coverage check]

:heart_eyes: **pass** : 3 / 3 (100.00%)




#### file detail

|   |path|covered line|new line|coverage|
|----|----|----|----|----|
|:large_blue_circle:|io/questdb/griffin/engine/functions/catalogue/TableListFunctionFactory.java|3|3|100.00%|

**Review by bluestreak01 — APPROVED** [review]

**Pull request merged**
