### PR TITLE
fix(sql): consider order when checking timestamp order in metadata

### LINKED ISSUE #2092: Metadata's timestamp index breaks sample by in desc order case
With recent changes `RecordMetadata#getTimestampIndex()` is allowed to return non-`-1` value in the ORDER BY designated_ts DESC case (also see `RecordCursorFactory#hasDescendingOrder()`). This can be easily seen on filtered scan queries, but not only. Previously, the contract was different: a non-`-1` value was returned only for empty ORDER BY and ORDER BY designated_ts ASC cases.

This change breaks certain assumptions we had in the code. Say, SAMPLE BY assumes that the records are ASC ordered when it does this check: https://github.com/questdb/questdb/blob/b7f6318c753712d6de7dc1bcf97992d1ad377b9d/core/src/main/java/io/questdb/griffin/SqlCodeGenerator.java#L1558-L1562

### Reproducer

```sql
create table test as (
  select  x, rnd_symbol('A', 'B', 'C') as sym, timestamp_sequence(0, 10000000) ts
  from long_sequence(10000)
) timestamp(ts) partition by day;
```

The query
```sql
select ts, first(x)
from (test where x % 2 = 0 order by x ts desc)
sample by 1h;
```
works (and returns some rubbish) while it should fail with `base query does not provide dedicated TIMESTAMP column` error.

### Summary

We should go through all places (not only SAMPLE BY) where we're using `RecordMetadata#getTimestampIndex()` and make sure to check the sort order.

### PR DESCRIPTION
**Pull request by puzpuzpuz**
Closes #2092

Adds missing checks for designated timestamp column order to the places where we require ASC order, like SAMPLE BY. That's because `RecordMetadata#getTimestampIndex()` may now return non -1 value in the DESC timestamp order case.

### CODE REVIEW

**Comment by ideoma** [comment]
#### [PR Coverage check]

:heart_eyes: **pass** : 7 / 11 (63.64%)




#### file detail

|   |path|covered line|new line|coverage|
|----|----|----|----|----|
|:large_blue_circle:|io/questdb/griffin/engine/join/HashOuterJoinLightRecordCursorFactory.java|0|1|00.00%|
|:large_blue_circle:|io/questdb/griffin/engine/join/HashJoinRecordCursorFactory.java|0|1|00.00%|
|:large_blue_circle:|io/questdb/griffin/engine/join/HashOuterJoinRecordCursorFactory.java|0|1|00.00%|
|:large_blue_circle:|io/questdb/griffin/engine/groupby/DistinctTimeSeriesRecordCursorFactory.java|2|3|66.67%|
|:large_blue_circle:|io/questdb/griffin/SqlCodeGenerator.java|4|4|100.00%|
|:large_blue_circle:|io/questdb/griffin/engine/join/HashJoinLightRecordCursorFactory.java|1|1|100.00%|

**Review by bluestreak01 — CHANGES_REQUESTED** [review]
There are more places. If you check usages of `RecordMetadata.getTimestampIndex()` some of them should be apparent.

image

this is todo with As Of and Lt join generation

**Review by bluestreak01 — CHANGES_REQUESTED** [review]
image

**Review by bluestreak01 — CHANGES_REQUESTED** [review]
image

**Review by bluestreak01 — CHANGES_REQUESTED** [review]
```sql
insert as select ...
```

**Comment by puzpuzpuz** [comment]
> If you check usages of `RecordMetadata.getTimestampIndex()` some of them should be apparent.

That's what I did when creating this PR, yet the places you're referring to didn't seem to be applicable. Let me double check them.

**Comment by puzpuzpuz** [comment]
`DistinctTimeSeriesRecordCursorFactory` works correctly in the ORDER BY ts DESC case and there is a test for that. See `DistinctTimeSeriesTest#testTimestampDescOrder()`

**Comment by puzpuzpuz** [comment]
> ```sql
> insert as select ...
> ```

Both `CREATE TABLE x AS (SELECT ...)` and `INSERT INTO x SELECT ...` are ok since we end up with O3 inserts. Added some tests to verify the behavior in 18b3af12ddfab22c511015d0bbb2bbfd5a0a8f2b

**Comment by ideoma** [comment]
#### [PR Coverage check]

:heart_eyes: **pass** : 10 / 14 (71.43%)




#### file detail

|   |path|covered line|new line|coverage|
|----|----|----|----|----|
|:large_blue_circle:|io/questdb/griffin/engine/join/HashOuterJoinLightRecordCursorFactory.java|0|1|00.00%|
|:large_blue_circle:|io/questdb/griffin/engine/join/HashJoinRecordCursorFactory.java|0|1|00.00%|
|:large_blue_circle:|io/questdb/griffin/engine/join/HashOuterJoinRecordCursorFactory.java|0|1|00.00%|
|:large_blue_circle:|io/questdb/griffin/engine/groupby/DistinctTimeSeriesRecordCursorFactory.java|2|3|66.67%|
|:large_blue_circle:|io/questdb/griffin/SqlCompiler.java|3|3|100.00%|
|:large_blue_circle:|io/questdb/griffin/SqlCodeGenerator.java|4|4|100.00%|
|:large_blue_circle:|io/questdb/griffin/engine/join/HashJoinLightRecordCursorFactory.java|1|1|100.00%|

**Comment by puzpuzpuz** [comment]
> this is todo with As Of and Lt join generation

Added missing validation for ASOF / LT / SPLICE JOIN in 223f86627017f44c7d79718af5e78101922d786c

**Comment by ideoma** [comment]
#### [PR Coverage check]

:heart_eyes: **pass** : 26 / 29 (89.66%)




#### file detail

|   |path|covered line|new line|coverage|
|----|----|----|----|----|
|:large_blue_circle:|io/questdb/griffin/engine/join/HashOuterJoinLightRecordCursorFactory.java|0|1|00.00%|
|:large_blue_circle:|io/questdb/griffin/engine/join/HashJoinRecordCursorFactory.java|0|1|00.00%|
|:large_blue_circle:|io/questdb/griffin/engine/join/HashOuterJoinRecordCursorFactory.java|0|1|00.00%|
|:large_blue_circle:|io/questdb/griffin/engine/groupby/DistinctTimeSeriesRecordCursorFactory.java|3|3|100.00%|
|:large_blue_circle:|io/questdb/griffin/engine/join/AsOfJoinRecordCursorFactory.java|1|1|100.00%|
|:large_blue_circle:|io/questdb/griffin/engine/join/AsOfJoinNoKeyRecordCursorFactory.java|1|1|100.00%|
|:large_blue_circle:|io/questdb/griffin/engine/join/LtJoinNoKeyRecordCursorFactory.java|1|1|100.00%|
|:large_blue_circle:|io/questdb/griffin/engine/join/LtJoinRecordCursorFactory.java|1|1|100.00%|
|:large_blue_circle:|io/questdb/griffin/engine/join/SpliceJoinLightRecordCursorFactory.java|1|1|100.00%|
|:large_blue_circle:|io/questdb/griffin/SqlCompiler.java|3|3|100.00%|
|:large_blue_circle:|io/questdb/griffin/SqlCodeGenerator.java|12|12|100.00%|
|:large_blue_circle:|io/questdb/griffin/engine/join/HashJoinLightRecordCursorFactory.java|1|1|100.00%|
|:large_blue_circle:|io/questdb/griffin/engine/join/LtJoinLightRecordCursorFactory.java|1|1|100.00%|
|:large_blue_circle:|io/questdb/griffin/engine/join/AsOfJoinLightRecordCursorFactory.java|1|1|100.00%|

**Comment by puzpuzpuz** [comment]
@bluestreak01 I went through all places where we use `RecordMetadata#getTimestampIndex()` once again and added missing checks and tests. There may be some blind spots still, so would be nice if you could do another review round.

**Comment by ideoma** [comment]
#### [PR Coverage check]

:heart_eyes: **pass** : 27 / 30 (90.00%)




#### file detail

|   |path|covered line|new line|coverage|
|----|----|----|----|----|
|:large_blue_circle:|io/questdb/griffin/engine/join/HashOuterJoinLightRecordCursorFactory.java|0|1|00.00%|
|:large_blue_circle:|io/questdb/griffin/engine/join/HashJoinRecordCursorFactory.java|0|1|00.00%|
|:large_blue_circle:|io/questdb/griffin/engine/join/HashOuterJoinRecordCursorFactory.java|0|1|00.00%|
|:large_blue_circle:|io/questdb/griffin/engine/groupby/DistinctTimeSeriesRecordCursorFactory.java|3|3|100.00%|
|:large_blue_circle:|io/questdb/griffin/engine/join/AsOfJoinRecordCursorFactory.java|1|1|100.00%|
|:large_blue_circle:|io/questdb/griffin/engine/join/AsOfJoinNoKeyRecordCursorFactory.java|1|1|100.00%|
|:large_blue_circle:|io/questdb/griffin/engine/table/VirtualRecordCursorFactory.java|1|1|100.00%|
|:large_blue_circle:|io/questdb/griffin/engine/join/LtJoinNoKeyRecordCursorFactory.java|1|1|100.00%|
|:large_blue_circle:|io/questdb/griffin/engine/join/LtJoinRecordCursorFactory.java|1|1|100.00%|
|:large_blue_circle:|io/questdb/griffin/engine/join/SpliceJoinLightRecordCursorFactory.java|1|1|100.00%|
|:large_blue_circle:|io/questdb/griffin/SqlCompiler.java|3|3|100.00%|
|:large_blue_circle:|io/questdb/griffin/SqlCodeGenerator.java|12|12|100.00%|
|:large_blue_circle:|io/questdb/griffin/engine/join/HashJoinLightRecordCursorFactory.java|1|1|100.00%|
|:large_blue_circle:|io/questdb/griffin/engine/join/LtJoinLightRecordCursorFactory.java|1|1|100.00%|
|:large_blue_circle:|io/questdb/griffin/engine/join/AsOfJoinLightRecordCursorFactory.java|1|1|100.00%|

**Comment by ideoma** [comment]
#### [PR Coverage check]

:heart_eyes: **pass** : 27 / 30 (90.00%)




#### file detail

|   |path|covered line|new line|coverage|
|----|----|----|----|----|
|:large_blue_circle:|io/questdb/griffin/engine/join/HashOuterJoinLightRecordCursorFactory.java|0|1|00.00%|
|:large_blue_circle:|io/questdb/griffin/engine/join/HashJoinRecordCursorFactory.java|0|1|00.00%|
|:large_blue_circle:|io/questdb/griffin/engine/join/HashOuterJoinRecordCursorFactory.java|0|1|00.00%|
|:large_blue_circle:|io/questdb/griffin/engine/groupby/DistinctTimeSeriesRecordCursorFactory.java|3|3|100.00%|
|:large_blue_circle:|io/questdb/griffin/engine/join/AsOfJoinRecordCursorFactory.java|1|1|100.00%|
|:large_blue_circle:|io/questdb/griffin/engine/join/AsOfJoinNoKeyRecordCursorFactory.java|1|1|100.00%|
|:large_blue_circle:|io/questdb/griffin/engine/table/VirtualRecordCursorFactory.java|1|1|100.00%|
|:large_blue_circle:|io/questdb/griffin/engine/join/LtJoinNoKeyRecordCursorFactory.java|1|1|100.00%|
|:large_blue_circle:|io/questdb/griffin/engine/join/LtJoinRecordCursorFactory.java|1|1|100.00%|
|:large_blue_circle:|io/questdb/griffin/engine/join/SpliceJoinLightRecordCursorFactory.java|1|1|100.00%|
|:large_blue_circle:|io/questdb/griffin/SqlCompiler.java|3|3|100.00%|
|:large_blue_circle:|io/questdb/griffin/SqlCodeGenerator.java|12|12|100.00%|
|:large_blue_circle:|io/questdb/griffin/engine/join/HashJoinLightRecordCursorFactory.java|1|1|100.00%|
|:large_blue_circle:|io/questdb/griffin/engine/join/LtJoinLightRecordCursorFactory.java|1|1|100.00%|
|:large_blue_circle:|io/questdb/griffin/engine/join/AsOfJoinLightRecordCursorFactory.java|1|1|100.00%|

**Review by bluestreak01 — APPROVED** [review]

**Review by bziobrowski — APPROVED** [review]

**Comment by puzpuzpuz** [comment]
Yeah, the message is more like a hint rather than the accurate description of the problematic join member. But having something more accurate might require lots of changes in the compiler, so let's keep as is.

**Pull request merged**
