### PR TITLE
fix(pgwire): fix spurious error when executing "create table" SQL from Rust

### PR DESCRIPTION
**Pull request by bluestreak01**
When executing any `CREATE TABLE` statement via Rust table would be created but Rust client will receive spurious "table already exists" error. This PR fixes that by not re-executing `CREATE TABLE` despite Rust treating it as a prepared statement.

Fixes the following:
- in "simple" mode we print millis using `S` format, which removes leading zeroes. This causes incorrect data values to be returned and inconsistent behaviour between "simple" and "extended" protocols
- in "extended" protocol mode we could run non-renetrable SQL statements twice, those include `CREATE TABLE`, `CREATE AS SELECT` and `COPY`
- errors parsing `BIND` message would leave `syncActions` array dirty. Subsequent SQL execution crashes JDBC driver due to duplicate response from the server
- we force disconnect client if they attempt to send `CLOSE` message on non-existing statement. This behaviour is removed. Some `PARSE` errors could end up never registering named statement, which would subsequently fail to close.

Adds tests, most PG wire tests, which require simple connection, are now run by a wrapper. This wrapper executes the same "lambda" against 12 different protocol combinations. This ensures consistent behaviour wherever possible.

## Gotcha

`testBatchInsertWithTransaction` excludes `simple` protocol due to a bug. With simple protocol enabled, test hangs the connection on "cannot insert records out of order" error. We are sending invalid error response to the driver. This requires wireshark investigation as the behaviour is specific to batch execution over simple protocol. @bziobrowski would you mind having a look please?

### CODE REVIEW

**Comment by ideoma** [comment]
#### [PR Coverage check]

:heart_eyes: **pass** : 3 / 3 (100.00%)




#### file detail

|   |path|covered line|new line|coverage|
|----|----|----|----|----|
|:large_blue_circle:|io/questdb/cutlass/pgwire/PGConnectionContext.java|3|3|100.00%|

**Comment by bziobrowski** [comment]
The real issue is that create table statement is executed in parse phase instead of execute .
First test below reproduces the issue and should be more readable than hex . It does work with the fix but if CTAS statement contains bind variable it still returns error even though in the background it creates table and populates with bad data (first column is all nulls because bind variable value is missing during execution). 

```
    @Test
    public void testCreateTable() throws Exception {
        assertMemoryLeak(() -> {
            try (
                    final PGWireServer ignored = createPGServer(2);
                    final Connection connection = getConnection(Mode.ExtendedForPrepared, false, -1)
            ) {
                connection.setAutoCommit(false);
                try (PreparedStatement pstmt = connection.prepareStatement("create table t (\n" +
                        "  a SYMBOL,\n" +
                        "  b TIMESTAMP)\n" +
                        "    timestamp(b)")) {
                    pstmt.execute();
                }
            }
        });
    }

    @Test
    public void testCreateTable2() throws Exception {
        assertMemoryLeak(() -> {
            try (
                    final PGWireServer ignored = createPGServer(2);
                    final Connection connection = getConnection(Mode.ExtendedForPrepared, false, -1)
            ) {
                connection.setAutoCommit(false);
                try (PreparedStatement pstmt = connection.prepareStatement("create table t as " +
                        "(select cast(x + ? as long) a, cast(x as timestamp) b from long_sequence(10))")) {
                    pstmt.setLong(1, 10);
                    pstmt.execute();
                }
            }
        });
    }
```

**Comment by bluestreak01** [comment]
Thank you @bziobrowski Your test is a lot better and reproduces the very same issue found by Rust.

Regarding bind variables in `CREATE TABLE`. This is not so much of PG wire issue. We do not have infrastructure at compiler level to execute this. That said, it is not a difficult addition but use-case seems a bit far fetched for now. I would not bother in this PR.

**Comment by ideoma** [comment]
#### [PR Coverage check]

:heart_eyes: **pass** : 3 / 3 (100.00%)




#### file detail

|   |path|covered line|new line|coverage|
|----|----|----|----|----|
|:large_blue_circle:|io/questdb/cutlass/pgwire/PGConnectionContext.java|3|3|100.00%|

**Comment by bziobrowski** [comment]
CTAS executed as prepared statements fail even when there are no actual bind variables so this fix works only for CREATE TABLE x (spec) statements .

**Comment by ideoma** [comment]
#### [PR Coverage check]

:heart_eyes: **pass** : 7 / 7 (100.00%)




#### file detail

|   |path|covered line|new line|coverage|
|----|----|----|----|----|
|:large_blue_circle:|io/questdb/cutlass/pgwire/PGConnectionContext.java|6|6|100.00%|
|:large_blue_circle:|io/questdb/std/datetime/millitime/DateFormatUtils.java|1|1|100.00%|

**Comment by bluestreak01** [comment]
All the issues Bolek mentioned are fixed.

After merging master, which brought copy unification PR new “fuzz” PG tests began to fail specifically for “copy” sql. I asked @puzpuzpuz to take a look asap

**Comment by puzpuzpuz** [comment]
The COPY issue is now fixed as well as the CTAS/DDL not being executed on multiple statement runs.

**Comment by ideoma** [comment]
#### [PR Coverage check]

:heart_eyes: **pass** : 77 / 79 (97.47%)




#### file detail

|   |path|covered line|new line|coverage|
|----|----|----|----|----|
|:large_blue_circle:|io/questdb/griffin/SqlCompiler.java|36|38|94.74%|
|:large_blue_circle:|io/questdb/cutlass/pgwire/PGConnectionContext.java|7|7|100.00%|
|:large_blue_circle:|io/questdb/std/datetime/millitime/DateFormatUtils.java|1|1|100.00%|
|:large_blue_circle:|io/questdb/griffin/engine/ops/CopyFactory.java|33|33|100.00%|

**Comment by ideoma** [comment]
#### [PR Coverage check]

:heart_eyes: **pass** : 85 / 87 (97.70%)




#### file detail

|   |path|covered line|new line|coverage|
|----|----|----|----|----|
|:large_blue_circle:|io/questdb/griffin/SqlCompiler.java|36|38|94.74%|
|:large_blue_circle:|io/questdb/cutlass/pgwire/PGWireServer.java|2|2|100.00%|
|:large_blue_circle:|io/questdb/cutlass/pgwire/PGConnectionContext.java|13|13|100.00%|
|:large_blue_circle:|io/questdb/std/datetime/millitime/DateFormatUtils.java|1|1|100.00%|
|:large_blue_circle:|io/questdb/griffin/engine/ops/CopyFactory.java|33|33|100.00%|

**Review by puzpuzpuz — APPROVED** [review]

**Pull request merged**
