### PR TITLE
fix(sql): allow selecting aliased column followed by wildcard

### LINKED ISSUE #2870: Duplicate Column when using CAST and * in the same SELECT
### Describe the bug

When doing `SELECT CAST(anycolumn AS type) AS newName, * FROM table` we get a duplicate column error

If we change the order of arguments and do instead `SELECT *, CAST(anycolumn AS type) AS newName FROM table`, this works

It should always work without errors 

### To reproduce

Go to the demo site at https://demo.questdb.io

This works
`select *, cast(timestamp AS long) AS t from trades
`
This breaks
`select cast(timestamp AS long) AS t , * from trades
`
Same with other datatypes. Example
`select cast(price AS long) AS t , * from trades`

### Expected Behavior

Returns should be returned with no errors. Business as usual

### Environment

```markdown
- **QuestDB version**:6.1.1
- **OS**: demo machine and also locally on Mac M1
- **Browser**: Chrome
```

### Additional context

_No response_

### PR DESCRIPTION
**Pull request by puzpuzpuz**
Fixes #2870

### CODE REVIEW

**Comment by ideoma** [comment]
#### [PR Coverage check]

:heart_eyes: **pass** : 1 / 1 (100.00%)




#### file detail

|   |path|covered line|new line|coverage|
|----|----|----|----|----|
|:large_blue_circle:|io/questdb/griffin/SqlOptimiser.java|1|1|100.00%|

**Review by eugenels — APPROVED** [review]

**Comment by bziobrowski** [comment]
Similar error still occurs if there's a join : 

```sql
create table xo1 as 
(
  select
  rnd_double(0)*100 a,
  rnd_long() l,
  timestamp_sequence(0, 10000) k
  from long_sequence(3)
) timestamp(k);

create table xo2 as 
(
  select
  rnd_double(0)*100 a,
  rnd_long() l,
  timestamp_sequence(0, 10000) k
  from long_sequence(3)
) timestamp(k);


select cast(xo1.k as long), cast(xo2.k as long), *
from xo1  
join xo2 on xo1.k = xo2.k;

--Duplicate column [name=k]
```

**Comment by puzpuzpuz** [comment]
@bziobrowski good catch. Let me take a look at joins.

**Comment by puzpuzpuz** [comment]
> Similar error still occurs if there's a join

Addressed in 008787954b30e503454d9d2f414dd1f136413355

```sql
select rnd_int()*k as zz, *
from xo1  
join xo2 on xo1.k = xo2.k;**
```

This query is incorrect: should be `rnd_int()*xo1.k` or `rnd_int()*xo2.k` instead of `rnd_int()*k`.

**Comment by ideoma** [comment]
#### [PR Coverage check]

:heart_eyes: **pass** : 3 / 3 (100.00%)




#### file detail

|   |path|covered line|new line|coverage|
|----|----|----|----|----|
|:large_blue_circle:|io/questdb/griffin/SqlOptimiser.java|3|3|100.00%|

**Comment by eugenels** [comment]
> Similar error still occurs if there's a join :
> 
> ```sql
> create table xo1 as 
> (
>   select
>   rnd_double(0)*100 a,
>   rnd_long() l,
>   timestamp_sequence(0, 10000) k
>   from long_sequence(3)
> ) timestamp(k);
> 
> create table xo2 as 
> (
>   select
>   rnd_double(0)*100 a,
>   rnd_long() l,
>   timestamp_sequence(0, 10000) k
>   from long_sequence(3)
> ) timestamp(k);
> 
> 
> select cast(xo1.k as long), cast(xo2.k as long), *
> from xo1  
> join xo2 on xo1.k = xo2.k;
> 
> --or
> 
> select rnd_int()*k as zz, * 
> from xo1  
> join xo2 on xo1.k = xo2.k;
> 
> --Duplicate column [name=k]
> ```

Should this work for cross join as well?

```sql
select *, xo1.k as kk1 from xo1 cross join xo2;
-- vs
select xo1.k as kk1, * from xo1 cross join xo2;
```

**Comment by puzpuzpuz** [comment]
> Should this work for cross join as well?

Yes, it should. Fixed that in 3404ce6ba4b51266ca746a94e34ce73147867726

**Comment by ideoma** [comment]
#### [PR Coverage check]

:heart_eyes: **pass** : 8 / 8 (100.00%)




#### file detail

|   |path|covered line|new line|coverage|
|----|----|----|----|----|
|:large_blue_circle:|io/questdb/griffin/SqlOptimiser.java|8|8|100.00%|

**Comment by ideoma** [comment]
#### [PR Coverage check]

:heart_eyes: **pass** : 8 / 8 (100.00%)




#### file detail

|   |path|covered line|new line|coverage|
|----|----|----|----|----|
|:large_blue_circle:|io/questdb/griffin/SqlOptimiser.java|8|8|100.00%|

**Pull request merged**
