### PR TITLE
chore(build): fix `TxnScoreboardTest.testHammer` to check the pattern used in production code

### PR DESCRIPTION
**Pull request by ideoma**
Check in Scoreboard concurrency test the pattern used in production code to determine that there are no readers and it's safe to delete the partition version to prevent random test failures.

### CODE REVIEW

**Comment by questdb-butler** [comment]
<table>
  <thead>
    <tr>
      <th width="50"></th>
      <th width="100%" data-danger-table="true">Fails</th>
    </tr>
  </thead>
  <tbody><tr>
      <td>:no_entry_sign:</td>
      <td>

  Please update the PR title to match this format:
`type(subType): description`

Where `type` is one of:
`feat`, `fix`, `chore`, `docs`, `style`, `refactor`, `perf`, `test`, `ci`, `chore`, `revert`

And: `subType` is one of:
`build`, `sql`, `log`, `mig`, `core`, `ilp`, `pgwire`, `http`, `conf`, `ui`, `wal`

For Example:

```
perf(sql): improve pattern matching performance for SELECT sub-queries
```
  </td>
    </tr>
  </tbody>
</table>




<p align="right">
  Generated by :no_entry_sign: <a href="https://danger.systems/js">dangerJS</a> against 377bdcb46fc628b8fb8dcefde02b4d9968a00ff2
</p>

**Comment by bluestreak01** [comment]
`testHammer` was flapping, how does this PR fix that ?

**Comment by ideoma** [comment]
> `testHammer` was flapping, how does this PR fix that ?

yes

**Comment by ideoma** [comment]
> `testHammer` was flapping, how does this PR fix that ?

Didn't understand the question first.

It's fixed by checking that scoreboard is locked with same way as we check in production code 

```

                    // Simulate TableWriter trying to find if there are readers before the published transaction
                    if (scoreboard.acquireTxn(nextTxn)) {
                        scoreboard.releaseTxn(nextTxn);
                    }

                    writerMin = scoreboard.getMin();
```

After writer publishes new transaction number it locks / unlocks the scoreboard with the newly published number and checks the scoreboard min. If the min matches the newly published number means there are no readers for old transaction numbers.

**Review by bluestreak01 — APPROVED** [review]

**Pull request merged**
