### PR TITLE
fix(cairo): fix o3 partition purge jobs

### PR DESCRIPTION
**Pull request by ideoma**
Partition purge jobs did not work properly for cases where not every commit is out of order commit. 

This change will only remove a partition if there are no readers with transaction number below next available partition version. 

It also addresses inconsistency that when reader reads transaction 10 it will look at partition folders .9 and not .10

### CODE REVIEW

**Comment by ideoma** [comment]
#### [PR Coverage check]

:heart_eyes: **pass** : 140 / 156 (89.74%)




#### file detail

|   |path|covered line|new line|coverage|
|----|----|----|----|----|
|:large_blue_circle:|io/questdb/cairo/O3PurgeDiscoveryJob.java|20|28|71.43%|
|:large_blue_circle:|io/questdb/cairo/TableWriter.java|109|117|93.16%|
|:large_blue_circle:|io/questdb/cairo/O3PurgeJob.java|11|11|100.00%|

**Comment by ideoma** [comment]
#### [PR Coverage check]

:heart_eyes: **pass** : 163 / 166 (98.19%)




#### file detail

|   |path|covered line|new line|coverage|
|----|----|----|----|----|
|:large_blue_circle:|io/questdb/cairo/TableWriter.java|137|140|97.86%|
|:large_blue_circle:|io/questdb/cairo/O3PurgeJob.java|12|12|100.00%|
|:large_blue_circle:|io/questdb/cairo/O3PurgeDiscoveryJob.java|14|14|100.00%|

**Comment by ideoma** [comment]
#### [PR Coverage check]

:heart_eyes: **pass** : 163 / 166 (98.19%)




#### file detail

|   |path|covered line|new line|coverage|
|----|----|----|----|----|
|:large_blue_circle:|io/questdb/cairo/TableWriter.java|137|140|97.86%|
|:large_blue_circle:|io/questdb/cairo/O3PurgeJob.java|12|12|100.00%|
|:large_blue_circle:|io/questdb/cairo/O3PurgeDiscoveryJob.java|14|14|100.00%|

**Comment by ideoma** [comment]
#### [PR Coverage check]

:heart_eyes: **pass** : 163 / 166 (98.19%)




#### file detail

|   |path|covered line|new line|coverage|
|----|----|----|----|----|
|:large_blue_circle:|io/questdb/cairo/TableWriter.java|137|140|97.86%|
|:large_blue_circle:|io/questdb/cairo/O3PurgeJob.java|12|12|100.00%|
|:large_blue_circle:|io/questdb/cairo/O3PurgeDiscoveryJob.java|14|14|100.00%|

**Comment by ideoma** [comment]
#### [PR Coverage check]

:heart_eyes: **pass** : 163 / 166 (98.19%)




#### file detail

|   |path|covered line|new line|coverage|
|----|----|----|----|----|
|:large_blue_circle:|io/questdb/cairo/TableWriter.java|137|140|97.86%|
|:large_blue_circle:|io/questdb/cairo/O3PurgeJob.java|12|12|100.00%|
|:large_blue_circle:|io/questdb/cairo/O3PurgeDiscoveryJob.java|14|14|100.00%|

**Review by bluestreak01 — APPROVED** [review]

**Comment by ideoma** [comment]
#### [PR Coverage check]

:heart_eyes: **pass** : 163 / 166 (98.19%)




#### file detail

|   |path|covered line|new line|coverage|
|----|----|----|----|----|
|:large_blue_circle:|io/questdb/cairo/TableWriter.java|137|140|97.86%|
|:large_blue_circle:|io/questdb/cairo/O3PurgeJob.java|12|12|100.00%|
|:large_blue_circle:|io/questdb/cairo/O3PurgeDiscoveryJob.java|14|14|100.00%|

**Pull request merged**
