### PR TITLE
fix(sql): fix timestamp interval optimizer case sensitivity

### LINKED ISSUE #2858: Timestamp interval optimizer is case sensitive
### Describe the bug

```sql
create table t as (
  select
    rnd_symbol('A', 'B') SYM,
    rnd_long() L,
    timestamp_sequence(0, 1000000000) TS
  from long_sequence(1000000)
) timestamp(TS);
```

Notice upper-case column names.

```sql
select *
from t
where sym = 'A'
  and ts > '2024-01-01 00:00:00';
```

The above query leads to a full scan while the filtered intervals has no rows in it.

### To reproduce

_No response_

### Expected Behavior

_No response_

### Environment

```markdown
- **QuestDB version**:
- **OS**:
- **Browser**:
```

### Additional context

_No response_

### PR DESCRIPTION
**Pull request by puzpuzpuz**
Fixes #2858

Also aligns `Chars#equalsNc()`, `Chars#equalsIgnoreCaseNc()` and `Chars#equalsLowerCaseAsciiNc()` in terms of argument nullability.

### CODE REVIEW

**Comment by ideoma** [comment]
#### [PR Coverage check]

:heart_eyes: **pass** : 48 / 48 (100.00%)




#### file detail

|   |path|covered line|new line|coverage|
|----|----|----|----|----|
|:large_blue_circle:|io/questdb/std/Chars.java|4|4|100.00%|
|:large_blue_circle:|io/questdb/griffin/WhereClauseParser.java|39|39|100.00%|
|:large_blue_circle:|io/questdb/griffin/SqlCompiler.java|4|4|100.00%|
|:large_blue_circle:|io/questdb/cairo/AbstractDataFrameCursorFactory.java|1|1|100.00%|

**Review by marregui — APPROVED** [review]
LGTM

it reformatted a lot of indentation from 4 to 8 spaces, is this the norm? 8 spaces?

**Comment by bluestreak01** [comment]
@marregui you can open this PR and format the code locally in intellij, that should yield almost no changes!

**Comment by puzpuzpuz** [comment]
> it reformatted a lot of indentation from 4 to 8 spaces, is this the norm? 8 spaces?

Yes, 8 spaces is the norm. For some time we had an issue with `.editorconfig` which took over the IDEA settings, so that a few wrongly formatted files got through into the `master` branch.

**Comment by puzpuzpuz** [comment]
@marregui thanks for the review!

**Comment by ideoma** [comment]
#### [PR Coverage check]

:heart_eyes: **pass** : 48 / 48 (100.00%)




#### file detail

|   |path|covered line|new line|coverage|
|----|----|----|----|----|
|:large_blue_circle:|io/questdb/std/Chars.java|4|4|100.00%|
|:large_blue_circle:|io/questdb/griffin/WhereClauseParser.java|39|39|100.00%|
|:large_blue_circle:|io/questdb/griffin/SqlCompiler.java|4|4|100.00%|
|:large_blue_circle:|io/questdb/cairo/AbstractDataFrameCursorFactory.java|1|1|100.00%|

**Pull request merged**
