### PR TITLE
feat(sql): improve expression parsing of geohash type constant

### PR DESCRIPTION
**Pull request by marregui**
Thanks for the patience.

### CODE REVIEW

**Comment by ideoma** [comment]
#### [PR Coverage check]

:heart_eyes: **pass** : 28 / 28 (100.00%)




#### file detail

|   |path|covered line|new line|coverage|
|----|----|----|----|----|
|:large_blue_circle:|io/questdb/griffin/PostOrderTreeTraversalAlgo.java|1|1|100.00%|
|:large_blue_circle:|io/questdb/griffin/SqlKeywords.java|1|1|100.00%|
|:large_blue_circle:|io/questdb/griffin/FunctionParser.java|4|4|100.00%|
|:large_blue_circle:|io/questdb/griffin/SqlParser.java|7|7|100.00%|
|:large_blue_circle:|io/questdb/griffin/ExpressionParser.java|8|8|100.00%|
|:large_blue_circle:|io/questdb/griffin/SqlCompiler.java|1|1|100.00%|
|:large_blue_circle:|io/questdb/std/GenericLexer.java|6|6|100.00%|

**Comment by ideoma** [comment]
#### [PR Coverage check]

:heart_eyes: **pass** : 28 / 28 (100.00%)




#### file detail

|   |path|covered line|new line|coverage|
|----|----|----|----|----|
|:large_blue_circle:|io/questdb/griffin/PostOrderTreeTraversalAlgo.java|1|1|100.00%|
|:large_blue_circle:|io/questdb/griffin/FunctionParser.java|4|4|100.00%|
|:large_blue_circle:|io/questdb/griffin/SqlKeywords.java|1|1|100.00%|
|:large_blue_circle:|io/questdb/griffin/SqlParser.java|7|7|100.00%|
|:large_blue_circle:|io/questdb/griffin/ExpressionParser.java|8|8|100.00%|
|:large_blue_circle:|io/questdb/griffin/SqlCompiler.java|1|1|100.00%|
|:large_blue_circle:|io/questdb/std/GenericLexer.java|6|6|100.00%|

**Comment by ideoma** [comment]
#### [PR Coverage check]

:heart_eyes: **pass** : 52 / 53 (98.11%)




#### file detail

|   |path|covered line|new line|coverage|
|----|----|----|----|----|
|:large_blue_circle:|io/questdb/std/GenericLexer.java|16|17|94.12%|
|:large_blue_circle:|io/questdb/griffin/PostOrderTreeTraversalAlgo.java|1|1|100.00%|
|:large_blue_circle:|io/questdb/griffin/FunctionParser.java|4|4|100.00%|
|:large_blue_circle:|io/questdb/griffin/SqlKeywords.java|10|10|100.00%|
|:large_blue_circle:|io/questdb/griffin/SqlParser.java|7|7|100.00%|
|:large_blue_circle:|io/questdb/griffin/ExpressionParser.java|13|13|100.00%|
|:large_blue_circle:|io/questdb/griffin/SqlCompiler.java|1|1|100.00%|

**Comment by ideoma** [comment]
#### [PR Coverage check]

:heart_eyes: **pass** : 52 / 53 (98.11%)




#### file detail

|   |path|covered line|new line|coverage|
|----|----|----|----|----|
|:large_blue_circle:|io/questdb/std/GenericLexer.java|16|17|94.12%|
|:large_blue_circle:|io/questdb/griffin/PostOrderTreeTraversalAlgo.java|1|1|100.00%|
|:large_blue_circle:|io/questdb/griffin/SqlKeywords.java|10|10|100.00%|
|:large_blue_circle:|io/questdb/griffin/FunctionParser.java|4|4|100.00%|
|:large_blue_circle:|io/questdb/griffin/SqlParser.java|7|7|100.00%|
|:large_blue_circle:|io/questdb/griffin/ExpressionParser.java|13|13|100.00%|
|:large_blue_circle:|io/questdb/griffin/SqlCompiler.java|1|1|100.00%|

**Comment by ideoma** [comment]
#### [PR Coverage check]

:heart_eyes: **pass** : 52 / 53 (98.11%)




#### file detail

|   |path|covered line|new line|coverage|
|----|----|----|----|----|
|:large_blue_circle:|io/questdb/std/GenericLexer.java|16|17|94.12%|
|:large_blue_circle:|io/questdb/griffin/PostOrderTreeTraversalAlgo.java|1|1|100.00%|
|:large_blue_circle:|io/questdb/griffin/SqlKeywords.java|10|10|100.00%|
|:large_blue_circle:|io/questdb/griffin/FunctionParser.java|4|4|100.00%|
|:large_blue_circle:|io/questdb/griffin/SqlParser.java|7|7|100.00%|
|:large_blue_circle:|io/questdb/griffin/ExpressionParser.java|13|13|100.00%|
|:large_blue_circle:|io/questdb/griffin/SqlCompiler.java|1|1|100.00%|

**Comment by ideoma** [comment]
#### [PR Coverage check]

:heart_eyes: **pass** : 52 / 53 (98.11%)




#### file detail

|   |path|covered line|new line|coverage|
|----|----|----|----|----|
|:large_blue_circle:|io/questdb/std/GenericLexer.java|16|17|94.12%|
|:large_blue_circle:|io/questdb/griffin/PostOrderTreeTraversalAlgo.java|1|1|100.00%|
|:large_blue_circle:|io/questdb/griffin/FunctionParser.java|4|4|100.00%|
|:large_blue_circle:|io/questdb/griffin/SqlKeywords.java|10|10|100.00%|
|:large_blue_circle:|io/questdb/griffin/SqlParser.java|7|7|100.00%|
|:large_blue_circle:|io/questdb/griffin/ExpressionParser.java|13|13|100.00%|
|:large_blue_circle:|io/questdb/griffin/SqlCompiler.java|1|1|100.00%|

**Comment by ideoma** [comment]
#### [PR Coverage check]

:heart_eyes: **pass** : 52 / 53 (98.11%)




#### file detail

|   |path|covered line|new line|coverage|
|----|----|----|----|----|
|:large_blue_circle:|io/questdb/std/GenericLexer.java|16|17|94.12%|
|:large_blue_circle:|io/questdb/griffin/PostOrderTreeTraversalAlgo.java|1|1|100.00%|
|:large_blue_circle:|io/questdb/griffin/SqlKeywords.java|10|10|100.00%|
|:large_blue_circle:|io/questdb/griffin/FunctionParser.java|4|4|100.00%|
|:large_blue_circle:|io/questdb/griffin/SqlParser.java|7|7|100.00%|
|:large_blue_circle:|io/questdb/griffin/ExpressionParser.java|13|13|100.00%|
|:large_blue_circle:|io/questdb/griffin/SqlCompiler.java|1|1|100.00%|

**Comment by ideoma** [comment]
#### [PR Coverage check]

:heart_eyes: **pass** : 52 / 53 (98.11%)




#### file detail

|   |path|covered line|new line|coverage|
|----|----|----|----|----|
|:large_blue_circle:|io/questdb/std/GenericLexer.java|16|17|94.12%|
|:large_blue_circle:|io/questdb/griffin/PostOrderTreeTraversalAlgo.java|1|1|100.00%|
|:large_blue_circle:|io/questdb/griffin/FunctionParser.java|4|4|100.00%|
|:large_blue_circle:|io/questdb/griffin/SqlKeywords.java|10|10|100.00%|
|:large_blue_circle:|io/questdb/griffin/SqlParser.java|7|7|100.00%|
|:large_blue_circle:|io/questdb/griffin/ExpressionParser.java|13|13|100.00%|
|:large_blue_circle:|io/questdb/griffin/SqlCompiler.java|1|1|100.00%|

**Comment by ideoma** [comment]
#### [PR Coverage check]

:heart_eyes: **pass** : 52 / 53 (98.11%)




#### file detail

|   |path|covered line|new line|coverage|
|----|----|----|----|----|
|:large_blue_circle:|io/questdb/std/GenericLexer.java|16|17|94.12%|
|:large_blue_circle:|io/questdb/griffin/PostOrderTreeTraversalAlgo.java|1|1|100.00%|
|:large_blue_circle:|io/questdb/griffin/SqlKeywords.java|10|10|100.00%|
|:large_blue_circle:|io/questdb/griffin/FunctionParser.java|4|4|100.00%|
|:large_blue_circle:|io/questdb/griffin/SqlParser.java|7|7|100.00%|
|:large_blue_circle:|io/questdb/griffin/ExpressionParser.java|13|13|100.00%|
|:large_blue_circle:|io/questdb/griffin/SqlCompiler.java|1|1|100.00%|

**Comment by ideoma** [comment]
#### [PR Coverage check]

:heart_eyes: **pass** : 52 / 53 (98.11%)




#### file detail

|   |path|covered line|new line|coverage|
|----|----|----|----|----|
|:large_blue_circle:|io/questdb/std/GenericLexer.java|16|17|94.12%|
|:large_blue_circle:|io/questdb/griffin/PostOrderTreeTraversalAlgo.java|1|1|100.00%|
|:large_blue_circle:|io/questdb/griffin/FunctionParser.java|4|4|100.00%|
|:large_blue_circle:|io/questdb/griffin/SqlKeywords.java|10|10|100.00%|
|:large_blue_circle:|io/questdb/griffin/SqlParser.java|7|7|100.00%|
|:large_blue_circle:|io/questdb/griffin/ExpressionParser.java|13|13|100.00%|
|:large_blue_circle:|io/questdb/griffin/SqlCompiler.java|1|1|100.00%|

**Review by bluestreak01 — APPROVED** [review]

**Pull request merged**
