### PR TITLE
fix(sql): segfault when running SAMPLE BY query with index-based filter and last/first functions

### LINKED ISSUE #4232: Segfault when running SAMPLE BY with index-based access
### To reproduce

A reproducer is to be found, so I'm going to describe the symptoms and the scenario.

DDL:
```sql
create table xx (
  d1 double,
  d2 double,
  s1 symbol index,
  s2 symbol,
  kms long,
  k timestamp
) timestamp(k) partition by day wal;
```

Query leading to segfault:
```sql
SELECT last(kms) AS k, last(d1) as d1, last(d2) as d2
FROM xx
WHERE k BETWEEN '1970-01-01T00:15:33.063Z' AND '1970-01-01T01:15:33.063Z'
  AND s1 = 'a'
  AND s2 = '0'
SAMPLE BY 10s;
```

When this query is run concurrently with intensive ingestion, a segfault may happen occasionally.

Fragments of JVM crash report:
```
#
# A fatal error has been detected by the Java Runtime Environment:
#
#  SIGSEGV (0xb) at pc=0x00007f569b02a207, pid=3895449, tid=3895486
#
# JRE version: OpenJDK Runtime Environment Temurin-17.0.7+7 (17.0.7+7) (build 17.0.7+7)
# Java VM: OpenJDK 64-Bit Server VM Temurin-17.0.7+7 (17.0.7+7, mixed mode, tiered, compressed oops, compressed class ptrs, parallel gc, linux-amd64)
# Problematic frame:
# C  [libquestdb5017929588398074597.so+0xe207]  Java_io_questdb_std_BitmapIndexUtilsNative_findFirstLastInFrame0+0x1a7
...
---------------  T H R E A D  ---------------

Current thread (0x00007f57088809f0):  JavaThread "questdb-shared-3" [_thread_in_native, id=3895486, stack(0x00007f5698a16000,0x00007f5698b17000)]

Stack: [0x00007f5698a16000,0x00007f5698b17000],  sp=0x00007f5698b14f08,  free space=1019k
Native frames: (J=compiled Java code, j=interpreted, Vv=VM code, C=native code)
C  [libquestdb5017929588398074597.so+0xe207]  Java_io_questdb_std_BitmapIndexUtilsNative_findFirstLastInFrame0+0x1a7

Java frames: (J=compiled Java code, j=interpreted, Vv=VM code)
J 2951  io.questdb.std.BitmapIndexUtilsNative.findFirstLastInFrame0(IJJJJJJJJIJJI)I io.questdb@7.3.3 (0 bytes) @ 0x00007f5700d029bd [0x00007f5700d02920+0x000000000000009d]
J 2945 c1 io.questdb.std.BitmapIndexUtilsNative.findFirstLastInFrame(IJJJJJJJJIJJI)I io.questdb@7.3.3 (55 bytes) @ 0x00007f56f95692ac [0x00007f56f95691c0+0x00000000000000ec]
J 2831 c1 io.questdb.griffin.engine.groupby.SampleByFirstLastRecordCursorFactory$SampleByFirstLastRecordCursor.getNextState(I)I io.questdb@7.3.3 (830 bytes) @ 0x00007f56f952b214 [0x00007f56f9529d20+0x00000000000014f4]
J 3085 c2 io.questdb.griffin.engine.groupby.SampleByFirstLastRecordCursorFactory$SampleByFirstLastRecordCursor.hasNext()Z io.questdb@7.3.3 (40 bytes) @ 0x00007f5700d1042c [0x00007f5700d10340+0x00000000000000ec]
J 3307 c1 io.questdb.cutlass.pgwire.PGConnectionContext.sendCursor0(Lio/questdb/cairo/sql/Record;ILio/questdb/cutlass/pgwire/PGConnectionContext$PGResumeProcessor;)V io.questdb@7.3.3 (226 bytes) @ 0x00007f56f965587c [0x00007f56f9655520+0x000000000000035c]
J 4674 c1 io.questdb.cutlass.pgwire.PGConnectionContext.sendCursor(Lio/questdb/cutlass/pgwire/PGConnectionContext$PGResumeProcessor;Lio/questdb/cutlass/pgwire/PGConnectionContext$PGResumeProcessor;Lio/questdb/cutlass/pgwire/PGConnectionContext$PGResumeProcessor;)V io.questdb@7.3.3 (55 bytes) @ 0x00007f56f931d06c [0x00007f56f931cc80+0x00000000000003ec]
J 4780 c1 io.questdb.cutlass.pgwire.PGConnectionContext$PGConnectionBatchCallback.postCompile(Lio/questdb/griffin/SqlCompiler;Lio/questdb/griffin/CompiledQuery;Ljava/lang/CharSequence;)V io.questdb@7.3.3 (265 bytes) @ 0x00007f56f96475bc [0x00007f56f9647340+0x000000000000027c]
J 4781 c1 io.questdb.griffin.SqlCompilerImpl.compileBatch(Ljava/lang/CharSequence;Lio/questdb/griffin/SqlExecutionContext;Lio/questdb/griffin/BatchCallback;)V io.questdb@7.3.3 (196 bytes) @ 0x00007f56f930aeac [0x00007f56f930a780+0x000000000000072c]
J 4816 c1 io.questdb.cutlass.pgwire.PGConnectionContext.processQuery(JJ)V io.questdb@7.3.3 (226 bytes) @ 0x00007f56f900ba54 [0x00007f56f900b2c0+0x0000000000000794]
J 3424 c1 io.questdb.cutlass.pgwire.PGConnectionContext.parse(JI)V io.questdb@7.3.3 (691 bytes) @ 0x00007f56f968bf2c [0x00007f56f968abc0+0x000000000000136c]
J 3709 c1 io.questdb.cutlass.pgwire.PGConnectionContext.handleClientOperation(I)V io.questdb@7.3.3 (410 bytes) @ 0x00007f56f9711b3c [0x00007f56f9711260+0x00000000000008dc]
J 3708 c1 io.questdb.cutlass.pgwire.PGWireServer$1.lambda$$0(ILio/questdb/cutlass/pgwire/PGConnectionContext;)Z io.questdb@7.3.3 (194 bytes) @ 0x00007f56f971e97c [0x00007f56f971e700+0x000000000000027c]
J 3707 c1 io.questdb.cutlass.pgwire.PGWireServer$1$$Lambda$397+0x000000080027c778.onRequest(ILio/questdb/network/IOContext;)Z io.questdb@7.3.3 (13 bytes) @ 0x00007f56f970e3ac [0x00007f56f970e240+0x000000000000016c]
J 2592 c2 io.questdb.cutlass.pgwire.PGWireServer$1.run(ILio/questdb/mp/Job$RunStatus;)Z io.questdb@7.3.3 (74 bytes) @ 0x00007f5700cc0854 [0x00007f5700cc04e0+0x0000000000000374]
J 2167% c2 io.questdb.mp.Worker.run()V io.questdb@7.3.3 (557 bytes) @ 0x00007f5700c8b238 [0x00007f5700c8b160+0x00000000000000d8]
v  ~StubRoutines::call_stub

siginfo: si_signo: 11 (SIGSEGV), si_code: 1 (SEGV_MAPERR), si_addr: 0x00007f55051e8088
...
7f5505152000-7f55051e8000 r--s 00000000 fd:11 39977379                   /data/home/data/questdb/data/db/xx~5/2024-02-22.752332/timestamp.d
```

Notice `0x00007f55051e8088` accessed address leading to the segfault. This address is very close to the upper boundary of the `timestamp.d` mmapped file, so very likely that `Java_io_questdb_std_BitmapIndexUtilsNative_findFirstLastInFrame0` accessed timestamp memory out of range.

### QuestDB version:

7.3.3

### OS, in case of Docker specify Docker and the Host OS:

Alibaba Cloud Linux

### File System, in case of Docker specify Host File System:

ext4

### Full Name:

Andrei Pechkurov

### Affiliation:

QuestDB

### Have you followed Linux, MacOs kernel configuration steps to increase Maximum open files and Maximum virtual memory areas limit?

- [X] Yes, I have

### Additional context

_No response_

### PR DESCRIPTION
**Pull request by puzpuzpuz**
Fixes #4232

### CODE REVIEW

**Comment by ideoma** [comment]
#### [PR Coverage check]


:heart_eyes: **pass** : 0 / 0 (0%)

**Comment by puzpuzpuz** [comment]
@ideoma Eugene told that you wrote `findFirstLastInFrame0`. Could you review this one when you have the time? It's not urgent.

**Comment by ideoma** [comment]
#### [PR Coverage check]

:heart_eyes: **pass** : 10 / 10 (100.00%)




#### file detail

|   |path|covered line|new line|coverage|
|----|----|----|----|----|
|:large_blue_circle:|io/questdb/griffin/engine/groupby/SampleByFirstLastRecordCursorFactory.java|10|10|100.00%|

**Review by ideoma — COMMENTED** [review]
Can you please revert the binaries update or update them for every platform?

**Comment by ideoma** [comment]
#### [PR Coverage check]

:heart_eyes: **pass** : 10 / 10 (100.00%)




#### file detail

|   |path|covered line|new line|coverage|
|----|----|----|----|----|
|:large_blue_circle:|io/questdb/griffin/engine/groupby/SampleByFirstLastRecordCursorFactory.java|10|10|100.00%|

**Review by ideoma — APPROVED** [review]

**Pull request merged**
