### PR TITLE
fix(log): fix the way `env` variables are picked up for purpose of configuring the logger

### PR DESCRIPTION
**Pull request by bluestreak01**
Added `stderr` output to verify that `env` variables are being applied to the logger configuration.

Most changes are code reformatting, the actual change is one line.

```
╭─vladilyushchenko at m1pro in ~/dev/questdb/core on vi_log_env✔
╰─± QDB_LOG_W_STDOUT_LEVEL=DEBUG  java -p target/questdb-6.5.5-SNAPSHOT.jar -m io.questdb/io.questdb.ServerMain -d ~/tmp/qdbtest 
Created log directory: /Users/vladilyushchenko/tmp/qdbtest/log
    Using env: QDB_LOG_W_STDOUT_LEVEL=DEBUG
Log configuration loaded from default internal file.
2022-11-04T20:33:29.737389Z D i.q.c.TableUtils open [file=/Users/vladilyushchenko/tmp/qdbtest/db/_tab_index.d, fd=9]
2022-11-04T20:33:32.156699Z D i.q.c.TableUtils open [file=/Users/vladilyushchenko/tmp/qdbtest/db/_tab_index.d, fd=8]
2022-11-04T20:33:32.164408Z D i.q.c.TableUtils open [file=/Users/vladilyushchenko/tmp/qdbtest/db/_upgrade.d, fd=9]
2022-11-04T20:33:32.164434Z D i.q.c.m.EngineMigration open [fd=9, path=/Users/vladilyushchenko/tmp/qdbtest/db/_upgrade.d]
```

Closes https://github.com/questdb/questdb/pull/2577

### What is in this PR:

- we log file name, which we use to configure the logger
- if logger configuration picks up any env variables for purpose of using their values, names of these variables are logged into `stderr`
- servermain will copy logger conf file from the resources _before_ configuring logger, thus making logger pick up env variables at the first start and all subsequent starts

### CODE REVIEW

**Comment by ideoma** [comment]
#### [PR Coverage check]

:heart_eyes: **pass** : 171 / 188 (90.96%)




#### file detail

|   |path|covered line|new line|coverage|
|----|----|----|----|----|
|:large_blue_circle:|io/questdb/log/LogFactory.java|169|186|90.86%|
|:large_blue_circle:|io/questdb/cairo/vm/MemoryCARWImpl.java|2|2|100.00%|

**Comment by ideoma** [comment]
#### [PR Coverage check]

:heart_eyes: **pass** : 171 / 188 (90.96%)




#### file detail

|   |path|covered line|new line|coverage|
|----|----|----|----|----|
|:large_blue_circle:|io/questdb/log/LogFactory.java|169|186|90.86%|
|:large_blue_circle:|io/questdb/cairo/vm/MemoryCARWImpl.java|2|2|100.00%|

**Comment by ideoma** [comment]
#### [PR Coverage check]

:heart_eyes: **pass** : 249 / 288 (86.46%)




#### file detail

|   |path|covered line|new line|coverage|
|----|----|----|----|----|
|:large_blue_circle:|io/questdb/Bootstrap.java|78|100|78.00%|
|:large_blue_circle:|io/questdb/log/LogFactory.java|169|186|90.86%|
|:large_blue_circle:|io/questdb/cairo/vm/MemoryCARWImpl.java|2|2|100.00%|

**Comment by bluestreak01** [comment]
works with docker:

image

**Review by sklarsa — APPROVED** [review]

**Comment by ideoma** [comment]
#### [PR Coverage check]

:heart_eyes: **pass** : 261 / 296 (88.18%)




#### file detail

|   |path|covered line|new line|coverage|
|----|----|----|----|----|
|:large_blue_circle:|io/questdb/Bootstrap.java|90|108|83.33%|
|:large_blue_circle:|io/questdb/log/LogFactory.java|169|186|90.86%|
|:large_blue_circle:|io/questdb/cairo/vm/MemoryCARWImpl.java|2|2|100.00%|

**Pull request merged**
