### PR TITLE
fix(sql): fix non-existing symbol bind variable initialization in indexed filter queries

### PR DESCRIPTION
**Pull request by puzpuzpuz**
Symbol key was not correctly initialized in `DeferredSymbolIndexRowCursorFactory` in case of non-existing symbols.

### Reproducer

```sql
CREATE TABLE 'one_min' (
  ticker SYMBOL capacity 256 CACHE index capacity 256,
  open INT,
  high INT,
  low INT,
  close INT,
  time TIMESTAMP
) TIMESTAMP (time) PARTITION BY YEAR WAL;

INSERT INTO one_min VALUES ('x', 1, 1, 1, 1, now());
```

Then `SELECT * FROM one_min WHERE ticker = ?;` query can be run for `x` and `foobar` (non-exiting) symbol values. The second execution would wrongly return results for the `x` symbol.

### CODE REVIEW

**Review by ideoma — DISMISSED** [review]

**Comment by ideoma** [comment]
#### [PR Coverage check]

:heart_eyes: **pass** : 3 / 3 (100.00%)




#### file detail

|   |path|covered line|new line|coverage|
|----|----|----|----|----|
|:large_blue_circle:|io/questdb/griffin/engine/table/DeferredSymbolIndexRowCursorFactory.java|3|3|100.00%|

**Comment by puzpuzpuz** [comment]
@ideoma thanks for the quick review. Could you take another look? I've added non-existent symbol cases for other symbol filters, like `sym != ?` and `sym in (?, ?)`: 955c63de418e60ac9dc5a4d797284e4d187b5d26

**Comment by ideoma** [comment]
#### [PR Coverage check]

:heart_eyes: **pass** : 3 / 3 (100.00%)




#### file detail

|   |path|covered line|new line|coverage|
|----|----|----|----|----|
|:large_blue_circle:|io/questdb/griffin/engine/table/DeferredSymbolIndexRowCursorFactory.java|3|3|100.00%|

**Comment by ideoma** [comment]
#### [PR Coverage check]

:heart_eyes: **pass** : 3 / 3 (100.00%)




#### file detail

|   |path|covered line|new line|coverage|
|----|----|----|----|----|
|:large_blue_circle:|io/questdb/griffin/engine/table/DeferredSymbolIndexRowCursorFactory.java|3|3|100.00%|

**Pull request merged**
