### PR TITLE
chore(core): fix mixup of 401 and 403

### PR DESCRIPTION
**Pull request by glasstiger**
small fix for bug introduced in https://github.com/questdb/questdb/pull/5078

PR title is chore, because bug has not been released, so no user can be impacted.

### CODE REVIEW

**Comment by glasstiger** [comment]
#### [PR Coverage check]

:disappointed: **fail** : 0 / 1 (00.00%)




#### file detail

|   |path|covered line|new line|coverage|
|----|----|----|----|----|
|:large_blue_circle:|io/questdb/cutlass/http/processors/JsonQueryProcessor.java|0|1|00.00%|

**Comment by bluestreak01** [comment]
can we have a test?

**Comment by glasstiger** [comment]
#### [PR Coverage check]

:heart_eyes: **pass** : 12 / 12 (100.00%)




#### file detail

|   |path|covered line|new line|coverage|
|----|----|----|----|----|
|:large_blue_circle:|io/questdb/cutlass/http/processors/JsonQueryProcessor.java|1|1|100.00%|
|:large_blue_circle:|io/questdb/FactoryProviderImpl.java|1|1|100.00%|
|:large_blue_circle:|io/questdb/griffin/engine/functions/catalogue/SimulateCrashFunctionFactory.java|10|10|100.00%|

**Review by bluestreak01 — APPROVED** [review]

**Comment by bluestreak01** [comment]
@glasstiger does this work with the Web Console?

**Comment by glasstiger** [comment]
> @glasstiger does this work with the Web Console?

yes, it works.

**Pull request merged**
