### PR TITLE
style(core): code formatting

### PR DESCRIPTION
**Pull request by glasstiger**
- fix code formatting issues
- added @ formatter:off to Numbers.java (works with intellij default settings only)

### CODE REVIEW

**Comment by questdb-butler** [comment]
<table>
  <thead>
    <tr>
      <th width="50"></th>
      <th width="100%" data-danger-table="true">Fails</th>
    </tr>
  </thead>
  <tbody><tr>
      <td>:no_entry_sign:</td>
      <td>

  Please update the PR title to match this format:
`type(subType): description`

Where `type` is one of:
`feat`, `fix`, `chore`, `docs`, `style`, `refactor`, `perf`, `test`, `ci`, `chore`, `revert`

And: `subType` is one of:
`build`, `sql`, `log`, `mig`, `core`, `ilp`, `pgwire`, `http`, `conf`, `ui`, `wal`

For Example:

```
perf(sql): improve pattern matching performance for SELECT sub-queries
```
  </td>
    </tr>
  </tbody>
</table>




<p align="right">
  Generated by :no_entry_sign: <a href="https://danger.systems/js">dangerJS</a> against fa8e2dc76653db53a4c4a1ed57cdb05e7335e31e
</p>

**Comment by ideoma** [comment]
#### [PR Coverage check]

:heart_eyes: **pass** : 11 / 11 (100.00%)




#### file detail

|   |path|covered line|new line|coverage|
|----|----|----|----|----|
|:large_blue_circle:|io/questdb/griffin/engine/functions/str/TrimFunction.java|5|5|100.00%|
|:large_blue_circle:|io/questdb/cairo/wal/WalEventReader.java|1|1|100.00%|
|:large_blue_circle:|io/questdb/jit/CompiledFilterIRSerializer.java|1|1|100.00%|
|:large_blue_circle:|io/questdb/std/Chars.java|1|1|100.00%|
|:large_blue_circle:|io/questdb/cutlass/http/processors/TextQueryProcessorState.java|1|1|100.00%|
|:large_blue_circle:|io/questdb/griffin/model/IntervalUtils.java|1|1|100.00%|
|:large_blue_circle:|io/questdb/cutlass/pgwire/PGConnectionContext.java|1|1|100.00%|

**Comment by questdb-butler** [comment]
<table>
  <thead>
    <tr>
      <th width="50"></th>
      <th width="100%" data-danger-table="true">Fails</th>
    </tr>
  </thead>
  <tbody><tr>
      <td>:no_entry_sign:</td>
      <td>

  Please update the PR title to match this format:
`type(subType): description`

Where `type` is one of:
`feat`, `fix`, `chore`, `docs`, `style`, `refactor`, `perf`, `test`, `ci`, `chore`, `revert`

And: `subType` is one of:
`build`, `sql`, `log`, `mig`, `core`, `ilp`, `pgwire`, `http`, `conf`, `ui`, `wal`

For Example:

```
perf(sql): improve pattern matching performance for SELECT sub-queries
```
  </td>
    </tr>
  </tbody>
</table>




<p align="right">
  Generated by :no_entry_sign: <a href="https://danger.systems/js">dangerJS</a> against fa8e2dc76653db53a4c4a1ed57cdb05e7335e31e
</p>

**Review by bluestreak01 — APPROVED** [review]

**Comment by ideoma** [comment]
#### [PR Coverage check]

:heart_eyes: **pass** : 11 / 11 (100.00%)




#### file detail

|   |path|covered line|new line|coverage|
|----|----|----|----|----|
|:large_blue_circle:|io/questdb/griffin/engine/functions/str/TrimFunction.java|5|5|100.00%|
|:large_blue_circle:|io/questdb/cairo/wal/WalEventReader.java|1|1|100.00%|
|:large_blue_circle:|io/questdb/jit/CompiledFilterIRSerializer.java|1|1|100.00%|
|:large_blue_circle:|io/questdb/std/Chars.java|1|1|100.00%|
|:large_blue_circle:|io/questdb/cutlass/http/processors/TextQueryProcessorState.java|1|1|100.00%|
|:large_blue_circle:|io/questdb/griffin/model/IntervalUtils.java|1|1|100.00%|
|:large_blue_circle:|io/questdb/cutlass/pgwire/PGConnectionContext.java|1|1|100.00%|

**Pull request merged**
