### PR TITLE
Implicitly cast Symbols to Strings

### LINKED ISSUE #1056: Automatically cast Symbol columns to String when calling a function which accepts String
**Is your feature request related to a problem? Please describe.**
A number of functions like to_str, dateadd etc works with String arguments but does not work with Symbol even though it is very similar data type

**Describe the solution you'd like**
Implicitly cast Symbols to Strings on the function calls

**Describe alternatives you've considered**
Manual CAST(sym as String) is possible but confusing

### PR DESCRIPTION
**Pull request by eugenels**
closes #1056

### CODE REVIEW

**Comment by ideoma** [comment]
#### [PR Coverage check]

:disappointed: **fail** : 1 / 8 (12.50%)




#### file detail

|   |path|covered line|new line|coverage|
|----|----|----|----|----|
|:large_blue_circle:|io/questdb/griffin/engine/functions/constants/SymbolConstant.java|0|4|00.00%|
|:large_blue_circle:|io/questdb/griffin/engine/functions/columns/SymbolColumn.java|1|4|25.00%|

**Comment by ideoma** [comment]
#### [PR Coverage check]

:disappointed: **fail** : 6 / 13 (46.15%)




#### file detail

|   |path|covered line|new line|coverage|
|----|----|----|----|----|
|:large_blue_circle:|io/questdb/griffin/engine/functions/constants/SymbolConstant.java|0|4|00.00%|
|:large_blue_circle:|io/questdb/griffin/engine/functions/columns/SymbolColumn.java|1|4|25.00%|
|:large_blue_circle:|io/questdb/griffin/SqlCodeGenerator.java|5|5|100.00%|

**Comment by ideoma** [comment]
#### [PR Coverage check]

:heart_eyes: **pass** : 15 / 21 (71.43%)




#### file detail

|   |path|covered line|new line|coverage|
|----|----|----|----|----|
|:large_blue_circle:|io/questdb/griffin/engine/functions/constants/SymbolConstant.java|1|4|25.00%|
|:large_blue_circle:|io/questdb/griffin/engine/functions/columns/SymbolColumn.java|1|4|25.00%|
|:large_blue_circle:|io/questdb/griffin/FunctionParser.java|7|7|100.00%|
|:large_blue_circle:|io/questdb/griffin/WhereClauseParser.java|1|1|100.00%|
|:large_blue_circle:|io/questdb/griffin/SqlCodeGenerator.java|5|5|100.00%|

**Review by ideoma — APPROVED** [review]

**Comment by ideoma** [comment]
#### [PR Coverage check]

:heart_eyes: **pass** : 15 / 21 (71.43%)




#### file detail

|   |path|covered line|new line|coverage|
|----|----|----|----|----|
|:large_blue_circle:|io/questdb/griffin/engine/functions/constants/SymbolConstant.java|1|4|25.00%|
|:large_blue_circle:|io/questdb/griffin/engine/functions/columns/SymbolColumn.java|1|4|25.00%|
|:large_blue_circle:|io/questdb/griffin/FunctionParser.java|7|7|100.00%|
|:large_blue_circle:|io/questdb/griffin/WhereClauseParser.java|1|1|100.00%|
|:large_blue_circle:|io/questdb/griffin/SqlCodeGenerator.java|5|5|100.00%|

**Comment by ideoma** [comment]
#### [PR Coverage check]

:heart_eyes: **pass** : 15 / 21 (71.43%)




#### file detail

|   |path|covered line|new line|coverage|
|----|----|----|----|----|
|:large_blue_circle:|io/questdb/griffin/engine/functions/constants/SymbolConstant.java|1|4|25.00%|
|:large_blue_circle:|io/questdb/griffin/engine/functions/columns/SymbolColumn.java|1|4|25.00%|
|:large_blue_circle:|io/questdb/griffin/FunctionParser.java|7|7|100.00%|
|:large_blue_circle:|io/questdb/griffin/WhereClauseParser.java|1|1|100.00%|
|:large_blue_circle:|io/questdb/griffin/SqlCodeGenerator.java|5|5|100.00%|

**Comment by ideoma** [comment]
#### [PR Coverage check]

:heart_eyes: **pass** : 15 / 21 (71.43%)




#### file detail

|   |path|covered line|new line|coverage|
|----|----|----|----|----|
|:large_blue_circle:|io/questdb/griffin/engine/functions/constants/SymbolConstant.java|1|4|25.00%|
|:large_blue_circle:|io/questdb/griffin/engine/functions/columns/SymbolColumn.java|1|4|25.00%|
|:large_blue_circle:|io/questdb/griffin/FunctionParser.java|7|7|100.00%|
|:large_blue_circle:|io/questdb/griffin/WhereClauseParser.java|1|1|100.00%|
|:large_blue_circle:|io/questdb/griffin/SqlCodeGenerator.java|5|5|100.00%|

**Comment by ideoma** [comment]
#### [PR Coverage check]

:heart_eyes: **pass** : 15 / 21 (71.43%)




#### file detail

|   |path|covered line|new line|coverage|
|----|----|----|----|----|
|:large_blue_circle:|io/questdb/griffin/engine/functions/constants/SymbolConstant.java|1|4|25.00%|
|:large_blue_circle:|io/questdb/griffin/engine/functions/columns/SymbolColumn.java|1|4|25.00%|
|:large_blue_circle:|io/questdb/griffin/FunctionParser.java|7|7|100.00%|
|:large_blue_circle:|io/questdb/griffin/WhereClauseParser.java|1|1|100.00%|
|:large_blue_circle:|io/questdb/griffin/SqlCodeGenerator.java|5|5|100.00%|

**Comment by ideoma** [comment]
#### [PR Coverage check]

:heart_eyes: **pass** : 15 / 15 (100.00%)




#### file detail

|   |path|covered line|new line|coverage|
|----|----|----|----|----|
|:large_blue_circle:|io/questdb/griffin/FunctionParser.java|7|7|100.00%|
|:large_blue_circle:|io/questdb/griffin/engine/functions/SymbolFunction.java|2|2|100.00%|
|:large_blue_circle:|io/questdb/griffin/WhereClauseParser.java|1|1|100.00%|
|:large_blue_circle:|io/questdb/griffin/SqlCodeGenerator.java|5|5|100.00%|

**Review by bluestreak01 — APPROVED** [review]

**Comment by ideoma** [comment]
#### [PR Coverage check]

:heart_eyes: **pass** : 15 / 15 (100.00%)




#### file detail

|   |path|covered line|new line|coverage|
|----|----|----|----|----|
|:large_blue_circle:|io/questdb/griffin/FunctionParser.java|7|7|100.00%|
|:large_blue_circle:|io/questdb/griffin/engine/functions/SymbolFunction.java|2|2|100.00%|
|:large_blue_circle:|io/questdb/griffin/WhereClauseParser.java|1|1|100.00%|
|:large_blue_circle:|io/questdb/griffin/SqlCodeGenerator.java|5|5|100.00%|

**Pull request merged**
