### PR TITLE
chore(core): replace the pinsrq instruction with vpinsrq

### PR DESCRIPTION
**Pull request by mtopolnik**
In our AVX2 JIT code, we use the SSE instruction `pinsrq`. It is dangerous for performance to mix SSE instructions with AVX2 as on some chips (both Intel and AMD) every transition from one to the other can costs dozens of CPU cycles.

On the EC2 instance where I benchmarked this, there's no perf difference, but it is nevertheless a good idea to do this "by the book" and use the appropriate `vpinsrq` instruction instead.

### CODE REVIEW

**Review by puzpuzpuz — DISMISSED** [review]

**Comment by mtopolnik** [comment]
`libquestdbr.so` seems to be empty now. Maybe the Rebuild Native Binaries action doesn't work correctly?

**Comment by puzpuzpuz** [comment]
Looks like this change broke several things like `java.lang.UnsatisfiedLinkError` on mac. Could you check?

**Comment by bluestreak01** [comment]
the build should be fixed with https://github.com/questdb/questdb/pull/4448

**Comment by mtopolnik** [comment]
There's also an actual test failure and it's very easy to reproduce. When a NULL value appears at positions 1 or 2 of the four qwords loaded in the AVX2 loop, and others are non-null, then this NULL is not detected and passes as not-null.

**Review by bluestreak01 — APPROVED** [review]

**Pull request merged**
