### PR TITLE
fix(sql): unhandled ArrayIndexOutOfBoundsException in ASOF and LT JOIN on empty table

### LINKED ISSUE #3301: ArrayIndexOutOfBoundsException in ASOF JOIN query
### Describe the bug

```sql
create table t1 as (select x as id, cast(x as timestamp) ts from long_sequence(10)) timestamp(ts) partition by day;
create table t2 as (select x as id, cast(x as timestamp) ts from long_sequence(10)) timestamp(ts) partition by day;
create table t3 (id long, ts timestamp) timestamp(ts) partition by day;

SELECT *
FROM (
  (t1 INNER JOIN t2 ON id) 
  ASOF JOIN t3 ON id
);
```

The query gives an error:
```
2023-05-04T08:03:56.337251Z C i.q.c.h.p.JsonQueryProcessorState [131] Uh-oh. Error!
java.lang.ArrayIndexOutOfBoundsException
```

### To reproduce

_No response_

### Expected Behavior

_No response_

### Environment

```markdown
- **QuestDB version**:
- **OS**:
- **Browser**:
```

### Additional context

_No response_

### PR DESCRIPTION
**Pull request by puzpuzpuz**
Fixes #3301

### CODE REVIEW

**Comment by ideoma** [comment]
#### [PR Coverage check]

:heart_eyes: **pass** : 6 / 6 (100.00%)




#### file detail

|   |path|covered line|new line|coverage|
|----|----|----|----|----|
|:large_blue_circle:|io/questdb/griffin/engine/join/LtJoinLightRecordCursorFactory.java|3|3|100.00%|
|:large_blue_circle:|io/questdb/griffin/engine/join/AsOfJoinLightRecordCursorFactory.java|3|3|100.00%|

**Comment by jerrinot** [comment]
If I understand the problem well, it's caused by the fact the `record.getRowId()` has undefined behaviour when the `Record` does not point to anything, because there was no `cursor.hasNext()` returning `true` called. Is that right? 

Do you think it would make sense to define the `getRow()` contract that way? currently, it says this:
```java
    /**
     * Gets the numeric ID of this row. This can be not real table row id
     *
     * @return numeric ID of the current row
     */
```
how about:
```java
    /**
     * Gets the numeric ID of this row. This can be not real table row id. 
     *
     * @return numeric ID of the current row or Long.LONG_NaN when the record is not associated with a valid row. 
     */
```

Or do you think `LONG_NaN` could be used to represent an actual row?

**Comment by puzpuzpuz** [comment]
> Do you think it would make sense to define the `getRow()` contract that way?

To me, `getRowId()` contact should be the same as for `getStr(int)` or any other column accessor method, i.e. it should be called only when the record is initialized with a previous `hasNext()` call that returned `true`. Introducing a special contract for `getRowId()` only would make the `Record` API less consistent.

@jerrinot WDYT?

**Comment by jerrinot** [comment]
@puzpuzpuz that's a good point. 

I thought the `getRowId()` was more meta-method than e.g `getStr()` and thus it should always return a well-defined result. but I understand your view too.

**Review by jerrinot — APPROVED** [review]

**Comment by puzpuzpuz** [comment]
@jerrinot thanks for the review!

**Pull request merged**
