### PR TITLE
Replace io.questdb.std.ThreadLocal usages with standard java.lang.ThreadLocal

### PR DESCRIPTION
**Pull request by pivovarit**
Looks like `io.questdb.std.ThreadLocal` was introduced only to provide one extra functionality which is already available: `java.lang.ThreadLocal#withInitial`.

Same value, but with slightly smaller maintenance costs!

### CODE REVIEW

**Comment by puzpuzpuz** [comment]
A rather random note: a custom `ThreadLocal` implementation may be valuable in future. Since we spin and control all of the threads, we could implement something similar to Netty's [FastThreadLocal](https://github.com/netty/netty/blob/1ecc053e70d57a8da70bf23bf5293b2072337b09/common/src/main/java/io/netty/util/concurrent/FastThreadLocal.java). The idea is to use index-based access on an array instead of a hash map. This saves some CPU cycles spent on `ThreadLocal#get()`.

**Comment by pivovarit** [comment]
Agreed! It's nice to hear that you actually care about optimizations like this!

Been wondering... why are thread locals used for storing exception instances? ([example](https://github.com/pivovarit/questdb/blob/a0669042d2c5766906b93b8065aa46f6ba021993/core/src/main/java/io/questdb/cairo/CairoException.java#L37)) I see that exceptions are already stackless, but wouldn't it be more performant if there was just a single static instance?

**Comment by puzpuzpuz** [comment]
> EDIT: I see that `errno` is actually mutated, so I guess keeping it thread-scoped is a must indeed.

Yes, that's the case. Exception objects are kept thread-local and reused to avoid allocations. There are some downsides, of course, but that's the price of being zero* GC.

* Obviously, zero makes sense and stands for hot path only ;)

**Comment by bluestreak01** [comment]
I'm assuming this PR is no longer needed? Do reopen if this is not the case

**Pull request closed without merging**
