### PR TITLE
fix(cairo): fix reader and txn scoreboard leak

### PR DESCRIPTION
**Pull request by ideoma**
Fix `txn_scoreboard` leak which eventually leads to all SELECT queries being locked with `max txn-inflight limit reached` error.

Problem happens when `TableReader` is taken from the pool, it re-reads transaction and fails to reload partitions. If failure happens at this point scoreboard is not released and reader is kept locked out of the pool.

Failure to release partition structure is quite likely on busy read/write system because of flaw in O3 purge partition logic which to be fixed separately.

### CODE REVIEW

**Comment by ideoma** [comment]
#### [PR Coverage check]

:heart_eyes: **pass** : 11 / 11 (100.00%)




#### file detail

|   |path|covered line|new line|coverage|
|----|----|----|----|----|
|:large_blue_circle:|io/questdb/cairo/TableReader.java|6|6|100.00%|
|:large_blue_circle:|io/questdb/cairo/pool/ReaderPool.java|5|5|100.00%|

**Comment by ideoma** [comment]
#### [PR Coverage check]

:heart_eyes: **pass** : 11 / 11 (100.00%)




#### file detail

|   |path|covered line|new line|coverage|
|----|----|----|----|----|
|:large_blue_circle:|io/questdb/cairo/TableReader.java|6|6|100.00%|
|:large_blue_circle:|io/questdb/cairo/pool/ReaderPool.java|5|5|100.00%|

**Comment by ideoma** [comment]
#### [PR Coverage check]

:heart_eyes: **pass** : 11 / 11 (100.00%)




#### file detail

|   |path|covered line|new line|coverage|
|----|----|----|----|----|
|:large_blue_circle:|io/questdb/cairo/TableReader.java|6|6|100.00%|
|:large_blue_circle:|io/questdb/cairo/pool/ReaderPool.java|5|5|100.00%|

**Review by bluestreak01 — APPROVED** [review]

**Comment by ideoma** [comment]
#### [PR Coverage check]

:heart_eyes: **pass** : 11 / 11 (100.00%)




#### file detail

|   |path|covered line|new line|coverage|
|----|----|----|----|----|
|:large_blue_circle:|io/questdb/cairo/TableReader.java|6|6|100.00%|
|:large_blue_circle:|io/questdb/cairo/pool/ReaderPool.java|5|5|100.00%|

**Comment by ideoma** [comment]
#### [PR Coverage check]

:heart_eyes: **pass** : 11 / 11 (100.00%)




#### file detail

|   |path|covered line|new line|coverage|
|----|----|----|----|----|
|:large_blue_circle:|io/questdb/cairo/TableReader.java|6|6|100.00%|
|:large_blue_circle:|io/questdb/cairo/pool/ReaderPool.java|5|5|100.00%|

**Comment by ideoma** [comment]
#### [PR Coverage check]

:heart_eyes: **pass** : 11 / 11 (100.00%)




#### file detail

|   |path|covered line|new line|coverage|
|----|----|----|----|----|
|:large_blue_circle:|io/questdb/cairo/TableReader.java|6|6|100.00%|
|:large_blue_circle:|io/questdb/cairo/pool/ReaderPool.java|5|5|100.00%|

**Pull request merged**
