### PR TITLE
fix(sql): fix symbol value comparison with <, <=, >, >= operators

### LINKED ISSUE #3828: Incorrect results with symbol comparison
### Describe the bug

Query:
`select c_0>'Z' from test where c_0>'Z';`
Result:
`False`

If `c_0>'Z'` is False, then there should be no result.

### To reproduce

```
create table test (c_0 symbol);
insert into test values ('A');
select c_0>'Z' from test where c_0>'Z';
```

### Expected Behavior

It should return empty results.

### Environment

```markdown
- **QuestDB version**: 7.3.3
```

### Additional context

_No response_

### PR DESCRIPTION
**Pull request by bziobrowski**
Fixes #3828 

PR rejects <, <=, >, >= operator serialization with symbol arguments because they require string value comparison and JIT doesn't handle string types yet.

### CODE REVIEW

**Comment by ideoma** [comment]
#### [PR Coverage check]

:heart_eyes: **pass** : 11 / 11 (100.00%)




#### file detail

|   |path|covered line|new line|coverage|
|----|----|----|----|----|
|:large_blue_circle:|io/questdb/jit/CompiledFilterIRSerializer.java|9|9|100.00%|
|:large_blue_circle:|io/questdb/griffin/engine/functions/lt/LtStrFunctionFactory.java|2|2|100.00%|

**Review by jerrinot — APPROVED** [review]
good fix

**Comment by jerrinot** [comment]
@bziobrowski I was thinking about this test:
```java
    @Test
    public void testSymbolComparisons() throws Exception {
        serialize("asymbol = asymbol");
        assertIR("different results for asymbol", "(i32 asymbol)(i32 asymbol)(=)(ret)");

        serialize("asymbol != asymbol");
        assertIR("different results for asymbol", "(i32 asymbol)(i32 asymbol)(<>)(ret)");

        String[] invalidSymbolComparisons = {">", ">=", "<", "<="};
        for (String op : invalidSymbolComparisons) {
            try {
                serialize("asymbol " + op + " asymbol");
                Assert.fail("expected exception, JIT does not support operator: " + op + " on symbols");
            } catch (SqlException e) {
                TestUtils.assertEquals("operator: " + op + " is not supported for SYMBOL type", e.getFlyweightMessage());
            }
        }
    }
```
Let me know if that's OK to push it. Alternatively, feel free to push it yourself (so GH still allows me to review this PR). Alternatively, feel free to tel me the test is pointless :) The idea behind this more fine-grained test: Have a test which fails regardless of the architecture it's running on. The integration test you are adding won't fail on ARM (Mac).

**Comment by ideoma** [comment]
#### [PR Coverage check]

:heart_eyes: **pass** : 11 / 11 (100.00%)




#### file detail

|   |path|covered line|new line|coverage|
|----|----|----|----|----|
|:large_blue_circle:|io/questdb/jit/CompiledFilterIRSerializer.java|9|9|100.00%|
|:large_blue_circle:|io/questdb/griffin/engine/functions/lt/LtStrFunctionFactory.java|2|2|100.00%|

**Pull request merged**
