### PR TITLE
fix(sql): internal error when inserting null string as a designated timestamp

### LINKED ISSUE #4407: Internal error when inserting a null string into a designated timestamp column
### To reproduce

1. create a table: `create table str_timestamps (s string, ts timestamp) timestamp(ts) partition by day wal;`
2. Insert a null string a timestamp `insert into str_timestamps values (null, null::string);` via the REST interface
3. watch log
```
2024-04-16T10:14:51.242218Z C i.q.c.h.p.JsonQueryProcessorState [107] internal error [ex=
java.lang.NullPointerException: Cannot invoke "java.lang.CharSequence.length()" because "seq" is null
	at io.questdb.griffin.model.IntervalUtils.parseFloorPartialTimestamp(IntervalUtils.java:522)
	at io.questdb.griffin.SqlUtil.parseFloorPartialTimestamp(SqlUtil.java:811)
	at io.questdb.griffin.InsertRowImpl.getRowWithStringTimestamp(InsertRowImpl.java:79)
	at io.questdb.griffin.InsertRowImpl.append(InsertRowImpl.java:64)
	at io.questdb.griffin.engine.ops.InsertOperationImpl$InsertMethodImpl.execute(InsertOperationImpl.java:156)
	at io.questdb.griffin.engine.ops.InsertOperationImpl.execute(InsertOperationImpl.java:106)
	at io.questdb.cutlass.http.processors.JsonQueryProcessor.executeInsert(JsonQueryProcessor.java:540)
	at io.questdb.cutlass.http.processors.JsonQueryProcessor.compileAndExecuteQuery(JsonQueryProcessor.java:460)
	at io.questdb.cutlass.http.processors.JsonQueryProcessor.execute0(JsonQueryProcessor.java:193)
	at io.questdb.cutlass.http.processors.JsonQueryProcessor.onRequestComplete(JsonQueryProcessor.java:262)
	at io.questdb.cutlass.http.HttpConnectionContext.handleClientRecv(HttpConnectionContext.java:919)
	at io.questdb.cutlass.http.HttpConnectionContext.handleClientOperation(HttpConnectionContext.java:260)
[...]
```

### QuestDB version:

7.4.1-snapshot

### OS, in case of Docker specify Docker and the Host OS:

macos, arm

### File System, in case of Docker specify Host File System:

irrelevant

### Full Name:

Jaromir Hamala

### Affiliation:

QuestDB

### Have you followed Linux, MacOs kernel configuration steps to increase Maximum open files and Maximum virtual memory areas limit?

- [X] Yes, I have

### Additional context

_No response_

### PR DESCRIPTION
**Pull request by jerrinot**
fixes #4407

- [x] Validate that constants returning `true` on `isNullConstant()` won't break anything
- [x] Check that a non-constant string cannot make it into `InsertRowImpl` - maybe a string function returning null?

This PR also makes inserting varchar timestamps consistent with string timestamps. Before this change VARCHAR timestamps were treated as micros since the epoch. Now they are treated as timestamps. This makes it consistent with string.

### CODE REVIEW

**Comment by ideoma** [comment]
#### [PR Coverage check]

:heart_eyes: **pass** : 28 / 29 (96.55%)




#### file detail

|   |path|covered line|new line|coverage|
|----|----|----|----|----|
|:large_blue_circle:|io/questdb/griffin/SqlCompilerImpl.java|5|6|83.33%|
|:large_blue_circle:|io/questdb/griffin/engine/functions/constants/SymbolConstant.java|1|1|100.00%|
|:large_blue_circle:|io/questdb/griffin/engine/functions/constants/LongConstant.java|1|1|100.00%|
|:large_blue_circle:|io/questdb/griffin/engine/functions/constants/GeoShortConstant.java|1|1|100.00%|
|:large_blue_circle:|io/questdb/griffin/engine/functions/constants/IPv4Constant.java|1|1|100.00%|
|:large_blue_circle:|io/questdb/griffin/engine/functions/constants/NullBinConstant.java|1|1|100.00%|
|:large_blue_circle:|io/questdb/griffin/engine/functions/constants/VarcharConstant.java|1|1|100.00%|
|:large_blue_circle:|io/questdb/griffin/engine/functions/constants/GeoLongConstant.java|1|1|100.00%|
|:large_blue_circle:|io/questdb/griffin/engine/functions/constants/DateConstant.java|1|1|100.00%|
|:large_blue_circle:|io/questdb/griffin/engine/functions/constants/DoubleConstant.java|1|1|100.00%|
|:large_blue_circle:|io/questdb/griffin/engine/functions/constants/UuidConstant.java|1|1|100.00%|
|:large_blue_circle:|io/questdb/griffin/engine/functions/constants/StrConstant.java|1|1|100.00%|
|:large_blue_circle:|io/questdb/griffin/engine/functions/constants/TimestampConstant.java|1|1|100.00%|
|:large_blue_circle:|io/questdb/griffin/engine/functions/constants/GeoIntConstant.java|1|1|100.00%|
|:large_blue_circle:|io/questdb/griffin/engine/functions/constants/Long128Constant.java|1|1|100.00%|
|:large_blue_circle:|io/questdb/griffin/InsertRowImpl.java|4|4|100.00%|
|:large_blue_circle:|io/questdb/griffin/engine/functions/constants/IntConstant.java|1|1|100.00%|
|:large_blue_circle:|io/questdb/griffin/engine/functions/constants/GeoByteConstant.java|1|1|100.00%|
|:large_blue_circle:|io/questdb/griffin/engine/functions/constants/Long256Constant.java|1|1|100.00%|
|:large_blue_circle:|io/questdb/griffin/engine/functions/constants/FloatConstant.java|1|1|100.00%|
|:large_blue_circle:|io/questdb/griffin/SqlUtil.java|1|1|100.00%|

**Comment by ideoma** [comment]
#### [PR Coverage check]

:heart_eyes: **pass** : 28 / 29 (96.55%)




#### file detail

|   |path|covered line|new line|coverage|
|----|----|----|----|----|
|:large_blue_circle:|io/questdb/griffin/SqlCompilerImpl.java|5|6|83.33%|
|:large_blue_circle:|io/questdb/griffin/engine/functions/constants/SymbolConstant.java|1|1|100.00%|
|:large_blue_circle:|io/questdb/griffin/engine/functions/constants/LongConstant.java|1|1|100.00%|
|:large_blue_circle:|io/questdb/griffin/engine/functions/constants/GeoShortConstant.java|1|1|100.00%|
|:large_blue_circle:|io/questdb/griffin/engine/functions/constants/IPv4Constant.java|1|1|100.00%|
|:large_blue_circle:|io/questdb/griffin/engine/functions/constants/NullBinConstant.java|1|1|100.00%|
|:large_blue_circle:|io/questdb/griffin/engine/functions/constants/VarcharConstant.java|1|1|100.00%|
|:large_blue_circle:|io/questdb/griffin/engine/functions/constants/GeoLongConstant.java|1|1|100.00%|
|:large_blue_circle:|io/questdb/griffin/engine/functions/constants/DateConstant.java|1|1|100.00%|
|:large_blue_circle:|io/questdb/griffin/engine/functions/constants/DoubleConstant.java|1|1|100.00%|
|:large_blue_circle:|io/questdb/griffin/engine/functions/constants/UuidConstant.java|1|1|100.00%|
|:large_blue_circle:|io/questdb/griffin/engine/functions/constants/StrConstant.java|1|1|100.00%|
|:large_blue_circle:|io/questdb/griffin/engine/functions/constants/TimestampConstant.java|1|1|100.00%|
|:large_blue_circle:|io/questdb/griffin/engine/functions/constants/GeoIntConstant.java|1|1|100.00%|
|:large_blue_circle:|io/questdb/griffin/engine/functions/constants/Long128Constant.java|1|1|100.00%|
|:large_blue_circle:|io/questdb/griffin/InsertRowImpl.java|4|4|100.00%|
|:large_blue_circle:|io/questdb/griffin/engine/functions/constants/IntConstant.java|1|1|100.00%|
|:large_blue_circle:|io/questdb/griffin/engine/functions/constants/GeoByteConstant.java|1|1|100.00%|
|:large_blue_circle:|io/questdb/griffin/engine/functions/constants/Long256Constant.java|1|1|100.00%|
|:large_blue_circle:|io/questdb/griffin/engine/functions/constants/FloatConstant.java|1|1|100.00%|
|:large_blue_circle:|io/questdb/griffin/SqlUtil.java|1|1|100.00%|

**Comment by jerrinot** [comment]
@bluestreak01 what makes you think so? I'm usually oblivious about formatting, but I do have it enabled on save. 

image

**Comment by ideoma** [comment]
#### [PR Coverage check]

:heart_eyes: **pass** : 28 / 29 (96.55%)




#### file detail

|   |path|covered line|new line|coverage|
|----|----|----|----|----|
|:large_blue_circle:|io/questdb/griffin/SqlCompilerImpl.java|5|6|83.33%|
|:large_blue_circle:|io/questdb/griffin/engine/functions/constants/SymbolConstant.java|1|1|100.00%|
|:large_blue_circle:|io/questdb/griffin/engine/functions/constants/LongConstant.java|1|1|100.00%|
|:large_blue_circle:|io/questdb/griffin/engine/functions/constants/GeoShortConstant.java|1|1|100.00%|
|:large_blue_circle:|io/questdb/griffin/engine/functions/constants/IPv4Constant.java|1|1|100.00%|
|:large_blue_circle:|io/questdb/griffin/engine/functions/constants/NullBinConstant.java|1|1|100.00%|
|:large_blue_circle:|io/questdb/griffin/engine/functions/constants/VarcharConstant.java|1|1|100.00%|
|:large_blue_circle:|io/questdb/griffin/engine/functions/constants/GeoLongConstant.java|1|1|100.00%|
|:large_blue_circle:|io/questdb/griffin/engine/functions/constants/DateConstant.java|1|1|100.00%|
|:large_blue_circle:|io/questdb/griffin/engine/functions/constants/DoubleConstant.java|1|1|100.00%|
|:large_blue_circle:|io/questdb/griffin/engine/functions/constants/UuidConstant.java|1|1|100.00%|
|:large_blue_circle:|io/questdb/griffin/engine/functions/constants/StrConstant.java|1|1|100.00%|
|:large_blue_circle:|io/questdb/griffin/engine/functions/constants/TimestampConstant.java|1|1|100.00%|
|:large_blue_circle:|io/questdb/griffin/engine/functions/constants/GeoIntConstant.java|1|1|100.00%|
|:large_blue_circle:|io/questdb/griffin/engine/functions/constants/Long128Constant.java|1|1|100.00%|
|:large_blue_circle:|io/questdb/griffin/InsertRowImpl.java|4|4|100.00%|
|:large_blue_circle:|io/questdb/griffin/engine/functions/constants/IntConstant.java|1|1|100.00%|
|:large_blue_circle:|io/questdb/griffin/engine/functions/constants/GeoByteConstant.java|1|1|100.00%|
|:large_blue_circle:|io/questdb/griffin/engine/functions/constants/Long256Constant.java|1|1|100.00%|
|:large_blue_circle:|io/questdb/griffin/engine/functions/constants/FloatConstant.java|1|1|100.00%|
|:large_blue_circle:|io/questdb/griffin/SqlUtil.java|1|1|100.00%|

**Comment by bluestreak01** [comment]
when i auto-format changed classes locally, i get a lot of changes. Don't you?

**Comment by bluestreak01** [comment]
let me commit the formatting to shortcircuit the process

**Review by bluestreak01 — APPROVED** [review]

**Comment by ideoma** [comment]
#### [PR Coverage check]

:heart_eyes: **pass** : 88 / 89 (98.88%)




#### file detail

|   |path|covered line|new line|coverage|
|----|----|----|----|----|
|:large_blue_circle:|io/questdb/griffin/SqlCompilerImpl.java|5|6|83.33%|
|:large_blue_circle:|io/questdb/griffin/engine/functions/constants/SymbolConstant.java|1|1|100.00%|
|:large_blue_circle:|io/questdb/griffin/engine/functions/constants/LongConstant.java|1|1|100.00%|
|:large_blue_circle:|io/questdb/griffin/engine/functions/constants/GeoShortConstant.java|1|1|100.00%|
|:large_blue_circle:|io/questdb/griffin/engine/functions/constants/IPv4Constant.java|1|1|100.00%|
|:large_blue_circle:|io/questdb/griffin/engine/functions/constants/NullBinConstant.java|1|1|100.00%|
|:large_blue_circle:|io/questdb/griffin/engine/functions/constants/VarcharConstant.java|1|1|100.00%|
|:large_blue_circle:|io/questdb/griffin/engine/functions/constants/GeoLongConstant.java|1|1|100.00%|
|:large_blue_circle:|io/questdb/griffin/engine/functions/constants/DateConstant.java|1|1|100.00%|
|:large_blue_circle:|io/questdb/griffin/engine/functions/constants/DoubleConstant.java|1|1|100.00%|
|:large_blue_circle:|io/questdb/griffin/engine/functions/constants/UuidConstant.java|1|1|100.00%|
|:large_blue_circle:|io/questdb/griffin/engine/functions/constants/StrConstant.java|1|1|100.00%|
|:large_blue_circle:|io/questdb/griffin/engine/functions/constants/TimestampConstant.java|1|1|100.00%|
|:large_blue_circle:|io/questdb/griffin/engine/functions/constants/GeoIntConstant.java|1|1|100.00%|
|:large_blue_circle:|io/questdb/griffin/engine/functions/constants/Long128Constant.java|1|1|100.00%|
|:large_blue_circle:|io/questdb/griffin/InsertRowImpl.java|4|4|100.00%|
|:large_blue_circle:|io/questdb/griffin/engine/functions/constants/IntConstant.java|1|1|100.00%|
|:large_blue_circle:|io/questdb/griffin/engine/functions/constants/GeoByteConstant.java|1|1|100.00%|
|:large_blue_circle:|io/questdb/griffin/engine/functions/constants/Long256Constant.java|1|1|100.00%|
|:large_blue_circle:|io/questdb/griffin/engine/functions/constants/FloatConstant.java|1|1|100.00%|
|:large_blue_circle:|io/questdb/griffin/SqlUtil.java|61|61|100.00%|

**Pull request merged**
