### PR TITLE
feat(sql): string_distinct_agg function

### PR DESCRIPTION
**Pull request by puzpuzpuz**
Adds `string_distinct_agg()` SQL function. Unlike the existing `string_agg()` function, this one concatenates unique values only. The output order matches the scan order.

The following SQL
```sql
select string_distinct_agg(s, ',')
from (
  select 'foo' s
  union all
  select 'bar' s
  union all
  select 'baz' s
  union all
  select 'foo' s
);
```
returns `foo,bar,baz` string.

It also includes the following:
* Ports `count_distinct(symbol)` to off-heap bitset to minimize the probability of `java.lang.OutOfMemoryError`
* Makes `count_distinct(symbol)` parallel in all cases except for non-keyed queries with no filter where all aggregate functions support early exit (think, `count_distinct(symbol)`)
* Changes default for `cairo.inactive.reader.max.open.partitions` to 10k
* Changes hash table defaults in parallel aggregate functions to more conservative ones. This leads to 2x memory footprint reduction in some cases
* Gets rid of expensive `ThreadLocal`-based `GroupByAllocator`. Now atoms have per-worker allocators, just like it's done with filters and group by functions
* Avoids OrderedMap resizes when hash table stats are in use by improving stats calculation

### CODE REVIEW

**Comment by ideoma** [comment]
#### [PR Coverage check]

:heart_eyes: **pass** : 287 / 326 (88.04%)




#### file detail

|   |path|covered line|new line|coverage|
|----|----|----|----|----|
|:large_blue_circle:|io/questdb/std/bytes/DirectByteSink.java|3|5|60.00%|
|:large_blue_circle:|io/questdb/griffin/engine/functions/groupby/StringDistinctAggVarcharGroupByFunction.java|56|68|82.35%|
|:large_blue_circle:|io/questdb/griffin/engine/functions/groupby/StringDistinctAggGroupByFunction.java|56|68|82.35%|
|:large_blue_circle:|io/questdb/griffin/engine/functions/date/IntervalFunctionFactory.java|14|16|87.50%|
|:large_blue_circle:|io/questdb/std/CompactUtf8SequenceHashSet.java|49|54|90.74%|
|:large_blue_circle:|io/questdb/griffin/engine/functions/groupby/StringDistinctAggSymbolGroupByFunction.java|67|73|91.78%|
|:large_blue_circle:|io/questdb/std/AbstractUtf8SequenceHashSet.java|3|3|100.00%|
|:large_blue_circle:|io/questdb/griffin/engine/functions/groupby/StringDistinctAggSymbolGroupByFunctionFactory.java|7|7|100.00%|
|:large_blue_circle:|io/questdb/griffin/engine/functions/groupby/StringDistinctAggVarcharGroupByFunctionFactory.java|8|8|100.00%|
|:large_blue_circle:|io/questdb/std/BitSet.java|3|3|100.00%|
|:large_blue_circle:|io/questdb/griffin/engine/functions/groupby/StringDistinctAggGroupByFunctionFactory.java|8|8|100.00%|
|:large_blue_circle:|io/questdb/std/str/DirectUtf8Sink.java|2|2|100.00%|
|:large_blue_circle:|io/questdb/std/Utf8SequenceHashSet.java|1|1|100.00%|
|:large_blue_circle:|io/questdb/griffin/engine/functions/groupby/CountDistinctVarcharGroupByFunction.java|3|3|100.00%|
|:large_blue_circle:|io/questdb/std/CompactCharSequenceHashSet.java|7|7|100.00%|

**Comment by ideoma** [comment]
#### [PR Coverage check]

:heart_eyes: **pass** : 325 / 370 (87.84%)




#### file detail

|   |path|covered line|new line|coverage|
|----|----|----|----|----|
|:large_blue_circle:|io/questdb/std/bytes/DirectByteSink.java|3|5|60.00%|
|:large_blue_circle:|io/questdb/griffin/engine/functions/groupby/StringDistinctAggVarcharGroupByFunction.java|56|68|82.35%|
|:large_blue_circle:|io/questdb/griffin/engine/functions/groupby/StringDistinctAggGroupByFunction.java|56|68|82.35%|
|:large_blue_circle:|io/questdb/griffin/engine/functions/groupby/StringDistinctAggSymbolGroupByFunction.java|53|63|84.13%|
|:large_blue_circle:|io/questdb/griffin/engine/functions/date/IntervalFunctionFactory.java|14|16|87.50%|
|:large_blue_circle:|io/questdb/std/CompactUtf8SequenceHashSet.java|49|54|90.74%|
|:large_blue_circle:|io/questdb/std/DirectBitSet.java|46|48|95.83%|
|:large_blue_circle:|io/questdb/std/AbstractUtf8SequenceHashSet.java|3|3|100.00%|
|:large_blue_circle:|io/questdb/griffin/engine/functions/groupby/StringDistinctAggSymbolGroupByFunctionFactory.java|7|7|100.00%|
|:large_blue_circle:|io/questdb/std/str/DirectUtf16Sink.java|1|1|100.00%|
|:large_blue_circle:|io/questdb/griffin/engine/functions/groupby/StringDistinctAggVarcharGroupByFunctionFactory.java|8|8|100.00%|
|:large_blue_circle:|io/questdb/std/BitSet.java|3|3|100.00%|
|:large_blue_circle:|io/questdb/griffin/engine/functions/groupby/StringDistinctAggGroupByFunctionFactory.java|8|8|100.00%|
|:large_blue_circle:|io/questdb/griffin/engine/functions/groupby/CountDistinctSymbolGroupByFunction.java|4|4|100.00%|
|:large_blue_circle:|io/questdb/std/MemoryTag.java|1|1|100.00%|
|:large_blue_circle:|io/questdb/std/str/DirectUtf8Sink.java|2|2|100.00%|
|:large_blue_circle:|io/questdb/std/Utf8SequenceHashSet.java|1|1|100.00%|
|:large_blue_circle:|io/questdb/griffin/engine/functions/groupby/CountDistinctVarcharGroupByFunction.java|3|3|100.00%|
|:large_blue_circle:|io/questdb/std/CompactCharSequenceHashSet.java|7|7|100.00%|

**Comment by ideoma** [comment]
#### [PR Coverage check]

:heart_eyes: **pass** : 301 / 346 (86.99%)




#### file detail

|   |path|covered line|new line|coverage|
|----|----|----|----|----|
|:large_blue_circle:|io/questdb/std/bytes/DirectByteSink.java|3|5|60.00%|
|:large_blue_circle:|io/questdb/griffin/engine/functions/groupby/StringDistinctAggVarcharGroupByFunction.java|56|68|82.35%|
|:large_blue_circle:|io/questdb/griffin/engine/functions/groupby/StringDistinctAggGroupByFunction.java|56|68|82.35%|
|:large_blue_circle:|io/questdb/griffin/engine/functions/groupby/CountDistinctSymbolGroupByFunction.java|21|25|84.00%|
|:large_blue_circle:|io/questdb/griffin/engine/functions/groupby/StringDistinctAggSymbolGroupByFunction.java|53|61|86.89%|
|:large_blue_circle:|io/questdb/griffin/engine/functions/date/IntervalFunctionFactory.java|14|16|87.50%|
|:large_blue_circle:|io/questdb/std/CompactUtf8SequenceHashSet.java|49|54|90.74%|
|:large_blue_circle:|io/questdb/std/AbstractUtf8SequenceHashSet.java|3|3|100.00%|
|:large_blue_circle:|io/questdb/griffin/engine/functions/groupby/CountDistinctSymbolGroupByFunctionFactory.java|4|4|100.00%|
|:large_blue_circle:|io/questdb/griffin/engine/functions/groupby/StringDistinctAggSymbolGroupByFunctionFactory.java|8|8|100.00%|
|:large_blue_circle:|io/questdb/std/str/DirectUtf16Sink.java|1|1|100.00%|
|:large_blue_circle:|io/questdb/griffin/engine/functions/groupby/StringDistinctAggVarcharGroupByFunctionFactory.java|8|8|100.00%|
|:large_blue_circle:|io/questdb/std/BitSet.java|3|3|100.00%|
|:large_blue_circle:|io/questdb/griffin/engine/functions/groupby/StringDistinctAggGroupByFunctionFactory.java|8|8|100.00%|
|:large_blue_circle:|io/questdb/std/MemoryTag.java|1|1|100.00%|
|:large_blue_circle:|io/questdb/std/str/DirectUtf8Sink.java|2|2|100.00%|
|:large_blue_circle:|io/questdb/std/Utf8SequenceHashSet.java|1|1|100.00%|
|:large_blue_circle:|io/questdb/griffin/engine/functions/groupby/CountDistinctVarcharGroupByFunction.java|3|3|100.00%|
|:large_blue_circle:|io/questdb/std/CompactCharSequenceHashSet.java|7|7|100.00%|

**Comment by ideoma** [comment]
#### [PR Coverage check]

:heart_eyes: **pass** : 332 / 382 (86.91%)




#### file detail

|   |path|covered line|new line|coverage|
|----|----|----|----|----|
|:large_blue_circle:|io/questdb/std/bytes/DirectByteSink.java|3|5|60.00%|
|:large_blue_circle:|io/questdb/griffin/engine/functions/groupby/StringDistinctAggVarcharGroupByFunction.java|56|68|82.35%|
|:large_blue_circle:|io/questdb/griffin/engine/functions/groupby/CountDistinctSymbolGroupByFunction.java|41|50|82.00%|
|:large_blue_circle:|io/questdb/griffin/engine/functions/groupby/StringDistinctAggGroupByFunction.java|56|68|82.35%|
|:large_blue_circle:|io/questdb/griffin/engine/functions/groupby/StringDistinctAggSymbolGroupByFunction.java|53|61|86.89%|
|:large_blue_circle:|io/questdb/griffin/engine/functions/date/IntervalFunctionFactory.java|14|16|87.50%|
|:large_blue_circle:|io/questdb/std/CompactUtf8SequenceHashSet.java|49|54|90.74%|
|:large_blue_circle:|io/questdb/std/AbstractUtf8SequenceHashSet.java|3|3|100.00%|
|:large_blue_circle:|io/questdb/griffin/engine/functions/groupby/CountDistinctSymbolGroupByFunctionFactory.java|4|4|100.00%|
|:large_blue_circle:|io/questdb/griffin/engine/functions/groupby/StringDistinctAggSymbolGroupByFunctionFactory.java|8|8|100.00%|
|:large_blue_circle:|io/questdb/std/str/DirectUtf16Sink.java|1|1|100.00%|
|:large_blue_circle:|io/questdb/griffin/engine/functions/groupby/StringDistinctAggVarcharGroupByFunctionFactory.java|8|8|100.00%|
|:large_blue_circle:|io/questdb/std/BitSet.java|3|3|100.00%|
|:large_blue_circle:|io/questdb/griffin/engine/functions/groupby/StringDistinctAggGroupByFunctionFactory.java|8|8|100.00%|
|:large_blue_circle:|io/questdb/griffin/engine/groupby/GroupByUtils.java|4|4|100.00%|
|:large_blue_circle:|io/questdb/std/MemoryTag.java|1|1|100.00%|
|:large_blue_circle:|io/questdb/std/str/DirectUtf8Sink.java|2|2|100.00%|
|:large_blue_circle:|io/questdb/griffin/SqlCodeGenerator.java|6|6|100.00%|
|:large_blue_circle:|io/questdb/griffin/engine/groupby/GroupByNotKeyedRecordCursorFactory.java|1|1|100.00%|
|:large_blue_circle:|io/questdb/std/Utf8SequenceHashSet.java|1|1|100.00%|
|:large_blue_circle:|io/questdb/griffin/engine/functions/groupby/CountDistinctVarcharGroupByFunction.java|3|3|100.00%|
|:large_blue_circle:|io/questdb/std/CompactCharSequenceHashSet.java|7|7|100.00%|

**Comment by ideoma** [comment]
#### [PR Coverage check]

:heart_eyes: **pass** : 356 / 408 (87.25%)




#### file detail

|   |path|covered line|new line|coverage|
|----|----|----|----|----|
|:large_blue_circle:|io/questdb/std/bytes/DirectByteSink.java|3|5|60.00%|
|:large_blue_circle:|io/questdb/griffin/engine/functions/groupby/CountDistinctUuidGroupByFunction.java|3|4|75.00%|
|:large_blue_circle:|io/questdb/griffin/engine/functions/groupby/StringDistinctAggVarcharGroupByFunction.java|56|68|82.35%|
|:large_blue_circle:|io/questdb/griffin/engine/functions/groupby/CountDistinctSymbolGroupByFunction.java|41|50|82.00%|
|:large_blue_circle:|io/questdb/griffin/engine/functions/groupby/StringDistinctAggGroupByFunction.java|56|68|82.35%|
|:large_blue_circle:|io/questdb/griffin/engine/functions/groupby/CountDistinctLong256GroupByFunction.java|6|7|85.71%|
|:large_blue_circle:|io/questdb/griffin/engine/functions/groupby/StringDistinctAggSymbolGroupByFunction.java|53|61|86.89%|
|:large_blue_circle:|io/questdb/griffin/engine/functions/date/IntervalFunctionFactory.java|14|16|87.50%|
|:large_blue_circle:|io/questdb/std/CompactUtf8SequenceHashSet.java|49|54|90.74%|
|:large_blue_circle:|io/questdb/std/AbstractUtf8SequenceHashSet.java|3|3|100.00%|
|:large_blue_circle:|io/questdb/griffin/engine/functions/groupby/CountDistinctSymbolGroupByFunctionFactory.java|4|4|100.00%|
|:large_blue_circle:|io/questdb/griffin/engine/functions/groupby/StringDistinctAggSymbolGroupByFunctionFactory.java|8|8|100.00%|
|:large_blue_circle:|io/questdb/PropServerConfiguration.java|9|9|100.00%|
|:large_blue_circle:|io/questdb/std/str/DirectUtf16Sink.java|1|1|100.00%|
|:large_blue_circle:|io/questdb/griffin/engine/functions/groupby/StringDistinctAggVarcharGroupByFunctionFactory.java|8|8|100.00%|
|:large_blue_circle:|io/questdb/std/BitSet.java|3|3|100.00%|
|:large_blue_circle:|io/questdb/griffin/engine/functions/groupby/StringDistinctAggGroupByFunctionFactory.java|8|8|100.00%|
|:large_blue_circle:|io/questdb/griffin/engine/groupby/GroupByUtils.java|4|4|100.00%|
|:large_blue_circle:|io/questdb/std/MemoryTag.java|1|1|100.00%|
|:large_blue_circle:|io/questdb/griffin/engine/functions/groupby/CountDistinctLongGroupByFunction.java|3|3|100.00%|
|:large_blue_circle:|io/questdb/std/str/DirectUtf8Sink.java|2|2|100.00%|
|:large_blue_circle:|io/questdb/griffin/SqlCodeGenerator.java|6|6|100.00%|
|:large_blue_circle:|io/questdb/griffin/engine/groupby/GroupByNotKeyedRecordCursorFactory.java|1|1|100.00%|
|:large_blue_circle:|io/questdb/std/Utf8SequenceHashSet.java|1|1|100.00%|
|:large_blue_circle:|io/questdb/griffin/engine/functions/groupby/CountDistinctVarcharGroupByFunction.java|3|3|100.00%|
|:large_blue_circle:|io/questdb/std/CompactCharSequenceHashSet.java|7|7|100.00%|
|:large_blue_circle:|io/questdb/griffin/engine/functions/groupby/CountDistinctIntGroupByFunction.java|3|3|100.00%|

**Comment by ideoma** [comment]
#### [PR Coverage check]

:heart_eyes: **pass** : 470 / 527 (89.18%)




#### file detail

|   |path|covered line|new line|coverage|
|----|----|----|----|----|
|:large_blue_circle:|io/questdb/std/bytes/DirectByteSink.java|3|5|60.00%|
|:large_blue_circle:|io/questdb/cairo/DefaultCairoConfiguration.java|5|8|62.50%|
|:large_blue_circle:|io/questdb/griffin/engine/functions/groupby/CountDistinctUuidGroupByFunction.java|3|4|75.00%|
|:large_blue_circle:|io/questdb/griffin/engine/functions/groupby/StringDistinctAggVarcharGroupByFunction.java|56|68|82.35%|
|:large_blue_circle:|io/questdb/griffin/engine/functions/groupby/CountDistinctSymbolGroupByFunction.java|41|50|82.00%|
|:large_blue_circle:|io/questdb/griffin/engine/functions/groupby/StringDistinctAggGroupByFunction.java|56|68|82.35%|
|:large_blue_circle:|io/questdb/griffin/engine/functions/groupby/CountDistinctLong256GroupByFunction.java|6|7|85.71%|
|:large_blue_circle:|io/questdb/griffin/engine/functions/groupby/StringDistinctAggSymbolGroupByFunction.java|53|61|86.89%|
|:large_blue_circle:|io/questdb/griffin/engine/functions/date/IntervalFunctionFactory.java|14|16|87.50%|
|:large_blue_circle:|io/questdb/cairo/map/OrderedMap.java|16|18|88.89%|
|:large_blue_circle:|io/questdb/std/CompactUtf8SequenceHashSet.java|49|54|90.74%|
|:large_blue_circle:|io/questdb/std/AbstractUtf8SequenceHashSet.java|3|3|100.00%|
|:large_blue_circle:|io/questdb/griffin/engine/functions/groupby/CountDistinctSymbolGroupByFunctionFactory.java|4|4|100.00%|
|:large_blue_circle:|io/questdb/griffin/engine/table/AsyncGroupByNotKeyedRecordCursorFactory.java|3|3|100.00%|
|:large_blue_circle:|io/questdb/griffin/engine/functions/groupby/StringDistinctAggSymbolGroupByFunctionFactory.java|8|8|100.00%|
|:large_blue_circle:|io/questdb/PropServerConfiguration.java|8|8|100.00%|
|:large_blue_circle:|io/questdb/std/str/DirectUtf16Sink.java|1|1|100.00%|
|:large_blue_circle:|io/questdb/griffin/engine/functions/groupby/StringDistinctAggVarcharGroupByFunctionFactory.java|8|8|100.00%|
|:large_blue_circle:|io/questdb/griffin/engine/groupby/SampleByInterpolateRecordCursorFactory.java|1|1|100.00%|
|:large_blue_circle:|io/questdb/std/BitSet.java|3|3|100.00%|
|:large_blue_circle:|io/questdb/griffin/engine/functions/groupby/StringDistinctAggGroupByFunctionFactory.java|8|8|100.00%|
|:large_blue_circle:|io/questdb/griffin/engine/groupby/GroupByAllocatorFactory.java|1|1|100.00%|
|:large_blue_circle:|io/questdb/griffin/engine/table/AsyncGroupByNotKeyedRecordCursor.java|1|1|100.00%|
|:large_blue_circle:|io/questdb/griffin/engine/table/AsyncGroupByAtom.java|49|49|100.00%|
|:large_blue_circle:|io/questdb/griffin/engine/groupby/GroupByRecordCursorFactory.java|1|1|100.00%|
|:large_blue_circle:|io/questdb/griffin/engine/groupby/GroupByUtils.java|4|4|100.00%|
|:large_blue_circle:|io/questdb/std/MemoryTag.java|1|1|100.00%|
|:large_blue_circle:|io/questdb/griffin/engine/functions/groupby/CountDistinctLongGroupByFunction.java|3|3|100.00%|
|:large_blue_circle:|io/questdb/griffin/engine/table/AsyncGroupByRecordCursor.java|1|1|100.00%|
|:large_blue_circle:|io/questdb/griffin/engine/groupby/AbstractNoRecordSampleByCursor.java|1|1|100.00%|
|:large_blue_circle:|io/questdb/std/str/DirectUtf8Sink.java|2|2|100.00%|
|:large_blue_circle:|io/questdb/griffin/engine/groupby/FastGroupByAllocator.java|1|1|100.00%|
|:large_blue_circle:|io/questdb/griffin/SqlCodeGenerator.java|6|6|100.00%|
|:large_blue_circle:|io/questdb/cairo/map/UnorderedVarcharMap.java|1|1|100.00%|
|:large_blue_circle:|io/questdb/griffin/engine/groupby/GroupByNotKeyedRecordCursorFactory.java|2|2|100.00%|
|:large_blue_circle:|io/questdb/std/Utf8SequenceHashSet.java|1|1|100.00%|
|:large_blue_circle:|io/questdb/griffin/engine/functions/groupby/CountDistinctVarcharGroupByFunction.java|3|3|100.00%|
|:large_blue_circle:|io/questdb/griffin/engine/table/AsyncGroupByNotKeyedAtom.java|33|33|100.00%|
|:large_blue_circle:|io/questdb/std/CompactCharSequenceHashSet.java|7|7|100.00%|
|:large_blue_circle:|io/questdb/griffin/engine/functions/groupby/CountDistinctIntGroupByFunction.java|3|3|100.00%|

**Review by jerrinot — APPROVED** [review]
lgtm.

potential further work: offheap impl of `Utf8SequenceSet`  - since the current version stores rather heavy on-heap objects. but it's nice-to-have rather than something critical. since at the end of the day we have to send the result set over a wire -> a row must fit into a network buffer of whatever protocol is used.

**Comment by puzpuzpuz** [comment]
@jerrinot thanks for the review!

**Comment by puzpuzpuz** [comment]
@goodroot another heads-up for the upcoming OSS release. This PR adds `string_distinct_agg` SQL function.

**Comment by goodroot** [comment]
Got it - also, congrats on PR 5000 👯 🎉

**Pull request merged**
