### PR TITLE
chore(ilp): add insert permission checks for ILP/TCP

### PR DESCRIPTION
**Pull request by puzpuzpuz**
Adds missing `SecurityContext#authorizeInsert()` calls to ILP/TCP.

The logic is different for WAL and non-WAL tables, yet both table types use an empty `columnNames` list in the permission checks to minimize the performance impact, so we check the all-column INSERT permission.

### WAL

The check is made before `writer.ic()`/`writer.commit()` calls to minimize the performance impact.

### Non-WAL

The check is made when we send an ILP row to the writer thread, i.e. for each row.

### CODE REVIEW

**Comment by ideoma** [comment]
#### [PR Coverage check]

:heart_eyes: **pass** : 138 / 194 (71.13%)




#### file detail

|   |path|covered line|new line|coverage|
|----|----|----|----|----|
|:large_blue_circle:|io/questdb/cairo/wal/WalWriter.java|6|12|50.00%|
|:large_blue_circle:|io/questdb/cutlass/line/tcp/ColumnTrackingWriterAPI.java|95|142|66.90%|
|:large_blue_circle:|io/questdb/cairo/TableWriter.java|11|13|84.62%|
|:large_blue_circle:|io/questdb/cutlass/line/tcp/TableUpdateDetails.java|13|14|92.86%|
|:large_blue_circle:|io/questdb/cutlass/line/tcp/LineTcpMeasurementScheduler.java|12|12|100.00%|
|:large_blue_circle:|io/questdb/cutlass/auth/EllipticCurveLineAuthenticatorFactory.java|1|1|100.00%|

**Comment by ideoma** [comment]
#### [PR Coverage check]

:heart_eyes: **pass** : 179 / 194 (92.27%)




#### file detail

|   |path|covered line|new line|coverage|
|----|----|----|----|----|
|:large_blue_circle:|io/questdb/cairo/wal/WalWriter.java|10|12|83.33%|
|:large_blue_circle:|io/questdb/cairo/TableWriter.java|11|13|84.62%|
|:large_blue_circle:|io/questdb/cutlass/line/tcp/TableUpdateDetails.java|13|14|92.86%|
|:large_blue_circle:|io/questdb/cutlass/line/tcp/ColumnTrackingWriterAPI.java|132|142|92.96%|
|:large_blue_circle:|io/questdb/cutlass/line/tcp/LineTcpMeasurementScheduler.java|12|12|100.00%|
|:large_blue_circle:|io/questdb/cutlass/auth/EllipticCurveLineAuthenticatorFactory.java|1|1|100.00%|

**Comment by ideoma** [comment]
#### [PR Coverage check]

:heart_eyes: **pass** : 184 / 202 (91.09%)




#### file detail

|   |path|covered line|new line|coverage|
|----|----|----|----|----|
|:large_blue_circle:|io/questdb/cairo/wal/WalWriter.java|10|12|83.33%|
|:large_blue_circle:|io/questdb/cutlass/line/tcp/ColumnTrackingWriterAPI.java|127|142|89.44%|
|:large_blue_circle:|io/questdb/cutlass/line/tcp/TableUpdateDetails.java|18|19|94.74%|
|:large_blue_circle:|io/questdb/cutlass/line/tcp/LineTcpMeasurementScheduler.java|12|12|100.00%|
|:large_blue_circle:|io/questdb/cutlass/auth/EllipticCurveAuthenticatorFactory.java|1|1|100.00%|
|:large_blue_circle:|io/questdb/cairo/TableWriter.java|13|13|100.00%|
|:large_blue_circle:|io/questdb/cutlass/line/tcp/LineTcpMeasurementEvent.java|3|3|100.00%|

**Comment by ideoma** [comment]
#### [PR Coverage check]

:heart_eyes: **pass** : 185 / 203 (91.13%)




#### file detail

|   |path|covered line|new line|coverage|
|----|----|----|----|----|
|:large_blue_circle:|io/questdb/cairo/wal/WalWriter.java|10|12|83.33%|
|:large_blue_circle:|io/questdb/cutlass/line/tcp/ColumnTrackingWriterAPI.java|127|142|89.44%|
|:large_blue_circle:|io/questdb/cutlass/line/tcp/TableUpdateDetails.java|18|19|94.74%|
|:large_blue_circle:|io/questdb/cutlass/line/tcp/LineTcpMeasurementScheduler.java|12|12|100.00%|
|:large_blue_circle:|io/questdb/cutlass/auth/EllipticCurveAuthenticatorFactory.java|1|1|100.00%|
|:large_blue_circle:|io/questdb/cairo/TableWriter.java|13|13|100.00%|
|:large_blue_circle:|io/questdb/cutlass/line/tcp/LineTcpMeasurementEvent.java|4|4|100.00%|

**Comment by ideoma** [comment]
#### [PR Coverage check]

:heart_eyes: **pass** : 51 / 58 (87.93%)




#### file detail

|   |path|covered line|new line|coverage|
|----|----|----|----|----|
|:large_blue_circle:|io/questdb/cairo/wal/WalWriter.java|6|12|50.00%|
|:large_blue_circle:|io/questdb/cutlass/line/tcp/TableUpdateDetails.java|16|17|94.12%|
|:large_blue_circle:|io/questdb/cutlass/line/tcp/LineTcpMeasurementScheduler.java|12|12|100.00%|
|:large_blue_circle:|io/questdb/cutlass/auth/EllipticCurveAuthenticatorFactory.java|1|1|100.00%|
|:large_blue_circle:|io/questdb/cairo/TableWriter.java|13|13|100.00%|
|:large_blue_circle:|io/questdb/cutlass/line/tcp/LineTcpMeasurementEvent.java|3|3|100.00%|

**Comment by ideoma** [comment]
#### [PR Coverage check]

:heart_eyes: **pass** : 51 / 58 (87.93%)




#### file detail

|   |path|covered line|new line|coverage|
|----|----|----|----|----|
|:large_blue_circle:|io/questdb/cairo/wal/WalWriter.java|6|12|50.00%|
|:large_blue_circle:|io/questdb/cutlass/line/tcp/TableUpdateDetails.java|16|17|94.12%|
|:large_blue_circle:|io/questdb/cutlass/line/tcp/LineTcpMeasurementScheduler.java|12|12|100.00%|
|:large_blue_circle:|io/questdb/cutlass/auth/EllipticCurveAuthenticatorFactory.java|1|1|100.00%|
|:large_blue_circle:|io/questdb/cairo/TableWriter.java|13|13|100.00%|
|:large_blue_circle:|io/questdb/cutlass/line/tcp/LineTcpMeasurementEvent.java|3|3|100.00%|

**Review by glasstiger — APPROVED** [review]

**Pull request merged**
