### PR TITLE
chore(core): make SecurityContext aware of authentication type

### LINKED ISSUE #3935: NullPointerException: Cannot invoke "io.questdb.cairo.sql.SymbolTable.valueOf(int)" because "this.symbolTable" is null
### Describe the bug

```
java.lang.NullPointerException: Cannot invoke "io.questdb.cairo.sql.SymbolTable.valueOf(int)" because "this.symbolTable" is null
	at io.questdb.griffin.engine.functions.columns.SymbolColumn.getSymbol(SymbolColumn.java:72)
	at io.questdb.griffin.engine.functions.SymbolFunction.getStr(SymbolFunction.java:156)
	at io.questdb.griffin.engine.functions.regex.AbstractLikeStrFunctionFactory$ConstLikeStrFunction.getBool(AbstractLikeStrFunctionFactory.java:438)
	at io.questdb.cairo.sql.VirtualRecord.getBool(VirtualRecord.java:61)
	at io.questdb.cairo.map.FastMap$BaseKey.put(FastMap.java:482)
	at io.questdb.griffin.engine.functions.window.AvgDoubleWindowFunctionFactory$AvgOverPartitionFunction.pass1(AvgDoubleWindowFunctionFactory.java:357)
	at io.questdb.griffin.engine.window.CachedWindowRecordCursorFactory$CachedWindowRecordCursor.buildRecordChain(CachedWindowRecordCursorFactory.java:380)
	at io.questdb.griffin.engine.window.CachedWindowRecordCursorFactory$CachedWindowRecordCursor.hasNext(CachedWindowRecordCursorFactory.java:303)
	at io.questdb.cutlass.pgwire.PGConnectionContext.sendCursor0(PGConnectionContext.java:2710)
	at io.questdb.cutlass.pgwire.PGConnectionContext.sendCursor(PGConnectionContext.java:2701)
	at io.questdb.cutlass.pgwire.PGConnectionContext$PGConnectionBatchCallback.postCompile(PGConnectionContext.java:2988)
	at io.questdb.griffin.SqlCompilerImpl.compileBatch(SqlCompilerImpl.java:296)
	at io.questdb.cairo.pool.SqlCompilerPool$C.compileBatch(SqlCompilerPool.java:103)
	at io.questdb.cutlass.pgwire.PGConnectionContext.processQuery(PGConnectionContext.java:2491)
	at io.questdb.cutlass.pgwire.PGConnectionContext.parse(PGConnectionContext.java:1910)
	at io.questdb.cutlass.pgwire.PGConnectionContext.handleClientOperation(PGConnectionContext.java:519)
	at io.questdb.cutlass.pgwire.PGWireServer$1.lambda$$0(PGWireServer.java:79)
	at io.questdb.network.AbstractIODispatcher.processIOQueue(AbstractIODispatcher.java:199)
	at io.questdb.cutlass.pgwire.PGWireServer$1.run(PGWireServer.java:109)
	at io.questdb.mp.Worker.run(Worker.java:148)
```

### To reproduce

```
create table test (c_0 symbol, c_1 int);
insert into test values('aaa', 1);
SELECT avg(c_1) OVER(PARTITION BY c_0 LIKE 'aaa') FROM test;
```

### Expected Behavior

_No response_

### Environment

```markdown
- **QuestDB version**: 7.3.4
- **OS**:
- **Browser**:
```

### Additional context

_No response_

### PR DESCRIPTION
**Pull request by puzpuzpuz**
Also fixes #3935

### CODE REVIEW

**Comment by ideoma** [comment]
#### [PR Coverage check]

:heart_eyes: **pass** : 11 / 13 (84.62%)




#### file detail

|   |path|covered line|new line|coverage|
|----|----|----|----|----|
|:large_blue_circle:|io/questdb/cairo/SecurityContext.java|0|1|00.00%|
|:large_blue_circle:|io/questdb/cutlass/auth/Authenticator.java|0|1|00.00%|
|:large_blue_circle:|io/questdb/cutlass/line/tcp/auth/EllipticCurveAuthenticator.java|1|1|100.00%|
|:large_blue_circle:|io/questdb/cutlass/http/HttpConnectionContext.java|1|1|100.00%|
|:large_blue_circle:|io/questdb/cutlass/line/tcp/LineTcpConnectionContext.java|4|4|100.00%|
|:large_blue_circle:|io/questdb/cutlass/pgwire/CleartextPasswordPgWireAuthenticator.java|1|1|100.00%|
|:large_blue_circle:|io/questdb/cutlass/http/HttpAuthenticator.java|1|1|100.00%|
|:large_blue_circle:|io/questdb/cutlass/pgwire/PGConnectionContext.java|3|3|100.00%|

**Comment by ideoma** [comment]
#### [PR Coverage check]

:heart_eyes: **pass** : 41 / 43 (95.35%)




#### file detail

|   |path|covered line|new line|coverage|
|----|----|----|----|----|
|:large_blue_circle:|io/questdb/cairo/SecurityContext.java|0|1|00.00%|
|:large_blue_circle:|io/questdb/cutlass/auth/Authenticator.java|0|1|00.00%|
|:large_blue_circle:|io/questdb/cutlass/line/tcp/auth/EllipticCurveAuthenticator.java|1|1|100.00%|
|:large_blue_circle:|io/questdb/cutlass/http/HttpConnectionContext.java|1|1|100.00%|
|:large_blue_circle:|io/questdb/griffin/engine/functions/window/AvgDoubleWindowFunctionFactory.java|15|15|100.00%|
|:large_blue_circle:|io/questdb/griffin/engine/window/WindowRecordCursorFactory.java|4|4|100.00%|
|:large_blue_circle:|io/questdb/cutlass/line/tcp/LineTcpConnectionContext.java|4|4|100.00%|
|:large_blue_circle:|io/questdb/cutlass/pgwire/CleartextPasswordPgWireAuthenticator.java|1|1|100.00%|
|:large_blue_circle:|io/questdb/cutlass/http/HttpAuthenticator.java|1|1|100.00%|
|:large_blue_circle:|io/questdb/griffin/engine/window/CachedWindowRecordCursorFactory.java|9|9|100.00%|
|:large_blue_circle:|io/questdb/griffin/SqlCodeGenerator.java|2|2|100.00%|
|:large_blue_circle:|io/questdb/cutlass/pgwire/PGConnectionContext.java|3|3|100.00%|

**Comment by ideoma** [comment]
#### [PR Coverage check]

:heart_eyes: **pass** : 41 / 43 (95.35%)




#### file detail

|   |path|covered line|new line|coverage|
|----|----|----|----|----|
|:large_blue_circle:|io/questdb/cairo/SecurityContext.java|0|1|00.00%|
|:large_blue_circle:|io/questdb/cutlass/auth/Authenticator.java|0|1|00.00%|
|:large_blue_circle:|io/questdb/cutlass/line/tcp/auth/EllipticCurveAuthenticator.java|1|1|100.00%|
|:large_blue_circle:|io/questdb/cutlass/http/HttpConnectionContext.java|1|1|100.00%|
|:large_blue_circle:|io/questdb/griffin/engine/functions/window/AvgDoubleWindowFunctionFactory.java|15|15|100.00%|
|:large_blue_circle:|io/questdb/griffin/engine/window/WindowRecordCursorFactory.java|4|4|100.00%|
|:large_blue_circle:|io/questdb/cutlass/line/tcp/LineTcpConnectionContext.java|4|4|100.00%|
|:large_blue_circle:|io/questdb/cutlass/pgwire/CleartextPasswordPgWireAuthenticator.java|1|1|100.00%|
|:large_blue_circle:|io/questdb/cutlass/http/HttpAuthenticator.java|1|1|100.00%|
|:large_blue_circle:|io/questdb/griffin/engine/window/CachedWindowRecordCursorFactory.java|9|9|100.00%|
|:large_blue_circle:|io/questdb/griffin/SqlCodeGenerator.java|2|2|100.00%|
|:large_blue_circle:|io/questdb/cutlass/pgwire/PGConnectionContext.java|3|3|100.00%|

**Review by glasstiger — APPROVED** [review]

**Comment by puzpuzpuz** [comment]
@glasstiger thanks for the review!

**Pull request merged**
