### PR TITLE
Add geohash support for PGWire protocol

### PR DESCRIPTION
**Pull request by eugenels**

### CODE REVIEW

**Comment by ideoma** [comment]
#### [PR Coverage check]

coverage check fail. please retry. :fearful:

[Please let me know](https://github.com/naver/cover-checker/issues/new) when error again.

com.naver.nid.cover.parser.coverage.exception.ParseException: java.io.FileNotFoundException: /home/vsts/work/1/s/core/CCReport43F6D5EF/jacoco.xml (No such file or directory)

**Comment by marregui** [comment]
LGTM

I would add a few more tests though, around the areas of: 
- geohashes containing wrong characters e.g. '@'
- table column declared with a precision, then the insert containing a LOWER precision geohash -> should reject
- table column declared with a precision, then the insert containing a HIGHER precision geohash -> should truncate
- something that looks like a geohash but it is not, e.g. londer than 60 bits or 12 chars

**Comment by ideoma** [comment]
#### [PR Coverage check]

:heart_eyes: **pass** : 46 / 47 (97.87%)




#### file detail

|   |path|covered line|new line|coverage|
|----|----|----|----|----|
|:large_blue_circle:|io/questdb/cutlass/pgwire/PGConnectionContext.java|45|46|97.83%|
|:large_blue_circle:|io/questdb/cutlass/pgwire/PGOids.java|1|1|100.00%|

**Comment by ideoma** [comment]
#### [PR Coverage check]

:heart_eyes: **pass** : 46 / 47 (97.87%)




#### file detail

|   |path|covered line|new line|coverage|
|----|----|----|----|----|
|:large_blue_circle:|io/questdb/cutlass/pgwire/PGConnectionContext.java|45|46|97.83%|
|:large_blue_circle:|io/questdb/cutlass/pgwire/PGOids.java|1|1|100.00%|

**Review by marregui — DISMISSED** [review]
LGTM

Personal opinion, I would merge and then add the missing todo part as a different task.
There is a PR in transit at the moment that could be merged and which contains literal syntax for geohash constants.

**Comment by ideoma** [comment]
#### [PR Coverage check]

:heart_eyes: **pass** : 46 / 47 (97.87%)




#### file detail

|   |path|covered line|new line|coverage|
|----|----|----|----|----|
|:large_blue_circle:|io/questdb/cutlass/pgwire/PGConnectionContext.java|45|46|97.83%|
|:large_blue_circle:|io/questdb/cutlass/pgwire/PGOids.java|1|1|100.00%|

**Comment by ideoma** [comment]
#### [PR Coverage check]

coverage check fail. please retry. :fearful:

[Please let me know](https://github.com/naver/cover-checker/issues/new) when error again.

com.naver.nid.cover.parser.coverage.exception.ParseException: java.io.FileNotFoundException: /home/vsts/work/1/s/core/CCReport43F6D5EF/jacoco.xml (No such file or directory)

**Comment by ideoma** [comment]
#### [PR Coverage check]

:heart_eyes: **pass** : 46 / 47 (97.87%)




#### file detail

|   |path|covered line|new line|coverage|
|----|----|----|----|----|
|:large_blue_circle:|io/questdb/cutlass/pgwire/PGConnectionContext.java|45|46|97.83%|
|:large_blue_circle:|io/questdb/cutlass/pgwire/PGOids.java|1|1|100.00%|

**Comment by ideoma** [comment]
#### [PR Coverage check]

:heart_eyes: **pass** : 46 / 47 (97.87%)




#### file detail

|   |path|covered line|new line|coverage|
|----|----|----|----|----|
|:large_blue_circle:|io/questdb/cutlass/pgwire/PGConnectionContext.java|45|46|97.83%|
|:large_blue_circle:|io/questdb/cutlass/pgwire/PGOids.java|1|1|100.00%|

**Review by bluestreak01 — APPROVED** [review]

**Comment by ideoma** [comment]
#### [PR Coverage check]

:heart_eyes: **pass** : 46 / 47 (97.87%)




#### file detail

|   |path|covered line|new line|coverage|
|----|----|----|----|----|
|:large_blue_circle:|io/questdb/cutlass/pgwire/PGConnectionContext.java|45|46|97.83%|
|:large_blue_circle:|io/questdb/cutlass/pgwire/PGOids.java|1|1|100.00%|

**Comment by ideoma** [comment]
#### [PR Coverage check]

:heart_eyes: **pass** : 46 / 47 (97.87%)




#### file detail

|   |path|covered line|new line|coverage|
|----|----|----|----|----|
|:large_blue_circle:|io/questdb/cutlass/pgwire/PGConnectionContext.java|45|46|97.83%|
|:large_blue_circle:|io/questdb/cutlass/pgwire/PGOids.java|1|1|100.00%|

**Pull request merged**
