### PR TITLE
feat(sql): support const expression in sample by period

### LINKED ISSUE #1447: Variable Declaration and/or Improved Math Support
**Is your feature request related to a problem? Please describe.**

I am using *Telegraf*, *QuestDB*, and *Grafana* to visualize high-frequency time-series data. In order to reduce the time Grafana takes to query long time ranges of data, I need leverage QuestDB's `SAMPLE BY` function.  

Throughout this effort, I have constantly found a need to either declare variables and/or performing mathematical operations outside of the `SELECT` statement (e.g. in the `SAMPLE BY` statement). 

**Describe the solution you'd like**

I need to make my QuestDB query dynamic based on a simple math equation leveraging Grafana's system variable *$__interval_ms* and an arbitrary numeric. After working through this problem, it would seem the two easiest ways to accommodate this would be to either: a) provide the ability to declare a variable (e.g. `DECLARE @SAMPLER` or add support with the `WITH` statement); or b) improve mathematics support so that I can dynamically assign the `SAMPLE BY` value via third-party tools (e.g. `SAMPLE BY (1000/10)T`).

**Describe alternatives you've considered**

I have tried to do the following as workarounds:

 1. declare a variable via `DECLARE @sampler` -- failed
 2. perform a `WITH` statement before the query via `WITH sampler as (SELECT concat($__interval_ms / 1000, 'T')` and then reference `sampler` at the end via `SAMPLE BY sampler` -- failed
 3. perform the math in a Grafana variable (via their standard dashboard variable GUI) -- failed
 4. embedding a `SELECT` statement in the `SAMPLE BY` function -- failed

**Additional context**

In query below, I am attempting to leverage Grafana's system variables to make my query dynamic. I am expecting QuestDB to understand and perform the mathematical operation necessary to complete the `SAMPLE BY` function.
```
SELECT ts time, last(x), last(y), last(z)
FROM accelerometer
WHERE $__timeFilter(ts)
SAMPLE BY ($__interval_ms/1000)T
```
After Grafana processes this query, it is passed to QuestDB as...
```
SELECT ts time, last(x), last(y), last(z)
FROM accelerometer
WHERE ts BETWEEN '2021-10-12T00:00:00.000Z' AND '2021-10-12T01:00:00.000Z'
SAMPLE BY (30000/1000)T
```
*NOTE: if I replace `SAMPLE BY (300000/1000)T` with `SAMPLE BY 30T`, the query performs as expected.*

### PR DESCRIPTION
**Pull request by ideoma**
Closes #1447. Enables to queries with math support in `SAMPLE BY` period expression like:

- `sample by 300/10 m`
- `sample by 100+200 T`

### CODE REVIEW

**Comment by ideoma** [comment]
#### [PR Coverage check]

:heart_eyes: **pass** : 26 / 35 (74.29%)




#### file detail

|   |path|covered line|new line|coverage|
|----|----|----|----|----|
|:large_blue_circle:|io/questdb/griffin/engine/groupby/TimestampSamplerFactory.java|3|11|27.27%|
|:large_blue_circle:|io/questdb/griffin/SqlParser.java|9|10|90.00%|
|:large_blue_circle:|io/questdb/griffin/model/QueryModel.java|6|6|100.00%|
|:large_blue_circle:|io/questdb/griffin/SqlCodeGenerator.java|8|8|100.00%|

**Comment by ideoma** [comment]
#### [PR Coverage check]

:heart_eyes: **pass** : 26 / 35 (74.29%)




#### file detail

|   |path|covered line|new line|coverage|
|----|----|----|----|----|
|:large_blue_circle:|io/questdb/griffin/engine/groupby/TimestampSamplerFactory.java|3|11|27.27%|
|:large_blue_circle:|io/questdb/griffin/SqlParser.java|9|10|90.00%|
|:large_blue_circle:|io/questdb/griffin/model/QueryModel.java|6|6|100.00%|
|:large_blue_circle:|io/questdb/griffin/SqlCodeGenerator.java|8|8|100.00%|

**Comment by ideoma** [comment]
#### [PR Coverage check]

:heart_eyes: **pass** : 26 / 35 (74.29%)




#### file detail

|   |path|covered line|new line|coverage|
|----|----|----|----|----|
|:large_blue_circle:|io/questdb/griffin/engine/groupby/TimestampSamplerFactory.java|3|11|27.27%|
|:large_blue_circle:|io/questdb/griffin/SqlParser.java|9|10|90.00%|
|:large_blue_circle:|io/questdb/griffin/model/QueryModel.java|6|6|100.00%|
|:large_blue_circle:|io/questdb/griffin/SqlCodeGenerator.java|8|8|100.00%|

**Comment by ideoma** [comment]
#### [PR Coverage check]

:heart_eyes: **pass** : 41 / 42 (97.62%)




#### file detail

|   |path|covered line|new line|coverage|
|----|----|----|----|----|
|:large_blue_circle:|io/questdb/griffin/engine/groupby/TimestampSamplerFactory.java|12|13|92.31%|
|:large_blue_circle:|io/questdb/griffin/model/QueryModel.java|6|6|100.00%|
|:large_blue_circle:|io/questdb/griffin/SqlParser.java|15|15|100.00%|
|:large_blue_circle:|io/questdb/griffin/SqlCodeGenerator.java|8|8|100.00%|

**Comment by ideoma** [comment]
#### [PR Coverage check]

:heart_eyes: **pass** : 41 / 42 (97.62%)




#### file detail

|   |path|covered line|new line|coverage|
|----|----|----|----|----|
|:large_blue_circle:|io/questdb/griffin/engine/groupby/TimestampSamplerFactory.java|12|13|92.31%|
|:large_blue_circle:|io/questdb/griffin/model/QueryModel.java|6|6|100.00%|
|:large_blue_circle:|io/questdb/griffin/SqlParser.java|15|15|100.00%|
|:large_blue_circle:|io/questdb/griffin/SqlCodeGenerator.java|8|8|100.00%|

**Comment by ideoma** [comment]
#### [PR Coverage check]

:heart_eyes: **pass** : 41 / 42 (97.62%)




#### file detail

|   |path|covered line|new line|coverage|
|----|----|----|----|----|
|:large_blue_circle:|io/questdb/griffin/engine/groupby/TimestampSamplerFactory.java|12|13|92.31%|
|:large_blue_circle:|io/questdb/griffin/model/QueryModel.java|6|6|100.00%|
|:large_blue_circle:|io/questdb/griffin/SqlParser.java|15|15|100.00%|
|:large_blue_circle:|io/questdb/griffin/SqlCodeGenerator.java|8|8|100.00%|

**Comment by ideoma** [comment]
#### [PR Coverage check]

:heart_eyes: **pass** : 41 / 42 (97.62%)




#### file detail

|   |path|covered line|new line|coverage|
|----|----|----|----|----|
|:large_blue_circle:|io/questdb/griffin/engine/groupby/TimestampSamplerFactory.java|12|13|92.31%|
|:large_blue_circle:|io/questdb/griffin/model/QueryModel.java|6|6|100.00%|
|:large_blue_circle:|io/questdb/griffin/SqlParser.java|15|15|100.00%|
|:large_blue_circle:|io/questdb/griffin/SqlCodeGenerator.java|8|8|100.00%|

**Comment by ideoma** [comment]
#### [PR Coverage check]

:heart_eyes: **pass** : 41 / 42 (97.62%)




#### file detail

|   |path|covered line|new line|coverage|
|----|----|----|----|----|
|:large_blue_circle:|io/questdb/griffin/engine/groupby/TimestampSamplerFactory.java|12|13|92.31%|
|:large_blue_circle:|io/questdb/griffin/model/QueryModel.java|6|6|100.00%|
|:large_blue_circle:|io/questdb/griffin/SqlParser.java|15|15|100.00%|
|:large_blue_circle:|io/questdb/griffin/SqlCodeGenerator.java|8|8|100.00%|

**Comment by ideoma** [comment]
#### [PR Coverage check]

:heart_eyes: **pass** : 41 / 42 (97.62%)




#### file detail

|   |path|covered line|new line|coverage|
|----|----|----|----|----|
|:large_blue_circle:|io/questdb/griffin/engine/groupby/TimestampSamplerFactory.java|12|13|92.31%|
|:large_blue_circle:|io/questdb/griffin/model/QueryModel.java|6|6|100.00%|
|:large_blue_circle:|io/questdb/griffin/SqlParser.java|15|15|100.00%|
|:large_blue_circle:|io/questdb/griffin/SqlCodeGenerator.java|8|8|100.00%|

**Comment by ideoma** [comment]
#### [PR Coverage check]

:heart_eyes: **pass** : 41 / 42 (97.62%)




#### file detail

|   |path|covered line|new line|coverage|
|----|----|----|----|----|
|:large_blue_circle:|io/questdb/griffin/engine/groupby/TimestampSamplerFactory.java|12|13|92.31%|
|:large_blue_circle:|io/questdb/griffin/model/QueryModel.java|6|6|100.00%|
|:large_blue_circle:|io/questdb/griffin/SqlParser.java|15|15|100.00%|
|:large_blue_circle:|io/questdb/griffin/SqlCodeGenerator.java|8|8|100.00%|

**Comment by bluestreak01** [comment]
can we have more negative testing pls:

- unsupported types, double, string etc
- literal reference from expression, need to check quality of error messages

**Comment by ideoma** [comment]
#### [PR Coverage check]

:heart_eyes: **pass** : 44 / 45 (97.78%)




#### file detail

|   |path|covered line|new line|coverage|
|----|----|----|----|----|
|:large_blue_circle:|io/questdb/griffin/engine/groupby/TimestampSamplerFactory.java|13|14|92.86%|
|:large_blue_circle:|io/questdb/griffin/model/QueryModel.java|6|6|100.00%|
|:large_blue_circle:|io/questdb/griffin/SqlParser.java|15|15|100.00%|
|:large_blue_circle:|io/questdb/griffin/SqlCodeGenerator.java|10|10|100.00%|

**Comment by ideoma** [comment]
#### [PR Coverage check]

:heart_eyes: **pass** : 44 / 45 (97.78%)




#### file detail

|   |path|covered line|new line|coverage|
|----|----|----|----|----|
|:large_blue_circle:|io/questdb/griffin/engine/groupby/TimestampSamplerFactory.java|13|14|92.86%|
|:large_blue_circle:|io/questdb/griffin/model/QueryModel.java|6|6|100.00%|
|:large_blue_circle:|io/questdb/griffin/SqlParser.java|15|15|100.00%|
|:large_blue_circle:|io/questdb/griffin/SqlCodeGenerator.java|10|10|100.00%|

**Comment by ideoma** [comment]
#### [PR Coverage check]

:heart_eyes: **pass** : 45 / 46 (97.83%)




#### file detail

|   |path|covered line|new line|coverage|
|----|----|----|----|----|
|:large_blue_circle:|io/questdb/griffin/engine/groupby/TimestampSamplerFactory.java|13|14|92.86%|
|:large_blue_circle:|io/questdb/griffin/model/QueryModel.java|6|6|100.00%|
|:large_blue_circle:|io/questdb/griffin/SqlParser.java|16|16|100.00%|
|:large_blue_circle:|io/questdb/griffin/SqlCodeGenerator.java|10|10|100.00%|

**Comment by ideoma** [comment]
#### [PR Coverage check]

:heart_eyes: **pass** : 45 / 46 (97.83%)




#### file detail

|   |path|covered line|new line|coverage|
|----|----|----|----|----|
|:large_blue_circle:|io/questdb/griffin/engine/groupby/TimestampSamplerFactory.java|13|14|92.86%|
|:large_blue_circle:|io/questdb/griffin/model/QueryModel.java|6|6|100.00%|
|:large_blue_circle:|io/questdb/griffin/SqlParser.java|16|16|100.00%|
|:large_blue_circle:|io/questdb/griffin/SqlCodeGenerator.java|10|10|100.00%|

**Comment by ideoma** [comment]
#### [PR Coverage check]

:heart_eyes: **pass** : 45 / 46 (97.83%)




#### file detail

|   |path|covered line|new line|coverage|
|----|----|----|----|----|
|:large_blue_circle:|io/questdb/griffin/engine/groupby/TimestampSamplerFactory.java|13|14|92.86%|
|:large_blue_circle:|io/questdb/griffin/model/QueryModel.java|6|6|100.00%|
|:large_blue_circle:|io/questdb/griffin/SqlParser.java|16|16|100.00%|
|:large_blue_circle:|io/questdb/griffin/SqlCodeGenerator.java|10|10|100.00%|

**Comment by ideoma** [comment]
#### [PR Coverage check]

:heart_eyes: **pass** : 44 / 45 (97.78%)




#### file detail

|   |path|covered line|new line|coverage|
|----|----|----|----|----|
|:large_blue_circle:|io/questdb/griffin/engine/groupby/TimestampSamplerFactory.java|12|13|92.31%|
|:large_blue_circle:|io/questdb/griffin/model/QueryModel.java|6|6|100.00%|
|:large_blue_circle:|io/questdb/griffin/SqlParser.java|16|16|100.00%|
|:large_blue_circle:|io/questdb/griffin/SqlCodeGenerator.java|10|10|100.00%|

**Comment by ideoma** [comment]
#### [PR Coverage check]

:heart_eyes: **pass** : 44 / 45 (97.78%)




#### file detail

|   |path|covered line|new line|coverage|
|----|----|----|----|----|
|:large_blue_circle:|io/questdb/griffin/engine/groupby/TimestampSamplerFactory.java|12|13|92.31%|
|:large_blue_circle:|io/questdb/griffin/model/QueryModel.java|6|6|100.00%|
|:large_blue_circle:|io/questdb/griffin/SqlParser.java|16|16|100.00%|
|:large_blue_circle:|io/questdb/griffin/SqlCodeGenerator.java|10|10|100.00%|

**Review by bluestreak01 — APPROVED** [review]

**Pull request merged**
