### PR TITLE
feat(sql): enable rank() analytical SQL function

### PR DESCRIPTION
**Pull request by puzpuzpuz**
https://bugs.openjdk.org/browse/JDK-8296924 has been fixed and backported to OpenJDK 11.0.19 and 17.0.7

Pending change: we're waiting until Coretto 17.0.7 release becomes available, so that we can start using it in rt artifacts.

### CODE REVIEW

**Comment by jerrinot** [comment]
hm, the new JDKs are not released yet

**Comment by bziobrowski** [comment]
Assuming latest jdks fix the issue, shouldn't we somehow warn users about it? 
e.g. check jdk version in props or in reference doc (which is missing) .

**Comment by puzpuzpuz** [comment]
> Assuming latest jdks fix the issue, shouldn't we somehow warn users about it?

Might be a good idea to do it at least in the release notes. Other than that, I'm not convinced that `rank()` was doing something very specific to reproduce the C2 bug. Other parts of our code could theoretically lead to the same bug.

**Review by marregui — DISMISSED** [review]
LGTM

**Comment by jerrinot** [comment]
well, `rank()` was triggering the bug. I am not aware of any other function triggering it. hence I would wait until the updated JDKs are released, we can upgrade the container image, etc.

**Comment by jerrinot** [comment]
according to https://wiki.openjdk.org/display/JDKUpdates/JDK11u 11.0.19 is scheduled to be released in April. that's not great.

**Comment by puzpuzpuz** [comment]
> 1.0.19 is scheduled to be released in April

Better late than never.

**Comment by puzpuzpuz** [comment]
Corretto 1.17.0.7 is now available, so we can merge this one: https://github.com/corretto/corretto-17/releases/tag/17.0.7.7.1

@marregui @jerrinot could you take another look at the PR?

**Review by marregui — APPROVED** [review]
LGTM

**Review by jerrinot — APPROVED** [review]

**Comment by bluestreak01** [comment]
@puzpuzpuz what are the implications of this PR for the Docker build?

**Comment by puzpuzpuz** [comment]
> @puzpuzpuz what are the implications of this PR for the Docker build?

Thanks for the reminder. Updated the version in f14eb4d627dd832e21ad351f4ef62721abd452bd

@mariusgheorghies do I need to update JDK version elsewhere, e.g. for the purpose of *-rt artifacts?

**Review by bluestreak01 — APPROVED** [review]

**Pull request merged**
