### PR TITLE
fix(ilp): Race between schema inference and schema mutation could corrupt data

### LINKED ISSUE #2019: Very frequent random crash
### Describe the bug

We are seeing the very frequent crash. there is no particular sequence or with certain data. the crash is really random.

 A fatal error has been detected by the Java Runtime Environment:
 SIGSEGV (0xb) at pc=0x00007f88f8bfd930, pid=548526, tid=548553
JRE version: OpenJDK Runtime Environment AdoptOpenJDK (11.0.9.1+1) (build 11.0.9.1+1)
Java VM: OpenJDK 64-Bit Server VM AdoptOpenJDK (11.0.9.1+1, mixed mode, tiered, compressed oops, parallel gc, linux-amd64)
 Problematic frame:
 J 2408 c2 io.questdb.cairo.vm.api.MemoryCR.getLong(J)J io.questdb@6.2 (44 bytes) @ 0x00007f88f8bfd930 [0x00007f88f8bfd8c0+0x0000000000000070]

 No core dump will be written. Core dumps have been disabled. To enable core dumping, try "ulimit -c unlimited" before starting Java again

stdout-2022-04-07T22-34-26.txt](https://github.com/questdb/questdb/files/8446400/stdout-2022-04-07T22-34-26.txt)
[hs_err_pid548526.log](https://github.com/questdb/questdb/files/8446421/hs_err_pid548526.log)

### To reproduce

There is no particular step to reproduce the issue. issues are seen very often with our test case environment

### Expected Behavior

questDB running continuously with out interruption

### Environment

```markdown
- **QuestDB version**:6.2
- **OS**: ubuntu 20.04
- **Browser**:
```

### Additional context

_No response_

### PR DESCRIPTION
**Pull request by bluestreak01**
Fixes #2019

Easiest way to explain the issue is via an example.
Problematic ILP ingestion:
```
weather,location=london temperature=22.3 1234567890
weather,location=london temperature=22.1,notes="any string" 1234567891
weather,location=london temperature=22.4,notes=754.56 1234567892
```

First line creates the table.
Second adds new column 'notes' with type STRING.
Third line contains 'notes' again but this time the inferred type is FLOAT as there are no quotes and value is numeric.
As the column is added on the writer thread there is a good chance that at the time of processing of the third line the IO thread cannot see the column created yet.
The 'notes' column will be sent to the writer thread by name again as a double value.
TableWriter then adds this double to the string column and data file gets corrupted.
Next read is likely to fail with a crash.
Fix is to cache inferred column types when columns are added dynamically via ILP and validate type on all subsequent lines.

### CODE REVIEW

**Comment by ideoma** [comment]
#### [PR Coverage check]

:disappointed: **fail** : 0 / 10 (00.00%)




#### file detail

|   |path|covered line|new line|coverage|
|----|----|----|----|----|
|:large_blue_circle:|io/questdb/cutlass/line/tcp/LineTcpMeasurementScheduler.java|0|1|00.00%|
|:large_blue_circle:|io/questdb/cutlass/line/tcp/TableUpdateDetails.java|0|8|00.00%|
|:large_blue_circle:|io/questdb/cutlass/line/tcp/LineTcpMeasurementEvent.java|0|1|00.00%|

**Comment by ideoma** [comment]
#### [PR Coverage check]

:heart_eyes: **pass** : 10 / 10 (100.00%)




#### file detail

|   |path|covered line|new line|coverage|
|----|----|----|----|----|
|:large_blue_circle:|io/questdb/cutlass/line/tcp/LineTcpMeasurementScheduler.java|1|1|100.00%|
|:large_blue_circle:|io/questdb/cutlass/line/tcp/TableUpdateDetails.java|8|8|100.00%|
|:large_blue_circle:|io/questdb/cutlass/line/tcp/LineTcpMeasurementEvent.java|1|1|100.00%|

**Review by bluestreak01 — COMMENTED** [review]
Test failures should be investigated

**Comment by ideoma** [comment]
#### [PR Coverage check]

:disappointed: **fail** : 0 / 11 (00.00%)




#### file detail

|   |path|covered line|new line|coverage|
|----|----|----|----|----|
|:large_blue_circle:|io/questdb/cutlass/line/tcp/LineTcpMeasurementScheduler.java|0|1|00.00%|
|:large_blue_circle:|io/questdb/cutlass/line/tcp/TableUpdateDetails.java|0|8|00.00%|
|:large_blue_circle:|io/questdb/cutlass/line/tcp/LineTcpMeasurementEvent.java|0|2|00.00%|

**Comment by ideoma** [comment]
#### [PR Coverage check]

:disappointed: **fail** : 0 / 14 (00.00%)




#### file detail

|   |path|covered line|new line|coverage|
|----|----|----|----|----|
|:large_blue_circle:|io/questdb/cutlass/line/tcp/LineTcpMeasurementScheduler.java|0|1|00.00%|
|:large_blue_circle:|io/questdb/cutlass/line/tcp/TableUpdateDetails.java|0|8|00.00%|
|:large_blue_circle:|io/questdb/cutlass/line/tcp/LineTcpMeasurementEvent.java|0|5|00.00%|

**Comment by ideoma** [comment]
#### [PR Coverage check]

:disappointed: **fail** : 0 / 14 (00.00%)




#### file detail

|   |path|covered line|new line|coverage|
|----|----|----|----|----|
|:large_blue_circle:|io/questdb/cutlass/line/tcp/LineTcpMeasurementScheduler.java|0|1|00.00%|
|:large_blue_circle:|io/questdb/cutlass/line/tcp/TableUpdateDetails.java|0|8|00.00%|
|:large_blue_circle:|io/questdb/cutlass/line/tcp/LineTcpMeasurementEvent.java|0|5|00.00%|

**Comment by ideoma** [comment]
#### [PR Coverage check]

:disappointed: **fail** : 0 / 14 (00.00%)




#### file detail

|   |path|covered line|new line|coverage|
|----|----|----|----|----|
|:large_blue_circle:|io/questdb/cutlass/line/tcp/LineTcpMeasurementScheduler.java|0|1|00.00%|
|:large_blue_circle:|io/questdb/cutlass/line/tcp/TableUpdateDetails.java|0|8|00.00%|
|:large_blue_circle:|io/questdb/cutlass/line/tcp/LineTcpMeasurementEvent.java|0|5|00.00%|

**Comment by ideoma** [comment]
#### [PR Coverage check]

:heart_eyes: **pass** : 14 / 14 (100.00%)




#### file detail

|   |path|covered line|new line|coverage|
|----|----|----|----|----|
|:large_blue_circle:|io/questdb/cutlass/line/tcp/LineTcpMeasurementScheduler.java|1|1|100.00%|
|:large_blue_circle:|io/questdb/cutlass/line/tcp/TableUpdateDetails.java|8|8|100.00%|
|:large_blue_circle:|io/questdb/cutlass/line/tcp/LineTcpMeasurementEvent.java|5|5|100.00%|

**Comment by ideoma** [comment]
#### [PR Coverage check]

:disappointed: **fail** : 0 / 14 (00.00%)




#### file detail

|   |path|covered line|new line|coverage|
|----|----|----|----|----|
|:large_blue_circle:|io/questdb/cutlass/line/tcp/LineTcpMeasurementScheduler.java|0|1|00.00%|
|:large_blue_circle:|io/questdb/cutlass/line/tcp/TableUpdateDetails.java|0|8|00.00%|
|:large_blue_circle:|io/questdb/cutlass/line/tcp/LineTcpMeasurementEvent.java|0|5|00.00%|

**Comment by ideoma** [comment]
#### [PR Coverage check]

:disappointed: **fail** : 0 / 14 (00.00%)




#### file detail

|   |path|covered line|new line|coverage|
|----|----|----|----|----|
|:large_blue_circle:|io/questdb/cutlass/line/tcp/LineTcpMeasurementScheduler.java|0|1|00.00%|
|:large_blue_circle:|io/questdb/cutlass/line/tcp/TableUpdateDetails.java|0|8|00.00%|
|:large_blue_circle:|io/questdb/cutlass/line/tcp/LineTcpMeasurementEvent.java|0|5|00.00%|

**Review by jerrinot — APPROVED** [review]
I changed the title as discussed, the description is pretty good. 
I did *not* review the code.

**Pull request merged**
