### PR TITLE
feat: add "sudo" disable option for telemetry

### PR DESCRIPTION
**Pull request by eugenels**

### CODE REVIEW

**Review by bluestreak01 — APPROVED** [review]

**Comment by ideoma** [comment]
#### [PR Coverage check]

:disappointed: **fail** : 1 / 7 (14.29%)




#### file detail

|   |path|covered line|new line|coverage|
|----|----|----|----|----|
|:large_blue_circle:|io/questdb/DefaultTelemetryConfiguration.java|0|1|00.00%|
|:large_blue_circle:|io/questdb/ServerMain.java|0|5|00.00%|
|:large_blue_circle:|io/questdb/PropServerConfiguration.java|1|1|100.00%|

**Comment by ideoma** [comment]
#### [PR Coverage check]

:disappointed: **fail** : 1 / 7 (14.29%)




#### file detail

|   |path|covered line|new line|coverage|
|----|----|----|----|----|
|:large_blue_circle:|io/questdb/DefaultTelemetryConfiguration.java|0|1|00.00%|
|:large_blue_circle:|io/questdb/ServerMain.java|0|5|00.00%|
|:large_blue_circle:|io/questdb/PropServerConfiguration.java|1|1|100.00%|

**Comment by ideoma** [comment]
#### [PR Coverage check]

:disappointed: **fail** : 1 / 7 (14.29%)




#### file detail

|   |path|covered line|new line|coverage|
|----|----|----|----|----|
|:large_blue_circle:|io/questdb/DefaultTelemetryConfiguration.java|0|1|00.00%|
|:large_blue_circle:|io/questdb/ServerMain.java|0|5|00.00%|
|:large_blue_circle:|io/questdb/PropServerConfiguration.java|1|1|100.00%|

**Comment by ideoma** [comment]
#### [PR Coverage check]

:disappointed: **fail** : 1 / 7 (14.29%)




#### file detail

|   |path|covered line|new line|coverage|
|----|----|----|----|----|
|:large_blue_circle:|io/questdb/DefaultTelemetryConfiguration.java|0|1|00.00%|
|:large_blue_circle:|io/questdb/ServerMain.java|0|5|00.00%|
|:large_blue_circle:|io/questdb/PropServerConfiguration.java|1|1|100.00%|

**Pull request merged**
