### PR TITLE
fix(sql): fix timestamp column required error in sample by with sub-queries

### LINKED ISSUE #2919: ASC order over TIMESTAMP column is required but not provided error in SAMPLE BY over a table with no designated timestamp
### Describe the bug

`timestampRequiredFlag` is pushed too early in `generateSampleBy`. Most likely we need to push it after the `generateSubQuery` call.

### To reproduce

```sql
create table x as (
  select x as value,
         rnd_symbol(100, 10, 10, 0) sym,
         cast(x as timestamp) ts
  from long_sequence(10)
);

select ts, last(value) v
from (
    select ts, value
    from x
    where sym is not null
    order by ts
) timestamp(ts)
sample by 1d;
```

The above query leads to `ASC order over TIMESTAMP column is required but not providedASC order over TIMESTAMP column is required but not provided` while it should not.

### Expected Behavior

_No response_

### Environment

```markdown
- **QuestDB version**:
- **OS**:
- **Browser**:
```

### Additional context

_No response_

### LINKED ISSUE #2939: Flaky FullFwdDataFrameCursorTest.testIndexFailAtRuntimeByWeek3v
### Describe the bug

Fails reliably on Linux:
```
io.questdb.cairo.CairoException: [2] could not mmap column [fd=47, size=16777216]

	at io.questdb@6.6.2-SNAPSHOT/io.questdb.cairo.CairoException.critical(CairoException.java:54)
	at io.questdb@6.6.2-SNAPSHOT/io.questdb.cairo.TableUtils.mapRW(TableUtils.java:782)
	at io.questdb@6.6.2-SNAPSHOT/io.questdb.cairo.vm.MemoryPMARImpl.mapPage(MemoryPMARImpl.java:89)
	at io.questdb@6.6.2-SNAPSHOT/io.questdb.cairo.vm.MemoryPMARImpl.mapWritePage(MemoryPMARImpl.java:154)
	at io.questdb@6.6.2-SNAPSHOT/io.questdb.cairo.vm.MemoryPARWImpl.jumpTo0(MemoryPARWImpl.java:812)
	at io.questdb@6.6.2-SNAPSHOT/io.questdb.cairo.vm.MemoryPARWImpl.jumpTo(MemoryPARWImpl.java:325)
	at io.questdb@6.6.2-SNAPSHOT/io.questdb.cairo.TableWriter.setColumnSize(TableWriter.java:6065)
	at io.questdb@6.6.2-SNAPSHOT/io.questdb.cairo.TableWriter.setAppendPosition(TableWriter.java:6030)
	at io.questdb@6.6.2-SNAPSHOT/io.questdb.cairo.TableWriter.rowCancel(TableWriter.java:6610)
	at io.questdb@6.6.2-SNAPSHOT/io.questdb.cairo.TableWriter.commit(TableWriter.java:2675)
	at io.questdb@6.6.2-SNAPSHOT/io.questdb.cairo.TableWriter.commit(TableWriter.java:846)
	at io.questdb@6.6.2-SNAPSHOT/io.questdb.cairo.TableWriter.commit(TableWriter.java:842)
	at io.questdb@6.6.2-SNAPSHOT/io.questdb.cairo.FullFwdDataFrameCursorTest.lambda$testIndexFailureAtRuntime$4(FullFwdDataFrameCursorTest.java:1334)
	at io.questdb@6.6.2-SNAPSHOT/io.questdb.test.tools.TestUtils.assertMemoryLeak(TestUtils.java:542)
	at io.questdb@6.6.2-SNAPSHOT/io.questdb.cairo.FullFwdDataFrameCursorTest.testIndexFailureAtRuntime(FullFwdDataFrameCursorTest.java:1244)
	at io.questdb@6.6.2-SNAPSHOT/io.questdb.cairo.FullFwdDataFrameCursorTest.testIndexFailAtRuntimeByWeek3v(FullFwdDataFrameCursorTest.java:217)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:568)
	at org.junit.runners.model.FrameworkMethod$1.runReflectiveCall(FrameworkMethod.java:59)
	at org.junit.internal.runners.model.ReflectiveCallable.run(ReflectiveCallable.java:12)
	at org.junit.runners.model.FrameworkMethod.invokeExplosively(FrameworkMethod.java:56)
	at org.junit.internal.runners.statements.InvokeMethod.evaluate(InvokeMethod.java:17)
	at org.junit.internal.runners.statements.RunBefores.evaluate(RunBefores.java:26)
	at org.junit.internal.runners.statements.RunAfters.evaluate(RunAfters.java:27)
	at org.junit.rules.TestWatcher$1.evaluate(TestWatcher.java:61)
	at org.junit.rules.TestWatcher$1.evaluate(TestWatcher.java:61)
	at org.junit.internal.runners.statements.FailOnTimeout$CallableStatement.call(FailOnTimeout.java:299)
	at org.junit.internal.runners.statements.FailOnTimeout$CallableStatement.call(FailOnTimeout.java:293)
	at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
	at java.base/java.lang.Thread.run(Thread.java:833)
```

### To reproduce

_No response_

### Expected Behavior

_No response_

### Environment

```markdown
- **QuestDB version**:
- **OS**:
- **Browser**:
```

### Additional context

_No response_

### PR DESCRIPTION
**Pull request by puzpuzpuz**
Fixes #2919 (both cases)
Fixes #2939

### CODE REVIEW

**Comment by ideoma** [comment]
#### [PR Coverage check]

:heart_eyes: **pass** : 68 / 68 (100.00%)




#### file detail

|   |path|covered line|new line|coverage|
|----|----|----|----|----|
|:large_blue_circle:|io/questdb/griffin/FunctionParser.java|3|3|100.00%|
|:large_blue_circle:|io/questdb/griffin/SqlCodeGenerator.java|65|65|100.00%|

**Review by bziobrowski — DISMISSED** [review]

**Comment by bluestreak01** [comment]
@puzpuzpuz failed tests seem relevant to the change

**Comment by puzpuzpuz** [comment]
> @puzpuzpuz failed tests seem relevant to the change

Looking into it.

**Comment by ideoma** [comment]
#### [PR Coverage check]

:heart_eyes: **pass** : 94 / 94 (100.00%)




#### file detail

|   |path|covered line|new line|coverage|
|----|----|----|----|----|
|:large_blue_circle:|io/questdb/griffin/FunctionParser.java|3|3|100.00%|
|:large_blue_circle:|io/questdb/griffin/SqlCodeGenerator.java|91|91|100.00%|

**Comment by puzpuzpuz** [comment]
@bluestreak01 those failures were unrelated with this PR. I've noticed flakiness `FullFwdDataFrameCursorTest.testIndexFailAtRuntimeByWeek3v` and pushed a fix in 79015fe525799f94476afe55afe7f33748bc1d04

We weren't marking table writer as distressed when an error occurred in the `switchPartition` -> `setAppendPosition` -> `setColumnSize` call chain.

**Comment by bluestreak01** [comment]
this PR https://github.com/questdb/questdb/pull/2938 fixes some flaky tests, but it doesn't address those in this CI. They still don't look like something we've seen before

**Comment by puzpuzpuz** [comment]
> They still don't look like something we've seen before

We've merged a bunch of PRs recently, so chances are high that those failures are something new.

**Comment by ideoma** [comment]
#### [PR Coverage check]

:heart_eyes: **pass** : 125 / 138 (90.58%)




#### file detail

|   |path|covered line|new line|coverage|
|----|----|----|----|----|
|:large_blue_circle:|io/questdb/cairo/TableWriter.java|31|44|70.45%|
|:large_blue_circle:|io/questdb/griffin/FunctionParser.java|3|3|100.00%|
|:large_blue_circle:|io/questdb/griffin/SqlCodeGenerator.java|91|91|100.00%|

**Review by marregui — APPROVED** [review]
LGTM

**Review by bziobrowski — DISMISSED** [review]

**Comment by puzpuzpuz** [comment]
@bziobrowski @marregui thanks for the review!

**Review by bluestreak01 — APPROVED** [review]

**Comment by ideoma** [comment]
#### [PR Coverage check]

:heart_eyes: **pass** : 125 / 138 (90.58%)




#### file detail

|   |path|covered line|new line|coverage|
|----|----|----|----|----|
|:large_blue_circle:|io/questdb/cairo/TableWriter.java|31|44|70.45%|
|:large_blue_circle:|io/questdb/griffin/FunctionParser.java|3|3|100.00%|
|:large_blue_circle:|io/questdb/griffin/SqlCodeGenerator.java|91|91|100.00%|

**Pull request merged**
