### PR TITLE
feat(sql): add mid price SQL function

### LINKED ISSUE #4730: Add a pricing midpoint function
### Is your feature request related to a problem?

See https://github.com/questdb/questdb/issues/4620

Find the mid of an asking and bidding price i.e

`mid(DD)` = `mid(bid, ask)` = `avg(bid, ask)`

### Describe the solution you'd like.

_No response_

### Describe alternatives you've considered.

_No response_

### Full Name:

Nick Woolmer

### Affiliation:

QuestDB

### Additional context

_No response_

### PR DESCRIPTION
**Pull request by sklarsa**
fix #4730

### CODE REVIEW

**Comment by ideoma** [comment]
#### [PR Coverage check]

:heart_eyes: **pass** : 15 / 15 (100.00%)




#### file detail

|   |path|covered line|new line|coverage|
|----|----|----|----|----|
|:large_blue_circle:|io/questdb/griffin/engine/functions/finance/MidPriceFunctionFactory.java|15|15|100.00%|

**Comment by sklarsa** [comment]
@nwoolmer I added `isFinite` checks for both args, which I found in some of the`avg` functions. In this case, I think most of the traditional `avg` edge cases are mitigated by the fact that we lock the divisor to `2` in this function.

**Comment by ideoma** [comment]
#### [PR Coverage check]

:heart_eyes: **pass** : 15 / 15 (100.00%)




#### file detail

|   |path|covered line|new line|coverage|
|----|----|----|----|----|
|:large_blue_circle:|io/questdb/griffin/engine/functions/finance/MidPriceFunctionFactory.java|15|15|100.00%|

**Comment by ideoma** [comment]
#### [PR Coverage check]

:heart_eyes: **pass** : 15 / 15 (100.00%)




#### file detail

|   |path|covered line|new line|coverage|
|----|----|----|----|----|
|:large_blue_circle:|io/questdb/griffin/engine/functions/finance/MidPriceFunctionFactory.java|15|15|100.00%|

**Comment by ideoma** [comment]
#### [PR Coverage check]

:heart_eyes: **pass** : 15 / 15 (100.00%)




#### file detail

|   |path|covered line|new line|coverage|
|----|----|----|----|----|
|:large_blue_circle:|io/questdb/griffin/engine/functions/finance/MidPriceFunctionFactory.java|15|15|100.00%|

**Pull request merged**
