### PR TITLE
fix(sql): breaking change 💥 - use PostgreSQL type names in information_schema.columns()

### PR DESCRIPTION
**Pull request by jerrinot**
## Changes
- Modified `information_schema.columns()` to return PostgreSQL and SQL Standard-compliant type names instead of QuestDB native types
- Added new view `information_schema.questdb_columns()` that retains the original QuestDB native type names

## Benefits
- Improved compatibility with BI tools and applications that expect standard PostgreSQL type names (e.g., Power BI)
- Maintains backward compatibility through the new `questdb_columns()` view for applications dependent on QuestDB native types

## Migration
Applications requiring QuestDB native type names should update their queries to use `information_schema.questdb_columns()` instead of `information_schema.columns()`.

## Webconsole Compatibility Notes
- New webconsole is fully compatible with old server versions through a type name fallback mechanism implemented in https://github.com/questdb/ui/pull/359
- Old webconsole remains compatible with new server versions. Note: Code completion hints will display SQL standard types instead of QuestDB native types

### CODE REVIEW

**Comment by glasstiger** [comment]
#### [PR Coverage check]

:heart_eyes: **pass** : 30 / 31 (96.77%)




#### file detail

|   |path|covered line|new line|coverage|
|----|----|----|----|----|
|:large_blue_circle:|io/questdb/griffin/engine/functions/catalogue/InformationSchemaColumnsFunctionFactory.java|25|26|96.15%|
|:large_blue_circle:|io/questdb/griffin/engine/functions/catalogue/InformationSchemaQuestDBColumnsFunctionFactory.java|5|5|100.00%|

**Comment by glasstiger** [comment]
#### [PR Coverage check]

:heart_eyes: **pass** : 30 / 31 (96.77%)




#### file detail

|   |path|covered line|new line|coverage|
|----|----|----|----|----|
|:large_blue_circle:|io/questdb/griffin/engine/functions/catalogue/InformationSchemaColumnsFunctionFactory.java|25|26|96.15%|
|:large_blue_circle:|io/questdb/griffin/engine/functions/catalogue/InformationSchemaQuestDBColumnsFunctionFactory.java|5|5|100.00%|

**Review by bluestreak01 — APPROVED** [review]

**Comment by glasstiger** [comment]
#### [PR Coverage check]

:heart_eyes: **pass** : 40 / 41 (97.56%)




#### file detail

|   |path|covered line|new line|coverage|
|----|----|----|----|----|
|:large_blue_circle:|io/questdb/griffin/engine/functions/catalogue/InformationSchemaColumnsFunctionFactory.java|35|36|97.22%|
|:large_blue_circle:|io/questdb/griffin/engine/functions/catalogue/InformationSchemaQuestDBColumnsFunctionFactory.java|5|5|100.00%|

**Comment by glasstiger** [comment]
#### [PR Coverage check]

:heart_eyes: **pass** : 40 / 41 (97.56%)




#### file detail

|   |path|covered line|new line|coverage|
|----|----|----|----|----|
|:large_blue_circle:|io/questdb/griffin/engine/functions/catalogue/InformationSchemaColumnsFunctionFactory.java|35|36|97.22%|
|:large_blue_circle:|io/questdb/griffin/engine/functions/catalogue/InformationSchemaQuestDBColumnsFunctionFactory.java|5|5|100.00%|

**Pull request merged**
