### PR TITLE
test(sql): fix flaky copy test

### LINKED ISSUE #2408: Flaky testLocalCopyFrom
### Describe the bug

Log attached:

[82.txt.zip](https://github.com/questdb/questdb/files/9282589/82.txt.zip)

Notable problem:

```
2022-08-06T06:07:53.4268258Z 2022-08-06T06:07:53.426604Z I i.q.c.p.WriterPool << [table=`x`, thread=2612]
2022-08-06T06:07:53.4269081Z 2022-08-06T06:07:53.426611Z I i.q.c.p.WriterPool << [table=`__systext_import_log`, thread=2612]
2022-08-06T06:07:53.4275133Z java.lang.NullPointerException
2022-08-06T06:07:53.4279764Z 	at io.questdb.cutlass.text.SerialCsvFileImporter.process(SerialCsvFileImporter.java:157)
2022-08-06T06:07:53.4283791Z 	at io.questdb.cutlass.text.TextImportRequestJob.runSerially(TextImportRequestJob.java:185)
2022-08-06T06:07:53.4287583Z 	at io.questdb.mp.SynchronizedJob.run(SynchronizedJob.java:39)
2022-08-06T06:07:53.4292424Z 	at io.questdb.mp.Worker.run(Worker.java:116)
2022-08-06T06:07:53.4300172Z 2022-08-06T06:07:53.429470Z I pg-server scheduling disconnect [fd=22, reason=15]
2022-08-06T06:07:53.4301247Z 2022-08-06T06:07:53.429510Z I i.q.c.p.PGWireServer closed

```
### To reproduce

_No response_

### Expected Behavior

_No response_

### Environment

```markdown
- **QuestDB version**:
- **OS**:
- **Browser**:
```

### Additional context

_No response_

### PR DESCRIPTION
**Pull request by puzpuzpuz**
Closes #2408

### CODE REVIEW

**Comment by questdb-butler** [comment]
<table>
  <thead>
    <tr>
      <th width="50"></th>
      <th width="100%" data-danger-table="true">Fails</th>
    </tr>
  </thead>
  <tbody><tr>
      <td>:no_entry_sign:</td>
      <td>

  Please update the PR title to match this format:
`type(subType): description`

Where `type` is one of:
`feat`, `fix`, `chore`, `docs`, `style`, `refactor`, `perf`, `test`, `build`, `ci`, `chore`, `revert`

And: `subType` is one of:
`build`, `sql`, `log`, `mig`, `core`, `ilp`, `pgwire`, `http`, `conf`

For Example:

```
perf(sql): improve pattern matching performance for SELECT sub-queries
```
  </td>
    </tr>
  </tbody>
</table>




<p align="right">
  Generated by :no_entry_sign: <a href="https://danger.systems/js">dangerJS</a> against a8e8df19783cf9423982ac24212c9c8413e3f06b
</p>

**Comment by bluestreak01** [comment]
How does this fix the NPE?

**Comment by puzpuzpuz** [comment]
> How does this fix the NPE?

That's a good question. :)

`pool.halt()` was racing with `AutoClosable` (try-with-resources) behavior of `processingJob`, i.e. under certain unlucky conditions `processingJob.close()` call could be made before the `TextImportRequestTask` task gets fully executed. The reason is that the `assertEventually()` check passed to the `runWithTextImportRequestJob` method was checking presence of rows in the imported table. The rows insertion is not the last step in the task handling, hence try-with-resources' `close()` call was racing with the pool.

**Review by ideoma — APPROVED** [review]
well done!

**Pull request merged**
