### PR TITLE
chore(core): fix web console bundling in final artifact

### PR DESCRIPTION
**Pull request by puzpuzpuz**
#1725 seems to have broken Web Console bundling in Maven builds: `public.zip` is no longer included in the final jar file. That's because `package` phase comes after `resources`. This PR changes the phase to `generate-resources` in order to fix the issue.

Also removes `ui/utils/deploy.js` since it's no longer used.

### CODE REVIEW

**Comment by insmac** [comment]
On an Intel and M1 Pro Mac the Web Console build directory tree is different when run from maven and via `npm run build` directly.

The maven-triggered one does not contain any files in `assets` directory - the folder is empty. These files are copied there using a `CopyWebpackPlugin` with small differences between dev and prod .

Correct directory tree:
CleanShot 2021-12-28 at 17 25 03@2x

**Comment by puzpuzpuz** [comment]
> The maven-triggered one does not contain any files in `assets` directory - the folder is empty.

@insmac There was another problem in maven-assembly-plugin configuration. It should be fixed by 1737b2c774da59c4ee7c96fe52f829eba31b85bd. Could you check once again?

**Review by insmac — DISMISSED** [review]
I can confirm the assembly works properly on Mac after the latest commit.

CleanShot 2021-12-29 at 09 13 56@2x

**Comment by puzpuzpuz** [comment]
@insmac the problem with fonts I've noticed should be fixed in 1e8e1f11a8a693db1973b2a0682a3d995544138

The problem was related with corrupted font files. See `OTS parsing error` messages in the below screenshot of Chrome console.
Screenshot from 2021-12-29 13-41-37

**Review by bluestreak01 — APPROVED** [review]

**Pull request merged**
