### PR TITLE
Throw invalid date exception on negative time interval

### PR DESCRIPTION
**Pull request by eugenels**

### CODE REVIEW

**Comment by ideoma** [comment]
#### [PR Coverage check]

:heart_eyes: **pass** : 7 / 8 (87.50%)




#### file detail

|   |path|covered line|new line|coverage|
|----|----|----|----|----|
|:large_blue_circle:|io/questdb/griffin/model/IntervalUtils.java|7|8|87.50%|

**Comment by ideoma** [comment]
#### [PR Coverage check]

:heart_eyes: **pass** : 128 / 138 (92.75%)




#### file detail

|   |path|covered line|new line|coverage|
|----|----|----|----|----|
|:large_blue_circle:|io/questdb/cairo/ColumnType.java|0|1|00.00%|
|:large_blue_circle:|io/questdb/cairo/TableWriter.java|4|10|40.00%|
|:large_blue_circle:|io/questdb/griffin/engine/functions/rnd/RndGeoHashFunctionFactory.java|3|5|60.00%|
|:large_blue_circle:|io/questdb/griffin/model/IntervalUtils.java|7|8|87.50%|
|:large_blue_circle:|io/questdb/cutlass/line/CairoLineProtoParserSupport.java|41|41|100.00%|
|:large_blue_circle:|io/questdb/griffin/engine/functions/cast/CastStrToGeoHashFunctionFactory.java|1|1|100.00%|
|:large_blue_circle:|io/questdb/cutlass/line/tcp/LineTcpMeasurementScheduler.java|4|4|100.00%|
|:large_blue_circle:|io/questdb/cutlass/line/udp/CairoLineProtoParser.java|25|25|100.00%|
|:large_blue_circle:|io/questdb/std/Rnd.java|4|4|100.00%|
|:large_blue_circle:|io/questdb/cutlass/line/tcp/NewLineProtoParser.java|3|3|100.00%|
|:large_blue_circle:|io/questdb/cairo/GeoHashes.java|36|36|100.00%|

**Comment by ideoma** [comment]
#### [PR Coverage check]

:heart_eyes: **pass** : 128 / 138 (92.75%)




#### file detail

|   |path|covered line|new line|coverage|
|----|----|----|----|----|
|:large_blue_circle:|io/questdb/cairo/ColumnType.java|0|1|00.00%|
|:large_blue_circle:|io/questdb/cairo/TableWriter.java|4|10|40.00%|
|:large_blue_circle:|io/questdb/griffin/engine/functions/rnd/RndGeoHashFunctionFactory.java|3|5|60.00%|
|:large_blue_circle:|io/questdb/griffin/model/IntervalUtils.java|7|8|87.50%|
|:large_blue_circle:|io/questdb/cutlass/line/CairoLineProtoParserSupport.java|41|41|100.00%|
|:large_blue_circle:|io/questdb/griffin/engine/functions/cast/CastStrToGeoHashFunctionFactory.java|1|1|100.00%|
|:large_blue_circle:|io/questdb/cutlass/line/tcp/LineTcpMeasurementScheduler.java|4|4|100.00%|
|:large_blue_circle:|io/questdb/cutlass/line/udp/CairoLineProtoParser.java|25|25|100.00%|
|:large_blue_circle:|io/questdb/std/Rnd.java|4|4|100.00%|
|:large_blue_circle:|io/questdb/cutlass/line/tcp/NewLineProtoParser.java|3|3|100.00%|
|:large_blue_circle:|io/questdb/cairo/GeoHashes.java|36|36|100.00%|

**Review by bluestreak01 — APPROVED** [review]

**Comment by ideoma** [comment]
#### [PR Coverage check]

:heart_eyes: **pass** : 7 / 8 (87.50%)




#### file detail

|   |path|covered line|new line|coverage|
|----|----|----|----|----|
|:large_blue_circle:|io/questdb/griffin/model/IntervalUtils.java|7|8|87.50%|

**Comment by ideoma** [comment]
#### [PR Coverage check]

:heart_eyes: **pass** : 7 / 8 (87.50%)




#### file detail

|   |path|covered line|new line|coverage|
|----|----|----|----|----|
|:large_blue_circle:|io/questdb/griffin/model/IntervalUtils.java|7|8|87.50%|

**Pull request merged**
