### PR TITLE
fix(sql): improve order by handling in optimizer

### LINKED ISSUE #2330: slow limit -N queries without order by ts queries
### Describe the bug

Looks like in latest release queries that use limit -N without explicit order by issued against tables with designated timestamp traverse partitions from first to last . This can make a big difference for tables with many partitions that get queried rarely  enough to not be present in os cache . 

### To reproduce

```sql
create table test ( ts timestamp, d double, f float, i int, l long, s1 string, s2 string, sy symbol index) timestamp(ts) partition by day;

insert into test 
SELECT cast( (x*2500000)  as timestamp), x, x, cast(x as int), x, 's1' || (x%10), 's2' || (x%10), 'sy' || (x%10) 
from long_sequence(100000000);

selecT count(*) from test limit -5; 
--observe many 'open partition'  messages in logs

--after restart run
selecT * from test order by ts desc limit 5; 
--check that there's only 1 'open partition' message
```

### Expected Behavior

_No response_

### Environment

```markdown
- **QuestDB version**:  6.4.4-snapshot
- **OS**: Windows
- **Browser**: Chrome
```

### Additional context

_No response_

### PR DESCRIPTION
**Pull request by bziobrowski**
Fixes #2330 

All sql examples below use demo instance tables . 

Changes :  
- improve execution of queries ordered by designated timestamp desc,  e.g. 
```sql
explain select * from trips where pickup_datetime > dateadd('m', -1, now()) order by pickup_datetime desc 
DataFrame
    Row backward scan
    Interval backward scan on: trips
      intervals: [static=[0,9223372036854775807,281481419161601,4294967296] dynamic=[dateadd('m',-1,now())]]
```

- improve execution of queries with negative limit and no order by via  backward scanning from end of table
```sql
explain select * from trips desc limit -10
Sort light
  keys: [ts]
    Limit lo: 5
        DataFrame
            Row backward scan
            Frame backward scan on: trips
```

- improve execution of async filter with order by timestamp desc and negative limit by scanning from start and then reordering rows . 
```sql
explain select * from trips where passenger_count > 0 order by pickup_datetime desc limit -10 ;

Async JIT Filter
  limit: 10
  filter: 0<passenger_count
  workers: 14
    DataFrame
        Row forward scan
        Frame forward scan on: trips
```

- prevent copying of limit advice into `distinct `'s subquery. The following queries apply  limit 10 to async jit filter executed before distinct :
```sql
select distinct passenger_count from trips where passenger_count < 5 limit 10
select distinct pickup_datetime from trips where passenger_count < 5 limit 10
```
Explain shows: 
```sql
Limit lo: 10
    DistinctTimeSeries
      keys: pickup_datetime
        SelectedRecord
            Async JIT Filter
              limit: 10 <-- WRONG
...
```

- reduce need for explicit timestamp(column) function use by maintaining timestamp metadata  on order by ts, col1, col2, ... . 
For example - the following query doesn't need `timestamp(pickup_datetime)` anymore : 
```sql
select * from 
(select * from trips order by pickup_datetime asc, passenger_count limit 10) 
lt join 
(select * from trips) order by pickup_datetime asc
```

- avoid unnecessary sorting by designated timestamp, e.g. 
```sql
explain select * from (select * from trips order by pickup_datetime desc) t1 cross join trips t2 order by t1.pickup_datetime
SelectedRecord
    Cross Join
        DataFrame
            Row forward scan
            Frame forward scan on: trips
        DataFrame
            Row forward scan
            Frame forward scan on: trips
```

### CODE REVIEW

**Comment by ideoma** [comment]
#### [PR Coverage check]

:heart_eyes: **pass** : 120 / 121 (99.17%)




#### file detail

|   |path|covered line|new line|coverage|
|----|----|----|----|----|
|:large_blue_circle:|io/questdb/cairo/IntervalBwdDataFrameCursorFactory.java|2|3|66.67%|
|:large_blue_circle:|io/questdb/cairo/FullBwdDataFrameCursorFactory.java|6|6|100.00%|
|:large_blue_circle:|io/questdb/griffin/engine/table/AsyncFilteredNegativeLimitRecordCursor.java|7|7|100.00%|
|:large_blue_circle:|io/questdb/griffin/engine/join/NestedLoopLeftJoinRecordCursorFactory.java|1|1|100.00%|
|:large_blue_circle:|io/questdb/griffin/engine/union/ExceptRecordCursorFactory.java|1|1|100.00%|
|:large_blue_circle:|io/questdb/griffin/engine/orderby/SortedLightRecordCursorFactory.java|1|1|100.00%|
|:large_blue_circle:|io/questdb/griffin/engine/orderby/LimitedSizeSortedLightRecordCursorFactory.java|1|1|100.00%|
|:large_blue_circle:|io/questdb/griffin/engine/join/CrossJoinRecordCursorFactory.java|1|1|100.00%|
|:large_blue_circle:|io/questdb/griffin/engine/union/IntersectRecordCursorFactory.java|1|1|100.00%|
|:large_blue_circle:|io/questdb/griffin/engine/table/AsyncJitFilteredRecordCursorFactory.java|2|2|100.00%|
|:large_blue_circle:|io/questdb/griffin/engine/orderby/SortedRecordCursorFactory.java|6|6|100.00%|
|:large_blue_circle:|io/questdb/griffin/engine/LimitRecordCursorFactory.java|1|1|100.00%|
|:large_blue_circle:|io/questdb/griffin/SqlCodeGenerator.java|12|12|100.00%|
|:large_blue_circle:|io/questdb/griffin/SqlOptimiser.java|73|73|100.00%|
|:large_blue_circle:|io/questdb/griffin/engine/table/AsyncFilteredRecordCursorFactory.java|2|2|100.00%|
|:large_blue_circle:|io/questdb/griffin/engine/table/BwdDataFrameRowCursorFactory.java|3|3|100.00%|

**Comment by ideoma** [comment]
#### [PR Coverage check]

:heart_eyes: **pass** : 120 / 121 (99.17%)




#### file detail

|   |path|covered line|new line|coverage|
|----|----|----|----|----|
|:large_blue_circle:|io/questdb/cairo/IntervalBwdDataFrameCursorFactory.java|2|3|66.67%|
|:large_blue_circle:|io/questdb/cairo/FullBwdDataFrameCursorFactory.java|6|6|100.00%|
|:large_blue_circle:|io/questdb/griffin/engine/table/AsyncFilteredNegativeLimitRecordCursor.java|7|7|100.00%|
|:large_blue_circle:|io/questdb/griffin/engine/join/NestedLoopLeftJoinRecordCursorFactory.java|1|1|100.00%|
|:large_blue_circle:|io/questdb/griffin/engine/union/ExceptRecordCursorFactory.java|1|1|100.00%|
|:large_blue_circle:|io/questdb/griffin/engine/orderby/SortedLightRecordCursorFactory.java|1|1|100.00%|
|:large_blue_circle:|io/questdb/griffin/engine/orderby/LimitedSizeSortedLightRecordCursorFactory.java|1|1|100.00%|
|:large_blue_circle:|io/questdb/griffin/engine/join/CrossJoinRecordCursorFactory.java|1|1|100.00%|
|:large_blue_circle:|io/questdb/griffin/engine/union/IntersectRecordCursorFactory.java|1|1|100.00%|
|:large_blue_circle:|io/questdb/griffin/engine/table/AsyncJitFilteredRecordCursorFactory.java|2|2|100.00%|
|:large_blue_circle:|io/questdb/griffin/engine/orderby/SortedRecordCursorFactory.java|6|6|100.00%|
|:large_blue_circle:|io/questdb/griffin/engine/LimitRecordCursorFactory.java|1|1|100.00%|
|:large_blue_circle:|io/questdb/griffin/SqlCodeGenerator.java|12|12|100.00%|
|:large_blue_circle:|io/questdb/griffin/SqlOptimiser.java|73|73|100.00%|
|:large_blue_circle:|io/questdb/griffin/engine/table/AsyncFilteredRecordCursorFactory.java|2|2|100.00%|
|:large_blue_circle:|io/questdb/griffin/engine/table/BwdDataFrameRowCursorFactory.java|3|3|100.00%|

**Comment by ideoma** [comment]
#### [PR Coverage check]

:heart_eyes: **pass** : 120 / 121 (99.17%)




#### file detail

|   |path|covered line|new line|coverage|
|----|----|----|----|----|
|:large_blue_circle:|io/questdb/cairo/IntervalBwdDataFrameCursorFactory.java|2|3|66.67%|
|:large_blue_circle:|io/questdb/cairo/FullBwdDataFrameCursorFactory.java|6|6|100.00%|
|:large_blue_circle:|io/questdb/griffin/engine/table/AsyncFilteredNegativeLimitRecordCursor.java|7|7|100.00%|
|:large_blue_circle:|io/questdb/griffin/engine/join/NestedLoopLeftJoinRecordCursorFactory.java|1|1|100.00%|
|:large_blue_circle:|io/questdb/griffin/engine/union/ExceptRecordCursorFactory.java|1|1|100.00%|
|:large_blue_circle:|io/questdb/griffin/engine/orderby/SortedLightRecordCursorFactory.java|1|1|100.00%|
|:large_blue_circle:|io/questdb/griffin/engine/orderby/LimitedSizeSortedLightRecordCursorFactory.java|1|1|100.00%|
|:large_blue_circle:|io/questdb/griffin/engine/join/CrossJoinRecordCursorFactory.java|1|1|100.00%|
|:large_blue_circle:|io/questdb/griffin/engine/union/IntersectRecordCursorFactory.java|1|1|100.00%|
|:large_blue_circle:|io/questdb/griffin/engine/table/AsyncJitFilteredRecordCursorFactory.java|2|2|100.00%|
|:large_blue_circle:|io/questdb/griffin/engine/orderby/SortedRecordCursorFactory.java|6|6|100.00%|
|:large_blue_circle:|io/questdb/griffin/engine/LimitRecordCursorFactory.java|1|1|100.00%|
|:large_blue_circle:|io/questdb/griffin/SqlCodeGenerator.java|12|12|100.00%|
|:large_blue_circle:|io/questdb/griffin/SqlOptimiser.java|73|73|100.00%|
|:large_blue_circle:|io/questdb/griffin/engine/table/AsyncFilteredRecordCursorFactory.java|2|2|100.00%|
|:large_blue_circle:|io/questdb/griffin/engine/table/BwdDataFrameRowCursorFactory.java|3|3|100.00%|

**Comment by bluestreak01** [comment]
This is awesome PR @bziobrowski

**Review by bluestreak01 — APPROVED** [review]

**Comment by ideoma** [comment]
#### [PR Coverage check]

:heart_eyes: **pass** : 120 / 121 (99.17%)




#### file detail

|   |path|covered line|new line|coverage|
|----|----|----|----|----|
|:large_blue_circle:|io/questdb/cairo/IntervalBwdDataFrameCursorFactory.java|2|3|66.67%|
|:large_blue_circle:|io/questdb/cairo/FullBwdDataFrameCursorFactory.java|6|6|100.00%|
|:large_blue_circle:|io/questdb/griffin/engine/table/AsyncFilteredNegativeLimitRecordCursor.java|7|7|100.00%|
|:large_blue_circle:|io/questdb/griffin/engine/join/NestedLoopLeftJoinRecordCursorFactory.java|1|1|100.00%|
|:large_blue_circle:|io/questdb/griffin/engine/union/ExceptRecordCursorFactory.java|1|1|100.00%|
|:large_blue_circle:|io/questdb/griffin/engine/orderby/SortedLightRecordCursorFactory.java|1|1|100.00%|
|:large_blue_circle:|io/questdb/griffin/engine/orderby/LimitedSizeSortedLightRecordCursorFactory.java|1|1|100.00%|
|:large_blue_circle:|io/questdb/griffin/engine/join/CrossJoinRecordCursorFactory.java|1|1|100.00%|
|:large_blue_circle:|io/questdb/griffin/engine/union/IntersectRecordCursorFactory.java|1|1|100.00%|
|:large_blue_circle:|io/questdb/griffin/engine/table/AsyncJitFilteredRecordCursorFactory.java|2|2|100.00%|
|:large_blue_circle:|io/questdb/griffin/engine/orderby/SortedRecordCursorFactory.java|6|6|100.00%|
|:large_blue_circle:|io/questdb/griffin/engine/LimitRecordCursorFactory.java|1|1|100.00%|
|:large_blue_circle:|io/questdb/griffin/SqlCodeGenerator.java|12|12|100.00%|
|:large_blue_circle:|io/questdb/griffin/SqlOptimiser.java|73|73|100.00%|
|:large_blue_circle:|io/questdb/griffin/engine/table/AsyncFilteredRecordCursorFactory.java|2|2|100.00%|
|:large_blue_circle:|io/questdb/griffin/engine/table/BwdDataFrameRowCursorFactory.java|3|3|100.00%|

**Comment by ideoma** [comment]
#### [PR Coverage check]

:heart_eyes: **pass** : 120 / 121 (99.17%)




#### file detail

|   |path|covered line|new line|coverage|
|----|----|----|----|----|
|:large_blue_circle:|io/questdb/cairo/IntervalBwdDataFrameCursorFactory.java|2|3|66.67%|
|:large_blue_circle:|io/questdb/cairo/FullBwdDataFrameCursorFactory.java|6|6|100.00%|
|:large_blue_circle:|io/questdb/griffin/engine/table/AsyncFilteredNegativeLimitRecordCursor.java|7|7|100.00%|
|:large_blue_circle:|io/questdb/griffin/engine/join/NestedLoopLeftJoinRecordCursorFactory.java|1|1|100.00%|
|:large_blue_circle:|io/questdb/griffin/engine/union/ExceptRecordCursorFactory.java|1|1|100.00%|
|:large_blue_circle:|io/questdb/griffin/engine/orderby/SortedLightRecordCursorFactory.java|1|1|100.00%|
|:large_blue_circle:|io/questdb/griffin/engine/orderby/LimitedSizeSortedLightRecordCursorFactory.java|1|1|100.00%|
|:large_blue_circle:|io/questdb/griffin/engine/join/CrossJoinRecordCursorFactory.java|1|1|100.00%|
|:large_blue_circle:|io/questdb/griffin/engine/union/IntersectRecordCursorFactory.java|1|1|100.00%|
|:large_blue_circle:|io/questdb/griffin/engine/table/AsyncJitFilteredRecordCursorFactory.java|2|2|100.00%|
|:large_blue_circle:|io/questdb/griffin/engine/orderby/SortedRecordCursorFactory.java|6|6|100.00%|
|:large_blue_circle:|io/questdb/griffin/engine/LimitRecordCursorFactory.java|1|1|100.00%|
|:large_blue_circle:|io/questdb/griffin/SqlCodeGenerator.java|12|12|100.00%|
|:large_blue_circle:|io/questdb/griffin/SqlOptimiser.java|73|73|100.00%|
|:large_blue_circle:|io/questdb/griffin/engine/table/AsyncFilteredRecordCursorFactory.java|2|2|100.00%|
|:large_blue_circle:|io/questdb/griffin/engine/table/BwdDataFrameRowCursorFactory.java|3|3|100.00%|

**Pull request merged**
