### PR TITLE
test(core): refactor O3 failure tests into fuzz tests

### PR DESCRIPTION
**Pull request by ideoma**
This turns tests of `O3FailureTest` which fail on allocate into Fuzz tests where the failure point is random.

This helped to identify a few more potential leaks on failures. Also, the change makes the development more stable where changing the code does not lead to an update in failure counters.

### CODE REVIEW

**Comment by ideoma** [comment]
#### [PR Coverage check]

:disappointed: **fail** : 2 / 11 (18.18%)




#### file detail

|   |path|covered line|new line|coverage|
|----|----|----|----|----|
|:large_blue_circle:|io/questdb/cairo/pool/WriterPool.java|0|9|00.00%|
|:large_blue_circle:|io/questdb/cairo/O3CopyJob.java|2|2|100.00%|

**Comment by ideoma** [comment]
The new code is eventually coverage by the randomised tests.

**Review by bluestreak01 — DISMISSED** [review]

**Comment by ideoma** [comment]
#### [PR Coverage check]

:disappointed: **fail** : 6 / 21 (28.57%)




#### file detail

|   |path|covered line|new line|coverage|
|----|----|----|----|----|
|:large_blue_circle:|io/questdb/cairo/BitmapIndexWriter.java|0|1|00.00%|
|:large_blue_circle:|io/questdb/cairo/pool/WriterPool.java|0|9|00.00%|
|:large_blue_circle:|io/questdb/cairo/TableUtils.java|1|6|16.67%|
|:large_blue_circle:|io/questdb/cairo/vm/MemoryCMARWImpl.java|5|5|100.00%|

**Comment by ideoma** [comment]
#### [PR Coverage check]

:disappointed: **fail** : 6 / 21 (28.57%)




#### file detail

|   |path|covered line|new line|coverage|
|----|----|----|----|----|
|:large_blue_circle:|io/questdb/cairo/BitmapIndexWriter.java|0|1|00.00%|
|:large_blue_circle:|io/questdb/cairo/pool/WriterPool.java|0|9|00.00%|
|:large_blue_circle:|io/questdb/std/Files.java|1|6|16.67%|
|:large_blue_circle:|io/questdb/cairo/vm/MemoryCMARWImpl.java|5|5|100.00%|

**Pull request merged**
