### PR TITLE
fix(ilp): fix 'maximum buffer size exceeded' in ILP client

### PR DESCRIPTION
**Pull request by jerrinot**
when adding a row into an empty `Sender` buffer and it happens to trigger interval-based auto-flush then flushes might stop working entirely.

workaround: disable interval-based flushes.

### CODE REVIEW

**Comment by jerrinot** [comment]
a Windows failure due to https://github.com/questdb/questdb/issues/2774 :-(

**Comment by ideoma** [comment]
#### [PR Coverage check]

:heart_eyes: **pass** : 1 / 1 (100.00%)




#### file detail

|   |path|covered line|new line|coverage|
|----|----|----|----|----|
|:large_blue_circle:|io/questdb/cutlass/line/http/LineHttpSender.java|1|1|100.00%|

**Review by ideoma — APPROVED** [review]

**Comment by jerrinot** [comment]
created https://github.com/questdb/questdb/issues/4374

**Comment by ideoma** [comment]
#### [PR Coverage check]

:heart_eyes: **pass** : 1 / 1 (100.00%)




#### file detail

|   |path|covered line|new line|coverage|
|----|----|----|----|----|
|:large_blue_circle:|io/questdb/cutlass/line/http/LineHttpSender.java|1|1|100.00%|

**Pull request merged**
