### PR TITLE
chore(core): hardening checks and tidy up

### PR DESCRIPTION
**Pull request by bluestreak01**
Closes https://github.com/questdb/questdb/issues/2551

Addresses @jerrinot comments in https://github.com/questdb/questdb/pull/2423

### CODE REVIEW

**Comment by ideoma** [comment]
#### [PR Coverage check]

:heart_eyes: **pass** : 66 / 76 (86.84%)




#### file detail

|   |path|covered line|new line|coverage|
|----|----|----|----|----|
|:large_blue_circle:|io/questdb/griffin/RecordToRowCopierUtils.java|21|31|67.74%|
|:large_blue_circle:|io/questdb/cairo/vm/api/MemoryCARW.java|1|1|100.00%|
|:large_blue_circle:|io/questdb/std/Long256FromCharSequenceDecoder.java|18|18|100.00%|
|:large_blue_circle:|io/questdb/cairo/vm/MemoryPARWImpl.java|2|2|100.00%|
|:large_blue_circle:|io/questdb/cutlass/text/TextImportTask.java|6|6|100.00%|
|:large_blue_circle:|io/questdb/std/Numbers.java|10|10|100.00%|
|:large_blue_circle:|io/questdb/griffin/engine/functions/eq/EqLong256StrFunctionFactory.java|1|1|100.00%|
|:large_blue_circle:|io/questdb/griffin/SqlUtil.java|7|7|100.00%|

**Comment by ideoma** [comment]
#### [PR Coverage check]

:heart_eyes: **pass** : 66 / 76 (86.84%)




#### file detail

|   |path|covered line|new line|coverage|
|----|----|----|----|----|
|:large_blue_circle:|io/questdb/griffin/RecordToRowCopierUtils.java|21|31|67.74%|
|:large_blue_circle:|io/questdb/cairo/vm/api/MemoryCARW.java|1|1|100.00%|
|:large_blue_circle:|io/questdb/std/Long256FromCharSequenceDecoder.java|18|18|100.00%|
|:large_blue_circle:|io/questdb/cairo/vm/MemoryPARWImpl.java|2|2|100.00%|
|:large_blue_circle:|io/questdb/cutlass/text/TextImportTask.java|6|6|100.00%|
|:large_blue_circle:|io/questdb/std/Numbers.java|10|10|100.00%|
|:large_blue_circle:|io/questdb/griffin/engine/functions/eq/EqLong256StrFunctionFactory.java|1|1|100.00%|
|:large_blue_circle:|io/questdb/griffin/SqlUtil.java|7|7|100.00%|

**Review by marregui — APPROVED** [review]
LGTM

**Comment by ideoma** [comment]
#### [PR Coverage check]

:heart_eyes: **pass** : 66 / 76 (86.84%)




#### file detail

|   |path|covered line|new line|coverage|
|----|----|----|----|----|
|:large_blue_circle:|io/questdb/griffin/RecordToRowCopierUtils.java|21|31|67.74%|
|:large_blue_circle:|io/questdb/cairo/vm/api/MemoryCARW.java|1|1|100.00%|
|:large_blue_circle:|io/questdb/std/Long256FromCharSequenceDecoder.java|18|18|100.00%|
|:large_blue_circle:|io/questdb/cairo/vm/MemoryPARWImpl.java|2|2|100.00%|
|:large_blue_circle:|io/questdb/cutlass/text/TextImportTask.java|6|6|100.00%|
|:large_blue_circle:|io/questdb/std/Numbers.java|10|10|100.00%|
|:large_blue_circle:|io/questdb/griffin/engine/functions/eq/EqLong256StrFunctionFactory.java|1|1|100.00%|
|:large_blue_circle:|io/questdb/griffin/SqlUtil.java|7|7|100.00%|

**Comment by ideoma** [comment]
#### [PR Coverage check]

:heart_eyes: **pass** : 66 / 76 (86.84%)




#### file detail

|   |path|covered line|new line|coverage|
|----|----|----|----|----|
|:large_blue_circle:|io/questdb/griffin/RecordToRowCopierUtils.java|21|31|67.74%|
|:large_blue_circle:|io/questdb/cairo/vm/api/MemoryCARW.java|1|1|100.00%|
|:large_blue_circle:|io/questdb/std/Long256FromCharSequenceDecoder.java|18|18|100.00%|
|:large_blue_circle:|io/questdb/cairo/vm/MemoryPARWImpl.java|2|2|100.00%|
|:large_blue_circle:|io/questdb/cutlass/text/TextImportTask.java|6|6|100.00%|
|:large_blue_circle:|io/questdb/std/Numbers.java|10|10|100.00%|
|:large_blue_circle:|io/questdb/griffin/engine/functions/eq/EqLong256StrFunctionFactory.java|1|1|100.00%|
|:large_blue_circle:|io/questdb/griffin/SqlUtil.java|7|7|100.00%|

**Comment by ideoma** [comment]
#### [PR Coverage check]

:heart_eyes: **pass** : 66 / 76 (86.84%)




#### file detail

|   |path|covered line|new line|coverage|
|----|----|----|----|----|
|:large_blue_circle:|io/questdb/griffin/RecordToRowCopierUtils.java|21|31|67.74%|
|:large_blue_circle:|io/questdb/cairo/vm/api/MemoryCARW.java|1|1|100.00%|
|:large_blue_circle:|io/questdb/std/Long256FromCharSequenceDecoder.java|18|18|100.00%|
|:large_blue_circle:|io/questdb/cairo/vm/MemoryPARWImpl.java|2|2|100.00%|
|:large_blue_circle:|io/questdb/cutlass/text/TextImportTask.java|6|6|100.00%|
|:large_blue_circle:|io/questdb/std/Numbers.java|10|10|100.00%|
|:large_blue_circle:|io/questdb/griffin/engine/functions/eq/EqLong256StrFunctionFactory.java|1|1|100.00%|
|:large_blue_circle:|io/questdb/griffin/SqlUtil.java|7|7|100.00%|

**Review by marregui — APPROVED** [review]
LGTM

**Pull request merged**
