### PR TITLE
fix(core): fix commit error when many partitions are added and merged in one transaction

### PR DESCRIPTION
**Pull request by ideoma**
Fix sporadic commit error with errno [2] on opening partition to merge.

```
2022-10-07T08:13:25.893769Z I i.q.c.TableWriter merged partition [table=`People`, ts=1984-12-17T00:00:00.000000Z, txn=8]
2022-10-07T08:13:25.925159Z I i.q.c.TableWriter purged [path=/var/lib/questdb/db/People/1984-12-17]
2022-10-07T08:13:28.565776Z E i.q.c.O3PartitionJob process existing partition error [table=People, e=
io.questdb.cairo.CairoException: [2] could not open read-write [file=/var/lib/questdb/db/People/1984-12-17/timestamp.d]
]
```

Problem occurred because of `TxWriter` partition table could be updated in parallel to reading during O3 commit. While TableWriter were dispatching partition tasks some task can be completed and try to update the partition table on completion in parallel worker threads because of work stealing.

The fix is to defer partitions and _txn file update until the end of all partitions and perform it in the main TableWriter thread. To avoid task stealing because of limited queue size a dedicated sink of Long list is pre-created in the beginning of the transaction. All the values are collected to the sink and applied at the end.

### CODE REVIEW

**Comment by ideoma** [comment]
#### [PR Coverage check]

:heart_eyes: **pass** : 106 / 114 (92.98%)




#### file detail

|   |path|covered line|new line|coverage|
|----|----|----|----|----|
|:large_blue_circle:|io/questdb/cairo/TableWriter.java|105|113|92.92%|
|:large_blue_circle:|io/questdb/cairo/O3CopyJob.java|1|1|100.00%|

**Review by marregui — DISMISSED** [review]
LGTM

**Comment by ideoma** [comment]
#### [PR Coverage check]

:heart_eyes: **pass** : 109 / 117 (93.16%)




#### file detail

|   |path|covered line|new line|coverage|
|----|----|----|----|----|
|:large_blue_circle:|io/questdb/cairo/TableWriter.java|108|116|93.10%|
|:large_blue_circle:|io/questdb/cairo/O3CopyJob.java|1|1|100.00%|

**Comment by ideoma** [comment]
#### [PR Coverage check]

:heart_eyes: **pass** : 109 / 117 (93.16%)




#### file detail

|   |path|covered line|new line|coverage|
|----|----|----|----|----|
|:large_blue_circle:|io/questdb/cairo/TableWriter.java|108|116|93.10%|
|:large_blue_circle:|io/questdb/cairo/O3CopyJob.java|1|1|100.00%|

**Comment by ideoma** [comment]
#### [PR Coverage check]

:heart_eyes: **pass** : 61 / 61 (100.00%)




#### file detail

|   |path|covered line|new line|coverage|
|----|----|----|----|----|
|:large_blue_circle:|io/questdb/cairo/O3CopyJob.java|1|1|100.00%|
|:large_blue_circle:|io/questdb/cairo/TableWriter.java|60|60|100.00%|

**Pull request merged**
