### PR TITLE
fix(log): fix the way alert appender deals with template encoding

### PR DESCRIPTION
**Pull request by marregui**
Revisit sink so that by default the put method is ascii, and there are additional means of putting utf8 text.

### CODE REVIEW

**Comment by ideoma** [comment]
#### [PR Coverage check]

:heart_eyes: **pass** : 13 / 13 (100.00%)




#### file detail

|   |path|covered line|new line|coverage|
|----|----|----|----|----|
|:large_blue_circle:|io/questdb/log/TemplateParser.java|6|6|100.00%|
|:large_blue_circle:|io/questdb/log/LogRecordSink.java|5|5|100.00%|
|:large_blue_circle:|io/questdb/log/HttpLogRecordSink.java|2|2|100.00%|

**Comment by ideoma** [comment]
#### [PR Coverage check]

:heart_eyes: **pass** : 11 / 11 (100.00%)




#### file detail

|   |path|covered line|new line|coverage|
|----|----|----|----|----|
|:large_blue_circle:|io/questdb/log/TemplateParser.java|6|6|100.00%|
|:large_blue_circle:|io/questdb/log/LogRecordSink.java|2|2|100.00%|
|:large_blue_circle:|io/questdb/log/HttpLogRecordSink.java|3|3|100.00%|

**Comment by ideoma** [comment]
#### [PR Coverage check]

:heart_eyes: **pass** : 19 / 19 (100.00%)




#### file detail

|   |path|covered line|new line|coverage|
|----|----|----|----|----|
|:large_blue_circle:|io/questdb/log/TemplateParser.java|6|6|100.00%|
|:large_blue_circle:|io/questdb/log/LogRecordSink.java|10|10|100.00%|
|:large_blue_circle:|io/questdb/log/HttpLogRecordSink.java|3|3|100.00%|

**Review by bluestreak01 — APPROVED** [review]

**Comment by ideoma** [comment]
#### [PR Coverage check]

:heart_eyes: **pass** : 19 / 19 (100.00%)




#### file detail

|   |path|covered line|new line|coverage|
|----|----|----|----|----|
|:large_blue_circle:|io/questdb/log/TemplateParser.java|6|6|100.00%|
|:large_blue_circle:|io/questdb/log/LogRecordSink.java|10|10|100.00%|
|:large_blue_circle:|io/questdb/log/HttpLogRecordSink.java|3|3|100.00%|

**Comment by ideoma** [comment]
#### [PR Coverage check]

:heart_eyes: **pass** : 19 / 19 (100.00%)




#### file detail

|   |path|covered line|new line|coverage|
|----|----|----|----|----|
|:large_blue_circle:|io/questdb/log/TemplateParser.java|6|6|100.00%|
|:large_blue_circle:|io/questdb/log/LogRecordSink.java|10|10|100.00%|
|:large_blue_circle:|io/questdb/log/HttpLogRecordSink.java|3|3|100.00%|

**Comment by ideoma** [comment]
#### [PR Coverage check]

:heart_eyes: **pass** : 19 / 19 (100.00%)




#### file detail

|   |path|covered line|new line|coverage|
|----|----|----|----|----|
|:large_blue_circle:|io/questdb/log/TemplateParser.java|6|6|100.00%|
|:large_blue_circle:|io/questdb/log/LogRecordSink.java|10|10|100.00%|
|:large_blue_circle:|io/questdb/log/HttpLogRecordSink.java|3|3|100.00%|

**Comment by ideoma** [comment]
#### [PR Coverage check]

:heart_eyes: **pass** : 19 / 19 (100.00%)




#### file detail

|   |path|covered line|new line|coverage|
|----|----|----|----|----|
|:large_blue_circle:|io/questdb/log/TemplateParser.java|6|6|100.00%|
|:large_blue_circle:|io/questdb/log/LogRecordSink.java|10|10|100.00%|
|:large_blue_circle:|io/questdb/log/HttpLogRecordSink.java|3|3|100.00%|

**Comment by ideoma** [comment]
#### [PR Coverage check]

:heart_eyes: **pass** : 19 / 19 (100.00%)




#### file detail

|   |path|covered line|new line|coverage|
|----|----|----|----|----|
|:large_blue_circle:|io/questdb/log/TemplateParser.java|6|6|100.00%|
|:large_blue_circle:|io/questdb/log/LogRecordSink.java|10|10|100.00%|
|:large_blue_circle:|io/questdb/log/HttpLogRecordSink.java|3|3|100.00%|

**Pull request merged**
