### PR TITLE
fix(pgwire): added support for `asyncpg` client

### PR DESCRIPTION
**Pull request by bluestreak01**
## AsyncPG support

Tested the following snippet:

```python
import asyncio
import asyncpg

async def run():
    conn = await asyncpg.connect(user='xyz', password='oh',
                                 database='postgres', host='127.0.0.1')
    s = """
            select * from 'tab'
            LIMIT 100
        """
    values = await conn.fetch(s)
    await conn.close()

loop = asyncio.get_event_loop()
loop.run_until_complete(run())
```

and the following for bind variable test:

```python
import asyncio
import asyncpg

async def run():
    conn = await asyncpg.connect(user='xyz', password='oh',
                                 database='postgres', host='127.0.0.1')
    s = """
            select * from 'tab2' where a > $1
            LIMIT 100
        """
    values = await conn.fetch(s, 0.4)
    await conn.close()

loop = asyncio.get_event_loop()
loop.run_until_complete(run())
```

## Bug fixes

- Also, I accidentally stumbled on a memory leak from PG wire. We could just "forget" to release `RecordCursorFactory` instances when using bind variables. This was a genuine memory leak prompted by using JIT factory in a test.

- We were replying "ready for query" to a login attempt with bad credentials. AyncPG client doesn't like that and rightly so. This is fixed in this PR.

- PG wire tests were turning socket linger off on client side. This could lead to flapping tests where under pressure server wasn't receiving complete message.

### CODE REVIEW

**Comment by puzpuzpuz** [comment]
You should test on a prepared statement with some bind variables. That's where the driver didn't work while I was testing it recently.

**Comment by bluestreak01** [comment]
yeah, just tested it and it doesn't work indeed, hence draft now

**Comment by ideoma** [comment]
#### [PR Coverage check]

:heart_eyes: **pass** : 3 / 3 (100.00%)




#### file detail

|   |path|covered line|new line|coverage|
|----|----|----|----|----|
|:large_blue_circle:|io/questdb/cutlass/pgwire/PGConnectionContext.java|3|3|100.00%|

**Comment by ideoma** [comment]
#### [PR Coverage check]

:heart_eyes: **pass** : 3 / 3 (100.00%)




#### file detail

|   |path|covered line|new line|coverage|
|----|----|----|----|----|
|:large_blue_circle:|io/questdb/cutlass/pgwire/PGConnectionContext.java|3|3|100.00%|

**Comment by ideoma** [comment]
#### [PR Coverage check]

:heart_eyes: **pass** : 3 / 3 (100.00%)




#### file detail

|   |path|covered line|new line|coverage|
|----|----|----|----|----|
|:large_blue_circle:|io/questdb/cutlass/pgwire/PGConnectionContext.java|3|3|100.00%|

**Comment by bluestreak01** [comment]
bind variable is actually supported with this change, we don't seem to report "invalid user/password" correctly to this driver. I have a test for bind variables but its leaking memory somewhere :(

**Comment by bluestreak01** [comment]
fun fact, it is actually JIT that's leaking memory. May be it isn't, but its lazily allocating something in a static `compiler` instance

**Comment by bluestreak01** [comment]
this is a legit memory leak in PG wire server

**Comment by ideoma** [comment]
#### [PR Coverage check]

:heart_eyes: **pass** : 15 / 16 (93.75%)




#### file detail

|   |path|covered line|new line|coverage|
|----|----|----|----|----|
|:large_blue_circle:|io/questdb/cutlass/pgwire/PGConnectionContext.java|15|16|93.75%|

**Comment by ideoma** [comment]
#### [PR Coverage check]

:heart_eyes: **pass** : 15 / 15 (100.00%)




#### file detail

|   |path|covered line|new line|coverage|
|----|----|----|----|----|
|:large_blue_circle:|io/questdb/cutlass/pgwire/AuthenticationException.java|3|3|100.00%|
|:large_blue_circle:|io/questdb/cutlass/pgwire/PGBasicAuthenticator.java|1|1|100.00%|
|:large_blue_circle:|io/questdb/cutlass/pgwire/PGConnectionContext.java|11|11|100.00%|

**Comment by ideoma** [comment]
#### [PR Coverage check]

:heart_eyes: **pass** : 15 / 15 (100.00%)




#### file detail

|   |path|covered line|new line|coverage|
|----|----|----|----|----|
|:large_blue_circle:|io/questdb/cutlass/pgwire/AuthenticationException.java|3|3|100.00%|
|:large_blue_circle:|io/questdb/cutlass/pgwire/PGBasicAuthenticator.java|1|1|100.00%|
|:large_blue_circle:|io/questdb/cutlass/pgwire/PGConnectionContext.java|11|11|100.00%|

**Review by ideoma — APPROVED** [review]

**Comment by ideoma** [comment]
#### [PR Coverage check]

:heart_eyes: **pass** : 15 / 15 (100.00%)




#### file detail

|   |path|covered line|new line|coverage|
|----|----|----|----|----|
|:large_blue_circle:|io/questdb/cutlass/pgwire/AuthenticationException.java|3|3|100.00%|
|:large_blue_circle:|io/questdb/cutlass/pgwire/PGBasicAuthenticator.java|1|1|100.00%|
|:large_blue_circle:|io/questdb/cutlass/pgwire/PGConnectionContext.java|11|11|100.00%|

**Comment by ideoma** [comment]
#### [PR Coverage check]

:heart_eyes: **pass** : 15 / 15 (100.00%)




#### file detail

|   |path|covered line|new line|coverage|
|----|----|----|----|----|
|:large_blue_circle:|io/questdb/cutlass/pgwire/AuthenticationException.java|3|3|100.00%|
|:large_blue_circle:|io/questdb/cutlass/pgwire/PGBasicAuthenticator.java|1|1|100.00%|
|:large_blue_circle:|io/questdb/cutlass/pgwire/PGConnectionContext.java|11|11|100.00%|

**Comment by ideoma** [comment]
#### [PR Coverage check]

:heart_eyes: **pass** : 15 / 15 (100.00%)




#### file detail

|   |path|covered line|new line|coverage|
|----|----|----|----|----|
|:large_blue_circle:|io/questdb/cutlass/pgwire/AuthenticationException.java|3|3|100.00%|
|:large_blue_circle:|io/questdb/cutlass/pgwire/PGBasicAuthenticator.java|1|1|100.00%|
|:large_blue_circle:|io/questdb/cutlass/pgwire/PGConnectionContext.java|11|11|100.00%|

**Comment by ideoma** [comment]
#### [PR Coverage check]

:heart_eyes: **pass** : 15 / 15 (100.00%)




#### file detail

|   |path|covered line|new line|coverage|
|----|----|----|----|----|
|:large_blue_circle:|io/questdb/cutlass/pgwire/AuthenticationException.java|3|3|100.00%|
|:large_blue_circle:|io/questdb/cutlass/pgwire/PGBasicAuthenticator.java|1|1|100.00%|
|:large_blue_circle:|io/questdb/cutlass/pgwire/PGConnectionContext.java|11|11|100.00%|

**Comment by ideoma** [comment]
#### [PR Coverage check]

:heart_eyes: **pass** : 15 / 15 (100.00%)




#### file detail

|   |path|covered line|new line|coverage|
|----|----|----|----|----|
|:large_blue_circle:|io/questdb/cutlass/pgwire/AuthenticationException.java|3|3|100.00%|
|:large_blue_circle:|io/questdb/cutlass/pgwire/PGBasicAuthenticator.java|1|1|100.00%|
|:large_blue_circle:|io/questdb/cutlass/pgwire/PGConnectionContext.java|11|11|100.00%|

**Comment by ideoma** [comment]
#### [PR Coverage check]

:heart_eyes: **pass** : 15 / 15 (100.00%)




#### file detail

|   |path|covered line|new line|coverage|
|----|----|----|----|----|
|:large_blue_circle:|io/questdb/cutlass/pgwire/AuthenticationException.java|3|3|100.00%|
|:large_blue_circle:|io/questdb/cutlass/pgwire/PGBasicAuthenticator.java|1|1|100.00%|
|:large_blue_circle:|io/questdb/cutlass/pgwire/PGConnectionContext.java|11|11|100.00%|

**Pull request merged**
