### PR TITLE
chore(docs): Tukrish README translation

### PR DESCRIPTION
**Pull request by kerimsenturk5734**
I have added turkish support and configured other READMEs for that.

### CODE REVIEW

**Comment by oliver-daniel** [comment]
Hi! Thanks for your contribution. Can you please add `i18n/README.tr-tr.md` to `.all-contributorsrc`, as recently done in [this PR](https://github.com/questdb/questdb/pull/3682/files)? Thank you!

**Comment by kerimsenturk5734** [comment]
I have added my profile in  `.all-contributorsrc` but i couldn't be sure. Should not had i do that?

**Comment by oliver-daniel** [comment]
Hi Kerim, you can definitely recognize yourself for your work! That said, it looks like you added the JSON object representing your profile yourself. Might I recommend reverting that change and running the following command inside the project root:

`npx all-contributors-cli add kerimsenturk5734 doc`

You should see the changes propagate across all the READMEs automatically. :grin: That said, it really isn't a big deal either way -- the only thing left to review is the translation itself, and we should be underway pretty quickly after that. Thanks again!

**Comment by kerimsenturk5734** [comment]
I like this tool. I had not seen it before. Thanks for help

**Comment by oliver-daniel** [comment]
Hey Kerim, thanks for your patience. I had a Turkish-speaking associate take a look at the translation and he said it looks really good. He offered a few comments, but I can open those in another PR for your consideration.

Approved!

**Comment by kerimsenturk5734** [comment]
I am really happy to contribute to this great project. I will have fixed it for next pr if you feed me back with the your friend's comments

**Review by oliver-daniel — APPROVED** [review]

**Comment by oliver-daniel** [comment]
Hey @bluestreak01 are you around to sync and merge? Thanks!

**Pull request merged**
