### PR TITLE
chore(core): handling of unexpected errors in SQL execution

### PR DESCRIPTION
**Pull request by glasstiger**
When Chrome (and probably other browsers too) makes a GET request and detects a broken connection, it will retry the request a certain number of times. In my case this number is 3.
What this means is that if we run a SQL from web console, and the server just simply disconnects, the browser resends the same query multiple times.
To avoid this problem, we should almost always send back a response to the client.
Unexpected errors, such as UnsatisfiedLinkError, will result in a response code HTTP 500 (Internal Error).

required by https://github.com/questdb/questdb-enterprise/pull/266

### CODE REVIEW

**Comment by ideoma** [comment]
#### [PR Coverage check]

:heart_eyes: **pass** : 2 / 2 (100.00%)




#### file detail

|   |path|covered line|new line|coverage|
|----|----|----|----|----|
|:large_blue_circle:|io/questdb/network/AbstractIODispatcher.java|1|1|100.00%|
|:large_blue_circle:|io/questdb/cutlass/http/WaitProcessor.java|1|1|100.00%|

**Comment by ideoma** [comment]
#### [PR Coverage check]

:heart_eyes: **pass** : 5 / 8 (62.50%)




#### file detail

|   |path|covered line|new line|coverage|
|----|----|----|----|----|
|:large_blue_circle:|io/questdb/cutlass/http/processors/JsonQueryProcessor.java|2|4|50.00%|
|:large_blue_circle:|io/questdb/cutlass/pgwire/PGConnectionContext.java|3|4|75.00%|

**Review by puzpuzpuz — DISMISSED** [review]
nit: would be great to add a test factory and some tests around this behavior.

**Comment by glasstiger** [comment]
> nit: would be great to add a test factory and some tests around this behavior.

ent project has the tests but will try to add something here as well

**Comment by ideoma** [comment]
#### [PR Coverage check]

:heart_eyes: **pass** : 4 / 8 (50.00%)




#### file detail

|   |path|covered line|new line|coverage|
|----|----|----|----|----|
|:large_blue_circle:|io/questdb/cutlass/http/processors/JsonQueryProcessor.java|2|4|50.00%|
|:large_blue_circle:|io/questdb/cutlass/pgwire/PGConnectionContext.java|2|4|50.00%|

**Comment by glasstiger** [comment]
> nit: would be great to add a test factory and some tests around this behavior.

pushed tests in fe07e916d81ce41db6f120cc99bc1bc93c0c71fe

**Comment by puzpuzpuz** [comment]
Thanks for going an extra mile with the additional tests! Will approve once CI is green.

**Comment by ideoma** [comment]
#### [PR Coverage check]

:heart_eyes: **pass** : 11 / 12 (91.67%)




#### file detail

|   |path|covered line|new line|coverage|
|----|----|----|----|----|
|:large_blue_circle:|io/questdb/cutlass/pgwire/PGConnectionContext.java|3|4|75.00%|
|:large_blue_circle:|io/questdb/cutlass/http/HttpConnectionContext.java|4|4|100.00%|
|:large_blue_circle:|io/questdb/cutlass/http/processors/JsonQueryProcessor.java|4|4|100.00%|

**Comment by ideoma** [comment]
#### [PR Coverage check]

:heart_eyes: **pass** : 11 / 12 (91.67%)




#### file detail

|   |path|covered line|new line|coverage|
|----|----|----|----|----|
|:large_blue_circle:|io/questdb/cutlass/pgwire/PGConnectionContext.java|3|4|75.00%|
|:large_blue_circle:|io/questdb/cutlass/http/HttpConnectionContext.java|4|4|100.00%|
|:large_blue_circle:|io/questdb/cutlass/http/processors/JsonQueryProcessor.java|4|4|100.00%|

**Review by puzpuzpuz — APPROVED** [review]

**Comment by ideoma** [comment]
#### [PR Coverage check]

:heart_eyes: **pass** : 11 / 12 (91.67%)




#### file detail

|   |path|covered line|new line|coverage|
|----|----|----|----|----|
|:large_blue_circle:|io/questdb/cutlass/pgwire/PGConnectionContext.java|3|4|75.00%|
|:large_blue_circle:|io/questdb/cutlass/http/HttpConnectionContext.java|4|4|100.00%|
|:large_blue_circle:|io/questdb/cutlass/http/processors/JsonQueryProcessor.java|4|4|100.00%|

**Comment by ideoma** [comment]
#### [PR Coverage check]

:heart_eyes: **pass** : 11 / 12 (91.67%)




#### file detail

|   |path|covered line|new line|coverage|
|----|----|----|----|----|
|:large_blue_circle:|io/questdb/cutlass/pgwire/PGConnectionContext.java|3|4|75.00%|
|:large_blue_circle:|io/questdb/cutlass/http/HttpConnectionContext.java|4|4|100.00%|
|:large_blue_circle:|io/questdb/cutlass/http/processors/JsonQueryProcessor.java|4|4|100.00%|

**Comment by ideoma** [comment]
#### [PR Coverage check]

:heart_eyes: **pass** : 42 / 45 (93.33%)




#### file detail

|   |path|covered line|new line|coverage|
|----|----|----|----|----|
|:large_blue_circle:|io/questdb/cutlass/pgwire/PGConnectionContext.java|34|37|91.89%|
|:large_blue_circle:|io/questdb/cutlass/http/HttpConnectionContext.java|4|4|100.00%|
|:large_blue_circle:|io/questdb/cutlass/http/processors/JsonQueryProcessor.java|4|4|100.00%|

**Review by bluestreak01 — APPROVED** [review]

**Pull request merged**
