### PR TITLE
feat: run as questdb user in docker

### PR DESCRIPTION
**Pull request by mariusgheorghies**
Tested with:
- legacy questdb root folder on /root/.questdb
  - questdb will run as root
  - if there are problems with `/root/.questdb` mount detection there is a environment variable flag that will disable the check: `IGNORE_DATA_ROOT_MOUNT_CHECK`
    - in this case setting `IGNORE_DATA_ROOT_MOUNT_CHECK` to true, `QUESTDB_DATA_DIR` to `/root/.questdb` and `RUN_AS_ROOT` to true should have the same effect
- new questdb root folder on /var/lib/questdb
- if data in /var/lib/questdb is own by other than questdb:questdb it will change ownership to questdb:questdb, this should help with migration
- different entrypoint overwrite (docker-entrypoint.sh is bypassed)
- different arguments to /app/bin/java
- different commands that start with /app/bin/java
- with other user than questdb, works but should files in questdb data should be own by that user id

Added the following environment variable:
- `IGNORE_FIND_AND_OWN_DIR` set to `false` by default
  - there is a function that will find all the files owned by other users/group than questdb/questdb and it will change the ownership to questdb/questdb
  - this flag will disable the change of ownership
- `IGNORE_DATA_ROOT_MOUNT_CHECK` set to `false` by default
  - this will disable the `/root/.questdb` check if that creates problems
- `RUN_AS_ROOT` default set to `false`
  - it will run questdb as root if set to true
- `QUESTDB_DATA_DIR` default to `/var/lib/questdb`
  - set this if you are mount quesdb data to another path

### CODE REVIEW

**Comment by ideoma** [comment]
#### [PR Coverage check]

:heart_eyes: **pass** : 11 / 16 (68.75%)




#### file detail

|   |path|covered line|new line|coverage|
|----|----|----|----|----|
|:large_blue_circle:|io/questdb/PropServerConfiguration.java|1|2|50.00%|
|:large_blue_circle:|io/questdb/griffin/engine/functions/catalogue/SimulateCrashFunctionFactory.java|7|11|63.64%|
|:large_blue_circle:|io/questdb/cairo/DefaultCairoConfiguration.java|1|1|100.00%|
|:large_blue_circle:|io/questdb/PropertyKey.java|2|2|100.00%|

**Review by ideoma — APPROVED** [review]
Docker change is good.
Works with mounts to `/root/.questdb` and `/var/lib/quetsdb` and works as root and questdb users respectively

**Comment by ideoma** [comment]
#### [PR Coverage check]

:heart_eyes: **pass** : 12 / 21 (57.14%)




#### file detail

|   |path|covered line|new line|coverage|
|----|----|----|----|----|
|:large_blue_circle:|io/questdb/PropServerConfiguration.java|1|2|50.00%|
|:large_blue_circle:|io/questdb/griffin/engine/functions/catalogue/SimulateCrashFunctionFactory.java|8|16|50.00%|
|:large_blue_circle:|io/questdb/cairo/DefaultCairoConfiguration.java|1|1|100.00%|
|:large_blue_circle:|io/questdb/PropertyKey.java|2|2|100.00%|

**Review by ideoma — APPROVED** [review]

**Comment by newskooler** [comment]
Is it explained anywhere in docs how to run as a custom user via docker for QuestDB?

**Pull request merged**
