### PR TITLE
fix(sql): fix wrong results returned from union queries with similar joins

### LINKED ISSUE #3581: Incorrect result returned by `INTERSECT`
### Describe the bug

Buggy query:
```
(SELECT count(1) FROM telemetry as T1 CROSS JOIN telemetry as T2 WHERE T2.created=NOW() AND T2.created='2023-04-14 19:11:51+00' ) INTERSECT (SELECT count(1) FROM telemetry as T1 JOIN telemetry as T2 on T1.created=T2.created JOIN telemetry as T3 ON T2.created=T3.created WHERE T3.created<NOW() )
```
The buggy query is a bit complex (I have tried to simplify it but it does not happen in simple cases):
The first half is `SELECT count(1) FROM telemetry as T1 CROSS JOIN telemetry as T2 WHERE T2.created=NOW() AND T2.created='2023-04-14 19:11:51+00'` where the predicate is always False, so the subquery result is 0.
The second half is `SELECT count(1) FROM telemetry as T1 JOIN telemetry as T2 on T1.created=T2.created JOIN telemetry as T3 ON T2.created=T3.created WHERE T3.created<NOW()` where the predicate is always True, so the subquery result is greater than 0.
The INTERSECT should return an empty result: [], however, it returns [(0,)]
Replacing the first half with `(SELECT 0)` or the second half with `(SELCT 100)` does not have this issue.

### To reproduce

```
(SELECT count(1) FROM telemetry as T1 CROSS JOIN telemetry as T2 WHERE T2.created=NOW() AND T2.created='2023-04-14 19:11:51+00' ) INTERSECT (SELECT count(1) FROM telemetry as T1 JOIN telemetry as T2 on T1.created=T2.created JOIN telemetry as T3 ON T2.created=T3.created WHERE T3.created<NOW() )
```

### Expected Behavior

The INTERSECT should return an empty result: [], however, it returns [(0,)]

### Environment

```markdown
- **QuestDB version**: v7.2.1
- **OS**: ubuntu 20.04
```

### Additional context

_No response_

### LINKED ISSUE #3669: Incorrect results returned from `UNION`
### Describe the bug

In some cases with table joins, the `UNION` operator does not return the expected result.

### To reproduce

Query 1: `result = [(0,)]`
```
(SELECT count(1) FROM telemetry as T1 JOIN telemetry as T2 ON T1.created=T2.created WHERE T1.event=0.0)
```
Query 2: `result = [(4361,)]` (could differ but not zero)
```
(SELECT count(1) FROM telemetry as T1 JOIN telemetry as T2 ON T1.event=T2.event)
```
Query 3 (i.e., Query 1 UNION Query 2): `result = [(0,)]` (buggy)
```
(SELECT count(1) FROM telemetry as T1 JOIN telemetry as T2 ON T1.created=T2.created WHERE T1.event=0.0) UNION (SELECT count(1) FROM telemetry as T1 JOIN telemetry as T2 ON T1.event=T2.event)
``` 

### Expected Behavior

The expected result of Query 3 is `[(0,4361)]`

### Environment

```markdown
- **QuestDB version**: v7.3.1
```

### Additional context

_No response_

### PR DESCRIPTION
**Pull request by puzpuzpuz**
Fixes #3581
Fixes #3669

Fixes isolation for the lookup maps used in join optimizations (see comments in the added tests).

### CODE REVIEW

**Comment by ideoma** [comment]
#### [PR Coverage check]

:heart_eyes: **pass** : 27 / 37 (72.97%)




#### file detail

|   |path|covered line|new line|coverage|
|----|----|----|----|----|
|:large_blue_circle:|io/questdb/griffin/model/RuntimeIntervalModelBuilder.java|18|28|64.29%|
|:large_blue_circle:|io/questdb/griffin/engine/union/IntersectRecordCursor.java|1|1|100.00%|
|:large_blue_circle:|io/questdb/griffin/SqlOptimiser.java|8|8|100.00%|

**Comment by ideoma** [comment]
#### [PR Coverage check]

:heart_eyes: **pass** : 27 / 37 (72.97%)




#### file detail

|   |path|covered line|new line|coverage|
|----|----|----|----|----|
|:large_blue_circle:|io/questdb/griffin/model/RuntimeIntervalModelBuilder.java|18|28|64.29%|
|:large_blue_circle:|io/questdb/griffin/engine/union/IntersectRecordCursor.java|1|1|100.00%|
|:large_blue_circle:|io/questdb/griffin/SqlOptimiser.java|8|8|100.00%|

**Comment by ideoma** [comment]
#### [PR Coverage check]

:heart_eyes: **pass** : 27 / 37 (72.97%)




#### file detail

|   |path|covered line|new line|coverage|
|----|----|----|----|----|
|:large_blue_circle:|io/questdb/griffin/model/RuntimeIntervalModelBuilder.java|18|28|64.29%|
|:large_blue_circle:|io/questdb/griffin/engine/union/IntersectRecordCursor.java|1|1|100.00%|
|:large_blue_circle:|io/questdb/griffin/SqlOptimiser.java|8|8|100.00%|

**Review by bluestreak01 — APPROVED** [review]

**Comment by ideoma** [comment]
#### [PR Coverage check]

:heart_eyes: **pass** : 27 / 37 (72.97%)




#### file detail

|   |path|covered line|new line|coverage|
|----|----|----|----|----|
|:large_blue_circle:|io/questdb/griffin/model/RuntimeIntervalModelBuilder.java|18|28|64.29%|
|:large_blue_circle:|io/questdb/griffin/engine/union/IntersectRecordCursor.java|1|1|100.00%|
|:large_blue_circle:|io/questdb/griffin/SqlOptimiser.java|8|8|100.00%|

**Pull request merged**
