### PR TITLE
chore(core): refactor code to support acl update on table or column rename

### PR DESCRIPTION
**Pull request by bziobrowski**
Also - adds authorization to /imp endpoint and copy command

### CODE REVIEW

**Comment by ideoma** [comment]
#### [PR Coverage check]

:heart_eyes: **pass** : 14 / 16 (87.50%)




#### file detail

|   |path|covered line|new line|coverage|
|----|----|----|----|----|
|:large_blue_circle:|io/questdb/cairo/security/ReadOnlySecurityContext.java|0|2|00.00%|
|:large_blue_circle:|io/questdb/cairo/wal/WalWriter.java|1|1|100.00%|
|:large_blue_circle:|io/questdb/cairo/CairoEngine.java|3|3|100.00%|
|:large_blue_circle:|io/questdb/cairo/TableWriter.java|3|3|100.00%|
|:large_blue_circle:|io/questdb/griffin/engine/ops/AlterOperation.java|5|5|100.00%|
|:large_blue_circle:|io/questdb/cairo/security/AllowAllSecurityContext.java|2|2|100.00%|

**Comment by ideoma** [comment]
#### [PR Coverage check]

:heart_eyes: **pass** : 14 / 16 (87.50%)




#### file detail

|   |path|covered line|new line|coverage|
|----|----|----|----|----|
|:large_blue_circle:|io/questdb/cairo/security/ReadOnlySecurityContext.java|0|2|00.00%|
|:large_blue_circle:|io/questdb/cairo/wal/WalWriter.java|1|1|100.00%|
|:large_blue_circle:|io/questdb/cairo/CairoEngine.java|3|3|100.00%|
|:large_blue_circle:|io/questdb/cairo/TableWriter.java|3|3|100.00%|
|:large_blue_circle:|io/questdb/griffin/engine/ops/AlterOperation.java|5|5|100.00%|
|:large_blue_circle:|io/questdb/cairo/security/AllowAllSecurityContext.java|2|2|100.00%|

**Comment by ideoma** [comment]
#### [PR Coverage check]

:heart_eyes: **pass** : 30 / 33 (90.91%)




#### file detail

|   |path|covered line|new line|coverage|
|----|----|----|----|----|
|:large_blue_circle:|io/questdb/PropServerConfiguration.java|6|9|66.67%|
|:large_blue_circle:|io/questdb/cairo/wal/WalWriter.java|2|2|100.00%|
|:large_blue_circle:|io/questdb/cutlass/text/CairoTextWriter.java|2|2|100.00%|
|:large_blue_circle:|io/questdb/cutlass/text/CopyRequestJob.java|2|2|100.00%|
|:large_blue_circle:|io/questdb/cairo/wal/MetadataService.java|2|2|100.00%|
|:large_blue_circle:|io/questdb/cairo/CairoEngine.java|4|4|100.00%|
|:large_blue_circle:|io/questdb/PropertyKey.java|1|1|100.00%|
|:large_blue_circle:|io/questdb/cutlass/text/ParallelCsvFileImporter.java|7|7|100.00%|
|:large_blue_circle:|io/questdb/cairo/TableWriter.java|2|2|100.00%|
|:large_blue_circle:|io/questdb/griffin/engine/ops/AlterOperation.java|1|1|100.00%|
|:large_blue_circle:|io/questdb/cutlass/text/CopyTask.java|1|1|100.00%|

**Comment by ideoma** [comment]
#### [PR Coverage check]

:heart_eyes: **pass** : 29 / 32 (90.62%)




#### file detail

|   |path|covered line|new line|coverage|
|----|----|----|----|----|
|:large_blue_circle:|io/questdb/PropServerConfiguration.java|6|9|66.67%|
|:large_blue_circle:|io/questdb/cairo/wal/WalWriter.java|2|2|100.00%|
|:large_blue_circle:|io/questdb/cutlass/text/CairoTextWriter.java|2|2|100.00%|
|:large_blue_circle:|io/questdb/cutlass/text/CopyRequestJob.java|2|2|100.00%|
|:large_blue_circle:|io/questdb/cairo/wal/MetadataService.java|2|2|100.00%|
|:large_blue_circle:|io/questdb/cairo/DefaultDdlListener.java|2|2|100.00%|
|:large_blue_circle:|io/questdb/cairo/CairoEngine.java|1|1|100.00%|
|:large_blue_circle:|io/questdb/PropertyKey.java|1|1|100.00%|
|:large_blue_circle:|io/questdb/cutlass/text/ParallelCsvFileImporter.java|7|7|100.00%|
|:large_blue_circle:|io/questdb/cairo/TableWriter.java|2|2|100.00%|
|:large_blue_circle:|io/questdb/griffin/engine/ops/AlterOperation.java|1|1|100.00%|
|:large_blue_circle:|io/questdb/cutlass/text/CopyTask.java|1|1|100.00%|

**Review by bluestreak01 — APPROVED** [review]

**Pull request merged**
