### PR TITLE
test(core): improve FuzzRunner

### PR DESCRIPTION
**Pull request by puzpuzpuz**
Follow-up for #4014

With this change, col tops columns are included in the fuzzed transactions. Previously it wasn't the case as those columns weren't in the end table when the fuzzer was generating transactions.

### CODE REVIEW

**Comment by questdb-butler** [comment]
<table>
  <thead>
    <tr>
      <th width="50"></th>
      <th width="100%" data-danger-table="true">Fails</th>
    </tr>
  </thead>
  <tbody><tr>
      <td>:no_entry_sign:</td>
      <td>

  Please update the PR title to match this format:
`type(subType): description`

Where `type` is one of:
`feat`, `fix`, `chore`, `docs`, `style`, `refactor`, `perf`, `test`, `ci`, `revert`

And: `subType` is one of:
`build`, `sql`, `log`, `mig`, `core`, `ilp`, `pgwire`, `http`, `conf`, `ui`, `wal`

For Example:

```
perf(sql): improve pattern matching performance for SELECT sub-queries
```
  </td>
    </tr>
  </tbody>
</table>




<p align="right">
  Generated by :no_entry_sign: <a href="https://danger.systems/js">dangerJS</a> against 167c3478555cbfd1e0786364defce018c611c788
</p>

**Comment by ideoma** [comment]
#### [PR Coverage check]


:heart_eyes: **pass** : 0 / 0 (0%)

**Comment by ideoma** [comment]
I think that the column with the column tops are part of the metadata when the transactions are generated:
image

It happens because the metadata is taken from non-wal table where there is no delay in applying metadata changes.

**Comment by puzpuzpuz** [comment]
> I think that the column with the column tops are part of the metadata when the transactions are generated

This is non-deterministic. WAL apply job may be fast enough to apply the transactions before the `generateTransactions()` call, but in many cases, it's not fast enough. Adding an await makes this predictable.

**Comment by puzpuzpuz** [comment]
> It happens because the metadata is taken from non-wal table where there is no delay in applying metadata changes.

This is not the case at least in `ReplicationFuzzTest`: we use a WAL table there.

**Comment by ideoma** [comment]
> The thing is that we do a deep metadata copy in `FuzzTransactionGenerator#generateSet()` and sequencer metadata won't do. It throws in many methods such as `isDedupKey()`.

Ok, I understand. Can we make this apply conditional then? It is only needed for a subset of test cases and running it mainstream WAL fuzz tests removes the test cases of operating on columns that have not been applied yet.

**Comment by puzpuzpuz** [comment]
> Ok, I understand. Can we make this apply conditional then? It is only needed for a subset of test cases and running it mainstream WAL fuzz tests removes the test cases of operating on columns that have not been applied yet.

I took a slightly different approach in 849515412375e27a49f0a02416326e3525e0ae8e. Now we use a mix of sequencer metadata + table reader metadata - this is the same behavior as what we had before the recent metadata pool split patch.

**Review by ideoma — APPROVED** [review]

**Pull request merged**
