### PR TITLE
fix(sql): fix slowness due to redundant disk reads in LIMIT K,N filtered queries

### PR DESCRIPTION
**Pull request by puzpuzpuz**
The slowness was introduced in 6.5.3 (#2531)

### CODE REVIEW

**Comment by ideoma** [comment]
#### [PR Coverage check]

:heart_eyes: **pass** : 4 / 4 (100.00%)




#### file detail

|   |path|covered line|new line|coverage|
|----|----|----|----|----|
|:large_blue_circle:|io/questdb/griffin/engine/LimitRecordCursorFactory.java|4|4|100.00%|

**Comment by bluestreak01** [comment]
we also implement `limits` outside of `LimitCursorFactory`. It is often used as a hint. Notable examples are async offload and sorting

**Comment by puzpuzpuz** [comment]
Failed test is #2774

**Comment by puzpuzpuz** [comment]
> we also implement `limits` outside of `LimitCursorFactory`. It is often used as a hint. Notable examples are async offload and sorting

Added missing code for `LimitedSizeSortedLightRecordCursorFactory`. Are you referring to any other places? Async filtered factories themselves handle only LIMIT N case, not LIMIT K,N.

**Comment by ideoma** [comment]
#### [PR Coverage check]

:heart_eyes: **pass** : 12 / 12 (100.00%)




#### file detail

|   |path|covered line|new line|coverage|
|----|----|----|----|----|
|:large_blue_circle:|io/questdb/griffin/engine/orderby/LimitedSizeSortedLightRecordCursorFactory.java|6|6|100.00%|
|:large_blue_circle:|io/questdb/griffin/engine/LimitRecordCursorFactory.java|4|4|100.00%|
|:large_blue_circle:|io/questdb/griffin/SqlCodeGenerator.java|2|2|100.00%|

**Comment by bziobrowski** [comment]
Is PR meant to disable pre-fetch for LIMIT N and LIMIT K,N  or just LIMIT K,N ? 
If it's the latter then it'd be good to check limitLo & limitHi  before disabling prefetch in context .

**Comment by ideoma** [comment]
#### [PR Coverage check]

:heart_eyes: **pass** : 12 / 12 (100.00%)




#### file detail

|   |path|covered line|new line|coverage|
|----|----|----|----|----|
|:large_blue_circle:|io/questdb/griffin/engine/orderby/LimitedSizeSortedLightRecordCursorFactory.java|6|6|100.00%|
|:large_blue_circle:|io/questdb/griffin/engine/LimitRecordCursorFactory.java|4|4|100.00%|
|:large_blue_circle:|io/questdb/griffin/SqlCodeGenerator.java|2|2|100.00%|

**Comment by bziobrowski** [comment]
LimitedSizeSortedLightRecordCursorFactory implements sort + limit N and sort + limit K, N and 
limit isn't always pushed to model with filter so with this change pre-touch is also disabled for many cases of "limit N" . 
Examples :

```sql
CREATE TABLE trips(l long, ts TIMESTAMP) timestamp(ts) partition by month;

selecT * from 
(
   select l, ts from trips 
   where l <=5 
   and ts < to_timestamp('2022-01-08T00:00:00', 'yyyy-MM-ddTHH:mm:ss') 
) aaa 
order by ts desc 
limit 3;

select l, ts from trips 
where l <=5 
and ts < to_timestamp('2022-01-08T00:00:00', 'yyyy-MM-ddTHH:mm:ss') 
order by ts desc 
limit 3;
```

Checking hi/lo functions should do the trick .

**Comment by puzpuzpuz** [comment]
> LimitedSizeSortedLightRecordCursorFactory implements sort + limit N and sort + limit K, N

Thanks! Let me check that one.

**Comment by puzpuzpuz** [comment]
Added function checks in 169db6080e8a01ad58c3dfa0437aa1d28db9517c

**Comment by ideoma** [comment]
#### [PR Coverage check]

:heart_eyes: **pass** : 15 / 15 (100.00%)




#### file detail

|   |path|covered line|new line|coverage|
|----|----|----|----|----|
|:large_blue_circle:|io/questdb/griffin/engine/orderby/LimitedSizeSortedLightRecordCursorFactory.java|6|6|100.00%|
|:large_blue_circle:|io/questdb/griffin/engine/LimitRecordCursorFactory.java|7|7|100.00%|
|:large_blue_circle:|io/questdb/griffin/SqlCodeGenerator.java|2|2|100.00%|

**Review by bziobrowski — APPROVED** [review]

**Comment by puzpuzpuz** [comment]
@bziobrowski thanks for the helpful hints!

**Comment by ideoma** [comment]
#### [PR Coverage check]

:heart_eyes: **pass** : 15 / 15 (100.00%)




#### file detail

|   |path|covered line|new line|coverage|
|----|----|----|----|----|
|:large_blue_circle:|io/questdb/griffin/engine/orderby/LimitedSizeSortedLightRecordCursorFactory.java|6|6|100.00%|
|:large_blue_circle:|io/questdb/griffin/engine/LimitRecordCursorFactory.java|7|7|100.00%|
|:large_blue_circle:|io/questdb/griffin/SqlCodeGenerator.java|2|2|100.00%|

**Pull request merged**
