### PR TITLE
fix(sql): fix incorrect results returned by GROUP BY queries with int or symbol key

### LINKED ISSUE #4159: Query intermittently returns null
### To reproduce

I have a table with cols: ticker, date, ohlcv. if I run the below query, occasionally, it returns nulls for min(date). if I run the query again, it returns valid values, and maybe null again at a later stage. please note, I am updating the table in another process.

`SELECT ticker, min(date), max(date) from mkt_ohlcv order by 1`

### QuestDB version:

7.3.9

### OS, in case of Docker specify Docker and the Host OS:

Mac

### File System, in case of Docker specify Host File System:

Mac

### Full Name:

Roh Codeur

### Affiliation:

personal

### Have you followed Linux, MacOs kernel configuration steps to increase Maximum open files and Maximum virtual memory areas limit?

- [X] Yes, I have

### Additional context

_No response_

### PR DESCRIPTION
**Pull request by puzpuzpuz**
Fixes #4159

Also, includes the following:
* Fix incorrect null handling in Rosti merge functions for `min` and `sum` aggregate functions for int, long and long256 types. Due to this bug the database could return NULL instead of the correct function value.
* Fix broken `getLong256` method in Rosti's record cursor. It was reading from `offset + 3 + Long.BYTES` address instead of `offset + 3 * Long.BYTES`.
* Remove Rosti implementations of `sum` and `avg` functions for date and timestamp types. They were not present in Java aggregate function implementations and their value for the end users is questionable.
* The `cairo.sql.parallel.groupby.enabled` property now also controls Rosti-based factories usage, not only parallel GROUP BY Java factories.

### CODE REVIEW

**Comment by ideoma** [comment]
#### [PR Coverage check]

:heart_eyes: **pass** : 57 / 61 (93.44%)




#### file detail

|   |path|covered line|new line|coverage|
|----|----|----|----|----|
|:large_blue_circle:|io/questdb/std/Long256Util.java|1|2|50.00%|
|:large_blue_circle:|io/questdb/griffin/engine/groupby/vect/GroupByRecordCursorFactory.java|4|6|66.67%|
|:large_blue_circle:|io/questdb/griffin/engine/functions/rnd/RndLongCCFunctionFactory.java|3|4|75.00%|
|:large_blue_circle:|io/questdb/griffin/engine/functions/cast/CastDoubleToLong256FunctionFactory.java|2|2|100.00%|
|:large_blue_circle:|io/questdb/griffin/engine/functions/cast/CastShortToLong256FunctionFactory.java|2|2|100.00%|
|:large_blue_circle:|io/questdb/std/Long256Acceptor.java|8|8|100.00%|
|:large_blue_circle:|io/questdb/griffin/engine/functions/cast/CastDateToLong256FunctionFactory.java|2|2|100.00%|
|:large_blue_circle:|io/questdb/cairo/sql/PageAddressCacheRecord.java|1|1|100.00%|
|:large_blue_circle:|io/questdb/griffin/engine/groupby/vect/GroupByNotKeyedVectorRecordCursorFactory.java|1|1|100.00%|
|:large_blue_circle:|io/questdb/cairo/map/OrderedMapFixedSizeRecord.java|1|1|100.00%|
|:large_blue_circle:|io/questdb/griffin/engine/functions/cast/CastLongToLong256FunctionFactory.java|2|2|100.00%|
|:large_blue_circle:|io/questdb/cairo/map/Unordered8MapRecord.java|1|1|100.00%|
|:large_blue_circle:|io/questdb/cairo/map/Unordered4MapValue.java|1|1|100.00%|
|:large_blue_circle:|io/questdb/cairo/map/Unordered4MapRecord.java|1|1|100.00%|
|:large_blue_circle:|io/questdb/cairo/map/Unordered8MapValue.java|1|1|100.00%|
|:large_blue_circle:|io/questdb/griffin/engine/functions/cast/CastBooleanToLong256FunctionFactory.java|2|2|100.00%|
|:large_blue_circle:|io/questdb/cairo/vm/api/MemoryR.java|1|1|100.00%|
|:large_blue_circle:|io/questdb/griffin/engine/functions/rnd/RndLong256FunctionFactory.java|1|1|100.00%|
|:large_blue_circle:|io/questdb/cairo/map/OrderedMapValue.java|1|1|100.00%|
|:large_blue_circle:|io/questdb/griffin/engine/functions/rnd/RndDateCCCFunctionFactory.java|3|3|100.00%|
|:large_blue_circle:|io/questdb/griffin/engine/functions/cast/CastByteToLong256FunctionFactory.java|2|2|100.00%|
|:large_blue_circle:|io/questdb/cairo/map/Unordered2MapValue.java|1|1|100.00%|
|:large_blue_circle:|io/questdb/cairo/map/Unordered16MapValue.java|1|1|100.00%|
|:large_blue_circle:|io/questdb/cairo/vm/MemoryPARWImpl.java|1|1|100.00%|
|:large_blue_circle:|io/questdb/cairo/map/Unordered16MapRecord.java|1|1|100.00%|
|:large_blue_circle:|io/questdb/griffin/engine/functions/cast/CastTimestampToLong256FunctionFactory.java|2|2|100.00%|
|:large_blue_circle:|io/questdb/cairo/map/OrderedMapVarSizeRecord.java|1|1|100.00%|
|:large_blue_circle:|io/questdb/griffin/engine/functions/cast/CastFloatToLong256FunctionFactory.java|2|2|100.00%|
|:large_blue_circle:|io/questdb/griffin/SqlCodeGenerator.java|2|2|100.00%|
|:large_blue_circle:|io/questdb/griffin/engine/functions/cast/CastCharToLong256FunctionFactory.java|2|2|100.00%|
|:large_blue_circle:|io/questdb/cairo/map/Unordered2MapRecord.java|1|1|100.00%|
|:large_blue_circle:|io/questdb/griffin/engine/functions/cast/CastIntToLong256FunctionFactory.java|2|2|100.00%|

**Review by bluestreak01 — DISMISSED** [review]

**Comment by ideoma** [comment]
#### [PR Coverage check]

:heart_eyes: **pass** : 57 / 61 (93.44%)




#### file detail

|   |path|covered line|new line|coverage|
|----|----|----|----|----|
|:large_blue_circle:|io/questdb/std/Long256Util.java|1|2|50.00%|
|:large_blue_circle:|io/questdb/griffin/engine/groupby/vect/GroupByRecordCursorFactory.java|4|6|66.67%|
|:large_blue_circle:|io/questdb/griffin/engine/functions/rnd/RndLongCCFunctionFactory.java|3|4|75.00%|
|:large_blue_circle:|io/questdb/griffin/engine/functions/cast/CastDoubleToLong256FunctionFactory.java|2|2|100.00%|
|:large_blue_circle:|io/questdb/griffin/engine/functions/cast/CastShortToLong256FunctionFactory.java|2|2|100.00%|
|:large_blue_circle:|io/questdb/std/Long256Acceptor.java|8|8|100.00%|
|:large_blue_circle:|io/questdb/griffin/engine/functions/cast/CastDateToLong256FunctionFactory.java|2|2|100.00%|
|:large_blue_circle:|io/questdb/cairo/sql/PageAddressCacheRecord.java|1|1|100.00%|
|:large_blue_circle:|io/questdb/griffin/engine/groupby/vect/GroupByNotKeyedVectorRecordCursorFactory.java|1|1|100.00%|
|:large_blue_circle:|io/questdb/cairo/map/OrderedMapFixedSizeRecord.java|1|1|100.00%|
|:large_blue_circle:|io/questdb/griffin/engine/functions/cast/CastLongToLong256FunctionFactory.java|2|2|100.00%|
|:large_blue_circle:|io/questdb/cairo/map/Unordered8MapRecord.java|1|1|100.00%|
|:large_blue_circle:|io/questdb/cairo/map/Unordered4MapValue.java|1|1|100.00%|
|:large_blue_circle:|io/questdb/cairo/map/Unordered4MapRecord.java|1|1|100.00%|
|:large_blue_circle:|io/questdb/cairo/map/Unordered8MapValue.java|1|1|100.00%|
|:large_blue_circle:|io/questdb/griffin/engine/functions/cast/CastBooleanToLong256FunctionFactory.java|2|2|100.00%|
|:large_blue_circle:|io/questdb/cairo/vm/api/MemoryR.java|1|1|100.00%|
|:large_blue_circle:|io/questdb/griffin/engine/functions/rnd/RndLong256FunctionFactory.java|1|1|100.00%|
|:large_blue_circle:|io/questdb/cairo/map/OrderedMapValue.java|1|1|100.00%|
|:large_blue_circle:|io/questdb/griffin/engine/functions/rnd/RndDateCCCFunctionFactory.java|3|3|100.00%|
|:large_blue_circle:|io/questdb/griffin/engine/functions/cast/CastByteToLong256FunctionFactory.java|2|2|100.00%|
|:large_blue_circle:|io/questdb/cairo/map/Unordered2MapValue.java|1|1|100.00%|
|:large_blue_circle:|io/questdb/cairo/map/Unordered16MapValue.java|1|1|100.00%|
|:large_blue_circle:|io/questdb/cairo/vm/MemoryPARWImpl.java|1|1|100.00%|
|:large_blue_circle:|io/questdb/cairo/map/Unordered16MapRecord.java|1|1|100.00%|
|:large_blue_circle:|io/questdb/griffin/engine/functions/cast/CastTimestampToLong256FunctionFactory.java|2|2|100.00%|
|:large_blue_circle:|io/questdb/cairo/map/OrderedMapVarSizeRecord.java|1|1|100.00%|
|:large_blue_circle:|io/questdb/griffin/engine/functions/cast/CastFloatToLong256FunctionFactory.java|2|2|100.00%|
|:large_blue_circle:|io/questdb/griffin/SqlCodeGenerator.java|2|2|100.00%|
|:large_blue_circle:|io/questdb/griffin/engine/functions/cast/CastCharToLong256FunctionFactory.java|2|2|100.00%|
|:large_blue_circle:|io/questdb/cairo/map/Unordered2MapRecord.java|1|1|100.00%|
|:large_blue_circle:|io/questdb/griffin/engine/functions/cast/CastIntToLong256FunctionFactory.java|2|2|100.00%|

**Comment by ideoma** [comment]
#### [PR Coverage check]

:heart_eyes: **pass** : 57 / 61 (93.44%)




#### file detail

|   |path|covered line|new line|coverage|
|----|----|----|----|----|
|:large_blue_circle:|io/questdb/std/Long256Util.java|1|2|50.00%|
|:large_blue_circle:|io/questdb/griffin/engine/groupby/vect/GroupByRecordCursorFactory.java|4|6|66.67%|
|:large_blue_circle:|io/questdb/griffin/engine/functions/rnd/RndLongCCFunctionFactory.java|3|4|75.00%|
|:large_blue_circle:|io/questdb/griffin/engine/functions/cast/CastDoubleToLong256FunctionFactory.java|2|2|100.00%|
|:large_blue_circle:|io/questdb/griffin/engine/functions/cast/CastShortToLong256FunctionFactory.java|2|2|100.00%|
|:large_blue_circle:|io/questdb/std/Long256Acceptor.java|8|8|100.00%|
|:large_blue_circle:|io/questdb/griffin/engine/functions/cast/CastDateToLong256FunctionFactory.java|2|2|100.00%|
|:large_blue_circle:|io/questdb/cairo/sql/PageAddressCacheRecord.java|1|1|100.00%|
|:large_blue_circle:|io/questdb/griffin/engine/groupby/vect/GroupByNotKeyedVectorRecordCursorFactory.java|1|1|100.00%|
|:large_blue_circle:|io/questdb/cairo/map/OrderedMapFixedSizeRecord.java|1|1|100.00%|
|:large_blue_circle:|io/questdb/griffin/engine/functions/cast/CastLongToLong256FunctionFactory.java|2|2|100.00%|
|:large_blue_circle:|io/questdb/cairo/map/Unordered8MapRecord.java|1|1|100.00%|
|:large_blue_circle:|io/questdb/cairo/map/Unordered4MapValue.java|1|1|100.00%|
|:large_blue_circle:|io/questdb/cairo/map/Unordered4MapRecord.java|1|1|100.00%|
|:large_blue_circle:|io/questdb/cairo/map/Unordered8MapValue.java|1|1|100.00%|
|:large_blue_circle:|io/questdb/griffin/engine/functions/cast/CastBooleanToLong256FunctionFactory.java|2|2|100.00%|
|:large_blue_circle:|io/questdb/cairo/vm/api/MemoryR.java|1|1|100.00%|
|:large_blue_circle:|io/questdb/griffin/engine/functions/rnd/RndLong256FunctionFactory.java|1|1|100.00%|
|:large_blue_circle:|io/questdb/cairo/map/OrderedMapValue.java|1|1|100.00%|
|:large_blue_circle:|io/questdb/griffin/engine/functions/rnd/RndDateCCCFunctionFactory.java|3|3|100.00%|
|:large_blue_circle:|io/questdb/griffin/engine/functions/cast/CastByteToLong256FunctionFactory.java|2|2|100.00%|
|:large_blue_circle:|io/questdb/cairo/map/Unordered2MapValue.java|1|1|100.00%|
|:large_blue_circle:|io/questdb/cairo/map/Unordered16MapValue.java|1|1|100.00%|
|:large_blue_circle:|io/questdb/cairo/vm/MemoryPARWImpl.java|1|1|100.00%|
|:large_blue_circle:|io/questdb/cairo/map/Unordered16MapRecord.java|1|1|100.00%|
|:large_blue_circle:|io/questdb/griffin/engine/functions/cast/CastTimestampToLong256FunctionFactory.java|2|2|100.00%|
|:large_blue_circle:|io/questdb/cairo/map/OrderedMapVarSizeRecord.java|1|1|100.00%|
|:large_blue_circle:|io/questdb/griffin/engine/functions/cast/CastFloatToLong256FunctionFactory.java|2|2|100.00%|
|:large_blue_circle:|io/questdb/griffin/SqlCodeGenerator.java|2|2|100.00%|
|:large_blue_circle:|io/questdb/griffin/engine/functions/cast/CastCharToLong256FunctionFactory.java|2|2|100.00%|
|:large_blue_circle:|io/questdb/cairo/map/Unordered2MapRecord.java|1|1|100.00%|
|:large_blue_circle:|io/questdb/griffin/engine/functions/cast/CastIntToLong256FunctionFactory.java|2|2|100.00%|

**Comment by puzpuzpuz** [comment]
@bluestreak01 I've cleaned up the way we register jobs in 557ff45b071ede0ba74b15c1412571b0bb1d9c49

Now we have `WorkerPoolUtils` with two utility methods: `setupQueryJobs` (jobs used for query handling like `PageFrameReduceJob`) and `setupWriterJobs` (O3, `ColumnIndexerJob` and friends). The problem with the previous approach was that `O3#setupWorkerPool()` was called only for non-read-only instances while it set up `PageFrameReduceJob`. So, read-only instances had single-threaded filters and group by.

`setupQueryJobs` also checks if parallel filters and group by are enabled before registering the corresponding jobs.

**Comment by ideoma** [comment]
#### [PR Coverage check]

:heart_eyes: **pass** : 97 / 103 (94.17%)




#### file detail

|   |path|covered line|new line|coverage|
|----|----|----|----|----|
|:large_blue_circle:|io/questdb/std/Long256Util.java|1|2|50.00%|
|:large_blue_circle:|io/questdb/griffin/engine/groupby/vect/GroupByRecordCursorFactory.java|5|7|71.43%|
|:large_blue_circle:|io/questdb/griffin/engine/functions/rnd/RndLongCCFunctionFactory.java|3|4|75.00%|
|:large_blue_circle:|io/questdb/ServerMain.java|4|5|80.00%|
|:large_blue_circle:|io/questdb/mp/WorkerPoolUtils.java|32|33|96.97%|
|:large_blue_circle:|io/questdb/griffin/engine/functions/cast/CastDoubleToLong256FunctionFactory.java|2|2|100.00%|
|:large_blue_circle:|io/questdb/griffin/engine/functions/cast/CastShortToLong256FunctionFactory.java|2|2|100.00%|
|:large_blue_circle:|io/questdb/std/Long256Acceptor.java|8|8|100.00%|
|:large_blue_circle:|io/questdb/griffin/engine/functions/cast/CastDateToLong256FunctionFactory.java|2|2|100.00%|
|:large_blue_circle:|io/questdb/cairo/sql/PageAddressCacheRecord.java|1|1|100.00%|
|:large_blue_circle:|io/questdb/griffin/engine/groupby/vect/GroupByNotKeyedVectorRecordCursorFactory.java|4|4|100.00%|
|:large_blue_circle:|io/questdb/cairo/map/OrderedMapFixedSizeRecord.java|1|1|100.00%|
|:large_blue_circle:|io/questdb/griffin/engine/functions/cast/CastLongToLong256FunctionFactory.java|2|2|100.00%|
|:large_blue_circle:|io/questdb/cairo/map/Unordered8MapRecord.java|1|1|100.00%|
|:large_blue_circle:|io/questdb/cairo/map/Unordered4MapValue.java|1|1|100.00%|
|:large_blue_circle:|io/questdb/cairo/map/Unordered4MapRecord.java|1|1|100.00%|
|:large_blue_circle:|io/questdb/cairo/map/Unordered8MapValue.java|1|1|100.00%|
|:large_blue_circle:|io/questdb/griffin/engine/functions/cast/CastBooleanToLong256FunctionFactory.java|2|2|100.00%|
|:large_blue_circle:|io/questdb/cairo/vm/api/MemoryR.java|1|1|100.00%|
|:large_blue_circle:|io/questdb/griffin/engine/functions/rnd/RndLong256FunctionFactory.java|1|1|100.00%|
|:large_blue_circle:|io/questdb/cairo/map/OrderedMapValue.java|1|1|100.00%|
|:large_blue_circle:|io/questdb/griffin/engine/functions/rnd/RndDateCCCFunctionFactory.java|3|3|100.00%|
|:large_blue_circle:|io/questdb/griffin/engine/functions/cast/CastByteToLong256FunctionFactory.java|2|2|100.00%|
|:large_blue_circle:|io/questdb/cairo/map/Unordered2MapValue.java|1|1|100.00%|
|:large_blue_circle:|io/questdb/cairo/map/Unordered16MapValue.java|1|1|100.00%|
|:large_blue_circle:|io/questdb/cairo/vm/MemoryPARWImpl.java|1|1|100.00%|
|:large_blue_circle:|io/questdb/cairo/map/Unordered16MapRecord.java|1|1|100.00%|
|:large_blue_circle:|io/questdb/griffin/engine/functions/cast/CastTimestampToLong256FunctionFactory.java|2|2|100.00%|
|:large_blue_circle:|io/questdb/cairo/map/OrderedMapVarSizeRecord.java|1|1|100.00%|
|:large_blue_circle:|io/questdb/griffin/engine/functions/cast/CastFloatToLong256FunctionFactory.java|2|2|100.00%|
|:large_blue_circle:|io/questdb/griffin/SqlCodeGenerator.java|2|2|100.00%|
|:large_blue_circle:|io/questdb/griffin/engine/functions/cast/CastCharToLong256FunctionFactory.java|2|2|100.00%|
|:large_blue_circle:|io/questdb/cairo/map/Unordered2MapRecord.java|1|1|100.00%|
|:large_blue_circle:|io/questdb/griffin/engine/functions/cast/CastIntToLong256FunctionFactory.java|2|2|100.00%|

**Review by bluestreak01 — APPROVED** [review]

**Pull request merged**
