### PR TITLE
fix(sql): make table column names case insensitive in where

### LINKED ISSUE #1036: Aggregate query is column name case sensitive
**Describe the bug**
Error when query WHERE uses column in different casing

**To Reproduce**
```
create table sensors2 (
ID int
)

select count()  
from sensors2
where id < 0
```
Error happens, in the logs

```
2021-05-18T10:40:07.838491Z E i.q.c.h.p.JsonQueryProcessorState [27] Uh-oh. Error! java.lang.ArrayIndexOutOfBoundsException

```

**Expected behavior**
Should return count 0

**Environment (please complete the following information):**
 - Version: 6.0.1

### PR DESCRIPTION
**Pull request by ideoma**
Closes #1036

### CODE REVIEW

**Comment by ideoma** [comment]
#### [PR Coverage check]

:heart_eyes: **pass** : 18 / 31 (58.06%)




#### file detail

|   |path|covered line|new line|coverage|
|----|----|----|----|----|
|:large_blue_circle:|io/questdb/std/LowerCaseCharSequenceIntHashMap.java|13|26|50.00%|
|:large_blue_circle:|io/questdb/cairo/TableWriter.java|1|1|100.00%|
|:large_blue_circle:|io/questdb/griffin/engine/join/JoinRecordMetadata.java|1|1|100.00%|
|:large_blue_circle:|io/questdb/cairo/TableWriterMetadata.java|1|1|100.00%|
|:large_blue_circle:|io/questdb/cairo/TableReaderMetadata.java|2|2|100.00%|

**Comment by ideoma** [comment]
#### [PR Coverage check]

:heart_eyes: **pass** : 18 / 31 (58.06%)




#### file detail

|   |path|covered line|new line|coverage|
|----|----|----|----|----|
|:large_blue_circle:|io/questdb/std/LowerCaseCharSequenceIntHashMap.java|13|26|50.00%|
|:large_blue_circle:|io/questdb/cairo/TableWriter.java|1|1|100.00%|
|:large_blue_circle:|io/questdb/griffin/engine/join/JoinRecordMetadata.java|1|1|100.00%|
|:large_blue_circle:|io/questdb/cairo/TableWriterMetadata.java|1|1|100.00%|
|:large_blue_circle:|io/questdb/cairo/TableReaderMetadata.java|2|2|100.00%|

**Comment by ideoma** [comment]
#### [PR Coverage check]

:heart_eyes: **pass** : 8 / 9 (88.89%)




#### file detail

|   |path|covered line|new line|coverage|
|----|----|----|----|----|
|:large_blue_circle:|io/questdb/std/LowerCaseCharSequenceIntHashMap.java|3|4|75.00%|
|:large_blue_circle:|io/questdb/cairo/TableWriter.java|1|1|100.00%|
|:large_blue_circle:|io/questdb/griffin/engine/join/JoinRecordMetadata.java|1|1|100.00%|
|:large_blue_circle:|io/questdb/cairo/TableWriterMetadata.java|1|1|100.00%|
|:large_blue_circle:|io/questdb/cairo/TableReaderMetadata.java|2|2|100.00%|

**Comment by ideoma** [comment]
#### [PR Coverage check]

:heart_eyes: **pass** : 16 / 16 (100.00%)




#### file detail

|   |path|covered line|new line|coverage|
|----|----|----|----|----|
|:large_blue_circle:|io/questdb/cairo/TableWriter.java|1|1|100.00%|
|:large_blue_circle:|io/questdb/std/CharSequenceIntHashMap.java|3|3|100.00%|
|:large_blue_circle:|io/questdb/griffin/engine/join/JoinRecordMetadata.java|1|1|100.00%|
|:large_blue_circle:|io/questdb/cairo/TableWriterMetadata.java|1|1|100.00%|
|:large_blue_circle:|io/questdb/std/LowerCaseCharSequenceIntHashMap.java|8|8|100.00%|
|:large_blue_circle:|io/questdb/cairo/TableReaderMetadata.java|2|2|100.00%|

**Review by bluestreak01 — APPROVED** [review]

**Comment by ideoma** [comment]
#### [PR Coverage check]

:heart_eyes: **pass** : 16 / 16 (100.00%)




#### file detail

|   |path|covered line|new line|coverage|
|----|----|----|----|----|
|:large_blue_circle:|io/questdb/cairo/TableWriter.java|1|1|100.00%|
|:large_blue_circle:|io/questdb/std/CharSequenceIntHashMap.java|3|3|100.00%|
|:large_blue_circle:|io/questdb/griffin/engine/join/JoinRecordMetadata.java|1|1|100.00%|
|:large_blue_circle:|io/questdb/cairo/TableWriterMetadata.java|1|1|100.00%|
|:large_blue_circle:|io/questdb/std/LowerCaseCharSequenceIntHashMap.java|8|8|100.00%|
|:large_blue_circle:|io/questdb/cairo/TableReaderMetadata.java|2|2|100.00%|

**Comment by ideoma** [comment]
#### [PR Coverage check]

:heart_eyes: **pass** : 16 / 16 (100.00%)




#### file detail

|   |path|covered line|new line|coverage|
|----|----|----|----|----|
|:large_blue_circle:|io/questdb/cairo/TableWriter.java|1|1|100.00%|
|:large_blue_circle:|io/questdb/std/CharSequenceIntHashMap.java|3|3|100.00%|
|:large_blue_circle:|io/questdb/griffin/engine/join/JoinRecordMetadata.java|1|1|100.00%|
|:large_blue_circle:|io/questdb/cairo/TableWriterMetadata.java|1|1|100.00%|
|:large_blue_circle:|io/questdb/std/LowerCaseCharSequenceIntHashMap.java|8|8|100.00%|
|:large_blue_circle:|io/questdb/cairo/TableReaderMetadata.java|2|2|100.00%|

**Pull request merged**
