### PR TITLE
chore(core): Java code formatting checks with IntelliJ

### PR DESCRIPTION
**Pull request by amunra**
# Change
Introduced Java auto-code formatting checks in CI.

# Details
* Introduced a new CI job which downloads/installs/runs the IntelliJ IDEA Community Edition code formatter according to our pre-existing project settings.
* Formatted all Java code to pass CI.

# Testing
After setting up the command, testing has been done by formatting around 20 files in the IDE and observing that CI no longer signaled them as badly formatted.
This verifies that the code formatting rules used for the command line match those used by the IDE.

# Caveats
A few files (namely, those related to histogram functionality) have been edited manually.
This is because the code formatter behaves oddly with two consecutive JavaDoc style sections and aims to merge them, corrupting the banner section formatting.

The workaround has been to convert the section following the banner to (`//`) comments.

### CODE REVIEW

**Comment by ideoma** [comment]
#### [PR Coverage check]

:heart_eyes: **pass** : 2 / 4 (50.00%)




#### file detail

|   |path|covered line|new line|coverage|
|----|----|----|----|----|
|:large_blue_circle:|io/questdb/cairo/wal/CheckWalTransactionsJob.java|0|2|00.00%|
|:large_blue_circle:|io/questdb/griffin/engine/groupby/hyperloglog/BiasCorrectionData.java|1|1|100.00%|
|:large_blue_circle:|io/questdb/griffin/SqlOptimiser.java|1|1|100.00%|

**Comment by ideoma** [comment]
#### [PR Coverage check]

:heart_eyes: **pass** : 2 / 4 (50.00%)




#### file detail

|   |path|covered line|new line|coverage|
|----|----|----|----|----|
|:large_blue_circle:|io/questdb/cairo/wal/CheckWalTransactionsJob.java|0|2|00.00%|
|:large_blue_circle:|io/questdb/griffin/engine/groupby/hyperloglog/BiasCorrectionData.java|1|1|100.00%|
|:large_blue_circle:|io/questdb/griffin/SqlOptimiser.java|1|1|100.00%|

**Comment by ideoma** [comment]
#### [PR Coverage check]

:disappointed: **fail** : 1 / 3 (33.33%)




#### file detail

|   |path|covered line|new line|coverage|
|----|----|----|----|----|
|:large_blue_circle:|io/questdb/cairo/wal/CheckWalTransactionsJob.java|0|2|00.00%|
|:large_blue_circle:|io/questdb/griffin/engine/groupby/hyperloglog/BiasCorrectionData.java|1|1|100.00%|

**Comment by ideoma** [comment]
#### [PR Coverage check]

:disappointed: **fail** : 1 / 3 (33.33%)




#### file detail

|   |path|covered line|new line|coverage|
|----|----|----|----|----|
|:large_blue_circle:|io/questdb/cairo/wal/CheckWalTransactionsJob.java|0|2|00.00%|
|:large_blue_circle:|io/questdb/griffin/engine/groupby/hyperloglog/BiasCorrectionData.java|1|1|100.00%|

**Review by bluestreak01 — APPROVED** [review]

**Pull request merged**
