### PR TITLE
feat(config): Made config validation optional, but enabled for new installs.

### PR DESCRIPTION
**Pull request by amunra**
# Goal

* Enable validation for new installations.
* Preserve no validation for existing installations.
* Inform users how to migrate to newer setttings via deprecation logic.

# Optional Validation

New installations of QuestDB will have the following at the very top of `server.conf`:

```ini
# This configuration file is optionally validated. Comment or set to false to disable.
config.validation.enabled=true
```

Existing installations can begin validating their config by enabling the same setting, which is otherwise `false` by default.

## Naming

My rationale for calling this `config.validation.enabled` rather than `config.validation` is that the former makes it easier to introduce new config validation settings in future releases, e.g.:

```ini
config.validation.check_hostnames=true
```

That said, we could also rename this to something else. Naming suggestions welcome.

# Deprecation Logic
These changes (as per Alex's request) also log suggested config changes when:

* Obsolete settings are used: I.e. settings that existed previously, but no longer do anything. These will cause a hard fail if validation is on (just logged if validation is off).
* Deprecated settings are used: I.e. settings that are still supported, but have newer replacements. These will be logged without causing failure regardless the `config.validation.enabled` setting.

All errors are collected into a single `String` message. Depending on severity and settings, this is then either raised as an exception (causing startup to fail) or logged to an `A`dvisory log line.

Here's an example error message:

```
Configuration issues:
    Invalid settings (not recognized, probable typos):
        * telemerty.hide.tables
    Obsolete settings (no longer recognized):
        * cairo.timestamp.locale: Replaced by `cairo.date.locale`
        * pg.timestamp.locale: Replaced by `pg.date.locale`
    Deprecated settings (recognized but superseded by newer settings):
        * line.tcp.default.partition.by: Replaced by `line.default.partition.by`
        * http.min.bind.to: Replaced by `http.min.net.bind.to`
```

### CODE REVIEW

**Comment by amunra** [comment]
Still work in progress, I'm populating `OBSOLETE` and `DEPRECATED` maps.

**Comment by ideoma** [comment]
#### [PR Coverage check]

:heart_eyes: **pass** : 41 / 61 (67.21%)




#### file detail

|   |path|covered line|new line|coverage|
|----|----|----|----|----|
|:large_blue_circle:|io/questdb/PropServerConfiguration.java|40|60|66.67%|
|:large_blue_circle:|io/questdb/PropertyKey.java|1|1|100.00%|

**Comment by ideoma** [comment]
#### [PR Coverage check]

:disappointed: **fail** : 29 / 86 (33.72%)




#### file detail

|   |path|covered line|new line|coverage|
|----|----|----|----|----|
|:large_blue_circle:|io/questdb/PropServerConfiguration.java|28|85|32.94%|
|:large_blue_circle:|io/questdb/PropertyKey.java|1|1|100.00%|

**Comment by ideoma** [comment]
#### [PR Coverage check]

:disappointed: **fail** : 34 / 92 (36.96%)




#### file detail

|   |path|covered line|new line|coverage|
|----|----|----|----|----|
|:large_blue_circle:|io/questdb/PropServerConfiguration.java|33|91|36.26%|
|:large_blue_circle:|io/questdb/PropertyKey.java|1|1|100.00%|

**Comment by ideoma** [comment]
#### [PR Coverage check]

:heart_eyes: **pass** : 91 / 92 (98.91%)




#### file detail

|   |path|covered line|new line|coverage|
|----|----|----|----|----|
|:large_blue_circle:|io/questdb/PropServerConfiguration.java|90|91|98.90%|
|:large_blue_circle:|io/questdb/PropertyKey.java|1|1|100.00%|

**Comment by ideoma** [comment]
#### [PR Coverage check]

:disappointed: **fail** : 40 / 98 (40.82%)




#### file detail

|   |path|covered line|new line|coverage|
|----|----|----|----|----|
|:large_blue_circle:|io/questdb/PropServerConfiguration.java|39|97|40.21%|
|:large_blue_circle:|io/questdb/PropertyKey.java|1|1|100.00%|

**Comment by ideoma** [comment]
#### [PR Coverage check]

:disappointed: **fail** : 40 / 98 (40.82%)




#### file detail

|   |path|covered line|new line|coverage|
|----|----|----|----|----|
|:large_blue_circle:|io/questdb/PropServerConfiguration.java|39|97|40.21%|
|:large_blue_circle:|io/questdb/PropertyKey.java|1|1|100.00%|

**Comment by amunra** [comment]
Renamed branch, abandoning PR. See new one: https://github.com/questdb/questdb/pull/2047

**Pull request closed without merging**
