### PR TITLE
feat(ui): Notifications pane

### PR DESCRIPTION
**Pull request by insmac**
### Description
- Currently, the notifications interface is a set of toast messages, which disappear after a brief amount of time. They can be pinned, but it requires deliberate action.
- By design, toast messages should provide status messages which are short-lived, whereas a list of executed queries and other similar records are typically more suited for a permanent pane that can be toggled if needed.

### Changes
- Introduce a bottom `Log` pane, that is hidden by default and can be toggled.
- If the pane is hidden, indicate new messages by a small icon. 
- Change the order of notifications so that the newest are on the bottom, as it's a more common user experience for log panes.
- Replace sliding with the fade transition for appear/exit.
- Hide the pane on mobile by default, but keep an ability to toggle as needed.
- Allow all the notifications to be visible and disable removing more than 2 from the array.
- Add a `Clear all` button to the pane
- Set log buffer size at 20 messages

### Screen recording
https://user-images.githubusercontent.com/1871646/133768508-55bc7396-eab6-441a-b4d1-5e7c6d013730.mp4

### CODE REVIEW

**Review by marregui — COMMENTED** [review]
Awesome contribution @insmac , thank you very much.

It is ready for review. Code looks great, works exactly as you describe it, and the description is spectacular. 

As a user, my first thought was, how do I clear these?, would it be possible to add a clear all button, or right click action?. 
The list may grow indefinitely, or is there a limit?. Could there be a limit of say 20?

Thank you again, would you please sign the license cla?

**Comment by insmac** [comment]
> Awesome contribution @insmac , thank you very much.
> 
> It is ready for review. Code looks great, works exactly as you describe it, and the description is spectacular.
> 
> As a user, my first thought was, how do I clear these?, would it be possible to add a clear all button, or right click action?.
> The list may grow indefinitely, or is there a limit?. Could there be a limit of say 20?
> 
> Thank you again, would you please sign the license cla?

Thanks for your feedback @marregui ! 🙂 

The ability to clear all the notifications is already provided via `CMD` + `K` shortcut which is unfortunately only accessible within the SQL editor. Ideally it should be an app-wide command.

Also, `Clear all` link is certainly something worth adding, and easy to do as well. 

There is no list limit as I know of, but we might introduce a hard stop that would slice the array above a certain threshold, much like an ordinary terminal / console does. Good idea!

**Comment by insmac** [comment]
@marregui 

Couple of updates here 🙂 

- `Clear all` function in the console (button)
- Log buffer size set to 20 recent messages
- Removed an unused option in settings to control when notifications disappear
- Overall cleanup.

**Review by marregui — APPROVED** [review]
Top job @insmac thank you very much for this contribution.

LGTM

**Comment by insmac** [comment]
@marregui @bsmth 

Updates:
- Re-implemented notification items in accordance with the new UI/feedback - all items are one-liners
- The collapsed state now contains the newest (current) log message at all times
- Three distinct notification types: info, success, error
- Removed notifications for the recently added context menu actions (copying table schema to clipboard, copying build version)

**Review by bsmth — APPROVED** [review]
Looks good, thanks 👍🏻

**Review by bluestreak01 — APPROVED** [review]

**Pull request merged**
