### PR TITLE
fix(sql): improve index selection in query planning

### PR DESCRIPTION
**Pull request by bziobrowski**
Changes how where clause parser chooses main index to use while executing query (keyColumn). 
Current master uses index block capacity as a measure of selectivity but :
- it's a not well known metric that's rarely set by users (vs symbol capacity)
- it's a bad proxy for selectivity 
- the condition seems to be reversed in master  (it prefers to use columns with higher index block capacity so theoretically with more rowids per symbol value and thus less selective )
so index selected for a query is often not the optimal one.  

Instead of index block capacity this PR uses actual symbol count and capacity (when counts are equal) in map reader . 

Note 1: index selection is still too simplistic but to really correct things we'd need to start collecting statistics  and analyze selectivity of each operator including arguments . 
For example : 
```sql
create table tab(sym1 symbol index, sym2 symbol index);
select * from tab where sym1 in ('a','b') and sym2 != 'c' 
```
in this case sym1 predicate should be preferred even though sym2 column has more distinct values .

Note 2: I've more (& more readable) tests in explain PR . I'll add them once this one's merged .

### CODE REVIEW

**Comment by ideoma** [comment]
#### [PR Coverage check]

:heart_eyes: **pass** : 23 / 23 (100.00%)




#### file detail

|   |path|covered line|new line|coverage|
|----|----|----|----|----|
|:large_blue_circle:|io/questdb/griffin/WhereClauseParser.java|23|23|100.00%|

**Comment by ideoma** [comment]
#### [PR Coverage check]

:heart_eyes: **pass** : 23 / 23 (100.00%)




#### file detail

|   |path|covered line|new line|coverage|
|----|----|----|----|----|
|:large_blue_circle:|io/questdb/griffin/WhereClauseParser.java|23|23|100.00%|

**Review by bluestreak01 — CHANGES_REQUESTED** [review]
please format test classes

**Comment by ideoma** [comment]
#### [PR Coverage check]

:heart_eyes: **pass** : 23 / 23 (100.00%)




#### file detail

|   |path|covered line|new line|coverage|
|----|----|----|----|----|
|:large_blue_circle:|io/questdb/griffin/WhereClauseParser.java|23|23|100.00%|

**Comment by bziobrowski** [comment]
reformatted tests

**Comment by ideoma** [comment]
#### [PR Coverage check]

:heart_eyes: **pass** : 23 / 23 (100.00%)




#### file detail

|   |path|covered line|new line|coverage|
|----|----|----|----|----|
|:large_blue_circle:|io/questdb/griffin/WhereClauseParser.java|23|23|100.00%|

**Review by bluestreak01 — APPROVED** [review]

**Pull request merged**
