### PR TITLE
fix(sql): fix boolean numeric representation

### PR DESCRIPTION
**Pull request by Zahlii**
Should fix https://github.com/questdb/questdb/issues/2379

### CODE REVIEW

**Comment by Zahlii** [comment]
While fixing the problems mentioned above, I noticed that the boolean logic related to bool - other data types conversion was reversed to what one would expect, i.e. false mapping to int 1 etc. I changed this to make more sense and allow for aggregated calculations over booleans, however this also required to change the symbol mapping for booleans to be changed from false -> index 1 to false -> index 0. Please let me know if this can break anything existing.

**Review by bluestreak01 — CHANGES_REQUESTED** [review]
There are few more factories to be changed to make things consistent:

```
CastByteToBooleanFunctionFactory
CastDateToBooleanFunctionFactory
CastLongToBooleanFunctionFactory
CastShortToBooleanFunctionFactory
CastTimestampToBooleanFunctionFactory
```

**Comment by Zahlii** [comment]
> There are few more factories to be changed to make things consistent:
> 
> ```
> CastByteToBooleanFunctionFactory
> CastDateToBooleanFunctionFactory
> CastLongToBooleanFunctionFactory
> CastShortToBooleanFunctionFactory
> CastTimestampToBooleanFunctionFactory
> ```

Thanks, will bring them in line. On a side note: Why don't we allow explicit casts from float/double to boolean, in a similar logic? I guess because postgres also doesn't allow this?

**Comment by bluestreak01** [comment]
No specific reason. Feel free to add cast functions for double & float

**Comment by eugenels** [comment]
There are still many non-obvious places that need to be fixed:
https://github.com/questdb/questdb/blob/792cca6fea2fc2a153940dabae690f4c669a3304/core/src/main/java/io/questdb/cairo/vm/MemoryPARWImpl.java#L534

https://github.com/questdb/questdb/blob/783d7ef0f0fc99f16029040ae82ac5b08dec1f89/core/src/main/java/io/questdb/cairo/vm/api/MemoryCR.java#L50

https://github.com/questdb/questdb/blob/85191c8761342acfd32e0c0ff369633696ef5487/core/src/main/java/io/questdb/cutlass/line/tcp/LineTcpMeasurementEvent.java#L187

https://github.com/questdb/questdb/blob/01b1885c9b4da13652af43fc2e8bb4a84ebbd3f6/core/src/main/java/io/questdb/griffin/engine/functions/bool/InCharFunctionFactory.java#L61

https://github.com/questdb/questdb/blob/826f3e677fd976d686cbdfa9fb3091fc58e6936d/core/src/main/java/io/questdb/griffin/engine/functions/bool/InStrFunctionFactory.java#L55

https://github.com/questdb/questdb/blob/7b8d1ccffc1cfe8a194a3c914964b8077e3b1425/core/src/main/java/io/questdb/griffin/engine/functions/bool/InSymbolFunctionFactory.java#L55

https://github.com/questdb/questdb/blob/c6c87c6fee0467e42a360a7d71e8003f69da61b0/core/src/main/java/io/questdb/std/Unsafe.java#L179

https://github.com/questdb/questdb/blob/16e4eee6066bb5ba7be695f6b06b15b048b34642/core/src/main/java/io/questdb/cairo/sql/PageAddressCacheRecord.java#L96

https://github.com/questdb/questdb/blob/f6905e94c58837e0e565a4bd3bf1efe0890dfc7b/core/src/main/java/io/questdb/griffin/engine/groupby/SimpleMapValue.java#L52

https://github.com/questdb/questdb/blob/f6905e94c58837e0e565a4bd3bf1efe0890dfc7b/core/src/main/java/io/questdb/cairo/map/FastMapValue.java#L47

and probably more...

**Comment by Zahlii** [comment]
> There are still many non-obvious places that need to be fixed:
> 
> https://github.com/questdb/questdb/blob/792cca6fea2fc2a153940dabae690f4c669a3304/core/src/main/java/io/questdb/cairo/vm/MemoryPARWImpl.java#L534
> 
> https://github.com/questdb/questdb/blob/783d7ef0f0fc99f16029040ae82ac5b08dec1f89/core/src/main/java/io/questdb/cairo/vm/api/MemoryCR.java#L50
> 
> https://github.com/questdb/questdb/blob/85191c8761342acfd32e0c0ff369633696ef5487/core/src/main/java/io/questdb/cutlass/line/tcp/LineTcpMeasurementEvent.java#L187
> 
> https://github.com/questdb/questdb/blob/01b1885c9b4da13652af43fc2e8bb4a84ebbd3f6/core/src/main/java/io/questdb/griffin/engine/functions/bool/InCharFunctionFactory.java#L61
> 
> https://github.com/questdb/questdb/blob/826f3e677fd976d686cbdfa9fb3091fc58e6936d/core/src/main/java/io/questdb/griffin/engine/functions/bool/InStrFunctionFactory.java#L55
> 
> https://github.com/questdb/questdb/blob/7b8d1ccffc1cfe8a194a3c914964b8077e3b1425/core/src/main/java/io/questdb/griffin/engine/functions/bool/InSymbolFunctionFactory.java#L55
> 
> https://github.com/questdb/questdb/blob/c6c87c6fee0467e42a360a7d71e8003f69da61b0/core/src/main/java/io/questdb/std/Unsafe.java#L179
> 
> https://github.com/questdb/questdb/blob/16e4eee6066bb5ba7be695f6b06b15b048b34642/core/src/main/java/io/questdb/cairo/sql/PageAddressCacheRecord.java#L96
> 
> https://github.com/questdb/questdb/blob/f6905e94c58837e0e565a4bd3bf1efe0890dfc7b/core/src/main/java/io/questdb/griffin/engine/groupby/SimpleMapValue.java#L52
> 
> https://github.com/questdb/questdb/blob/f6905e94c58837e0e565a4bd3bf1efe0890dfc7b/core/src/main/java/io/questdb/cairo/map/FastMapValue.java#L47
> 
> and probably more...

What did I start here... I might be able to do a more exhaustive search over the weekend and try to change the logic wherever possible, assuming that this will impact quite some test cases then.

**Comment by bluestreak01** [comment]
@eugenels changing these places will require migration procedure, we must not change them in this PR. We do store revered `byte` representation in columns, but it could stay like this.

**Comment by bluestreak01** [comment]
@Zahlii  I would not do any more changes

**Comment by eugenels** [comment]
> @eugenels changing these places will require migration procedure, we must not change them in this PR. We do store revered `byte` representation in columns, but it could stay like this.

Looked at the code again:
You're right, most places are consistent except for SimpleMapValue:

`return values[4 * index] == 0;`

This fix will not require a migration.

**Review by ideoma — APPROVED** [review]
I think how we store bytes for boolean does not matter on the functions level. 
We cannot read memory for boolean column with other method than `getBool`

**Pull request merged**
