### PR TITLE
chore(core): simplify atomic operations in reader pool

### PR DESCRIPTION
**Pull request by puzpuzpuz**
Swaps CAS with much cheaper volatile reads where possible.

### CODE REVIEW

**Comment by ideoma** [comment]
#### [PR Coverage check]

:heart_eyes: **pass** : 6 / 8 (75.00%)




#### file detail

|   |path|covered line|new line|coverage|
|----|----|----|----|----|
|:large_blue_circle:|io/questdb/cairo/pool/ReaderPool.java|6|8|75.00%|

**Comment by ideoma** [comment]
#### [PR Coverage check]

:heart_eyes: **pass** : 8 / 10 (80.00%)




#### file detail

|   |path|covered line|new line|coverage|
|----|----|----|----|----|
|:large_blue_circle:|io/questdb/cairo/pool/ReaderPool.java|7|9|77.78%|
|:large_blue_circle:|io/questdb/cairo/pool/WriterPool.java|1|1|100.00%|

**Comment by puzpuzpuz** [comment]
Failed test is #2731

**Comment by ideoma** [comment]
#### [PR Coverage check]

:heart_eyes: **pass** : 5 / 5 (100.00%)




#### file detail

|   |path|covered line|new line|coverage|
|----|----|----|----|----|
|:large_blue_circle:|io/questdb/cairo/pool/WriterPool.java|1|1|100.00%|
|:large_blue_circle:|io/questdb/cairo/pool/ReaderPool.java|4|4|100.00%|

**Review by bluestreak01 — APPROVED** [review]

**Pull request merged**
