### PR TITLE
feat(core): use critical level to log all unhandled errors

### PR DESCRIPTION
**Pull request by puzpuzpuz**
With this change, instance log alerting can be based on ` C ` (critical log level) entries instead of ` E ` (error level) which produces lots of false positives.

cc @mariusgheorghies 

Also removes unused `Log#isDebugEnabled()` method and improves code style slightly.

### CODE REVIEW

**Comment by ideoma** [comment]
#### [PR Coverage check]

:heart_eyes: **pass** : 17 / 26 (65.38%)




#### file detail

|   |path|covered line|new line|coverage|
|----|----|----|----|----|
|:large_blue_circle:|io/questdb/cutlass/http/processors/JsonQueryProcessor.java|0|1|00.00%|
|:large_blue_circle:|io/questdb/cutlass/http/processors/JsonQueryProcessorState.java|0|1|00.00%|
|:large_blue_circle:|io/questdb/cutlass/http/processors/TextQueryProcessor.java|0|2|00.00%|
|:large_blue_circle:|io/questdb/cutlass/line/tcp/LineTcpWriterJob.java|2|7|28.57%|
|:large_blue_circle:|io/questdb/cutlass/line/tcp/LineTcpConnectionContext.java|11|11|100.00%|
|:large_blue_circle:|io/questdb/cairo/CairoEngine.java|1|1|100.00%|
|:large_blue_circle:|io/questdb/griffin/engine/groupby/SampleByFirstLastRecordCursorFactory.java|1|1|100.00%|
|:large_blue_circle:|io/questdb/mp/Worker.java|1|1|100.00%|
|:large_blue_circle:|io/questdb/cairo/TableWriter.java|1|1|100.00%|

**Comment by ideoma** [comment]
I'd think critical should also be logged every time we do `distressed = true;` in TableWriter.
Also I think all Throwables but not Exceptions on Worker level are also critical. This would be assertions, OOMs etc.

**Comment by puzpuzpuz** [comment]
> I'd think critical should also be logged every time we do `distressed = true;` in TableWriter.

Tried doing that in 7e89c9074251a0230e093007fd0431bd819c6017

> Also I think all Throwables but not Exceptions on Worker level are also critical. This would be assertions, OOMs etc.

All `Throwable`s are logged already in `Worker`. See `onError` method. As for having an exception for `Exception`s (excuse my tautology), I'd better not have it at least for now. They should be handled on the inner level.

**Comment by puzpuzpuz** [comment]
> One more place to consider is `WriterPool` some `error()` look critical there, say this one

Changed a few log call there in 0c9d2435e998178e110ffa5f50b616d9ffa308cb (the commit also includes some minor improvements)

**Comment by ideoma** [comment]
#### [PR Coverage check]

:heart_eyes: **pass** : 20 / 30 (66.67%)




#### file detail

|   |path|covered line|new line|coverage|
|----|----|----|----|----|
|:large_blue_circle:|io/questdb/cutlass/http/processors/JsonQueryProcessor.java|0|1|00.00%|
|:large_blue_circle:|io/questdb/griffin/SqlCompiler.java|0|1|00.00%|
|:large_blue_circle:|io/questdb/cutlass/http/processors/JsonQueryProcessorState.java|0|1|00.00%|
|:large_blue_circle:|io/questdb/cutlass/http/processors/TextQueryProcessor.java|0|2|00.00%|
|:large_blue_circle:|io/questdb/cutlass/line/tcp/LineTcpWriterJob.java|2|7|28.57%|
|:large_blue_circle:|io/questdb/cutlass/line/tcp/LineTcpConnectionContext.java|11|11|100.00%|
|:large_blue_circle:|io/questdb/cairo/CairoEngine.java|1|1|100.00%|
|:large_blue_circle:|io/questdb/griffin/engine/groupby/SampleByFirstLastRecordCursorFactory.java|1|1|100.00%|
|:large_blue_circle:|io/questdb/cairo/pool/WriterPool.java|2|2|100.00%|
|:large_blue_circle:|io/questdb/mp/Worker.java|1|1|100.00%|
|:large_blue_circle:|io/questdb/cairo/TableWriter.java|2|2|100.00%|

**Review by ideoma — APPROVED** [review]

**Comment by ideoma** [comment]
#### [PR Coverage check]

:heart_eyes: **pass** : 20 / 30 (66.67%)




#### file detail

|   |path|covered line|new line|coverage|
|----|----|----|----|----|
|:large_blue_circle:|io/questdb/cutlass/http/processors/JsonQueryProcessor.java|0|1|00.00%|
|:large_blue_circle:|io/questdb/griffin/SqlCompiler.java|0|1|00.00%|
|:large_blue_circle:|io/questdb/cutlass/http/processors/JsonQueryProcessorState.java|0|1|00.00%|
|:large_blue_circle:|io/questdb/cutlass/http/processors/TextQueryProcessor.java|0|2|00.00%|
|:large_blue_circle:|io/questdb/cutlass/line/tcp/LineTcpWriterJob.java|2|7|28.57%|
|:large_blue_circle:|io/questdb/cutlass/line/tcp/LineTcpConnectionContext.java|11|11|100.00%|
|:large_blue_circle:|io/questdb/cairo/CairoEngine.java|1|1|100.00%|
|:large_blue_circle:|io/questdb/griffin/engine/groupby/SampleByFirstLastRecordCursorFactory.java|1|1|100.00%|
|:large_blue_circle:|io/questdb/cairo/pool/WriterPool.java|2|2|100.00%|
|:large_blue_circle:|io/questdb/mp/Worker.java|1|1|100.00%|
|:large_blue_circle:|io/questdb/cairo/TableWriter.java|2|2|100.00%|

**Pull request merged**
