### PR TITLE
fix(sql): fix TableReader metadata open when columns are added frequently

### PR DESCRIPTION
**Pull request by ideoma**
Fixes this error from CI

```
2022-10-06T10:18:42.7683627Z 2022-10-06T10:18:42.719293Z I i.q.c.TableWriter ADDED column 'col428[SYMBOL], name txn 639 to /tmp/junit4122981112622880555/dbRoot/tbl_meta_test
2022-10-06T10:18:42.7684649Z 2022-10-06T10:18:42.720608Z E i.q.c.AbstractCairoTest 
2022-10-06T10:18:42.7685393Z io.questdb.cairo.CairoException: [0] File is too small, size=20480, required=20490
2022-10-06T10:18:42.7686143Z 	at io.questdb.cairo.CairoException.critical(CairoException.java:89)
2022-10-06T10:18:42.7686904Z 	at io.questdb.cairo.TableUtils.getCharSequence(TableUtils.java:1194)
2022-10-06T10:18:42.7687656Z 	at io.questdb.cairo.TableUtils.getColumnName(TableUtils.java:1177)
2022-10-06T10:18:42.7688394Z 	at io.questdb.cairo.TableUtils.validateMeta(TableUtils.java:1032)
2022-10-06T10:18:42.7689159Z 	at io.questdb.cairo.TableReaderMetadata.deferredInit(TableReaderMetadata.java:178)
2022-10-06T10:18:42.7689937Z 	at io.questdb.cairo.TableReader.openMetaFile(TableReader.java:758)
2022-10-06T10:18:42.7690925Z 	at io.questdb.cairo.TableReader.<init>(TableReader.java:99)
2022-10-06T10:18:42.7691715Z 	at io.questdb.cairo.pool.ReaderPool$R.<init>(ReaderPool.java:383)
2022-10-06T10:18:42.7692576Z 	at io.questdb.cairo.pool.ReaderPool.get(ReaderPool.java:93)
2022-10-06T10:18:42.7693302Z 	at io.questdb.cairo.CairoEngine.getReader(CairoEngine.java:272)
2022-10-06T10:18:42.7694038Z 	at io.questdb.cairo.CairoEngine.getReader(CairoEngine.java:262)
2022-10-06T10:18:42.7694892Z 	at io.questdb.cairo.TableReaderTest.lambda$testAddColumnPartitionConcurrentCreateReader$46(TableReaderTest.java:1628)
2022-10-06T10:18:42.7695701Z 	at java.lang.Thread.run(Thread.java:829)
2022-10-06T10:18:43.3785985Z 2022-10-06T10:18:43.360687Z I i.q.c.TableWriter adding column 'col429[SYMBOL], name txn 641 to 
```

by reading file length by file descriptor after opening the file.

When table metadata file is frequently updated, a new file is created and swap-renamed to the name _meta. When TableReader opens metadata file it could read file length of the different version of metadata resulting to the above error

### CODE REVIEW

**Review by puzpuzpuz — APPROVED** [review]
Nice catch!

**Comment by ideoma** [comment]
#### [PR Coverage check]

:heart_eyes: **pass** : 4 / 5 (80.00%)




#### file detail

|   |path|covered line|new line|coverage|
|----|----|----|----|----|
|:large_blue_circle:|io/questdb/cairo/vm/MemoryCMRImpl.java|4|5|80.00%|

**Comment by ideoma** [comment]
#### [PR Coverage check]

:heart_eyes: **pass** : 4 / 5 (80.00%)




#### file detail

|   |path|covered line|new line|coverage|
|----|----|----|----|----|
|:large_blue_circle:|io/questdb/cairo/vm/MemoryCMRImpl.java|4|5|80.00%|

**Review by bluestreak01 — APPROVED** [review]

**Comment by bluestreak01** [comment]
@ideoma do you think these issues had the same cause ?

https://github.com/questdb/questdb/issues/1912
https://github.com/questdb/questdb/issues/2340

?

**Pull request merged**
